### ISSUE TITLE
[BUG] Encrypted Volume does not expand beyond 15.5Ti

### ISSUE THREAD

**Issue by davidfrickert** [longhorn/longhorn#7174] opened 2023-11-22 09:56 UTC
## Describe the bug (🐛 if you encounter this issue)

A volume of mine has failed expanding and is now on attach-detach loop. What to do?

```
Engine failed or partially failed to expand the size at 2023-11-22T09:20:21.159044598Z: the expansion failed since all replica expansion failed: tcp://10.42.0.198:10040: error: code = ResultUnknown, message = failed to expand replica 10.42.0.198:10040 from remote: failed to unmarshal gRPC error message, gRPC err: rpc error: code = DeadlineExceeded desc = context deadline exceeded, json error: invalid character 'c' looking for beginning of value
```

The volume is saying that it has 0 bytes and in the filesystem it checks out. Its probably irrecoverable, which I don't mind since I was migrating data from another volume to move it to another disk - since setting up a replica for a 15TB volume does not work for me as it always faults in the middle of it and starts over, never completing. But I would like to leave the issue here to see if there's some process that might be improved or guideline on volume expansion.

Don't know if relevant but the fs of the volume was at 100% usage.

## To Reproduce

A bit difficult but attempt a volume expansion which fails.

## Expected behavior

Volume expansion doesn't fail or if it fails, volume is recovered.

## Support bundle for troubleshooting

https://drive.google.com/file/d/1RrlKyeDOD52VqbKfIuAL8DgxnqMETDbn/view?usp=sharing

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s 1.26
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Fedora 38
   - Kernel version: 6.5.10-200.fc38.x86_64
   - CPU per node: 4 
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 20
 - Impacted Longhorn resources: Volume with failed expansion
   - Volume names: pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec

**Comment by innobead** [comment] 2023-11-22 10:26
cc @ejweber

**Comment by ejweber** [comment] 2023-11-22 22:00
So far, from the support bundle, it's not clear that the expansion caused this issue, but we can see that it has been requested.

From the logs, every time we try to attach the volume:

```
2023-11-22T10:48:05.318560640+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=info msg="Creating instance" backendStoreDriver=v1 name=pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54 type=engine
2023-11-22T10:48:05.318564636+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=info msg="Creating process" args="[controller pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec --frontend tgt-blockdev --salvageRequested --size 18640158064640 --current-size 16492674416640 --engine-replica-timeout 8 --file-sync-http-client-timeout 30 --unmap-mark-snap-chain-removed --replica tcp://10.42.0.221:10290]" binary=/engine-binaries/longhornio-longhorn-engine-v1.5.1/longhorn name=pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54 portArgs="[--listen,0.0.0.0:]" portCount=1
2023-11-22T10:48:05.322158944+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=info msg="Process Manager: prepare to create process pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54"
2023-11-22T10:48:05.322166294+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=debug msg="Process Manager: validate process path: /engine-binaries/longhornio-longhorn-engine-v1.5.1/longhorn dir: /engine-binaries/ image: longhornio-longhorn-engine-v1.5.1 binary: longhorn"
2023-11-22T10:48:05.322168880+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=info msg="Process Manager: created process pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54"
2023-11-22T10:48:05.336763976+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54] time="2023-11-22T09:48:05Z" level=info msg="Creating volume pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec controller with iSCSI target request timeout 15s and engine to replica(s) timeout 8s"
2023-11-22T10:48:05.343944232+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54] time="2023-11-22T09:48:05Z" level=info msg="Starting with replicas [\"tcp://10.42.0.221:10290\"]"
2023-11-22T10:48:05.343961213+01:00 time="2023-11-22T09:48:05Z" level=info msg="Connecting to remote: 10.42.0.221:10290 (tcp)"
2023-11-22T10:48:05.359690186+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54] time="2023-11-22T09:48:05Z" level=info msg="Opening remote: 10.42.0.221:10290"
2023-11-22T10:48:05.359704065+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-r-f2d5b484] time="2023-11-22T09:48:05Z" level=info msg="New connection from: 10.42.0.221:50486"
2023-11-22T10:48:05.365013624+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-r-f2d5b484] time="2023-11-22T09:48:05Z" level=info msg="Opening replica: dir /host/media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07, size 16492674416640, sector size 512"
2023-11-22T10:48:05.420900755+01:00 [pvc-560a5743-4646-4c75-bde0-8c8120987f4c-e-b835547f] time="2023-11-22T09:48:05Z" level=info msg="Connecting to remote: 10.42.0.221:10300 (tcp)"
2023-11-22T10:48:05.429835869+01:00 [pvc-560a5743-4646-4c75-bde0-8c8120987f4c-e-b835547f] time="2023-11-22T09:48:05Z" level=info msg="Opening remote: 10.42.0.221:10300"
2023-11-22T10:48:05.429852417+01:00 [pvc-560a5743-4646-4c75-bde0-8c8120987f4c-r-efb7d8b5] time="2023-11-22T09:48:05Z" level=info msg="New connection from: 10.42.0.221:54118"
2023-11-22T10:48:05.429855393+01:00 time="2023-11-22T09:48:05Z" level=info msg="Opening replica: dir /host/media/external/longhorn/replicas/pvc-560a5743-4646-4c75-bde0-8c8120987f4c-4354bb87, size 107374182400, sector size 512"
2023-11-22T10:48:05.488317271+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54] time="2023-11-22T09:48:05Z" level=warning msg="Failed to create backend with address tcp://10.42.0.221:10290" error="failed to open replica 10.42.0.221:10290 from remote: rpc error: code = Unknown desc = error: code = FunctionFailedRollbackSucceeded, message = failed to create new disk 000: volume-head-001.img already exists"
2023-11-22T10:48:05.488337559+01:00 time="2023-11-22T09:48:05Z" level=info msg="Adding backend: tcp://10.42.0.221:10290"
2023-11-22T10:48:05.488348370+01:00 time="2023-11-22T09:48:05Z" level=error msg="no available backend due to replica error from the addresses [tcp://10.42.0.221:10290]"
2023-11-22T10:48:05.488351472+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=info msg="Wait for gRPC service of process pvc-7bfe9d26-a374-47e8-a8c8-b04c9e84daba-e-71d279f3 to start at localhost:10312"
2023-11-22T10:48:05.488353726+01:00 [pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-r-f2d5b484] time="2023-11-22T09:48:05Z" level=info msg="Starting to create disk" disk=000
2023-11-22T10:48:05.488355913+01:00 time="2023-11-22T09:48:05Z" level=error msg="Failed to create disk 000, will do rollback" disk=000 error="volume-head-001.img already exists"
2023-11-22T10:48:05.488358146+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=info msg="Process Manager: process pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54 error out, error msg: exit status 61"
2023-11-22T10:48:05.488360385+01:00 [longhorn-instance-manager] time="2023-11-22T09:48:05Z" level=warning msg="Process update: pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-e-b767fb54: state error: errorMsg: exit status 61"
```

It's possible that this was occurring before (or that we captured something else interesting), but most of the Longhorn-associated containers restarted less than a minute before this first instance, so anything else is lost.

It looks like we are probably missing some metadata from `/media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07`. We appear to be unable to find relevant <disk>.meta files, so we continually attempt to createDisk "000".

https://github.com/longhorn/longhorn-engine/blob/0d8e42d0c74b1d0430e56efa1e8247c55f34cef3/pkg/replica/replica.go#L223-L227

However, we do have a volume-head-001.img file, which the replica process doesn't expect, so it crashes out.

I do see a lot of dmesg I/O errors relating to out of space issues. They are probably related to Longhorn file systems being out of space, but it is difficult to confirm with just the dmesg logs.

@davidfrickert:

- Can you confirm that the file system containing /media/data/longhorn still has plenty of space (`df -h /media/data/longhorn`)?
- Can you provide a list of all the files in /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07 (`ls -al  /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07`)?
- Can you provide the contents of all the .meta files in /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07 (`grep "" /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07/*.meta)?

It looks like all the volumes in this cluster are encrypted. That may be important context, but I'm not sure yet.

**Comment by davidfrickert** [comment] 2023-11-22 22:14
Thanks for looking into it @ejweber 

> Can you confirm that the file system containing /media/data/longhorn still has plenty of space (df -h /media/data/longhorn)?

Yes, there is plenty of space:

```
davidjf@shiverpeaks ~> df -h /media/data/longhorn
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda1        37T  673G   34T   2% /media/data
```

> Can you provide a list of all the files in /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07 (ls -al  /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07)?

Sure:

```
[root@shiverpeaks davidjf]# ls -al  /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07
total 16
drwx------  2 root root 4096 Nov 22 10:17 .
drwxr-xr-x 24 root root 4096 Nov 22 00:09 ..
-rw-------  1 root root 4096 Nov 22 10:16 revision.counter
-rw-r--r--  1 root root    0 Nov 22 10:17 volume-head-001.img
-rw-r--r--  1 root root  146 Nov 22 00:57 volume.meta
```

> Can you provide the contents of all the .meta files in /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07 (`grep "" /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07/*.meta)?

Sure:
```
[root@shiverpeaks davidjf]# grep "" /media/data/longhorn/replicas/pvc-e19d261c-0fe8-41b0-81ea-bf9287d278ec-ed433d07/*.meta
{"Size":16492674416640,"Head":"volume-head-000.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"","SectorSize":512,"BackingFilePath":""}
```

All volumes are encrypted yes. Also, there was an option available to stop the volume expansion on the UI which I tried, and it didn't help. Still on the loop, but now reports Size 15Ti instead of 17Ti.

I did delete every pod after the issue to see if it helped, which in hindsight was not a great idea. 

I don't mind if this is irrecoverable, as I have the data still in another volume and can just resume migration from 0. Just wanted to see if this could lead to some bugfix / improvement.

**Comment by ejweber** [comment] 2023-11-22 23:29
Really appreciate it @davidfrickert! I will be out for the next few days for a US holiday. Not sure if other team members will have a chance to take a look. If you can keep this directory and volume around in case there are other things to look at, that will be helpful. I totally understand if you can't though!

**Comment by davidfrickert** [comment] 2023-11-23 05:39
No worries.

Sure, I can leave the files around as at this point they aren't using any space. Enjoy your vacation!

**Comment by ejweber** [comment] 2023-11-27 22:37
Yes, in this function, we look for any `*.meta` files (e.g. `volume-head-000.img.meta`). There are none in your replica directory, so we return `exists == false`.

https://github.com/longhorn/longhorn-engine/blob/0d8e42d0c74b1d0430e56efa1e8247c55f34cef3/pkg/replica/replica.go#L1034-L1060

This causes us to try to create disk "000".

According to your `volume.meta`, an `oldHead` named `volume-head-000.img` exists, so in the following lines we try to create `volume-head-001.img`. This file DOES exist (though it is empty), so we fail out.

https://github.com/longhorn/longhorn-engine/blob/0d8e42d0c74b1d0430e56efa1e8247c55f34cef3/pkg/replica/replica.go#L675-L682

Most of this analysis is not very useful. It gets at why we are responding the way we are NOW, but the fact is, this replica directory was broken previously, maybe by the expansion operation, in a way we don't expect.

@shuo-wu, @derekbit, can you think of a way the directory could have ended up this way?

**Comment by davidfrickert** [comment] 2023-12-17 20:16
okay... i'm not sure if you're back @ejweber but it happened again.
and i was kinda already thinking I had lost all the data which would be really annoying.

Support bundle: https://drive.google.com/file/d/1vskJMqpYtKyJ9HLueUljRVJjBqzIY3i2/view?usp=sharing

But I managed to fix it somehow.. Here's more or less what happened:

- I tried to expand volume from 15TB to 16TB - volume was at about 98% usage with 250gb left.
- expansion failed
- Volume went into attach - fault - autosalvage loop
- I looked into the files, I realized that there was a volume-head-005.img, without metadata, and the volume.meta expected head to be volume-head-004.img
- I copied volume-head-005.img to volume-head-004.img (empty)
- I created volume-head-004.img.meta, basically copied from another volume and replaced "Name" and "Parent" to match the proper ones in this volume
- then rescaled deployments for the volume to be used, and that seems to have fixed it

so.. really glad that i didn't lose all my data, but i kinda want to expand this volume, could you or someone in the team look into this?

**Comment by davidfrickert** [comment] 2023-12-18 20:17
```
time="2023-12-18T20:15:09Z" level=info msg="Starting to create disk" disk=expand-17592186044416
[pvc-216efdca-dde8-4791-8899-ec86dfd72391-r-42b71492] time="2023-12-18T20:15:09Z" level=info msg="Removing disk volume-head-009.img"
[pvc-216efdca-dde8-4791-8899-ec86dfd72391-r-42b71492] panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0xa039e7]

goroutine 69800 [running]:
github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead.func1.1()
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:698 +0x47
github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead.func1()
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:706 +0x11b
github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead(0xc0000ee120, {0xc119ad2270, 0x13}, {0xc00003aa50, 0x25}, {0xc119ad2318, 0x14}, 0xc00004a500?)
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:712 +0x5fe
github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createDisk(0xc0000ee120, {0xc119ad2300, 0x15}, 0x0, {0xc119ad2318, 0x14}, 0xc0000b0570, 0x100000000000)
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:905 +0x436
github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).Expand(0xc0000ee120, 0x100000000000)
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:1208 +0x1bf
github.com/longhorn/longhorn-engine/pkg/replica.(*Server).Expand(0xc000131ef0, 0xc000248788?)
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/server.go:208 +0xec
github.com/longhorn/longhorn-engine/pkg/replica/rpc.(*ReplicaServer).ReplicaExpand(0xc0000aa018, {0xc0000b04e0?, 0x513f26?}, 0x0?)
	/go/src/github.com/longhorn/longhorn-engine/pkg/replica/rpc/server.go:173 +0x2b
github.com/longhorn/longhorn-engine/proto/ptypes._ReplicaService_ReplicaExpand_Handler({0xfe1120?, 0xc0000aa018}, {0x11fa390, 0xc0000b04b0}, 0xc00014c930, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/proto/ptypes/replica.pb.go:1929 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0000d0000, {0x11fe320, 0xc0004fc680}, 0xc0000ee7e0, 0xc0000b0210, 0x185cd00, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1336 +0xd33
google.golang.org/grpc.(*Server).handleStream(0xc0000d0000, {0x11fe320, 0xc0004fc680}, 0xc0000ee7e0, 0x0)
	/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1704 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.2()
	/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:963 +0x28a
[pvc-216efdca-dde8-4791-8899-ec86dfd72391-e-2b7090ee] time="2023-12-18T20:15:09Z" level=info msg="All replica expansion failed and some replica rollback failed: tcp://10.42.0.181:10145: error: code = ResultUnknown, message = failed to expand replica 10.42.0.181:10145 from remote: failed to unmarshal gRPC error message, gRPC err: rpc error: code = Unavailable desc = error reading from server: EOF, json error: invalid character 'e' looking for beginning of value"
time="2023-12-18T20:15:09Z" level=error msg="Setting replica tcp://10.42.0.181:10145 to ERR" error="tcp://10.42.0.181:10145: error: code = ResultUnknown, message = failed to expand replica 10.42.0.181:10145 from remote: failed to unmarshal gRPC error message, gRPC err: rpc error: code = Unavailable desc = error reading from server: EOF, json error: invalid character 'e' looking for beginning of value"
time="2023-12-18T20:15:09Z" level=info msg="Setting replica tcp://10.42.0.181:10145 to mode ERR"
time="2023-12-18T20:15:09Z" level=error msg="I/O error" error="tcp://10.42.0.181:10145: error: code = ResultUnknown, message = failed to expand replica 10.42.0.181:10145 from remote: failed to unmarshal gRPC error message, gRPC err: rpc error: code = Unavailable desc = error reading from server: EOF, json error: invalid character 'e' looking for beginning of value"
time="2023-12-18T20:15:09Z" level=error msg="Failed to handle the backend expansion errors" error="tcp://10.42.0.181:10145: error: code = ResultUnknown, message = failed to expand replica 10.42.0.181:10145 from remote: failed to unmarshal gRPC error message, gRPC err: rpc error: code = Unavailable desc = error reading from server: EOF, json error: invalid character 'e' looking for beginning of value"
[pvc-216efdca-dde8-4791-8899-ec86dfd72391-e-2b7090ee] time="2023-12-18T20:15:09Z" level=info msg="Controller failed to expand from size 17042430230528 to 17592186044416"
```

Okay here's relevant logs.

Now more weird stuff:

I've tried to expand from 15Ti to 15.5Ti. All good. it expands

Then I try to expand to 16Ti and it fails with the logs above. weird.

**Comment by ejweber** [comment] 2023-12-22 16:48
This analysis is GREAT @davidfrickert! So the reproduce steps are:

No issue:

- Create a 15 TiB encrypted volume.
- Expand it to 15.5 TiB.
- Observe no issues.

Issue:

- Create a 15 TiB encrypted volume.
- Expand it to 16 TiB.
- Either the replica process crashes or the entire instance-manager-r crashes due to a SIGSEGV.
- Because it is a SIGSEV instead of some error we can handle, we don't do a rollback, leaving the replica broken.

**Comment by ejweber** [comment] 2023-12-22 16:50
Since it sounds like you can repeat it, are you able to do so if the volume is NOT encrypted?

**Comment by ejweber** [comment] 2023-12-22 17:13
This is even easier to reproduce than I expected. It looks like there's some (hidden?) limit to the maximum volume size in Longhorn.

- I created a 16384 GiB (16 TiB) volume in my cluster and tried to attach it to a node. It failed with a SIGSEGV.
- I created a 16383 GiB (16 TiB - 1 GiB) volume in my cluster and tried to attach it to a node. It attached successfully.

For the failed volume:

```
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] [test-way-too-big-r-030f144e] time="2023-12-22T17:10:14Z" level=info msg="Starting to create disk" func="replica.(*Replica).createDisk" file="replica.go:863" disk=000
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] [test-way-too-big-r-030f144e] time="2023-12-22T17:10:14Z" level=error msg="Caught FATAL error:  runtime error: invalid memory address or nil pointer dereference" func=main.ResponseLogAndError file="main.go:50"
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] goroutine 1 [running]:
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] runtime/debug.Stack()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /usr/local/go/src/runtime/debug/stack.go:24 +0x5e
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] runtime/debug.PrintStack()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /usr/local/go/src/runtime/debug/stack.go:16 +0x13
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.ResponseLogAndError({0xee5020?, 0x18e4e50?})
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:51 +0x30a
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.cleanup()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:59 +0x54
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] panic({0xee5020?, 0x18e4e50?})
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /usr/local/go/src/runtime/panic.go:914 +0x21f
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead.func1.1()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:698 +0x4b
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead.func1()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:706 +0x11f
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createNewHead(0xc00051c000, {0x0, 0x0}, {0x0, 0x0}, {0xc000040030, 0x14}, 0x0?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:712 +0x633
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Replica).createDisk(0xc00051c000, {0x1024b2d, 0x3}, 0x0, {0xc000040030, 0x14}, 0x0, 0x100000000000)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:905 +0x496
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.construct(0x4?, 0x100000000000, 0x200, {0x7ffc84b54518, 0x39}, {0x0, 0x0}, 0x0, 0x0, 0x0)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:224 +0x557
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.New(...)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/replica.go:145
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/pkg/replica.(*Server).Create(0xc000090960, 0xe?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/pkg/replica/server.go:53 +0x2cd
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/app/cmd.startReplica(0xc000470c60)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/app/cmd/replica.go:110 +0x26d
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/longhorn/longhorn-engine/app/cmd.ReplicaCmd.func1(0xc000470c60?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/app/cmd/replica.go:78 +0x1d
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/urfave/cli.HandleAction({0xe80c20?, 0x108dc78?}, 0x7?)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:526 +0x75
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/urfave/cli.Command.Run({{0x1027b1d, 0x7}, {0x0, 0x0}, {0x0, 0x0, 0x0}, {0x0, 0x0}, {0x1047630, ...}, ...}, ...)
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/command.go:173 +0x63e
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] github.com/urfave/cli.(*App).Run(0xc0000e9500, {0xc00012e1a0, 0xd, 0xd})
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/vendor/github.com/urfave/cli/app.go:277 +0xb07
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.longhornCli()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:153 +0x27ba
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] main.main()
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb]     /go/src/github.com/longhorn/longhorn-engine/main.go:34 +0xb6
[instance-manager-cb8ea04b1204debf53e18db4ba29e6fb] Caught FATAL error:  runtime error: invalid memory address or nil pointer dereference
```

![image](https://github.com/longhorn/longhorn/assets/24213029/8bd869c3-ed09-4ff7-b686-6556ad5571a0)

Checking whether we document anywhere that this is some kind of hard limit.

We need to:

- Understand where/how exactly we SIGSEGV.
- Either:
  - Prevent the SIGSEGV somehow, or
  - Reject any operation that would result in a 16TiB or larger.

**Comment by ejweber** [comment] 2023-12-22 17:17
- https://github.com/longhorn/longhorn/issues/4768
- https://github.com/longhorn/longhorn/issues/2509

**Comment by ejweber** [comment] 2023-12-22 17:23
```
root@eweber-v126-worker-9c1451b4-kgxdq:~# df -T /
Filesystem     Type 1K-blocks    Used Available Use% Mounted on
/dev/vda1      ext4 162406320 8447280 153942656   6% /

root@eweber-v126-worker-9c1451b4-kgxdq:~# truncate -s 16T too_big
truncate: failed to truncate 'too_big' at 17592186044416 bytes: File too large

root@eweber-v126-worker-9c1451b4-kgxdq:~# truncate -s 16384G too_big
truncate: failed to truncate 'too_big' at 17592186044416 bytes: File too large

root@eweber-v126-worker-9c1451b4-kgxdq:~# truncate -s 16383G not_too_big
# No failure.
```

It seems that this is indeed a limitation of using ext4 as the underlying file system. A user in the above-linked issues switched to an underlying XFS file system and had success.

**Comment by davidfrickert** [comment] 2023-12-22 17:40
I see.. that sounds quite weird indeed, it would be nice to check why this condition exists and document it plus develop a plan to remove this limitation!

**Comment by ejweber** [comment] 2023-12-22 17:47
> I see.. that sounds quite weird indeed, it would be nice to check why this condition exists and document it plus develop a plan to remove this limitation!

I think we cannot remove this limitation in Longhorn. Fundamentally, v1 volumes work by creating sparse files that are the size of the volume you want. Even though we do not populate them with data until the workload writes some, the underlying file system must allow a file of the correct size to be created.

I think the ultimate solution is either `xfs` or (eventually) the v2 engine. The v2 engine does not operate on top of a mounted file system, so this limitation will not exist.

Will you check https://github.com/longhorn/longhorn/issues/7423 and consider closing this issue out in favor of that one? Now that we know the real cause of the failure, I think it would be clearest to continue there.

**Comment by davidfrickert** [comment] 2023-12-22 17:48
Will do. Thanks @ejweber for looking into it.

**Closed** 2023-12-22 17:49 UTC
Labels: kind/bug, require/qa-review-coverage, require/backport

**Comment by ejweber** [comment] 2023-12-22 17:51
> Will do. Thanks @ejweber for looking into it.

Huge thanks to you as well @davidfrickert. If you hadn't continued your analysis and determined the threshold over which the expansion would fail, I'd still be spinning my wheels.
