### ISSUE TITLE
[Question] Error upgrading to latest with helm

### ISSUE THREAD

**Issue by mckernanin** [longhorn/longhorn#2371] opened 2021-03-17 16:43 UTC
**Question**

**Environment:**
 - Longhorn version: longhorn-1.0.2
 - Kubernetes version: 1.19.8
 - Node config
   - OS type and version: Ubuntu server 20.04
   - CPU per node: 4c/8t i7 7700k
   - Memory per node: 16
   - Disk type: m.2 SSD
   - Network bandwidth and latency between the nodes: home gigabit network
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): microk8s

**Additional context**
I'm trying to upgrade longhorn, and I'm getting the following error from helm 3:
```
❯ helm upgrade longhorn ./longhorn/chart --namespace longhorn-system
Error: UPGRADE FAILED: rendered manifests contain a new resource that already exists. Unable to continue with update: existing resource conflict: kind: CustomResourceDefinition, namespace: , name: settings.longhorn.io
```

**Comment by cclhsu** [comment] 2021-03-18 05:25
Not sure if this helm related issue as in https://github.com/helm/helm/issues/7697.  Can you provide your helm version? If possible, provide log for `helm upgrade longhorn ./longhorn/chart --namespace longhorn-system --debug -v 10`?

**Comment by shuo-wu** [comment] 2021-04-27 01:51
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by shuo-wu** 2021-04-27 01:51 UTC
