### ISSUE TITLE
Needlessly difficult to parse logs

### ISSUE THREAD

**Issue by summed** [longhorn/longhorn#1494] opened 2020-06-15 09:54 UTC
*Can there be a way of changing the log-output-format to a machine-friendlier format, like JSON?*

This would ease ingestion to logging systems like fluentd, datadog etc...

I am unsure of the exact contribution process, as I couldn't find much info on https://longhorn.io/docs/1.0.0/contributing/ I'll cross-reference a proposal PR in the discussion to this issue.

---
version: `1.0.0`

**Comment by summed** [comment] 2020-06-15 09:55
PR here: https://github.com/longhorn/longhorn-manager/pull/605

**Comment by shuo-wu** [comment] 2020-06-15 15:00
Thank you for your contribution! I am not sure if there is a standard contribution process/workflow.   We will discuss it with @yasker later.

For now, I think you can follow this simple workflow for the contribution:
1. Analyze and implement the feature. 
2. Manually test the feature and write down the test step here.
3. Create the PR. Write a summary in the PR or in the commit if the PR/commit is not straightforward. For your commit, I think adding `longhorn #1494` in the commit is enough.
4. Check if an integration test is needed. If YES, we also need to review the test PR before merging. I think we don't need the integration test for this feature.
5. Wait for our QA's validation and feedback.

If you have any questions, feel free to ask us.

**Comment by yasker** [comment] 2020-06-23 20:18
@summed Thanks for the contribution!

Since it's a small PR and has no side effort on other parts of Longhorn, I am planning to include it in the v1.0.1 release.

We're using ZenHub for project management. You can download the browser extension [here](https://www.zenhub.com/extension) (no need to register).

Before we move this issue to the merge, the contributor needs to finish the pre-merge checklist. I will post it in the next comment. Once the checklist is completed, we can move the issue to the `merged` column and our QA will pick up from there for testing.

**Comment by yasker** [comment] 2020-06-23 20:18
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] Which areas/issues this PR might have potential impacts on?
Area
Issues

* [ ] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [ ] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~ 

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by summed** [comment] 2020-06-25 15:05
@yasker Ok, let me have a stab at this checklist.


> Does the PR include the explanation for the fix or the feature?

Think most/all has been explained in my initial PR comment.

> Is the backend code merged?

I have just PR synced with upstream/master bc77aeccd90496384e1a84e185a9eb6e7076e6f4

> Is the reproduce steps/test steps documented?

I'm unsure if this is wanted for this. But basically running the longhorn-manager with "-j" argument should be enough.

> Which areas/issues this PR might have potential impacts on?
- Longhorn-manager process argument and/or environment variable parsing.
- As I'm a little rusty on logrus usage, I suppose there might some issue logging commands/output. Although I doubt it.

> If labeled: require/automation-e2e Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?

_No. I'm unsure if needed._

> if labeled: require/manual-test-plan Has the manual test plan been documented?

_No. I'm unsure if needed._

**Comment by yasker** [comment] 2020-07-02 21:23
To verify, run the manager with `-j` parameter and the log output should be in JSON format.

**Comment by khushboo-rancher** [comment] 2020-07-06 23:12
Verified in master - 07-06-2020

Validation - **Passed**

With ```-j``` parameter, the output of manager's logs is in JSON format.
It appears as below:
```
[longhorn-manager-ht78z] {"level":"debug","msg":"Instance vol2-e-e0c7d9c5 starts running, IP 10.42.1.19","time":"2020-07-06T23:08:01Z"} 
[longhorn-manager-ht78z] {"level":"debug","msg":"Instance vol2-e-e0c7d9c5 starts running, Port 10000","time":"2020-07-06T23:08:01Z"} 
[longhorn-manager-ht78z] {"level":"debug","msg":"Instance handler updated instance vol2-e-e0c7d9c5 state, old state starting, new state running","time":"2020-07-06T23:08:01Z"} 
[longhorn-manager-ht78z] {"level":"debug","msg":"Start monitoring vol2-e-e0c7d9c5","time":"2020-07-06T23:08:01Z"} 
[longhorn-manager-ht78z] {"level":"info","msg":"Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"vol2\", UID:\"cd7f1de8-9bec-4000-8efc-963c28d80141\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"62087\", FieldPath:\"\"}): type: 'Normal' reason: 'Attached' volume vol2 has been attached to khushboo-test-wk3","time":"2020-07-06T23:08:01Z"} 
```

**Closed by khushboo-rancher** 2020-07-06 23:12 UTC
Labels: area/manager, enhancement, priority/3
