### ISSUE TITLE
Replicas error

### ISSUE THREAD

**Issue by tiger0425** [longhorn/longhorn#675] opened 2019-08-06 02:49 UTC
replica status is stop ,no rebuilding,pod report error
time="2019-08-06T02:45:12Z" level=error msg="Error in request: Failed to find metadata for volume-snap-c-rdofl3-153e4e48.img"

time="2019-08-06T01:57:36Z" level=info msg="Done running ssync [ssync -port 9780 -daemon volume-snap-c-2fv2en-8101389c.img.meta]"
time="2019-08-06T01:57:36Z" level=info msg="Running ssync [ssync -port 9781 -daemon volume-snap-c-2fv2en-b28845f6.img]"
time="2019-08-06T01:57:36Z" level=info msg="Creating Ssync service"
time="2019-08-06T01:57:37Z" level=info msg="open: receiving fileSize: 858993459200, setting up directIo: true"
time="2019-08-06T01:57:37Z" level=info msg="Ssync server opened and ready"
time="2019-08-06T03:09:28Z" level=info msg="Closing volume"
10.42.4.230 - - [06/Aug/2019:03:09:28 +0000] "POST /v1/replicas/1?action=close HTTP/1.1" 200 808 "" "Go-http-client/1.1"
time="2019-08-06T03:09:34Z" level=info msg="Opening volume /volume, size 858993459200/512"
time="2019-08-06T03:09:34Z" level=error msg="Error in request: Failed to find metadata for volume-snap-c-2fv2en-b28845f6.img"
10.42.4.217 - - [06/Aug/2019:03:09:34 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 500 209 "" "Go-http-client/1.1"
time="2019-08-06T03:10:06Z" level=info msg="Opening volume /volume, size 858993459200/512"
time="2019-08-06T03:10:06Z" level=error msg="Error in request: Failed to find metadata for volume-snap-c-2fv2en-b28845f6.img"
10.42.4.217 - - [06/Aug/2019:03:10:06 +0000] "POST /v1/replicas/1?action=open HTTP/1.1" 500 209 "" "Go-http-client/1.1"

time="2019-08-06T03:22:03Z" level=info msg="Done running ssync [ssync -port 9718 -daemon volume-snap-c-9omgr9-8dd9b047.img.meta]"
time="2019-08-06T03:22:04Z" level=info msg="Running ssync [ssync -port 9719 -daemon volume-snap-c-9omgr9-86292196.img]"
time="2019-08-06T03:22:04Z" level=info msg="Creating Ssync service"
time="2019-08-06T03:22:04Z" level=info msg="open: receiving fileSize: 858993459200, setting up directIo: true"
time="2019-08-06T03:22:04Z" level=info msg="Ssync server opened and ready"
time="2019-08-06T03:22:11Z" level=info msg="Ssync server exit(0)"
time="2019-08-06T03:22:11Z" level=info msg="Done running ssync [ssync -port 9719 -daemon volume-snap-c-9omgr9-86292196.img]"
time="2019-08-06T03:22:11Z" level=info msg="Running ssync [ssync -port 9720 -daemon volume-snap-c-9omgr9-86292196.img.meta]"
time="2019-08-06T03:22:11Z" level=info msg="Creating Ssync service"
time="2019-08-06T03:22:11Z" level=info msg="open: receiving fileSize: 181, setting up directIo: false"
time="2019-08-06T03:22:11Z" level=info msg="Ssync server opened and ready"
time="2019-08-06T03:22:11Z" level=info msg="Ssync server exit(0)"
longhorn 0.5.0

**Comment by yasker** [comment] 2019-08-06 18:59
Mark as duplicate of #413

**Closed by yasker** 2019-08-06 18:59 UTC
