### ISSUE TITLE
[BUG] Replica should reported `stopped` if the instance manager cannot be found

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1118] opened 2020-03-17 19:53 UTC
**Describe the bug**
Related to https://github.com/longhorn/longhorn/issues/1071

It seems if replica cannot find the instance manager, the reconciliation process shouldn't be blocked. Instead, the replica should report stopped and then Longhorn should continue on cleaning up things.

Missing instance manager pod seems due to the eviction.

**To Reproduce**
[TO BE ADDED]

**Expected behavior**
The replica should be marked as `stopped` if it failed to sync due to missing instance manager pod.

**Log**
From log:
```
logs/longhorn-manager-lbx4g/longhorn-manager.log:2020-02-23T23:33:34.986388398Z E0223 23:33:34.986271       1 replica_controller.go:178] fail to sync replica for longhorn-system/sfpl-prod-file-service-r-4103790a: failed to get instance manager for instance sfpl-prod-file-service-r-4103790a: cannot find instance manager by node=agent-2, engineImage=ei-ec95b5ad, type=replica
logs/longhorn-manager-lbx4g/longhorn-manager.log:2020-02-23T23:33:34.988611706Z time="2020-02-23T23:33:34Z" level=warning msg="Dropping Longhorn replica longhorn-system/sfpl-prod-file-service-r-4103790a out of the queue: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-4103790a: failed to get instance manager for instance sfpl-prod-file-service-r-4103790a: cannot find instance manager by node=agent-2, engineImage=ei-ec95b5ad, type=replica"
logs/longhorn-manager-lbx4g/longhorn-manager.log:2020-02-23T23:34:05.016686408Z time="2020-02-23T23:34:05Z" level=warning msg="Error syncing Longhorn replica longhorn-system/sfpl-prod-file-service-r-4103790a: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-4103790a: failed to get instance manager for instance sfpl-prod-file-service-r-4103790a: cannot find instance manager by node=agent-2, engineImage=ei-ec95b5ad, type=replica"
logs/longhorn-manager-lbx4g/longhorn-manager.log:2020-02-23T23:34:05.060095132Z time="2020-02-23T23:34:05Z" level=warning msg="Error syncing Longhorn replica longhorn-system/sfpl-prod-file-service-r-4103790a: fail to sync replica for longhorn-system/sfpl-prod-file-service-r-4103790a: failed to get instance manager for instance sfpl-prod-file-service-r-4103790a: cannot find instance manager by node=agent-2, engineImage=ei-ec95b5ad, type=replica"
```

**Environment:**
 - Longhorn version: v0.7.0
 - Kubernetes version: unknown
 - Node OS type and version: unknown

**Comment by yasker** [comment] 2020-04-09 02:07
It happened because of the upgrade process, the manager cannot find the instance manager with the old image. Punt to later.

**Comment by yasker** [comment] 2020-06-02 00:36
Need to see what's the impact of instance manager refactoring.

**Comment by yasker** [comment] 2020-11-12 02:43
@shuo-wu can you check if this is still possible in v1.1.0?

**Comment by shuo-wu** [comment] 2020-11-16 12:22
The case instance manager not found is totally different from the case instance manager **pod** is not found. The error reported above is [here](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/controller/instance_handler.go#L215). 

If instance manager pod is not found, all related replicas will be marked as ERROR immediately. Then Longhorn needs to wait for 30s ~ 1minute to wait for the instances becoming stopped (here is a separate issue tracking this bug).

If instance manager is not found, then we need to consider:
    1. Why the instance manager disappears when there are instances using it. And if we directly mark the instances as stopped rather than error
    2. If we need to distinguish the node down case from the instance manager not found case. 
If No, we can avoid returning error [here](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/controller/instance_handler.go#L215) then [this part](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/controller/instance_handler.go#L53) will handle both cases.
If YES, we can blindly mark instance as stopped rather than [unknown](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/controller/instance_handler.go#L54) when the instance manager is nil. 
Of course, we need to test this part throughly since the modification is a little bit sensitive.

**Comment by shuo-wu** [comment] 2020-12-04 09:13
I am thinking if we still need to add extra logic to handle [this error ](https://github.com/longhorn/longhorn-manager/blob/8af120dd7c109d81d86118e482f88a26ddf7650f/controller/instance_handler.go#L215). Right now Longhorn will immediately recreate a new instance manager if the existing one somehow is deleted. And instance-manager-controller will mark all related processes as ERROR when the instance manager CR deletion is triggered.

**Comment by yasker** [comment] 2020-12-04 17:54
We do have finalizers for InstanceManager CR, so the cleanup process shouldn't be skipped. So it won't be an edge trigger case.

As long as the reconciliation process won't get blocked and can recover, I am fine with closing this issue.

**Comment by shuo-wu** [comment] 2020-12-05 04:27
Found the error in #1975. Let's see if Khushboo can provide the reproducing step first.

**Comment by yasker** [comment] 2020-12-08 16:40
Punt to v1.1.1 due to hard to reproduce the issue.

**Comment by olljanat** [comment] 2022-09-21 06:02
I noticed this bug also after upgrading to Longhorn 1.3.1. Is there plans to fix it?

**Comment by innobead** [comment] 2023-09-14 06:45
@chriscchien is this still valid?

cc @longhorn/qa

**Comment by chriscchien** [comment] 2023-09-22 07:26
Verified **pass** on longhorn-master(longhorn-instance-manager `5fe6bb`)

1. Delete instance-manager pod, can observe that correspond replica state will kept in `stopped` until instance-manager recreated.
```
k get replica vol1-r-148ad82e -n longhorn-system -w
NAME              STATE     NODE               DISK                                   INSTANCEMANAGER                                     IMAGE                                    AGE
vol1-r-148ad82e   running   ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511   longhornio/longhorn-engine:master-head   4m
vol1-r-148ad82e   error     ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511                                            4m12s
vol1-r-148ad82e   error     ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511                                            4m12s
vol1-r-148ad82e   stopped   ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766                                                                                                4m12s
vol1-r-148ad82e   stopped   ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766                                                                                                4m12s
vol1-r-148ad82e   stopped   ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766                                                                                                4m12s
vol1-r-148ad82e   stopped   ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766                                                                                                4m20s
vol1-r-148ad82e   starting   ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511                                            4m20s
vol1-r-148ad82e   running    ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511   longhornio/longhorn-engine:master-head   4m21s
vol1-r-148ad82e   running    ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511   longhornio/longhorn-engine:master-head   4m31s
vol1-r-148ad82e   running    ip-172-31-41-181   365db1e9-1921-44f0-bd5c-fc1aa82ea766   instance-manager-84b89982c4dca78f1fbc008c71ca8511   longhornio/longhorn-engine:master-head   4m35s
```
2. Deploy Longhorn v1.5.1 with volume attached. Delete instance manager pod wait correspond replica in `stopped` state and  then upgrade Longhorn to master-head immediately, the upgrade complete and volume worked well after upgrade.

**Closed by chriscchien** 2023-09-22 07:26 UTC
Labels: kind/bug, area/manager, severity/1, reproduce/rare, priority/2
