### ISSUE TITLE
[Question] i/o timeout during replica rebuild

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2146] opened 2020-12-31 03:25 UTC
**Describe the bug**
As described in the title. The instance manager image is `longhornio/longhorn-instance-manager:v1_20201216`, which is the latest version in v1.1.0. The original post of this issue is in [Slack](https://rancher-users.slack.com/archives/CC2UQM49Y/p1609247747073400)

**To Reproduce**
Not sure right now

**Expected behavior**
No i/o timeout error

**Log**
```
Failed rebuilding replica with Address 10.42.135.197:10000: failed to add replica address=‘tcp://10.42.135.197:10000’ to controller ‘siemtest-data’: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn [--url 10.42.197.84:10000 add tcp://10.42.135.197:10000], output , stderr, time=“2020-12-29T13:08:29Z” level=fatal msg=“Error running add replica command: failed to get replica 10.42.135.197:10000: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \“transport: Error while dialing dial tcp 10.42.135.197:10000: i/o timeout\“” , error exit status 1"
And the Volume replication fails on my second worker node. And im all out of ideas what could be wrong.
Also when i try to check logs on longhorn-csi-plugin-XXXX/longhorn-csi-plugin i receive “dial tcp 10.227.34.12:10250: i/o timeout
```

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

**Comment by yasker** [comment] 2021-01-05 01:59
We will try to reproduce the issue first.

**Comment by ajjo-tech** [comment] 2021-01-08 11:18
Hi,
Here's the details of the environment:
Kubernetes distro RKE and version 1.19.4:
Node config

    OS type and version: Ubuntu 20.04.1 LTS
    CPU per node: 8Cores
    Memory per node: 16GB for Master and 32GB for Workers
    Disk type(e.g. SSD/NVMe): SSD
    Network bandwidth and latency between the nodes:

Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare.

Regards,
/Anders.

**Comment by joshimoo** [comment] 2021-01-20 18:32
@ajjo-tech Can you check your network configuration between the nodes / vm's.
There is definitly something wrong on that end.

Are you doing a kubectl logs here? This should not timeout at all, therefore it looks like something is not right with your network setup.
`Also when i try to check logs on longhorn-csi-plugin-XXXX/longhorn-csi-plugin i receive “dial tcp 10.227.34.12:10250: i/o timeout`

**Comment by joshimoo** [comment] 2021-02-17 00:18
@ajjo-tech is this still an issue, the above logs point towards a network environment issue.
Particularly the csi plugin part: `Also when i try to check logs on longhorn-csi-plugin-XXXX/longhorn-csi-plugin i receive “dial tcp 10.227.34.12:10250: i/o timeout`

**Comment by ajjo-tech** [comment] 2021-02-17 13:40
@joshimoo 
We can go ahead and close this. As you correctly concluded it was network related.

Thanks,
/Anders.

**Closed** 2021-02-17 17:02 UTC
Labels: question
