### ISSUE TITLE
[BUG] when one snapshot is removed from a replica, volume stuck in recursive Attaching/detaching state.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1251] opened 2020-04-25 02:12 UTC
**Describe the bug**
If one snapshot out of many is deleted and pod is scaled to zero. On attaching the volume to node, it stuck in 'Attaching' and 'De-attaching' state.

**To Reproduce**
1. Create a volume -(1 replica, 1 node) and attach it to a pod.
2. Write data into the volume and take three snapshots. s1, s2 and s3
3. Go to /var/lib/rancher/longhorn/replica/vol----
4. Delete the s2. (.img and .meta both)
5. Scale down the pod to zero.
6. Go to volume and try to attach it to node.

**Expected behavior**
Volume attaching to node should not fail

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.17.4
 - Node OS type and version: Digital ocean node - ubuntu

**Comment by shuo-wu** [comment] 2020-06-19 14:43
There are 2 scenarios for this issue:

1. There are multiple replicas in the volume. And a snapshot is removed from only some of the replicas. In this case, those replicas will be marked as Failed and the volume still works fine.

2. A snapshot is removed from all of the replicas. In this case, the bug mentioned above will be triggered. And this scenario is like a duplicate of #1330

**Comment by shuo-wu** [comment] 2020-07-01 02:18
If this issue is different from #1330, then move it to the next release. Otherwise, we can close it.

**Comment by khushboo-rancher** [comment] 2020-07-07 01:32
Current behavior of the system:
**Scenario 1**
1. A snapshot is removed from only one of the replicas. Detach and attach the volume.
**Result**:
Volume becomes degraded first then rebuild the bad replica and works fine.

**Scenario 2**
1. A snapshot is removed from all the replicas. Detach and attach the volume.
**Result**:
Volume stuck in recursive attaching and detaching state. Similar to https://github.com/longhorn/longhorn/issues/1330

[longhorn-support-bundle_2954e33c-a95a-4d5d-b94b-6b2d560b9480_2020-07-07T01-25-32Z.zip](https://github.com/longhorn/longhorn/files/4881959/longhorn-support-bundle_2954e33c-a95a-4d5d-b94b-6b2d560b9480_2020-07-07T01-25-32Z.zip)
Volume name - vol1
Time of execution - Around UTC 01:25:00

**Comment by shuo-wu** [comment] 2020-07-07 02:04
@khushboo-rancher Can we close this one and track the bug in #1330?

**Closed** 2020-07-07 02:06 UTC
Labels: area/engine, bug, priority/2, reproduce/always, require/automation-e2e
