### ISSUE TITLE
[IMPROVEMENT] Support bundle doesn't collect the snapshot yamls

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#4285] opened 2022-07-27 00:37 UTC
TODO for Longhorn team: the support bundle doesn't collect the snapshot yamls

__Originally posted by @PhanLe1010 in https://github.com/longhorn/longhorn/issues/4278#issuecomment-1196003259__

**Comment by PhanLe1010** [comment] 2022-07-30 02:07
Test steps:

1. Create/attach a volume
2. Take a few snapshots
3. Generate support bundle
4. Verify that snapshot yamls are in /yaml/longhorn/snapshots

**Comment by joshimoo** [comment] 2022-07-30 22:06
Probably a good idea to test with a large set of snapshots, the generation should work fine and not timeout.

**Comment by innobead** [comment] 2022-08-01 10:44
@PhanLe1010 Please move to `ready-for-testing` if this and the backport are ready. I also suggest having scaling testing (simulation should be fine) to see if any impact on the bundle generation.

**Comment by PhanLe1010** [comment] 2022-08-01 17:38
> Please move to ready-for-testing if this and the backport are ready.

Thank you. Done 

>  also suggest having scaling testing (simulation should be fine) to see if any impact on the bundle generation.

I updated the test steps generate 15k snapshots

**Comment by yangchiu** [comment] 2022-08-04 07:54
Tested failed on master-head (longhorn-manager bd383f9).

Test steps:
(1) Create/attach a 150 volumes
(2) Create a new recurring snapshot jobs that select all volume, take snapshot every minute, and retain 50 snapshots
(_Setting retain to 100 will show error message:_ `unable to create recurring job c-u6rz9o: admission webhook "validator.longhorn.io" denied the request: retain in body should be less than or equal to 50 `)
(3) Wait for 51 minutes
(4) Generate a support bundle => Get `504` Timeout error. UI stuck in `Generating...`.

**Comment by innobead** [comment] 2022-08-04 08:20
How about the content of the support bundle?

**Comment by yangchiu** [comment] 2022-08-04 08:31
> How about the content of the downloaded support bundle?

The content of the downloaded support bundle is intact.
In the above test scenario, the downloaded support bundle is with compressed size 11.6MB, uncompressed size 204.2MB, and the snapshots.yaml is 44.3MB is size, with 2,841,199 lines.

**Comment by innobead** [comment] 2022-08-04 08:36
LGTM, but we need to have a notice in our doc.

@PhanLe1010 WDYT?

**Comment by PhanLe1010** [comment] 2022-08-04 21:34
>  Generate a support bundle => Get 504 Timeout error (Could be from /v1/supportbundles POST call). UI stuck in Generating.... Unable to get support bundle.

This is unexpected as [the init request](https://github.com/longhorn/longhorn-manager/blob/4fa1cc197e893c0243599398d3c4bbf021e7b0e7/api/router.go#L163) is async: [link](https://github.com/longhorn/longhorn-manager/blob/4fa1cc197e893c0243599398d3c4bbf021e7b0e7/manager/misc.go#L140-L166) . Can I access your env?

>  After the error, close/reopen the UI page and try to regenerate the support bundle, still unable to get the support bundle, the API /v1/supportbundles/ip-10-0-1-180/longhorn-support-bundle_c6d6cc3d-1a42-46a6-8c9f-cf6adaf9fbe8_2022-08-04T07-56-06Z keeps polling for 10 minutes until it gets non-zero progressPercentage and starts the downloading

This is expected. Longhorn generate support bundle by generating yamls and logs. There is no progress at the beginning when Longhorn try to generate yamls. We can improve on this.

**Comment by yangchiu** [comment] 2022-08-05 01:05
> > Generate a support bundle => Get 504 Timeout error (Could be from /v1/supportbundles POST call). UI stuck in Generating.... Unable to get support bundle.
> 
> This is unexpected as [the init request](https://github.com/longhorn/longhorn-manager/blob/4fa1cc197e893c0243599398d3c4bbf021e7b0e7/api/router.go#L163) is async: [link](https://github.com/longhorn/longhorn-manager/blob/4fa1cc197e893c0243599398d3c4bbf021e7b0e7/manager/misc.go#L140-L166) . Can I access your env?

The env has been destroyed. But once I can reproduce it, I'll let you know!

**Comment by yangchiu** [comment] 2022-08-05 04:15
> Test steps:
> 
> 1. Create/attach a 150 volumes
> 2. Create a new recurring snapshot jobs that select all volume, take snapshot every minute, and retain 100 snapshots
> 3. Wait for 101 minutes
> 4. Generate a support bundle
> 5. Verify that snapshot yamls are in /yaml/longhorn/snapshots

@PhanLe1010 one more question: In the step 5:` Verify that snapshot yamls are in /yaml/longhorn/snapshots`

Seems it expects separate yaml files for different snapshots in the `/yaml/longhorn/snapshots` folder, but currently in the downloaded support bundle, all the yaml contents of all the snapshot are concatenated into the same `snapshots.yaml` file, and there is no `/yaml/longhorn/snapshots` folder. Just like the attached file:
[longhorn-support-bundle_0b2b7f6e-9bd1-4ccf-a435-c45106ef7ab0_2022-08-05T03-54-40Z.zip](https://github.com/longhorn/longhorn/files/9265174/longhorn-support-bundle_0b2b7f6e-9bd1-4ccf-a435-c45106ef7ab0_2022-08-05T03-54-40Z.zip)

Is it what we expected?

**Comment by PhanLe1010** [comment] 2022-08-05 19:56
> Seems it expects separate yaml files for different snapshots in the /yaml/longhorn/snapshots folder, but currently in the downloaded support bundle, all the yaml contents of all the snapshot are concatenated into the same snapshots.yaml file, and there is no /yaml/longhorn/snapshots folder. Just like the attached file:

Sorry for the confusion.  `All the yaml contents of all the snapshot are concatenated into the same snapshots.yaml` is the correct behavior

**Comment by yangchiu** [comment] 2022-08-06 14:39
I'm unable to reproduce the 504 timeout error again on either master-head or v1.3.x-head.
The support bundle can be generated and downloaded successfully, and the content of snapshots.yaml are as our expected.
The functionality of collecting snapshot yamls in support bundle works, so close this ticket for now.

**Closed by yangchiu** 2022-08-06 14:39 UTC
Labels: area/manager, area/troubleshooting, backport-needed/1.3.1
