### ISSUE TITLE
Longhorn mount disk Consul use longhorn do not work well

### ISSUE THREAD

**Issue by jinze1107** [longhorn/longhorn#2337] opened 2021-03-13 10:42 UTC
1.i install longhorn with helm chart  [longhorn-1.1.0   v1.1.0] ,and i mount one remote disk: 
df -h :
/dev/vdb                                                1.1T  538M  981G   1% /data/longhorn

2.then i set longhorn defaultDataPath: /data/longhorn. , run longhron 
3. helm install consul i use longhorn
   storageClass: longhorn 
   
  then run consul, but longhorn volume is work well:  
   volume state alway changing: Attaching-Detaching-Detached-Attaching. 
   then i see manager engine and replica log do not have errors , so what can i do , does it is a bug?
      when i do not use one remote disk it work well 

csi-attacher.log error:
`2021-03-13T05:07:53.076327657+08:00 I0312 21:07:53.070805       1 connection.go:183] GRPC request: {"node_id":"vm-0-68-centos","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"baseImage":"","fromBackup":"","numberOfReplicas":"3","staleReplicaTimeout":"30","storage.kubernetes.io/csiProvisionerIdentity":"1615556111741-8081-driver.longhorn.io"},"volume_id":"pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33"}
2021-03-13T05:07:53.106585983+08:00 I0312 21:07:53.106047       1 connection.go:185] GRPC response: {}
2021-03-13T05:07:53.106601422+08:00 I0312 21:07:53.106540       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching
2021-03-13T05:07:53.106606692+08:00 I0312 21:07:53.106557       1 csi_handler.go:559] Saving attach error to "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.110367173+08:00 I0312 21:07:53.109844       1 connection.go:185] GRPC response: {}
2021-03-13T05:07:53.110391969+08:00 I0312 21:07:53.110272       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching
2021-03-13T05:07:53.110399203+08:00 I0312 21:07:53.110283       1 csi_handler.go:575] Saving detach error to "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.117654096+08:00 I0312 21:07:53.117559       1 csi_handler.go:570] Saved attach error to "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117696877+08:00 I0312 21:07:53.117591       1 csi_handler.go:219] Error processing "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9": failed to attach: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching
2021-03-13T05:07:53.117715301+08:00 I0312 21:07:53.117627       1 controller.go:198] Started VA processing "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117732834+08:00 I0312 21:07:53.117637       1 csi_handler.go:209] CSIHandler: processing VA "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117736932+08:00 I0312 21:07:53.117644       1 csi_handler.go:236] Attaching "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117742893+08:00 I0312 21:07:53.117650       1 csi_handler.go:396] Starting attach operation for "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117747461+08:00 I0312 21:07:53.117683       1 csi_handler.go:329] PV finalizer is already set on "pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33"
2021-03-13T05:07:53.117751138+08:00 I0312 21:07:53.117695       1 csi_handler.go:689] Found NodeID vm-0-68-centos in CSINode vm-0-68-centos
2021-03-13T05:07:53.117762810+08:00 I0312 21:07:53.117704       1 csi_handler.go:289] VA finalizer is already set on "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117766928+08:00 I0312 21:07:53.117715       1 csi_handler.go:303] NodeID annotation is already set on "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.117770575+08:00 I0312 21:07:53.117727       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerPublishVolume
2021-03-13T05:07:53.119474369+08:00 I0312 21:07:53.117731       1 connection.go:183] GRPC request: {"node_id":"vm-0-68-centos","volume_capability":{"AccessType":{"Mount":{"fs_type":"ext4"}},"access_mode":{"mode":1}},"volume_context":{"baseImage":"","fromBackup":"","numberOfReplicas":"3","staleReplicaTimeout":"30","storage.kubernetes.io/csiProvisionerIdentity":"1615556111741-8081-driver.longhorn.io"},"volume_id":"pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33"}
2021-03-13T05:07:53.119854081+08:00 I0312 21:07:53.119812       1 csi_handler.go:586] Saved detach error to "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.119863569+08:00 I0312 21:07:53.119833       1 csi_handler.go:219] Error processing "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990": failed to detach: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching
2021-03-13T05:07:53.120847765+08:00 I0312 21:07:53.120734       1 controller.go:198] Started VA processing "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.120860799+08:00 I0312 21:07:53.120745       1 csi_handler.go:209] CSIHandler: processing VA "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.120864757+08:00 I0312 21:07:53.120751       1 csi_handler.go:260] Starting detach operation for "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.120869345+08:00 I0312 21:07:53.120771       1 csi_handler.go:267] Detaching "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.120874044+08:00 I0312 21:07:53.120782       1 csi_handler.go:689] Found NodeID vm-0-94-centos in CSINode vm-0-94-centos
2021-03-13T05:07:53.120878913+08:00 I0312 21:07:53.120790       1 connection.go:182] GRPC call: /csi.v1.Controller/ControllerUnpublishVolume
2021-03-13T05:07:53.121337122+08:00 I0312 21:07:53.120794       1 connection.go:183] GRPC request: {"node_id":"vm-0-94-centos","volume_id":"pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33"}
2021-03-13T05:07:53.123478517+08:00 I0312 21:07:53.122952       1 connection.go:185] GRPC response: {}
2021-03-13T05:07:53.123487474+08:00 I0312 21:07:53.123445       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching
2021-03-13T05:07:53.123490840+08:00 I0312 21:07:53.123455       1 csi_handler.go:559] Saving attach error to "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.124231029+08:00 I0312 21:07:53.123747       1 connection.go:185] GRPC response: {}
2021-03-13T05:07:53.124240736+08:00 I0312 21:07:53.124197       1 connection.go:186] GRPC error: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching
2021-03-13T05:07:53.124243461+08:00 I0312 21:07:53.124204       1 csi_handler.go:575] Saving detach error to "csi-1050e9b3f1327e64884ed9e3abb0c1a5af3a41163990cae2b75540ee48861990"
2021-03-13T05:07:53.126947302+08:00 I0312 21:07:53.126848       1 csi_handler.go:570] Saved attach error to "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9"
2021-03-13T05:07:53.126964213+08:00 I0312 21:07:53.126870       1 csi_handler.go:219] Error processing "csi-d73a531cd440a8cb6d4a91b5f59280a038208f5ccb02fdba5347090186fd47e9": failed to attach: rpc error: code = Aborted desc = The volume pvc-30d7c87a-6fdb-41b6-bd9a-86938cf3ce33 is detaching`

**Comment by jinze1107** [comment] 2021-03-13 11:17
i found error in engine-manager.log:  but ican install iscsi use command :   yum install -y iscsi-initiator-utils  why have still errors?
2021-03-13T18:01:27.786797157+08:00 receive_msg: fail to read magic version
2021-03-13T18:01:27.786800353+08:00 response_process: Receive response returned error
2021-03-13T18:01:27.786802958+08:00 lh_client_close_conn: Closing connection
2021-03-13T18:01:27.786932581+08:00 lh_client_close_conn: Connection close complete
2021-03-13T18:01:27.789851495+08:00 [pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce] time="2021-03-13T10:01:27Z" level=info msg="device pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c: SCSI device /dev/longhorn/pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c shutdown"
2021-03-13T18:01:28.530242093+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:28Z" level=info msg="wait for gRPC service of process pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce to start at localhost:10000"
2021-03-13T18:01:28.791307216+08:00 [pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce] go-iscsi-helper: tgtd is already running
2021-03-13T18:01:28.795212046+08:00 [pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce] time="2021-03-13T10:01:28Z" level=info msg="go-iscsi-helper: found available target id 1"
2021-03-13T18:01:28.799457875+08:00 tgtd: device_mgmt(246) sz:109 params:path=/var/run/longhorn-pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c.sock,bstype=longhorn,bsopts=size=21474836480
2021-03-13T18:01:28.799480487+08:00 tgtd: bs_thread_open(409) 16
2021-03-13T18:01:28.804334002+08:00 [pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce] time="2021-03-13T10:01:28Z" level=info msg="New data socket connnection established"
2021-03-13T18:01:28.825873355+08:00 [pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce] time="2021-03-13T10:01:28Z" level=error msg="Failed to startup frontend: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m node -T iqn.2019-10.io.longhorn:pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c -p 10.42.3.150 --login], output Logging in to [iface: default, target: iqn.2019-10.io.longhorn:pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c, portal: 10.42.3.150,3260] (multiple)\n, stderr, iscsiadm: Could not login to [iface: default, target: iqn.2019-10.io.longhorn:pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c, portal: 10.42.3.150,3260].\niscsiadm: initiator reported error (12 - iSCSI driver not found. Please make sure it is loaded, and retry the operation)\niscsiadm: Could not log into all portals\n, error exit status 12"
2021-03-13T18:01:28.836053823+08:00 [pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce] 2021/03/13 10:01:28 failed to start up frontend: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm -m node -T iqn.2019-10.io.longhorn:pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c -p 10.42.3.150 --login], output Logging in to [iface: default, target: iqn.2019-10.io.longhorn:pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c, portal: 10.42.3.150,3260] (multiple)
2021-03-13T18:01:28.836089841+08:00 , stderr, iscsiadm: Could not login to [iface: default, target: iqn.2019-10.io.longhorn:pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c, portal: 10.42.3.150,3260].
2021-03-13T18:01:28.836095632+08:00 iscsiadm: initiator reported error (12 - iSCSI driver not found. Please make sure it is loaded, and retry the operation)
2021-03-13T18:01:28.836100391+08:00 iscsiadm: Could not log into all portals
2021-03-13T18:01:28.836104679+08:00 , error exit status 12
2021-03-13T18:01:28.845790110+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:28Z" level=info msg="Process Manager: process pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce error out, error msg: exit status 1"
2021-03-13T18:01:28.845825286+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:28Z" level=debug msg="Process update: pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce: state error: Error: exit status 1"
2021-03-13T18:01:29.533814667+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:29Z" level=info msg="wait for gRPC service of process pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce to start at localhost:10000"
2021-03-13T18:01:29.533840435+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:29Z" level=info msg="stop waiting for gRPC service of process pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce to start at localhost:10000"
2021-03-13T18:01:29.736795514+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:29Z" level=debug msg="Process update: pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce: state error: Error: exit status 1"
2021-03-13T18:01:29.757194371+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:29Z" level=debug msg="Process Manager: start getting logs for process pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce"
2021-03-13T18:01:29.757460409+08:00 [longhorn-instance-manager] time="2021-03-13T10:01:29Z" level=debug msg="Process Manager: got logs for process pvc-3487bde2-fedf-4ab8-9729-8e44d646f64c-e-cb0518ce"

**Comment by cclhsu** [comment] 2021-03-16 08:25
Hi! Can you help provide information on cluster setup? If node (10.42.3.150) is pingable and iscsi install on that Node?

**Comment by cclhsu** [comment] 2021-03-26 03:57
@jinze1107 Are you able to resolve the issue? If not, please try to deploy ISCSI from link below:

https://github.com/longhorn/longhorn-manager/tree/master/deploy/prerequisite

and apply following command

```
NAMESPACE=longhorn-system
kubectl rollout restart deployment --namespace ${NAMESPACE} 
```

to see if it helps.  I think it could related to iscsi mod/servevice not staring properly.

**Comment by shuo-wu** [comment] 2021-04-27 01:51
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by shuo-wu** 2021-04-27 01:51 UTC
