### ISSUE TITLE
[BUG] Constant errors about io.rancher.longhorn-reg.sock

### ISSUE THREAD

**Issue by Leen15** [longhorn/longhorn#1412] opened 2020-05-27 15:29 UTC
**Describe the bug**
I have several errors in kubelet log of every node, and it's the same that continues every X minutes:

```
I0527 14:47:10.544314   10814 reconciler.go:156] operationExecutor.RegisterPlugin started for plugin at "/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock" (plugin details: &{/var/lib/kubelet/plugins/io.rancher.longhorn-reg.socktrue 2020-03-21 22:46:57.40373808 +0000 UTC m=+21.619442778})
I0527 14:47:10.544409   10814 operation_generator.go:193] parsed scheme: ""
I0527 14:47:10.544427   10814 operation_generator.go:193] scheme "" not registered, fallback to default scheme
I0527 14:47:10.544452   10814 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock 0  <nil>}] <nil>}
I0527 14:47:10.544478   10814 clientconn.go:577] ClientConn switching balancer to "pick_first"
I0527 14:47:10.544581   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, CONNECTING
W0527 14:47:10.544781   10814 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock: connect: connection refused". Reconnecting...
I0527 14:47:10.544846   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, TRANSIENT_FAILURE
I0527 14:47:11.545032   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, CONNECTING
W0527 14:47:11.545080   10814 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock: connect: connection refused". Reconnecting...
I0527 14:47:11.545120   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, TRANSIENT_FAILURE
I0527 14:47:13.214754   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, CONNECTING
W0527 14:47:13.214799   10814 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock: connect: connection refused". Reconnecting...
I0527 14:47:13.214866   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, TRANSIENT_FAILURE
I0527 14:47:15.865668   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, CONNECTING
W0527 14:47:15.865765   10814 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock: connect: connection refused". Reconnecting...
I0527 14:47:15.865828   10814 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc001438790, TRANSIENT_FAILURE
W0527 14:47:17.528690   10814 kubelet_pods.go:849] Unable to retrieve pull secret longhorn-system/ for longhorn-system/longhorn-csi-plugin-9mrj8 due to secret "" not found.  The image pull may not succeed.
E0527 14:47:20.544545   10814 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock" failed. No retries permitted until 2020-05-27 14:49:22.544513867 +0000 UTC m=+5760166.760218627 (durationBeforeRetry 2m2s). Error: "RegisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins/io.rancher.longhorn-reg.sock, err: context deadline exceeded"
```

**To Reproduce**
I have two clusters but this error happens only on one of them.
It's a RKE cluster, on 3 bare metal servers.
The error is logged in all nodes.
I already tried to remove longhorn with also manual remove of CRDs but the error PERSISTS also after remove longhorn.
So I tried to install again (last version) and the error continues.

**Expected behavior**
No errors in kubelet logs.

**Environment:**
 - Longhorn version: 0.8.1 (the same with 0.7.0)
 - Kubernetes version: 1.16.6
 - Node OS type and version: Ubuntu 18.04

**Comment by yasker** [comment] 2020-05-27 16:57
@Leen15 This should be fixed in v1.0.0 when we removed compatible CSI plugin #1365 .  @boknowswiki Can you check if this still happens for the master branch now?

**Comment by boknowswiki** [comment] 2020-05-27 17:56
@yasker 
Tried two ways to find the error messages:
1. Logged into all three nodes, and goto `/var/log` directories, run `rep "io.rancher.longhorn-reg.sock" -r *`, nothing returned.
2. Run `docker logs <kubelet docker id> | grep "io.rancher.longhorn-reg.sock"`, don't see the same error message, but found one interesting message, but I think it's from 5/22/2020, please help to confirm.

`I0522 01:29:49.955216    9802 handlers.go:66] Exec lifecycle hook ([/bin/sh -c rm -rf /registration/driver.longhorn.io /registration/driver.longhorn.io-reg.sock /csi//*]) for Container "node-driver-registrar" in Pod "longhorn-csi-plugin-424n9_longhorn-system(e3667b35-3627-4af8-bd1a-4e75ad03931d)" failed - error: command '/bin/sh -c rm -rf /registration/driver.longhorn.io /registration/driver.longhorn.io-reg.sock /csi//*' exited with 126: , message: "OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused \"exec: \\\"/bin/sh\\\": stat /bin/sh: no such file or directory\": unknown\r\n"`

Thanks.

**Comment by yasker** [comment] 2020-05-27 18:01
@boknowswiki the second error message should be something else. Are you able to reproduce the issue on v0.8.1?

**Comment by boknowswiki** [comment] 2020-05-27 18:15
@yasker , I just found this error message, I can see the issue on my testbed now.

`W0527 18:11:26.910365    1113 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock: connect: connection refused". Reconnecting...`

**Comment by yasker** [comment] 2020-05-27 18:31
@boknowswiki which version you're using? If it's v1.0.0-rc2, can you restart the node/kubelet, to see if it disappears? Since kubelet might keep some internal states in the memory.

**Comment by boknowswiki** [comment] 2020-05-27 20:06
@yasker I am using latest master images. I did `kubectl delete -f <manager and driver yaml>`, and apply them back. Let me try v1.0.0-rc2.

**Comment by boknowswiki** [comment] 2020-05-27 20:40
@yasker 
Steps I did:
1. Uninstall longhorn and make sure nothing left.
2. Restart all my worker nodes.
3. Install longhorn v1.0.0-rc2.

I can see the same error message:

`W0527 20:37:19.600693    1093 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock: connect: connection refused". Reconnecting...`

**Comment by yasker** [comment] 2020-05-27 20:46
@boknowswiki There is a host directory leftover by the previous driver, located at `/var/lib/kubelet/plugins/io.rancher.longhorn`. Can you try to remove it and see if it helps?

**Comment by boknowswiki** [comment] 2020-05-27 22:41
Found it at `/var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock`, and after I remove it, the error message is gone with the message in kubelet log:

`I0527 22:35:53.677564    1093 plugin_watcher.go:212] Removing socket path /var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock from desired state cache`

**Comment by yasker** [comment] 2020-05-28 02:35
@Leen15 According to what we have discussed above, you should be able to remove `/var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock` from the node to stop kubelet from complaining about this obsolete domain socket.

**Comment by Leen15** [comment] 2020-05-28 06:57
Hi @yasker , I see two sock in plugins_registry:
```
driver.longhorn.io-reg.sock 
io.rancher.longhorn-reg.sock
```
can I safely remove `io.rancher.longhorn-reg.sock` from all nodes keeping longhorn 0.8.1 running?

**Comment by yasker** [comment] 2020-05-28 14:20
@Leen15 After making sure you have no PV with driver `io.rancher.longhorn` (see the instruction [here](https://longhorn.io/docs/0.8.1/deploy/upgrade/longhorn-manager/#upgrading-from-v062-or-older-version-to-v081)), you can safely remove `io.rancher.longhorn-reg.sock`

**Comment by Leen15** [comment] 2020-05-29 07:45
I removed the sock in both plugins and plugins_registry directories but it continues:

```
onBeforeRetry 2m2s). Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/io.rancher.longhorn-reg.sock, err: context deadline exceeded"
I0529 07:43:42.201933    3034 reconciler.go:139] operationExecutor.UnregisterPlugin started for plugin at "/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock" (plugin details: &{/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock false 2020-05-27 14:31:10.934280222 +0000 UTC m=+3389191.734068089})
I0529 07:43:42.202053    3034 operation_generator.go:193] parsed scheme: ""
I0529 07:43:42.202089    3034 operation_generator.go:193] scheme "" not registered, fallback to default scheme
I0529 07:43:42.202133    3034 passthrough.go:48] ccResolverWrapper: sending update to cc: {[{/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock 0  <nil>}] <nil>}
I0529 07:43:42.202165    3034 clientconn.go:577] ClientConn switching balancer to "pick_first"
I0529 07:43:42.202277    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, CONNECTING
W0529 07:43:42.202486    3034 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock: connect: no such file or directory". Reconnecting...
I0529 07:43:42.202543    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, TRANSIENT_FAILURE
I0529 07:43:42.231889    3034 kubelet_network_linux.go:111] Not using `--random-fully` in the MASQUERADE rule for iptables because the local version of iptables does not support it
I0529 07:43:43.202847    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, CONNECTING
W0529 07:43:43.202877    3034 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock: connect: no such file or directory". Reconnecting...
I0529 07:43:43.202938    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, TRANSIENT_FAILURE
I0529 07:43:44.724684    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, CONNECTING
W0529 07:43:44.724752    3034 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock: connect: no such file or directory". Reconnecting...
I0529 07:43:44.724831    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, TRANSIENT_FAILURE
I0529 07:43:46.965593    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, CONNECTING
W0529 07:43:46.965682    3034 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock: connect: no such file or directory". Reconnecting...
I0529 07:43:46.965763    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, TRANSIENT_FAILURE
I0529 07:43:51.642421    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, CONNECTING
W0529 07:43:51.642450    3034 clientconn.go:1120] grpc: addrConn.createTransport failed to connect to {/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock 0  <nil>}. Err :connection error: desc = "transport: Error while dialing dial unix /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock: connect: no such file or directory". Reconnecting...
I0529 07:43:51.642472    3034 balancer_conn_wrappers.go:127] pickfirstBalancer: HandleSubConnStateChange: 0xc00187b2a0, TRANSIENT_FAILURE
E0529 07:43:52.202279    3034 goroutinemap.go:150] Operation for "/var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock" failed. No retries permitted until 2020-05-29 07:45:54.20222555 +0000 UTC m=+3537675.002013581 (durationBeforeRetry 2m2s). Error: "UnregisterPlugin error -- dial failed at socket /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock, err: failed to dial socket /var/lib/kubelet/plugins_registry/driver.longhorn.io-reg.sock, err:context deadline exceeded"
```

**Comment by yasker** [comment] 2020-05-29 13:17
@boknowswiki Do we need to do anything after removing the Unix domain socket? e.g. restart kubelet. Or Kubelet will automatically pick it up?

**Comment by boknowswiki** [comment] 2020-05-29 17:06
@yasker , No, after I delete the `io.rancher.longhorn-reg.sock` socket, the error message went away. And I just logged in my node, and I haven't see the error message so far, it's been more than 10 mins now.

Another thing is I did received the email about @Leen15 reporting the issue again, but I don't see the comment here.

**Comment by boknowswiki** [comment] 2020-05-29 17:14
@Leen15 , could you help to confirm if you still see the error message after removing `io.rancher.longhorn-reg.sock` socket? Thanks.

**Comment by Leen15** [comment] 2020-05-29 17:21
Hi @boknowswiki , I first reported the issue again, but then after removed the sock from the plugins folder too, and restarted the kubelet, I didn't see the error anymore.
I don't know if one of these two things did the magic, but now It works.

**Comment by boknowswiki** [comment] 2020-05-29 17:28
@Leen15 , thanks for your confirm, and good to hear the issue is gone for you.

**Comment by khushboo-rancher** [comment] 2020-06-16 17:37
@boknowswiki Can you please point me to the doc link? I couldn't found it here https://staging.longhorn.io/docs/0.8.1/deploy/upgrade/longhorn-manager/#migration-failure-handling 
and 
https://longhorn.io/docs/0.8.1/deploy/upgrade/longhorn-manager/#migration-failure-handling

**Comment by khushboo-rancher** [comment] 2020-06-16 18:54
Followed the instructions from https://longhorn.io/docs/1.0.0/deploy/upgrade/longhorn-manager/#cleanup-for-compatible-csi-plugin, the logs of error message related to ```io.rancher.longhorn-reg.``` disappear.

To repro the issue, tried steps from https://github.com/longhorn/longhorn/issues/1412#issuecomment-634927383

**Closed by khushboo-rancher** 2020-06-16 18:54 UTC
Labels: area/deployment, area/manager, bug

**Comment by KeithTt** [comment] 2022-07-25 08:23
@khushboo-rancher Thanks a lot, this doc really help me.
