### ISSUE TITLE
[BUG] The 'Attached to' column needs to incorporate all pods history for RWX volume

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2056] opened 2020-12-08 18:16 UTC
**Describe the bug**
The 'Attached to' column needs to incorporate pods history for all the RWX volume on the longhorn UI. As of now, it shows only the last pod attached history.

**To Reproduce**
1. Create an statefulSet of 3 pods with RWX volume.
2. Scale down all the pods.
3. RWX volume shows only the last pod attached history.

**Environment:**
 - Longhorn version: v1.1.0-rc1
 - Kubernetes version: v19.2

**Comment by yasker** [comment] 2020-12-23 06:12
We need some thoughts about this. We cannot show all the histories since the main point of having the history is to remind users what does this volume for. @joshimoo what do you think?

**Comment by joshimoo** [comment] 2020-12-23 15:31
Needs some more design discussion, but how do you feel about instead of referencing the individual pods, have the ui reference the deployment/statefulset instead?

**Comment by yasker** [comment] 2020-12-23 18:00
But the same PVC can be used by different Deployment/StatefulSet as well. We record this information too.

And for StatefulSet, each pod can have different data, so it's still better to show the Pod and StatefulSet instead of just the StatefulSet.

The problem is, previously we only show either the history information or the current information. Once a pod starts to use the volume, we will show the current information. For history information, as Khushboo mentioned, we only show the last Pod who used it - which makes more sense in RWO since normally there is only one Pod using it.

In RWX, there can be multiple Pods using the volume. Though now I am still leaning towards only show the history of the last Pod, since:
1. The goal is we want to let the user know what's in the volume.
2. It's hard to decide when to clean up the history information if we're going to show both current and history at the same time.

@khushboo-rancher What do you think?

**Comment by khushboo-rancher** [comment] 2020-12-23 19:27
Agree, Showing the history of the last attached pod makes sense.

**Comment by yasker** [comment] 2020-12-23 19:34
@khushboo-rancher @joshimoo If you agree, we can close this issue.

**Closed** 2020-12-23 19:35 UTC
Labels: enhancement, feature/rwx
