### ISSUE TITLE
[BUG] Backup marked as "completed" cannot be restored, gzip: invalid header

### ISSUE THREAD

**Issue by ohthehugemanatee** [longhorn/longhorn#7687] opened 2024-01-15 14:48 UTC
## Describe the bug

I have 3 months of backups marked as "completed" without issue, which can't be restored due to what appears to be a problem during backup creation. The error message on restore is "gzip: invalid header".

Problems creating a backup should raise an error, and the resulting backup should not be marked as "Completed".

See #7670 for the specific case. I thought this was due to my confusion around the engine image version used for the volume, but testing with a variety of versions in the `restore-backup-to-file.sh` script indicates it must be a problem in image creation. Regardless, backups should not depend on assumptions about the longhorn context... all information required to restore the backup should be included in the backup metadata.  

```
time="2024-01-14T12:03:42Z" level=info msg="Running restore to file command: backup-url=nfs://warehouse.vert:/mnt/storage/.docker/longhorn-backups?backup=backup-8417093ca8854143&volume=pvc-2925f092-964d-4f62-9c4f-941f39605413 backing-file= output-file=/tmp/restore/mariadb.raw output-format=raw" func=cmd.RestoreToFileCmd.func1 file="restore_to_file.go:63"
time="2024-01-14T12:03:42Z" level=info msg="Output file path=/tmp/restore/mariadb.raw" func=cmd.restoreToFile file="restore_to_file.go:138"
time="2024-01-14T12:03:42Z" level=info msg="Start to restore nfs://warehouse.vert:/mnt/storage/.docker/longhorn-backups?backup=backup-8417093ca8854143&volume=pvc-2925f092-964d-4f62-9c4f-941f39605413 to backup.img" func=cmd.restoreToFile file="restore_to_file.go:142"
time="2024-01-14T12:03:42Z" level=info msg="Attempting mount for nfs path warehouse.vert:/mnt/storage/.docker/longhorn-backups with nfsvers 4.2" func="nfs.(*BackupStoreDriver).mount" file="nfs.go:126" pkg=nfs
time="2024-01-14T12:03:42Z" level=info msg="Mounting NFS share nfs://warehouse.vert:/mnt/storage/.docker/longhorn-backups on mount point /var/lib/longhorn-backupstore-mounts/warehouse_vert/mnt/storage/.docker/longhorn-backups with options [nfsvers=4.2 actimeo=1 soft timeo=300 retry=2]" func="nfs.(*BackupStoreDriver).mount" file="nfs.go:137" pkg=nfs
time="2024-01-14T12:03:42Z" level=info msg="Loaded driver for nfs://warehouse.vert:/mnt/storage/.docker/longhorn-backups" func=nfs.initFunc file="nfs.go:91" pkg=nfs
time="2024-01-14T12:03:42Z" level=info msg="Saving config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:79" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=start
time="2024-01-14T12:03:42Z" level=info msg="Saved config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:90" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=complete
time="2024-01-14T12:03:42Z" level=info msg="Stored lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck type 1 on backupstore" func=backupstore.saveLock file="lock.go:190" pkg=backupstore
time="2024-01-14T12:03:44Z" level=info msg="Loading config in backupstore" func=backupstore.LoadConfigInBackupStore file="config.go:54" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=start
time="2024-01-14T12:03:44Z" level=info msg="Loaded config in backupstore" func=backupstore.LoadConfigInBackupStore file="config.go:65" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=complete
time="2024-01-14T12:03:44Z" level=info msg="Loaded lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck type 1 on backupstore" func=backupstore.loadLock file="lock.go:171" pkg=backupstore
time="2024-01-14T12:03:44Z" level=info msg="Trying to acquire lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck" func="backupstore.(*FileLock).canAcquire" file="lock.go:65" lock="{ volume: pvc-2925f092-964d-4f62-9c4f-941f39605413, name: lock-e0dd61273bea4e88, type: 1, acquired: false, serverTime: 2024-01-14 12:03:42.44230808 +0000 UTC }" pkg=backupstore
time="2024-01-14T12:03:44Z" level=info msg="backupstore volume pvc-2925f092-964d-4f62-9c4f-941f39605413 contains locks [{ volume: , name: lock-e0dd61273bea4e88, type: 1, acquired: false, serverTime: 2024-01-14 12:03:42.44230808 +0000 UTC }]" func="backupstore.(*FileLock).canAcquire" file="lock.go:66" pkg=backupstore
time="2024-01-14T12:03:44Z" level=info msg="Acquired lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck type 1 on backupstore" func="backupstore.(*FileLock).Lock" file="lock.go:114" pkg=backupstore
time="2024-01-14T12:03:44Z" level=info msg="Saving config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:79" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=start
time="2024-01-14T12:03:44Z" level=info msg="Saved config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:90" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=complete
time="2024-01-14T12:03:44Z" level=info msg="Stored lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck type 1 on backupstore" func=backupstore.saveLock file="lock.go:190" pkg=backupstore
time="2024-01-14T12:03:44Z" level=info msg="Loading config in backupstore" func=backupstore.LoadConfigInBackupStore file="config.go:54" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/volume.cfg kind=nfs object=config pkg=backupstore reason=start
time="2024-01-14T12:03:44Z" level=info msg="Loaded config in backupstore" func=backupstore.LoadConfigInBackupStore file="config.go:65" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/volume.cfg kind=nfs object=config pkg=backupstore reason=complete
time="2024-01-14T12:03:44Z" level=info msg="Loading config in backupstore" func=backupstore.LoadConfigInBackupStore file="config.go:54" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/backups/backup_backup-8417093ca8854143.cfg kind=nfs object=config pkg=backupstore reason=start
time="2024-01-14T12:03:44Z" level=info msg="Loaded config in backupstore" func=backupstore.LoadConfigInBackupStore file="config.go:65" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/backups/backup_backup-8417093ca8854143.cfg kind=nfs object=config pkg=backupstore reason=complete
time="2024-01-14T12:03:44Z" level=info msg="Restoring delta block backup" func=backupstore.RestoreDeltaBlockBackup file="deltablock.go:719" backup_url="nfs://warehouse.vert:/mnt/storage/.docker/longhorn-backups?backup=backup-8417093ca8854143&volume=pvc-2925f092-964d-4f62-9c4f-941f39605413" event=restore object=snapshot original_volume=pvc-2925f092-964d-4f62-9c4f-941f39605413 pkg=backupstore reason=start snapshot=backup-8417093ca8854143 volume_dev=backup.img
time="2024-01-14T12:03:44Z" level=info msg="Saving config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:79" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=start
time="2024-01-14T12:03:44Z" level=info msg="Saved config in backupstore" func=backupstore.SaveConfigInBackupStore file="config.go:90" filepath=backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck kind=nfs object=config pkg=backupstore reason=complete
time="2024-01-14T12:03:44Z" level=info msg="Stored lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck type 1 on backupstore" func=backupstore.saveLock file="lock.go:190" pkg=backupstore
 0 / 100    0.00%time="2024-01-14T12:03:45Z" level=error msg="Failed to delta restore volume pvc-2925f092-964d-4f62-9c4f-941f39605413 backup backup-8417093ca8854143" func=backupstore.RestoreDeltaBlockBackup.func2 file="deltablock.go:759" error="gzip: invalid header"
time="2024-01-14T12:03:45Z" level=info msg="Removed lock backupstore/volumes/a7/51/pvc-2925f092-964d-4f62-9c4f-941f39605413/locks/lock-e0dd61273bea4e88.lck type 1 on backupstore" func=backupstore.removeLock file="lock.go:180" pkg=backupstore
 0 / 100    0.00% 2s
time="2024-01-14T12:03:46Z" level=error msg="Failed to remove tmp file=backup.img.converted" func=cmd.CleanupTempFiles file="restore_to_file.go:223" error="remove /backup.img.converted: no such file or directory"
time="2024-01-14T12:03:46Z" level=error msg="Failed to remove tmp file=backing.img.cp" func=cmd.CleanupTempFiles file="restore_to_file.go:223" error="remove /backing.img.cp: no such file or directory"
time="2024-01-14T12:03:46Z" level=fatal msg="Error running restore to file command" func=cmd.RestoreToFileCmd.func1 file="restore_to_file.go:66" error="gzip: invalid header"
```
## To Reproduce

1) Create a scheduled backup, observe "completed" status
2) ???
3) Attempt to restore and observe "gzip: invalid header" error.

## Expected behavior

Completed backups should restore.

## Support bundle for troubleshooting

Not relevant (and honestly confusing on my dev cluster, which has had many versions of longhorn installed). I can email it upon request. But the backup metadata is

```
{
  "Name": "pvc-2925f092-964d-4f62-9c4f-941f39605413",
  "Size": "12884901888",
  "Labels": {
    "KubernetesStatus": "{\"pvName\":\"pvc-2925f092-964d-4f62-9c4f-941f39605413\",\"pvStatus\":\"Bound\",\"namespace\":\"default\",\"pvcName\":\"datadir-mariadb-0\",\"lastPVCRefAt\":\"\",\"workloadsStatus\":[{\"podName\":\"mariadb-0\",\"podStatus\":\"Running\",\"workloadName\":\"mariadb\",\"workloadType\":\"StatefulSet\"}],\"lastPodRefAt\":\"\"}",
    "RecurringJob": "restored-recurring-job-fe3ec17624033ffa",
    "VolumeRecurringJobInfo": "{\"backup\":{\"jobSpec\":{\"name\":\"backup\",\"groups\":[\"default\"],\"task\":\"backup\",\"cron\":\"0 2 * * *\",\"retain\":7,\"concurrency\":1},\"fromGroup\":[\"default\"],\"fromJob\":false},\"restored-recurring-job-b942e1756afafbd1\":{\"jobSpec\":{\"name\":\"restored-recurring-job-b942e1756afafbd1\",\"groups\":[\"default\"],\"task\":\"snapshot\",\"cron\":\"38 */12 * * *\",\"retain\":2,\"concurrency\":1},\"fromGroup\":[\"default\"],\"fromJob\":false},\"restored-recurring-job-d492cb5c84a7b09e\":{\"jobSpec\":{\"name\":\"restored-recurring-job-d492cb5c84a7b09e\",\"groups\":[\"default\"],\"task\":\"backup\",\"cron\":\"0 2 * * *\",\"retain\":7,\"concurrency\":1},\"fromGroup\":[\"default\"],\"fromJob\":false},\"restored-recurring-job-fe3ec17624033ffa\":{\"jobSpec\":{\"name\":\"restored-recurring-job-fe3ec17624033ffa\",\"groups\":[\"default\"],\"task\":\"backup\",\"cron\":\"0 2 * * *\",\"retain\":7,\"concurrency\":1},\"fromGroup\":[\"default\"],\"fromJob\":false},\"snapshot\":{\"jobSpec\":{\"name\":\"snapshot\",\"groups\":[\"default\"],\"task\":\"snapshot\",\"cron\":\"38 */12 * * *\",\"retain\":2,\"concurrency\":1},\"fromGroup\":[\"default\"],\"fromJob\":false}}",
    "longhorn.io/volume-access-mode": "rwo"
  },
  "CreatedTime": "2023-10-12T02:32:38Z",
  "LastBackupName": "backup-8417093ca8854143",
  "LastBackupAt": "2024-01-13T09:04:34Z",
  "BlockCount": "5711",
  "BackingImageName": "\"\"",
  "BackingImageChecksum": "\"\"",
  "CompressionMethod": "\"gzip\"",
  "StorageClassName": "\"longhorn\""
}

```

## Environment

 - Longhorn version: 1.6.0-dev at the moment, though I've tried restoring the backup from 1.4.0, 1.4.4, 1.5.3 as well.
 - Impacted volume (PV): pvc-2925f092-964d-4f62-9c4f-941f39605413
 - Installation method: kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s  v1.28.5+k3s1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 4
 - Node config
   - OS type and version: ubuntu 22.04
   - Kernel version: 5.15.0
   - CPU per node: varies
   - Memory per node: varies
   - Disk type (e.g. SSD/NVMe/HDD): HDD
   - Network bandwidth between the nodes (Gbps): 1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Bare metal
 - Number of Longhorn volumes in the cluster: 14

## Additional context

It's a dev cluster with mixed arm64/amd64, though everything is on ubuntu.

**Comment by derekbit** [comment] 2024-01-15 15:03
Please provide a support bundle, volume and backup config files of the volume. I think it is due to the volume backup is compressed by lz4. 
BTW, what's the purpose of o using restore_to_file?

**Comment by derekbit** [comment] 2024-01-17 00:02
> the issue impacts every backup for this volume since I moved to 1.6.0-dev in October. Backups from other volumes or from this volume before the move can restore fine.

This is due to that the backup is incremental. If one of backup files corrupted, backups using the corrupted file will fail to restore. I've created a ticket for the issue https://github.com/longhorn/longhorn/issues/7070.

I think it is not due to NFS and gzip. The issue is usually due to the silent data corruption caused by the underlying storage related to memory, disk and so on.

> Personally I think it would be helpful to inspect one of the broken backups directly; I'm happy to take any further steps you think would be helpful here or even (privately) link to a broken backup for you to inspect.

Sure. I will check the information you provided and prepare a script for helping find and inspect the problematic backup file if necessary.

**Comment by thejaykobe** [comment] 2024-04-16 16:54
Posting a support bundle here.
[supportbundle_115e29e8-9a7a-4725-b9f6-1d336837655a_2024-04-16T16-09-56Z.zip](https://github.com/longhorn/longhorn/files/15000150/supportbundle_115e29e8-9a7a-4725-b9f6-1d336837655a_2024-04-16T16-09-56Z.zip)

As directed by @derekbit 

Do we know if the data is retrievable at all? I really need it ASAP.

**Comment by derekbit** [comment] 2024-04-17 01:07
@thejaykobe Can you reach out to me on Rancher or CNCF slack channel to speed up the troubleshooting process? Thank you.

**Comment by derekbit** [comment] 2024-04-17 03:26
@ohthehugemanatee 
Sorry for the late reply.
Does the problematic volume and backup still exist?

**Comment by derekbit** [comment] 2024-04-17 11:38
@ohthehugemanatee 

Can you try to restore the problematic backup and volume by the [restore-backup-to-file.sh](https://raw.githubusercontent.com/longhorn/longhorn/v1.5.x/scripts/restore-backup-to-file.sh) by specifying `--version v1.5.x-head`? The usage is in the doc https://longhorn.io/docs/1.7.0/advanced-resources/data-recovery/recover-without-system/.

I expect the restoration will fail and please send us the log of the restore process. Thank you.

**Comment by derekbit** [comment] 2024-04-17 15:36
I went through @ohthehugemanatee's support bundle again.

Just realized the engine of the volume `pvc-2925f092-964d-4f62-9c4f-941f39605413` is v1.4.0. All backups and the failed restoration are run using v1.4.0. v1.4.0 only supports gzip, and the issue is not related to lz4 introduced in v1.5.0.

**Comment by ChanYiLin** [comment] 2024-04-19 15:31
Hi @thejaykobe 
If your backupstore is using s3
Can you download the backupvolume to the local environment
The path pattern should be like
```
<backup store work directory>/backupstore/volumes/
    <2 random characters>/<2 random characters>/<backup volume name>/
        volume.cfg
        backups/
            backup1.cfg
            backup2.cfg
            ......
        blocks/
            <2 random characters>/<2 random characters>/
                <backup data, 2MB block, the name is the checksum>.blk
            <2 random characters>/<2 random characters>/
                <backup data, 2MB block, the name is the checksum>.blk
            ......
```

After downloading to the local, the folder structure should be like
```
$ ll {VOLUME_NAME}/
- backups/
- blocks/
- volume.cfg
```

Then, install `lz4`  and `gzip` in your local environment

Now, you can run the script [here](https://github.com/longhorn/longhorn/issues/7069#issuecomment-1802248632) to detect the corrupted file.
By analyzing the corrupted file we might find out how to fix the compression `gzip: invalid header` issue

Thanks!

**Comment by derekbit** [comment] 2024-04-30 00:08
I worked with @thejaykobe during these two weeks and have successfully restored the volume.

What I found 
- The original volume is gone, so the details are gone
- The compression method in the volume config is `gzip`. However, according to the information provided by @thejaykobe, the volume is created in Longhorn v1.5.3. The compression method should be `lz4`.
- The backup blocks of the volume are mostly compressed by `gzip`, but few blocks are compressed by `lz4`. The backup resources indicate all existing backups are compressed by `gzip`.

Currently, I'm unable to reproduce the issue in my environment and need more input and further investigation.

**Comment by derekbit** [comment] 2024-05-10 02:25
## Pre Ready-For-Testing Checklist
* [x] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:

We are still investigating the root cause of the issue.
The PRs improve the resilience in the decompression path.

The following test cases need to be tested in S3, Azure and NFS backupstore.

- Test case 1
  1. Create a volume in LH v1.4.x, write data and take backup multiple times
  1. Update to v1.6.x, restore the backups. The restoration should succeed and then verify data.

- Test case 2
  1. Create a volume in LH v1.6.x, write data and take backup multiple times
  1. Update to v1.6.x, restore the backups. The restoration should succeed and then verify data.

- Test Case 3
  1. The test cases in e2e related to backup/restore should pass
 
- Test Case 4
  1. Create a new 10GiB volume and write 5GiB data by `dd`
  2. Backup volume and restore it. Verify the checksum.
  3. Login to the backupstore. Update compressionMethod in `volume.cfg` and `backup_*.cfg` to `gzip`.
  4. Restore the volume and verify the checksum.
  5. Also check if there is any memory leak in instance-manager pods by `kubectl -n longhorn-system top pods`.

- Test case 5
   1. Test backing images and restore as the steps in Test Case 4

- Test Case 6
  1. Set global setting `backup-compression-method` to `gzip`
  1. Create a new 10GiB volume and write 5GiB data by `dd`
  2. Backup volume and restore it. Verify the checksum.
  3. Login to the backupstore. Update compressionMethod in `volume.cfg` and `backup_*.cfg` to `lz4`.
  4. Restore the volume and verify the checksum.
  5. Also check if there is any memory leak in instance-manager pods by `kubectl -n longhorn-system top pods`.

- Test case 7
   1. Test backing images and restore as the steps in Test Case 6


* [x] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at

https://github.com/longhorn/backupstore/pull/167
https://github.com/longhorn/longhorn-engine/pull/1076
https://github.com/longhorn/backupstore/pull/172

* [ ] Which areas/issues this PR might have potential impacts on?
Area: backup and restore
Issues

**Comment by roger-ryao** [comment] 2024-05-20 09:58
**Verified on master-head 20240520**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/5a3c410218e4152c6302ed12cde1cfa6ed1ec446
- longhorn-engine `master-head` https://github.com/longhorn/longhorn-engine/commit/e39b7f0313b22d5c435ce57d1442800999a0f4ac
- backupstore `master-head` https://github.com/longhorn/backupstore/commit/3bce6e69af1514165c17e6949f8736d9f69aabf2

**The test steps**
https://github.com/longhorn/longhorn/issues/7687#issuecomment-2103744408

**Result Passed**

- [x] Test case 1
  1. Create a volume in LH `v1.4.x`, write data and take backup multiple times
  2. Update to `v1.5.x` and then to `v1.6.x` and then to `master`, restore the backups. The restoration succeeded.

- [x] Test case 2
  1. Create a volume in LH `v1.6.1`, write data and take backup multiple times
  2. Update to `master-head`, restore the backups. The restoration succeeded.

- [x] Test case 3 
  1. Back up backing images and restore it
 
- [x] Test case 4
- [x] Test case 5
- [x] Test case 6
- [x] Test case 7
  1. For cases 4-7, we didn't observe any memory leaks in the instance-manager pods on `master-head`.
  2. For cases 4-7, we could use the below scripts in the MinIO or NFS pod bash mode

```bash
echo '#!/bin/sh

# Check if a file path parameter is provided
if [ -z "$1" ]; then
  echo "Please provide a file path as a parameter."
  exit 1
fi

# File path
file_path="$1"

# Read the file content and replace
cat "$file_path" | sed "s/lz4/gzip/g" > /tmp/tempfile

# Write the replaced content back to the original file
cat /tmp/tempfile > "$file_path"

# Remove the temporary file
rm /tmp/tempfile

echo "Replacement completed: $file_path"' > replace_lz4_with_gzip.sh

echo '#!/bin/sh

# Check if a file path parameter is provided
if [ -z "$1" ]; then
  echo "Please provide a file path as a parameter."
  exit 1
fi

# File path
file_path="$1"

# Read the file content and replace
cat "$file_path" | sed "s/gzip/lz4/g" > /tmp/tempfile

# Write the replaced content back to the original file
cat /tmp/tempfile > "$file_path"

# Remove the temporary file
rm /tmp/tempfile

echo "Replacement completed: $file_path"' > replace_gzip_with_lz4.sh
```

**Closed by roger-ryao** 2024-05-20 09:58 UTC
Labels: kind/bug, area/volume-backup-restore, investigation-needed, area/resilience, require/qa-review-coverage, require/backport, backport/1.5.5, backport/1.6.2, backport/1.5.6
