### ISSUE TITLE
[BUG] During volume live engine upgrade, if the replica pod is killed, the volume is stuck in upgrading forever

### ISSUE THREAD

**Issue by dgiebert** [longhorn/longhorn#5684] opened 2023-03-30 12:49 UTC
## Describe the 🐛

During volume live engine upgrade, if the replica pod is killed, the volume is stuck in upgrading forever.

## To Reproduce

- Install Longhorn v1.3.1 into a 3-nodes cluster
- Create a volume and attach it to a node
- Upgrade Longhorn to v1.3.2 or v1.3.3-rc2
- Upgrade the engine for the volume
- At the same time, kill the instance-manager-r pod on the node 
- The volume is stuck in the upgrading process forever

## Expected behavior

As soon as the instance-manager-r pod is restarted, the upgrade should continue and succeed.

**Comment by innobead** [comment] 2023-03-30 13:41
> * Upgrade the engine for the volume
> * At the same time, kill the instance-manager-r pod on the node

@PhanLe1010 In this case, it seems that the volume already had all migrating replicas in `engine.spec.upgradedReplicaAddressMap`, but later the new IM pod got deleted, so it became stuck in retrying upgrading engine. 

The fix of https://github.com/longhorn/longhorn/issues/5618 focuses on the upgrading of replicas that have not yet been created, so it gets fixed, but in this case, it is the opposite.

**Comment by PhanLe1010** [comment] 2023-04-01 00:05
From the logs of engine instance manager: there is no backend (replica available) even though we only crash one replica:
```
2023-03-31T23:40:36.511594810Z [testvol1-e-f6779de8] time="2023-03-31T23:40:36Z" level=warning msg="Failed to create backend with address tcp://10.42.117.113:10015" error="failed to get replica 10.42.117.113:10015 info from remote: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.117.113:10015: i/o timeout\""
2023-03-31T23:40:36.511618566Z time="2023-03-31T23:40:36Z" level=info msg="Connecting to remote: 10.42.234.98:10015"
2023-03-31T23:40:36.513870315Z [testvol1-e-f6779de8] time="2023-03-31T23:40:36Z" level=warning msg="Failed to create backend with address tcp://10.42.234.98:10015" error="replica must be closed, cannot add in state: dirty"
2023-03-31T23:40:36.513902307Z time="2023-03-31T23:40:36Z" level=info msg="Connecting to remote: 10.42.152.41:10015"
2023-03-31T23:40:36.516459138Z [testvol1-e-f6779de8] time="2023-03-31T23:40:36Z" level=warning msg="Failed to create backend with address tcp://10.42.152.41:10015" error="replica must be closed, cannot add in state: dirty"
...
2023-03-31T23:40:36.516503223Z time="2023-03-31T23:40:36Z" level=error msg="no available backend due to service unavailable from the addresses [tcp://10.42.117.113:10015 tcp://10.42.234.98:10015 tcp://10.42.152.41:10015]"
```

It looks like other newly migrating replica cannot be added because they are dirty. I am investigating to see why they are dirty and if dirty replica condition should be a blocking condition

**Comment by PhanLe1010** [comment] 2023-04-05 00:48
# Root Cause Analysis 

## Case 1: Replicas on deleted pod becomes error before the engine starts doing upgrading
Updating ... 

## Case 1: Replicas on deleted pod becomes error after the engine starts doing upgrading
In this case, we hit the issue with the logs https://github.com/longhorn/longhorn/issues/5684#issuecomment-1492745713

### Why are replicas dirty during the engine live upgrade even though there is no IO coming into the replica yet? 
Updating ... 

### Why is the engine live upgrade blocked by the dirty replicas?
Updating ...

**Comment by PhanLe1010** [comment] 2023-04-06 23:55
Test plan:
Same as in the issue description but make sure that:
1. The engine upgrade eventually finishes.
2. The volume has some data before the upgrade and verifies the data are consistent after the upgrade

**Comment by PhanLe1010** [comment] 2023-04-07 05:15
@dgiebert The fix has been merged. Could you help to test using the `1.3.x` branch?
More specifically, using [this chart ](https://github.com/longhorn/longhorn/blob/v1.3.x/chart/values.yaml) but replace Helm value 
* `v.1.3.3-rc2` by `v1.3.x-head`
* `v1_20230317` by `v1_20230407`

**Comment by yangchiu** [comment] 2023-04-20 03:00
Verified passed on master-head (longhorn-manager b1b4fc0) following [the test steps](https://github.com/longhorn/longhorn/issues/5684#issue-1647554849).

Upgrade longhorn from v1.3.1 to master-head, delete instance-manager-r pod won't cause upgrading gets stuck, and volume data remains intact.

**Closed by yangchiu** 2023-04-20 03:00 UTC
Labels: kind/bug, area/manager, priority/0, backport/1.3.3, area/volume-upgrade, backport/1.4.2
