### ISSUE TITLE
[BUG] Backup restore succeeds when an instance manager engine crashes and data is NOT available in the restore volume

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1336] opened 2020-05-13 18:29 UTC
**Describe the bug**
Backup restore succeeds when an instance manager engine crashes and data is NOT available in the restore volume

**To Reproduce**

- Have a volume v1 - with 3 replicas
- write data into the volume
- Take a backup
- Restore from the backup
- While the restore is in progress, delete instance manager engine running the volume.
- The restore succeeds.
- Data is NOT available in the volume.

**Expected behavior**
@yasker Should the restore fail in this case? And the volume be shown as "Faulted" ?

**Log**
[longhorn-support-bundle_f7248c7c-cbac-44c3-b611-48b17218f97b_2020-05-13T18-25-27Z.zip](https://github.com/longhorn/longhorn/files/4623895/longhorn-support-bundle_f7248c7c-cbac-44c3-b611-48b17218f97b_2020-05-13T18-25-27Z.zip)

**Note:**
Backup is in S3

**Environment:**
 - Longhorn version: master - 05/13/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: RKE LINUX DO nodes

**Comment by yasker** [comment] 2020-05-14 17:22
@shuo-wu We need to understand why it behaviors in this way first before fixing this. The question here is why the restore was a success?

**Comment by shuo-wu** [comment] 2020-05-15 04:03
There are some weird/wrong behaviors after deleting the engine manager:
1. Stopping the errored engine takes a long time (about 1 minute).
2. The volume will be reattached automatically.
3. The volume will become `Ready` after the automatic reattachment and detachment.

Ideally, the engine should be `stopped `and the volume should be Faulted after the engine manager deletion. And this shouldn't take a long time.

**Comment by shuo-wu** [comment] 2020-05-18 10:58
The explanations for the issue and the behaviors mentioned above:
1. Since there is no process existing in the newly recreated engine manager, the engine manager needs to wait for 60s to refresh the instance map. This part is fine and we don't need to do anything for it.

2. When the Longhorn tries to reattach the volume, `v.Status.CurrentNodeID` will be cleaned up since the volume needs to be detached first. But the auto attachment logic (for restore volumes and expanding volumes) will blindly set `v.Status.CurrentNodeID = v.Status.OwnerID` once `v.Status.CurrentNodeID` is ready. Then this volume gets stuck in the detach (part of auto reattach) and auto-attach loop. BUG!
```
......
[longhorn-manager-mjcwx] time="2020-05-18T09:43:07Z" level=warning msg="Engine of volume vol3 dead unexpectedly, reattach the volume"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:07Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"vol3\", UID:\"943c235c-f953-4f05-adf6-8e7001f647f5\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"10947215\", FieldPath:\"\"}): type: 'Warning' reason: 'DetachedUnexpectly' Engine of volume vol3 dead unexpectedly, reattach the volume"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:31Z" level=debug msg="Instance handler updated instance vol3-e-14ba4459 state, old state error, new state stopped"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:31Z" level=info msg="----------------Volume vol3 current state is updated from detaching to attaching"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:31Z" level=debug msg="Prepare to create instance vol3-e-14ba4459"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:31Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"vol3-e-14ba4459\", UID:\"9ae8a872-b776-46ea-b44a-775d5f4c33ec\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"10947431\", FieldPath:\"\"}): type: 'Normal' reason: 'Start' Starts vol3-e-14ba4459"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:31Z" level=debug msg="Instance process vol3-e-14ba4459 had been created, need to wait for instance manager update"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:32Z" level=debug msg="Instance process vol3-e-14ba4459 had been created, need to wait for instance manager update"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:32Z" level=debug msg="Instance handler updated instance vol3-e-14ba4459 state, old state stopped, new state starting"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:33Z" level=debug msg="Instance vol3-e-14ba4459 starts running, IP 10.42.2.234"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:33Z" level=debug msg="Instance vol3-e-14ba4459 starts running, Port 10000"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:33Z" level=debug msg="Instance handler updated instance vol3-e-14ba4459 state, old state starting, new state running"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:33Z" level=debug msg="Start monitoring vol3-e-14ba4459"
[longhorn-manager-mjcwx] time="2020-05-18T09:43:33Z" level=info msg="----------------Volume vol3 current state is updated from attaching to attached"
```

3. Due to the above BUG, as long as the engine becomes `Stopped`, `v.Status.CurrentNodeID` will be immediately set by the auto attach logic and won't be cleaned up by the auto reattach logic. Then Longhorn won't stop all replicas and wait for the volume becoming `Detached` before (re)attaching the volume. This means **all replicas keep `running` and wrongly finish the restore during the engine restart**. When the volume is reattached, those replicas will report restore complete and the volume will be wrongly marked as `Ready` for workloads. False-positive here!
```
[longhorn-instance-manager] time="2020-05-18T09:41:45Z" level=info msg="Process Manager: prepare to create process vol3-r-3fe3d6c2"
[longhorn-instance-manager] time="2020-05-18T09:41:45Z" level=info msg="Process Manager: created process vol3-r-3fe3d6c2"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:45Z" level=info msg="Creating volume /host/var/lib/longhorn/replicas/vol3-92d81037, size 2147483648/512"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:45Z" level=info msg="Listening on gRPC Replica server 0.0.0.0:10000"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:45Z" level=info msg="Listening on data server 0.0.0.0:10001"
time="2020-05-18T09:41:45Z" level=info msg="Listening on sync agent server 0.0.0.0:10002"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:45Z" level=info msg="Listening on sync 0.0.0.0:10002"
[longhorn-instance-manager] time="2020-05-18T09:41:45Z" level=info msg="Process vol3-r-3fe3d6c2 has started at localhost:10000"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:47Z" level=info msg="New connection from: 10.42.2.221:47358"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:47Z" level=info msg="Opening volume /host/var/lib/longhorn/replicas/vol3-92d81037, size 2147483648/512"
[vol3-r-3fe3d6c2] time="2020-05-18T09:41:51Z" level=info msg="Successfully initiated restore for s3://backupbucket@us-east-1/backupstore?backup=backup-f0a33111b9614af7&volume=pvc-0af64609-b5e8-4ac0-9f36-94044bc68db5 to [volume-snap-00d4d3a5-32f3-47dc-92ab-64675e3c2601.img]"
[vol3-r-3fe3d6c2] time="2020-05-18T09:42:15Z" level=info msg="Closing volume"
[vol3-r-3fe3d6c2] time="2020-05-18T09:42:25Z" level=info msg="Restore completed successfully in Server"
time="2020-05-18T09:42:25Z" level=info msg="Reverting to snapshot volume-snap-00d4d3a5-32f3-47dc-92ab-64675e3c2601.img on 0.0.0.0:10000 at 2020-05-18T09:42:25Z"
[vol3-r-3fe3d6c2] time="2020-05-18T09:42:25Z" level=info msg="Reverting to snapshot volume-snap-00d4d3a5-32f3-47dc-92ab-64675e3c2601.img on 0.0.0.0:10000 successful"
[vol3-r-3fe3d6c2] time="2020-05-18T09:42:25Z" level=info msg="Done running restore s3://backupbucket@us-east-1/backupstore?backup=backup-f0a33111b9614af7&volume=pvc-0af64609-b5e8-4ac0-9f36-94044bc68db5 to volume-snap-00d4d3a5-32f3-47dc-92ab-64675e3c2601.img"
```

4. The reason why I say `all replicas keep running and wrongly finish the restore` is that the replica server will be closed once the old engine process is down. Then the `Revert` operation or data write operation for the restore doesn't make sense. NOT SURE if this should be considered as a bug.
```
[vol3-r-3fe3d6c2] time="2020-05-18T09:42:15Z" level=info msg="Closing volume"
[vol3-r-3fe3d6c2] time="2020-05-18T09:42:25Z" level=info msg="Restore completed successfully in Server"
time="2020-05-18T09:42:25Z" level=info msg="Reverting to snapshot volume-snap-00d4d3a5-32f3-47dc-92ab-64675e3c2601.img on 0.0.0.0:10000 at 2020-05-18T09:42:25Z"
```

Ideally, Longhorn should mark the volume as Faulted without the reattachment. But we are not sure if there are some side effects hence the following **workaround may work** now:
- Add `v.Status.PendingNodeID` check in the auto attach logic. 
- In that case, all replicas will be stopped before the volume reattachment. Then the restore won't be restarted and there is no restore status in the re-launched replicas after the attachment. Finally, the reattached volume will get stuck there with `Not Ready` status.

**Comment by shuo-wu** [comment] 2020-05-19 05:53
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by sowmyav27** [comment] 2020-05-19 23:48
**Validating on master - 05/19/2020 - 16:30 PDT**

**Steps:**

- Setup a backupstore on S3
- Create volume and attach to a workload
- Write random data to the pod volume and get the md5sum.
- Create a backup for the volume.
- Restore a new volume from the backup.
- Crash the engine during the restore - delete instance manager engine on the node where volume is attached.
- Wait for the volume detaching.
- Wait for the volume reattached.
- Volume should be in detached state after restore is complete.
- Attach this restored volume to a new workload.
- Verified data is intact.

**Closed** 2020-05-19 23:48 UTC
Labels: area/engine, area/manager, bug
