### ISSUE TITLE
[FEATURE] Shrinking Volumes

### ISSUE THREAD

**Issue by timmy59100** [longhorn/longhorn#1132] opened 2020-03-23 22:59 UTC
As described in the documentation, a volume shrink is not possible at the moment.
After for example cleaning the content of a volume it would be great to shrink the volume itself so it does not take huge amounts of space on the disk.
It would be ok, if it's only possible for a offline volume.

**Comment by timmy59100** [comment] 2020-05-25 20:11
Would be something like this be possible?

**Comment by yasker** [comment] 2020-05-25 21:24
@timmy59100 There are a few scenarios:
1. Space taken by the extra snapshots. For example, the whole volume size might exceed the nominal size of the volume if there are multiple snapshots. The user can free up space by deleting snapshots or scheduling a recurring snapshot.
2. Space taken by the volume. For example, the volume has a nominal size of 20G, but the whole volume was written over, in the end the volume will take 20G of the space but 1G of the data exists in the filesystem. Those are unlikely to be freed up at the moment. This case was discussed on https://github.com/longhorn/longhorn/issues/836 .

Which scenario is likely your case?

**Comment by timmy59100** [comment] 2020-05-26 20:15
It would be the second scenario. At the moment we have to avoid spikes in data usage to not bloat the space on disk, backup or replica.

**Comment by yasker** [comment] 2020-05-26 21:57
@timmy59100 so instead of creating 20G volume at first, does create e.g 2G volume work for your scenario? Or maybe you don't have the control over the volume size.

**Comment by timmy59100** [comment] 2020-07-08 11:05
@yasker It seems the volume size is irrelevant here because, we have one volume where the size is 20Gi. The Actual Size is 40 Gi. There are no snapshots.

**Comment by yasker** [comment] 2020-07-08 15:48
@timmy59100 There is a button next to the snapshot tree, `show hidden`. There should be some snapshots once you click that.

**Comment by eminalemdar** [comment] 2021-08-13 07:26
We are having issues with Volume Shrinking. Can you open this Feature? Is it on your roadmap?

**Comment by jenting** [comment] 2021-11-02 00:27
Same issue to #836

**Comment by innobead** [comment] 2021-11-02 02:25
Closing due to a duplicate of #836

**Closed by innobead** 2021-11-02 02:25 UTC
Labels: kind/enhancement

**Comment by dberardo-com** [comment] 2023-10-19 07:36
reclaim space is not the same as shrinking the volume. 

is it possible to reduce the volume of the PVC made on longhorn volume? so that if a volume was 30 GB before, now it can become 25 G?

and also: is it possible  to perform this operation on non-trimming-capable disks such as HDD ?

**Comment by dberardo-com** [comment] 2025-03-04 18:18
Any update on this? Would be nice to see size shrinking available besides trimming

**Comment by derekbit** [comment] 2025-03-05 00:41
> Any update on this? Would be nice to see size shrinking available besides trimming

It is a limitation of Kubernetes. Kubernetes does not support shrinking a PVC to less than its current size.
Ref: https://kubernetes.io/docs/concepts/storage/persistent-volumes/
