### ISSUE TITLE
Enhance Kubernetes node recovery speed up to support auto-detach deployment pod's volume when the node is down

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#820] opened 2019-10-15 19:13 UTC
After #793 is fixed, the Kubernetes controller cannot handle the volumes on the down node since the `ownerID` of those volumes won't change after node down. Then [the feature disaster recovery speeding up](https://github.com/longhorn/longhorn-manager/wiki/Feature:-Kubernetes-integration#speed-up-disaster-recovery) doesn't work. We need to reconsider the workflow of kubernetes controller.

**Comment by yasker** [comment] 2020-05-04 04:04
We need a quick POC to check if deleting the volume attachment works for detaching the volume from deployment's old pod and make it available to the new pod. See https://github.com/longhorn/longhorn/issues/1105#issuecomment-612814811

If it's doable, we will include this feature for deployment workload in the release.

We will going to trigger the deletion of the volumeattachment when:
1. The original volume is stuck on a `NotReady` node
2. Kubernetes has decided to start another pod for the deployment on another node, which is asking for the same volume.

**Comment by yasker** [comment] 2020-05-07 18:13
Remember to test #1307 when this is fixed.

**Comment by joshimoo** [comment] 2020-05-19 05:36
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by joshimoo** [comment] 2020-05-19 06:38
It's useful to attach to the log output before starting the tests
```
kubetail longhorn-manager -n longhorn-system
kubetail longhorn-csi-plugin -n longhorn-system
```

**Testing Setup:**
- create a volume + pv + pvc named `vol1`
- create deployment of default ubuntu named `shell` with usage of pvc `vol1` mounted under `/mnt/vol1`
- wait till everything is up and running, verify volume `vol1` is accessible from shell via `/mnt/vol1`
- turn off node for workload `shell`
- wait till replacement pod is generated for workload `shell` (default is around 6 minutes, kubernetes setting)
- if volume attachment reclaim policy is set to `wait` (default) wait till volume.deletionTimestamp has passed (30s grace period after the replacement pods are created)

**Evaluation:**
- afterwards you should start seeing calls in the `longhorn-csi-plugin` there should be a Controller.UnpublishVolume request for the downed node. Then there could be a couple of Controller.PublishVolume requests for the downed node (if the new node is after the downed node) and eventually the Controller.PublishVolume request for the new node of the replacement pod followed by a NodePublishVolume.

- verify that you can access `vol1` via the `shell` replacement pod under `/mnt/vol1`
- verify `kubectl get volumeattachments` 
-- there could be 2 one attached = false for the dead node or just 1 for the replacement node depending on the node order. 
- you should be able to repeat the above process multiple times as long as you have more then 2 alive nodes, so start with a cluster > 3 nodes and wait in between till things are in a good state again.

**Example where we switch from a later node to a previous node:**
```
jmoody@dev:~$ kubectl get volumeattachments
NAME                                                                   ATTACHER             PV     NODE           ATTACHED   AGE
csi-ef23ec8f333a89da39d08bca1e159e6674f233d11f828c375e585af415e815c1   driver.longhorn.io   vol1   rancher-dev3   true       38s
jmoody@dev:~$ kubectl get volumeattachments
NAME                                                                   ATTACHER             PV     NODE           ATTACHED   AGE
csi-a9a9725d3499745a3f3f2dccba70accb8e22af941962b704d08a1ebd428c5612   driver.longhorn.io   vol1   rancher-dev1   true       61s
```


**Example of a straightforward switch:**
```
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T05:59:56Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerUnpublishVolume" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T05:59:56Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev3\",\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T05:59:56Z" level=info msg="ControllerServer ControllerUnpublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev3\" " 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T05:59:59Z" level=debug msg="Polling vol1 state for detached at 2020-05-19 05:59:59.009450465 +0000 UTC m=+1017.042814906" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T05:59:59Z" level=debug msg="Volume vol1 detached on rancher-dev3" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T05:59:59Z" level=info msg="GRPC response: {}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:41Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:41Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:41Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:41Z" level=debug msg="ControllerPublishVolume: current nodeID rancher-dev1" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:43Z" level=debug msg="Polling vol1 state for attached at 2020-05-19 06:00:43.435492356 +0000 UTC m=+1061.468856798" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=debug msg="Polling vol1 state for attached at 2020-05-19 06:00:45.435582425 +0000 UTC m=+1063.468946867" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=debug msg="Volume vol1 attached on rancher-dev1" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=info msg="GRPC response: {}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:45Z" level=info msg="ControllerPublishVolume: no need to attach volume vol1 since it's already attached to the correct node rancher-dev1" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:47Z" level=debug msg="Polling vol1 state for attached at 2020-05-19 06:00:47.482784474 +0000 UTC m=+1065.516148927" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:47Z" level=debug msg="Volume vol1 attached on rancher-dev1" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:00:47Z" level=info msg="GRPC response: {}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC call: /csi.v1.Node/NodeGetCapabilities" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC request: {}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":3}}}]}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC call: /csi.v1.Node/NodeGetCapabilities" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC request: {}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":3}}}]}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC call: /csi.v1.Node/NodePublishVolume" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="GRPC request: {\"target_path\":\"/var/lib/kubelet/pods/84166ea1-aa22-4392-9df1-36cc0682623a/volumes/kubernetes.io~csi/vol1/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"vol1\" target_path:\"/var/lib/kubelet/pods/84166ea1-aa22-4392-9df1-36cc0682623a/volumes/kubernetes.io~csi/vol1/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-pwqfh longhorn-csi-plugin] time="2020-05-19T06:01:24Z" level=debug msg="NodePublishVolume: done MountVolume vol1" 
```

**Example of a competing switch:**
```
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:31:48Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerUnpublishVolume" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:31:48Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:31:48Z" level=info msg="ControllerServer ControllerUnpublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" " 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:31:50Z" level=debug msg="Polling vol1 state for detached at 2020-05-19 06:31:50.694797149 +0000 UTC m=+2928.705785551" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:31:50Z" level=debug msg="Volume vol1 detached on rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:31:50Z" level=info msg="GRPC response: {}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=warning msg="ControllerPublishVolume: the volume vol1 cannot be attached to `NotReady` node rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=error msg="GRPC error: rpc error: code = NotFound desc = ControllerPublishVolume: the volume vol1 cannot be attached to `NotReady` node rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=warning msg="ControllerPublishVolume: the volume vol1 cannot be attached to `NotReady` node rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:19Z" level=error msg="GRPC error: rpc error: code = NotFound desc = ControllerPublishVolume: the volume vol1 cannot be attached to `NotReady` node rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:20Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:20Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:20Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:20Z" level=warning msg="ControllerPublishVolume: the volume vol1 cannot be attached to `NotReady` node rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:20Z" level=error msg="GRPC error: rpc error: code = NotFound desc = ControllerPublishVolume: the volume vol1 cannot be attached to `NotReady` node rancher-dev1" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev3\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev3\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > " 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=debug msg="ControllerPublishVolume: current nodeID rancher-dev3" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerUnpublishVolume" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="GRPC request: {\"node_id\":\"rancher-dev1\",\"volume_id\":\"vol1\"}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="ControllerServer ControllerUnpublishVolume req: volume_id:\"vol1\" node_id:\"rancher-dev1\" " 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:23Z" level=info msg="GRPC response: {}" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:25Z" level=debug msg="Polling vol1 state for attached at 2020-05-19 06:32:25.070793055 +0000 UTC m=+2963.081781457" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:27Z" level=debug msg="Polling vol1 state for attached at 2020-05-19 06:32:27.071043376 +0000 UTC m=+2965.082031778" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:29Z" level=debug msg="Polling vol1 state for attached at 2020-05-19 06:32:29.0707466 +0000 UTC m=+2967.081735022" 
[longhorn-csi-plugin-s8k6r longhorn-csi-plugin] time="2020-05-19T06:32:29Z" level=debug msg="Volume vol1 attached on rancher-dev3" 
```

**Comment by joshimoo** [comment] 2020-05-19 06:39
Some more notes below:
In general things get hairy once downed nodes come back from the dead, that's not related to this change and so far I observed things getting back to the correct state eventually.

Something odd I noticed was after longhorn-manager updates I was not able to access the mount anymore since it looked like the remount failed, so I created an issue for it here: longhorn/longhorn#1362 I am not certain whether it's related to this change or not.

Best to test all kinds of failure scenarios that you can come up with.
- Test with stateful set, to make sure that the volume attachment does not get deleted.
- Test longhorn-manager update, etc.

**Comment by joshimoo** [comment] 2020-05-19 23:19
### Testing Setup
- create a volume + pv + pvc named vol1
- create deployment of default ubuntu named shell with usage of pvc vol1 mounted under /mnt/vol1
- wait till everything is up and running, verify volume vol1 is accessible from shell via /mnt/vol1


### StatefulSet
### if Volume Attachment Recovery Policy is set to `never` | `wait` | `immediate`
- turn off node for workload shell
- wait till the `pod.deletionTimestamp` has passed (30s grace period after the replacement pods are created)
- verify no replacement pod generated
- verify via `kubectl get volumeattachments` that the VA for the statefulset pod still exists
- force delete the terminating pod
- wait till replacement pod is running
- verify that you can access `vol1` via the `shell` replacement pod under /mnt/vol1

### Deployment
### If Volume Attachment Recovery Policy is set to `never`
- turn off node for workload shell
- wait till replacement pod is generated for workload shell (default is around 6 minutes, kubernetes setting)
- wait till the `pod.deletionTimestamp` has passed (30s grace period after the replacement pods are created)
- replacement pod will be stuck in Pending state forever
- force delete the terminating pod
- wait till replacement pod is running
- verify that you can access `vol1` via the `shell` replacement pod under /mnt/vol1

### If Volume Attachment Recovery Policy is set to `wait` (default)
- turn off node for workload `shell`
- wait till `replacement pod` is generated for workload `shell` (default is around 6 minutes, kubernetes setting)
- wait till the `pod.deletionTimestamp` has passed (30s grace period after the replacement pods are created)
- verify that you can access `vol1` via the `shell` replacement pod under /mnt/vol1

### If Volume Attachment Recovery Policy is set to `immediate`
- turn off node for workload `shell`
- wait till `replacement pod` is generated for workload `shell` (default is around 6 minutes, kubernetes setting)
- verify that you can access `vol1` via the `shell` replacement pod under /mnt/vol1

**Comment by joshimoo** [comment] 2020-05-19 23:22
To make kubernetes wait less for the setup of replacement pods have a look at this [article](https://fatalfailure.wordpress.com/2016/06/10/improving-kubernetes-reliability-quicker-detection-of-a-node-down/) on how one can configure the eviction timeout. I haven't tried this yet @meldafrawi would probably be the best to ask about this setup.

**Comment by rsoika** [comment] 2020-05-20 22:08
Just made a test in my self manged cluster

 - updated longhorn release from v0.8.1  -->  v1.0.0-rc1
 - upgraded my enginge-images in longhorn to longhornio/longhorn-engine:v1.0.0-rc1
 - killed one of my nodes hosting my PostgresDB and my Application (both with longhorn volumes)
 - waited 6 minutes
    - services were rescheduled by kubernetes 
    - volumes from dead node were detached 
    - new node was able to attache the volume again
 - application is up and running again 

so after 7 minutes my postgredb service and my application (with a lucene index) was back again without any need for administrative intervention.

super great job!!
Thanks a lot for this feature

**Comment by sowmyav27** [comment] 2020-05-20 23:14
**Verified on `1.0.0-rc1`**

### Workload type: Deployment
**Immediate:**
- Have a workload deployed using longhorn volume
- change the `terminationGracePeriodSeconds: 600` in the yaml of the workload.
- Power down the node where the pod is attached on
- The replacement pod is created after 5 minutes from when the original pod goes into `Unknown` state.
- the volume is able to attach/mount and come up only after about 17 minutes.

**Expected:** It should come up in about a minute or two after 5 mins(replacement pod has come up)

**wait:**

**never:**

**Closed** 2020-05-21 03:19 UTC
Labels: area/manager, bug, enhancement, highlight, priority/1, reproduce/always, require-doc

**Comment by yasker** [comment] 2020-05-21 03:21
@sowmyav27 Can you update the manual test steps on https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan ? Probably we need a separate page for it and link it there.
