### ISSUE TITLE
[BUG] Failed replicas not cleaned up when disk is disabled

### ISSUE THREAD

**Issue by janeczku** [longhorn/longhorn#3041] opened 2021-09-21 11:03 UTC
**Describe the bug**

1. Create and attach volume
2. In Longhorn UI disable a disk containing at least one of the replicas
3. Simulate failure of that replica by deleting the volume files under /var/lib/longhorn

**Actual Result**
After grace period that failed replica is rebuild on a schedulable disk
The failed replica is never cleaned up (both the Longhorn object and the data on disk remain).
User has to manually delete the failed replica.

**Expected Result**
After replica was rebuilt the failed replica should be cleaned up automatically

0.2.0

**Comment by yasker** [comment] 2021-09-22 01:34
We have another issue tracking the cleanup after a failure: https://github.com/longhorn/longhorn/issues/685, which is tracking for v1.3.0.

I will close this as a duplicate of #685

**Closed by yasker** 2021-09-22 01:34 UTC
Labels: kind/bug
