### ISSUE TITLE
[BUG] Setting and clearing the toleration `:` leaves some down nodes in Longhorn system

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#2026] opened 2020-12-02 23:14 UTC
**Describe the bug**
In a cluster with control/etcd nodes separated from workers nodes, the control/etcd nodes become `down` state when users set then clear the special toleration `:` (which means it will tolerate every taints)

**To Reproduce**
1. Create a cluster of 4 nodes with 1 control/etcd node and 3 worker nodes
2. Install Longhorn. Set toleration `:` in Longhorn UI
3. Wait until all Longhorn components comeback, clear the toleration in Longhorn UI
4. Wait until all Longhorn components comeback. Go to `nodes` tab in Longhorn UI, see that the control/etcd node is in `down` state

**Expected behavior**
Longhorn should clean up the control/etcd node

**Environment:**
 - Longhorn version: master 12/02/2020

**Comment by PhanLe1010** [comment] 2020-12-02 23:20
The current workaround is that users can manually delete the failed Longhorn node CRs by:
```
kubectl delete nodes.longhorn.io <FAILED-NODE-NAME>  -n longhorn-system 
```

**Comment by james-munson** [comment] 2023-12-18 19:36
It may be that this issue has either been fixed or morphed into something else with the passage of time.  When I do the steps to reproduce, setting the toleration to `":"` does indeed force a general rescheduling of pods, some of which end up on the control-plane node:
```
 == k8s nodes ==
NAME                           STATUS   ROLES                       AGE     VERSION
jbm-u22-pool1-151e5e81-9wg5r   Ready    control-plane,etcd,master   3d18h   v1.25.15+rke2r2
jbm-u22-pool2-ca5a5aa4-bxbgr   Ready    worker                      3d18h   v1.25.15+rke2r2
jbm-u22-pool2-ca5a5aa4-glvzc   Ready    worker                      3d18h   v1.25.15+rke2r2
jbm-u22-pool2-ca5a5aa4-rb299   Ready    worker                      3d18h   v1.25.15+rke2r2

 == longhorn.io nodes ==
NAME                           READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
jbm-u22-pool2-ca5a5aa4-bxbgr   True    true              True          2d20h
jbm-u22-pool2-ca5a5aa4-glvzc   True    true              True          2d20h
jbm-u22-pool2-ca5a5aa4-rb299   True    true              True          2d20h

 == pods ==
csi-attacher-776c477d6f-tlrh5                       1/1     Running   0               64s     10.42.195.151   jbm-u22-pool1-151e5e81-9wg5r   <none>           <none>
csi-provisioner-7d8d8d9887-b8cr4                    1/1     Running   0               64s     10.42.195.153   jbm-u22-pool1-151e5e81-9wg5r   <none>           <none>
csi-resizer-5bfd4fb474-blk7m                        1/1     Running   0               64s     10.42.195.150   jbm-u22-pool1-151e5e81-9wg5r   <none>           <none>
csi-snapshotter-68db784d4-ctcvr                     1/1     Running   0               64s     10.42.195.149   jbm-u22-pool1-151e5e81-9wg5r   <none>           <none>
engine-image-ei-b907910b-54lzc                      1/1     Running   0               64s     10.42.195.152   jbm-u22-pool1-151e5e81-9wg5r   <none>           <none>
longhorn-csi-plugin-msdfh                           3/3     Running   0               64s     10.42.195.148   jbm-u22-pool1-151e5e81-9wg5r   <none>           <none>
```
But when the setting is cleared again, they go back meekly to the worker nodes.
```
 == k8s nodes ==
NAME                           STATUS   ROLES                       AGE     VERSION
jbm-u22-pool1-151e5e81-9wg5r   Ready    control-plane,etcd,master   3d18h   v1.25.15+rke2r2
jbm-u22-pool2-ca5a5aa4-bxbgr   Ready    worker                      3d18h   v1.25.15+rke2r2
jbm-u22-pool2-ca5a5aa4-glvzc   Ready    worker                      3d18h   v1.25.15+rke2r2
jbm-u22-pool2-ca5a5aa4-rb299   Ready    worker                      3d18h   v1.25.15+rke2r2

 == longhorn.io nodes ==
NAME                           READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
jbm-u22-pool2-ca5a5aa4-bxbgr   True    true              True          2d20h
jbm-u22-pool2-ca5a5aa4-glvzc   True    true              True          2d20h
jbm-u22-pool2-ca5a5aa4-rb299   True    true              True          2d20h

 == pods ==



```
Further, the control-plane node was never one of the nodes.longhorn.io set, and its status appears to be fine.
```
 kl get node.longhorn.io jbm-u22-pool1-151e5e81-9wg5r 
Error from server (NotFound): nodes.longhorn.io "jbm-u22-pool1-151e5e81-9wg5r" not found
```
k get node  jbm-u22-pool1-151e5e81-9wg5r -o yaml
apiVersion: v1
kind: Node
metadata:
  annotations:
    alpha.kubernetes.io/provided-node-ip: 146.190.56.64
    cluster.x-k8s.io/cluster-name: jbm-u22
    cluster.x-k8s.io/cluster-namespace: fleet-default
    cluster.x-k8s.io/machine: jbm-u22-pool1-65dc765487-9qkgn
    cluster.x-k8s.io/owner-kind: MachineSet
    cluster.x-k8s.io/owner-name: jbm-u22-pool1-65dc765487
    etcd.rke2.cattle.io/local-snapshots-timestamp: "2023-12-18T15:00:02Z"
    etcd.rke2.cattle.io/node-address: 146.190.56.64
    etcd.rke2.cattle.io/node-name: -cde1bc2e
    management.cattle.io/pod-limits: '{"cpu":"200m","memory":"192Mi"}'
    management.cattle.io/pod-requests: '{"cpu":"1225m","memory":"2320Mi","pods":"15"}'
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 10.124.0.5/20
    projectcalico.org/IPv4VXLANTunnelAddr: 10.42.195.128
    rke2.io/encryption-config-hash: start-efd353c6a2bf99b3d51614646649f9a0771596c008d74cc8099ae14a5e7eb3a9
    rke2.io/hostname: jbm-u22-pool1-151e5e81-9wg5r
    rke2.io/internal-ip: 146.190.56.64
    rke2.io/node-args: '["server","--agent-token","********","--cni","calico","--disable-kube-proxy","false","--etcd-expose-metrics","false","--etcd-snapshot-retention","5","--etcd-snapshot-schedule-cron","0
      */5 * * *","--kube-controller-manager-arg","cert-dir=/var/lib/rancher/rke2/server/tls/kube-controller-manager","--kube-controller-manager-arg","secure-port=10257","--kube-controller-manager-extra-mount","/var/lib/rancher/rke2/server/tls/kube-controller-manager:/var/lib/rancher/rke2/server/tls/kube-controller-manager","--kube-scheduler-arg","cert-dir=/var/lib/rancher/rke2/server/tls/kube-scheduler","--kube-scheduler-arg","secure-port=10259","--kube-scheduler-extra-mount","/var/lib/rancher/rke2/server/tls/kube-scheduler:/var/lib/rancher/rke2/server/tls/kube-scheduler","--node-label","rke.cattle.io/machine=09b89719-1c9c-4222-aef6-94601d5fb41c","--node-taint","node-role.kubernetes.io/control-plane:NoSchedule","--node-taint","node-role.kubernetes.io/etcd:NoExecute","--private-registry","/etc/rancher/rke2/registries.yaml","--protect-kernel-defaults","false","--token","********"]'
    rke2.io/node-config-hash: SG666XHEYZ62UENCBAKYNM6673XAFAYJ37PCIQWUDATYUODRGQPQ====
    rke2.io/node-env: '{}'
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2023-12-15T00:54:07Z"
  finalizers:
  - wrangler.cattle.io/node
  - wrangler.cattle.io/managed-etcd-controller
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/instance-type: rke2
    beta.kubernetes.io/os: linux
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: jbm-u22-pool1-151e5e81-9wg5r
    kubernetes.io/os: linux
    node-role.kubernetes.io/control-plane: "true"
    node-role.kubernetes.io/etcd: "true"
    node-role.kubernetes.io/master: "true"
    node.kubernetes.io/instance-type: rke2
    plan.upgrade.cattle.io/system-agent-upgrader: 7dbfe3bc7aa1f9e217597840afda8c191bdef89403968ed04de99eec
    rke.cattle.io/machine: 09b89719-1c9c-4222-aef6-94601d5fb41c
  name: jbm-u22-pool1-151e5e81-9wg5r
  resourceVersion: "2450457"
  uid: 90e8597b-c149-43b6-9139-22bb3b5ed7cb
spec:
  podCIDR: 10.42.0.0/24
  podCIDRs:
  - 10.42.0.0/24
  providerID: rke2://jbm-u22-pool1-151e5e81-9wg5r
  taints:
  - effect: NoSchedule
    key: node-role.kubernetes.io/control-plane
  - effect: NoExecute
    key: node-role.kubernetes.io/etcd
status:
  addresses:
  - address: 146.190.56.64
    type: InternalIP
  - address: jbm-u22-pool1-151e5e81-9wg5r
    type: Hostname
  allocatable:
    cpu: "2"
    ephemeral-storage: "78900761129"
    hugepages-2Mi: "0"
    memory: 4018124Ki
    pods: "110"
  capacity:
    cpu: "2"
    ephemeral-storage: 81106868Ki
    hugepages-2Mi: "0"
    memory: 4018124Ki
    pods: "110"
  conditions:
  - lastHeartbeatTime: "2023-12-15T00:55:22Z"
    lastTransitionTime: "2023-12-15T00:55:22Z"
    message: Calico is running on this node
    reason: CalicoIsUp
    status: "False"
    type: NetworkUnavailable
  - lastHeartbeatTime: "2023-12-18T19:35:55Z"
    lastTransitionTime: "2023-12-15T00:54:05Z"
    message: kubelet has sufficient memory available
    reason: KubeletHasSufficientMemory
    status: "False"
    type: MemoryPressure
  - lastHeartbeatTime: "2023-12-18T19:35:55Z"
    lastTransitionTime: "2023-12-15T00:54:05Z"
    message: kubelet has no disk pressure
    reason: KubeletHasNoDiskPressure
    status: "False"
    type: DiskPressure
  - lastHeartbeatTime: "2023-12-18T19:35:55Z"
    lastTransitionTime: "2023-12-15T00:54:05Z"
    message: kubelet has sufficient PID available
    reason: KubeletHasSufficientPID
    status: "False"
    type: PIDPressure
  - lastHeartbeatTime: "2023-12-18T19:35:55Z"
    lastTransitionTime: "2023-12-15T00:55:18Z"
    message: kubelet is posting ready status. AppArmor enabled
    reason: KubeletReady
    status: "True"
    type: Ready
  daemonEndpoints:
    kubeletEndpoint:
      Port: 10250
  images:
  - names:
    - docker.io/rancher/rancher-agent@sha256:992e1f2c8131e12456dd15fef45cd6308859c42be4fa39b80180592fd888d2b8
    - docker.io/rancher/rancher-agent:v2.7.4
    sizeBytes: 436600368
  - names:
    - docker.io/rancher/hardened-kubernetes@sha256:afd6bfa5b6b8b3f907be8437ee6472f35958662fa227462756ce0d1174b2ecc7
    - docker.io/rancher/hardened-kubernetes:v1.25.15-rke2r2-build20231102
    sizeBytes: 214396534
  - names:
    - docker.io/longhornio/longhorn-engine@sha256:a087938ab55640b5561cd6d84ecafb6787cc6e81db2dbec52c08c5aa57c93089
    - docker.io/longhornio/longhorn-engine:master-head
    sizeBytes: 129094759
  - names:
    - docker.io/longhornio/longhorn-manager@sha256:47bf326dc65be10ca63cbca549dbaf08a4dfc5828e15749ecedf224bb0a8b193
    - docker.io/longhornio/longhorn-manager:master-head
    sizeBytes: 111285754
  - names:
    - docker.io/rancher/mirrored-calico-cni@sha256:d4ed12d28127c9570bf773016857c8cdc20d7862eaebd74d3d0fc7b345cc74f7
    - docker.io/rancher/mirrored-calico-cni:v3.26.1
    sizeBytes: 93375345
  - names:
    - docker.io/rancher/klipper-helm@sha256:b0b0c4f73f2391697edb52adffe4fc490de1c8590606024515bb906b2813554a
    - docker.io/rancher/klipper-helm:v0.8.2-build20230815
    sizeBytes: 90877642
  - names:
    - docker.io/rancher/mirrored-calico-node@sha256:65dfcd7a75c52ae5303af4b03d24d522133d7ec1135e1855ea9ee35ebec33ce2
    - docker.io/rancher/mirrored-calico-node:v3.26.1
    sizeBytes: 86591907
  - names:
    - docker.io/rancher/hardened-etcd@sha256:c4d25c075d5d61b1860ae5496d1acc8f88dd3a8be6024b37207901da744efa08
    - docker.io/rancher/hardened-etcd:v3.5.9-k3s1-build20230802
    sizeBytes: 64402047
  - names:
    - docker.io/rancher/hardened-coredns@sha256:3bbaf490bb8cd2d5582f6873e223bb2acec83cbcef88b398871f27a88ee1f820
    - docker.io/rancher/hardened-coredns:v1.10.1-build20230607
    sizeBytes: 64397511
  - names:
    - docker.io/rancher/rke2-cloud-provider@sha256:e2d98791f28b7aed3ab99afb99b52310eb1a36844b9bc9c497ebce327e4c68d5
    - docker.io/rancher/rke2-cloud-provider:v1.26.3-build20230406
    sizeBytes: 63663048
  - names:
    - docker.io/rancher/hardened-cluster-autoscaler@sha256:462d646604da3600521bff37608e1c03af322c30983c97c039fdc4afb7b69836
    - docker.io/rancher/hardened-cluster-autoscaler:v1.8.6-build20230609
    sizeBytes: 58304503
  - names:
    - docker.io/rancher/mirrored-calico-kube-controllers@sha256:5e0df66c5028b9cab397e44970f747023d0fe5f9162c95920689248650f8a6d6
    - docker.io/rancher/mirrored-calico-kube-controllers:v3.26.1
    sizeBytes: 32799621
  - names:
    - docker.io/longhornio/csi-provisioner@sha256:5005886e5beb365ce41b2c688d156be13da7f57d35b0894064b3d3db987f601a
    - docker.io/longhornio/csi-provisioner:v3.6.0
    sizeBytes: 28656962
  - names:
    - docker.io/rancher/mirrored-calico-typha@sha256:47b7aa28a2e5bfd847be633aa5a825e5b5489b4e333213036c468c6141debc93
    - docker.io/rancher/mirrored-calico-typha:v3.26.1
    sizeBytes: 28262748
  - names:
    - docker.io/rancher/system-agent@sha256:9bb6379007c4afd99948507f82f3b62a9c06ac889fe1baaae4ef0628249ceee3
    - docker.io/rancher/system-agent:v0.3.2-suc
    sizeBytes: 27695105
  - names:
    - docker.io/longhornio/csi-resizer@sha256:9c70e50427afd9171d43506e141eab09993642f280a835d8be3e4a8e5c8d6d88
    - docker.io/longhornio/csi-resizer:v1.9.0
    sizeBytes: 26957768
  - names:
    - docker.io/longhornio/csi-snapshotter@sha256:195d700862588836e5014dfc36d1267926c392605e296658f99691d47667395d
    - docker.io/longhornio/csi-snapshotter:v6.3.0
    sizeBytes: 26794997
  - names:
    - docker.io/longhornio/csi-attacher@sha256:649954eacbea9b0dfa3de8163bb2931bc23ab721c3f1f87d0de0488424528f54
    - docker.io/longhornio/csi-attacher:v4.4.0
    sizeBytes: 26684753
  - names:
    - docker.io/rancher/mirrored-calico-operator@sha256:5d91bf2448b434e42f074e096f6f433fcd0e41c9a4823afdeb8bfa4195196ba9
    - docker.io/rancher/mirrored-calico-operator:v1.30.4
    sizeBytes: 21216633
  - names:
    - docker.io/longhornio/csi-node-driver-registrar@sha256:698949b9997d6d2779ade2d3563951aed06e5d480426a6bc33344fdb5132050b
    - docker.io/longhornio/csi-node-driver-registrar:v2.9.0
    sizeBytes: 10755623
  - names:
    - docker.io/longhornio/livenessprobe@sha256:f0f8695d321ae8ca3e1fcb88e12a54a466a14182752212b674eb6e997bb2d14b
    - docker.io/longhornio/livenessprobe:v2.11.0
    sizeBytes: 9696399
  - names:
    - docker.io/rancher/system-upgrade-controller@sha256:f4dcde2abcaa21b72247a13bb4c063e40e9803e18a9d5bb3f38038f628cb10ff
    - docker.io/rancher/system-upgrade-controller:v0.10.0
    sizeBytes: 8592158
  - names:
    - docker.io/rancher/mirrored-calico-pod2daemon-flexvol@sha256:f490933d59c85bfb33530b762aa8040d9810e2da1c2fb3e039118bfaed2de14c
    - docker.io/rancher/mirrored-calico-pod2daemon-flexvol:v3.26.1
    sizeBytes: 7290863
  - names:
    - docker.io/rancher/pause@sha256:036d575e82945c112ef84e4585caff3648322a2f9ed4c3a6ce409dd10abc4f34
    - docker.io/rancher/pause:3.6
    sizeBytes: 299396
  nodeInfo:
    architecture: amd64
    bootID: 2a902a68-075f-4b64-897f-4ece58de1615
    containerRuntimeVersion: containerd://1.7.7-k3s1
    kernelVersion: 5.15.0-67-generic
    kubeProxyVersion: v1.25.15+rke2r2
    kubeletVersion: v1.25.15+rke2r2
    machineID: 33f7658762d7156f41d21360657ba35d
    operatingSystem: linux
    osImage: Ubuntu 22.04.2 LTS
    systemUUID: 73b0bb4a-6ea5-4664-b5a9-e42f3fdf9d11
```

**Comment by PhanLe1010** [comment] 2023-12-18 19:44
> It may be that this issue has either been fixed or morphed into something else with the passage of time.  When I do the steps to reproduce, setting the toleration to `":"` does indeed force a general rescheduling of pods, some of which end up on the control-plane node:
> ```
>  == k8s nodes ==
> NAME                           STATUS   ROLES                       AGE     VERSION
> jbm-u22-pool1-151e5e81-9wg5r   Ready    control-plane,etcd,master   3d18h   v1.25.15+rke2r2
> jbm-u22-pool2-ca5a5aa4-bxbgr   Ready    worker                      3d18h   v1.25.15+rke2r2
> jbm-u22-pool2-ca5a5aa4-glvzc   Ready    worker                      3d18h   v1.25.15+rke2r2
> jbm-u22-pool2-ca5a5aa4-rb299   Ready    worker                      3d18h   v1.25.15+rke2r2
> 
>  == longhorn.io nodes ==
> NAME                           READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
> jbm-u22-pool2-ca5a5aa4-bxbgr   True    true              True          2d20h
> jbm-u22-pool2-ca5a5aa4-glvzc   True    true              True          2d20h
> jbm-u22-pool2-ca5a5aa4-rb299   True    true              True          2d20h
> ```

Hi @james-munson ! The nodes.longhorn.io doesn't seem to be available on the master node. Did you copy the correct output?

**Comment by james-munson** [comment] 2023-12-18 19:55
That was the complete output of `kubectl -n longhorn-system get nodes.longhorn.io`

**Comment by james-munson** [comment] 2023-12-18 19:56
For what it is worth, the regression test case commented out in https://github.com/longhorn/longhorn-tests/pull/495 does still fail when enabled.  So I do need to figure out what the failure is.

**Comment by james-munson** [comment] 2023-12-18 20:27
A couple of controllers have a note in comments that 
```go
            // there is no Longhorn node created for the Kubernetes
            // node (e.g. controller/etcd node). Skip it
```
https://github.com/longhorn/longhorn-manager/blob/7aa262549f443166d63becf5f8a2ecd351e88c73/controller/backing_image_data_source_controller.go#L938
https://github.com/longhorn/longhorn-manager/blob/7aa262549f443166d63becf5f8a2ecd351e88c73/controller/instance_manager_controller.go#L906

**Comment by PhanLe1010** [comment] 2023-12-18 21:28
> Thanks, @PhanLe1010 . That was the complete output of `kubectl -n longhorn-system get nodes.longhorn.io`

Thank you for the confirm. I see why the issue no longer exist:
1. In the past, the setting  `taint-toleration` controls both user-deployed comments (longhorn-manager deamonset, longhorn-ui, longhorn driver deployer) and longhorn managed components (instance-manager, csi-xxx sidecars,..). Therefore, when users change the `taint-toleration` setting to `:` , longhorn-manager pod is also deployed on the master node. This longhorn-manager pod created a `nodes.longhorn.io` CR for master node. Then when users clear the setting `taint-toleration` setting, longhorn-manager pod is removed from master node which leaves the `nodes.longhorn.io` CR of master node in `down` state forever 
1. Now, the setting  `taint-toleration` only controls longhorn managed components(instance-manager, csi-xxx sidecars,..). Therefore, when users change the `taint-toleration` setting to `:` , longhorn-manager pod is NOT deployed on the master node. So there is no `nodes.longhorn.io` CR created for the master node. Then when users clear the setting `taint-toleration` setting, there is no leftover `nodes.longhorn.io` CR on the master node. We are good now

**Comment by PhanLe1010** [comment] 2023-12-18 21:37
> For what it is worth, the regression test case commented out in [longhorn/longhorn-tests#495](https://github.com/longhorn/longhorn-tests/pull/495) does still fail when enabled. So I do need to figure out what the failure is.

Could you provide the logs when it failed? 

Btw, I usually do this when I want to run a specific test:
1. cd into test repo. Deploy backup target `kubectl apply -f manager/integration/deploy/backupstores/`
1. Modify test.yaml at `manager/integration/deploy/test.yaml` to add a sleep command:
```yaml
spec:
  containers:
  - name: longhorn-test
    image: longhornio/longhorn-manager-test:master-head
    command: ["/bin/sh", "-c", "sleep 36000000"]
```
1. deploy the test pod `kubectl apply -f manager/integration/deploy/test.yaml`
1. exec into the test pod `k exec -it longhorn-test -- bin/bash`
1. The the specific test case `pytest -svvl test_setting.py::test_setting_toleration_extra`

**Comment by james-munson** [comment] 2023-12-18 22:54
Thanks for the tip!
I saw it fail in regression run https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5388/console

```
    def wait_for_toleration_update(core_api, apps_api, count,  # NOQA
                                   expected_tolerations,
                                   chk_removed_tolerations=[]):
        not_managed_apps = [
            "csi-attacher",
            "csi-provisioner",
            "csi-resizer",
            "csi-snapshotter",
            "longhorn-csi-plugin",
            "longhorn-driver-deployer",
            "longhorn-manager",
            "longhorn-ui",
        ]
        updated = False
        for _ in range(RETRY_COUNTS):
            time.sleep(RETRY_INTERVAL_LONG)
    
            updated = True
            if not check_workload_update(core_api, apps_api, count):
                updated = False
                continue
    
            pod_list = core_api.list_namespaced_pod(LONGHORN_NAMESPACE).items
            for p in pod_list:
                managed_by = p.metadata.labels.get('longhorn.io/managed-by', '')
                if str(managed_by) != "longhorn-manager":
                    continue
                else:
                    app_name = str(p.metadata.labels.get('app', ''))
                    assert app_name not in not_managed_apps
    
                if p.status.phase != "Running" \
                    or not check_tolerations_set(p.spec.tolerations,
                                                 expected_tolerations,
                                                 chk_removed_tolerations):
                    updated = False
                    break
            if updated:
                break
>       assert updated
E       assert False
```

**Comment by PhanLe1010** [comment] 2023-12-18 23:08
Sorry, no idea on top of my head. I would set a breakpoint at the function `wait_for_toleration_update` and manually step through the test to see where it stuck exactly and how it stuck

**Comment by james-munson** [comment] 2023-12-21 00:05
In the re-added case, the check fails on this line in 
```
56  	def check_workload_update(core_api, apps_api, count):  # NOQA
 57  	    da_list = apps_api.list_namespaced_daemon_set(LONGHORN_NAMESPACE).items
 58  	    for da in da_list:
 59  	        if da.status.updated_number_scheduled != count:
 60  ->	            return False
 ```
The item that fails is 
```
(Pdb) print(da)
{'api_version': None,
 'kind': None,
 'metadata': {'annotations': {'deprecated.daemonset.template.generation': '29',
                              'longhorn.io/last-applied-tolerations': '[{"operator":"Exists"}]'},
              'creation_timestamp': datetime.datetime(2023, 12, 15, 22, 33, 45, tzinfo=tzlocal()),
              'deletion_grace_period_seconds': None,
              'deletion_timestamp': None,
              'finalizers': None,
              'generate_name': None,
              'generation': 29,
              'labels': {'longhorn.io/component': 'engine-image',
                         'longhorn.io/engine-image': 'ei-b907910b',
                         'longhorn.io/managed-by': 'longhorn-manager'},
... etc
```
And that makes sense, I think because at this point the daemonsets look like:
```
kl get daemonsets
NAME                       DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
engine-image-ei-b907910b   4         4         4       4            4           <none>          5d1h
longhorn-csi-plugin        4         4         4       4            4           <none>          5d1h
longhorn-manager           3         3         3       3            3           <none>          5d1h
```
So the longhorn-manager has behaved itself, and we have indeed not made a misleading extra nodes.longhorn.io item for the master node.  So are we really unhappy with engine-image and the csi-plugin having expanded there?  When the toleration is removed, the daemonsets will shrink again.

**Comment by james-munson** [comment] 2023-12-21 00:10
We can
- Find a way to keep the other daemonsets from expanding outside of the nodes.longhorn.io list, or
- Doctor the test checking criteria, or
- Continue to leave the test case commented out (and extend the comment) but close this issue because the stated problem of a bogus down master node is no longer true.

**Comment by innobead** [comment] 2023-12-24 14:48
This is not an issue anymore. Closing this issue.

**Closed by innobead** 2023-12-24 14:48 UTC
Labels: kind/bug, area/manager
