### ISSUE TITLE
[BUG] longhorn-driver-deployer pod in init state

### ISSUE THREAD

**Issue by asiisc** [longhorn/longhorn#5898] opened 2023-05-09 21:07 UTC
## Describe the bug (🐛 if you encounter this issue

After longhorn helm installation, longhorn-driver-deployer is in init state on openshift 4.12.

## To Reproduce

3. Perform '....'

## Expected behavior

Installation should create csi pods as shown on this page -  https://longhorn.io/docs/1.4.1/deploy/install/install-with-helm/

## Log or Support bundle

<img width="904" alt="image" src="https://github.com/longhorn/longhorn/assets/114128/b9eba06a-bed4-4bfa-a210-73f27bf16910">

**oc logs longhorn-driver-deployer-796c7c6996-n44x9 -n longhorn-system**
Defaulted container "longhorn-driver-deployer" out of: longhorn-driver-deployer, wait-longhorn-manager (init)
Error from server (BadRequest): container "longhorn-driver-deployer" in pod "longhorn-driver-deployer-796c7c6996-n44x9" is waiting to start: PodInitializing

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.4.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: Openshift, 4.12
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Node config
   - OS type and version: CoreOS
   - CPU per node: 16
   - Memory per node: 64
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by ChanYiLin** [comment] 2023-05-12 04:40
There is a init container `wait-longhorn-manager` in longhorn-driver-deployer pod
1. can you provide the log in this init container by adding `-c wait-longhorn-manager` to get the log
2. can you check if you can access longhorn-manager service from other pod
thanks

**Comment by asiisc** [comment] 2023-05-16 17:46
oc logs longhorn-driver-deployer-796c7c6996-h7t4k -n longhorn-system -c wait-longhorn-manager
Error from server (BadRequest): container "wait-longhorn-manager" in pod "longhorn-driver-deployer-796c7c6996-h7t4k" is waiting to start: PodInitializing

**Comment by asiisc** [comment] 2023-05-16 20:01
mountPropogation is not set for failing pod longhorn-driver-deployer 

oc get pod longhorn-driver-deployer-796c7c6996-h7t4k -n longhorn-system -o yaml | grep mountPropagation
[[root@api.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com](mailto:root@api.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com) ~]

**Comment by asiisc** [comment] 2023-05-17 00:58
Hi @ChanYiLin what will be service url ?

**Comment by ChanYiLin** [comment] 2023-05-17 04:12
```
      initContainers:
        - name: wait-longhorn-manager
          image: longhornio/longhorn-manager:master-head
          command: ['sh', '-c', 'while [ $(curl -m 1 -s -o /dev/null -w "%{http_code}" http://longhorn-backend:9500/v1) != "200" ]; do echo waiting; sleep 2; done']
```
https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml#L4220

Can you also check if there is any error in longhorn-manager's log ?

**Comment by asiisc** [comment] 2023-05-17 20:06
Hi @ChanYiLin 
I tried from the UI pod -

`nginx@longhorn-ui-84db4b588b-rxhvq:/web> curl http://longhorn-backend:9500/v1
{"actions":{},"id":"v1","links":{"PVCCreateInputs":"http://longhorn-backend:9500/v1/pvccreateinputs","PVCreateInputs":"http://longhorn-backend:9500/v1/pvcreateinputs","UpdateAccessModeInputs":"http://longhorn-backend:9500/v1/updateaccessmodeinputs","UpdateDataLocalityInputs":"http://longhorn-backend:9500/v1/updatedatalocalityinputs","UpdateReplicaAutoBalanceInputs":"http://longhorn-backend:9500/v1/updatereplicaautobalanceinputs","UpdateReplicaCountInputs":"http://longhorn-backend:9500/v1/updatereplicacountinputs","UpdateSnapshotDataIntegrityInputs":"http://longhorn-backend:9500/v1/updatesnapshotdataintegrityinputs","UpdateUnmapMarkSnapChainRemovedInputs":"http://longhorn-backend:9500/v1/updateunmapmarksnapchainremovedinputs","activateInputs":"http://longhorn-backend:9500/v1/activateinputs","apiVersions":"http://longhorn-backend:9500/v1/apiversions","attachInputs":"http://longhorn-backend:9500/v1/attachinputs","backingImageCleanupInputs":"http://longhorn-backend:9500/v1/backingimagecleanupinputs","backingImageDiskFileStatuses":"http://longhorn-backend:9500/v1/backingimagediskfilestatuses","backingImages":"http://longhorn-backend:9500/v1/backingimages","backupInputs":"http://longhorn-backend:9500/v1/backupinputs","backupListOutputs":"http://longhorn-backend:9500/v1/backuplistoutputs","backupStatuses":"http://longhorn-backend:9500/v1/backupstatuses","backupTargets":"http://longhorn-backend:9500/v1/backuptargets","backupVolumes":"http://longhorn-backend:9500/v1/backupvolumes","backups":"http://longhorn-backend:9500/v1/backups","cloneStatuses":"http://longhorn-backend:9500/v1/clonestatuses","controllers":"http://longhorn-backend:9500/v1/controllers","detachInputs":"http://longhorn-backend:9500/v1/detachinputs","diskConditions":"http://longhorn-backend:9500/v1/diskconditions","diskInfos":"http://longhorn-backend:9500/v1/diskinfos","diskUpdateInputs":"http://longhorn-backend:9500/v1/diskupdateinputs","diskUpdates":"http://longhorn-backend:9500/v1/diskupdates","engineImages":"http://longhorn-backend:9500/v1/engineimages","engineUpgradeInputs":"http://longhorn-backend:9500/v1/engineupgradeinputs","errors":"http://longhorn-backend:9500/v1/errors","events":"http://longhorn-backend:9500/v1/events","expandInputs":"http://longhorn-backend:9500/v1/expandinputs","instanceManagers":"http://longhorn-backend:9500/v1/instancemanagers","instanceProcesses":"http://longhorn-backend:9500/v1/instanceprocesses","kubernetesStatuses":"http://longhorn-backend:9500/v1/kubernetesstatuses","nodeConditions":"http://longhorn-backend:9500/v1/nodeconditions","nodes":"http://longhorn-backend:9500/v1/nodes","orphans":"http://longhorn-backend:9500/v1/orphans","purgeStatuses":"http://longhorn-backend:9500/v1/purgestatuses","rebuildStatuses":"http://longhorn-backend:9500/v1/rebuildstatuses","recurringJobs":"http://longhorn-backend:9500/v1/recurringjobs","replicaRemoveInputs":"http://longhorn-backend:9500/v1/replicaremoveinputs","replicas":"http://longhorn-backend:9500/v1/replicas","restoreStatuses":"http://longhorn-backend:9500/v1/restorestatuses","salvageInputs":"http://longhorn-backend:9500/v1/salvageinputs","schemas":"http://longhorn-backend:9500/v1/schemas","self":"http://longhorn-backend:9500/v1/apiversions/v1","settingDefinitions":"http://longhorn-backend:9500/v1/settingdefinitions","settings":"http://longhorn-backend:9500/v1/settings","snapshotInputs":"http://longhorn-backend:9500/v1/snapshotinputs","snapshotListOutputs":"http://longhorn-backend:9500/v1/snapshotlistoutputs","snapshots":"http://longhorn-backend:9500/v1/snapshots","supportBundleInitateInputs":"http://longhorn-backend:9500/v1/supportbundleinitateinputs","supportBundles":"http://longhorn-backend:9500/v1/supportbundles","systemBackups":"http://longhorn-backend:9500/v1/systembackups","systemRestores":"http://longhorn-backend:9500/v1/systemrestores","tags":"http://longhorn-backend:9500/v1/tags","volumeConditions":"http://longhorn-backend:9500/v1/volumeconditions","volumeRecurringJobInputs":"http://longhorn-backend:9500/v1/volumerecurringjobinputs","volumeRecurringJobs":"http://longhorn-backend:9500/v1/volumerecurringjobs","volumes":"http://longhorn-backend:9500/v1/volumes","workloadStatuses":"http://longhorn-backend:9500/v1/workloadstatuses"},"type":"apiVersion"}`

**Comment by asiisc** [comment] 2023-05-17 20:49
One of the Manager pod is showing errors -

`time="2023-05-17T20:46:58Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:46:58Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:46:58Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:46:58Z" level=warning msg="Dropping Longhorn engine image out of the queue" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:28Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:28Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:28Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:28Z" level=warning msg="Dropping Longhorn engine image out of the queue" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:58Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:58Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:58Z" level=warning msg="Error syncing Longhorn engine image" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com
time="2023-05-17T20:47:58Z" level=warning msg="Dropping Longhorn engine image out of the queue" controller=longhorn-engine-image engineImage=longhorn-system/ei-7fa7c208 error="failed to sync engine image for longhorn-system/ei-7fa7c208: daemonsets.apps \"engine-image-ei-7fa7c208\" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>" node=worker2.sre-othr-3m5w-fips-nfs-03.cp.fyre.ibm.com`

**Comment by ChanYiLin** [comment] 2023-05-18 06:33
It seems that there are some rbac issue, have to add finalizer rbac permission in `longhorn.io`

you can refer to this thread for workaround: 
- https://github.com/longhorn/longhorn/issues/1831#issuecomment-702690613

and also this PR for more information of installing longhorn on openshift
- https://github.com/longhorn/longhorn/pull/5004

**Comment by ChanYiLin** [comment] 2023-05-22 01:44
Can you provide the error log in `longhorn-ui` and `longhorn-manager` ?
Or maybe the support bundle: https://longhorn.io/kb/troubleshooting-create-support-bundle-with-curl
longhorn-ui crashing sometimes means it cannot connect to longhorn-manager

**Comment by asiisc** [comment] 2023-05-30 18:01
Longhorn-ui log -
`nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2023/05/30 17:54:56 [warn] 10#10: duplicate MIME type "text/html" in /var/config/nginx/nginx.conf:7
2023/05/30 17:54:56 [emerg] 10#10: mkdir() "/var/lib/nginx/tmp/" failed (13: Permission denied)`

longhorn-manager log -
[long-manager-log.txt](https://github.com/longhorn/longhorn/files/11603141/long-manager-log.txt)

**Comment by ChanYiLin** [comment] 2023-05-31 02:27
From the longhorn-manager log, I can still see
```
E0529 17:27:09.080604       1 instance_manager_controller.go:252] failed to sync instance manager for longhorn-system/instance-manager-r-99bde50ae68d6481191633cafe0f8205: pods "instance-manager-r-99bde50ae68d6481191633cafe0f8205" is forbidden: cannot set blockOwnerDeletion if an ownerReference refers to a resource you can't set finalizers on: , <nil>
```

**Comment by asiisc** [comment] 2023-05-31 04:57
Looks like instancemanagers/finalizers was not added.  All pods looks good -

`NAME                                                              READY   STATUS    RESTARTS      AGE
csi-attacher-66f9979b99-75thk                                     1/1     Running   0             12d
csi-attacher-66f9979b99-892qj                                     1/1     Running   0             12d
csi-attacher-66f9979b99-j2fbl                                     1/1     Running   0             12d
csi-provisioner-64dcbd65b4-46p5m                                  1/1     Running   0             12d
csi-provisioner-64dcbd65b4-bwgvl                                  1/1     Running   0             12d
csi-provisioner-64dcbd65b4-lb457                                  1/1     Running   0             12d
csi-resizer-ccdb95b5c-685wq                                       1/1     Running   0             12d
csi-resizer-ccdb95b5c-pv5c4                                       1/1     Running   0             12d
csi-resizer-ccdb95b5c-wwq5w                                       1/1     Running   0             12d
csi-snapshotter-546b79649b-d78tr                                  1/1     Running   0             12d
csi-snapshotter-546b79649b-h8cng                                  1/1     Running   0             12d
csi-snapshotter-546b79649b-nc42t                                  1/1     Running   0             12d
engine-image-ei-7fa7c208-5mrbk                                    1/1     Running   0             12d
engine-image-ei-7fa7c208-6x677                                    1/1     Running   0             12d
engine-image-ei-7fa7c208-7kfsp                                    1/1     Running   0             12d
engine-image-ei-7fa7c208-gbf6z                                    1/1     Running   0             12d
engine-image-ei-7fa7c208-gxqzw                                    1/1     Running   0             12d
instance-manager-e-36fdc25ad205210e0247767f9e1732df               1/1     Running   0             103s
instance-manager-e-512323da2c0ce376090c50bd3860c73a               1/1     Running   0             101s
instance-manager-e-99bde50ae68d6481191633cafe0f8205               1/1     Running   0             103s
instance-manager-e-c4d0cd72ecb3611d903e6676acd087a4               1/1     Running   0             100s
instance-manager-e-ef610ce397d06ac6a1146b1b8d02138b               1/1     Running   0             102s
instance-manager-r-36fdc25ad205210e0247767f9e1732df               1/1     Running   0             103s
instance-manager-r-512323da2c0ce376090c50bd3860c73a               1/1     Running   0             101s
instance-manager-r-99bde50ae68d6481191633cafe0f8205               1/1     Running   0             103s
instance-manager-r-c4d0cd72ecb3611d903e6676acd087a4               1/1     Running   0             100s
instance-manager-r-ef610ce397d06ac6a1146b1b8d02138b               1/1     Running   0             102s
longhorn-admission-webhook-5bc4b984c4-27lzc                       1/1     Running   0             12d
longhorn-admission-webhook-5bc4b984c4-l5tf6                       1/1     Running   0             12d
longhorn-conversion-webhook-75d97f9fc8-dkbrx                      1/1     Running   0             12d
longhorn-conversion-webhook-75d97f9fc8-h5277                      1/1     Running   0             12d
longhorn-csi-plugin-n5vmh                                         3/3     Running   0             12d
longhorn-csi-plugin-rxct4                                         3/3     Running   0             12d
longhorn-csi-plugin-rzj96                                         3/3     Running   0             12d
longhorn-csi-plugin-scqlz                                         3/3     Running   0             12d
longhorn-csi-plugin-z2n9p                                         3/3     Running   0             12d
longhorn-driver-deployer-c654d94c9-jrbkv                          1/1     Running   5 (12d ago)   12d
longhorn-manager-2vvwt                                            1/1     Running   0             12d
longhorn-manager-b747z                                            1/1     Running   0             12d
longhorn-manager-bp85n                                            1/1     Running   0             12d
longhorn-manager-n8tcl                                            1/1     Running   0             12d
longhorn-manager-q2rbm                                            1/1     Running   1 (12d ago)   12d
longhorn-recovery-backend-bc84b6dbf-29qds                         1/1     Running   0             12d
longhorn-recovery-backend-bc84b6dbf-jpqd5                         1/1     Running   0             12d
longhorn-support-bundle-manager-support-bundle-2023-05-22tshfxg   1/1     Running   0             8d
longhorn-ui-677c9cb6d7-dq2t8                                      1/1     Running   0             55s
longhorn-ui-677c9cb6d7-wn94s                                      1/1     Running   0             74s`

**Comment by ChanYiLin** [comment] 2023-05-31 06:12
Congrats!

**Comment by asiisc** [comment] 2023-06-16 19:37
Hi @ChanYiLin Trying to run example given in longhorn documentation - https://longhorn.io/docs/1.4.1/volumes-and-nodes/create-volumes/

but it failed to attach the volume 
kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.4.1/examples/pod_with_pvc.yaml

Volume will be in progress condition and then will show as detatched.

<img width="521" alt="image" src="https://github.com/longhorn/longhorn/assets/114128/def5558d-fd14-44fe-a634-3b4cc3ed54e1">

**Comment by ChanYiLin** [comment] 2023-06-19 01:44
When creating volume and then binding to the pod, it should be in `attaching` state
can you provide more information like
- `kubectl get pod -oyaml` to see the pod's event
- support bundle to see what happened inside longhorn

Thanks!

**Comment by asiisc** [comment] 2023-06-20 06:58
Hi @ChanYiLin I  have no idea but today it started working. After cleanup I tried again and it worked :) 
<img width="855" alt="image" src="https://github.com/longhorn/longhorn/assets/114128/e10a1202-9f7d-4f41-803c-017672842293">

<img width="489" alt="image" src="https://github.com/longhorn/longhorn/assets/114128/201c6439-5fa8-4989-a1ad-5635ef2f32ce">

**Comment by c3y1huang** [comment] 2023-09-26 03:14
Seems the issue is resolved. Closing this, feel free to re-open.

**Closed by c3y1huang** 2023-09-26 03:14 UTC
Labels: kind/bug
