### ISSUE TITLE
[BUG] test_migration_with_rebuilding_replica and test_migration_with_unscheduled_replica are failing

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#4684] opened 2022-10-06 22:03 UTC
## Describe the bug

The test `test_migration_with_rebuilding_replica and test_migration_with_unscheduled_replica ` are failing on v1.3.x-head in our nightly test run.

## To Reproduce

1. Run the integration tests on a 3 node Longhorn set up.

## Expected behavior

The tests should not fail.

## Log or Support bundle

```
volume = common.wait_for_volume_migration_ready(client, volume_name)

test_migration.py:281: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7fd09271a610>
volume_name = 'longhorn-testvol-kzp4di'

    def wait_for_volume_migration_ready(client, volume_name):
        ready = False
        for i in range(RETRY_COUNTS):
            v = client.by_id_volume(volume_name)
            engines = v.controllers
            ready = len(engines) == 2
            for e in engines:
                ready = ready and e.endpoint != ""
            if ready:
                break
            time.sleep(RETRY_INTERVAL)
>       assert ready
E       AssertionError

common.py:2847: AssertionError
```

## Environment

 - Longhorn version: v1.3.x-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
 - Node config
   - OS type and version: Ubuntu 22.04/ SLES 15.3

**Comment by innobead** [comment] 2022-10-06 22:09
These are new test cases added to the master and backported to 1.3.

**Comment by khushboo-rancher** [comment] 2022-10-06 22:12
These are passing on master-head, only failing on v1.3.x

**Comment by innobead** [comment] 2022-10-06 22:15
@khushboo-rancher Let's also verify these cases manually to see if any issues there as well.

**Comment by chriscchien** [comment] 2022-10-07 02:07
Hi @khushboo-rancher 
I use new cluster to test on my local, those 2 test cases were all passed in `v1.3.x-head` and `v1.3.2-rc1 `
Also pipeline result for [test_migration_with_rebuilding_replica](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2153/testReport/tests/test_migration/) and [test_migration_with_unscheduled_replica](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2154/testReport/tests/test_migration/) were good. I will keep following test result. thank you

**Comment by khushboo-rancher** [comment] 2022-10-07 04:29
Thanks @chriscchien for checking. I also checked this manually, they worked fine. Probably something related to the tests. We'll need to investigate.

**Comment by innobead** [comment] 2022-10-07 05:22
Thanks @khushboo-rancher and @chriscchien :+1:

**Comment by chriscchien** [comment] 2022-10-20 05:54
Close this ticket because after PR merged, those 2 test cases are working properly on v1.3.x [pipeline](https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/180/testReport/tests/test_migration/) now

**Closed by chriscchien** 2022-10-20 05:54 UTC
Labels: kind/bug, kind/test, reproduce/rare, severity/4, flaky-test
