### ISSUE TITLE
[FEATURE] Talos support

### ISSUE THREAD

**Issue by runningman84** [longhorn/longhorn#3161] opened 2021-10-16 20:48 UTC
**Is your feature request related to a problem? Please describe.**
Talos does not support longhorn due to missing iscsi support:
https://github.com/talos-systems/talos/issues/3057

**Describe the solution you'd like**
Other supported storage providers in talos use the nvmf protocol to overcome this issue.

**Describe alternatives you've considered**
I would really like to continue using longhorn, the other solutions have their our limitations like needing a seperated disk.

**Additional context**
With an uncertain future of k3os many users might take a look at talos.

**Comment by HaveFun83** [comment] 2022-07-30 20:48
iscsi-tools are now support via system extensions on the talos side. 
Maybe the settings how longhorn communicate with the iscsi-daemon can be made configurable?

https://www.talos.dev/v1.1/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/

**Comment by skandragon** [comment] 2022-09-27 19:41
I fear it's more than just the settings.  I fear it's also that bash and other tools are used.  There's a somewhat long list of tools:

**Comment by innobead** [comment] 2022-11-23 17:15
ref: https://www.talos.dev/v1.2/kubernetes-guides/configuration/replicated-local-storage-with-openebs-jiva/

**Comment by c3y1huang** [comment] 2023-03-27 09:41
Note:
- The `iscsiadm` still needs to be executed using `nsenter` approach from its ancestor namespace.
- We should replace all dependent binary invocations. To achieve this, we need to implement namespace entering using `setns` or alternatives.
- We also need to replace the binary dependencies in the automation tests.

I've written a PoC to test the feasibility of the changes. And will revisit this issue later to provide a proper LEP.

**Comment by japtain-cack** [comment] 2023-08-06 20:24
I'm really looking forward to this. I've been trying out linstor, via the piraeus operator, and it just doesn't work as well as longhorn. Sure, it might theoretically be faster, and that does seem to be the case, but it's much more complex and I've not had good luck with loosing a disk during testing. My pod shouldn't be stopped when a single disk is lost. Longhorn never failed me in the past, but I have not been able to use it since I moved to Talos/Sidero.

**Comment by c3y1huang** [comment] 2023-08-14 04:05
Regression test result: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4813/

**Comment by c3y1huang** [comment] 2023-08-15 12:00
Tests results (full):
- Regression: WIP
- Talos Linux: WIP

**Comment by camaeel** [comment] 2023-08-17 09:09
Is there any estimated time when Longhorn 1.6 can be released?

**Comment by c3y1huang** [comment] 2023-08-17 10:21
> Is there any estimated time when Longhorn 1.6 can be released?

Afaik, v1.6.0 is planned to be out around the end of this year.

**Comment by c3y1huang** [comment] 2023-08-29 02:26
Test results (full/arm64):
- SUSE (SLES15-SP5)
  - S3: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4860/
    ```
    ==== 1 failed, 331 passed, 17 skipped, 189 warnings in 50111.50s (13:55:11) ====
    ```
  - NFS: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/4861/
    ```
    ==== 3 failed, 328 passed, 18 skipped, 188 warnings in 50321.42s (13:58:41) ====
    ```

**Comment by ccben87** [comment] 2023-08-31 10:57
Hi @c3y1huang,

Is this currently in a working state? I'd very much like to test it / use it prior to release of 1.6.

**Comment by c3y1huang** [comment] 2023-09-01 00:22
> Hi @c3y1huang,
> 
> Is this currently in a working state? I'd very much like to test it / use it prior to release of 1.6.

The pull requests are currently under review, which means there may still be ongoing changes. I suggest to wait until the PRs are merged before testing it.

**Comment by zimmertr** [comment] 2023-09-16 18:03
I am so excited for this!

**Comment by larssb** [comment] 2023-09-16 18:15
Me as well @zimmertr

**Comment by runningman84** [comment] 2023-09-16 18:45
Cool so see my feature request implemented…

**Comment by ccben87** [comment] 2023-10-25 10:15
I really hope this will be merged soon. Otherwise I might have to look at alternatives :(

**Comment by CRASH-Tech** [comment] 2023-10-25 10:17
> I really hope this will be merged soon. Otherwise I might have to look at alternatives :(

Same situation

**Comment by zimmertr** [comment] 2023-10-25 14:29
If you're using Proxmox someone has recently started developing a CSI driver that works with ZFS, LVM, Local, etc. Storage types. [I'm](https://github.com/zimmertr/Kubernetes-Manifests/tree/main/storage#proxmox-csi-driver)  using [it](https://github.com/sergelogvinov/proxmox-csi-plugin)  with ZFS quite happily now.

**Comment by ccben87** [comment] 2023-10-25 14:38
> If you're using Proxmox someone has recently started developing a CSI driver that works with ZFS, LVM, Local, etc. Storage types. [I'm](https://github.com/zimmertr/Kubernetes-Manifests/tree/main/storage#proxmox-csi-driver) using [it](https://github.com/sergelogvinov/proxmox-csi-plugin) with ZFS quite happily now.

I am using Nutanix AHV which is KVM under the surface so it might work? Maybe not? What is this project?

**Comment by zimmertr** [comment] 2023-10-25 15:23
Review the hyperlinks you quoted 😉

But no, the plugin directly interacts with the Proxmox API.

**Comment by bdsoha** [comment] 2023-10-29 09:51
@c3y1huang Any updates on the merge process?

**Comment by innobead** [comment] 2023-10-29 14:08
> @c3y1huang Any updates on the merge process?

The PRs will be released in the near future and planned for the upcoming 1.6.0 release.

**Comment by c3y1huang** [comment] 2023-11-15 07:11
Test results (core):
- Talos (v1.5.5)
  - S3
    ```
    === 63 passed, 1 skipped, 290 deselected, 27 warnings in 7091.03s (1:58:11) ====
    ```
  - NFS
    ```
    WIP
    ```
- SUSE (SLES15-SP5)
  - S3: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5232/
    ```
    === 63 passed, 1 skipped, 290 deselected, 28 warnings in 6878.20s (1:54:38) ====
    ``` 
  - NFS: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5233/
    ```
    ========= 64 passed, 290 deselected, 28 warnings in 7014.31s (1:56:54) =========
    ```

**Comment by c3y1huang** [comment] 2023-11-16 03:13
Test result (full):
- Talos (v1.5.5)
  - S3
  ```
  = 336 passed, 18 skipped, 223 warnings in 50413.40s (14:00:13) =
  ```
  - NFS
  ```
  WIP
  ```
- SUSE (SLES15-SP5)
  - S3: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5234/
  ```
  = 337 passed, 17 skipped, 217 warnings in 50205.38s (13:56:45) =
  ```
  - NFS: https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5235/
  ```
  = 336 passed, 18 skipped, 216 warnings in 50201.84s (13:56:41) =
  ```

**Comment by Ornias1993** [comment] 2023-12-10 21:56
To ensure it actually makes 1.6.0, it might be best to give the PR's a bit more pro-active attention @innobead

**Comment by boixu** [comment] 2023-12-18 18:09
Hi, I am also very much interested in this. Keep up the great work!

**Comment by c3y1huang** [comment] 2023-12-27 04:58
Currently I am experimenting Longhorn with Talos v1.6.0. Somehow, patching the machine kubelet extra-mount isn't working as in v1.5.5. cc @frezbo
```
machine:
  kubelet:
    extraMounts:
      - destination: /var/lib/longhorn
        type: bind
        source: /var/lib/longhorn
        options:
          - bind
          - rshared
          - rw
```

**Comment by frezbo** [comment] 2023-12-27 05:06
> Currently I am experimenting Longhorn with Talos v1.6.0. Somehow, patching the machine kubelet extra-mount isn't working as in Talos v1.5.5. cc @frezbo
> 
> ```
> machine:
>   kubelet:
>     extraMounts:
>       - destination: /var/lib/longhorn
>         type: bind
>         source: /var/lib/longhorn
>         options:
>           - bind
>           - rshared
>           - rw
> ```

what's the error?

**Comment by c3y1huang** [comment] 2023-12-27 05:08
> what's the error?

There is no error, the mount didn't seem to apply somehow.

**Comment by frezbo** [comment] 2023-12-27 05:51
> > what's the error?
> 
> There is no error, the mount didn't seem to apply somehow.

Probably check the `kubelet` and `controller-runtime` logs

`talosctl logs kubelet` `talosctl logs controller-runtime`

**Comment by c3y1huang** [comment] 2023-12-27 06:10
> Probably check the `kubelet` and `controller-runtime` logs
> 
> `talosctl logs kubelet` `talosctl logs controller-runtime`

Thank you @frezbo . It appears this was a false alarm caused by a typo in my launch template.

**Comment by c3y1huang** [comment] 2023-12-28 03:17
Test result (full):
- Talos (v1.6.0)
  - S3
  ```
  = 2 failed, 341 passed, 22 skipped, 254 warnings, 1 error in 50724.13s (14:05:24) =
  ```
  - NFS
  ```
  WIP
  ```

**Comment by innobead** [comment] 2023-12-29 12:08
> The 2 failed test cases seem unrelated to this feature.
> 
> * test_engine_image_incompatible: `Failed to pull image "longhornio/longhorn-test:version-test.7-7.5-4.1-1"`

@chriscchien Please help with this. @longhorn/qa

**Comment by yangchiu** [comment] 2024-01-03 05:58
Verified passed on master-head (longhorn-manager b2132e7) following https://github.com/longhorn/website/pull/827 to setup Talos environment, but extra config for `Pod Security` is also needed:
```
cluster:
  apiServer:
    admissionControl:
      - name: PodSecurity
        configuration:
          apiVersion: pod-security.admission.config.k8s.io/v1alpha1
          defaults:
            enforce: privileged
          kind: PodSecurityConfiguration
```
Longhorn can be installed successfully in the configured Talos environment. And longhorn-tests `coretest` has been run based on https://github.com/longhorn/longhorn-tests/pull/1501, there is no outstanding issue found.

**Closed by yangchiu** 2024-01-03 05:58 UTC
Labels: kind/enhancement, area/install-uninstall-upgrade, highlight, priority/0, require/auto-e2e-test, require/doc, require/lep

**Comment by camaeel** [comment] 2024-01-03 06:38
> Verified passed on master-head (longhorn-manager b2132e7) following [longhorn/website#827](https://github.com/longhorn/website/pull/827) to setup Talos environment, but extra config for `Pod Security` is also needed:
> 
> ```
> cluster:
>   apiServer:
>     admissionControl:
>       - name: PodSecurity
>         configuration:
>           apiVersion: pod-security.admission.config.k8s.io/v1alpha1
>           defaults:
>             enforce: privileged
>           kind: PodSecurityConfiguration
> ```
> 
> Longhorn can be installed successfully in the configured Talos environment. And longhorn-tests `coretest` has been run based on [longhorn/longhorn-tests#1501](https://github.com/longhorn/longhorn-tests/pull/1501), there is no outstanding issue found.

Instead lowering PodSecurity for whole cluster it would be better either to label longhorn-system namespace or put it into PodSecurityConfiguration as exemption (https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller).

**Comment by yangchiu** [comment] 2024-01-03 06:45
> Instead lowering PodSecurity for whole cluster it would be better either to label longhorn-system namespace or put it into PodSecurityConfiguration as exemption (https://kubernetes.io/docs/tasks/configure-pod-container/enforce-standards-admission-controller/#configure-the-admission-controller).

@c3y1huang Would you like to add this to the documentation?

**Comment by c3y1huang** [comment] 2024-01-03 07:58
> @c3y1huang Would you like to add this to the documentation?

Longhorn's documentation has links directing to the Talos documentation, which offers various approaches for handling this (including the namespace approach).
