### ISSUE TITLE
[FEATURE] Support automatic rebalance the replicas

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#587] opened 2019-06-03 22:27 UTC
Add a global setting to enable `Automatic replica rebalance`.

In the case of there is a limited or no redundancy for the volume (e.g. due to node offline temporarily), if this option is enabled, we can automatically check if a new replica can be scheduled on the new node to restore the redundancy. Notice this can have some system level impact since it will result in more network traffic in the system.

Should be implemented with `Maximum Concurrent Replica Rebuilding Count` option. 

from: https://github.com/rancher/longhorn/issues/570

**Comment by ironsalsa** [comment] 2019-08-14 15:57
Adding my vote here for this feature - it would be great to not need manual intervention after node failures.

**Comment by michaelpearce-gain** [comment] 2021-04-09 23:03
Is there any update on this? When would it possibly be available. Whilst hard affinity is ok, in AZ failure scenarios it can hurt, you obviously want replicas in separate AZ's so that should a DC fail you know data is in another AZ, but once that occurs, you kind of want your operations to continue in the remaining, including able to create new PVs, as well as have resilience from node loss whilst the other AZ is out,, and simply once the other AZ is back, you'd want to re-balance automatically data so your back to having safety from a future AZ failure, with no manual steps.

**Comment by joshimoo** [comment] 2021-04-10 11:09
@michaelpearce-gain we do have the option for sofft anti affinity on the zone.
https://longhorn.io/docs/1.1.0/volumes-and-nodes/scheduling/#the-node-and-zone-selection-stage

This would allow a rebuild to happen in Zone `A` when Zone `B` fails.
But we currently don't have auto rebalancing after Zone `B` comes back.

As a workaround a user can manually evict a single replica from Zone `A` once Zone `B` is available again, this will make Longhorn respect the soft anti affinity of the zones and prioritize the rebuild into the now available Zone `B`.

**Comment by michaelpearce-gain** [comment] 2021-04-24 01:07
@joshimoo  we would need it that theres 100% guarantee that after zone B comes back that replicas will be there again, so should zone A go down weeks later, youre not left with both replicas in zone A. Soft affinity as i understand it is a best effort, not a guarentee, like hard affinity gives as i understand

**Comment by c3y1huang** [comment] 2021-05-28 09:42
Discussed with @innobead and will remove `require/manual-test-plan` tag. We can refer to e2e since already covered the cases.

**Comment by innobead** [comment] 2021-05-28 09:47
> Discussed with @innobead and will remove `require/manual-test-plan` tag. We can refer to e2e since already covered the cases.

cc @khushboo-rancher @meldafrawi @kaxing

**Comment by yasker** [comment] 2021-06-29 19:12
@c3y1huang Good job on completing the e2e test case too! Just to make sure if we decide to use the automation test case for QA test, make sure we have added the direct link to the test cases in the checklist, so QA can take a look directly and make sure it has addressed all the possible scenarios. cc @innobead 

E.g. for this issue, I've found:
https://longhorn.github.io/longhorn-tests/integration/test_scheduling.html#tests.test_scheduling.test_replica_auto_balance_disabled_volume_spec_enabled
https://longhorn.github.io/longhorn-tests/integration/test_scheduling.html#tests.test_scheduling.test_replica_auto_balance_node_best_effort
https://longhorn.github.io/longhorn-tests/integration/test_scheduling.html#tests.test_scheduling.test_replica_auto_balance_node_least_effort
https://longhorn.github.io/longhorn-tests/integration/test_zone.html#tests.test_zone.test_replica_auto_balance_node_duplicates_in_multiple_zones
https://longhorn.github.io/longhorn-tests/integration/test_zone.html#tests.test_zone.test_replica_auto_balance_zone_best_effort
https://longhorn.github.io/longhorn-tests/integration/test_zone.html#tests.test_zone.test_replica_auto_balance_zone_best_effort_with_data_locality
https://longhorn.github.io/longhorn-tests/integration/test_zone.html#tests.test_zone.test_replica_auto_balance_zone_best_effort_with_uneven_node_in_zones
https://longhorn.github.io/longhorn-tests/integration/test_zone.html#tests.test_zone.test_replica_auto_balance_zone_least_effort

Not sure if there is more to it.

**Comment by c3y1huang** [comment] 2021-06-30 01:49
I should have made it more clear where to seek if looking for manual testings.
Please reference to the automation test skeletons with prefix `test_replica_auto_balance` in [test_scheduling.py](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_scheduling.py#L427-L824) and [test_zone.py](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_zone.py#L281-L871).

@khushboo-rancher , @meldafrawi , @kaxing

**Comment by kaxing** [comment] 2021-07-14 12:13
Validating in progress,
tested on 1+3 cluster setup with master-head images(0714), initial result looks good,
Test name | Duration | Status
-- | -- | --
test_data_locality_basic | 9 min 17 sec | Passed
test_hard_anti_affinity_detach | 42 sec | Passed
test_hard_anti_affinity_live_rebuild | 50 sec | Passed
test_hard_anti_affinity_offline_rebuild | 45 sec | Passed
test_hard_anti_affinity_scheduling | 30 sec | Passed
test_replica_auto_balance_disabled_volume_spec_enabled | 49 sec | Passed
test_replica_auto_balance_node_best_effort | 2 min 41 sec | Passed
test_replica_auto_balance_node_least_effort | 1 min 31 sec | Passed
test_replica_rebuild_per_volume_limit | 2 min 55 sec | Passed
test_soft_anti_affinity_detach | 45 sec | Passed
test_soft_anti_affinity_scheduling | 33 sec | Passed


Test name | Duration | Status
-- | -- | --
test_replica_auto_balance_node_duplicates_in_multiple_zones | 25 sec | Passed
test_replica_auto_balance_zone_best_effort | 1 min 57 sec | Passed
test_replica_auto_balance_zone_best_effort_with_data_locality | 5 min 21 sec | Passed
test_replica_auto_balance_zone_best_effort_with_uneven_node_in_zones | 0 ms | Skipped
test_replica_auto_balance_zone_least_effort | 41 sec | Passed
test_replica_zone_anti_affinity | 12 sec | Passed
test_zone_tags | 2 min 20 sec | Passed

**Comment by khushboo-rancher** [comment] 2021-07-14 18:21
Thanks @kaxing for running the tests, could you also test this feature using the Longhorn GUI?

1. Scenarios related to enable/disable the global setting `Replica Auto Balance` vs per volume. Modification of the setting.
2. Replica auto balancing when there is a node added with smaller disk (replica unable to schedule on the new node)
3. Volumes created with node tag/disk tag.
4. Upgrade a set up from v1.1.2 to master-head and functionality should remain intact.
5. Functionality with node eviction.
6. Scenario where all the replicas are balanced and a node start having disk full, will the replicas move to another node where we have disks with enough space?

**Comment by kaxing** [comment] 2021-07-16 12:43
Validation - **Passed**

Tested on Longhorn master-images (0716, ui: 67cebbd), with 1 control node, and begin with 3 worker nodes.

> 1. Scenarios related to enable/disable the global setting `Replica Auto Balance` vs per volume. Modification of the setting.

Global and per volume settings are work as expected, and detail walk through testing in the below.

> 2. Replica auto balancing when there is a node added with smaller disk (replica unable to schedule on the new node)

As overserving, smaller disk, or node with less storage available will not be used for auto-balance.

> 3. Volumes created with node tag/disk tag.

Node tag and disk tag will got higher priority and not be affected by replica-auto-balance

> 4. Upgrade a set up from v1.1.2 to master-head and functionality should remain intact.

Setting remain intact and new features will be in default.

> 5. Functionality with node eviction.

When turn off node and request eviction, replica will starting to delete or rebalance based on setting.

> 6. Scenario where all the replicas are balanced and a node start having disk full, will the replicas move to another node 
where we have disks with enough space?


And following is the detail walk through testing with different setting combinations.

Initial General Setting:
Replica Auto Balance: disabled
Replica Node Level Soft Anti-Affinity: false
Replica Zone Level Soft Anti-Affinity: false

Individual Volume setting:
Volume-1 Replica Auto Balance set to: ignored
Volume-2 Replica Auto Balance set to: disabled
Volume-3 Replica Auto Balance set to: least-effort
Volume-4 Replica Auto Balance set to: best-effort
All volume replica count set to: 3

// Nodes manipulation done by changing scheduling status within Longhorn settings

Initial node count: 1 node in zone-1
Manually deleting all replica til only 1 left.
Replica count:
| Volume | Replicas| Health status |
| - | :-: | - |
| Volume-1 | 1 | Scheduling Failure |
| Volume-2 | 1 | Scheduling Failure |
| Volume-3 | 1 | Scheduling Failure |
| Volume-4 | 1 | Scheduling Failure |

Node count update to: 2 node in zone-1
Manually deleting all replica til only 1 left and wait for rebuilding.
Replica count: remain the same as above.

Node count update to: 1 node in zone-1, 1 node in zone-2
Manually deleting all replica til only 1 left.
Replica count:
| Volume | Replicas| Health status |
| - | :-: | - |
| Volume-1 | 2 | Scheduling Failure |
| Volume-2 | 2 | Scheduling Failure |
| Volume-3 | 2 | Scheduling Failure |
| Volume-4 | 2 | Scheduling Failure |

---

Update General Setting:
Replica Auto Balance: disabled
Replica Node Level Soft Anti-Affinity: true
Replica Zone Level Soft Anti-Affinity: false

Node count update to: 3 node in zone-1
Manually deleting all replica til only 1 left and wait for rebuilding.
Replica count:
| Volume | Replicas| Health status |
| - | :-: | - |
| Volume-1 | 3 | Healthy |
| Volume-2 | 3 | Healthy |
| Volume-3 | 3 | Healthy |
| Volume-4 | 3 | Healthy |

---

Update General Setting:
Replica Auto Balance: disabled
Replica Node Level Soft Anti-Affinity: false
Replica Zone Level Soft Anti-Affinity: true

Node count update to: 1 node in zone-1, 1 node in zone-2
Manually deleting all replica til only 1 left and wait for rebuilding.
Replica count:
| Volume | Replicas| Health status |
| - | :-: | - |
| Volume-1 | 2 | Scheduling Failure |
| Volume-2 | 2 | Scheduling Failure |
| Volume-3 | 2 | Scheduling Failure |
| Volume-4 | 2 | Scheduling Failure |


---

Update General Setting:
Replica Auto Balance: disabled
Replica Node Level Soft Anti-Affinity: true
Replica Zone Level Soft Anti-Affinity: true

Node count update to: 1 node in zone-1, 1 node in zone-2
Manually deleting all replica til only 1 left.
Replica count:
| Volume | Replicas| Health status |
| - | :-: | - |
| Volume-1 | 3 | Healthy with replicas on the same node warning |
| Volume-2 | 3 | Healthy with replicas on the same node warning |
| Volume-3 | 3 | Healthy with replicas on the same node warning |
| Volume-4 | 3 | Healthy with replicas on the same node warning |

---

Update General Setting:
Replica Auto Balance: disabled
Replica Node Level Soft Anti-Affinity: true
Replica Zone Level Soft Anti-Affinity: true

Node count update to: 1 node in zone-1, 1 node in zone-2, 1 node in zone-3
Replica count:
| Volume | Zone-1 | Zone-2 | Zone-3 | Health status |
| - | :-: | :-: | :-: | - |
| Volume-1 | 2 | 1 | 0 | Healthy with replicas on the same node warning |
| Volume-2 | 2 | 1 | 0 | Healthy with replicas on the same node warning |
| Volume-3 | 1 | 1 | 1 | Healthy |
| Volume-4 | 1 | 1 | 1 | Healthy |

---

Update General Setting:
Replica Auto Balance: least-effort
Replica Node Level Soft Anti-Affinity: true
Replica Zone Level Soft Anti-Affinity: true

Node count update to: 1 node in zone-1, 1 node in zone-2, 1 node in zone-3
Replica count:
| Volume| Zone-1 | Zone-2 | Zone-3 | Health status |
| - | :-: | :-: | :-: | - |
| Volume-1 | 1 | 1 | 1 | Healthy |
| Volume-2 | 2 | 1 | 1 | Healthy with replicas on the same node warning |
| Volume-3 | 1 | 1 | 1 | Healthy |
| Volume-4 | 1 | 1 | 1 | Healthy |

Update all volume replica count from 3 to: 4
Replica count:
|Volume| Zone-1 | Zone-2 | Zone-3 | Health status |
| - | :-: | :-: | :-: | - |
| Volume-1 | 1 | 1 | 2 | Healthy with replicas on the same node warning |
| Volume-2 | 2 | 1 | 1 | Healthy with replicas on the same node warning |
| Volume-3 | 2 | 1 | 1 | Healthy with replicas on the same node warning |
| Volume-4 | 1 | 2 | 1 | Healthy with replicas on the same node warning |

Node count update to: 1 node in zone-1, 2 node in zone-2, 2 node in zone-3
Replica count:
| Volume | Zone-1 | Node 1 in Zone-2 | Node 2 in Zone-2 | Node 1 in Zone-3 | Node 2 in Zone-3 | Health status |
| - | :-: | :-: | :-: | :-: | :-: | - |
| Volume-1 | 1 | 1 | 0 | 1 | 1 | Healthy |
| Volume-2 | 2 | 1 | 0 | 1 | 0 | Healthy with replicas on the same node warning |
| Volume-3 | 1 | 1 | 0 | 1 | 1 | Healthy |
| Volume-4 | 1 | 1 | 0 | 1 | 1 | Healthy |

Update all volume replica count from 4 to: 5
Replica count:
| Volume | Zone-1| Node 1 in Zone-2 | Node 2 in Zone-2 | Node 1 in Zone-3 | Node 2 in Zone-3 | Health status |
| - | :-: | :-: | :-: | :-: | :-: | - |
| Volume-1 | 1 | 1 | 1 | 1 | 1 | Healthy |
| Volume-2 | 2 | 1 | 1 | 1 | 0 | Healthy with replicas on the same node warning |
| Volume-3 | 1 | 1 | 1 | 1 | 1 | Healthy |
| Volume-4 | 1 | 1 | 1 | 1 | 1 | Healthy |

Node count update to: 1 node in zone-1, 2 node in zone-2, 3 node in zone-3
Replica count:
| Volume | Zone-1 | Node 1 in Zone-2 | Node 2 in Zone-2 | Node 1 in Zone-3 | Node 2 in Zone-3 | Node 3 in Zone-3 | Health status |
| - | :-: | :-: | :-: | :-: | :-: | :-: |- |
| Volume-1 | 1 | 1 | 1 | 1 | 1 | 0 | Healthy |
| Volume-2 | 2 | 1 | 0 | 1 | 1 | 0 | Healthy with replicas on the same node warning |
| Volume-3 | 1 | 1 | 1 | 1 | 1 | 0 | Healthy |
| Volume-4 | 1 | 1 | 1 | 1 | 1 | 0 | Healthy |

Node count update to: 2 node in zone-1, 2 node in zone-2, 3 node in zone-3
Replica count:
| Volume | Node 1 in Zone-1 | Node 2 in Zone-1| Node 1 in Zone-2 | Node 2 in Zone-2 | Node 1 in Zone-3 | Node 2 in Zone-3 | Node 3 in Zone-3 | Health status |
| - | :-: | :-: | :-: | :-: | :-: | :-: | :-: | - |
| Volume-1 | 1 | 0 | 1 | 1 | 1 | 1 | 0 | Healthy |
| Volume-2 | 2 | 0 | 1 | 0 | 1 | 1 | 0 | Healthy with replicas on the same node warning |
| Volume-3 | 1 | 0 | 1 | 1 | 1 | 1 | 0 | Healthy |
| Volume-4 | 1 | 1 | 1 | 1 | 1 | 0 | 0 | Healthy* |

*And you can see when there are two equal zones(with the same node numbers), replica-auto-balance will rebuild replica in between zones.

**Comment by khushboo-rancher** [comment] 2021-07-16 16:09
> And you can see when there are two equal zones(with the same node numbers), replica-auto-balance will rebuild replica in between zones.
Does it mean the replica keeps rebuilding multiple times on both the zones?

**Comment by c3y1huang** [comment] 2021-07-19 02:30
@kaxing I've not been able to reproduce this with https://github.com/c3y1huang/longhorn-tests/blob/bug-replica-autobalance-besteffort-rebuild-bounce/manager/integration/tests/test_zone.py#L875-L955. Can you provide the reproducing step?

**Comment by kaxing** [comment] 2021-07-19 03:01
> > And you can see when there are two equal zones(with the same node numbers), replica-auto-balance will rebuild replica in between zones.
> 
> Does it mean the replica keeps rebuilding multiple times on both the zones?

@khushboo-rancher No, it's not rebuilding on both zones at the same time, one of the replica will rebuilding in between zones.

@c3y1huang I was doing this test with walkthrough style and only notice this by the end. Let me try to re-check this with my test environment and come back to you.

**Comment by c3y1huang** [comment] 2021-07-19 10:44
> @c3y1huang I was doing this test with walkthrough style and only notice this by the end. Let me try to re-check this with my test environment and come back to you.

I am able to reproduce with 7 node cluster, 3 zones, and 5 replicas. Still not clear about the root cause.

**Comment by kaxing** [comment] 2021-07-20 04:29
Validating again with the image contains the fix from longhorn/longhorn-manager#963

No more aggressive looping-rebuilding situation for the replica sets.

Tested with following configurations:

1. With 5 replicas per volume,

|Zone Label|Node count|
| - |  :-: |
|zone-1|2|
|zone-2|2|
|zone-3|3|

2. With 7 replicas per volume,

|Zone Label|Node count|
| - |  :-: |
|zone-1|2|
|zone-2|2|
|zone-3|2|
|no zone|3|

**Comment by c3y1huang** [comment] 2021-07-20 04:34
@kaxing , thanks for testing. We probably want to keep this open to tracking the review/merge for the fix in  https://github.com/longhorn/longhorn-manager/pull/963 .

**Comment by joshimoo** [comment] 2021-07-21 00:38
I approved the fix PR https://github.com/longhorn/longhorn-manager/pull/963#pullrequestreview-711164868
under the premise that the fix has been tested already by QA/E2E.

@innobead if we have time I would like to see this refactoring surround the replica scheduling done as part of v1.2
https://github.com/longhorn/longhorn/issues/2667#issuecomment-883795644

**Comment by kaxing** [comment] 2021-07-26 09:26
Validation - **Passed**

Testing again with the master-head images(0726, UI: 0aac5e3), no more replica rebuild bounce sighted.

**Closed by kaxing** 2021-07-26 09:26 UTC
Labels: area/manager, highlight, kind/enhancement, priority/1, require/LEP, require/automation-e2e, require/doc
