### ISSUE TITLE
[BUG] The number of snapshot and backup created in recurring job is unstable

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2378] opened 2021-03-19 03:31 UTC
**Describe the bug**
Should fix the unstable number of snapshots and backups created in the recurring jobs. This is causing test_recurring_job regression results unstable.

Finding:
1. When wite and backup happen at the same time, occasionally seeing the backup created twice.
![Screenshot-2021-03-19-16:27:16](https://user-images.githubusercontent.com/22583541/111751982-17df0900-88d0-11eb-8e3e-65ca5232cf46.png)

2. If write, snapshot and backup happening at different times, occasionally seeing the number of snapshots created are less than expected.
![Screenshot-2021-03-19-16:27:04](https://user-images.githubusercontent.com/22583541/111752028-24fbf800-88d0-11eb-948d-655d8aa30203.png)

**To Reproduce**
1. Run test_recurring_job

**Expected behavior**
Should have a stable pass.

**Log**
`n/a`

**Environment:**
`none`

**Additional context**
Not reproducible every time.

**Comment by innobead** [comment] 2021-06-21 03:43
Closing, because the behavior was changed by #2231 and the test cases fixed by #2158 . 

Please reopen if this is still found from the future regression. 

cc @khushboo-rancher @kaxing @meldafrawi @cclhsu

**Closed by innobead** 2021-06-21 03:43 UTC
Labels: area/manager, feature/backup-restore, kind/bug, reproduce/rare
