### ISSUE TITLE
[BUG] Nodes unavailable due to "failed to get disk config: error: unknown disk type "

### ISSUE THREAD

**Issue by johanneskastl** [longhorn/longhorn#7212] opened 2023-11-27 09:42 UTC
## Describe the bug

- Three node cluster with k3s running on openSUSE MicroOS with btrfs
- single node k3s also running on openSUSE MicroOS with btrfs
- single node cluster is working perfectly fine
- 3-node-cluster has three nodes unavailable due to the following error in the node details in the Longhorn UI 

```
Last Transition Time: a month ago
Message: Disk default-disk-5dd97ea1ec1601b8(/var/lib/longhorn/) on node nuc-links is not ready: failed to get disk config: error: unknown disk type
Reason: NoDiskInfo
Status: False
```

## To Reproduce

I cannot reproduce this, as another single-node k3s machine also on openSUSE MicroOS with btrfs, does not have this error.

## Expected behavior

The node should be available.

## Support bundle for troubleshooting

[supportbundle_1c1364ad-747b-4fd7-9265-2af5a80ce4ec_2023-11-27T09-38-54Z.zip](https://github.com/longhorn/longhorn/files/13472400/supportbundle_1c1364ad-747b-4fd7-9265-2af5a80ce4ec_2023-11-27T09-38-54Z.zip)

## Environment

 - Longhorn version: 1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: (no separate workers, all control plane nodes are schedulable) 
 - Node config
   - OS type and version: openSUSE MicroOS
   - Kernel version:  `Linux <redacted> 6.5.9-1-default #1 SMP PREEMPT_DYNAMIC Wed Oct 25 10:31:37 UTC 2023 (29edc7c) x86_64 x86_64 x86_64 GNU/Linux`
   - CPU per node: 2
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: 1GBit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 13
 - Impacted Longhorn resources:
   - Volume names: all but one (13 total, 8 degraded, 4 fault, 1 healthy)

## Additional context

The question is why this happens on the three-node-cluster but not on the singlenode-cluster, as they are using the same k3s version, OS version, kernel version, filesystem and have the same set of tools (as far as I can say) installed.

**Comment by derekbit** [comment] 2023-11-27 10:28
A fresh installed cluster or an upgraded one?

**Comment by johanneskastl** [comment] 2023-11-27 10:46
This cluster was working fine with longhorn for 1,5 years and was recently upgraded to Longhorn 1.5.1 (and was working fine for some time).

**Comment by johanneskastl** [comment] 2023-11-27 10:49
> The disk types of the disks are not patched correctly during upgrade. It might be due to the issue #6294.
> 
> Can you try to add diskType to the `node.spec.disks` manually?
> 
> ```
>     disks:
>       default-disk-5dd97ea1ec1601b8:
>         allowScheduling: true
>         evictionRequested: false
>         path: /var/lib/longhorn/
>         storageReserved: 5.8970938982e+10
>         tags: []
>         diskType: flesystem <---ADD THIS LINE
> ```

I'll try. Sorry for the question, but where does this need to go?

**Comment by derekbit** [comment] 2023-11-27 10:56
Try the steps

1. `kubectl -n longhorn-system edit node.longhorn.io <node-name>`
2. Go to `spec.disks`
3. Add `diskType: flesystem` as I mentioned above.

**Comment by johanneskastl** [comment] 2023-11-27 11:51
Thanks! Is `flesystem` a typo and should be `filesystem` with an `i`?

**Comment by derekbit** [comment] 2023-11-27 11:53
Ah, typo, should be `filesystem`.

**Comment by johanneskastl** [comment] 2023-11-27 19:06
Hooray, that seems to have done the trick. One of the nodes is still unavailable, but that is due to not enough space being available (need to dig into why that is, it has no volumes?).

So my problem is solved for now, but how to prevent this happening for others again? Should we leave this bug open?

**Comment by derekbit** [comment] 2023-11-27 23:38
@johanneskastl 
The issue is resolved in https://github.com/longhorn/longhorn/issues/6294. 
BTW, there are some outstanding issues in v1.5.1, I recommend you upgrading it to v1.5.2.

**Closed** 2023-11-30 22:53 UTC
Labels: kind/bug, duplicated, require/qa-review-coverage, require/backport
