### ISSUE TITLE
[BUG] Longhorn 1.2.0 unable to handle instance-manager failure

### ISSUE THREAD

**Issue by bkupidura** [longhorn/longhorn#3070] opened 2021-09-26 09:01 UTC
**Describe the bug**
Couple of days ago i start observing some POD failures. Only PODs which were using longhorn block storage was affected.
After some debugging it looks that k8s/longhorn is not able to handle instance-manager failure properly even when StorageClass have more than 1 replica.

When instance-manager will die, PODs attached to it, will not be able to recover.

POD will stay in `CrashLoopBackOff` because of I/O errors from volume.

**To Reproduce**
1. Deploy POD which will need PV to properly start (e.g config file on PV)
2. Kill instance-manager serving PV for POD (kubectl delete -n longhorn-system --force --grace-period=0 instance-manager-...
3. Wait till new instance-manager will be spawned
4. Check if POD was recovered

**Expected behavior**
After instance-manager failure, POD should be restarted and able to use volume.

**Environment:**
 - Longhorn version: 1.2.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.21.4+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: Intel i3/i5
   - Memory per node: 8GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 1Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: ~10

Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly: true
Pod Deletion Policy When Node is Down: delete-both-statefulset-and-deployment-pod

**Additional context**
It looks like some race condition. On HV i can see those I/O errors, so looks like OS still have volume mounted from failed instance-manager.

```
root@k3s-delta:~# crictl inspect 22644f59333cd |grep volumes
        "hostPath": "/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount",
        "hostPath": "/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~projected/kube-api-access-qvrbx",
          "host_path": "/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount"
          "host_path": "/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~projected/kube-api-access-qvrbx",
          "source": "/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount",
          "source": "/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~projected/kube-api-access-qvrbx",

root@k3s-delta:~# ls /var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount
ls: reading directory '/var/lib/kubelet/pods/37667d1d-522d-4dd2-8dc7-38506cda3347/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount': Input/output error

root@k3s-delta:~# df -h |grep eb67d196
/dev/longhorn/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b  2.0G  351M  1.6G  19% /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/globalmount
```

If you delete failed POD, nothing will change. To fix problem i need to scale deployment to 0 and after that scale it back to previous number. I would guess, that scaling is performing some cleanup on HV.

Volume status after deployment scale=0 -> scale=1
```
root@k3s-delta:~# crictl inspect c6ccfe69eab33 |grep volume
        "hostPath": "/var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount",
        "hostPath": "/var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~projected/kube-api-access-6jzb7",
          "host_path": "/var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount"
          "host_path": "/var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~projected/kube-api-access-6jzb7",
          "source": "/var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount",
          "source": "/var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~projected/kube-api-access-6jzb7",

root@k3s-delta:~# ls /var/lib/kubelet/pods/95e77a5e-e0a2-4c38-bfb2-23e2dea9c1dc/volumes/kubernetes.io~csi/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/mount
[some files from volume, without IO errors]

root@k3s-delta:~# df -h |grep eb67d196
/dev/longhorn/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b  2.0G  351M  1.6G  19% /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-eb67d196-a204-442f-a4a4-2bb0c127572b/globalmount
```

**Comment by joshimoo** [comment] 2021-09-28 10:50
@bkupidura does the same happen when you remove the `--force --grace-period=0`? Also how many pods does your deployment have when you say that it doesn't recover when you delete a single pod? Did longhorn correctly delete all the pods from that deployment? after the instance-manager comes back?

**Comment by bkupidura** [comment] 2021-09-28 11:05
@jenting 
1) Not really as i already migrated my storage from longhorn to ceph
2) I had this issue with any POD which required PV to successfully start. This should work for you
```
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: debugpod
  labels:
    app.kubernetes.io/name: debugpod
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: debugpod
  template:
    metadata:
      labels:
        app.kubernetes.io/name: debugpod
    spec:
      containers:
      - name: debugpod
        image: ubuntu:latest
        command:
          - "/bin/sh"
          - "-ec"
          - |
            touch /data/test
            tail -f /data/test
        volumeMounts:
          - mountPath: /data
            name: data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: test-data
```
3) HV - hypervisor, baremetal node on which k8s is running
4) No

@joshimoo To be honest i didnt try to gracefuly delete instance-manager POD. I was testing what is happening with my workloads when instance-manager is unexpectedly killed.
All Deployments with this issue had 1 POD.

In free time i will try to bring up second k8s cluster with longhorn and provide more data. Cant promise when exactly.
Right now i would suggest to just spawn one POD as described in this ticket and just kill instance-manager - you should be able to reproduce.

If interested, my whole k8s setup is available as ansible playbook https://github.com/bkupidura/home-k8s.
I would expect that if you deploy vanilla ubuntu, provision k3s and render longhorn manifest you will endup with exact copy of my environment.

**Comment by joshimoo** [comment] 2021-09-28 11:11
@bkupidura thank you for the additional information.

**Comment by jenting** [comment] 2021-09-30 02:04
I could reproduce it even without `--force --grace-period=0`.

The deployment Pods be restarted by Longhorn-manager, but after Pod restart, the Pod is still in I/O error state.

**Comment by innobead** [comment] 2021-09-30 04:09
cc @khushboo-rancher

**Comment by shuo-wu** [comment] 2021-09-30 09:36
This issue is probably a side effect of the CSI Node Staging Capability introducing:
When Longhorn detects the volume crash caused by instance manager pod deletion, it will restart the workload pod as long as one setting is enabled. The deployment pod is probably restarted on the same node hence Kubernetes would issue any unstage or detach call for the corresponding volume during the old pod cleanup. Instead, it will directly do umount for the old path as well as issuing mount calls only for the new pod. But here the staging path, which is the mount point, is already corrupted. Then the mount calls (between the staging path and the volume mount point) for the new pod are meaningless/ corrupted as well.

I tried to add validation for the staging path in Longhorn CSI API `NodePublishVolume` based on [the spec doc](https://github.com/container-storage-interface/spec/blob/master/spec.md#nodepublishvolume-errors) but kubelet won't re-send NodeStageVolume calls after receiving the errors. We need to find a way to ask kubelet to re-do the staging.


cc @joshimoo

**Comment by khushboo-rancher** [comment] 2021-10-04 20:03
Validated with v1.2.x-head and master-head `10/04/2021`

Validation - **Pass**

Validated below cases.
1. Validated IM deletion with and without grace for RWO volume with workload having configured file on PV as mentioned https://github.com/longhorn/longhorn/issues/3070#issuecomment-929085544
2. Validated IM deletion with and without grace for RWX volume with workload having configured file on PV.
3. Validated above scenarios with pod managed by deployment and StatefulSet.
4. Validated kubelet restart with RWO/RWX volumes.
5. Validated rke2-agent.service restart with RWO volume.

**Comment by meldafrawi** [comment] 2021-10-04 22:56
Validation: Passed

- validated encrypted volume cases for IM deletion with and without grace for RWO
- validated encrypted volume cases for IM deletion with and without grace for RWX

**Comment by joshimoo** [comment] 2021-10-05 08:02
@meldafrawi encrypted RWO volumes will not work correctly in this failure scenario when the deployment is on a single node kubernetes cluster and has multiple replicas. The mounts will succeed but the actual IO is not possible since the crypt device maps to a no longer present scsi device.

**Comment by cchien816** [comment] 2022-03-18 08:02
While working on https://github.com/longhorn/longhorn/issues/3104, I found in master-head 20220318, after delete` instance manager-e`, deployment pod won't restart and data will loose

But double verified with v1.2.4 is pass , thank you

Steps:
```
    Related issue :
    https://github.com/longhorn/longhorn/issues/3070

    Steps:
    1. Create a volume and PV/PVC.
    2. Create a deployment with 1 pod having below in command section on node-1
       and attach to the volume.
       command:
          - "/bin/sh"
          - "-ec"
          - |
            touch /data/test
            tail -f /data/test
    3. Wait for the pod to become healthy.
    4. Write small(100MB) data.
    5. Kill the instance-manager-e on node-1.
    6. Wait for the instance-manager-e pod to become healthy.
    7. Wait for pod to get terminated and recreated.
    8. Read and write in the pod to verify the pod is accessible.
```
cc @innobead

**Comment by innobead** [comment] 2022-03-18 08:16
> While working on #3104, I found in master-head 20220318, after delete` instance manager-e`, deployment pod won't restart and data will loose
> 
> But double verified on v1.2.4 is pass , thank you
> 

@PhanLe1010 this is probably related to https://github.com/longhorn/longhorn/issues/3629.

**Comment by PhanLe1010** [comment] 2022-03-18 18:28
Thanks @innobead 
Yes, it looks like so

**Comment by cchien816** [comment] 2022-05-03 03:04
Close this issue
Verified on master head 20220503
1. This case was passed in [e2e](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/110/testReport/tests/test_ha/test_recovery_from_im_deletion/) master branch pipeline
2. This case was passed in [e2e](https://ci.longhorn.io/job/public/job/v1.2.x/job/v1.2.x-longhorn-tests-sles-amd64/85/testReport/tests/test_ha/test_recovery_from_im_deletion//) v1.2.x branch pipeline
3. Manually verifed pass on local environment

**Closed by cchien816** 2022-05-03 03:04 UTC
Labels: kind/bug, priority/1, require/automation-e2e, kind/regression, severity/3
