### ISSUE TITLE
[BUG] Instance manager crashes with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by reitermarkus** [longhorn/longhorn#3466] opened 2021-12-24 16:44 UTC
## Describe the bug

The instance manager on one of my nodes is not starting anymore and is failing with a panic.

## To Reproduce

Not sure.

## Expected behavior

No panic.

## Log or Support bundle

```
time="2021-12-24T16:29:02Z" level=info msg="Running ssync server for file volume-snap-monthly-c-b8ee4f7b.img.meta at port 10009"
time="2021-12-24T16:29:02Z" level=info msg="Creating Ssync service"
time="2021-12-24T16:29:02Z" level=info msg="open: receiving fileSize: 162, setting up directIO: false"
time="2021-12-24T16:29:02Z" level=error msg="open failed, err: open: Failed to open/create local source file, path: volume-snap-monthly-c-b8ee4f7b.img.meta, err: open volume-snap-monthly-c-b8ee4f7b.img.meta: no such file or directory"
2021/12/24 16:29:02 http: panic serving 10.42.2.251:42464: runtime error: invalid memory address or nil pointer dereference
goroutine 88514 [running]:
net/http.(*conn).serve.func1(0xc00032e000)
	/usr/local/go/src/net/http/server.go:1772 +0x139
panic(0xd73a40, 0x168d100)
	/usr/local/go/src/runtime/panic.go:975 +0x3e3
github.com/longhorn/sparse-tools/sparse/rest.(*SyncServer).close(0xc00041c050, 0x108cf60, 0xc00015c000, 0xc000364200)
	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/sparse-tools/sparse/rest/handlers.go:119 +0x63
net/http.HandlerFunc.ServeHTTP(0xc0001f6830, 0x108cf60, 0xc00015c000, 0xc000364200)
	/usr/local/go/src/net/http/server.go:2012 +0x44
github.com/gorilla/mux.(*Router).ServeHTTP(0xc0004f6000, 0x108cf60, 0xc00015c000, 0xc00020a300)
	/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/gorilla/mux/mux.go:212 +0xe2
net/http.serverHandler.ServeHTTP(0xc000428000, 0x108cf60, 0xc00015c000, 0xc00020a300)
	/usr/local/go/src/net/http/server.go:2807 +0xa3
net/http.(*conn).serve(0xc00032e000, 0x10915a0, 0xc0003ae240)
	/usr/local/go/src/net/http/server.go:1895 +0x86c
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2933 +0x35c
time="2021-12-24T16:29:02Z" level=error msg="Sync agent gRPC server failed to rebuild replica/sync files: replica tcp://10.42.2.251:10015 failed to send file volume-snap-monthly-c-b8ee4f7b.img.meta to 10.42.0.253:10009: failed to send file volume-snap-monthly-c-b8ee4f7b.img.meta to 10.42.0.253:10009: rpc error: code = Unknown desc = failed to SyncContent for source: volume-snap-monthly-c-b8ee4f7b.img.meta: openServer failed, err: resp.StatusCode(500) != http.StatusOK"
ERROR: 2021/12/24 16:29:02 grpc: server failed to encode response:  rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
```

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3OS v0.22.2-k3s2r0
   - Number of management node in the cluster: 4
   - Number of worker node in the cluster: 4
 - Node config
   - OS type and version: k3OS v0.22.2-k3s2r0
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal/KVM
 - Number of Longhorn volumes in the cluster:

## Additional context

N/A

**Comment by timmy59100** [comment] 2021-12-27 10:11
Same with 1.23

`panic: runtime error: invalid memory address or nil pointer dereference [recovered]

	panic: runtime error: invalid memory address or nil pointer dereference

[signal SIGSEGV: segmentation violation code=0x1 addr=0x1f0 pc=0x161662d]

goroutine 958 [running]:

k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x105

panic(0x1931a20, 0x2c92950)

	/usr/local/go/src/runtime/panic.go:967 +0x166

github.com/longhorn/longhorn-manager/controller.(*BackupController).getEngineClient(0xc000763d00, 0xc000fa4cf0, 0x28, 0x0, 0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:416 +0x7d

github.com/longhorn/longhorn-manager/controller.(*BackupController).checkMonitor(0xc000763d00, 0xc0044c6780, 0xc0044f8000, 0xc000a56340, 0x0, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:469 +0x182

github.com/longhorn/longhorn-manager/controller.(*BackupController).reconcile(0xc000763d00, 0xc000f48b80, 0x17, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:305 +0x1263

github.com/longhorn/longhorn-manager/controller.(*BackupController).syncHandler(0xc000763d00, 0xc000f48b70, 0x27, 0x0, 0x0)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:170 +0x182

github.com/longhorn/longhorn-manager/controller.(*BackupController).processNextWorkItem(0xc000763d00, 0x203000)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:136 +0xcc

github.com/longhorn/longhorn-manager/controller.(*BackupController).worker(0xc000763d00)

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:126 +0x2b

k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0xc000634850)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:155 +0x5f

k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc000634850, 0x1e6faa0, 0xc00449a1e0, 0x726f747365527401, 0xc0000ba1e0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:156 +0xa3

k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000634850, 0x3b9aca00, 0x0, 0x1c67301, 0xc0000ba1e0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x98

k8s.io/apimachinery/pkg/util/wait.Until(0xc000634850, 0x3b9aca00, 0xc0000ba1e0)

	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:90 +0x4d

created by github.com/longhorn/longhorn-manager/controller.(*BackupController).Run

	/go/src/github.com/longhorn/longhorn-manager/controller/backup_controller.go:120 +0x1c9`

**Comment by innobead** [comment] 2021-12-27 10:46
cc @shuo-wu

**Comment by kaxing** [comment] 2021-12-27 12:19
Hello, @reitermarkus which Longhorn version were you upgrading from? Maybe I can do a quick check.

Also, can you generate support bundle with the current situation? If possible would be nice to upload it here.

**Comment by timmy59100** [comment] 2021-12-27 12:52
@kaxing I upgraded from 1.22 to 1.23. I sent the support bundle per email.

**Comment by reitermarkus** [comment] 2021-12-28 04:41
Upgraded from 1.22 to 1.23 as well.

**Comment by shuo-wu** [comment] 2021-12-28 13:28
It seems that the NPE errors are triggered by 2 different bugs:
1. Instance manager pod crash: During the rebuilding, the receive server [failed to create a file](https://github.com/longhorn/sparse-tools/blob/a0fb4226a960dfa0a77a843b052a44824a9d729a/sparse/rest/handlers.go#L99-L101) then [the sender directly closed the server](https://github.com/longhorn/sparse-tools/blob/a0fb4226a960dfa0a77a843b052a44824a9d729a/sparse/client.go#L99-L106). 
2. Longhorn manager pod crash: The volume is asked to created a backup before the engine is created

Fixing these 2 cases may be simple. But I am still checking how to reproduce them.

**Comment by shuo-wu** [comment] 2021-12-28 13:32
And for the instance manager crash case, can you check if the data path of the node the instance manager pod resides on works fine?

**Comment by khushboo-rancher** [comment] 2022-01-11 19:35
Validation - **Pass**

Validated on master-head `01/11/2022`

Test steps followed from https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.3.0/test-instance-manager-npe/

I was able to reproduce the problem on v1.2.3 and the issue is fixed on master-head.
Log from v1.2.3 : 
[instance-manager-r-54127d36_replica-manager.log](https://github.com/longhorn/longhorn/files/7849439/instance-manager-r-54127d36_replica-manager.log)

Log from master-head : 
[instance-manager-r-02f18c3e_replica-manager.log](https://github.com/longhorn/longhorn/files/7849447/instance-manager-r-02f18c3e_replica-manager.log)
```
time="2022-01-11T19:21:05Z" level=error msg="open failed, err: open: Failed to open/create local source file, path: volume-snap-faeb025b-6030-42d9-bb92-c7b4dd450c5f.img.meta, err: open volume-snap-faeb025b-6030-42d9-bb92-c7b4dd450c5f.img.meta: is a directory"
--
Tue, Jan 11 2022 11:21:05 am | time="2022-01-11T19:21:05Z" level=info msg="Closing ssync server"
Tue, Jan 11 2022 11:21:05 am | time="2022-01-11T19:21:05Z" level=info msg="Done running ssync server for file volume-snap-faeb025b-6030-42d9-bb92-c7b4dd450c5f.img.meta at port 10011"
Tue, Jan 11 2022 11:21:05 am | [volume-test-1-r-4262ea51] time="2022-01-11T19:21:05Z" level=error msg="Sync agent gRPC server failed to rebuild replica/sync files: replica tcp://10.42.0.26:10000 failed to send file volume-snap-faeb025b-6030-42d9-bb92-c7b4dd450c5f.img.meta to 10.42.2.25:10011: failed to send file volume-snap-faeb025b-6030-42d9-bb92-c7b4dd450c5f.img.meta to 10.42.2.25:10011: rpc error: code = Unknown desc = failed to SyncContent for source: volume-snap-faeb025b-6030-42d9-bb92-c7b4dd450c5f.img.meta: openServer failed, err: resp.StatusCode(500) != http.StatusOK"
Tue, Jan 11 2022 11:21:05 am | [volume-test-1-r-4262ea51] ERROR: 2022/01/11 19:21:05 grpc: server failed to encode response: rpc error: code = Internal desc = grpc: error while marshaling: proto: Marshal called with nil
```

**Closed by khushboo-rancher** 2022-01-11 19:35 UTC
Labels: kind/bug, backport-needed/1.2.4
