### ISSUE TITLE
[TASK] Bump the version of SLES, RHEL, Ubuntu in the integration test pipeline

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#3045] opened 2021-09-21 20:56 UTC
**What's the task? Please describe.**
Use the latest version of the SLES, Ubuntu and RHEL in the integration test pipeline

https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Use the latest ami for the instances running the Longhorn tests.
- [ ] Run the test and verify the result

**Comment by meldafrawi** [comment] 2021-09-21 23:11
SLES jobs:
- https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/14/console
- https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/7/console


RHEL jobs:
- https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-tests-rhel-amd64/29/console
- https://ci.longhorn.io/job/public/job/master/job/rhel/job/amd64/job/longhorn-upgrade-tests-rhel-amd64/19/console

**Comment by meldafrawi** [comment] 2021-09-22 21:06
RHEL 8.4.0: Terraform step will take longer time than expected, will check the root cause.

**Comment by meldafrawi** [comment] 2021-09-27 16:49
We've reverted to use RHEL 8.3 for now.

**Comment by innobead** [comment] 2021-10-01 01:10
@meldafrawi Please close this if it's done.

**Closed** 2021-10-01 19:50 UTC
Labels: kind/task
