### ISSUE TITLE
[BUG] Unable to list backups when backuptarget resource is picked up by a cordoned node

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7619] opened 2024-01-11 01:24 UTC
## Describe the bug

Unable to list backups when backuptarget resource is picked up by a cordoned node

## To Reproduce

1. Prepare a 3-node cluster
2. Cordon node-2 and node-3
3. Install Longhorn v1.5.3 or master-head 
4. If backuptarget is picked up by a cordoned node, the error message is emitted when listing backups

```
failed to get engine client proxy: instance-manager-595f55887f0bef4e44b1846739426fd8 instance manager is in stopped, not running state
```
## Environment

 - Longhorn version: v1.5.3 and master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

<!-Please add any other context about the problem here.-->

**Comment by c3y1huang** [comment] 2024-01-11 03:35
So far I am unable to reproduce this. Checking with @derekbit about the reproducing steps.

Below are my steps attempting to reproduce:
1. Cordoned all worker nodes.
```bash
> k cordon ip-10-0-2-24; k cordon ip-10-0-2-68; k cordon ip-10-0-2-181
> k get nodes
NAME            STATUS                     ROLES                  AGE    VERSION
ip-10-0-2-24    Ready,SchedulingDisabled   <none>                 7d2h   v1.27.1+k3s1
ip-10-0-2-68    Ready,SchedulingDisabled   <none>                 7d2h   v1.27.1+k3s1
ip-10-0-2-181   Ready,SchedulingDisabled   <none>                 7d2h   v1.27.1+k3s1
ip-10-0-1-145   Ready                      control-plane,master   7d2h   v1.27.1+k3s1
```
2. Checked instance-managers.
```bash
> k -n longhorn-system get lhim
NAME                                                STATE     TYPE   NODE            AGE
instance-manager-d9ac85ac5afd4cda85235f84a47d8dfd   running   aio    ip-10-0-2-68    5m47s
instance-manager-824cd89daa26c0160438e0f69c4f5b3c   running   aio    ip-10-0-2-24    5m47s
instance-manager-188cf465a00e27f2d2497f6cdd5017ec   running   aio    ip-10-0-2-181   5m44s
```
3. Checked backup.
```bash
> k -n longhorn-system get backup
NAME                      SNAPSHOTNAME                           SNAPSHOTSIZE   SNAPSHOTCREATEDAT      STATE       LASTSYNCEDAT
backup-8357898bca8d4ded   ec4dced4-961d-4d8d-a3f2-a3384fc2bd26   117440512      2023-09-15T00:53:03Z   Completed   2024-01-11T03:12:51Z
```
4. Disabled backup target.
```bash
> k -n longhorn-system get backuptargets.longhorn.io 
NAME      URL   CREDENTIAL   LASTBACKUPAT   AVAILABLE   LASTSYNCEDAT
default                      5m0s           false       2024-01-11T03:22:23Z
```

5. Checked backup.
```bash
> k -n longhorn-system get backup
No resources found in longhorn-system namespace.
```

6. Enabled backup target.
```bash
> k -n longhorn-system get backuptargets.longhorn.io 
NAME      URL                            CREDENTIAL   LASTBACKUPAT   AVAILABLE   LASTSYNCEDAT
default   s3://c3y1-s3@ap-southeast-1/   aws-secret   5m0s           true        2024-01-11T03:27:59Z
```

7. Checked backup.
```bash
> k -n longhorn-system get backup
NAME                      SNAPSHOTNAME                           SNAPSHOTSIZE   SNAPSHOTCREATEDAT      STATE       LASTSYNCEDAT
backup-8357898bca8d4ded   ec4dced4-961d-4d8d-a3f2-a3384fc2bd26   117440512      2023-09-15T00:53:03Z   Completed   2024-01-11T03:28:00Z
```

**Comment by derekbit** [comment] 2024-01-11 03:43
Provided a cluster with the issue to @c3y1huang 

My steps are 
```
k cordon dereksu-aws-longhorn-pool1-caacdd4c-5fjh9 
k cordon dereksu-aws-longhorn-pool1-caacdd4c-67mbh
-------
(install LH v1.5.3)
helm install longhorn --namespace longhorn-system --create-namespace ./chart

k apply -f deploy/backupstores/nfs-backupstore.yaml

Update the backuptarget setting to nfs://longhorn-test-nfs-svc.default:/opt/backupstore
-------
List backups on UI
```

![image](https://github.com/longhorn/longhorn/assets/12527233/61d83bc5-effa-43d8-9ed0-c77e467bf49d)

**Comment by c3y1huang** [comment] 2024-01-11 04:27
Cause `The DaemonSet controller automatically adds a set of [tolerations](https://kubernetes.io/docs/concepts/scheduling-eviction/taint-and-toleration/) to DaemonSet Pods`

https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#taints-and-tolerations

**Comment by chriscchien** [comment] 2024-01-15 03:07
Verifide **pass** on longhorn master (longhorn-manager `a78c2a`) with test [steps](https://github.com/longhorn/longhorn/issues/7619#issuecomment-1886176257) 

Can reproduce on v1.5.x. In master-head, backup can be listed when longhorn installed on a cluser which already have some worker nodes cordoned.

**Closed by chriscchien** 2024-01-15 03:07 UTC
Labels: kind/bug, priority/0, require/manual-test-plan, area/volume-backup-restore, require/qa-review-coverage, require/backport, backport/1.4.5, backport/1.5.4
