### ISSUE TITLE
[BUG] longhorn installation randomly failed on sles 15-sp5 due to longhorn manager CrashLoopBackOff

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#6504] opened 2023-08-11 11:47 UTC
## Describe the bug (🐛 if you encounter this issue)

Although `open-iscsi` has been installed through cloud-init in the terraform script:
https://github.com/longhorn/longhorn-tests/blob/master/test_framework/terraform/aws/sles/user-data-scripts/provision_k3s_agent.sh.tpl#L5

Longhorn installation randomly failed on `sles 15-sp5` due to longhorn manager `CrashLoopBackOff`:
```
# kubectl logs longhorn-manager-2vmll -n longhorn-system
time="2023-08-11T09:06:36Z" level=fatal msg="Error starting manager: Failed environment check, please make sure you have iscsiadm/open-iscsi installed on the host: failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net iscsiadm --version], output , stderr nsenter: failed to execute iscsiadm: No such file or directory\n: exit status 127"
```

And it doesn't always happen.

Like
https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-arm64/210/console is just a replay of https://ci.longhorn.io/job/public/job/v1.1.x/job/v1.1.x-longhorn-upgrade-tests-sles-arm64/206/console.
But `210` failed and `206` succeeded.

And it never happen in `sles 15-sp4`.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by ejweber** [comment] 2023-08-15 16:44
The intermediate cause appears to be a temporary network problem. There is a `guestregister` service that is supposed to do the job of registering the SLES instance and setting up repos. On a "good" node, we see the following:

```
-> sudo journalctl -u guestregister
Aug 11 21:03:14 ip-10-0-2-123 systemd[1]: Starting Obtain Cloud update server info and register with the server...
Aug 11 21:04:34 ip-10-0-2-123 registercloudguest[1557]: Registration succeeded
Aug 11 21:04:34 ip-10-0-2-123 systemd[1]: guestregister.service: Deactivated successfully.
Aug 11 21:04:34 ip-10-0-2-123 systemd[1]: Finished Obtain Cloud update server info and register with the server.

-> cat /var/log/cloudregister
2023-08-11 21:03:14,568 INFO:Region server arguments: ?regionHint=us-east-1
2023-08-11 21:03:14,569 INFO:Using API: regionInfo
2023-08-11 21:03:14,574 INFO:Region server arguments: ?regionHint=us-east-1
2023-08-11 21:03:14,575 INFO:Getting update server information, attempt 1
2023-08-11 21:03:14,575 INFO:   Using region server: 2600:1f13:355:4700:ee7a:f5f8:6b38:c9c
2023-08-11 21:03:14,577 ERROR:  No response from: 2600:1f13:355:4700:ee7a:f5f8:6b38:c9c
2023-08-11 21:03:14,577 INFO:   Using region server: 2600:1f18:4665:e200:3aa2:d7c:2176:70c3
2023-08-11 21:03:14,579 ERROR:  No response from: 2600:1f18:4665:e200:3aa2:d7c:2176:70c3
2023-08-11 21:03:14,579 INFO:   Using region server: 2406:da12:878:8b00:9ea4:1263:39d3:bda1
2023-08-11 21:03:14,580 ERROR:  No response from: 2406:da12:878:8b00:9ea4:1263:39d3:bda1
2023-08-11 21:03:14,580 INFO:   Using region server: 2a05:d018:71c:e300:5ec0:8a24:7b5d:86ef
2023-08-11 21:03:14,581 ERROR:  No response from: 2a05:d018:71c:e300:5ec0:8a24:7b5d:86ef
2023-08-11 21:03:14,582 INFO:   Using region server: 2406:da1c:f2a:8400:9982:83c:559d:7f56
2023-08-11 21:03:14,583 ERROR:  No response from: 2406:da1c:f2a:8400:9982:83c:559d:7f56
2023-08-11 21:03:14,583 INFO:   Using region server: 2400:7fc0:8ad4:9e00:78bd:8464:c08c:f4f6
2023-08-11 21:03:14,584 ERROR:  No response from: 2400:7fc0:8ad4:9e00:78bd:8464:c08c:f4f6
2023-08-11 21:03:14,584 INFO:   Using region server: 54.247.166.75
2023-08-11 21:03:29,601 ERROR:  No response from: 54.247.166.75
2023-08-11 21:03:29,601 INFO:   Using region server: 54.253.118.149
2023-08-11 21:03:44,618 ERROR:  No response from: 54.253.118.149
2023-08-11 21:03:44,618 INFO:   Using region server: 54.223.148.145
2023-08-11 21:03:59,635 ERROR:  No response from: 54.223.148.145
2023-08-11 21:03:59,635 INFO:   Using region server: 34.197.223.242
2023-08-11 21:04:11,092 INFO:Region server arguments: ?regionHint=us-east-1
2023-08-11 21:04:18,720 INFO:Writing SMT rootCA: /etc/pki/trust/anchors
2023-08-11 21:04:18,744 INFO:Updating CA certificates: update-ca-certificates
2023-08-11 21:04:19,714 INFO:Modified /etc/hosts, added: 54.197.240.216 smt-ec2.susecloud.net   smt-ec2
```

On a "bad" node, we see:

```
-> sudo journalctl -u guestregister
Aug 11 21:03:11 ip-10-0-2-233 systemd[1]: Starting Obtain Cloud update server info and register with the server...
Aug 11 21:04:07 ip-10-0-2-233 systemd[1]: guestregister.service: Main process exited, code=exited, status=1/FAILURE
Aug 11 21:04:07 ip-10-0-2-233 systemd[1]: guestregister.service: Failed with result 'exit-code'.
Aug 11 21:04:07 ip-10-0-2-233 systemd[1]: Failed to start Obtain Cloud update server info and register with the server.

-> cat /var/log/cloudregister
2023-08-11 21:03:12,451 INFO:Region server arguments: ?regionHint=us-east-1
2023-08-11 21:03:12,452 INFO:Using API: regionInfo
2023-08-11 21:03:12,457 INFO:Region server arguments: ?regionHint=us-east-1
2023-08-11 21:03:12,457 INFO:Getting update server information, attempt 1
2023-08-11 21:03:12,457 INFO:   Using region server: 2400:7fc0:8ad4:9e00:78bd:8464:c08c:f4f6
2023-08-11 21:03:12,460 ERROR:  No response from: 2400:7fc0:8ad4:9e00:78bd:8464:c08c:f4f6
2023-08-11 21:03:12,460 INFO:   Using region server: 2600:1f13:355:4700:ee7a:f5f8:6b38:c9c
2023-08-11 21:03:12,461 ERROR:  No response from: 2600:1f13:355:4700:ee7a:f5f8:6b38:c9c
2023-08-11 21:03:12,461 INFO:   Using region server: 2406:da12:878:8b00:9ea4:1263:39d3:bda1
2023-08-11 21:03:12,462 ERROR:  No response from: 2406:da12:878:8b00:9ea4:1263:39d3:bda1
2023-08-11 21:03:12,463 INFO:   Using region server: 2600:1f18:4665:e200:3aa2:d7c:2176:70c3
2023-08-11 21:03:12,464 ERROR:  No response from: 2600:1f18:4665:e200:3aa2:d7c:2176:70c3
2023-08-11 21:03:12,464 INFO:   Using region server: 2406:da1c:f2a:8400:9982:83c:559d:7f56
2023-08-11 21:03:12,465 ERROR:  No response from: 2406:da1c:f2a:8400:9982:83c:559d:7f56
2023-08-11 21:03:12,465 INFO:   Using region server: 2a05:d018:71c:e300:5ec0:8a24:7b5d:86ef
2023-08-11 21:03:12,467 ERROR:  No response from: 2a05:d018:71c:e300:5ec0:8a24:7b5d:86ef
2023-08-11 21:03:12,467 INFO:   Using region server: 54.223.148.145
2023-08-11 21:03:27,483 ERROR:  No response from: 54.223.148.145
2023-08-11 21:03:27,483 INFO:   Using region server: 54.247.166.75
2023-08-11 21:03:42,500 ERROR:  No response from: 54.247.166.75
2023-08-11 21:03:42,501 INFO:   Using region server: 34.197.223.242
2023-08-11 21:03:57,517 ERROR:  No response from: 34.197.223.242
2023-08-11 21:03:57,518 INFO:   Using region server: 52.79.82.165
2023-08-11 21:04:01,092 INFO:Region server arguments: ?regionHint=us-east-1
2023-08-11 21:04:07,104 ERROR:No response from: [('54.197.240.216', None), ('54.225.105.144', None), ('107.22.231.220', None)]
```

It seems the "bad" node is able to make contact with the "region" server, but none of the update servers.

A simple workaround on a node that previously experienced the issue is:

```bash
sudo systemctl restart guestregister
sudo zypper refresh
```

I have tried this on a couple of nodes after Longhorn installation failure, and it has always seemed to work. This supports the idea that there is some temporary networking issue we just need to overcome. We can probably add these commands (or similar) to the user-data-scripts to get unstuck.

While the reason this only happens with SLES SP15 isn't clear to me, I have a hunch that the way we are handling Terraform dependencies exacerbates the problem. We define our worker nodes like:

```tf
resource "aws_instance" "lh_aws_instance_worker_rke2" {
  depends_on = [
    aws_internet_gateway.lh_aws_igw,
    aws_subnet.lh_aws_private_subnet,
    aws_instance.lh_aws_instance_controlplane_rke2
  ]
```

However, our worker nodes do not get the ability to communicate with the internet directly from the internet gateway (`lh_aws_igw`). They require a NAT gateway and certain route associations. I am experimenting with reordering the Terraform dependency graph to avoid the issue altogether. If that doesn't work, we can resort to the service restart instead.

**Comment by ejweber** [comment] 2023-08-15 19:10
The resource reorder seems to have been effective (five deployments in a row had no failures), but I'm not 100% it makes sense. The logs posted above suggest that at least some communication was established with the SUSE update infrastructure on failing nodes. If communication was possible, it seems the network should have been in a solid enough state to continue.

I will submit a PR with the reorder and the `guestmanager` restart to be safe.

**Comment by ejweber** [comment] 2023-08-15 19:49
The old AMI used v10.1.0 of `guestregister` and its associated scripts. The new AMI uses v10.1.2. I cannot see any changes that would cause the behavior we are observing

https://github.com/SUSE-Enceladus/cloud-regionsrv-client/compare/v10.1.0...master

I submitted https://github.com/SUSE-Enceladus/cloud-regionsrv-client/issues/125 in case there's something the cloud registration team can see in our logs.

**Comment by rjschwei** [comment] 2023-08-15 20:06
There is nothing in the logs that would indicate anything other than a network issue. While the initial connection, where the failure occurs is singular later connections when setting up repositories and pulling packages are no longer singular, i.e. zypper will make many connections. As such running behind a NAT has certain risks attached to it. I am not very familiar with NAT configuration in EC2 as such I cannot make an assessment on the impact of running behind a NAT.

**Comment by chriscchien** [comment] 2023-09-01 08:05
Verified **pass** on longhorn master(longhorn-test `f3324d`)

After the [fix](https://github.com/longhorn/longhorn-tests/pull/1504#event-10151896123) merged, master pipeline had continuous 10 times install longhorn success(before the fix, pipeline will randomly encounter install longhorn fail by `Error: longhorn installation timeout`)
- AMD64 : build [635](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/635/) to build [643](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/643/)
- ARM64 : build [585](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/585/) to build [593](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/593/)

**Closed by chriscchien** 2023-09-01 08:05 UTC
Labels: kind/bug, reproduce/often, area/environment-issue
