### ISSUE TITLE
[BUG]Cannot add a new available disk after the only disk doesn't work on the node

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1291] opened 2020-05-04 10:53 UTC
**Describe the bug**
When the only disk doesn't work on the node, adding a new disk via UI cannot make the node become `Schedulable`.

**To Reproduce**
1. Deploy Longhorn.
2. Attach a new (Linux) disk/volume to one node. Then create an extra Longhorn disk for the corresponding Longhorn node, make the extra Longhorn disk schedulable.
3. Delete the default disk for the Longhorn node.
4. Umount that extra (Linux) disk. Wait for the node becoming `Unschedulable`.
5. Add back the default disk.

**Expected behavior**
The node should become `Schedulable` and Longhorn should be able to detect the info of the added default disk.

**Log**
The manager log:
```
[longhorn-manager-p7kwx] time="2020-05-04T10:43:33Z" level=debug msg="Updated node shuo-longhorn-cluster-1-node-2 to {Name:shuo-longhorn-cluster-1-node-2 Disks:map[disk-2:{Path:/mnt/extra/ AllowScheduling:true StorageReserved:0 Tags:[]}] AllowScheduling:true Tags:[]}"
[longhorn-manager-p7kwx] 45.56.105.37 - - [04/May/2020:10:43:33 +0000] "PUT /v1/nodes/shuo-longhorn-cluster-1-node-2 HTTP/1.1" 200 1590 "http://45.56.105.37:30000/node" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/81.0.4044.122 Safari/537.36"

[longhorn-manager-p7kwx] time="2020-05-04T10:43:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"shuo-longhorn-cluster-1-node-2\", UID:\"aad1552d-fdd4-4b7c-b3e0-3d407f0bb03b\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6440400\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Disk disk-3(/var/lib/longhorn/) on node shuo-longhorn-cluster-1-node-2 is not ready: disk has same file system ID 58fe937c58377e45 as other disks [disk-2 disk-3]"

[longhorn-manager-p7kwx] time="2020-05-04T10:43:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"shuo-longhorn-cluster-1-node-2\", UID:\"aad1552d-fdd4-4b7c-b3e0-3d407f0bb03b\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6440400\", FieldPath:\"\"}): type: 'Warning' reason: 'Schedulable' the disk disk-3(/var/lib/longhorn/) on the node shuo-longhorn-cluster-1-node-2 has 0 available, but requires reserved 0, minimal 25% to schedule more replicas"
[longhorn-manager-p7kwx] time="2020-05-04T10:43:33Z" level=debug msg="Updated node disks of shuo-longhorn-cluster-1-node-2 to map[disk-2:{Path:/mnt/extra/ AllowScheduling:true StorageReserved:0 Tags:[]} disk-3:{Path:/var/lib/longhorn/ AllowScheduling:true StorageReserved:0 Tags:[]}]"
```

The node info:
```
~ kl get nodes.longhorn.io shuo-longhorn-cluster-1-node-2 -o yaml
apiVersion: longhorn.io/v1beta1
kind: Node
metadata:
  creationTimestamp: "2020-05-04T05:26:45Z"
  finalizers:
  - longhorn.io
  generation: 30
  name: shuo-longhorn-cluster-1-node-2
  namespace: longhorn-system
  resourceVersion: "6440402"
  selfLink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/nodes/shuo-longhorn-cluster-1-node-2
  uid: aad1552d-fdd4-4b7c-b3e0-3d407f0bb03b
spec:
  allowScheduling: true
  disks:
    disk-2:
      allowScheduling: true
      path: /mnt/extra/
      storageReserved: 0
      tags: null
    disk-3:
      allowScheduling: true
      path: /var/lib/longhorn/
      storageReserved: 0
      tags: null
  name: shuo-longhorn-cluster-1-node-2
  tags: null
status:
  conditions:
    MountPropagation:
      lastProbeTime: ""
      lastTransitionTime: "2020-05-04T05:26:45Z"
      message: ""
      reason: ""
      status: "True"
      type: MountPropagation
    Ready:
      lastProbeTime: ""
      lastTransitionTime: "2020-05-04T05:27:06Z"
      message: Node shuo-longhorn-cluster-1-node-2 is ready
      reason: ""
      status: "True"
      type: Ready
  diskStatus:
    disk-2:
      conditions:
        Ready:
          lastProbeTime: ""
          lastTransitionTime: "2020-05-04T10:42:41Z"
          message: 'Disk disk-2(/mnt/extra/) on node shuo-longhorn-cluster-1-node-2
            is not ready: cannot find disk config file, maybe due to a mount error'
          reason: DiskFilesystemChanged
          status: "False"
          type: Ready
        Schedulable:
          lastProbeTime: ""
          lastTransitionTime: "2020-05-04T10:42:41Z"
          message: the disk disk-2(/mnt/extra/) on the node shuo-longhorn-cluster-1-node-2
            has 0 available, but requires reserved 0, minimal 25% to schedule more
            replicas
          reason: DiskPressure
          status: "False"
          type: Schedulable
      diskUUID: f0d3ffa6-c1bf-4bd9-886c-e722d9b70a8a
      scheduledReplica: {}
      storageAvailable: 0
      storageMaximum: 0
      storageScheduled: 0
    disk-3:
      conditions:
        Ready:
          lastProbeTime: ""
          lastTransitionTime: "2020-05-04T10:43:33Z"
          message: 'Disk disk-3(/var/lib/longhorn/) on node shuo-longhorn-cluster-1-node-2
            is not ready: disk has same file system ID 58fe937c58377e45 as other disks
            [disk-2 disk-3]'
          reason: DiskFilesystemChanged
          status: "False"
          type: Ready
        Schedulable:
          lastProbeTime: ""
          lastTransitionTime: "2020-05-04T10:43:33Z"
          message: the disk disk-3(/var/lib/longhorn/) on the node shuo-longhorn-cluster-1-node-2
            has 0 available, but requires reserved 0, minimal 25% to schedule more
            replicas
          reason: DiskPressure
          status: "False"
          type: Schedulable
      diskUUID: ""
      scheduledReplica: {}
      storageAvailable: 0
      storageMaximum: 0
      storageScheduled: 0
  region: ""
  zone: ""
```

**Environment:**
 - Longhorn version: v0.8.1
 - Kubernetes version: v1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**
- This log reflects the cause of this issue:
```
[longhorn-manager-p7kwx] time="2020-05-04T10:43:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"shuo-longhorn-cluster-1-node-2\", UID:\"aad1552d-fdd4-4b7c-b3e0-3d407f0bb03b\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6440400\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Disk disk-3(/var/lib/longhorn/) on node shuo-longhorn-cluster-1-node-2 is not ready: disk has same file system ID 58fe937c58377e45 as other disks [disk-2 disk-3]"
```
- One simple workaround: Delete the invalid disk.

**Comment by yasker** [comment] 2020-05-05 06:50
If the disk's UUID check failed, we don't need to check the FSID.

**Comment by boknowswiki** [comment] 2020-05-13 19:08
@shuo-wu , thanks for providing the steps, I am able to reproduce this issue.

The reason the default disk can not be mark as schedulable is because it's in the same filesystem as the other path(which has been mounted to extra disk, but after unmount it, this path is the same filesystem as default disk path). Since we don't allow multiple paths in the same filesystem, in this case probably user has to either remove the extra disk(the unmounted path one) or mount it back to be able to add this default disk back to schedulable.

Please let me know what you think.

**Comment by yasker** [comment] 2020-05-13 20:29
The problem here is because the extra disk wasn't supposed to be on the same filesystem as the default disk. It failed disk UUID check already. So in this case, it doesn't make sense to check the filesystem ID of the extra disk because the extra disk doesn't suppose to use the root filesystem.

**Comment by boknowswiki** [comment] 2020-05-15 16:35
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ]~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by sowmyav27** [comment] 2020-05-19 05:43
**Reproduced the issue on 0.8.1 release**

**Steps:**

- Deploy Longhorn.
- Attach a new (Linux) disk/volume to one node. Then create an extra Longhorn disk for the corresponding Longhorn node, make the extra Longhorn disk schedulable.
- Delete the default disk for the Longhorn node.
- Umount that extra (Linux) disk. Wait for the node becoming Unschedulable.
- Add back the default disk.
- Node does not become `Schedulable`. Default disk is not recognized.

**Verified on master - 05/18/2020 - 22:00 PDT**

**Steps:**

- Deploy Longhorn.
- Attach a new (Linux) disk/volume to one node. Then create an extra Longhorn disk for the corresponding Longhorn node, make the extra Longhorn disk schedulable.
- Delete the default disk for the Longhorn node.
- Umount that extra (Linux) disk. Wait for the node becoming Unschedulable.
- Add back the default disk.
- Default disk is recognized and node becomes `Schedulable`
- Create a volume - 3 replicas - replica will schedule on the node ^^^ in the default disk.
- Attach volume to node. the replicas will be running state.

**Comment by boknowswiki** [comment] 2020-05-20 00:38
@meldafrawi , for your information, I will take care the test case for this #1291.

**Comment by yasker** [comment] 2020-05-26 17:31
The test case results in https://github.com/longhorn/longhorn/issues/1402 , which is later fixed by https://github.com/longhorn/longhorn-tests/pull/339

**Closed** 2020-05-28 21:56 UTC
Labels: area/manager, bug, priority/3, reproduce/always, require/automation-e2e
