### ISSUE TITLE
Volumes created with Block frontend fail to attach

### ISSUE THREAD

**Issue by jej2003** [longhorn/longhorn#3781] opened 2022-03-23 21:50 UTC
I'll start by saying I'm new to K8s and longhorn as well. I have setup a simple rke2 single node setup, installed longhorn following the documentation and everything appears to be ok. When creating a volume through the longhorn UI if I select Block frontend and try to attach it the volume state bounces from "Attaching" to "Detaching" and eventually fails. If I instead specify the iSCSI frontend it can be attached as expected. If I select maintenance when attaching it, it also attaches fine. I am struggling to figure out where to start debugging the issue, can anyone point me in the right direction?
## Environment

 - Longhorn version: latest 
 - Kubernetes version: Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.7+rke2r2", GitCommit:"b56e432f2191419647a6a13b9f5867801850f969", GitTreeState:"clean", BuildDate:"2022-03-04T23:17:38Z", GoVersion:"go1.16.14b7", Compiler:"gc", Platform:"linux/amd64"}
 - Node config
   - OS type and version: Rocky Linux 7
   - CPU per node: 4
   - Memory per node: 16GB
   - Disk type believe the interface to the VM is SCSI
   - Network bandwidth and latency between the nodes: single node
 - Underlying Infrastructure VMWare/KVM

**Comment by jej2003** [comment] 2022-03-24 03:49
after reading the documentation I've seen that longhorn is not compatible with the version of rke2 I was using so I switched as follows

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14+rke2r1", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T21:39:40Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.14+rke2r1", GitCommit:"57a3aa3f13699cf3db9c52d228c18db94fa81876", GitTreeState:"clean", BuildDate:"2021-12-15T21:39:40Z", GoVersion:"go1.15.15b5", Compiler:"gc", Platform:"linux/amd64"}

still seeing the same behavior though.

**Comment by PhanLe1010** [comment] 2022-03-24 23:29
> after reading the documentation I've seen that longhorn is not compatible with the version of rke2 I was using so I switched as follows

Can you point me to the doc? Longhorn should work with rke2 

It seems that you are missing some prerequisites on the host. Could you please check https://longhorn.io/docs/1.2.4/deploy/install/#installation-requirements. Especially the, iscsi stuff

**Comment by jej2003** [comment] 2022-03-25 01:12
It does work with rke2, I had issues with the latest version of rke2.  I can't find the github post, but it indicated that longhorn worked with 1.21, not 1.22 version of rke.  Perhaps that is no longer valid?

There were a number of other changes we made (install nfs-utils, disable firewalld, add exceptions for NetworkManager) as detailed in the instructions and known issues.

**Comment by PhanLe1010** [comment] 2022-03-28 23:36
Longhorn v1.2.4 should work with both kubernetes 1.21 and 1.22.

Since the issue is resolved:
(`There were a number of other changes we made (install nfs-utils, disable firewalld, add exceptions for NetworkManager) as detailed in the instructions and known issues.`), I am closing this issue. Feel free to open it if any further question

**Closed by PhanLe1010** 2022-03-28 23:36 UTC
Labels: kind/question
