### ISSUE TITLE
[BUG] v2 snapshot creation time will change in UI from time to time

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#7641] opened 2024-01-12 03:34 UTC
## Describe the bug

The reason is that, the caller randomly picks up a replica and its snapshot map each time when the UI requires snapshot info. And there may be 1 second gap when creating a snapshot among different replicas.

I am trying to ask the engine to collect the info and always pick up the replica that holds the earliest ancestor as the info provider. But the following is, things still change once **all replicas get rebuilt**.

For example:
1. Before rebuilding
Replica1: snap1 (time=5) -> snap2 (time 7) -> volume-head (time 12)
Replica2: snap1 (time=4) -> snap2 (time 8 ) -> volume-head (time 13) <== pick up this
2. Rebuilding replica 1
Replica1: snap1 (time=14) -> snap2 (time 15) -> volume-head (time 15)
Replica2: snap1 (time=4) -> snap2 (time 8 ) -> volume-head (time 13) <== pick up this
3. Rebuilding replica 2
Replica1: snap1 (time=14) -> snap2 (time 14) -> volume-head (time 14) <== pick up this. Change!
Replica2: snap1 (time=20) -> snap2 (time 21 ) -> volume-head (time 21)

Currently, there are 2 solution candidates:
- [ ] Make the creation timestamp as the input of lvol creation API
- [ ] Put the creation time in lvol xattr instead

## To Reproduce

1. Create and attach a v2 volume
2. Create some snapshots
3. Wait a while, then delete one replica
4. Detach the volume and trigger the offline rebuilding. And wait for rebuilding complete
5. Wait a while, then delete all other replicas
6. Wait for rebuilding complete
7. Reattach the volume, check the snapshot creation time

## Expected behavior

The creation time should not change

## Environment

 - Longhorn version: v1.6.0-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

cc @derekbit

**Comment by derekbit** [comment] 2024-01-12 03:48
Creation timestamp is created when taking a snapshot. Unlike v1 volume, the creation timestamp is stored in meta file, so it won't be changed after rebuilding.

After discussing with @shuo-wu, one solution is that we can save creation time got from engine to the xattr of a lvol rather than using the value created when taking a snapshot.

**Comment by derekbit** [comment] 2024-01-12 04:25
> Creation timestamp is created when taking a snapshot. Unlike v1 volume, the creation timestamp is stored in meta file, so it won't be changed after rebuilding.
> 
> After discussing with @shuo-wu, one solution is that we can save creation time got from engine to the xattrs of the downstream lvols rather than using the value created when taking a snapshot.

Unfortunately, xattrs are read-only for a snapshot lvol.
I'm thnking if I can add a `force` option in `bdev_lvol_set_xattr` method.
WDYT? @shuo-wu @DamiaSan @innobead

**Comment by DamiaSan** [comment] 2024-01-12 09:13
I don't know if it is a good idea, if we add this option we must add it not only to `spdk_blob_set_xattr` but also to `spdk_blob_sync_md`. Because in `spdk_blob_sync_md` we have:
```
	if (blob->md_ro) {
		assert(blob->state == SPDK_BLOB_STATE_CLEAN);
		cb_fn(cb_arg, 0);
		return;
	}
```
A snapshot has read only metadata and, setting an xattr, make the state of the blob `SPDK_BLOB_STATE_DIRTY`. So we run into the assert.

**Comment by DamiaSan** [comment] 2024-01-12 09:26
For head lvols, you can change the creation time with the RPC `bdev_lvol_set_xattr`.
For the snapshots, what we can do is to pass a list of xattr to the RPC `bdev_lvol_snapshot`: in this way we can set the `creation_time` we want and we can also set the `user_created` flag when needed.
WDYT? @shuo-wu @DamiaSan @innobead
Let me know because this impact the development I am finishing about the `user_created` flag.

**Comment by derekbit** [comment] 2024-01-12 09:29
> For the snapshots, what we can do is to pass a list of xattr to the RPC bdev_lvol_snapshot: in this way we can set the creation_time we want and we can also set the user_created flag when needed.

Sounds doable...TBH, the way is a little bit ugly.
Currently, all metadata of a snapshot lvol is always immutable, but I think it should support mutable fields as well.

**Comment by DamiaSan** [comment] 2024-01-12 09:38
Why do you think it is not easy to maintain?
If a snapshot is immutable, you are simply writing all your metadata when you create it. SPDK internally already does something similar, writing lvol name and uuid as xattr of the snapshot blob it is creating.

**Comment by derekbit** [comment] 2024-01-12 09:53
@DamiaSan 
Please ignore the previous comment (I already deleted it). I misunderstood your idea before.

> For the snapshots, what we can do is to pass a list of xattr to the RPC `bdev_lvol_snapshot`: in this way we can set the `creation_time` we want and we can also set the `user_created` flag when needed.

Yes, this is what we said in above [conversation](https://github.com/longhorn/longhorn/issues/7641#issuecomment-1888389878).
BTW, when rebuilding a replica, can we read the source snapshot's creation timestamp and create a destination snapshot with it? Is my understanding correct?

**Comment by DamiaSan** [comment] 2024-01-17 07:33
Implemented a generic list of xattr in this issue: #7578

**Comment by derekbit** [comment] 2024-01-18 07:33
Hello @DamiaSan, 
Before moving it to review, need to integrate to go-spdk-helper, longhorn-spdk-engine and longhorn-instance-manager as well.

**Comment by DamiaSan** [comment] 2024-01-18 07:39
Related PR for SPDK support: https://github.com/longhorn/spdk/pull/26

**Comment by DamiaSan** [comment] 2024-05-17 10:05
> @DamiaSan Is it resolved? 

I think so, all the works have been done.

**Comment by shuo-wu** [comment] 2024-05-17 17:34
Wait... Do we update `longhorn-spdk-engine` and `longhorn-manager`?

**Comment by DamiaSan** [comment] 2024-06-07 13:07
> Wait... Do we update `longhorn-spdk-engine` and `longhorn-manager`?

You are right

**Comment by DamiaSan** [comment] 2024-06-07 13:11
I was thinking that, if we let a snapshot to store new xattr after its creation (like for example the checksum), this functionality to pass xattr at snapshot creation may become obsolete.
WDYT?

**Comment by DamiaSan** [comment] 2024-06-11 14:58
PR for types https://github.com/longhorn/types/pull/12

**Comment by shuo-wu** [comment] 2024-06-11 18:09
Do you mean asking the snapshot API in `go-spdk-helper` to add the creation timestamp xattr? I am fine with it.

**Comment by derekbit** [comment] 2024-06-12 08:09
> We have decided to calculate the snapshot checksum inside SPDK, so there is no need to implement the functionality to add an xattr after the snapshot creation. So the functionality to add xattrs at snapshot creation will continue to be used.

OK. Then, go head remove it.

**Comment by DamiaSan** [comment] 2024-06-14 08:41
After `types`, some works on `go-spdk-helper` and `longhorn-spdk-engine` are needed to complete the issue.

**Comment by DamiaSan** [comment] 2024-06-27 08:42
`longhorn-spdk-engine` PR https://github.com/longhorn/longhorn-spdk-engine/pull/162
`longhorn-instance-manager` PR https://github.com/longhorn/longhorn-instance-manager/pull/534

**Comment by derekbit** [comment] 2024-06-27 09:04
Hello @DamiaSan 
Need to fill the form https://github.com/longhorn/longhorn/issues/7641#issuecomment-1897918543

**Comment by chriscchien** [comment] 2024-07-01 01:48
Hello @shuo-wu, @DamiaSan 

Currently v2 volume offline rebuilding is disabled on longhorn master, the reproduce [steps](https://github.com/longhorn/longhorn/issues/7641#issue-2078003315) are outdated, could you provide other validate steps for this issue? thank you.

**Comment by DamiaSan** [comment] 2024-07-01 08:07
The offline rebuilding is disabled but now we should have the online rebuilding. However, whatever is the rebuilding implemented, I think the reproduction steps are the same and so still valid. You have to simply _wait for rebuilding complete_, right @shuo-wu ?
But, before to proceed with this issue, we must before fix the [issue](https://github.com/longhorn/longhorn/issues/8862) that this development has probably introduced.

**Comment by chriscchien** [comment] 2024-07-02 02:30
> The offline rebuilding is disabled but now we should have the online rebuilding. However, whatever is the rebuilding implemented, I think the reproduction steps are the same and so still valid. You have to simply _wait for rebuilding complete_, right @shuo-wu ? But, before to proceed with this issue, we must before fix the [issue](https://github.com/longhorn/longhorn/issues/8862) that this development has probably introduced.

This ticket needs to wait until the v2 volume online rebuilding is introduced first to validate.
![image](https://github.com/longhorn/longhorn/assets/73337386/143c08e8-7d8d-4119-90be-a11353802aaa)

**Comment by derekbit** [comment] 2024-07-02 16:38
cc @shuo-wu @innobead  👆

**Comment by DamiaSan** [comment] 2024-07-08 04:50
> The offline rebuilding is disabled but now we should have the online rebuilding. However, whatever is the rebuilding implemented, I think the reproduction steps are the same and so still valid. You have to simply _wait for rebuilding complete_, right @shuo-wu ? But, before to proceed with this issue, we must before fix the [issue](https://github.com/longhorn/longhorn/issues/8862) that this development has probably introduced.

The issue has been fixed, so the development is ready to be tested once the rebuilding will be enabled again.

**Comment by DamiaSan** [comment] 2024-07-24 10:15
@chriscchien  online rebuilding has been merged

**Comment by chriscchien** [comment] 2024-07-25 02:17
Hi @DamiaSan ,

Snapshot created in `v1.7.x-head` not hit the creation time change issue, but hit this issue if snapshot created in `v1.6.2` then upgrade to `v1.7.x-head`

Steps:
1. Create v2 volume and have data and sanpshots
```bash
>kl get engineimage
NAME          INCOMPATIBLE   STATE      IMAGE                               REFCOUNT   BUILDDATE   AGE
ei-b0369a5d   false          deployed   longhornio/longhorn-engine:v1.6.2   0          63d         4m21s
>
> kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE               AGE
pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   v2            attached   healthy                  1073741824   ip-172-31-42-172   91s
>
> kl get snapshot
NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
f78370a0-926e-4436-ae59-2ae10084fe98   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:48:40Z   true         1073741824    161480704   44s
3a165f31-e52f-4f0a-8eb3-4f30786be050   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:48:48Z   true         1073741824    108003328   34s
a0ba1dda-f161-4d37-8242-fd66c17868ec   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:49:02Z   true         1073741824    108003328   19s
```
2. Detach v2 volume, upgrade to v1.7.x-head
3. Attach the v2 volume
```bash
> kl get engineimage
NAME          INCOMPATIBLE   STATE      IMAGE                                    REFCOUNT   BUILDDATE   AGE
ei-b0369a5d   false          deployed   longhornio/longhorn-engine:v1.6.2        0          63d         13m
ei-3c71f773   false          deployed   longhornio/longhorn-engine:v1.7.x-head   0          2d1h        3m27s
>
> kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE              AGE
pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   v2            attached   healthy                  1073741824   ip-172-31-37-41   12m
```
4. Trigger replica rebuilding serveral times, can see snapshot `3a165f31-e52f-4f0a-8eb3-4f30786be050` creation time changed from `2024-07-25T01:48:48Z` to `2024-07-25T02:00:44Z`
```bash
> kl get snapshot -w
NAME                                   VOLUME                                     CREATIONTIME           READYTOUSE   RESTORESIZE   SIZE        AGE
3a165f31-e52f-4f0a-8eb3-4f30786be050   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:48:48Z   true         1073741824    108003328   11m
a0ba1dda-f161-4d37-8242-fd66c17868ec   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:49:02Z   true         1073741824    108003328   11m
f78370a0-926e-4436-ae59-2ae10084fe98   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:48:40Z   true         1073741824    161480704   11m
a0ba1dda-f161-4d37-8242-fd66c17868ec   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T01:49:02Z   true         1073741824    108003328   11m
rebuild-05c69e17                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9                                                                 0s
rebuild-05c69e17                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25 02:00:41.515614094 +0000 UTC m=+302.713638322   true         1073741824    2097152     0s
rebuild-05c69e17                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25 02:00:41.515614094 +0000 UTC m=+302.713638322   true         1073741824    2097152     39s
rebuild-ce53e846                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9                                                                                                     0s
rebuild-ce53e846                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25 02:01:20.725620921 +0000 UTC m=+341.923648130   true         1073741824    0           0s
3a165f31-e52f-4f0a-8eb3-4f30786be050   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T02:00:44Z                                       true         1073741824    108003328   12m
a0ba1dda-f161-4d37-8242-fd66c17868ec   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T02:00:45Z                                       true         1073741824    108003328   12m
f78370a0-926e-4436-ae59-2ae10084fe98   pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25T02:00:43Z                                       true         1073741824    161480704   13m
rebuild-ce53e846                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25 02:01:20.725620921 +0000 UTC m=+341.923648130   true         1073741824    0           40s
rebuild-891d49dc                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9                                                                                                     0s
rebuild-891d49dc                       pvc-688e096d-d831-4a10-b2af-ecfeaf72c5d9   2024-07-25 02:02:01.160426788 +0000 UTC m=+382.358451023   true         1073741824    0           0s
```
![image](https://github.com/user-attachments/assets/b66b4cac-5be7-436e-8d9d-4e7904d780f5)

[supportbundle_ec67e93d-e081-4db1-9a08-7964ec139b0a_2024-07-25T02-05-53Z.zip](https://github.com/user-attachments/files/16369306/supportbundle_ec67e93d-e081-4db1-9a08-7964ec139b0a_2024-07-25T02-05-53Z.zip)

**Comment by derekbit** [comment] 2024-07-25 02:39
> Snapshot created in v1.7.x-head not hit the creation time change issue, but hit this issue if snapshot created in v1.6.2 then upgrade to v1.7.x-head

I think this is expected behavior for the snapshots created in v1.6.2, because they don't have snapshot_timestamp xattrs.
@DamiaSan WDYT?

**Comment by derekbit** [comment] 2024-07-25 03:48
Updated in https://github.com/longhorn/website/pull/951

cc @chriscchien @DamiaSan @innobead

**Comment by DamiaSan** [comment] 2024-07-25 09:01
> > Snapshot created in v1.7.x-head not hit the creation time change issue, but hit this issue if snapshot created in v1.6.2 then upgrade to v1.7.x-head
> 
> I think this is expected behavior for the snapshots created in v1.6.2, because they don't have snapshot_timestamp xattr. @DamiaSan WDYT?

You are right. In 1.6.2 snapshots don't have `snapshot_timestamp` xattr, so we make fallback on `creation_time` that change when the snapshot is recreated.

**Comment by derekbit** [comment] 2024-07-25 09:38
Thanks @DamiaSan's confirmation. @chriscchien I've added the known issue to the [important note](https://github.com/longhorn/website/pull/951).

**Comment by chriscchien** [comment] 2024-07-26 03:48
Verified **pass** on longhorn v1.7.0-rc2(longhorn-spdk-engine `c6a703`), longhorn master(longhorn-spdk-engine `c6a703`) with test [steps](https://github.com/longhorn/longhorn/issues/7641#issue-2078003315)

- V2 volume snapshot created in v1.7.0-dev and master will not change creation time while replica rebuilding.
- V2 volume snapshot created in v1.6.2 will change creation time while replica rebuilding after upgrade to v1.7.0-dev is [expected](https://github.com/longhorn/longhorn/issues/7641#issuecomment-2249311241)

**Closed by chriscchien** 2024-07-26 03:48 UTC
Labels: kind/bug, require/manual-test-plan, area/snapshot, require/important-note, area/spdk
