### ISSUE TITLE
[BUG] Nightly Upgrade Test: test_pvc_creation_with_default_sc_set failed

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1112] opened 2020-03-16 20:36 UTC
**Describe the bug**

**To Reproduce**
1. Install Longhorn v0.7.0
2. Upgrade Longhorn to v0.8.0
3. Run `test_pvc_creation_with_default_sc_set` test

**Expected behavior**
test should pass

**Log**
```
client = <longhorn.Client object at 0x7f4ecbd21250>
core_api = <kubernetes.client.apis.core_v1_api.CoreV1Api object at 0x7f4ecbff0190>
storage_class = {'allowVolumeExpansion': True, 'apiVersion': 'storage.k8s.io/v1', 'kind': 'StorageClass', 'metadata': {'annotations': {'storageclass.kubernetes.io/is-default-class': 'true'}, 'name': 'longhorn-test'}, ...}
pod = {'apiVersion': 'v1', 'kind': 'Pod', 'metadata': {'name': 'pod-test-pvc-creation-with-sc'}, 'spec': {'containers': [{'a...p', ...}], 'volumes': [{'name': 'pod-data', 'persistentVolumeClaim': {'claimName': 'pvc-test-pvc-creation-with-sc'}}]}}

    @pytest.mark.csi  # NOQA
    def test_pvc_creation_with_default_sc_set(
            client, core_api, storage_class, pod):  # NOQA
        # set default storage class
        storage_class['metadata']['annotations'] = \
            {"storageclass.kubernetes.io/is-default-class": "true"}
        create_storage_class(storage_class)
    
        static_sc_name = "longhorn-static-test"
        setting = client.by_id_setting(SETTING_DEFAULT_LONGHORN_STATIC_SC)
        setting = client.update(setting, value=static_sc_name)
        assert setting.value == static_sc_name
    
        volume_name = "test-pvc-creation-with-sc"
        pod_name = "pod-" + volume_name
        client.create_volume(name=volume_name, size=SIZE,
                             numberOfReplicas=2)
        volume = wait_for_volume_detached(client, volume_name)
    
        pv_name = "pv-" + volume_name
        pvc_name = "pvc-" + volume_name
        pvc_name_extra = "pvc-" + volume_name + "-extra"
    
        create_pv_for_volume(client, core_api, volume, pv_name)
        create_pvc_for_volume(client, core_api, volume, pvc_name)
    
        ret = core_api.list_namespaced_persistent_volume_claim(
            namespace='default')
        for item in ret.items:
            if item.metadata.name == pvc_name:
                pvc_found = item
                break
        assert pvc_found
        assert pvc_found.spec.storage_class_name == static_sc_name
    
        pod['metadata']['name'] = pod_name
        pod['spec']['volumes'] = [{
            'name': pod['spec']['containers'][0]['volumeMounts'][0]['name'],
            'persistentVolumeClaim': {
                'claimName': pvc_name,
            },
        }]
        create_and_wait_pod(core_api, pod)
    
        ks = {
            'pvName': pv_name,
            'pvStatus': 'Bound',
            'namespace': 'default',
            'pvcName': pvc_name,
            'lastPVCRefAt': '',
            'lastPodRefAt': '',
            'workloadsStatus': [{
                'podName': pod_name,
                'podStatus': 'Running',
                'workloadName': '',
                'workloadType': '',
            }, ],
        }
        wait_volume_kubernetes_status(client, volume_name, ks)
    
        delete_and_wait_pod(core_api, pod_name)
        delete_and_wait_pvc(core_api, pvc_name)
    
        ks = {
            'pvName': pv_name,
            'pvStatus': 'Released',
            'namespace': 'default',
            'pvcName': pvc_name,
            'lastPVCRefAt': 'not empty',
            'lastPodRefAt': 'not empty',
        }
        wait_volume_kubernetes_status(client, volume_name, ks)
    
        # try to reuse the pv
        volume = wait_for_volume_detached(client, volume_name)
>       create_pvc_for_volume(client, core_api, volume, pvc_name_extra)

test_kubernetes.py:355: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:2468: in create_pvc_for_volume
    volume.pvcCreate(namespace="default", pvcName=pvc_name)
longhorn.py:263: in cb
    *args, **kw)
longhorn.py:457: in action
    return self._post_and_retry(url, *args, **kw)
longhorn.py:415: in _post_and_retry
    raise e
longhorn.py:409: in _post_and_retry
    return self._post(url, data=self._to_dict(*args, **kw))
longhorn.py:74: in wrapped
    return fn(*args, **kw)
longhorn.py:303: in _post
    self._error(r.text, r.status_code)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <longhorn.Client object at 0x7f4ecbd21250>
text = '{"actions":{},"code":"Server Error","detail":"","links":{"self":"http://10.42.1.14:9500/v1/volumes/test-pvc-creation-...ated PVC pvc-test-pvc-creation-with-sc-extra doesn\'t bound PV, PV status is Available","status":500,"type":"error"}\n'
status_code = 500

    def _error(self, text, status_code):
>       raise ApiError(self._unmarshall(text), status_code)
E       longhorn.ApiError: (ApiError(...), '500 : unable to create PVC for volume test-pvc-creation-with-sc: created PVC pvc-test-pvc-creation-with-sc-extra doesn\'t bound PV, PV status is Available\n{\'code\': 500, \'detail\': \'\', \'message\': "unable to create PVC for volume test-pvc-creation-with-sc: created PVC pvc-test-pvc-creation-with-sc-extra doesn\'t bound PV, PV status is Available", \'status\': 500}')

longhorn.py:283: ApiError
```

**Environment:**
 - Longhorn version: 0.8.0
 - Kubernetes version: v1.17.2
 - Node OS type and version: Ubuntu 18.04

**Comment by shuo-wu** [comment] 2020-03-17 03:11
Duplicate of #1092

**Closed** 2020-03-17 06:34 UTC
Labels: area/test, bug
