### ISSUE TITLE
[BUG] Volume is seen in attached state after a DRV volume is activated when the last backup is deleted

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1380] opened 2020-05-21 06:19 UTC
**Describe the bug**
[BUG] Volume is seen in attached state after a DRV volume is activated when the last backup is deleted

**To Reproduce**

**Scenario#1**

1. Create a volume vol1, attach to workload in Cluster A
2. Write data
3. Take a backup b1
4. Create a DRV volume `test` in another cluster B from vol1 b1
5. Write data and take a backup b2
6. Verify `test` is restored with b2 when the `Backupstore Poll Interval` interval has passed.
7. Delete latest backup - b2 
8. Activate DRV `test` volume
9. The volume is seen in attached state

**Scenario#2**

1. Create a volume vol1, attach to workload in Cluster A
2. Write data
3. Take a backup b1
4. Create a DRV volume test in another cluster B from vol1 b1
5. Write data and take a backup b2
6. Before the `Backupstore Poll Interval` interval has passed and restore of b2 happens on DRV, Delete latest backup - b2
7. Activate DRV test volume
8. The volume is seen in attached state

**Expected behavior**
Volume should be in detached state

**Environment:**
 - Longhorn version: 1.0.0-rc1
 - Kubernetes version: 1.17.5
 - Node OS type and version: RKE DO Linux 18.04

**Comment by yasker** [comment] 2020-05-21 06:21
Let's investigate if there is a workaround. If so, we can fix it in v1.0.1 instead of v1.0.0.

**Comment by shuo-wu** [comment] 2020-05-21 14:44
Here is the cause of this bug:
1. The `bv.lastBackup` will become empty after deleting the latest backup:
https://github.com/longhorn/backupstore/blob/7f9a1e8a1d69eaaeb52d13793c539ba01085f82f/deltablock.go#L639
2. And the DR volume `lastBackup` field will be updated to empty, too:
https://github.com/longhorn/longhorn-manager/blob/73f1617797097025d9d7c707cc85ddee041dcf88/manager/backup.go#L63
3. Then the DR volume cannot be activated since the `v.Status.LastBackup != e.Status.LastRestoredBackup`:
https://github.com/longhorn/longhorn-manager/blob/73f1617797097025d9d7c707cc85ddee041dcf88/controller/volume_controller.go#L644

The solution:
Removing the check `v.Status.LastBackup == e.Status.LastRestoredBackup` for the activation.

**Comment by shuo-wu** [comment] 2020-05-21 15:22
One more manual test:
    1. Set a random backupstore.
    2. Create a volume, then create the corresponding PV, PVC and Pod.
    3. Write data to the pod volume and get the md5sum
       after the pod running.
    4. Create the 1st backup.
    5. Create a DR volume from the backup.
    6. Wait for the DR volume restore complete.
    7. Set a longer `backupPollInterval`
    8. Write data to the original volume then create the 2nd backup.
    9. Activate the DR volume **before** the incremental restore is triggered.
    10. Verify the DR volume:
         10.1. The field `lastBackup` will be forced updating to the 2nd backup.
         10.2. The incremental restore will be triggered.
    11. Wait for the incremental restore complete.
    11. Activate the DR volume and wait for it complete.
    12. Create PV/PVC/Pod for the activated volume.
    13. Validate the activated volume content. The activated volume should contain the data of the 2nd backup.

**Comment by shuo-wu** [comment] 2020-05-22 03:21
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [x] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] **if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?

**Comment by yasker** [comment] 2020-05-22 20:58
@shuo-wu please update the test skeleton.

I will make an exception and move this issue to Merged for RC2

**Comment by sowmyav27** [comment] 2020-05-22 21:27
**Validated on master - 05/22/2020**

Scenario#1

- Create a volume vol1, attach to workload in Cluster A
- Write data
- Take a backup b1
- Create a DRV volume test in another cluster B from vol1 b1
- Write data and take a backup b2
- Verify test is restored with b2 when the Backupstore Poll Interval interval has passed.
- Delete latest backup - b2
- Activate DRV test volume
- The volume is seen in detached state
- Create PV/PVC for the volume and attach to a workload. The volume has contents of b2 also.

Scenario#2

- Create a volume vol1, attach to workload in Cluster A
- Write data
- Take a backup b1
- Create a DRV volume test in another cluster B from vol1 b1
- Write data and take a backup b2
- Before the Backupstore Poll Interval interval has passed and restore of b2 happens on DRV, Delete latest backup - b2
- Restore happens on the DRV volume
- Activate DRV test volume
- The volume is seen in detached state
- - Create PV/PVC for the volume and attach to a workload. The volume has contents of b2 also.

**Comment by shuo-wu** [comment] 2020-05-23 01:06
@sowmyav27 
For scenario #2, you need to use **2 separate clusters** and DO NOT delete the last backup in the Cluster that contains the DR volume. Since listing backup operation/entering backup page will trigger DRV incremental restore without waiting for the poll interval. 

In your test step, the last backup is being restored by the DRV and suddenly gets deleted, then the DRV  becomes Faulted.

**Comment by sangeethah** [comment] 2020-05-23 14:11
For the Scenario#2 tracked in https://github.com/longhorn/longhorn/issues/1392 , we should consider providing a warning message to the user when deleting backups of the volume that have DRV associated with them.

**Comment by yasker** [comment] 2020-05-23 18:15
There isn't a way for us to tell if any volume is restoring using the backup when a user is deleting it (otherwise we can just stop them from using it). We can add a general warning message to delete backup and delete the whole backup volume. It can be filed as a separate UI issue.

**Comment by sowmyav27** [comment] 2020-05-23 19:35
Logged a UI issue - https://github.com/longhorn/longhorn/issues/1396

**Comment by meldafrawi** [comment] 2020-05-28 22:29
@shuo-wu 

test_dr_volume_with_last_backup_deletion failed at **longhorn-tests/457**

**Comment by meldafrawi** [comment] 2020-05-29 22:08
test_dr_volume_with_last_backup_deletion passed

**Closed by meldafrawi** 2020-05-29 22:08 UTC
Labels: area/manager, bug, reproduce/always, require/automation-e2e
