### ISSUE TITLE
[BUG] Observed massive `CSI UnmountVolume failed` in the kubelet log

### ISSUE THREAD

**Issue by nickngch** [longhorn/longhorn#2368] opened 2021-03-17 05:18 UTC
**Describe the bug**
Observed massive `CSI UnmountVolume failed` in the kubelet log, it is printing millions of similar messages with an hour, which contributed to kubelet log's size to over 200GB

Example:
```
2021-03-11T16:00:00.043044571Z E0311 16:00:00.042950    5374 reconciler.go:193] operationExecutor.UnmountVolume failed (controllerAttachDetachEnabled true) for volume "prometheus-rancher-monitoring-prometheus-db" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-c0476841-425f-4b3f-a638-3ef0c8aade2d") pod "d46145b2-fe45-4dd9-8628-e67746e609cf" (UID: "d46145b2-fe45-4dd9-8628-e67746e609cf") : UnmountVolume.NewUnmounter failed for volume "prometheus-rancher-monitoring-prometheus-db" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-c0476841-425f-4b3f-a638-3ef0c8aade2d") pod "d46145b2-fe45-4dd9-8628-e67746e609cf" (UID: "d46145b2-fe45-4dd9-8628-e67746e609cf") : kubernetes.io/csi: unmounter failed to load volume data file [/var/lib/kubelet/pods/d46145b2-fe45-4dd9-8628-e67746e609cf/volumes/kubernetes.io~csi/pvc-c0476841-425f-4b3f-a638-3ef0c8aade2d/mount]: kubernetes.io/csi: failed to open volume data file [/var/lib/kubelet/pods/d46145b2-fe45-4dd9-8628-e67746e609cf/volumes/kubernetes.io~csi/pvc-c0476841-425f-4b3f-a638-3ef0c8aade2d/vol_data.json]: open /var/lib/kubelet/pods/d46145b2-fe45-4dd9-8628-e67746e609cf/volumes/kubernetes.io~csi/pvc-c0476841-425f-4b3f-a638-3ef0c8aade2d/vol_data.json: no such file or directory
```

**To Reproduce**
- Not sure what triggered that at the moment

**Expected behavior**
Message printing out in a lower frequency

**Log**

[podlogs.zip](https://github.com/longhorn/longhorn/files/6153897/podlogs.zip)

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 10
 - Node config
   - OS type and version: Oracle Server Linux 7.9
   - CPU per node: 64
   - Memory per node: 128GB
   - Disk type(e.g. SSD/NVMe): ?
   - Network bandwidth between the nodes: ?
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): ?
 - Number of Longhorn volumes in the cluster: ?

**Additional context**
Looks like related  https://github.com/kubernetes/kubernetes/issues/85280

**Comment by cclhsu** [comment] 2021-03-17 09:02
Hi! The log provided is limited.  Is it possible for you to provide the support bundle?

**Comment by shuo-wu** [comment] 2021-04-27 02:06
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by shuo-wu** 2021-04-27 02:06 UTC
Labels: area/csi, kind/bug, kind/question

**Comment by xenuser** [comment] 2022-10-25 12:34
Issue still happens for us on RKE 1, Kubernetes  v1.19.10  and Longhorn 1.3.1
Is there nobody looking at this issue?
This is a showstopper if central logging is flooded with tons of logs

**Comment by shuo-wu** [comment] 2022-10-26 12:16
@xenuser 
It seems that kubelet does not clean up the volume mount gracefully when there is something unexpected happens... But to be honest, we have not taken time to find a good reproducing step and investigate the cause... 
If you have any clues, that would be great!

**Comment by xenuser** [comment] 2022-10-26 14:10
Thanks @shuo-wu for providing a response! Actually, we are not sure how we ended up here in the first place, so it will be hard to provide instructions on how to reproduce this issue. Is there any known workaround on how at least stop this log flooding (without having to solve the underlying problem)?

**Comment by oau-dev** [comment] 2022-10-26 14:12
hello

same problem here with cri-o and k8s 1.24. The only wa we found is to purge log with crontab.

oau
