### ISSUE TITLE
[BUG] Failed backups should be available to the user with a failed status

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1311] opened 2020-05-08 18:32 UTC
**Describe the bug**
Failed backups should be available to the user with a "failed" or in "Error" status

**To Reproduce**
- Create a volume, attach to a workload. write something to the volume
- Take a backup
- While the backup is in progress, reboot the node, in which the replica responsible for backup is running
- The backup fails
- It is not see in "In Progress" anymore
<img width="803" alt="Screen Shot 2020-05-08 at 11 16 11 AM" src="https://user-images.githubusercontent.com/26032343/81436643-aadedc80-911e-11ea-8eb9-a73ed71c59ea.png">

- But the failed backup status for that backup is not available anymore in the volumes API -
```
"backupStatus": [
        {
          "actions": null,
          "backupURL": "",
          "error": "",
          "id": "backup-c81d0fa474284d64",
          "links": null,
          "progress": 3,
          "replica": "vol-2-r-47bd8d7f",
          "snapshot": "f202c984-ed6b-4b94-935a-7663d7d57ff0",
          "state": "in_progress"
        },
        {
          "actions": null,
          "backupURL": "",
          "error": "",
          "id": "backup-e4a396f0495f4c1e",
          "links": null,
          "progress": 15,
          "replica": "vol-2-r-47bd8d7f",
          "snapshot": "b6c68e0e-de47-468b-807c-f9f84f581878",
          "state": "in_progress"
        }
      ],
```

**Expected behavior**
Failed backups should be available in the API/UI. This will be useful for the user, when one of the backups fail.

**Environment:**
 - Longhorn version: master - 05/08/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: RKE DO linux 18.04

**Comment by khushboo-rancher** [comment] 2020-05-09 00:18
Adding one more scenario here.

When backup is created from a replica and it gets rebuilt, volume API doesn't show the backups details in volume page tool tip of snapshot.
Steps:
1. Create a backup. (A snapshot also gets created before taking backup). Let it complete.
2. Delete the replica from where the above backup was created.
3. After replica rebuilt, Hover to snapshot or check the volume API call. It doesn't show the backup details from the failed replica.

**Comment by yasker** [comment] 2020-06-02 02:15
Sounds like the duplicate of https://github.com/longhorn/longhorn/issues/1249 .

**Comment by joshimoo** [comment] 2020-06-30 23:05
To solve this we need a persistentence layer for backup information. We might get that as part of the kubernetes csi snapshoter #304

**Comment by jenting** [comment] 2021-07-19 03:00
Here is the prototype of adding the event log to backup creation (start/failed/succeeded).
![image](https://user-images.githubusercontent.com/49380831/126096514-1fefb937-a5e5-4c15-8f45-50e0c6cfb37b.png)

**Comment by jenting** [comment] 2021-07-19 03:30
The rest is if the Longhorn engine calculates the snapshot file extent retrieval **failed**, now the snapshots and backups list won't adding the icon.

For a better user experience, I expect that when the user clicks the backup creation, the snapshots and backups list would add a new icon, and it indicates the status of the backup (start/progress/failed/succeeded).

**Comment by khushboo-rancher** [comment] 2021-12-10 21:30
Validation - **In Progress**

The failed backups are now available with the error as below.

**Volume detail page** - Hover on the snapshot taking the backup
<img width="1516" alt="Screen Shot 2021-12-10 at 1 12 23 PM" src="https://user-images.githubusercontent.com/60111667/145642146-c23b1db4-8280-4ac1-88a3-139a9e465069.png">

@jenting @smallteeths Once the backup fails, the progress in the snapshot icon stuck and keep showing the same %. Logged a bug of improvement of user experience - https://github.com/longhorn/longhorn/issues/3394

**Backup Page** - Creation state 
<img width="1769" alt="Screen Shot 2021-12-10 at 12 29 54 PM" src="https://user-images.githubusercontent.com/60111667/145642292-3f2679ca-46ab-4e10-ab21-4a9b04d0666d.png">

**Events** - Logs
<img width="1775" alt="Screen Shot 2021-12-10 at 12 27 28 PM" src="https://user-images.githubusercontent.com/60111667/145642410-f42c8d3c-0c2a-4bb3-b24f-28e5dd3ffb43.png">
<img width="1766" alt="Screen Shot 2021-12-10 at 12 28 08 PM" src="https://user-images.githubusercontent.com/60111667/145642413-bf0986be-c000-47b3-9c6c-5dbe0a1a2922.png">

@jenting - The event is appearing with warning level, isn't this be error level?

cc: @innobead

**Comment by jenting** [comment] 2021-12-10 23:15
> The event is appearing with warning level, isn't this be error level?

It's the event type defined in Kubernetes which only supports normal and warning, ref to https://github.com/kubernetes/kubernetes/blob/b11d0fbdd58394a62622787b38e98a620df82750/pkg/apis/core/types.go#L4670-L4676.

> Deleting the errored backup - This is a bit slow and there is no indication of the backup is being deleted on the UI. On deletion of the errored backup from backup page, the volume details page stop showing the error, working as expected.

Ref to #3349

**Closed** 2021-12-11 00:25 UTC
Labels: kind/bug, area/engine, area/ui, area/manager, priority/2, require/automation-e2e, feature/backup-restore, backport-needed/1.2.3
