### ISSUE TITLE
[Question] Automatically restart workloads after volume salvage

### ISSUE THREAD

**Issue by almorgv** [longhorn/longhorn#1709] opened 2020-08-21 14:03 UTC
**Is there a way to automatically restart workloads after volume savlage?**

One way to do this described in docs https://longhorn.io/docs/1.0.2/high-availability/recover-volume/#automatically-remount-volumes-and-restart-workloads

But the problem is then you use public helm charts like postgres you can't modify `livenessProbe`. The only way is to fork all used charts and modify them manually to add custom `livenessProbe`. But this is not maintainable and in this case updates of the chart will be really painfull.

**Comment by almorgv** [comment] 2020-08-24 11:26
It would help a lot. Currently its our own duty to manually detect failed workloads and restart (delete) them. But this could take a while because many workloads become unoperational but keep passing liveness/readiness probes. So we need to manually check worload logs to find a plenty of IO errors.

**Comment by PhanLe1010** [comment] 2020-10-21 06:40
The PR https://github.com/longhorn/longhorn-manager/pull/722 should be able to solve this issue.

**Comment by yasker** [comment] 2020-11-10 18:22
Duplicate of https://github.com/longhorn/longhorn/issues/1719.

**Closed by yasker** 2020-11-10 18:22 UTC
Labels: area/kubernetes, area/manager, enhancement, highlight, priority/2, require/LEP, require/automation-e2e, require/doc
