### ISSUE TITLE
[BUG] Backup error happen to volume with older engine image

### ISSUE THREAD

**Issue by kaxing** [longhorn/longhorn#3621] opened 2022-02-14 10:13 UTC
## Describe the bug

Found this issue while checking on #3620 

## To Reproduce

1. Install v1.1.3
2. Create some volumes
3. Upgrade to master-head(v1.2.3+)
4. Setup backup target(in-cluster nfs)
5. Create backup

## Expected behavior

Should be able to backup without problem or having prompt ask to upgrade engine image (if there is limit)

## Log or Support bundle

```error
failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.1.3/longhorn [--url 10.42.0.8:10000 backup status backup-32c743f226fc4ef2[], output , stderr, time="2022-02-14T09:58:45Z" level=fatal msg="Error querying backup status: failed to get backup status for backup-32c743f226fc4ef2: replica not found"
, error exit status 1
```

## Environment

 - Longhorn version: v1.1.3 to master-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s
   - Number of management node in the cluster: 1+3
   - Number of worker node in the cluster: 3

## Additional context

I am able to delete the error entry from the UI without further problem.

**Comment by kaxing** [comment] 2022-02-14 10:44
It appears the recurring backup job set to 1 minute will have too little time window for backup to be created. cc @jenting 

ref: https://github.com/longhorn/longhorn/issues/3055#issuecomment-926686241

**Comment by innobead** [comment] 2022-02-14 10:51
> It appears the recurring backup job set to 1 minute will have too little time window for backup to be created. cc @jenting
> 
> ref: [#3055 (comment)](https://github.com/longhorn/longhorn/issues/3055#issuecomment-926686241)

So this actually works except during a short period to create a backup?

**Comment by jenting** [comment] 2022-02-21 09:21
> @jenting If I remember right we did some modification to the replica selection process, i.e. pass the replica information. Perhabs our fallback for the replica search does not work correctly? (error message: "replica not found")

I don't recall we had the modification to the replica selection process related to backup :thinking:

**Comment by jenting** [comment] 2022-02-22 08:55
With longhorn-engine < 1.2.0, the backup name is generated in the longhorn-engine
With longhorn-engine >= 1.2.0, the backup name is generated in the longhorn-manager and passed to the longhorn engine.

With longhorn-manager >= 1.2.0 + longhorn-engine < 1.2.0, it'd have the intermediate transition state of the name of the created backup. However, in the end, Longhorn will ensure the backup is synced with the remote backup target and the backup will be updated to the final correct state as the remote backup target is the single source of truth.

But, after longhorn-manager >= 1.2.3, during backup in progress, the backup_controller creates a goroutine to monitor the backup progress/state from the longhorn engine, which means the longhorn-manager uses an incorrect backup name to query the longhorn-engine.

We should check the engine's API version to decide to pass the backup name to the longhorn engine or not.

**Comment by c3y1huang** [comment] 2022-03-03 04:54
Adding a note here, [this PR](https://github.com/longhorn/longhorn-manager/pull/1234) seems to have some side-effects. Ref https://ci.longhorn.io/job/private/job/longhorn-tests-regression/774/testReport/
```
"Error querying backup status: Missing required parameter backupID"
```

**Comment by jenting** [comment] 2022-03-04 05:59
> Adding a note here, [this PR](https://github.com/longhorn/longhorn-manager/pull/1234) have some side-effects caused unstable test results. Ref [test_restore_basic#774](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/774/testReport/tests/test_basic/), [test_restore_basic#775](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/775/testReport/tests/test_basic/)
> 
> ```
> "Error querying backup status: Missing required parameter backupID"
> ```

Since somehow the backup monitor routine disappeared, the in-memory engineBackupName be cleared.
So, after the new backup monitor routine is created, the engineBackupName does not fetch from the engine again but still query the engine's backup status.

There are some possible solutions we have think but not choose:
- Record the `engineBackupName` in the Backup CR: we don't want to record the engineBackupName in the Backup CR as a workaround way, so adding a new filed to Backup CR does not make sense.
- Call the engine's SnapShot API on the backup monitor routine creation: it would cause the engine to randomly search a replica to perform the backup, in the end, there might have more than 1 replica perform the snapshot backup for the same Backup CR.
- Use the remote backup target to correct the CR (**CR replacement**): we'll try this approach now. And since we are close to 1.2.4 RC1 release, we decided to revert the PR https://github.com/longhorn/longhorn-manager/pull/1234 to not block the 1.2.4 RC1 release. cc @innobead

**Comment by innobead** [comment] 2022-03-04 06:23
> * Use the remote backup target to correct the CR (**CR replacement**): we'll try this approach now. And since we are close to 1.2.4 RC1 release, we decided to revert the PR [Add a field to record the longhorn engine generated backup name longhorn-manager#1234](https://github.com/longhorn/longhorn-manager/pull/1234) to not block the 1.2.4 RC1 release. cc @innobead

This option seems the way to go for.

**Comment by innobead** [comment] 2022-03-14 10:17
This needs some time to investigate for the implementation, so move out from 1.2.4.

**Comment by jenting** [comment] 2022-03-19 10:21
We could consider show error/warning message when the user creates the backup in v1.2.x.
For v1.3.x, we could consider using validation admission webhook to deny the user creates the backup.

**Comment by innobead** [comment] 2022-08-22 03:08
1.1.x is not supported and this issue was introduced by 1.2 the behavior change of backup name generation. Closing first until there will be any further feedback from the community.

**Closed by innobead** 2022-08-22 03:08 UTC
Labels: kind/bug, area/engine, area/manager, severity/1, priority/0, kind/regression, feature/backup-restore, backport-needed/1.2.5
