### ISSUE TITLE
[BUG] Longhorn gives 500 error when trying to provision a volume created using a snapshot.

### ISSUE THREAD

**Issue by masteryyh** [longhorn/longhorn#4785] opened 2022-10-27 01:41 UTC
## Describe the bug

In Harvester, use a snapshot to create a volume, and while the volume is in `Pending` state, attach the volume to a VM immediately. Start the VM and the VM would stuck in `Starting` state, SSH into one of the node and execute `kubectl describe pvc <volume-name>` can see some message given by Longhorn:

```
Events:
  Type     Reason                Age                From                                                                                      Message
  ----     ------                ----               ----                                                                                      -------
  Warning  ProvisioningFailed    23s (x4 over 37s)  driver.longhorn.io_csi-provisioner-77b757f445-6gvqc_f518389e-c9b8-4d09-abd4-8e143c33965e  failed to provision volume with StorageClass "longhorn-image-8rtv9": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to create volume: unable to create volume pvc-bf336afd-ad19-484d-bac8-60fbacedbfd6: failed to verify data source: cannot get client for volume pvc-6b2fd344-3843-48e8-9fff-bc4e5a090b3a: engine is not running, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes]
  Normal   ExternalProvisioning  8s (x5 over 37s)   persistentvolume-controller                                                               waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
  Normal   Provisioning          8s (x8 over 37s)   driver.longhorn.io_csi-provisioner-77b757f445-6gvqc_f518389e-c9b8-4d09-abd4-8e143c33965e  External provisioner is provisioning volume for claim "default/restored"
  Warning  ProvisioningFailed    8s (x4 over 37s)   driver.longhorn.io_csi-provisioner-77b757f445-6gvqc_f518389e-c9b8-4d09-abd4-8e143c33965e  failed to provision volume with StorageClass "longhorn-image-8rtv9": rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to create volume: unable to create volume pvc-bf336afd-ad19-484d-bac8-60fbacedbfd6: failed to verify data source: cannot get client for volume pvc-6b2fd344-3843-48e8-9fff-bc4e5a090b3a: engine is not running] from [http://longhorn-backend:9500/v1/volumes]
```

## To Reproduce

Reproduce steps [here](https://github.com/harvester/harvester/pull/2980#issuecomment-1286486710)

## Expected behavior

Volume should be attached to VM after provisioned by longhorn and VM should boot up without problems.

## Log or Support bundle

[longhorn-support-bundle_902bc133-4666-44c4-8e51-093f4093bfdf_2022-10-27T01-38-29Z.zip](https://github.com/longhorn/longhorn/files/9874976/longhorn-support-bundle_902bc133-4666-44c4-8e51-093f4093bfdf_2022-10-27T01-38-29Z.zip)

## Environment

 - Longhorn version: 1.3.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm in Harvester
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 v1.24.7+rke2r1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 
 - Node config
   - OS type and version: Harvester v1.1.0
   - CPU per node: 8
   - Memory per node: 32Gi
   - Disk type(e.g. SSD/NVMe): VirtIO HDD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Virtualized Harvester on Proxmox VE 7.2-3
 - Number of Longhorn volumes in the cluster: 4

**Comment by guangbochen** [comment] 2023-01-05 07:08
@innobead we may need to backport this issue to LH v1.4.x milestone, for Harvester, the planning release date is April/04 with v1.2.0, can u please help to double-check if this is possible, thanks?

**Comment by innobead** [comment] 2023-01-05 07:19
@guangbochen It's planned for 1.5.0, so it will be naturally backported to 1.4.x.

**Comment by innobead** [comment] 2023-01-29 21:45
@PhanLe1010 Please help check this first to see the cause. Thanks.

**Comment by PhanLe1010** [comment] 2023-03-09 20:31
It looks like the source snapshot is on a detached volume: `unable to create volume: unable to create volume pvc-bf336afd-ad19-484d-bac8-60fbacedbfd6: failed to verify data source: cannot get client for volume pvc-6b2fd344-3843-48e8-9fff-bc4e5a090b3a: engine is not running`. Could we verify if we don't have this problem when the source volume is in attached state @masteryyh @weizhe0422 

Btw, provisioning a new volume from a snapshot of a detach volume, this will require the enhancement https://github.com/longhorn/longhorn-manager/pull/1541. This is a big feature so I think it is not possible to backport it to 1.4.x. cc @innobead

**Comment by innobead** [comment] 2023-03-13 06:24
> It looks like the source snapshot is on a detached volume: `unable to create volume: unable to create volume pvc-bf336afd-ad19-484d-bac8-60fbacedbfd6: failed to verify data source: cannot get client for volume pvc-6b2fd344-3843-48e8-9fff-bc4e5a090b3a: engine is not running`. Could we verify if we don't have this problem when the source volume is in attached state @masteryyh @weizhe0422
> 

@mantissahz Could you help check this part first? I assume there should be no issues with the attached volume.

**Comment by innobead** [comment] 2023-03-13 06:28
> Btw, provisioning a new volume from a snapshot of a detach volume, this will require the enhancement [longhorn/longhorn-manager#1541](https://github.com/longhorn/longhorn-manager/pull/1541). This is a big feature so I think it is not possible to backport it to 1.4.x. cc @innobead

YES, for this new behavior, it's only available in 1.5.0. Currently, we only need to check if the existing behavior works as expected, which means creating a volume from a snapshot of a `running` volume should work.

**Comment by mantissahz** [comment] 2023-03-13 07:40
Result: 
There are no issues with the attached volume, PVC could be created from a `VolumeSnapshot` CR of the attached volume normally.
Scale down the deployment to 0 and the volume will be detached, then it failed to create a PVC from a `VolumeSnapshot` CR of the detached volume.

Steps:
1. [Enable CSI Snapshot support](https://longhorn.io/docs/1.3.2/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/)
2. Use [Longhorn deployment example](https://longhorn.io/docs/1.3.2/references/examples/#deployment) to create a PVC, a PV and a deployment.
3. Create `VolumeSnapshotClass` by the manifest 
```text
kind: VolumeSnapshotClass
apiVersion: snapshot.storage.k8s.io/v1
metadata:
  name: longhorn-snapshot-vsc
driver: driver.longhorn.io
deletionPolicy: Delete
parameters:
  type: snap
```
4. Create the `VolumeSnapshot` by the manifest
```text
apiVersion: snapshot.storage.k8s.io/v1
kind: VolumeSnapshot
metadata:
  name: test-csi-volume-snapshot-longhorn-snapshot
spec:
  volumeSnapshotClassName: longhorn-snapshot-vsc
  source:
    persistentVolumeClaimName: mysql-pvc
```
5. Create the PVC by the manifest
```text
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: restore-from-csi-snapshot-pvc
spec:
  storageClassName: longhorn
  dataSource:
    name: test-csi-volume-snapshot-longhorn-snapshot
    kind: VolumeSnapshot
    apiGroup: snapshot.storage.k8s.io
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
```

**Comment by innobead** [comment] 2023-03-13 07:44
Thanks @mantissahz .

@masteryyh If this is the same case with you only being able to create a volume from a running snapshot, then it's the current behavior. 

About creating a volume from an inactive snapshot from a detached volume, it will be improved in 1.5.0.

cc @guangbochen

**Comment by masteryyh** [comment] 2023-04-19 08:20
I'm trying to bump Longhorn version in Harvester to v1.4.1 and repeat the reproduce steps [here](https://github.com/harvester/harvester/pull/2980#issuecomment-1286486710), the VM will stuck in `Starting` phase and in `status` of VM this appears:
```
volumeSnapshotStatuses:
    - enabled: false
      name: disk-1
      reason: 2 matching VolumeSnapshotClasses for longhorn-image-4m88v
    - enabled: false
      name: cloudinitdisk
      reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]
```

**Comment by hunghvu** [comment] 2023-07-19 06:24
In regard to this bug, does this mean Harvester snapshot restore is unusable as of v1.1.2? In my case, snapshot restoration simply does not work.

![image](https://github.com/longhorn/longhorn/assets/62678592/58fa3a9d-36ce-43e2-9093-1d8a1663d528)
![image](https://github.com/longhorn/longhorn/assets/62678592/53515c1c-c7ee-4d25-957d-d1d9215f1d4b)

**Comment by innobead** [comment] 2023-07-19 08:58
@hunghvu your case looks different because the error is due to `more than one engine exists`, so that just means the source volume could be a migrating volume. Suggest you can create an issue at the harvester github repo instead to clarify the cause there.

**Comment by masteryyh** [comment] 2023-07-20 09:05
If I understand this correctly, the snapshot is on the attached volume 🤔 when I'm testing this before this volume is attached already

**Comment by FrankYang0529** [comment] 2023-11-27 11:49
I can't reproduce the issue in Harvester v1.2.1 with LH v1.4.3 with following steps:

1. Create a VM.
2. Create a snapshot for the volume in the VM.
3. After snapshot is finished. Stop the VM. The volume is detached automatically.
4. Create another PVC from the snapshot and update the VM to the new PVC. (We cannot use a pending PVC in GUI, so I update VM Yaml directly.)
5. Before the new PVC is bound, starting the VM.
6. VM can get up without error.

**Comment by PhanLe1010** [comment] 2023-11-28 01:55
@FrankYang0529 

> Create another PVC from the snapshot and update the VM to the new PVC. (We cannot use a pending PVC in GUI, so I update VM Yaml directly.)

How did you update the VM? Did you keep both old PVC and new PVC?

**Comment by FrankYang0529** [comment] 2023-11-28 01:58
> > Create another PVC from the snapshot and update the VM to the new PVC. (We cannot use a pending PVC in GUI, so I update VM Yaml directly.)
> 
> How did you update the VM? Did you keep both old PVC and new PVC?

Yes, I use `kubectl edit` to update VM and keep both PVC.

**Comment by ChanYiLin** [comment] 2023-11-30 09:53
cc @innobead 
I think we can close the issue for now since @FrankYang0529 has tested and it works as expected now.

**Closed** 2023-11-30 10:32 UTC
Labels: kind/bug, priority/0, area/volume-backup-restore, area/snapshot, area/volume-attach-detach

**Comment by innobead** [comment] 2023-11-30 11:11
@ChanYiLin Let's added wontfix label as well.
