### ISSUE TITLE
[IMPROVEMENT] Prevent Volume Resize Stuck

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#6633] opened 2023-09-05 02:42 UTC
## Is your improvement request related to a feature? Please describe (👍 if you like this request)
As in tickets [#3156](https://github.com/harvester/harvester/issues/3156) and [#4371](https://github.com/harvester/harvester/issues/4371)

If the user specifies a size greater than Longhorn's capacity during volume expansion, the volume would be stuck in resizing. In Harvester's use cases, the related VM couldn't start and operate anymore.

## Describe the solution you'd like

Since there is a clear rule about [whether a replica could be scheduled to a specific disk](https://longhorn.io/docs/1.4.3/volumes-and-nodes/multidisk/#configuration), is it possible to have a capacity check ahead of volume resizing?

## To Reproduce

1. Creating a two nodes Harvester cluster from scratch
2. Updating an image to Harvester
3. Creating a VM from the uploaded image
4. Starting VM and stoping VM
5. Expand VM's volume to 500GB
6. Volume stuck in resizing and the VM can't start to operate

## Longhorn Nodes Information
Node 0:
```
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  creationTimestamp: "2023-08-25T08:17:33Z"
  finalizers:
  - longhorn.io
  - wrangler.cattle.io/harvester-ndm-node-handler
  generation: 1
  name: harvester-node-0
  namespace: longhorn-system
  resourceVersion: "3396769"
  uid: 0f62c7d8-27bf-4d13-bf54-fdfa3acd46dd
spec:
  allowScheduling: true
  disks:
    default-disk-66ed507656c8330b:
      allowScheduling: true
      evictionRequested: false
      path: /var/lib/harvester/defaultdisk
      storageReserved: 122324933836
      tags: []
  engineManagerCPURequest: 0
  evictionRequested: false
  name: harvester-node-0
  replicaManagerCPURequest: 0
  tags: []
status:
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2023-09-05T01:02:20Z"
    message: Node harvester-node-0 is ready
    reason: ""
    status: "True"
    type: Ready
  - lastProbeTime: ""
    lastTransitionTime: "2023-08-25T09:26:01Z"
    message: ""
    reason: ""
    status: "True"
    type: Schedulable
  - lastProbeTime: ""
    lastTransitionTime: "2023-08-25T08:17:33Z"
    message: ""
    reason: ""
    status: "True"
    type: MountPropagation
  diskStatus:
    default-disk-66ed507656c8330b:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2023-08-25T08:17:33Z"
        message: Disk default-disk-66ed507656c8330b(/var/lib/harvester/defaultdisk)
          on node harvester-node-0 is ready
        reason: ""
        status: "True"
        type: Ready
      - lastProbeTime: ""
        lastTransitionTime: "2023-08-25T08:17:33Z"
        message: Disk default-disk-66ed507656c8330b(/var/lib/harvester/defaultdisk)
          on node harvester-node-0 is schedulable
        reason: ""
        status: "True"
        type: Schedulable
      diskUUID: c3b149e7-b2f8-42b4-8829-a65fbd7aa35c
      scheduledReplica:
        pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814-r-4e1bd5cf: 21474836480
        pvc-692dc805-e42c-46d1-b993-2025add4b418-r-0ddbc348: 53687091200
        pvc-b4d5a7e2-460d-4a8c-bf77-3614449e4977-r-11c27c71: 5368709120
        pvc-cd80c4f1-129e-44f8-88f7-24d5bcaf8262-r-fa916047: 2147483648
      storageAvailable: 397934592000
      storageMaximum: 407749779456
      storageScheduled: 82678120448
  region: ""
  snapshotCheckStatus: {}
  zone: ""
```
Node 1:
```
apiVersion: longhorn.io/v1beta2
kind: Node
metadata:
  creationTimestamp: "2023-08-25T08:28:28Z"
  finalizers:
  - longhorn.io
  - wrangler.cattle.io/harvester-ndm-node-handler
  generation: 1
  name: harvester-node-1
  namespace: longhorn-system
  resourceVersion: "3396926"
  uid: 134d1d4c-3c2a-41a2-8c98-89323f01d75e
spec:
  allowScheduling: true
  disks:
    default-disk-32eca568fb4b242e:
      allowScheduling: true
      evictionRequested: false
      path: /var/lib/harvester/defaultdisk
      storageReserved: 122324933836
      tags: []
  engineManagerCPURequest: 0
  evictionRequested: false
  name: harvester-node-1
  replicaManagerCPURequest: 0
  tags: []
status:
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2023-09-01T03:14:12Z"
    message: Node harvester-node-1 is ready
    reason: ""
    status: "True"
    type: Ready
  - lastProbeTime: ""
    lastTransitionTime: "2023-08-25T09:36:40Z"
    message: ""
    reason: ""
    status: "True"
    type: Schedulable
  - lastProbeTime: ""
    lastTransitionTime: "2023-08-25T08:28:28Z"
    message: ""
    reason: ""
    status: "True"
    type: MountPropagation
  diskStatus:
    default-disk-32eca568fb4b242e:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2023-08-25T08:28:28Z"
        message: Disk default-disk-32eca568fb4b242e(/var/lib/harvester/defaultdisk)
          on node harvester-node-1 is ready
        reason: ""
        status: "True"
        type: Ready
      - lastProbeTime: ""
        lastTransitionTime: "2023-08-25T08:28:28Z"
        message: Disk default-disk-32eca568fb4b242e(/var/lib/harvester/defaultdisk)
          on node harvester-node-1 is schedulable
        reason: ""
        status: "True"
        type: Schedulable
      diskUUID: 9d9c9d8a-c699-4daa-94db-febaf7ebe0fe
      scheduledReplica:
        pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814-r-71d1f9f9: 21474836480
        pvc-692dc805-e42c-46d1-b993-2025add4b418-r-fb4c3b0d: 53687091200
        pvc-b4d5a7e2-460d-4a8c-bf77-3614449e4977-r-ce3d1106: 5368709120
        pvc-cd80c4f1-129e-44f8-88f7-24d5bcaf8262-r-2c0d4078: 2147483648
      storageAvailable: 393425715200
      storageMaximum: 407749779456
      storageScheduled: 82678120448
  region: ""
  snapshotCheckStatus: {}
  zone: ""
```
## Resizing Fail Log
```
....
resize volume "pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814" by resizer "driver.longhorn.io" failed: rpc error: code = OutOfRange desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to expand volume pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814: error while CheckReplicasSizeExpansion for volume pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814: cannot schedule 515396075520 more bytes to disk 9d9c9d8a-c699-4daa-94db-febaf7ebe0fe with &{StorageAvailable:393425715200 StorageMaximum:407749779456 StorageReserved:122324933836 StorageScheduled:82678120448 OverProvisioningPercentage:100 MinimalAvailablePercentage:25}, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814?action=expand]
.....
.....
resize volume "pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814" by resizer "driver.longhorn.io" failed: rpc error: code = OutOfRange desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [code=Server Error, detail=, message=unable to expand volume pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814: error while CheckReplicasSizeExpansion for volume pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814: cannot schedule 515396075520 more bytes to disk c3b149e7-b2f8-42b4-8829-a65fbd7aa35c with &{StorageAvailable:397934592000 StorageMaximum:407749779456 StorageReserved:122324933836 StorageScheduled:82678120448 OverProvisioningPercentage:100 MinimalAvailablePercentage:25}] from [http://longhorn-backend:9500/v1/volumes/pvc-094f5ac7-204e-45f2-a144-5d2b32dc8814?action=expand]
```

## Environment

 - Longhorn version: v1.4.3
 - Harvester version: v1.2.0-head

**Comment by innobead** [comment] 2023-09-05 03:08
This is expected. Because the size is unable to support at runtime, it is stuck. We could do some validation to prevent the size before runtime, but it will be just best efforts. 

@WebberHuang1118 Are u able to restart the volume with the allocable size? If not, it will be an issue instead.

**Comment by WebberHuang1118** [comment] 2023-09-05 03:12
Hi @innobead,

I can restart the volume if I change `StorageOverProvisioningPercentage` to a greater value. But I'm not sure about the `allocable size` you mentioned. Could you describe more about it? Many thanks.

**Comment by innobead** [comment] 2023-09-05 03:15
@WebberHuang1118 it's the original volume size before expansion.

**Comment by WebberHuang1118** [comment] 2023-09-05 03:36
Hi @innobead,
Harvester expands volume by changing PVC's `spec.resources.requests.storage`, during the resizing is stuck, the storage size is forbidden to be less than the previous value.

It seems the PVC size can't rollback, or do I miss anything? Thanks.

**Comment by innobead** [comment] 2023-09-05 03:57
I see, so even though the expansion is failed, users are now allowed to rollback to the previous size. 

Is disallowing rollback prevented by Longhorn validation?

@mantissahz worked on the related validation. any ideas?

**Comment by derekbit** [comment] 2023-09-05 04:08
> Is disallowing rollback prevented by Longhorn validation?

Just checked with @WebberHuang1118, upstream's PVC validation rejects the size rollback (to a smaller size).

**Comment by innobead** [comment] 2023-09-05 04:25
Then it's clear now. 

- Users need to ensure if there's enough space for expansion. (Bad UX, but a way for now)
- Have a best effort validation before mutating the size change. (feasibility first)
- Improve at Upstream to allow rollback if the expansion not really executed successfully. (Uncertain feasibility)

This seems not a priority but can see how to improve later. @WebberHuang1118 has provided the workaround, 👍.

Any other ideas?

**Comment by derekbit** [comment] 2024-12-04 04:51
@c3y1huang Can you help the ticket?

**Comment by c3y1huang** [comment] 2024-12-05 04:44
The oversize prevention seems to have already been addressed in https://github.com/longhorn/longhorn-manager/commit/946465b1fb7098cd9bbe042603ca2f8fc2328988.

cc @derekbit @mantissahz

**Comment by c3y1huang** [comment] 2024-12-05 04:53
After discussing with @derekbit , for this issue, we agreed to add a test case for this issue to ensure the behavior is validated in regression.

**Comment by c3y1huang** [comment] 2024-12-05 05:03
> The oversize prevention seems to have already been addressed in https://github.com/longhorn/longhorn-manager/commit/946465b1fb7098cd9bbe042603ca2f8fc2328988.

Sorry, my mistake, it hasn't. Overlooked. cc @derekbit

**Comment by roger-ryao** [comment] 2024-12-09 10:31
**Verified on master-head 20241209**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/6cc47ec5e942f33b10f644a5eaf0970b650e27a7
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-instance-manager/commit/e2b56a23d52e91317cc7c6fc98a17760d3fce4b6

**The test steps**
https://github.com/longhorn/longhorn/issues/6633#issuecomment-2521933374

**Result Passed**

Successfully executed the test case from [PR #2178](https://github.com/longhorn/longhorn-tests/pull/2178).

**Closed by roger-ryao** 2024-12-09 10:31 UTC
Labels: priority/0, require/auto-e2e-test, require/doc, area/upstream, kind/improvement, area/admission-webhook, area/volume-expansion, backport/1.6.4, backport/1.7.3
