### ISSUE TITLE
[BUG] Engine image and instance manager state is not correct on the node page of Longhorn UI

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2377] opened 2021-03-18 18:59 UTC
**Describe the bug**
The components details for a node don't show correct value if the engine image, instance-manger etc are not running on the node.
<img width="1509" alt="Screen Shot 2021-03-18 at 12 41 21 PM" src="https://user-images.githubusercontent.com/60111667/111682663-a610ac00-884a-11eb-8729-4fe8293a5694.png">

**To Reproduce**
Case 1:
1. Deploy Longhorn on a K8s cluster.
2. Add taint to a node, the state of the node should become `Down` on the Longhorn UI node page.
3. Go to the node page of the Longhorn UI and click in the state column shown as `notReady`.
4. The engine image shows `Deployed` and instance-manager shows `running` state.

Case 2: https://github.com/longhorn/longhorn/issues/2081#issuecomment-801842133

**Expected behavior**
The engine-image and instance-manager should show `error` state.

**Environment:**
 - Longhorn version: Longhorn-master `03/19/2021`

**Comment by khushboo-rancher** [comment] 2021-03-18 19:01
After discussing with @PhanLe1010, below points should be taken in consideration.
1. The UI should not should deployed when engine image NodeDeploymentMap[currentNode] == false. This can be fixed from UI side.
2. The issue with replica CR still in running state and this issue have the same root cause: when Longhorn manager pod stops running on a node but the Kubernetes node object is still ready, Longhorn doesn't consider the node as down https://github.com/longhorn/longhorn-manager/blob/0b4f6ef17c3f02f1c8f52576066abc4926ca56d2/datastore/longhorn.go#L1423. Therefore, Longhorn doesn't switch ownerID for the resource to a new node and the CRs are not updated. We need to reconsider this node down handling logic.

**Comment by PhanLe1010** [comment] 2021-03-20 23:18
In this issue, we should also fix this issue from @joshimoo  suggestion:

for each enqueue remove these type of checks, since they prohibit ownership transfer: https://github.com/longhorn/longhorn-manager/blob/b0b3579609ac768d76271f68f662ce2243b6cb99/controller/engine_image_controller.go#L656
The controller should at least look at each resource to determine whether it's responsible for it or not, it's no the enqueues responsibility to make that determination. This is a form of optimization we can add later if necessary, but for now remove these checks from the enques the same applies for other controllers.

**Comment by PhanLe1010** [comment] 2021-03-30 23:34
Manual test:
**Case 1:**
Test case 1 in the reproduce steps in the issue description 

**Case 2:**
Test case 2 in the reproduce steps in the issue description 

**Case 3:**
1. Set up a 3 node cluster and install Longhorn
1. Create a Deployment/StatefulSet of 1 pod using a volume of 3 replicas.
1. Taint the node that is not where the volume is attaching to with the taint `k=v:NoExecute`
1. Scale down the Deployment/StatefulSet, verify that volume is detached successfully 
1. Scale up the Deployment/StatefulSet, verify that volume is attached successfully 
1. Verify the `.Status.OwnerID` of engine, replica, volume CRs are all move to a different node
1. Remove the taint, verify that the failed replica get reuse 
Note: If we taint the node  where the volume is attaching to with the taint `k=v:NoExecute`, we will not be be to detach/attach the volume. This problem should be fixed in  the issue https://github.com/longhorn/longhorn/issues/2329

**Case 4: Test sharemanager change ownerID **
1. Create a Deployment/StatefulSet

**Comment by PhanLe1010** [comment] 2021-03-30 23:54
@smallteeths 
Besides the backend, This issue contains a UI bug. Can you help to fix?
* Each engine image object has the map `NodeDeploymentMap` that shows which node has this engine image like:
   ```
   NodeDeploymentMap:
   - phan-cluster-v46-worker1: True
   - phan-cluster-v46-worker2: True
   - phan-cluster-v46-worker3: True
   ```
* When user click on this popup modal:
   <img width="1509" alt="111682663-a610ac00-884a-11eb-8729-4fe8293a5694" src="https://user-images.githubusercontent.com/22139961/113070737-25ba4700-9178-11eb-95d1-c0b7943281d8.png">
   UI can use the engine image's NodeDeploymentMap map to check whether the clicked node has engine image. If the value is `false` or not exist, UI should show `not deployed`, otherwise shows `deployed`

**Comment by meldafrawi** [comment] 2021-04-06 21:56
Validation: **PASSED**

**Closed** 2021-04-06 21:56 UTC
Labels: area/manager, area/ui, kind/bug, priority/2
