### ISSUE TITLE
[BUG] backup creation time take longer time using master images causing some tests to fail exceeding backup timeout limits

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1721] opened 2020-08-25 21:37 UTC
**Describe the bug**
The following tests fail due to backup timeout
test_ha.py/test_engine_crash_for_restore_volume
test_ha.py/test_inc_restoration_with_multiple_rebuild_and_expansion
test_ha.py/test_engine_crash_for_restore_volume

**To Reproduce**
1, Install Longhorn using master images, and run the test

**Expected behavior**
tests should pass

**Log**
```
client = <longhorn.Client object at 0x7f57fdd29410>
volume_name = 'longhorn-testvol-pqatjd-std'
snapshot_name = 'cec97733-6420-4155-95b6-ccfd5c76a0d2'

    def wait_for_backup_completion(client, volume_name, snapshot_name):
        completed = False
        for i in range(RETRY_BACKUP_COUNTS):
            v = client.by_id_volume(volume_name)
            for b in v.backupStatus:
                if b.snapshot == snapshot_name and b.state == "complete":
                    assert b.progress == 100
                    assert b.error == ""
                    completed = True
                    break
            if completed:
                break
            time.sleep(RETRY_BACKUP_INTERVAL)
>       assert completed is True
E       AssertionError

common.py:2136: AssertionError
```
**Environment:**
 - Longhorn version: master
 - Kubernetes version: 1.18
 - Node OS type and version: Ubuntu 18.04

**Additional context**
Increasing backup timeout limit and comparing backup time between Longhorn v1.0.2 vs Longhorn `master` using `test_rebuild_with_restoration`
Results:  Backup of 500MB data completed in:
- v1.0.2:  275 seconds
- master: 290.5 seconds

**Comment by shuo-wu** [comment] 2020-08-27 12:41
I tried to test the backup creation speed in both `v1.0.2` and `master` by running the following test case multiple times:
```
def test_backup_speed(
        client, core_api, volume_name, csi_pv, pvc, pod_make):  # NOQA
    auto_salvage_setting = client.by_id_setting(SETTING_AUTO_SALVAGE)
    assert auto_salvage_setting.name == SETTING_AUTO_SALVAGE
    assert auto_salvage_setting.value == "true"

    set_random_backupstore(client)
    backupstore_cleanup(client)

    data_path = "/data/test"
    prepare_pod_with_data_in_mb(client, core_api, csi_pv, pvc,
                                pod_make,
                                volume_name,
                                data_size_in_mb=DATA_SIZE_IN_MB_4,
                                data_path=data_path)
    snap = create_snapshot(client, volume_name)
    volume = client.by_id_volume(volume_name)

    start_time = time.time()
    volume.snapshotBackup(name=snap.name)
    wait_for_backup_completion(client, volume_name, snap.name)
    find_backup(client, volume_name, snap.name)
    print("backup creation time:", time.time() - start_time)
```

The result is that:
    - `master`: around 445s
    - `v1.0.2`: 445s~465s

It seems that there is no regression issue about backup creation.

---
Most of the failed test cases are newly introduced tests. And as for the failed old test case `test_rebuild_with_restoration`, there is an extra rebuild in the `master` version. I am not sure which version you are using for the test.

@meldafrawi Can you check if the above test is fine for the backup creation speed test?

**Comment by khushboo-rancher** [comment] 2020-08-31 21:41
With longhorn Master - 08/31/2020, some more tests start failing and the reason looks as the delay in backup creation.
1. tests.test_basic.test_backup_status_for_unavailable_replicas
2. tests.test_basic.test_backup
3. tests.test_basic.test_backup_labels
4. tests.test_basic.test_restore_inc
5. tests.test_basic.test_deleting_backup_volume
6. tests.test_basic.test_listing_backup_volume
7. tests.test_ha.test_ha_backup_deletion_recovery
8. tests.test_ha.test_rebuild_with_restoration
9. tests.test_ha.test_single_replica_restore_failure
10. tests.test_ha.test_engine_crash_for_dr_volume
11. tests.test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
12. tests.test_ha.test_engine_crash_for_restore_volume

I tried with the test ```test_backup_labels``` with ```nfs-backupstore``` multiple times. The time taken in creating the backup is as follows
1. with v1.0.2 - 1 sec
2. with Master - ~31 sec

With v1.0.2
```
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:10:18
-----------------------------------
backup found =  21:10:19
.

============================================================================================================= 1 passed, 136 deselected in 23.24s =============================================================================================================
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:14:40
-----------------------------------
backup found =  21:14:41
.

============================================================================================================= 1 passed, 136 deselected in 25.22s =============================================================================================================
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:22:41
-----------------------------------
backup found =  21:22:42
.

============================================================================================================= 1 passed, 136 deselected in 23.50s =============================================================================================================
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:27:48
-----------------------------------
backup found =  21:27:49
```

With Master
```
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:26:10
------------------------------
backup complete =  21:26:42
.

============================================================================================================= 1 passed, 136 deselected in 51.62s =============================================================================================================
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:27:14
------------------------------
backup complete =  21:27:46
.

============================================================================================================= 1 passed, 136 deselected in 54.15s =============================================================================================================
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:28:54
------------------------------
backup complete =  21:29:26
.

============================================================================================================= 1 passed, 136 deselected in 51.60s =============================================================================================================
root@longhorn-test:/integration/tests# pytest -s -k test_backup_labels
==================================================================================================================== test session starts =====================================================================================================================
platform linux -- Python 3.7.4, pytest-5.3.1, py-1.9.0, pluggy-0.13.1
rootdir: /integration, inifile: pytest.ini
collected 137 items / 136 deselected / 1 selected                                                                                                                                                                                                            

test_basic.py Current Time = 21:31:50
------------------------------
backup complete =  21:32:22
```

**Comment by yasker** [comment] 2020-08-31 23:40
Those are likely caused by the recent merge of backupstore change, since the engine build time has increased from ~28 minutes to ~43 minutes. Since we've introduced a timed based locking mechanism, this might be the side effect of that.

@joshimoo can you check if this is expected?

**Comment by joshimoo** [comment] 2020-09-01 08:45
Will check, the locking should only have increased the delay of each backup operation by 2 seconds.
It's interesting that the above shows 32 seconds which is the 2 seconds + 30 seconds maximum wait time.

**Comment by khushboo-rancher** [comment] 2020-09-04 00:20
After revert, the performance of the test ```test_backup_labels``` looks good. The backup creation took ~1 sec for 512 data.
Waiting for integration test results.

**Comment by khushboo-rancher** [comment] 2020-09-05 00:18
Below tests passed in nightly integration tests.
1. tests.test_basic.test_backup_status_for_unavailable_replicas
2. tests.test_basic.test_backup
3. tests.test_basic.test_backup_labels
4. tests.test_basic.test_restore_inc
5. tests.test_basic.test_deleting_backup_volume
6. tests.test_basic.test_listing_backup_volume
7. tests.test_ha.test_ha_backup_deletion_recovery
8. tests.test_ha.test_rebuild_with_restoration
9. tests.test_ha.test_single_replica_restore_failure
10. tests.test_ha.test_engine_crash_for_dr_volume
11. tests.test_ha.test_inc_restoration_with_multiple_rebuild_and_expansion
12. tests.test_ha.test_engine_crash_for_restore_volume

The tests ```test_inc_restoration_with_multiple_rebuild_and_expansion and test_engine_crash_for_restore_volume``` fail because it tries to write 800 MI and fail to complete withing 5 mins (Timeout). I checked them with AWS cluster and Do cluster with v1.0.2 and master.
I'll create a PR to fix it.

**Comment by khushboo-rancher** [comment] 2020-09-22 20:58
The tests ```test_inc_restoration_with_multiple_rebuild_and_expansion``` and ```test_engine_crash_for_restore_volume``` are no longer failing to create backups because of timeout.
Closing the issue.

**Closed by khushboo-rancher** 2020-09-22 20:58 UTC
Labels: bug, regression
