### ISSUE TITLE
[BUG] nfs-ganesha-56[svc_89253] nfs4_Errno_verbose :NFS4 :CRIT :Error I/0 error with error code 5 in nfs4_op_commit converted to NFS4ERR_IO but was set non-retryable

### ISSUE THREAD

**Issue by helletheone** [longhorn/longhorn#8251] opened 2024-03-25 18:49 UTC
## Describe the bug

We had the problem that we could no longer mount a PVC. 

## To Reproduce

unfortunately we could not recreate it 

## Expected behavior

we have restarted everything possible (pods, replicas deleted in Longhorn, check if nfs-common is installed) 

im log was this message: 

`share-manager-pvc-fa38e319-7613-4a12-97e6-9e2e0dcee7dc
15/03/2024 00:29:43
65da6de7 : share-manager-pvc-fa38e319-7613-4a12-97e6-9e2e0dcee7dc
15/03/2024 00:29:43
65da6de7 : share-manager-pvc-fa38e319-7613-4a12-97e6-9e2e0dcee7dc
20/03/2024 09:06:10
poch 65da6de7 : share-manager-pvc-fa38e319-7613-4a12-97e6-9e2e0dcee7dc
: nfs-ganesha-56[svc_89253] nfs4_Errno_verbose :NFS4 :CRIT :Error I/0 error with error code 5 in nfs4_op_commit converted to NFS4ERR_IO but was set non-retryable nfs-ganesha-56[svc_89257] nfs4_Errno_verbose :NFS4 :CRIT :Error I/0 error with error code 5 in nfs4_write_cb converted to NFS4ERR_IO but was set non-retryable nfs-ganesha-56[svc_89259] nfs4_Errno_verbose :NFS4 :CRIT :Error I/0 error with error code 5 in nfs4_write_cb converted to NFS4ERR_IO but was set non-retryable
nfs-ganesha-56[svc115421] longhorn_rm_clid :CLIENT ID :EVENT :Remove client '27%3ALinux%20NFSv4.1%20node-rke2node6' from recovery backend share-manager-pvc-fa38e319-7613-4a12-`

## Environment

 - Longhorn version:  v1.4.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2 
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: 
   - Kernel version:
   - CPU per node: 4
   - Memory per node: 16gb
   - Disk type (e.g. SSD/NVMe/HDD): SSD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VM 
 - Number of Longhorn volumes in the cluster: 8

**Comment by james-munson** [comment] 2024-03-25 19:00
Please pull a support bundle and add it to the issue.

**Comment by helletheone** [comment] 2024-03-25 21:47
Does that still make sense? the error was last week? and now after restarting the the share manager the error is fixed. I would only be interested in the cause?

**Comment by derekbit** [comment] 2024-03-26 01:05
What's your longhorn version?

**Comment by derekbit** [comment] 2024-11-03 16:48
@helletheone Does the issue remain in newer versions?

**Comment by helletheone** [comment] 2024-11-07 10:44
@derekbit till now no, everything is fine

**Comment by derekbit** [comment] 2024-11-07 12:37
> @derekbit till now no, everything is fine

Thanks for the update. So, it seems caused by the NFS-ganesha internal bug.
Let's close the issue. Feel free to open a new issue ticket if encounter it again. Thank you.

**Comment by derekbit** [comment] 2024-11-07 12:38
> @derekbit till now no, everything is fine

Thanks for the update. So, it seems caused by the NFS-ganesha internal bug.
Let's close the issue. Thanks.

**Closed by derekbit** 2024-11-07 12:38 UTC
Labels: kind/bug, area/volume-rwx, area/upstream, require/qa-review-coverage, area/external-dependency, require/backport
