### ISSUE TITLE
[BUG] Facing data loss in longhorn volume

### ISSUE THREAD

**Issue by mynktl** [longhorn/longhorn#5574] opened 2023-03-16 09:07 UTC
## Describe the bug (🐛 if you encounter this issue)
I am using longhorn 1.3.1. I have created one volume with two longhorn replicas and uploaded data in volume. After sometime, data disappear from the volumes.

## Expected behavior
Data should not be lost.

## Log or Support bundle
In instance manager, I am seeing volume-head-xxx missing error.
```
instance-manager-r-cf5b560f/replica-manager.log:19037:2023-03-16T05:46:11.836582701Z time="2023-03-16T05:46:11Z" level=warning msg="Failed to open server: 10.42.3.117:10005, Retrying..."
instance-manager-r-cf5b560f/replica-manager.log:19060:2023-03-16T05:48:56.277460168Z [pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-r-44b09aef] time="2023-03-16T05:48:56Z" level=error msg="Fail to get size of file /host/datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-db63bf7c/volume-head-002.img: no such file or directory"
instance-manager-r-cf5b560f/replica-manager.log:19061:2023-03-16T05:48:56.277518561Z time="2023-03-16T05:48:56Z" level=error msg="Fail to get file /host/datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-db63bf7c/volume-head-002.img size"
instance-manager-r-cf5b560f/replica-manager.log:19062:2023-03-16T05:48:56.277526947Z time="2023-03-16T05:48:56Z" level=error msg="Fail to get size of file /host/datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-db63bf7c/volume-snap-uipath-s-13f4817e-7e50-49e6-b0ca-3f505e50d890.img: no such file or directory"
instance-manager-r-cf5b560f/replica-manager.log:19063:2023-03-16T05:48:56.285144257Z [pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-r-44b09aef] time="2023-03-16T05:48:56Z" level=error msg="Fail to get size of file /host/datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-db63bf7c/volume-snap-046e9650-f84c-4f9c-9d2e-77ac9471b9b0.img: no such file or directory"
instance-manager-r-cf5b560f/replica-manager.log:19064:2023-03-16T05:48:56.285163525Z time="2023-03-16T05:48:56Z" level=error msg="Fail to head file /host/datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-db63bf7c/volume-head-002.img stat, err no such file or directory"
```

## Environment

 - Longhorn version: 1.3.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 1.22
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: RHEL 8.7
   - CPU per node: 15
   - Memory per node: 64G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 1

**Comment by derekbit** [comment] 2023-03-16 09:37
Did the cluster experience unstable network status or power outage during a replica rebuilding?
Can you provide the support bundle for further investigation?

```
data disappear from the volumes.
```
Can you find the missing data in the `lost+found` directory inside the volume mount directory?

**Comment by mynktl** [comment] 2023-03-16 10:36
[longhorn-support-bundle.tar.zip](https://github.com/longhorn/longhorn/files/10989608/longhorn-support-bundle.tar.zip)
Hi
I have attached the bundle. 

> Can you find the missing data in the lost+found directory inside the volume mount directory?

I checked, but data was not there in that directory.

**Comment by derekbit** [comment] 2023-03-16 10:48
The volume only has one single replica volume. 
The log said the disk file `/host/datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-31a880d7/volume-head-002.img` is missing.

Can you check if the directory  /datadisk/replicas/pvc-bb5493c3-85ba-44e8-b3b9-a30531e29e32-31a880d7 exists on your worker node? If YES, please help list the files inside the directory as well as past the content of the *.meta.
Thank you.

**Comment by rajivml** [comment] 2023-03-16 10:49
HI @derekbit, thanks for starting looking into it, I have 3 users reporting the exact same issue today with longhorn 1.3.1 and we have never seen this issue with longhorn 1.2.x 

Host OS is RHEL and the disks that we present to longhorn are of xfs type and we don't specify fstype in the storage class so the volumes that longhorn provisions are by default in ext4 file format 

we deploy private docker registry and docker registry uses longhorn storage class with 2 replicas and we ensure both replicas are landed on two different nodes and somehow data from both replicas is getting deleted after sometime 

Am attaching logs shared by one of the users where they don't have any machine restart for the last 37 days and it's a fresh install with no applications running on top of a 5-node cluster  

This folder ASLogs-2.22 has a sub folder called longhorn-system which has one week worth of longhorn logs in debug mode and in this one week data got wiped out twice from docker-registry pvc's and the latest happened on March 7th but I don't have the exact timestamp when it happened 

And this is the pvc_id pvc-78b0b8a5-29e2-47f2-ad52-aa9b827afa85 in question 

https://uipath-my.sharepoint.com/:f:/p/rajiv_chodisetti/Eq_PXCqJXBpLlfZENAFAanUBP_XSiV6kfbCFulOl2GA7Xw?e=rb5A9o

**Comment by derekbit** [comment] 2023-03-16 11:08
@mynktl 
Can you provide the information I mentioned? Thank you.

**Comment by derekbit** [comment] 2023-03-16 11:40
@mynktl

Can you provide the information I mentioned as well?

Some questions for clarification first

1. Do you mean some files are missing if the volume is detached and then attached to workload? If yes, any rebuilding happened before the detachment?

2. What's the purpose of `I scaled it down to 1 replica to rebuild the data from snapshot`? Is the volume with two replicas unable to be attached?

**Comment by mynktl** [comment] 2023-03-16 12:35
Hi,

> Do you mean some files are sometimes missing if the volume is detached and then attached to workload? If yes, any rebuilding happened before the detachment?

It was fresh installation. I haven't perform any detachment for volume.

> What's the purpose of I scaled it down to 1 replica to rebuild the data from snapshot? Is the volume with two replicas unable to be attached?
No, Volume was in attached condition.

I recreated the PV. For new PV, details are as below.
```
kubectl get pods -n docker-registry -o wide
NAME                               READY   STATUS    RESTARTS   AGE    IP            NODE            NOMINATED NODE   READINESS GATES
docker-registry-569cdb7477-k5489   1/1     Running   0          175m   10.42.21.66   iaase00027578   <none>           <none>

kubectl get pvc -n docker-registry
NAME              STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS      AGE
docker-registry   Bound    pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719   200Gi      RWO            longhorn-backup   3h44m

kubectl get replicas -n longhorn-system |grep pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719
pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-r-8612851f   running   iaase00027571   67446771-11ab-4476-a402-d2a1a6c384da   instance-manager-r-cf5b560f   longhornio/longhorn-engine:v1.3.1   3h43m
pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-r-e592b477   running   iaase00027570   57b855e4-b6a8-4d24-8580-9e36c671baaf   instance-manager-r-2f6a7c00   longhornio/longhorn-engine:v1.3.1   3h43m
pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-r-e7a40326   stopped                                                                                                                            175m

```


```
[root@iaase00027570 ~]# cd /datadisk/replicas
[root@iaase00027570 replicas]# ls -l pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca
total 12815828
-rw-------. 1 root root        4096 Mar 16 11:58 revision.counter
-rw-r--r--. 1 root root 214748364800 Mar 16 11:59 volume-head-002.img
-rw-r--r--. 1 root root         178 Mar 16 11:59 volume-head-002.img.meta
-rw-r--r--. 1 root root         196 Mar 16 11:59 volume.meta
-rw-r--r--. 1 root root 214748364800 Mar 16 11:58 volume-snap-91df8940-02b8-473c-aa31-55d58dec1339.img
-rw-r--r--. 1 root root         158 Mar 16 12:01 volume-snap-91df8940-02b8-473c-aa31-55d58dec1339.img.meta
[root@iaase00027570 replicas]# cd /datadisk/replicas/pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca
[root@iaase00027570 pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca]# cat volume.meta
{"Size":214748364800,"Head":"volume-head-002.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-1256f02e-698c-46db-9d9a-8e149d6477d9.img","SectorSize":512,"BackingFilePath":""}
[root@iaase00027570 pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca]#

[root@iaase00027571 pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-fdbe6d8f]# ls -l /datadisk/replicas/pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-fdbe6d8f
total 12815812
-rw-------. 1 root root        4096 Mar 16 12:11 revision.counter
-rw-r--r--. 1 root root 214748364800 Mar 16 12:09 volume-head-001.img
-rw-r--r--. 1 root root         178 Mar 16 12:09 volume-head-001.img.meta
-rw-r--r--. 1 root root         196 Mar 16 12:11 volume.meta
-rw-r--r--. 1 root root 214748364800 Mar 16 12:11 volume-snap-1256f02e-698c-46db-9d9a-8e149d6477d9.img
-rw-r--r--. 1 root root         158 Mar 16 12:11 volume-snap-1256f02e-698c-46db-9d9a-8e149d6477d9.img.meta
[root@iaase00027571 pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-fdbe6d8f]#
[root@iaase00027571 replicas]# cd /datadisk/replicas/pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-fdbe6d8f
[root@iaase00027571 pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-fdbe6d8f]# cat volume.meta
{"Size":214748364800,"Head":"volume-head-001.img","Dirty":true,"Rebuilding":false,"Error":"","Parent":"volume-snap-1256f02e-698c-46db-9d9a-8e149d6477d9.img","SectorSize":512,"BackingFilePath":""}
[root@iaase00027571 pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-fdbe6d8f]#
```

**Comment by derekbit** [comment] 2023-03-16 12:47
@mynktl 
Sorry, I got confused.
Is `pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca` also a problematic volume? I cannot find the PVC in your support bundle. Can you reproduce the issue easily? If YES, can you provide the latest support bundle and dmesg of each node of the latest result.

**Comment by mynktl** [comment] 2023-03-16 13:01
@derekbit  
I am not seeing issue right now in `pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca`. This PVC is new. I recreated it post data loss.

> Can you reproduce the issue easily? If YES, can you provide the latest support bundle and dmesg of each node of the latest result.

I will try to repro. I have dmesg logs from previous run. If you want, I can share the same.

**Comment by derekbit** [comment] 2023-03-16 13:06
> @derekbit I am not seeing issue right now in `pvc-a15c8d7a-c52f-4e71-8a8c-a5465d2da719-f554eeca`. This PVC is new. I recreated it post data loss.
> 
> > Can you reproduce the issue easily? If YES, can you provide the latest support bundle and dmesg of each node of the latest result.

Cool. Thank you.

> 
> I will try to repro. I have dmesg logs from previous run. If you want, I can share the same.

@mynktl I want the dmesg and check them together. Thank you.

**Comment by mynktl** [comment] 2023-03-16 13:41
[message.tar.gz](https://github.com/longhorn/longhorn/files/10991421/message.tar.gz)

Hi @derekbit 
I have attached messages file from all 3 nodes.

**Comment by rajivml** [comment] 2023-03-16 13:45
@derekbit you can use the support bundles shared by me as well where you can correlate both longhorn and dmesg logs

**Comment by derekbit** [comment] 2023-03-16 14:32
@mynktl
Thank you

@rajivml 
Sure. I'm checking your support bundle as well.
I found there are lots of similar error messages in the longhorn engine logs. It means the disk file is missing and is somehow deleted.
```
[pvc-0eda8351-19d4-4a94-bea1-6ee7c72b93d7-e-a441b420] time="2023-03-08T11:06:06Z" level=error msg="Backend tcp://10.42.6.215:10030 monitoring failed, mark as ERR: ping failure due to Fail to get file /host/datadisk/replicas/pvc-0eda8351-19d4-4a94-bea1-6ee7c72b93d7-5c63df08/volume-head-002.img size"
```

I noticed the file `kube-system-longhorn-replica-folder-cleanup-lqbp4` and saw some messages like
```
Replica not found but Volume found with a valid status (robust status healthy). Data directory /datadisk//replicas/pvc-c15462c9-2384-44e2-a482-75c5fa34bc4b-4c673734/ can be deleted
```
Can you elaborate more on the `longhorn-replica-folder-cleanup`? Is it possible to delete the replica directories.

**Comment by rajivml** [comment] 2023-03-16 15:24
@derekbit looks like this PR has made that script irrelevant ? https://github.com/longhorn/longhorn-manager/pull/1413/files

**Comment by derekbit** [comment] 2023-03-16 15:37
```
/bin/bash: line 8: jq: command not found
Replica not found but Volume found with a valid status (robust status healthy). Data directory /datadisk//replicas/pvc-b56daf56-0332-47de-9b00-1855853b58c6-a7754531/ can be deleted
```

`jq` is not found in the system, so it always hit
```
                    echo "Replica not found but Volume found with a valid status (robust status ${robust_status}). Data directory $dir can be deleted"
                    rm -rf $dir
```
That means the replica directory is always deleted.

**Comment by rajivml** [comment] 2023-03-16 15:51
Thanks a lot @derekbit for looking into it at short notice. We have deleted that daemonset and hydrating the container registry again to validate if it indeed solves the issue 

We will look into orphaned replica folder cleanup feature as well 

Thanks to @innobead as well

**Comment by innobead** [comment] 2023-03-16 15:57
@rajivml feel free to reopen this if the issue is still. 

BTW, suggest following each release note, so you will better understand what new features/improvements/bugfixes introduced.

**Closed by innobead** 2023-03-16 15:57 UTC
Labels: kind/bug, invalid, area/environment-issue

**Comment by mynktl** [comment] 2023-03-16 16:04
Thanks @derekbit for looking into this.

**Comment by derekbit** [comment] 2023-03-16 16:16
> @derekbit one last confirmation, is it actually the jq issue or the daemonset has become irrelevant because of this PR https://github.com/longhorn/longhorn-manager/pull/1413/files ?

The issue is caused by missing jq and not related to https://github.com/longhorn/longhorn-manager/pull/1413/files .
