### ISSUE TITLE
[TASK] Upload local backing images to Longhorn

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2538] opened 2021-04-26 04:07 UTC
**What's the task? Please describe.**
Support uploading local backing images to Longhorn via UI

**Comment by yasker** [comment] 2021-04-26 05:46
1. I think it's not a task? It's a feature.
2. It's a duplicate of #2404

**Comment by innobead** [comment] 2021-04-26 07:56
Closing, because it's a duplicated of #2404

**Closed by innobead** 2021-04-26 07:56 UTC
Labels: area/backing-image, kind/enhancement, kind/task, priority/1, require/manual-test-plan
