### ISSUE TITLE
[BUG] Nightly test: Modify the tests related to rebuilding a new replica

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1918] opened 2020-10-27 22:50 UTC
**Describe the bug**
The following tests should be modified after the implementation of https://github.com/longhorn/longhorn/issues/1304. 
1. test_rebuild_after_replica_file_crash
2. test_rebuild_replica_and_from_replica_on_the_same_node
3. test_dr_volume_with_restore_command_error
4. test_csi_expansion_with_replica_failure

Currently, the test is designed to check that after a replica file crash new replica is rebuilt. 
According to https://github.com/longhorn/longhorn/issues/1304, the existing replica will be reused and no new replica rebuild is expected.

**To Reproduce**
1. Set up integration test on a cluster and run test above mentioned tests
**Log**
```
volume_head_file_path = replica["dataPath"] + "/volume-head-000.img"
    
        exec_cmd = ["rm", volume_head_file_path]
    
        try:
            subprocess.check_output(exec_cmd)
        except subprocess.CalledProcessError as e:
            print(e.output)
    
        wait_for_volume_degraded(client, volume_name)
        wait_for_rebuild_complete(client, volume_name)
        wait_for_volume_healthy(client, volume_name)
    
        volume = client.by_id_volume(volume_name)
    
        crashed_replica = None
        for rep in volume.replicas:
            if rep["name"] == replica["name"]:
                crashed_replica = rep
                break
    
>       assert crashed_replica["running"] is False
E       assert True is False

test_ha.py:1978: AssertionError
```

**Environment:**
 - Longhorn version: Longhorn-master
 - Kubernetes version: v1.18
 - Node OS type and version: ubuntu 18.04

**Comment by yasker** [comment] 2020-10-28 17:27
@shuo-wu those are integration test regression, please prioritize fixing them.

**Comment by shuo-wu** [comment] 2020-11-11 12:44
Will re-check test `test_csi_expansion_with_replica_failure` due to this test failure: https://ci.longhorn.io/job/public/job/longhorn-upgrade-tests/153/testReport/junit/tests/test_csi/test_csi_expansion_with_replica_failure/

**Comment by shuo-wu** [comment] 2020-11-25 11:08
`test_csi_expansion_with_replica_failure` passed in recent nightly tests. And the test implementation iteself looks fine.

**Comment by khushboo-rancher** [comment] 2020-12-01 22:01
The test `test_csi_expansion_with_replica_failure` failed recently. https://ci.longhorn.io/job/public/job/longhorn-upgrade-tests/176/
Moving it back to the backlog.

**Comment by shuo-wu** [comment] 2021-01-12 08:33
The bug in `test_csi_expansion_with_replica_failure` is tracked and fixed in https://github.com/longhorn/longhorn/issues/2167

We can close this issue if there is no other failure triggered by the above test cases.

**Comment by shuo-wu** [comment] 2021-01-25 08:43
Close this issue since the above tests do not fail in the recent nightly test.

**Closed by shuo-wu** 2021-01-25 08:43 UTC
Labels: area/test
