### ISSUE TITLE
[BUG]Longhorn nfsv4 client may fall back to use nfsv3

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#1488] opened 2020-06-12 15:34 UTC
There are multiple issues indicates that even though we've used `mount -t nfs4` for the NFS since we only support nfsv4, mount may fall back to use nfsv3 and caused confusing. E.g. 

https://github.com/longhorn/longhorn/issues/1346
https://forums.rancher.com/t/nfs-backup-target-localhost/17699/3

It's better if we can just let mount fail if it's not nfsv4, since we don't support NFSv3 anyway.

**Comment by yasker** [comment] 2020-07-02 21:17
The backend is merged. Need to check the pre-merge check list.

**Comment by ttpcodes** [comment] 2020-07-02 22:53
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [X] Which areas/issues this PR might have potential impacts on?
Area: area/engine, area/manager
Issues: #1488

* [X] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [X] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [X] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [X] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [X] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by ttpcodes** [comment] 2020-07-02 23:14
# Reproduce Steps
Since the client falling back to `NFSv3` usually results in a failure to mount the `NFS` share, the way we can check for `NFSv3` fallback is to check the error message returned and see if it mentions `rpc.statd`, since dependencies on `rpc.statd` and other services are no longer needed for `NFSv4`, but are needed for `NFSv3`:
1. Modify `nfs-backupstore.yaml` from `deploy/backupstores/` such that it includes the following environment variable (this will force the server to only support `NFSv3`:
```yaml
name: PROTOCOLS
value: "3"
```
2. Create the `Backup Store` using `nfs-backupstore.yaml`.
3. Set the `Backup Target` in the `longhorn-ui` to `nfs://longhorn-test-nfs-svc.default:/opt/backupstore`.
4. Attempt to list the `Backup Volumes` in the `longhorn-ui`. You should get an error that resembles the following:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output /usr/sbin/start-statd: 23: /usr/sbin/start-statd: systemctl: not found mount.nfs4: rpc.statd is not running but is required for remote locking. mount.nfs4: Either use '-o nolock' to keep locks local, or start statd. , error exit status 32 , stderr, time="2020-07-02T23:13:33Z" level=error msg="Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output /usr/sbin/start-statd: 23: /usr/sbin/start-statd: systemctl: not found\nmount.nfs4: rpc.statd is not running but is required for remote locking.\nmount.nfs4: Either use '-o nolock' to keep locks local, or start statd.\n, error exit status 32" , error exit status 1
```

**Comment by ttpcodes** [comment] 2020-07-03 00:03
# Reproduce Steps
Since this issue has already been patched, this issue can be reproduced by creating a `Longhorn` installation that uses this default `Engine Image`, which doesn't have the patch: `quay.io/ttpcodes/longhorn-engine:nfs3`

This can be done using the following steps:
1. Modify `01-manager.yaml` inside of `deploy/install/02-components/` in the `longhorn-manager` repository so it uses the unpatched `Engine Image`:
```yaml
- --engine-image
- quay.io/ttpcodes/longhorn-engine:nfs3
```
2. Apply the changes to the `longhorn-manager` and wait for new `Pods` for `longhorn-manager` to be created.

Since the client falling back to `NFSv3` usually results in a failure to mount the `NFS` share, the way we can check for `NFSv3` fallback is to check the error message returned and see if it mentions `rpc.statd`, since dependencies on `rpc.statd` and other services are no longer needed for `NFSv4`, but are needed for `NFSv3`:
1. Modify `nfs-backupstore.yaml` from `deploy/backupstores/` in the `longhorn` repository such that it includes the following environment variable (this will force the server to only support `NFSv3`):
```yaml
name: PROTOCOLS
value: "3"
```
2. Create the `Backup Store` using `nfs-backupstore.yaml`.
3. Set the `Backup Target` in the `longhorn-ui` to `nfs://longhorn-test-nfs-svc.default:/opt/backupstore`.
4. Attempt to list the `Backup Volumes` in the `longhorn-ui`. You should get an error that resembles the following:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output /usr/sbin/start-statd: 23: /usr/sbin/start-statd: systemctl: not found mount.nfs4: rpc.statd is not running but is required for remote locking. mount.nfs4: Either use '-o nolock' to keep locks local, or start statd. , error exit status 32 , stderr, time="2020-07-02T23:13:33Z" level=error msg="Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output /usr/sbin/start-statd: 23: /usr/sbin/start-statd: systemctl: not found\nmount.nfs4: rpc.statd is not running but is required for remote locking.\nmount.nfs4: Either use '-o nolock' to keep locks local, or start statd.\n, error exit status 32" , error exit status 1
```
# Manual Test Steps
To test this, follow the steps above, but against the `master` build of `Longhorn` which should contain the patch. You should instead see an error similar to the following:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/quay.io-ttpcodes-longhorn-engine-nfs4/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory , error exit status 32 , stderr, time="2020-07-02T23:44:22Z" level=error msg="Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory\n, error exit status 32" , error exit status 1
```
This indicates that the mount failed on `NFSv4` and did not attempt to fall back to `NFSv3` since there's no mention of `rpc.statd`.

**Comment by khushboo-rancher** [comment] 2020-07-07 00:28
Verified on master - 07-06-2020

Validation - **Passed**

Followed the steps to repo from https://github.com/longhorn/longhorn/issues/1488#issuecomment-653266333
With ```NFSv3``` manager's log shows below error on master.
```
[longhorn-manager-r6b68] {"level":"warning","msg":"backup store monitor: failed to list backup volumes in nfs://longhorn-test-nfs-svc.default:/opt/backupstore: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/quay.io-ttpcodes-longhorn-engine-nfs3/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output /usr/sbin/start-statd: 23: /usr/sbin/start-statd: systemctl: not found\nmount.nfs4: rpc.statd is not running but is required for remote locking.\nmount.nfs4: Either use '-o nolock' to keep locks local, or start statd.\n, error exit status 32\n, stderr, time=\"2020-07-07T00:17:52Z\" level=error msg=\"Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output /usr/sbin/start-statd: 23: /usr/sbin/start-statd: systemctl: not found\\nmount.nfs4: rpc.statd is not running but is required for remote locking.\\nmount.nfs4: Either use '-o nolock' to keep locks local, or start statd.\\n, error exit status 32\"\n, error exit status 1","time":"2020-07-07T00:17:52Z"}
```
UI shows error as below
<img width="1771" alt="Screen Shot 2020-07-06 at 5 25 19 PM" src="https://user-images.githubusercontent.com/60111667/86674895-00fcbe80-bfae-11ea-8dfe-e70bbc4e30ea.png">


Without fix, the manager logs show timeout failure in this sceanrio
```
[longhorn-manager-cps9x] {"level":"warning","msg":"backup store monitor: failed to list backup volumes in nfs://longhorn-test-nfs-svc.default:/opt/backupstore: error listing backup volumes: Timeout executing: /var/lib/longhorn/engine-binaries/quay.io-ttpcodes-longhorn-engine-nfs3/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output , stderr, , error \u003cnil\u003e","time":"2020-07-07T00:24:24Z"} 
```

**Comment by yasker** [comment] 2020-07-07 00:33
@khushboo-rancher It seems the error message is not as expected above?

Also, @ttpcodes There is nowhere in the error message mentioned version issue? Previously the error reported by rpc.statd is not obvious to the user, so we should at least tell user something might be wrong with the NFS server version.

**Comment by khushboo-rancher** [comment] 2020-07-07 01:04
Sorry, I misunderstood the bug. Understood after discussion with @yasker.

The logs with the fix is appearing as below.
```
[longhorn-manager-ncncf] {"level":"error","msg":"Error in request: error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory\n, error exit status 32\n, stderr, time=\"2020-07-07T01:00:37Z\" level=error msg=\"Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory\\n, error exit status 32\"\n, error exit status 1","time":"2020-07-07T01:00:37Z"}
```
But as @yasker mentioned there should be clear indication in log as the NFS version might be wrong needs to be addressed.

**Comment by ttpcodes** [comment] 2020-07-09 20:10
longhorn/backupstore#47 has been merged now, which contains the error message about `NFS` version. Instead of seeing the error message that I described above, you should see the following error message when following the test steps:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/quay.io-ttpcodes-longhorn-engine-nfs4/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: nfsv4 mount failed but nfsv3 mount succeeded, may be due to server only supporting nfsv3: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory , error exit status 32 , stderr, time="2020-07-09T20:05:44Z" level=error msg="Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: nfsv4 mount failed but nfsv3 mount succeeded, may be due to server only supporting nfsv3: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory\n, error exit status 32" , error exit status 1
```
You should see a mention that the error may have been caused by `NFSv3` like above.

Additionally, there is one new manual test case since we want to make sure that the wrapped error message should only appear if the server is `NFSv3`:
1. Set up the `NFS Backup Store` normally using `nfs-backupstore.yaml`. Do **not** make the changes to `nfs-backupstore.yaml` that I described above.
2. Set the `Backup Target` in the `longhorn-ui` to a non-exported `NFS` share, such as `nfs://longhorn-test-nfs-svc.default:/opt/test` (I set it to `test` because the correct directory is supposed to be `backupstore`).
3. Attempt to list the Backup Volumes in the longhorn-ui. You should get an `error` that resembles the following:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/quay.io-ttpcodes-longhorn-engine-nfs4/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/test], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/test: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/test /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/test], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/test failed, reason given by server: No such file or directory , error exit status 32 , stderr, time="2020-07-09T20:09:21Z" level=error msg="Cannot mount nfs longhorn-test-nfs-svc.default:/opt/test: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/test /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/test], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/test failed, reason given by server: No such file or directory\n, error exit status 32" , error exit status 1
```
You should **not** see any mention of `NFSv3` in this case.

**Comment by khushboo-rancher** [comment] 2020-07-10 00:57
Verified on Master - ```97a869e``` - 07-09-2020

Validation - **Passed**

With server supports only NFSv3, log is  as below:
```
error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: nfsv4 mount failed but nfsv3 mount succeeded, may be due to server only supporting nfsv3: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory\n, error exit status 32\n, stderr, time=\"2020-07-10T00:15:52Z\" level=error msg=\"Cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore: nfsv4 mount failed but nfsv3 mount succeeded, may be due to server only supporting nfsv3: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/backupstore /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore failed, reason given by server: No such file or directory\\n, error exit status 32\"\n, error exit status 1"
```

The log when NFSv3 is not the failure cause:
```
error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/test], output Cannot mount nfs longhorn-test-nfs-svc.default:/opt/test: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/test /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/test], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/test failed, reason given by server: No such file or directory\n, error exit status 32\n, stderr, time=\"2020-07-10T00:20:25Z\" level=error msg=\"Cannot mount nfs longhorn-test-nfs-svc.default:/opt/test: Failed to execute: mount [-t nfs4 -o nfsvers=4.2 longhorn-test-nfs-svc.default:/opt/test /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/test], output mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/test failed, reason given by server: No such file or directory\\n, error exit status 32\"\n, error exit status 1"
```

**Closed by khushboo-rancher** 2020-07-10 00:57 UTC
Labels: area/engine, area/manager, bug, priority/3, require/manual-test-plan
