### ISSUE TITLE
[FEATURE] Container-Optimized OS support

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#6165] opened 2023-06-20 05:13 UTC
## Is your feature request related to a problem? Please describe (👍 if you like this request)

https://cloud.google.com/container-optimized-os/docs This is an evaluation task instead to see how Longhorn can integrate with it. 

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Additional context

Limitations https://cloud.google.com/container-optimized-os/docs/concepts/features-and-benefits

**Comment by c3y1huang** [comment] 2024-03-06 03:07
According to the [document](https://cloud.google.com/container-optimized-os/docs/concepts/features-and-benefits#use_cases_for_container-optimized_os) statement:
> Container-Optimized OS is the default node OS Image in [Kubernetes Engine](https://cloud.google.com/kubernetes-engine) and other [Kubernetes](https://kubernetes.io/) deployments on Google Cloud Platform.

Given that Longhorn is compatible with GKE, we can assume that it should also work on COS.

TODO: manually create a COS cluster with Kubernetes and verify Longhorn.

**Comment by c3y1huang** [comment] 2024-03-06 05:38
Seems like we've only tested [GKE with UBUNTU_CONTAINERD](https://github.com/longhorn/longhorn-tests/blob/103d84f1b322e3a248f6197350cd79a8e90d5362/pipelines/gke/terraform/main.tf#L64). We've never done any testings with  `COS_CONTAINERD`.

**Comment by c3y1huang** [comment] 2024-03-12 01:07
> TODO: figure out how if it is possible to get Longhorn dependencies onto COS.

COS_CONTAINERD doesn't ship with the package manager, and the majority of directories are set to read-only. GKE works around this by cloud-config in user-data and `/home/kubernetes/containerized_mounter/rootfs` that contains the dependencies and mounts within the chroot environment. Testing with other orchestrators like K3s is challenging due to the absence of a support method for the environment pre-configuration.

The easiest approach is to use GKE which comes with the COS_CONTAINER + Kubernetes. We could potentially use the same rootfs for installing Longhorn dependencies and mounting for the data path. However, since the `user-data` is predefined in GKE, we can't directly utilize the cloud-config. Instead, a possible workaround is to use a daemonset that runs `chroot` and `nsenter` for Longhorn dependencies setup/installation.

ref: https://github.com/kubernetes/kubernetes/tree/v1.29.2/cluster/gce

**Comment by c3y1huang** [comment] 2024-03-12 06:34
As evidence supporting the assumption mentioned above, I have successfully installed the open-iscsi via a daemonset and confirmed its running on the host system:
```
> ps aux | grep iscsid
root       58264  0.0  0.0  25384   292 ?        Ss   06:21   0:00 /sbin/iscsid
root       58265  0.0  0.0  25888  5324 ?        S<Ls 06:21   0:00 /sbin/iscsid
```

**Comment by c3y1huang** [comment] 2024-03-18 04:33
Given that we've done the majority of the work on the Talos support feature, it seems that this feature that only a small effort is needed for this feature. Primarily, providing users with the necessary dependency installation.

Additionally, in GKE, periodic updates are made to `topology.kubernetes.io/zone` to reflect the actual zone, causing failures of the `replica_auto_balance_zone` tests when such updates occur. To tackle this, we can modify the tests to refresh the zone labels to maintain the expected zone label simulation throughout each test run.

Below is the full test result from my PoC.
```
= 355 passed, 19 skipped, 348 warnings in 53969.99s (14:59:29) =
```

**Comment by chriscchien** [comment] 2024-04-08 08:54
Hi @c3y1huang , test case [test_replica_auto_balance_node_duplicates_in_multiple_zones](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/813/testReport/junit/tests/test_zone/test_replica_auto_balance_node_duplicates_in_multiple_zones/) failed on master pipeline after https://github.com/longhorn/longhorn-tests/pull/1819, could you take a look on that? thank you.

**Comment by c3y1huang** [comment] 2024-04-08 09:42
> Hi @c3y1huang , test case [test_replica_auto_balance_node_duplicates_in_multiple_zones](https://ci.longhorn.io/job/public/job/master/job/sles/job/arm64/job/longhorn-tests-sles-arm64/813/testReport/junit/tests/test_zone/test_replica_auto_balance_node_duplicates_in_multiple_zones/) failed on master pipeline after [longhorn/longhorn-tests#1819](https://github.com/longhorn/longhorn-tests/pull/1819), could you take a look on that? thank you.

Thank you @chriscchien . Will be fixed in https://github.com/longhorn/longhorn-tests/pull/1849.

**Comment by yangchiu** [comment] 2024-04-25 09:34
After applied `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-gke-cos-node-agent.yaml` on `cos_containerd`, there are some error messages in the log:

```
$ kubectl get pods
NAME                                  READY   STATUS    RESTARTS        AGE
longhorn-gke-cos-node-agent-5n9xx     1/1     Running   1 (7h43m ago)   7h44m
longhorn-gke-cos-node-agent-8r7tx     1/1     Running   1 (7h43m ago)   7h44m
longhorn-gke-cos-node-agent-f28vz     1/1     Running   1 (7h43m ago)   7h44m

$ kubectl logs longhorn-gke-cos-node-agent-5n9xx
...
(23/24) Installing: systemd-249.17-150400.8.40.1.x86_64 [.......
Creating group systemd-journal with gid 485.
Creating group systemd-network with gid 484.
Creating user systemd-network (systemd Network Management) with uid 484 and gid 484.
Creating group systemd-timesync with gid 483.
Creating user systemd-timesync (systemd Time Synchronization) with uid 483 and gid 483.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
/usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
All rules containing unresolvable specifiers will be skipped.
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
done]
(24/24) Installing: open-iscsi-2.1.9-150500.46.3.1.x86_64 [..
System has not been booted with systemd as init system (PID 1). Can't operate.
Failed to connect to bus: Host is down
```

Not sure if there's any issue here, but longhorn can be installed without problem. cc @c3y1huang

**Comment by c3y1huang** [comment] 2024-04-25 10:26
> After applied `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-gke-cos-node-agent.yaml` on `cos_containerd`, there are some error messages in the log:
> 
> ```
> $ kubectl get pods
> NAME                                  READY   STATUS    RESTARTS        AGE
> longhorn-gke-cos-node-agent-5n9xx     1/1     Running   1 (7h43m ago)   7h44m
> longhorn-gke-cos-node-agent-8r7tx     1/1     Running   1 (7h43m ago)   7h44m
> longhorn-gke-cos-node-agent-f28vz     1/1     Running   1 (7h43m ago)   7h44m
> 
> $ kubectl logs longhorn-gke-cos-node-agent-5n9xx
> ...
> (23/24) Installing: systemd-249.17-150400.8.40.1.x86_64 [.......
> Creating group systemd-journal with gid 485.
> Creating group systemd-network with gid 484.
> Creating user systemd-network (systemd Network Management) with uid 484 and gid 484.
> Creating group systemd-timesync with gid 483.
> Creating user systemd-timesync (systemd Time Synchronization) with uid 483 and gid 483.
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> /usr/lib/tmpfiles.d/journal-nocow.conf:26: Failed to resolve specifier: uninitialized /etc detected, skipping
> All rules containing unresolvable specifiers will be skipped.
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> done]
> (24/24) Installing: open-iscsi-2.1.9-150500.46.3.1.x86_64 [..
> System has not been booted with systemd as init system (PID 1). Can't operate.
> Failed to connect to bus: Host is down
> ```
> 
> Not sure if there's any issue here, but longhorn can be installed without problem.

When dependencies are installed via package managers within a container, the package manager will try to initiate the ISCSi services managed by systemd, which causes problems because the container environment doesn't fully support systemd. Hence, the script manually starts the daemon instead of relying on systemd. Therefore, this kind of error should be safe to ignored in this context.

**Comment by yangchiu** [comment] 2024-04-26 05:50
Verified passed on master-head (longhorn-manager f63611c) following [the document](https://github.com/longhorn/website/pull/884) to setup Longhorn on `cos_containerd`. Longhorn can be installed without problem, and run core test on it, test cases all passed.

**Closed by yangchiu** 2024-04-26 05:50 UTC
Labels: kind/feature, area/install-uninstall-upgrade, highlight, priority/0, require/doc, require/manual-test-plan, area/platform-arch

**Comment by innobead** [comment] 2024-04-26 06:01
> > Not sure if there's any issue here, but longhorn can be installed without problem.
> 
> When iSCSId is installed via package managers within a container, the package manager will try to initiate the ISCSi services managed by systemd, which causes problems because the container environment doesn't fully support systemd. Hence, the script manually starts the daemon instead of relying on systemd. Therefore, this kind of error should be safe to ignore in this context.

@c3y1huang can we mention this is an expected warning in the doc? to prevent any confusion or later explanation?

**Comment by c3y1huang** [comment] 2024-04-26 07:25
> @c3y1huang can we mention this error as an expected warning in the doc? to prevent any confusion or later explanation?

Sure! Doc updated (https://github.com/longhorn/website/pull/884/files#diff-2eb85726fa84ef4b9aa85bb05e1a39d292fccefd1880bb5565441452273b3df3R51-R52).
