### ISSUE TITLE
[BUG] RWX volume unable to mount in rke2 cluster.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2659] opened 2021-06-07 20:31 UTC
**Describe the bug**
RWX volume fails to mount in a rke2 cluster.

**To Reproduce**
1. Create a rke2 kubernetes cluster.
2. Deploy Longhorn and make sure the nfs-common is installed on the nodes.
3. Create a RWX volume using LH UI. Create PV/PVC
4. Create a statefulSet and attach it to the RWX volume, the volume fails to mount.

**Expected behavior**
The volume should get mounted successfully.

**Log**
[longhorn-support-bundle_779efc67-dcfb-4130-a169-f3e872e0f27b_2021-06-07T20-20-46Z.zip](https://github.com/longhorn/longhorn/files/6611833/longhorn-support-bundle_779efc67-dcfb-4130-a169-f3e872e0f27b_2021-06-07T20-20-46Z.zip)

Volume name - volume-rwx-1
pod name - wk-rwx-1
Time stamp - ~2021-06-07 19:45:00 UTC

**Environment:**
 - Longhorn version: Longhorn-v1.1.2-head
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.21.1-rc2+rke2r1
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 4 GB
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: upto 5 Gi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 3

**Additional Context:**
RWO volumes are able to mount on the same node in the cluster.

**Comment by innobead** [comment] 2021-06-08 08:09
cc @kaxing

**Comment by joshimoo** [comment] 2021-06-08 22:24
I had a quick look at the test cluster, and identified a couple of potential issues, related to the share-manager.
- initially a failed mount call will be retried indefinitely on the share-manager before starting the nfs-server
- there was also a case where the nfs-server died but the share-manager process was not terminated (which means the pod is death but will not be restarted) this can be fixed by replacing the readiness probe with a liveness probe instead. And also consider adding an init probe as well.

On the manager side, while removing the VA cleanup feature I noticed we don't keep terminating pods in workload status.
There share-manager-controller determines whether the share-manager is still needed based on the active workloads.
We should probably keep terminating pods in the workload status.
https://github.com/longhorn/longhorn-manager/blob/779149f6f3a8556abff08e12feec6ec0646c3831/controller/share_manager_controller.go#L395

Since we don't have the terminating pods in the workload status, the share-manager pod might get terminated before the workload pod had a chance to finish termination and unmount the volume.

**Comment by innobead** [comment] 2021-06-09 09:30
@khushboo-rancher as we discussed, please help check if this issue already exists in 1.1.1 already or a regression issue.

**Comment by shuo-wu** [comment] 2021-06-09 14:05
Once there is a workload trying to use the RWX volume, the volume should be attached with a share manager(NFS server) launched. Then does this statement `initially a failed mount call will be retried indefinitely on the share-manager before starting the nfs-server` mean?

**Comment by joshimoo** [comment] 2021-06-09 22:11
@shuo-wu that statement refers to the RWO mount inside of the share-manager pod.
It will not start the nfs-server till the volume is mounted, and a failed mount currently is retried indefinitely.

**Comment by shuo-wu** [comment] 2021-06-10 04:30
You mean the RWO volume inside the share manager pod gets stuck in indefinitely mount failure & retries?

**Comment by khushboo-rancher** [comment] 2021-06-10 23:09
Update on the issue:
I am not able to reproduce this with Longhorn v1.1.2-head again or with Longhorn v1.1.1. This seems to be not reproducible all the time. Even our integration tests of RWX results are inconsistent on K3s cluster, it's passing ratio is nearly 50% on the nightly integration test run.

**Comment by derekbit** [comment] 2023-06-16 02:44
@khushboo-rancher  Is the issue still available?

cc @yangchiu @chriscchien

**Closed** 2023-07-05 11:44 UTC
Labels: kind/bug, severity/1, reproduce/often, priority/2, area/volume-rwx
