### ISSUE TITLE
[BUG] Backing Image Data Inconsistency if it's Exported from a Backing Image Backed Volume

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#6899] opened 2023-10-16 07:54 UTC
## Describe the bug (🐛 if you encounter this issue)
The volume encounters a data integrity issue, if it's from a backing image, and such backing image is exported by a volume backed by another backing image.

## To Reproduce
1. Preparing a Harvester v1.2.0-head cluster (for using volume as an OS root disk)
2. Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1**
3. Creating volume **vol1** from **img1**
4. Creating a VM with **vol1** as the root disk, and writing some data
5. Issuing sync on filesystem, e.q. `$ sudo sync`
6. Stopping VM, and waiting until **vol1** is completely detached
7. Exporting **vol1** as **img2**
8. Creating  **vol2** from **img2**
9. Comparing data content between **vol1** and **vol2**, the data is inconsistent
10. Running `e2fsck -v` on **vol2**, fsck will report filesystem errors and require data repair

## Expected behavior
The data of **vol1** and **vol2** should be consistent.

## Support bundle for troubleshooting
[supportbundle_066aa8ed-a12b-4ccc-971c-59404ee44cd4_2023-10-16T07-46-44Z.zip](https://github.com/longhorn/longhorn/files/12913647/supportbundle_066aa8ed-a12b-4ccc-971c-59404ee44cd4_2023-10-16T07-46-44Z.zip)

## Environment

 - Longhorn version: v1.4.3
 - Harvester version: v1.2.0-head
 - Number of Longhorn volumes in the cluster: 2
 - Impacted Longhorn resources:
   - Volume names: pvc-b8bd9013-e8e9-449d-9c25-6c6c0824d0b3, pvc-de64dd95-b0c1-4ce9-864a-88d38e06d9d3

## Additional context

- If **vol1** is not backed by backing image, there is no data inconsistency found between **vol1** and **vol2**
- A single node Harvester cluster should be enough to reproduce this issue

**Comment by innobead** [comment] 2023-10-26 11:57
cc @shuo-wu

**Comment by WebberHuang1118** [comment] 2023-10-27 06:29
Some observations with the following steps:
1. Preparing a Harvester v1.2.0-head single node cluster (for using volume as an OS root disk)
2. Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1** with replica number is 1
3. Checking data usage of **img1** (mapped to `bi default-image-s9rfj`), which is `640MB` ![data_usage_origin_img](https://github.com/longhorn/longhorn/assets/19387129/c79d04d3-cb9e-4383-8a07-19212c74de01)
4. Creating volume **os-vol** (mapped to `volume pvc-c3b1a434-86ee-453b-afc7-a52fe113c059`) from **img1** with claim size 10GB
5. Creating a VM with  **os-vol** as the root disk
6. Stopping VM, and waiting until **os-vol** is completely detached
7. Exporting **os-vol** as **os-vol.img** (mapped to `bi default-image-j8ghr`) with replica number is 1
8. Checking replica data usage of **os-vol**, which is `523MB` ![data_usage_os_vol](https://github.com/longhorn/longhorn/assets/19387129/bd756b83-c28d-4336-9512-4789f8a8ef23)
9. Checking data usage of **os-vol.img**, which is `2507MB` ![data_usage_os_vol_img](https://github.com/longhorn/longhorn/assets/19387129/ac8aa9d4-1620-4ba0-a5c5-2493a50fe1b3)
     - For the data usage, **os-vol.img**(2507MB) is much greater than the summation of **img1**(640MB) and **os-vol**(523MB)
     - The **os-vol.img**'s data usage shouldn't be greater than the summation of **img1**'s and **os-vol**'s ?
10. Creating volume **copy-vol** from **os-vol.img** with claim size 10GB
11. Comparing data content between **os-vol** and **copy-vol** with `$cmp -l os-vol copy-vol`
12. From the compare result [cmp.log](https://github.com/longhorn/longhorn/files/13184929/cmp.log), there are several continuous byte ranges overwritten with zero in the synthetic volume, **copy-vol**

Thanks

**Comment by ChanYiLin** [comment] 2024-01-03 03:08
Note: From Longhorn side, we can't reproduce the issue

Longhorn side reproduce steps
1. Create a BackingImageA
2. Create a Volume with the BackingImageA
3. Write some data to the Volume
4. Get the checksum of the Volume
5. Export the BackingImageB from the Volume
6. Get the checksum of the BackingImageB
7. Checksum is the same

**Comment by innobead** [comment] 2024-01-03 10:23
@WebberHuang1118 Please work with @ChanYiLin to reproduce the issue.

**Comment by WebberHuang1118** [comment] 2024-01-03 11:31
From the above reproduce steps https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530,

After step7 in https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530,
since the VM is stopped and the volume is detached, IMHO, this issue could be reduced to "if the exported backing image content is the same as the source volume ?"

As I described in step9 https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530,
the original backing image size is 640MB and the volume is 523MB, however, the synthesized backing image's grows to 2507MB (> (640MB + 523MB)).

If we create a new volume and compare its content to the source volume, the content is inconsistent. However, if the source volume is not a backing image backed volume, there is no such data inconsistency.

**Comment by WebberHuang1118** [comment] 2024-01-08 06:15
I found a method to reproduce a similar case without Harvester-specific operations (no VM operation, only creating PVC from backing image and I/O access)

Detailed steps:
- Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1**
- Creating PVC **os-vol** from **img1** with claim size 10GB and 1 replica number
- Applying the following yaml to mount **os-vol** as block mode in the pod
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: block-volume-test
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/os-vol
        name: os-vol
    volumes:
      - name: os-vol
        persistentVolumeClaim:
          claimName: os-vol
  ```  
- Issuing filesystem expand and I/O on **os-vol**
  -  Enter pod **block-volume-test**
  -  Install fdisk
     - $ apt update; apt install -y fdisk
  - Expanding filesystem on **os-vol**
    - Check device (/dev/sda for exmaple) mapped to **os-vol** by device number
    - $ fdisk /dev/sda
      - d 1 n 1 default default No w
    - $ resize2fs /dev/sda1
  - Mounting /dev/sda1 and writing I/O into it
    - $ mkdir /data; $ mount -t ext4 /dev/sda1 /data
    - $ dd if=/dev/zero of=/data/file bs=1M count=2048
  - Flushing data to storage for **os-vol**
    - $ umount /data
  -  Delete pod **block-volume-test**, and waiting until **os-vol**'s LH volume detach
- Exporting os-vol as os-vol.img

**Comment by WebberHuang1118** [comment] 2024-01-08 06:38
I found a method to reproduce a similar case without Harvester-specific operations (no VM operation, only creating PVC from backing image and I/O access)

Detailed steps:
- Uploading Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img)), **img1**
- Creating PVC **os-vol** from **img1** with claim size 10GB and 1 replica number
- Applying the following yaml to mount **os-vol** as block mode in the pod
  ```
  apiVersion: v1
  kind: Pod
  metadata:
    name: block-volume-test
    namespace: default
  spec:
    containers:
    - name: volume-test
      image: ubuntu
      imagePullPolicy: IfNotPresent
      securityContext:
        privileged: true
      command: ["/bin/sleep"]
      args: ["3600"]
      volumeDevices:
      - devicePath: /dev/os-vol
        name: os-vol
    volumes:
      - name: os-vol
        persistentVolumeClaim:
          claimName: os-vol
  ```  
- Issuing filesystem expand and I/O on **os-vol**
  -  Enter pod **block-volume-test**
  -  Install fdisk
     - $ apt update; apt install -y fdisk
  - Expanding filesystem on **os-vol**
    - Check device (/dev/sda for exmaple) mapped to **os-vol** by device number
    - $ fdisk /dev/sda
      - d 1 n 1 default default No w
    - $ resize2fs /dev/sda1
  - Mounting /dev/sda1 and writing I/O into it
    - $ mkdir /data; $ mount -t ext4 /dev/sda1 /data
    - $ dd if=/dev/zero of=/data/file bs=1M count=2048
  - Flushing data to storage for **os-vol**
    - $ umount /data
  -  Delete pod **block-volume-test**, and waiting until **os-vol**'s LH volume detach
- Exporting **os-vol** as image **os-vol.img**
- Creating PVC **copy-vol** from **os-vol.img** with claim size 10GB
- Comparing data content between **os-vol** and **copy-vol** with `$cmp -l os-vol copy-vol`
  - The data content is different between the two PVC, **os-vol** and **copy-vol**
- Finding filesystem error on **copy-vol** with` $e2fsck -c /dev/copy-vol`
  - There is no filesystem error on **os-vol**

**Comment by ChanYiLin** [comment] 2024-01-08 10:04
I can reproduce the issue, will look into how we export BackingImage

**Comment by ChanYiLin** [comment] 2024-01-09 06:17
## BackingImage Export Mechanism

Volume is composed of a series of snapshots and a BackingImage
```
Volume = BackingImage -> snap1 -> head
```

When Exporting Volume to another BackingImage [code](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L352)
1. create a snapshot
2. create an in-memory replica by `OpenSnapshot()` from that snaphot
3. `preload()` the block index map (including BackingImage)
  - so we know where to find the latest data in each block
5. use `SyncContent()` from sparse-tools to sync the replica content to BackingImage Datasource
  - we use `GetDataLayout()` to see if the block is hole or data

## Volume Cloning Mechanism

Is totally the same as exporting BackingImage except it won't load BackingImage when doing `preload()

**Comment by ChanYiLin** [comment] 2024-01-09 06:23
## Volume Cloning Test
1. Creating BackingImage **img1** with Ubuntu jammy cloud image ([latest version](https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img))
2. Creating StorageClass
  ```
  kind: StorageClass
  apiVersion: storage.k8s.io/v1
  metadata:
    name: longhorn-test
  provisioner: driver.longhorn.io
  allowVolumeExpansion: true
  reclaimPolicy: Delete
  volumeBindingMode: Immediate
  parameters:
    numberOfReplicas: "1"
    staleReplicaTimeout: "2880"
    backingImage: "img1"
  ```
2. Creating PVC **os-vol** from **img1** with claim size 5GB and 1 replicas
4. Mount **os-vol** as block mode in the pod
5. Issuing filesystem expand and I/O on **os-vol**
6. Cloning **os-vol** to another volume **os-cloned** by applying the YAML
  ```
  apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: os-cloned
  spec:
    accessModes:
      - ReadWriteOnce
    volumeMode: Block
    storageClassName: longhorn-test
    resources:
      requests:
        storage: 5Gi
    dataSource:
      name: os-vol
      kind: PersistentVolumeClaim
  ```
7. attach both **os-vol** and **os-cloned** to the host and check the checksum are the same

**Comment by ChanYiLin** [comment] 2024-01-09 06:45
## BackingImage Export Test - FAILED

Following the same steps mentioned here, but don't apply `resizefs`
Still inconsistent

**Comment by ChanYiLin** [comment] 2024-01-09 07:43
Consider Volume Clone(with partition recreation) works but BackingImage export(with partition recreation) doesn't.
I am thinking somehow the partition information are not correctly export when exporting with BackingImage

The only difference between Volume Clone and BackingImage export is that when 
doing preload() to build `replica.volume.Location`
```
replica.volume.location = array of sectorIndex -> diskIndex
```

Volume Clone won't consider BackingIamge index in this case, so the export won't export BackingImage data
BackingImage Export will consider BackingImage when the sector has no new data, so it will export BackingImage data

**Comment by shuo-wu** [comment] 2024-01-10 04:40
> Volume Clone won't consider BackingIamge index in this case, so the export won't export BackingImage data
BackingImage Export will consider BackingImage when the sector has no new data, so it will export BackingImage data

Sorry...? Do you mean that VolumeExport won't retrieve the backing image fiemap/sector list hence the BackingImage data won't be exported? But why does `Volume Cloning Test` get passed?

**Comment by ChanYiLin** [comment] 2024-01-10 09:12
Hi @shuo-wu 
When doing VolumeExport [here](https://github.com/longhorn/longhorn-engine/blob/master/pkg/sync/rpc/server.go#L352)

It will create a replica and preload the replica to build the r.volume.location index map
In `Volume Cloning` when doing it, since it don't clone the BackingImage, so when doing preload(), it ignore the BackingImage by init the index map with "0".
In `BackingImage Export`, it will consider BackingImage, so the preload() will init the index map with "1" which is the index of BackingImage.

Volume Clone only compressed all the Snapshots into one Snapshot and sync to the target Volume
BackingImage Export compressed all the Snapshots + BackingImage and sync to the target BackingImage

In the test, we mount the BackingImage to the Pod.
We recreate the partition and resize the filesystem and write some date

If we just do Volume Clone, then the new target Volume + Original BackingImage will be consistent
If we do BackingImage Export, then the new empty Volume + New BackingImage will be inconsistent

**Comment by shuo-wu** [comment] 2024-01-10 09:30
Does the [volume clone test](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1882478530) and [the failed backing image test](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1882496551) mean that the new partitioning info can be cloned correctly via `VolumeClone` but cannot be exported via `ExportingBackingImage`?

**Comment by ChanYiLin** [comment] 2024-01-10 09:34
Yes, that is what I observed here.

**Comment by ChanYiLin** [comment] 2024-01-10 10:04
I am thinking if it is because 
```
assuming snapshot chain as follow
0. nil
1. BackingImage [1, 1, 0, 0]
2. Snap1 [1, 0, 0, 1]


Case 1 - Volume Clone: Export without BackingImage
first init to all 0, location = [0, 0, 0, 0]
r.volumes.preload(), location:
i = 0, nil                          skip => location = [0, 0, 0, 0]
i = 1, BackingImage [1, 1, 0, 0],   skip => location = [0, 0, 0, 0]
i = 2, Snap1        [1, 0, 0, 1]         => location = [2, 0, 0, 2]

ExportVolume and GetDataLayout=> [2, 0, 0, 2] which is [Data, Hole, Hole, Data]

Case 2 - BackingImage Export: Export with BackingImage
first init to all 1, location = [1, 1, 1, 1]
r.volumes.preload(), location
i = 0, nil                          skip => location = [1, 1, 1, 1]
i = 1, BackingImage [1, 1, 0, 0],   skip => location = [1, 1, 1, 1]
i = 2, Snap1        [1, 0, 0, 1]         => location = [2, 1, 1, 2]

ExportVolume and GetDataLayout => [2, 1, 1, 2] which is [Data, Data, Data, Data]
```

When SyncContent(), we actually check if the sector is Data or Hole by checking if the DiskIndex is 0 or non-0
So in the Case 1, we still punch hole when for sector 2, 3
But in the Case 2, since we init the index map to all "1", so all the sector is Data, we don't do punch hole. Then there might have some sector should be Hole because it don't have data in BackingImage either, but we fill the sector with 0 instead of Hole?

[GetDataLayout()](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/replica.go#L1446) 

cc @shuo-wu @PhanLe1010

**Comment by shuo-wu** [comment] 2024-01-10 11:01
The question is, in case 2, `location = [2, 1, 1, 2]` means [reading data in snap1, reading data in BI, reading data in BI, reading data in snap1 ]. And reading data from BI should get the same result, which is a bunch of zero. In other words, the final data set should be identical...

**Comment by ChanYiLin** [comment] 2024-01-10 11:55
Yeah so the problem is still
Why the partition info is not exported or is corrupted during exporting BackingImage…

**Comment by PhanLe1010** [comment] 2024-01-11 00:32
This example assumes that the logical (virtual) size of the backing image is equal to the logical size of snapshot:
```
assuming snapshot chain as follow
0. nil
1. BackingImage [1, 1, 0, 0]
2. Snap1 [1, 0, 0, 1]


Case 1 - Volume Clone: Export without BackingImage
first init to all 0, location = [0, 0, 0, 0]
r.volumes.preload(), location:
i = 0, nil                          skip => location = [0, 0, 0, 0]
i = 1, BackingImage [1, 1, 0, 0],   skip => location = [0, 0, 0, 0]
i = 2, Snap1        [1, 0, 0, 1]         => location = [2, 0, 0, 2]

ExportVolume and GetDataLayout=> [2, 0, 0, 2] which is [Data, Hole, Hole, Data]

Case 2 - BackingImage Export: Export with BackingImage
first init to all 1, location = [1, 1, 1, 1]
r.volumes.preload(), location
i = 0, nil                          skip => location = [1, 1, 1, 1]
i = 1, BackingImage [1, 1, 0, 0],   skip => location = [1, 1, 1, 1]
i = 2, Snap1        [1, 0, 0, 1]         => location = [2, 1, 1, 2]

ExportVolume and GetDataLayout => [2, 1, 1, 2] which is [Data, Data, Data, Data]
```

In reality, they are not:
* The ubuntu image has 2.2 GiB logical size:
    ```
    ➜  Downloads qemu-img info jammy-server-cloudimg-amd64.img 
    image: jammy-server-cloudimg-amd64.img
    file format: qcow2
    virtual size: 2.2 GiB (2361393152 bytes)
    disk size: 642 MiB
    cluster_size: 65536
    Format specific information:
        compat: 0.10
        compression type: zlib
        refcount bits: 16
    ```
* While the Longhorn snapshot has 10GB logical size 

Revisiting 2 cases:
1. mount the BackingImage to the Pod + write some data => Export BackingImage is consistent
    -> In this case, all the write fall into the first 2.2GB region of the backing image file
1. mount the BackingImage to the Pod + recreate partition&resizefs + write some data => Export BackingImage is inconsistent and the filesystem is corrupted
    -> In this case, some data might fall outside of the 2.2GB region of the backing image file. So something like:
    ```
    assuming snapshot chain as follow
    0. nil
    1. BackingImage [1, 1, 0, 0]
    2. Snap1        [1, 0, 0, 1, 0, 1, 0]
    ```
   I am wondering if reading data from the qcow2 backing image outside of its virtual size can cause any consistency? Could we test with a raw backing image instead to see if we can hit the same issue @ChanYiLin ?

**Comment by PhanLe1010** [comment] 2024-01-11 02:40
An other testing idea I am thinking about is:
1. Create an empty qcow2/raw image file of 1MB
1. Create a volume with that backing image and the volume size is 16MB
1. Write some data at the 2MB offset to the volume
1. Exporting the backing image from the volume
1. Read and compare the data from newly exported backing image and the old volume. Which regions of the data are different?

**Comment by ChanYiLin** [comment] 2024-01-11 03:51
Hi @PhanLe1010 
Thanks for the advice! Here is the testing results

## BackingImage Export (use raw image) - FAILED
1. Create a raw image (I convert the jammy image from qcow2 to raw) and a Volume with it
2. Mount to the Pod
3. `fdisk` recreate the partition and `resize2fs` to resize the filesystem
4. Mounting device and writing I/O into it
    - $ mkdir /data; $ mount -t ext4 /dev/sdb1 /data
    - $ dd if=/dev/zero of=/data/file bs=1M count=2048
    - $ sync
5. Export the Volume to another BackingImage
6. Create a Volume with the BackingImage

### Two file sizes are slightly different
```
root@kworker2:/var/lib/longhorn# du -sm replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/*
1	replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/revision.counter
0	replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/volume-head-001.img
1	replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/volume-head-001.img.meta
2141	replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/volume-snap-test-export-806bbe7b.img
1	replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/volume-snap-test-export-806bbe7b.img.meta
1	replicas/pvc-b334ec5f-ab8f-4285-bffe-743b542ec494-9a715c65/volume.meta

root@kworker2:/var/lib/longhorn# du -sm backing-images/test-raw-61fde503/*
1517	backing-images/test-raw-61fde503/backing
1	backing-images/test-raw-61fde503/backing.cfg

root@kworker2:/var/lib/longhorn# du -sm backing-images/test-export-c504be3c/*
3868	backing-images/test-export-c504be3c/backing
1	backing-images/test-export-c504be3c/backing.cfg
```

### Attach two volume to the host and the cksum are not the same
```
root@kworker2:/dev/longhorn# ll
total 0
drwxr-xr-x  2 root root    80 Jan 11 03:24 ./
drwxr-xr-x 20 root root  4260 Jan 11 03:24 ../
brw-rw----  1 root root 8, 32 Jan 11 03:24 pvc-6a0211dd-09d8-4bb7-a95e-d054988dd958
brw-rw----  1 root root 8, 16 Jan 11 03:17 pvc-b334ec5f-ab8f-4285-bffe-743b542ec494
root@kworker2:/dev/longhorn# cksum pvc-b334ec5f-ab8f-4285-bffe-743b542ec494 
969496369 5368709120 pvc-b334ec5f-ab8f-4285-bffe-743b542ec494
root@kworker2:/dev/longhorn# cksum pvc-6a0211dd-09d8-4bb7-a95e-d054988dd958
2208768380 5368709120 pvc-6a0211dd-09d8-4bb7-a95e-d054988dd958
```

### Exported BackingImage with the Volume has no filesystem corrupted issue
```
root@block-volume-test:/# ls -al /dev/os-export 
brw-rw---- 1 root root 8, 32 Jan 11 03:35 /dev/os-export
root@block-volume-test:/# ls -al /dev/sdc       
brw-rw---- 1 root disk 8, 32 Jan 11 03:35 /dev/sdc
root@block-volume-test:/# e2fsck -c /dev/sdc1
e2fsck 1.46.5 (30-Dec-2021)
Checking for bad blocks (read-only test): done                                                 
cloudimg-rootfs: Updating bad block inode.
Pass 1: Checking inodes, blocks, and sizes
Pass 2: Checking directory structure
Pass 3: Checking directory connectivity
Pass 4: Checking reference counts
Pass 5: Checking group summary information

cloudimg-rootfs: ***** FILE SYSTEM WAS MODIFIED *****
cloudimg-rootfs: 73666/645120 files (0.0% non-contiguous), 949441/1282299 blocks
```

### The data written in to the device are the same
```
root@block-volume-test:/# mkdir /data
root@block-volume-test:/# mkdir /data-export
root@block-volume-test:/# mount -t ext4 /dev/sdb1 /data
root@block-volume-test:/# mount -t ext4 /dev/sdc1 /data-export
root@block-volume-test:/# cksum /data/file
2532515601 2147483648 /data/file
root@block-volume-test:/# cksum /data-export/file
2532515601 2147483648 /data-export/file
```

### Conclusion
- With using raw image, two volumes are still not consistent, and the size are different but almost the same.
- The filesystem in this case is not corrupted

**Comment by ChanYiLin** [comment] 2024-01-11 03:55
> An other testing idea I am thinking about is:
> 
> 1. Create an empty qcow2/raw image file of 1MB
> 2. Create a volume with that backing image and the volume size is 16MB
> 3. Write some data at the 2MB offset to the volume
> 4. Exporting the backing image from the volume
> 5. Read and compare the data from the newly exported backing image and the old volume.
>    
>    1. Which regions of the data are different?
>    2. Does the newly exported backing image contain all zero? -> If yes, it means the backing image layer overwrite the snapshot layer?

Hi @PhanLe1010 
Thanks for the idea, I will try
But we have confirmed that using qcow2 image,
if we directly mount the filesystem, without recreating the partition, the exported BackingImage will be consistent.
[Here](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1882527816) is the test case

**Comment by PhanLe1010** [comment] 2024-01-11 04:01
> Thanks for the idea, I will try
But we have confirmed that using qcow2 image,
if we directly mount the filesystem, without recreating the partition, the exported BackingImage will be consistent.
Here is the test case


I think the new test idea is different than the consistent test case because the new test idea does write data to outside of the backing image boundary (similar to when you recreating the partition and resize the filesystem to be bigger than the virtual size of the backing image). WDYT?

**Comment by ChanYiLin** [comment] 2024-01-11 05:46
Hi @PhanLe1010 I think you are right

## Backing Image Export Test (using empty raw image with larger volume size) - FAILED

- Create a empty raw image and upload as a BackingImage **empty-raw**
    - $ truncate -s 2M empty-raw
- Create a 16MB Volume **test-empty** with the raw image
- Attach to the host
- dd 1MB data starts from 3MB offset
    - $ dd of=/dev/longhorn/test-empty if=/dev/urandom bs=1M count=1 oflag=seek_bytes seek=3145728
- export the Volume to another BackingImage **empty-raw-export**
- Create a 16MB Volume **test-empty-export** with the BackingImage **empty-raw-export**
- Attach to the host

### Test Result
`test-empty-export` is empty
and the comparison result shows that it dffers from 3MB offset
```
brw-rw----  1 root root 8, 48 Jan 11 05:35 test-empty
brw-rw----  1 root root 8, 64 Jan 11 05:36 test-empty-export
root@kworker1:/dev/longhorn# cat test-empty-export
root@kworker1:/dev/longhorn# cmp test-empty test-empty-export
test-empty test-empty-export differ: byte 3145729, line 1
root@kworker1:/dev/longhorn# 
```

**Comment by ChanYiLin** [comment] 2024-01-11 05:49
This is actually fit the testing results from @WebberHuang1118 [testing](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530)
The [cmp.log](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1782369530) he provided also showed that the different bytes started after 2.2GB which is the size of the jammy ubuntu image.
And the differences were also because those values were now "0"

**Comment by PhanLe1010** [comment] 2024-01-11 06:01
Awesome. It means somehow the region outside of the backing image boundary (3MB offset to 4MB offset region) in the backing image layer is overwriting the snapshot layer. 

Maybe next step would be adding some logs to the preload() function to see if we can identify the fault logic (why choosing the backing image layer instead of snapshot layer for the region 3MB-4MB)?

**Comment by ChanYiLin** [comment] 2024-01-11 06:06
I did intentionally print the r.volume.location after the preload and also print the segments sending during the exporting
Here is the results
![Screenshot from 2024-01-11 14-00-46](https://github.com/longhorn/longhorn/assets/7100904/c28712b8-c7a3-4398-bc71-2eaa347a2844)

As you can see the preload location I think is correct, there is a series of 2 which means the data from the snapshot
But when doing exporting, it only sent one segment [D 0 4096]
Note: I add the log message [here](https://github.com/longhorn/sparse-tools/blob/master/sparse/client.go#L270), this function will be executed by multiple goroutine in parallel when sending segment

**Comment by PhanLe1010** [comment] 2024-01-11 06:24
Sorry @ChanYiLin. I will have to continue tomorrow.

**Comment by ChanYiLin** [comment] 2024-01-11 06:24
sure no problem, thanks for your help!
I think we are pretty close to the answer

**Comment by ChanYiLin** [comment] 2024-01-11 09:19
it seems the preload result and the sending segment intervals are correct
now the problem might happen in reading the data with the given segments?

**Comment by PhanLe1010** [comment] 2024-01-12 02:37
Interesting finding @ChanYiLin ! 

> Event it was reading [2MB, 4MB] position from the replicas, the data is all 0

What about when cloning, ReadAt() also returns all 0 in the region [2MB, 4MB] ?

**Comment by ChanYiLin** [comment] 2024-01-12 03:09
@PhanLe1010 you can search `[DEBUG in syncDataInterval]: Sending batch: [     512:    1024](512), dataBuffer:` in the file
that is the data sending from the sorce volume the target volume

Since the sending batch size is 2MB and the sector size is 4KB so the  [     512:    1024] means [2MB: 4MB]

**Comment by ChanYiLin** [comment] 2024-01-12 03:15
Data only exists in [3MB: 4MB]
As you can see from the previous test, the whole [2MB:4MB] data sending is "0" 

But Here is the result of using clone
The result of preload location is correct and the when sending the batch, it is sending `Sending batch: [     768:    1024](256)` exactly 1MB because [2MB: 3MB] is Hole now, it didn't even try to read from that offest
and the result is correct
[lhim1_new3.txt](https://github.com/longhorn/longhorn/files/13911116/lhim1_new3.txt)

**Comment by ChanYiLin** [comment] 2024-01-15 11:45
I think I found the bug
When reading [2MB-4MB] from the Volume
```
[2MB-3MB] is BackingImage
[3MB-4MB] is snap1
```

https://github.com/longhorn/longhorn-engine/blob/deb8b18a1558ddf4f359146b289d5469bef7cc6d/pkg/replica/diff_disk.go#L202-L241
Here when we try to read the data
- If the target disk is out of bound, it could because of Volume Expansion or BackingImage.
    - In this case the preload location indicated that [2MB-3MB] is BackingImage and tried to read from it.
- Then we will directly return 0 count because we failed to read any data to the `buf`
```
	// May read the expanded part
	if offset >= size {
		return 0, nil
	}
```
- For [3MB-4MB], the target disk is correct, and we read the data from snap1 to the buf and the count would be 1MB
- But we **cut the return buf with count** after reading from the file here. So the return data abandoned the data we read from the snap1 and only leave the first half of "0" data.
```
func ReadDataInterval(rw ReaderWriterAt, dataInterval Interval) ([]byte, error) {
	data := AllocateAligned(int(dataInterval.Len()))
	n, err := rw.ReadAt(data, dataInterval.Begin)
	if err != nil {
		if err == io.EOF {
			log.Debugf("Have read at the end of file, total read: %d", n)
		} else {
			log.WithError(err).Errorf("Failed to read interval %+v", dataInterval)
			return nil, errors.Wrapf(err, "failed to read interval %+v", dataInterval)
		}
	}
	return data[:n], nil
}
```

I wonder do we really need to cut it with count?  

cc @shuo-wu @PhanLe1010 @WebberHuang1118

**Comment by ChanYiLin** [comment] 2024-01-16 05:08
By not cutting the data `data[:n]`
The Volume are now consistent even testing with the original [Test Case](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1880453217)

**Comment by shuo-wu** [comment] 2024-01-16 10:44
Agreeing with removing the cut for `ReadDataInterval`. 

On the other hand, I am thinking if we need to improve `diffDisk.fullReadAt` result asl well. 
In the above case, we try to read data [2MB, 4MB], then `diffDisk` tells us the read count is 1MB. Intuitively users will consider that the read content is at the begin of the buffer then they will discard the latter 1MB. But actually NO...
What we can improve here is: When we read a data interval like `[out of bound part of the backing image/smaller snapshot,data, out of bound part of the backing image/smaller snapshot]`, the returned read length should be `len([out of bound part of the backing image/smaller snapshot, data])` rather than `len([data])`

**Comment by ChanYiLin** [comment] 2024-01-16 13:45
From my perspective, I think we should still return `len([data])` for `diffDisk.fullReadAt`
The reason is that, from the caller's perspective, it is reading from the `"Volume"`
```
func (r *Replica) ReadAt(buf []byte, offset int64) (int, error) {
	r.RLock()
	c, err := r.volume.ReadAt(buf, offset) // which will call diffDisk.fullReadAt()
	r.RUnlock()
	return c, err
}
```
So it has no knowledge about the snapshot chain underneath.

If it reads outside of the boundary of the `"Volume"`, we do return `io.ErrUnexpectedEOF` error [here](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/diff_disk.go#L235)
But if it only reads outside of the boundary of `"specific snapshot image"`, and we allow it to do so, then we should consider it as reading a bunch of "0", and that is also true. The caller does get a bunch of "0". 
The caller should not take care of the situation. Instead it might get confused that it doesn't get EOF error but how come the data length is not correct.

**Comment by shuo-wu** [comment] 2024-01-17 03:04
After discussing with @ChanYiLin, we agree that Longhorn should return the length the caller wants to read if there is no error `EOF`

**Comment by chriscchien** [comment] 2024-01-18 13:18
Hi @ChanYiLin ,

Following test [steps](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1880453217), this issue verified pass on master-head, but in v1.6.x-head, the two backing image data were still not consistent.

The measter-head engine images build time is later then v1.6.x-head,  not sure if this means that v1.6.x engine does not contain your fix, could you help to check? thank you.
```bash
> docker images
REPOSITORY                   TAG           IMAGE ID       CREATED       SIZE
longhornio/longhorn-engine   master-head   16d097e2f0e6   4 hours ago   343MB
longhornio/longhorn-engine   v1.6.x-head   1c7202bbd25e   5 hours ago   343MB

```

**Comment by innobead** [comment] 2024-01-18 13:21
@chriscchien 1.6 PR was just merged, so please wait for https://drone-publish.longhorn.io/longhorn/longhorn-engine/810 finished.

**Comment by chriscchien** [comment] 2024-01-19 01:22
Verified **pass** on longhorn master(longhorn-engine `ac4748`), longhorn v1.6.x(longhorn-engine `0b553a`) with test [steps](https://github.com/longhorn/longhorn/issues/6899#issuecomment-1880453217)

I could reproduce this issue before the fix, after the fix, the two volumes data are identical.

**Closed by chriscchien** 2024-01-19 01:22 UTC
Labels: kind/bug, priority/0, area/backing-image, require/qa-review-coverage, require/backport, backport/1.4.5, backport/1.5.4
