### ISSUE TITLE
[BUG] Can not delete type=`bi` VolumeSnapshot if related backing image not exist

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6266] opened 2023-07-10 02:40 UTC
## Describe the bug (🐛 if you encounter this issue)

Delete type=`bi` VolumeSnapshot will stuck if backing image not exist

## To Reproduce

1. Deploy the CSI snapshot CRDs and related Controller [v6.2.1](https://longhorn.io/docs/1.5.0/snapshots-and-backups/csi-snapshot-support/enable-csi-snapshot-support/)
2. Deploy Longhorn
3. Create VolumeSnapshotClass `longhorn-snapshot-vsc`
   <details>
     <summary>manifest</summary>
  
   ```yaml
        kind: VolumeSnapshotClass
        apiVersion: snapshot.storage.k8s.io/v1
        metadata:
            name: longhorn-snapshot-vsc
        driver: driver.longhorn.io
        deletionPolicy: Delete
        parameters:
            type: bi  
   ```
  </details>

4. Create VolumeSnapshotContent `test-on-demand-backing`

   <details>
     <summary>manifest</summary>
  
     ```yaml
        apiVersion: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshotContent
        metadata:
            name: test-on-demand-backing
        spec:
            volumeSnapshotClassName: longhorn-snapshot-vsc
            driver: driver.longhorn.io
            deletionPolicy: Delete
            source:
                snapshotHandle: bi://backing?backingImageDataSourceType=download&backingImage=test-bi&url=https%3A%2F%2Flonghorn-backing-image.s3-us-west-1.amazonaws.com%2Fparrot.qcow2&backingImageChecksum=bd79ab9e6d45abf4f3f0adf552a868074dd235c4698ce7258d521160e0ad79ffe555b94e7d4007add6e1a25f4526885eb25c53ce38f7d344dd4925b9f2cb5d3b  # NOQA
            volumeSnapshotRef:
                name: test-snapshot-on-demand-backing
                namespace: default
     ```
   </details>
5. Create VolumeSnapshot `test-snapshot-on-demand-backing`
   <details>
     <summary>manifest</summary>
  
     ```yaml
        apiVersion: snapshot.storage.k8s.io/v1
        kind: VolumeSnapshot
        metadata:
            name: test-snapshot-on-demand-backing
        spec:
            volumeSnapshotClassName: longhorn-snapshot-vsc
            source:
                volumeSnapshotContentName: test-on-demand-backing
     ```
   </details>
6. Delete VolumeSnapshot `test-snapshot-on-demand-backing`, the deletion stuck. (If Longhorn had a backing image named `test-bi` before execute step 6, the delete will success.)

## Expected behavior

Delete should success no matter backing image exist

## Log or Support bundle

longhorn-manager
```
time="2023-07-10T02:03:00Z" level=warning msg="HTTP handling error" error="failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
time="2023-07-10T02:03:00Z" level=error msg="Error in request: failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
10.42.0.31 - - [10/Jul/2023:02:03:00 +0000] "GET /v1/backingimages/test-bi HTTP/1.1" 500 248 "" "Go-http-client/1.1"
time="2023-07-10T02:05:08Z" level=warning msg="HTTP handling error" error="failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
time="2023-07-10T02:05:08Z" level=error msg="Error in request: failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found"
```

csi-snapshotter
```
E0710 01:55:06.791510       1 snapshot_controller_base.go:283] could not sync content "test-on-demand-backing": failed to delete snapshot "test-on-demand-backing", err: failed to delete snapshot content test-on-demand-backing: "rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [detail=, message=failed to get backing image 'test-bi': backingimage.longhorn.io \"test-bi\" not found, code=Server Error] from [http://longhorn-backend:9500/v1/backingimages/test-bi]"
```
[supportbundle_f16395ed-43c1-480c-bbb3-eec929c91479_2023-07-10T02-07-09Z.zip](https://github.com/longhorn/longhorn/files/11997084/supportbundle_f16395ed-43c1-480c-bbb3-eec929c91479_2023-07-10T02-07-09Z.zip)

## Environment

 - Longhorn version: master, v1.5.x, v1.4.x
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.3+k3s1
 - Node config
   - OS type and version: Ubuntu 22.04 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

## Additional context

https://github.com/longhorn/longhorn/issues/6231

**Comment by innobead** [comment] 2023-07-10 05:31
@chriscchien is this a regression? if yes, remember to add the regression label.

@ChanYiLin See if we can fix this in 1.4.3 or need more time on that.

**Comment by innobead** [comment] 2023-07-10 05:32
@chriscchien is this found from the daily regression? do we have a test case for it?

**Comment by chriscchien** [comment] 2023-07-10 05:57
> @chriscchien is this found from the daily regression? do we have a test case for it?

We have test case skeleton [here](https://github.com/longhorn/longhorn-tests/blob/1045840d030b34b372a8291ec7f725f6595025cb/manager/integration/tests/test_csi_snapshotter.py#L1370), the test script is under implementing.  This issue observed during test case implementing.

**Comment by innobead** [comment] 2023-07-10 06:32
Removed from 1.5.1 and 1.4.3 which will be released in near future, so this can be tackled in the following release instead.

**Comment by chriscchien** [comment] 2023-07-10 07:52
Hi @ChanYiLin,  

After execute step 5 in [reproduce steps](https://github.com/longhorn/longhorn/issues/6266#issue-1795810860), I create a PVC using VolumeSnapshot `test-snapshot-on-demand-backing`

<details>
  <summary>PVC manifest</summary>
  
  ```yaml
        apiVersion: v1
        kind: PersistentVolumeClaim
        metadata:
            name: test-restore-on-demand-backing
        spec:
            storageClassName: longhorn
            dataSource:
                name: test-snapshot-on-demand-backing
                kind: VolumeSnapshot
                apiGroup: snapshot.storage.k8s.io
            accessModes:
                - ReadWriteOnce
            resources:
                requests:
                    storage: 5Gi
  ```
</details>

I can see PVC `test-restore-on-demand-backing` and backing image `test-bi` create success.

Then I try delete volumeSnapshot `test-snapshot-on-demand-backing`, the deletion stuck and can see below log in longhorn-manager. Looks like delete a type='bi 'Volumesnapshot will also need to delete related backing image. In this case, backing image was used by replica make the deletion stuck. And I am wondering if you can help confirm if this is correct behavior, thank you.
```
10.42.1.90 - - [10/Jul/2023:07:13:44 +0000] "GET /v1/backingimages/test-bi HTTP/1.1" 200 954 "" "Go-http-client/1.1"
time="2023-07-10T07:13:44Z" level=warning msg="Rejected operation: Request (user: system:serviceaccount:longhorn-system:longhorn-service-account, longhorn.io/v1beta2, Kind=BackingImage, namespace: longhorn-system, name: test-bi, operation: DELETE)" error="cannot delete backing image test-bi since there are replicas using it" service=admissionWebhook
time="2023-07-10T07:13:44Z" level=warning msg="HTTP handling error" error="failed to delete backing image: admission webhook \"validator.longhorn.io\" denied the request: cannot delete backing image test-bi since there are replicas using it"
time="2023-07-10T07:13:44Z" level=error msg="Error in request: failed to delete backing image: admission webhook \"validator.longhorn.io\" denied the request: cannot delete backing image test-bi since there are replicas using it"
```

**Comment by ChanYiLin** [comment] 2023-07-10 08:19
Hi @chriscchien 
Yes this is expected.
Delete volumeSnapshot will also delete the corresponding backing image
If the backing image is being used, then it cannot be deleted

**Comment by ChanYiLin** [comment] 2023-07-10 08:39
Oh I found the reason why it failed
- In csi, before deleting the backing image, it will get the backing image through api (not datastore)
in `generated_client`
```
func (c *BackingImageClient) ById(id string) (*BackingImage, error) {
	resp := &BackingImage{}
	err := c.rancherClient.doById(BACKING_IMAGE_TYPE, id, resp)
	if apiError, ok := err.(*ApiError); ok {
		if apiError.StatusCode == 404 {
			return nil, nil
		}
	}
	return resp, err
}
```
we do check if it is not found (404) and return nil
- However, in server part, we raise 500 error with backing image not found
```
func (s *Server) BackingImageGet(rw http.ResponseWriter, req *http.Request) error {
	apiContext := api.GetApiContext(req)

	id := mux.Vars(req)["name"]

	bi, err := s.m.GetBackingImage(id)
	if err != nil {
		return errors.Wrapf(err, "failed to get backing image '%s'", id)
	}

	apiContext.Write(toBackingImageResource(bi, apiContext))
	return nil
}
```

So the csi failed to process because of the error.

**Comment by ChanYiLin** [comment] 2023-07-10 08:51
It seems backup type snapshot will have the same issue
If someone delete the backupVolume which is created by the volumesnapshot through UI
Then one can't delete the volumesnapshot after as well

**Comment by ChanYiLin** [comment] 2023-07-10 08:56
Hi @innobead 
there is no need to backport to 1.3.X and 1.4.X since backing image with csi feature is only introduced in `v1.5.x`
thanks!

**Comment by shuo-wu** [comment] 2023-07-10 13:09
Good finding! I think there are similar issues for other APIs/resources. Should we update them later?

BTW, why do we remove tag `backport/v1.5.1`?

**Comment by innobead** [comment] 2023-07-10 14:57
Need to fix in 1.5.1, since it's a minor fix now.

**Comment by innobead** [comment] 2023-07-10 14:59
> Good finding! I think there are similar issues for other APIs/resources. Should we update them later?
> 
> 
> 
> BTW, why do we remove tag `backport/v1.5.1`?

About this, can we do a middle layer to handle this error in general for all API calls? @ChanYiLin @shuo-wu (we can handle it later separately if need more time and it seems like a known issue instead of a regression)

**Comment by ChanYiLin** [comment] 2023-07-11 04:00
@innobead 
return 404 not found is api server implementation
from client it is quite hard to analyze the error, unless we check the error message, but then we need to unify the error message from server

Currently I don't have any idea for this middle layer

cc @shuo-wu

**Comment by ChanYiLin** [comment] 2023-07-11 04:32
Hi @chriscchien 
I have also fixed the same issue in type `bak` and `snap` VolumeSnapshot and update the test steps.
Thanks!

**Comment by innobead** [comment] 2023-07-11 04:53
> @innobead return 404 not found is api server implementation from client it is quite hard to analyze the error, unless we check the error message, but then we need to unify the error message from server
> 
> Currently I don't have any idea for this middle layer
> 
> cc @shuo-wu

What I mean is not client side but server side, like add your change in the below code in general to handle for all endpoint functions. WDYT?

[/api/router.go#L16-L24](https://github.com/longhorn/longhorn-manager/blob/fedfefc273086b8f0425d07c8fe26b510683284a/api/router.go#L16-L24)
```go
func HandleError(s *client.Schemas, t HandleFuncWithError) http.Handler {
	return api.ApiHandler(s, http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
		if err := t(rw, req); err != nil {
                    if datastore.ErrorIsNotFound(err) {
		        rw.WriteHeader(http.StatusNotFound)
		    }

		    logrus.WithError(err).Warnf("HTTP handling error")
		    apiContext := api.GetApiContext(req)
		    apiContext.WriteErr(err)
		}
	}))
}
```

**Comment by innobead** [comment] 2023-07-11 04:58
However, from my view, this is not a perfect solution because it seems we are relying on go-rancher lib which has some limitations. The perfect solution should be to have the same payload structure for any error users hit. 

The below code has the limitation I mentioned w/the hard-coded status code.

[/vendor/github.com/rancher/go-rancher/api/writer.go#L16-L30](https://github.com/longhorn/longhorn-manager/blob/fedfefc273086b8f0425d07c8fe26b510683284a/vendor/github.com/rancher/go-rancher/api/writer.go#L16-L30)
```go
func (a *ApiContext) WriteErr(err error) {
	logrus.Errorf("Error in request: %v", err)
	a.responseWriter.WriteHeader(500)
	writeErr := a.WriteResource(&client.ServerApiError{
		Resource: client.Resource{
			Type: "error",
		},
		Status:  500,
		Code:    "Server Error",
		Message: err.Error(),
	})
	if writeErr != nil {
		logrus.Errorf("Failed to write err: %v", err)
	}
}
```

**Comment by ChanYiLin** [comment] 2023-07-11 05:19
Oh I got it
Yeah 

> > @innobead return 404 not found is api server implementation from client it is quite hard to analyze the error, unless we check the error message, but then we need to unify the error message from server
> > Currently I don't have any idea for this middle layer
> > cc @shuo-wu
> 
> @ChanYiLin What I mean is not client side but server side, like add your change in the below code in general to handle for all endpoint functions. WDYT?
> 
> [/api/router.go#L16-L24](https://github.com/longhorn/longhorn-manager/blob/fedfefc273086b8f0425d07c8fe26b510683284a/api/router.go#L16-L24)
> 
> ```go
> func HandleError(s *client.Schemas, t HandleFuncWithError) http.Handler {
> 	return api.ApiHandler(s, http.HandlerFunc(func(rw http.ResponseWriter, req *http.Request) {
> 		if err := t(rw, req); err != nil {
>                     logrus.WithError(err).Warnf("HTTP handling error")  
>                     
>                     if datastore.ErrorIsNotFound(err) {
> 		        rw.WriteHeader(http.StatusNotFound)
>                         return nil
> 		    }
> 
> 		    apiContext := api.GetApiContext(req)
> 		    apiContext.WriteErr(err)
> 		}
> 	}))
> }
> ```

I think this solution is good enough for current issue and give the right status code (404) for all not found error
For other errors, as you said, we are currently restricted by the lib.

I think we can create another issue for handling other errors

**Comment by innobead** [comment] 2023-07-11 05:21
@ChanYiLin Sounds good, please help create the issue to track it later, also I am not sure if the go-rancher has any new version w/ a related improvement. or not or even we can contribute back to it.

**Comment by ChanYiLin** [comment] 2023-07-11 05:41
@innobead 
https://github.com/longhorn/longhorn/issues/6291

**Comment by innobead** [comment] 2023-07-12 05:34
@ChanYiLin It seems PRs merged. Please remember to move it to ready for testing if all done.

**Comment by chriscchien** [comment] 2023-07-17 07:42
Verified **pass** in longhorn master(longhorn-manager `8f1205`) with test [steps](https://github.com/longhorn/longhorn/issues/6266#issuecomment-1628559658)

Delete `volumesnapshot` will not stuck when `type=bi`, `type=bak` and `type=snap`

**Closed** 2023-07-17 07:46 UTC
Labels: kind/bug, priority/0, kind/regression, area/csi, severity/2, area/backing-image, area/snapshot, backport/1.5.1
