### ISSUE TITLE
[BUG] longhorn upgrade is not upgrading engineimage

### ISSUE THREAD

**Issue by mynktl** [longhorn/longhorn#5740] opened 2023-04-12 06:15 UTC
## Describe the bug (🐛 if you encounter this issue)
I am upgrading longhorn from 1.2.2 to 1.3.1.  I have set `concurrent-automatic-engine-upgrade-per-node-limit` to 1. After upgrading, there are few engineimages which still remains on 1.2.2. I have tried increasing concurrent upgrade limit to 5 also, but observing same behaviour, Although `engineimages` is getting deployed successfully on all nodes.

## To Reproduce
Install 1.2.2. Create longhorn volumes more than 10. Upgrade longhorn to 1.3.1

## Expected behavior
All engines should be upgraded.

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: RHEL
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 13

**Comment by mynktl** [comment] 2023-04-12 06:19
[longhorn-support-bundle_5d68d7b0-aa45-4a06-b8d8-ae10c25e4c17_2023-04-12T06-16-03Z.zip](https://github.com/longhorn/longhorn/files/11207815/longhorn-support-bundle_5d68d7b0-aa45-4a06-b8d8-ae10c25e4c17_2023-04-12T06-16-03Z.zip)
Support-bundle

**Comment by c3y1huang** [comment] 2023-04-12 08:50
It appears that the `default-disk-fd0400000000` on `agent3` scheduling is currently disabled. Could you please enable it, or remove any stopped replicas on agent3?

Note: the [node IDs are empty](https://github.com/longhorn/longhorn-manager/blob/v1.3.1/controller/volume_controller.go#L2326) on those replicas leading to upgrade failures: [CheckEngineImageReadiness: nodes [] don't have the engine image](https://github.com/longhorn/longhorn-manager/blob/v1.3.1/datastore/longhorn.go#L1386).

**Comment by mynktl** [comment] 2023-04-12 10:14
Hi @c3y1huang 
Thanks for reply.
I tried that and it is still giving the same error. I am seeing this error for other replicas also which are running on nodes having disk.
```
[root@server0 ~]# kubectl get replicas -n longhorn-system |grep pvc-ee8a7095-1e6d-4d8d-bac2-545a3f30d46c
pvc-ee8a7095-1e6d-4d8d-bac2-545a3f30d46c-r-6aba64bc   running   server0   ceb573c2-5cdf-414d-97a8-87cf7662bae9   instance-manager-r-43d27d07   sfbrdevhelmweacr.azurecr.io/longhornio/longhorn-engine:v1.2.2   13h
pvc-ee8a7095-1e6d-4d8d-bac2-545a3f30d46c-r-8b9ec4b9   running   server2   3d1c5500-2378-444e-9b39-6fc99168f2ab   instance-manager-r-23904f36   sfbrdevhelmweacr.azurecr.io/longhornio/longhorn-engine:v1.2.2   14h
[root@server0 ~]# kubectl get engines -n longhorn-system |grep pvc-ee8a7095-1e6d-4d8d-bac2-545a3f30d46c
pvc-ee8a7095-1e6d-4d8d-bac2-545a3f30d46c-e-9c8248d3   running   server2   instance-manager-e-45a58b0d   sfbrdevhelmweacr.azurecr.io/longhornio/longhorn-engine:v1.2.2   14h
```

**Comment by c3y1huang** [comment] 2023-04-13 01:49
@shuo-wu , any ideas?

**Comment by shuo-wu** [comment] 2023-04-13 04:07
Checked volume `pvc-2b681d80-52bc-46e5-a87a-2001d877bd84`
I don't know why this volume is healthy but contains an unscheduled replica. But I think this unscheduled replica (with empty node ID) is the culprit: When [the function](https://github.com/longhorn/longhorn-manager/blob/338782758fcf273d2c2a4481d39eaf4d84b3417b/datastore/longhorn.go#L1364) checks if the nodes of all replicas (`nodes`) have the corresponding engine image, the empty node ID of course does not in the engine image deploy list (`nodesHaveEngineImage`). Then Longhorn print out this kind of misleading log:
```
2023-04-12T05:53:19.791439128Z time="2023-04-12T05:53:19Z" level=warning msg="Engine live upgrade from sfbrdevhelmweacr.azurecr.io/longhornio/longhorn-engine:v1.2.2, but the image wasn't ready" accessMode=rwo controller=longhorn-volume engine=pvc-2b681d80-52bc-46e5-a87a-2001d877bd84-e-e7d696a7 error="<nil>" frontend=blockdev migratable=false node=agent3 owner=agent3 state=attached volume=pvc-2b681d80-52bc-46e5-a87a-2001d877bd84 volumeDesiredEngineImage="sfbrdevhelmweacr.azurecr.io/longhornio/longhorn-engine:v1.3.1"
```

**Comment by c3y1huang** [comment] 2023-04-13 04:47
@mynktl , in summary:
1. Try to solve the empty nodeID issue with [this comment](https://github.com/longhorn/longhorn/issues/5740#issuecomment-1504901468).
1. Make the volumes healthy as @shuo-wu [mentioned](https://github.com/longhorn/longhorn/issues/5740#issuecomment-1506312496).

Please provide a new support bundle if still doesn't work for you.

**Comment by mynktl** [comment] 2023-04-18 06:45
Hi @c3y1huang  @shuo-wu 
I am attaching a new bundle from another environment where I am seeing this issue.

In this, I am seeing issue with 5 volumes out of which 1 is healthy and remaining 4 are degraded (Its been more than 12hr still not able to complete rebuilding). All these volumes have replica in running state also.

[longhorn-support-bundle_80570984-c26d-474b-9ff3-51fc7f4fafa3_2023-04-18T06-39-42Z.zip](https://github.com/longhorn/longhorn/files/11258732/longhorn-support-bundle_80570984-c26d-474b-9ff3-51fc7f4fafa3_2023-04-18T06-39-42Z.zip)

Is there any way to make this volume healthy?

**Comment by c3y1huang** [comment] 2023-04-18 08:46
Possibly because the disk scheduling is disabled on agent3?
```
    name: agent3
    disks:
      default-disk-fd0400000000:
        path: /datadisk
        allowscheduling: false
        evictionrequested: false
        storagereserved: 641099366
        tags: []
```

**Comment by mynktl** [comment] 2023-04-18 10:07
I am not sure about that. I think that should not cause any issue since disk scheduling is configurable and all replicas are in running state.

**Comment by innobead** [comment] 2023-04-25 06:56
It seems it's unable to find the reproduce way, so see if live upgrade w/o any issues, is good enough, @shuo-wu ?

**Comment by shuo-wu** [comment] 2023-04-25 09:20
Sure. Will we close this issue then?

**Comment by innobead** [comment] 2023-04-25 09:40
Let's close this after QA verify the related auto e2e test cases.

cc @longhorn/qa

**Comment by chriscchien** [comment] 2023-04-27 03:32
Close this ticket, in recent build of longhorn master head test pipeline, engine upgrade test  did not encounter issue. Below is restult for reference:

- Upgrade form v1.2.6 to v1.3.2 to master-head, did not see outstanding issue in `test_engine_upgrade`
   - Build [155](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/155/testReport/tests/test_engine_upgrade/)
   - Build [156](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/156/testReport/tests/test_engine_upgrade/)
   - Build [157](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-2-stage-upgrade-tests-sles-amd64/157/testReport/tests/test_engine_upgrade/)

- Upgrade from v1.2.6 to master-head, did not see outstanding issue in `test_engine_upgrade`
   - Build [443](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/443/testReport/tests/test_engine_upgrade/)
   - Build [444](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/444/testReport/tests/test_engine_upgrade/)
   - Build [445](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-upgrade-tests-sles-amd64/445/testReport/tests/test_engine_upgrade/)

**Closed by chriscchien** 2023-04-27 03:32 UTC
Labels: kind/bug, area/manager, reproduce/rare, area/volume-upgrade, backport/1.4.2, backport/1.3.4
