### ISSUE TITLE
[BUG] Unable to attach restored `encrypted` pvc

### ISSUE THREAD

**Issue by BhautikChudasama** [longhorn/longhorn#9571] opened 2024-10-04 11:49 UTC
## Describe the bug
I had enabled the encrypted volume setup, in which i am taking the scheduled backup, and testing restoration of the encrypted backup. Backup is successful but it fails to restore on node mount. Here are the CSI manager logs
```
longhorn-csi-plugin time="2024-10-04T11:40:44Z" level=error msg="NodeStageVolume: err: rpc error: code = InvalidArgument desc = missing passphrase for encrypted volume pvc-96af543d-276a-451f-9ec7-ef48171f8fa8" func=csi.logGRPC file="server.go:138"                                                                                                                                                            │
```

Here is the StorageClass
```
apiVersion: v1
kind: Secret
metadata:
  name: longhorn-secret
  namespace: longhorn
stringData:
  CRYPTO_KEY_VALUE: "ACTUAL_SECRET"
  CRYPTO_KEY_PROVIDER: "secret"
---
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: internal
provisioner: driver.longhorn.io
allowVolumeExpansion: true
parameters:
  fromBackup: ""
  encrypted: "true"
  # global secret that contains the encryption key that will be used for all volumes
  csi.storage.k8s.io/provisioner-secret-name: "longhorn-secret"
  csi.storage.k8s.io/provisioner-secret-namespace: "longhorn"
  csi.storage.k8s.io/node-publish-secret-name: "longhorn-secret"
  csi.storage.k8s.io/node-publish-secret-namespace: "longhorn"
  csi.storage.k8s.io/node-stage-secret-name: "longhorn-secret"
  csi.storage.k8s.io/node-stage-secret-namespace: "longhorn"
  numberOfReplicas: "1"
  staleReplicaTimeout: "30"
  fsType: "ext4"
  migratable: "true"
  dataLocality: "disabled"
  unmapMarkSnapChainRemoved: "ignored"
 ```

I have investigated the CSI driver, in which `NodeStage` method cannot find the secret (https://github.com/longhorn/longhorn-manager/blob/4d779074b5f10fc0253bac80a159c05f918f8b6c/csi/node_server.go#L471-L472) CSI Ref:(https://kubernetes-csi.github.io/docs/secrets-and-credentials-storage-class.html)

What I am doing wrong?

Running on: k3s (v1.30.5+k3s1)
CSI Driver Image: longhornio/csi-node-driver-registrar:v2.9.2

**Comment by c3y1huang** [comment] 2024-10-07 07:04
Weird, what is your Longhorn version?

cc @mantissahz

**Comment by BhautikChudasama** [comment] 2024-10-07 10:19
Lognhorn chart version: v1.6.2

**Comment by innobead** [comment] 2024-10-07 10:38
Do we have corresponding e2e test cases? cc @longhorn/qa

**Comment by c3y1huang** [comment] 2024-10-08 05:11
> Do we have corresponding e2e test cases? cc @longhorn/qa

AFAIK we currently don't have an e2e test case for backing up and restoring an encrypted volume.

**Comment by c3y1huang** [comment] 2024-10-08 05:45
So far I haven't been able to reproduce using the StorageClass and Secret provided in the issue description. However, I am using `longhorn-system` namespace for testing.

**Comment by BhautikChudasama** [comment] 2024-10-08 06:07
I deployed in `longhorn` namespace.

Here is my deployment, am I missing anything?

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: anvil-pv-0
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-namespace: longhorn
    volume.kubernetes.io/provisioner-deletion-secret-name: longhorn-crypto
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
spec:
  capacity:
    storage: 8Gi # must match size of Longhorn volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io # driver must match this
    fsType: ext4
    volumeAttributes:
      numberOfReplicas: "1" # must match Longhorn volume value
      staleReplicaTimeout: "30" # in minutes
    volumeHandle: pvc-96af543d-276a-451f-9ec7-ef48171f8fa8 # must match volume name from Longhorn
  storageClassName: internal # must be same name that we will use later

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: anvil-anvil-0
  namespace: development-chains
  annotations:
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi # must match size from earlier
  storageClassName: internal # must match name from earlier
  volumeName: anvil-pv-0 # must reference Persistent Volume

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: anvil
  labels:
    app: anvil
  namespace: development-chains
spec:
  serviceName: anvil
  replicas: 1
  selector:
    matchLabels:
      app: anvil
  template:
    metadata:
      labels:
        app: anvil
    spec:
      containers:
        - name: anvil
          image: image:tag
          volumeMounts:
            - name: anvil
              mountPath: /opt/state1.json
              subPath: state1.json
  volumeClaimTemplates:
    - metadata:
        name: anvil
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: "internal"
        resources:
          requests:
            storage: 8Gi
```

**Comment by c3y1huang** [comment] 2024-10-08 06:48
`volume.kubernetes.io/provisioner-deletion-secret-name: longhorn-crypto`
I guess this should match your secret name.

Could you also share your steps for restoration? Have you tried to restore using the UI?

**Comment by c3y1huang** [comment] 2024-10-08 07:00
Mine CRs for restoration looks like this:
```
# Volume

apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  creationTimestamp: "2024-10-08T06:42:37Z"
  finalizers:
  - longhorn.io
  generation: 4
  labels:
    backup-volume: pvc-ed26d10d-e6bc-44de-92d4-6ba2bd6961c1
    longhornvolume: restore
    recurring-job-group.longhorn.io/default: enabled
    setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    setting.longhorn.io/replica-auto-balance: ignored
    setting.longhorn.io/snapshot-data-integrity: ignored
  name: restore
  namespace: longhorn-system
  resourceVersion: "4080"
  uid: 0e39fdc9-1d89-48b1-8a09-5e019ed7f268
spec:
  Standby: false
  accessMode: rwo
  backendStoreDriver: ""
  backingImage: ""
  backupCompressionMethod: lz4
  dataEngine: v1
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: true
  engineImage: ""
  fromBackup: s3://backupbucket@us-east-1/?backup=backup-eb99491ebf1147f8&volume=pvc-ed26d10d-e6bc-44de-92d4-6ba2bd6961c1
  frontend: blockdev
  image: longhornio/longhorn-engine:v1.6.2
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: ip-10-0-2-136
  nodeSelector: []
  numberOfReplicas: 3
  offlineReplicaRebuilding: disabled
  replicaAutoBalance: ignored
  replicaDiskSoftAntiAffinity: ignored
  replicaSoftAntiAffinity: ignored
  replicaZoneSoftAntiAffinity: ignored
  restoreVolumeRecurringJob: ignored
  revisionCounterDisabled: false
  size: "8589934592"
  snapshotDataIntegrity: ignored
  snapshotMaxCount: 250
  snapshotMaxSize: "0"
  staleReplicaTimeout: 20
  unmapMarkSnapChainRemoved: ignored
status:
  actualSize: 0
  cloneStatus:
    snapshot: ""
    sourceVolume: ""
    state: ""
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2024-10-08T06:42:38Z"
    message: ""
    reason: ""
    status: "False"
    type: WaitForBackingImage
  - lastProbeTime: ""
    lastTransitionTime: "2024-10-08T06:42:38Z"
    message: ""
    reason: ""
    status: "False"
    type: TooManySnapshots
  - lastProbeTime: ""
    lastTransitionTime: "2024-10-08T06:42:38Z"
    message: ""
    reason: ""
    status: "True"
    type: Scheduled
  - lastProbeTime: ""
    lastTransitionTime: "2024-10-08T06:42:51Z"
    message: ""
    reason: ""
    status: "False"
    type: Restore
  currentImage: longhornio/longhorn-engine:v1.6.2
  currentMigrationNodeID: ""
  currentNodeID: ip-10-0-2-136
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: default
    pvName: restore
    pvStatus: Bound
    pvcName: anvil-anvil-0-restore
    workloadsStatus:
    - podName: anvil-restore-0
      podStatus: Running
      workloadName: anvil-restore
      workloadType: StatefulSet
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: ""
  offlineReplicaRebuildingRequired: false
  ownerID: ip-10-0-2-136
  pendingNodeID: ""
  remountRequestedAt: ""
  restoreInitiated: true
  restoreRequired: false
  robustness: healthy
  shareEndpoint: ""
  shareState: ""
  state: attached
```
```
# PV

apiVersion: v1
kind: PersistentVolume
metadata:
  annotations:
    longhorn.io/volume-scheduling-error: ""
    pv.kubernetes.io/bound-by-controller: "yes"
  creationTimestamp: "2024-10-08T06:43:04Z"
  finalizers:
  - kubernetes.io/pv-protection
  - external-attacher/driver-longhorn-io
  name: restore
  resourceVersion: "4024"
  uid: 6dd42c40-5c64-45b7-bf99-2ac3ae15e1ce
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  claimRef:
    apiVersion: v1
    kind: PersistentVolumeClaim
    name: anvil-anvil-0-restore
    namespace: default
    resourceVersion: "3146"
    uid: e84fb167-f8cf-402b-a3fc-1178c517b73f
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    nodePublishSecretRef:
      name: longhorn-secret
      namespace: longhorn-system
    nodeStageSecretRef:
      name: longhorn-secret
      namespace: longhorn-system
    volumeAttributes:
      diskSelector: ""
      encrypted: "true"
      nodeSelector: ""
      numberOfReplicas: "3"
      staleReplicaTimeout: "20"
    volumeHandle: restore
  persistentVolumeReclaimPolicy: Retain
  storageClassName: internal
  volumeMode: Filesystem
status:
  lastPhaseTransitionTime: "2024-10-08T06:43:05Z"
  phase: Bound
```
```
#PVC

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
  creationTimestamp: "2024-10-08T06:43:05Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: anvil-anvil-0-restore
  namespace: default
  resourceVersion: "3155"
  uid: e84fb167-f8cf-402b-a3fc-1178c517b73f
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 8Gi
  storageClassName: internal
  volumeMode: Filesystem
  volumeName: restore
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 8Gi
  phase: Bound
```
```
#StatefulSet

apiVersion: apps/v1
kind: StatefulSet
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"StatefulSet","metadata":{"annotations":{},"labels":{"app":"anvil"},"name":"anvil-restore","namespace":"default"},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"anvil"}},"serviceName":"anvil","template":{"metadata":{"labels":{"app":"anvil"}},"spec":{"containers":[{"image":"nginx:stable-alpine","name":"anvil"}],"volumes":[{"name":"anvil","persistentVolumeClaim":{"claimName":"anvil-anvil-0-restore"}}]}}}}
  creationTimestamp: "2024-10-08T06:52:52Z"
  generation: 1
  labels:
    app: anvil
  name: anvil-restore
  namespace: default
  resourceVersion: "4066"
  uid: d0753479-4452-4339-8135-256bac4396b1
spec:
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: Retain
    whenScaled: Retain
  podManagementPolicy: OrderedReady
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: anvil
  serviceName: anvil
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: anvil
    spec:
      containers:
      - image: nginx:stable-alpine
        imagePullPolicy: IfNotPresent
        name: anvil
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: anvil
        persistentVolumeClaim:
          claimName: anvil-anvil-0-restore
  updateStrategy:
    rollingUpdate:
      partition: 0
    type: RollingUpdate
status:
  availableReplicas: 1
  collisionCount: 0
  currentReplicas: 1
  currentRevision: anvil-restore-56867f4cd9
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updateRevision: anvil-restore-56867f4cd9
  updatedReplicas: 1
```

**Comment by BhautikChudasama** [comment] 2024-10-10 12:38
sorry for the late reply, In the backup section i just selected the encrypted backup checkbox
  
<img width="726" alt="Screenshot 2024-10-10 at 6 07 20 PM" src="https://github.com/user-attachments/assets/64e0a321-9e8d-4903-aad6-3c71ed474e43">

**Comment by c3y1huang** [comment] 2024-10-11 01:41
How did you create the PV and PVC for the restored volume?  Did you specify the `Secret Namespace` and `Secret Name`?

![Screenshot from 2024-10-11 09-37-54](https://github.com/user-attachments/assets/ab6f7a2e-a7a3-4120-9743-f111ff457041)

**Comment by BhautikChudasama** [comment] 2024-10-11 04:49
Hi @c3y1huang, I caught my mistake, i am not specifying secretRef in `PV`.

```yaml
csi:
    nodePublishSecretRef:
      name: longhorn-crypto
      namespace: longhorn
    nodeStageSecretRef:
      name: longhorn-crypto
      namespace: longhorn
```

Here is my updated YAML.
```yaml
kind: PersistentVolume
metadata:
  name: anvil-pv-0
  annotations:
    volume.kubernetes.io/provisioner-deletion-secret-namespace: longhorn
    volume.kubernetes.io/provisioner-deletion-secret-name: longhorn-crypto
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
spec:
  capacity:
    storage: 8Gi # must match the size of Longhorn volume
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  csi:
    driver: driver.longhorn.io # driver must match this
    fsType: ext4
    nodePublishSecretRef:
      name: longhorn-crypto
      namespace: longhorn
    nodeStageSecretRef:
      name: longhorn-crypto
      namespace: longhorn
    volumeAttributes:
      numberOfReplicas: "1" # must match Longhorn volume value
      staleReplicaTimeout: "30" # in minutes
    volumeHandle: pvc-96af543d-276a-451f-9ec7-ef48171f8fa8 # must match volume name from Longhorn
  storageClassName: internal # must be same name that we will use later
  ```
  
One thing I don't understand is why we need to specify `nodePublishRef` in PV, we are already giving internal storage class name in which secrets are specified, and correct me if I am wrong longhorn engine intercepts the r/w request (act as proxy), and write to replicas OR decrypt the volume while mount? I'm very keen to understand.

**Comment by c3y1huang** [comment] 2024-10-16 04:19
Doc merged. Closing issue.

**Closed by c3y1huang** 2024-10-16 04:19 UTC
Labels: kind/bug, require/doc, area/volume-backup-restore, area/volume-encryption, require/qa-review-coverage, require/backport
