### ISSUE TITLE
[BUG] Cronjob for backup with Node who has taint

### ISSUE THREAD

**Issue by obeyler** [longhorn/longhorn#1903] opened 2020-10-22 13:17 UTC
**Describe the bug**
Cron job create for longhorn backup is created without neither toleration nor node selector
If Node has taint the pod created by Cron job are ejected by Taint controler very quikly and so on is recreated and ejected again and again. (at the end we have more than 60 000 pods and  K8S crash)
![image](https://user-images.githubusercontent.com/23224162/96876914-4c61ac80-1479-11eb-948d-53cd795805d9.png)
![image](https://user-images.githubusercontent.com/23224162/96876969-5b485f00-1479-11eb-80dc-bfab5e91ccdc.png)

it's occured whereas we installed longhorn with defaultSettings.taintToleration persistence=true:NoExecute

**Expected behavior**
We need a way to add a node selector or toleration on cronjob

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18

**Additional context**
We have Node with taint for persistence and Node without Taint

**Comment by joshimoo** [comment] 2020-10-22 13:44
We should set the tolerations for the cronjob pods that are set by the user via the longhorn-settings.
related issue https://github.com/longhorn/longhorn/issues/1796

**Comment by PhanLe1010** [comment] 2020-10-27 18:23
**Reproduce steps:**
1. Create 3 nodes cluster and install Longhorn v1.0.2
2. Taint `node-1` with `persistence=true:NoExecute`. 
3. Add toleration `persistence=true:NoExecute` to Longhorn
4. Create a volume, attach to `node-1`, create a recurring job for the vol.
5. Wait until the job start, observe that there are many many pods in the recurring job.

**Comment by obeyler** [comment] 2020-10-27 19:11
Could you give the step to deactivate properly a schedule backup without UI. When the K8S is crash due to many pods created by backup the UI is not usable anymore.
I suppose that it's a CRD who store the configuration and it's not only the cronjob. Thanks by advance

**Comment by PhanLe1010** [comment] 2020-10-28 01:24
> I suppose that it's a CRD who store the configuration and it's not only the cronjob
You are correct! The Longhorn volume CRD contains the cronjob configuration. In order to deactivate properly a schedule backup without UI, you can do:
1. List all Longhorn volumes in the system:
```
kubectl get volumes.longhorn.io -n longhorn-system
```
1. Identify the volumes that are having the problematic cronjob (The volumes that are attaching to the tainted node). Let's say one of them is `vol-1`
1. Run
```
kubectl edit volumes.longhorn.io vol-1 -n longhorn-system
```
and remove all cronjob inside the field `spec.recurringJobs`, and save.

Longhorn will remove the cronjob but it will take a while before Kubernetes can delete thousands of pods and recover.

**Comment by khushboo-rancher** [comment] 2020-10-29 07:06
Verified with longhorn-master - 10/28/2020

Validation - **Pass**

The reported issue is reproducible with v1.0.2, now with in master.
The recurring job is getting succeeded on the tainted node and at given point of time there is only max 2 pods are available for the recurring jobs.

I couldn't test this on an upgraded test as I encountered an issue https://github.com/longhorn/longhorn/issues/1924

**Comment by khushboo-rancher** [comment] 2020-10-29 21:20
Verified the scenario on the upgraded set up, it is working fine. the recurring jobs are running successfully on the tainted node.
https://github.com/longhorn/longhorn/issues/1924 failed because of the large number of pods which was available in the set up.

**Comment by yasker** [comment] 2020-12-07 19:05
It's unlikely we have time for writing the automation test for this issue in v1.1.0. Let's do a regression test and then punt it to v1.1.1 release.

**Comment by PhanLe1010** [comment] 2020-12-14 19:35
Re-validated manually

**Comment by Wykiki** [comment] 2021-01-07 14:31
Is there a way to manually fix this on existing CronJob ? Like, putting the right tolerations ?
I tried to edit the failing CronJob manually (adding tolerations), but they seem to immediately get overriden by Longhorn.

**Comment by joshimoo** [comment] 2021-01-07 15:20
@Wykiki are you having this issue on v1.1? The longhorn-manager would end up overriding your custom cronjob definition.

**Comment by Wykiki** [comment] 2021-01-10 20:17
I have the issue on :
- Longhorn v1.0.2
- Kubernetes v1.14
Not possible to test on Longhorn v1.1 yet

**Comment by PhanLe1010** [comment] 2021-01-10 20:24
@Wykiki 

Unfortunately, you cannot manually  add tolerations to cronjob since manager will override it. There only 1 option in this problem that is delete the cronjob by the step mentioned in https://github.com/longhorn/longhorn/issues/1903#issuecomment-717636744

Longhorn 1.1.0 require Kubernetes 1.16 or above. So, you would need to upgrade Kubernetes first

**Comment by meldafrawi** [comment] 2021-04-16 19:05
Closing, will track integration test implementation in a separate issue  https://github.com/longhorn/longhorn/issues/2485

**Closed by meldafrawi** 2021-04-16 19:05 UTC
Labels: area/manager, feature/backup&restore, feature/scheduling, kind/bug, priority/1, require/automation-e2e, severity/1
