### ISSUE TITLE
[BUG][v1.7.x-head] Test case `test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress` failed due to `failed lock *.lck type 1 acquisition`

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9037] opened 2024-07-18 11:04 UTC
## Describe the bug

Test case `test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress` failed on `v1.7.x-head` with reproducibility ~ 1/50 due to `failed lock *.lck type 1 acquisition`:

https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7258/testReport/junit/tests/test_basic/test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress_s3_6_50_/

```
set_random_backupstore = None
client = <longhorn.Client object at 0x7fede0263d50>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7fede0241f90>
volume_name = 'longhorn-testvol-xza8p1'

    def test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress(set_random_backupstore, client, core_api, volume_name):  # NOQA
        """
        Test DR volume last backup after block deletion aborted. This will set the
        last backup to be empty.
    
        Context:
    
        We want to make sure that when the block deletion for the last backup is
        aborted by operations such as backups in progress, the DR volume will still
        pick up the correct last backup.
    
        Steps:
    
        1.  Create a volume and attach to the current node.
        2.  Write 4 MB to the beginning of the volume (2 x 2MB backup blocks).
        3.  Create backup(0) of the volume.
        4.  Overwrite backup(0) 1st blocks of data on the volume.
            (Since backup(0) contains 2 blocks of data, the updated data is
            data1["content"] + data0["content"][BACKUP_BLOCK_SIZE:])
        5.  Create backup(1) of the volume.
        6.  Verify backup block count == 3.
        7.  Create DR volume from backup(1).
        8.  Verify DR volume last backup is backup(1).
        9.  Create an artificial in progress backup.cfg file.
            This cfg file will convince the longhorn manager that there is a
            backup being created. Then all subsequent backup block cleanup will be
            skipped.
        10. Delete backup(1).
        11. Verify backup block count == 3 (because of the in progress backup).
        12. Verify DR volume last backup is empty.
        13. Delete the artificial in progress backup.cfg file.
        14. Overwrite backup(0) 1st blocks of data on the volume.
            (Since backup(0) contains 2 blocks of data, the updated data is
            data2["content"] + data0["content"][BACKUP_BLOCK_SIZE:])
        15. Create backup(2) of the volume.
        16. Verify DR volume last backup is backup(2).
        17. Activate and verify DR volume data is
            data2["content"] + data0["content"][BACKUP_BLOCK_SIZE:].
        """
        backupstore_cleanup(client)
    
        host_id = get_self_host_id()
    
        vol = create_and_check_volume(client, volume_name,
                                      num_of_replicas=2,
                                      size=SIZE)
        vol.attach(hostId=host_id)
        vol = common.wait_for_volume_healthy(client, volume_name)
    
        data0 = {'pos': 0, 'len': 2 * BACKUP_BLOCK_SIZE,
                 'content': common.generate_random_data(2 * BACKUP_BLOCK_SIZE)}
        create_backup(client, volume_name, data0)
    
        data1 = {'pos': 0, 'len': BACKUP_BLOCK_SIZE,
                 'content': common.generate_random_data(BACKUP_BLOCK_SIZE)}
        _, backup1, _, data1 = create_backup(
            client, volume_name, data1)
    
        backup_blocks_count = backupstore_count_backup_block_files(client,
                                                                   core_api,
                                                                   volume_name)
        assert backup_blocks_count == 3
    
        dr_vol_name = "dr-" + volume_name
        client.create_volume(name=dr_vol_name, size=SIZE,
                             numberOfReplicas=2, fromBackup=backup1.url,
                             frontend="", standby=True)
        check_volume_last_backup(client, dr_vol_name, backup1.name)
        wait_for_backup_restore_completed(client, dr_vol_name, backup1.name)
    
        backupstore_create_dummy_in_progress_backup(client, core_api, volume_name)
        delete_backup(client, volume_name, backup1.name)
        assert backupstore_count_backup_block_files(client,
                                                    core_api,
                                                    volume_name) == 3
        check_volume_last_backup(client, dr_vol_name, "")
        backupstore_delete_dummy_in_progress_backup(client, core_api, volume_name)
    
        data2 = {'pos': 0,
                 'len': BACKUP_BLOCK_SIZE,
                 'content': common.generate_random_data(BACKUP_BLOCK_SIZE)}
>       _, backup2, _, _ = create_backup(client, volume_name, data2)

test_basic.py:973: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:459: in create_backup
    wait_for_backup_completion(client, volname, snap.name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

client = <longhorn.Client object at 0x7fede0263d50>
volume_name = 'longhorn-testvol-xza8p1'
snapshot_name = 'e47ebae9-8b74-4266-b835-6dbe90c0e0d4', retry_count = 300

    def wait_for_backup_completion(client, volume_name, snapshot_name=None,
                                   retry_count=RETRY_BACKUP_COUNTS):
        completed = False
        for _ in range(retry_count):
            v = client.by_id_volume(volume_name)
            for b in v.backupStatus:
                if snapshot_name is not None and b.snapshot != snapshot_name:
                    continue
                if b.state == "Completed":
                    assert b.progress == 100
                    assert b.error == ""
                    completed = True
                    break
            if completed:
                break
            time.sleep(RETRY_BACKUP_INTERVAL)
>       assert completed is True, f" Backup status = {b.state}," \
                                  f" Backup Progress = {b.progress}, Volume = {v}"
E       AssertionError:  Backup status = Error, Backup Progress = 0, Volume = {'accessMode': 'rwo', 'backingImage': '', 'backupCompressionMethod': 'lz4', 'backupStatus': [{'backupURL': 's3://backupbucket@us-east-1/backupstore?backup=backup-23d15bfdecc141b9&volume=longhorn-testvol-xza8p1', 'error': '', 'progress': 100, 'replica': 'longhorn-testvol-xza8p1-r-1d8e048c', 'size': '4194304', 'snapshot': '3017665e-0b3c-469d-a4e3-f6762d68ab45', 'state': 'Completed'}, {'backupURL': '', 'error': 'proxyServer=10.42.2.9:8501 destination=10.42.1.10:10000: failed to backup snapshot e47ebae9-8b74-4266-b835-6dbe90c0e0d4 to backup-3f1dfc6f3d2e46f8: rpc error: code = Internal desc = failed to create backup: failed to create backup to s3://backupbucket@us-east-1/backupstore for volume longhorn-testvol-xza8p1: rpc error: code = Unknown desc = failed lock backupstore/volumes/96/04/longhorn-testvol-xza8p1/locks/lock-d3a98544fcfd47c0.lck type 1 acquisition', 'progress': 0, 'replica': '', 'size': '', 'snapshot': '', 'state': 'Error'}], 'cloneStatus': {'attemptCount': 0, 'nextAllowedAttemptAt': '', 'snapshot': '', 'sourceVolume': '', 'state': ''}, 'conditions': {'Restore': {'lastProbeTime': '', 'lastTransitionTime': '2024-07-18T07:11:25Z', 'message': '', 'reason': '', 'status': 'False'}, 'Scheduled': {'lastProbeTime': '', 'lastTransitionTime': '2024-07-18T07:11:25Z', 'message': '', 'reason': '', 'status': 'True'}, 'TooManySnapshots': {'lastProbeTime': '', 'lastTransitionTime': '2024-07-18T07:11:25Z', 'message': '', 'reason': '', 'status': 'False'}, 'WaitForBackingImage': {'lastProbeTime': '', 'lastTransitionTime': '2024-07-18T07:11:25Z', 'message': '', 'reason': '', 'status': 'False'}}, 'controllers': [{'actualSize': '8388608', 'address': '10.42.1.10', 'currentImage': 'longhornio/longhorn-engine:v1.7.x-head', 'endpoint': '/dev/longhorn/longhorn-testvol-xza8p1', 'hostId': 'ip-10-0-2-106', 'image': 'longhornio/longhorn-engine:v1.7.x-head', 'instanceManagerName': 'instance-manager-1332f4efd18f3c091453a2b2bb0db662', 'isExpanding': False, 'lastExpansionError': '', 'lastExpansionFailedAt': '', 'lastRestoredBackup': '', 'name': 'longhorn-testvol-xza8p1-e-0', 'requestedBackupRestore': '', 'running': True, 'size': '16777216', 'unmapMarkSnapChainRemovedEnabled': False}], 'created': '2024-07-18 07:11:24 +0000 UTC', 'currentImage': 'longhornio/longhorn-engine:v1.7.x-head', 'dataEngine': 'v1', 'dataLocality': 'disabled', 'dataSource': '', 'disableFrontend': False, 'diskSelector': [], 'encrypted': False, 'freezeFilesystemForSnapshot': 'ignored', 'fromBackup': '', 'frontend': 'blockdev', 'image': 'longhornio/longhorn-engine:v1.7.x-head', 'kubernetesStatus': {'lastPVCRefAt': '', 'lastPodRefAt': '', 'namespace': '', 'pvName': '', 'pvStatus': '', 'pvcName': '', 'workloadsStatus': None}, 'lastAttachedBy': '', 'lastBackup': '', 'lastBackupAt': '', 'migratable': False, 'name': 'longhorn-testvol-xza8p1', 'nodeSelector': [], 'numberOfReplicas': 2, 'offlineReplicaRebuilding': 'disabled', 'offlineReplicaRebuildingRequired': False, 'purgeStatus': [{'error': '', 'isPurging': False, 'progress': 0, 'replica': 'longhorn-testvol-xza8p1-r-284f5567', 'state': ''}, {'error': '', 'isPurging': False, 'progress': 0, 'replica': 'longhorn-testvol-xza8p1-r-1d8e048c', 'state': ''}], 'ready': True, 'rebuildStatus': [], 'recurringJobSelector': None, 'replicaAutoBalance': 'ignored', 'replicaDiskSoftAntiAffinity': 'ignored', 'replicaSoftAntiAffinity': 'ignored', 'replicaZoneSoftAntiAffinity': 'ignored', 'replicas': [{'address': '10.42.4.10', 'currentImage': 'longhornio/longhorn-engine:v1.7.x-head', 'dataEngine': 'v1', 'dataPath': '/var/lib/longhorn/replicas/longhorn-testvol-xza8p1-81c8cbaf', 'diskID': '47c4b299-0cec-4db4-ae65-fdf7e04980da', 'diskPath': '/var/lib/longhorn/', 'failedAt': '', 'hostId': 'ip-10-0-2-112', 'image': 'longhornio/longhorn-engine:v1.7.x-head', 'instanceManagerName': 'instance-manager-4bbfb99c67b4c7bfc38197f9b7634b07', 'mode': 'RW', 'name': 'longhorn-testvol-xza8p1-r-1d8e048c', 'running': True}, {'address': '10.42.2.9', 'currentImage': 'longhornio/longhorn-engine:v1.7.x-head', 'dataEngine': 'v1', 'dataPath': '/var/lib/longhorn/replicas/longhorn-testvol-xza8p1-b8d12238', 'diskID': '104bad17-e269-4ea1-a643-5d3bd6681376', 'diskPath': '/var/lib/longhorn/', 'failedAt': '', 'hostId': 'ip-10-0-2-193', 'image': 'longhornio/longhorn-engine:v1.7.x-head', 'instanceManagerName': 'instance-manager-31adf39dba7fee19b32ecbe3f34dd732', 'mode': 'RW', 'name': 'longhorn-testvol-xza8p1-r-284f5567', 'running': True}], 'restoreInitiated': False, 'restoreRequired': False, 'restoreStatus': [{'backupURL': '', 'error': '', 'filename': '', 'isRestoring': False, 'lastRestored': '', 'progress': 0, 'replica': 'longhorn-testvol-xza8p1-r-284f5567', 'state': ''}, {'backupURL': '', 'error': '', 'filename': '', 'isRestoring': False, 'lastRestored': '', 'progress': 0, 'replica': 'longhorn-testvol-xza8p1-r-1d8e048c', 'state': ''}], 'restoreVolumeRecurringJob': 'ignored', 'revisionCounterDisabled': False, 'robustness': 'healthy', 'shareEndpoint': '', 'shareState': '', 'size': '16777216', 'snapshotDataIntegrity': 'ignored', 'snapshotMaxCount': 250, 'snapshotMaxSize': '0', 'staleReplicaTimeout': 0, 'standby': False, 'state': 'attached', 'unmapMarkSnapChainRemoved': 'ignored', 'volumeAttachment': {'attachments': {'': {'attachmentID': '', 'attachmentType': 'longhorn-api', 'conditions': [{'lastProbeTime': '', 'lastTransitionTime': '2024-07-18T07:11:29Z', 'message': '', 'reason': '', 'status': 'True'}], 'nodeID': 'ip-10-0-2-106', 'parameters': {'disableFrontend': 'false', 'lastAttachedBy': ''}, 'satisfied': True}}, 'volume': 'longhorn-testvol-xza8p1'}}

common.py:3220: AssertionError
```

## To Reproduce

Run test case `test_dr_volume_with_backup_block_deletion_abort_during_backup_in_progress` repeatedly

## Support bundle for troubleshooting

[longhorn-tests-regression-7258-bundle.zip](https://github.com/user-attachments/files/16282067/longhorn-tests-regression-7258-bundle.zip)

## Environment

 - Longhorn version: v1.7.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment] 2024-07-18 11:27
Is it reproducible in v1.6.2?

**Comment by ChanYiLin** [comment] 2024-07-19 08:41
I would like to fix this issue with this ticket
[Make backup wait until there is no backup being delete and Add the progress time](https://github.com/longhorn/longhorn/issues/8746)

This is going to resolve all kind of deletion lock issue

**Comment by derekbit** [comment] 2024-07-22 12:19
The issue is rare and needs more time to investigate. Move it to v1.8.0.
cc @innobead

**Comment by ChanYiLin** [comment] 2024-07-26 08:38
I think I found the root cause of this issue.
From the steps
```
 Steps:
...
        => 9.  Create an artificial in progress backup.cfg file.
            This cfg file will convince the longhorn manager that there is a
            backup being created. Then all subsequent backup block cleanup will be
            skipped.
        => 10. Delete backup(1).
        11. Verify backup block count == 3 (because of the in progress backup).
        12. Verify DR volume last backup is empty.
        => 13. Delete the artificial in progress backup.cfg file.
        14. Overwrite backup(0) 1st blocks of data on the volume.
            (Since backup(0) contains 2 blocks of data, the updated data is
            data2["content"] + data0["content"][BACKUP_BLOCK_SIZE:])
        => 15. Create backup(2) of the volume.
        16. Verify DR volume last backup is backup(2).
        17. Activate and verify DR volume data is
            data2["content"] + data0["content"][BACKUP_BLOCK_SIZE:].
```

In step9, since we add an artificial `backup.cfg` which name is `dummy` in the backupstore, `backup-volume-controller` will create the backup CR `dummy` in the cluster 
In step13, we delete the artificial `backup.cfg` in the backupstore directly and consider it as deleted. 
However, the CR is still there, `backup-volume-controller` will scan the cluster and the backupstore and tries to delete the CR
Thus, in the `backup-controller`, the `dummy` CR will be deleted and call the binary to delete the backup in the backupstore again which will introduce the lock.

**Comment by chriscchien** [comment] 2024-08-06 08:16
Close this issue as test case is stable now (50 time on [amd64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7393/) and [arm64](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7394/) all passed)

**Closed by chriscchien** 2024-08-06 08:16 UTC
Labels: kind/bug, reproduce/rare, priority/1, area/volume-backup-restore, severity/2, require/backport
