### ISSUE TITLE
Revert snapshot missing

### ISSUE THREAD

**Issue by jocarren** [longhorn/longhorn#992] opened 2019-12-31 16:04 UTC
I'm ussing 0.7 and the revert to snapshot option is missing. Only backup and delete.

![imagen](https://user-images.githubusercontent.com/23640344/71626833-ed6f3600-2bcd-11ea-982a-0f7a31e7ec2e.png)

I'm I doing something wrong?

**Comment by yasker** [comment] 2019-12-31 16:36
We've noticed that and it would be fixed in the next release (it was suppose to grey out rather than disappear).

You can attach the volume in maintenance mode and revert option should show up there. We don't want user to accidentally revert a snapshot with filesystem mounted, so we limit the revert function to the maintenance mode now

**Comment by jocarren** [comment] 2019-12-31 16:56
Ok, thanks!

**Comment by yasker** [comment] 2019-12-31 22:58
@smallteeths Can you check what's happened in v0.7.0? We want to make sure it's there for the next release.

**Comment by smallteeths** [comment] 2020-01-03 01:46
Disabled Revert snapshot has been changed
![Jietu20200103-092004](https://user-images.githubusercontent.com/27733391/71703043-a079a280-2e0d-11ea-9bc3-399a5b0e8eb8.jpg)

**Comment by yasker** [comment] 2020-01-03 01:49
According to @smallteeths , the issue is fixed in v0.8.0.

**Closed by yasker** 2020-01-03 01:49 UTC
Labels: area/ui, bug
