### ISSUE TITLE
[BUG] unable to detach degraded V2 volume; keeps automatically (but incompletely) re-attaching

### ISSUE THREAD

**Issue by tserong** [longhorn/longhorn#9005] opened 2024-07-15 11:46 UTC
## Describe the bug

If I create a V2 volume that is degraded (not enough replicas) and attach it to a node, it works fine the first time. I see `nvme0n1` and `dm-0` appear if I run `cat /proc/partitions`, and I can read/write the volume under `/dev/mapper/vol`. If I then detach the volume, it initially detaches (the devices disappear from the host), but then in the Lonhorn UI, it immediately goes back to saying it's attached to the host, and degraded, but the block devices are not actually present on the host.. If I click the detach button, nothing changes. It's still in this weird limbo state. If I force detach it, it appears to detach briefly, but then re-attaches, but again, it's not _really_ attached -- there's no block device on the host.

Healthy V2 volumes work just fine (attach, detach, no problem). Degraded V1 volumes also work fine.

## To Reproduce

- On a 1 node cluster, create a V2 volume with replica level 3
- Use the LH GUI to attach the volume to the node. Verify that the block device appears on the node by checking `cat /proc/partitions` and/or `ls /dev/mapper/`
- Use the LH GUI to detach the volume. Check `cat /proc/partitions` and/or `ls /dev/mapper/` and observe that the block device is gone.
- Look at the state of the volume in the LH GUI. It should still (weirdly) be listed as attached on $hostname, even though the block device isn't present.
- Try using the LH GUI to detach the volume. Nothing will happen (or, it might appear to briefly detach, then immediately re-attach).
- Try using the LH GUI to force detach the volume. It will appear to briefly detach, then immediately re-attach again.
- Despite the LH GUI saying the volume is attached, it won't really be attached (no block device is present on host).

## Expected behavior

The volume detaches successfully and remains detached, until the user explicitly re-attaches it.

## Support bundle for troubleshooting

[supportbundle_4c24e4a0-5577-47fb-8e50-77f44df24739_2024-07-15T11-28-52Z.zip](https://github.com/user-attachments/files/16233760/supportbundle_4c24e4a0-5577-47fb-8e50-77f44df24739_2024-07-15T11-28-52Z.zip)

Note that this supportbundle includes logs of reproducing this issue several times. The most recent attempt was made with a single 1GiB volume named v2-3r, created at 2024-07-15T11:25:56Z. Hopefully that helps to narrow things down.

## Environment

 - Longhorn version: 1.6.2
 - Impacted volume (PV): v2-3r
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Harvester v1.3.1
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.27.13+rke2r1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 0
 - Node config
   - OS type and version: Harvester v1.3.1 / SLE Micro 5.4
   - Kernel version: 5.14.21-150400.24.119-default
   - CPU per node: 10
   - Memory per node: 20GiB
   - Disk type (e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes (Gbps): N/A (only one node)
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 1

## Additional context

Here's a video:

https://github.com/user-attachments/assets/a714274d-6355-4dd3-a4ae-bbb33dcf463a

This shows, on a single-node cluser:
1. Creating a single-replica healthy V2 volume (name: v2-1r), then successfully attaching and detaching it to and from the host.
2. Creating a three-replica degraded V2 volume (name: v2-3r), then successfully attaching it to the host, but _failing_ to detach it as described in this issue.
3. Creating a three-replica degraded V1 volume (name: v1-3r), then successfully attaching and detaching it to and from the host.

You'll probably find all the above events in the attached supportbundle as well, but I can't say what the time indexes will be.

**Comment by derekbit** [comment] 2024-07-16 13:26
The reattachment after detaching a degraded v2 volume is caused by a bug of offline rebuilding. The offline rebuilding feature is removed from v1.7.0. I will resolve the issue in v1.6.3 rather than in v1.7.0. BTW, the offline rebuilding will be added back the later version.

@tserong Can you try v1.7.0-rc1 instead? Harvester v1.4.0 should pair with Longhorn v1.7.0. Thanks

**Comment by derekbit** [comment] 2024-08-19 00:59
@innobead Do we need to take time to fix the offline rebuilding bug in v1.6.3?

**Comment by innobead** [comment] 2024-09-04 13:55
No need. It seems the issue has been fixed. Let's close this.

**Closed by innobead** 2024-09-04 13:55 UTC
Labels: kind/bug, priority/0, area/v2-data-engine, require/qa-review-coverage, require/backport
