### ISSUE TITLE
[FEATURE] - Allow backups of detached volumes 

### ISSUE THREAD

**Issue by vikas027** [longhorn/longhorn#1509] opened 2020-06-18 03:00 UTC
**Describe the bug**
At the moment, there is no way to take a backup of a detached volume. It is helpful for pods used jobs, cronjobs, and FaaS systems like OpenFaas. Also, if backup is not allowed at the moment, option to `Schedule` should be disabled. As of now, I can schedule backups of a detached volume.

**To Reproduce**
1. Create a PVC and a pod which just used the PVC and stops
![2020-06-18_12-15-36](https://user-images.githubusercontent.com/6998650/84972956-4bcfa700-b163-11ea-9dbd-fba4d8a31048.png)

**Environment:**
 - Longhorn version: 1.0.0
 - Kubernetes version: 1.17.5
 - Node OS type and version: CentOS 7 (EC2 Instance)

**Workround**
Run a dummy pod with the PVC before taking a backup

**Comment by shuo-wu** [comment] 2020-06-18 12:02
Backup is based on a volume snapshot in Longhorn. And the snapshots can be shown only if the volume is running/attached. If we want to get the snapshots of detached volumes, it means we need to break the current design/architecture. 

One simple workaround for this case is: manually attach the volume to a random node then do the backup. You don't need a pod or a PVC in this case.

**Comment by vikas027** [comment] 2020-06-19 13:03
Sorry, I would like to differ. Manual is not simple.

If it is not easy in the current architecture, at least please disable the option to `Schedule` just like `Create Backup` option is grayed out.

**Comment by shuo-wu** [comment] 2020-06-19 13:16
`Recurring Snapshot and Backup Schedule` will work once you attach the volume. Longhorn allows you to config that in advance. And it's like a parameter rather than an operation of a volume. 
Are there any concerns about this option for the detached volume? Or it is easy to get misunderstood?

**Comment by vikas027** [comment] 2020-06-21 13:35
> Are there any concerns about this option for the detached volume?
No, no concerns, an option to back detached volumes is convenient

In my humble opinion, it makes sense to gray out `Schedule` option too when the volume detached, just like how `Create Backup` is grayed out.

**Comment by shuo-wu** [comment] 2020-06-22 03:53
IMO, graying out `Create backup` means this **operation** is not allowed for detached volumes. And enabling `Recurring Snapshot and Backup Schedule` means this **setting** can be modified for any volume.

**Comment by vikas027** [comment] 2020-06-23 09:01
But I can still create backup schedules for a detached volume which does nothing, I find this a bit weird. If you don't think so, feel free to close the ticket.

**Comment by yasker** [comment] 2020-06-23 18:10
@vikas027 @shuo-wu Thinking about it, I think it makes sense to allow recurring backup to happen when the volume is detached.

From the users' perspective, when they schedule a backup, they would expect they can see the backup to be created automatically according to a certain schedule. The expectation is, the backup store should always have the latest data of the volume.

But in the case of a volume was changed then detached before the last backup was done, the expectation will not be met. Then if the volume is lost during the time that volume is detached, then we lost the changed part of data of volume since the last backup.

So I think it makes sense for us to automatically attach the volume and try to do the snapshot/backup per schedule, then detach the volume manually. Of course, there are implications here:
1. What if during the time the volume was attached automatically then the user want to use the volume? We should treat this automatically attaching period like what we do with restoring or DR volume.
2. What if we failed to attach to the node we've chosen? Should we retry on a different node? The same case applies to the restoring and DR volume as well. We can consider it as a different issue.

After the work in #1406 is done, it should be easier for us to implement backup/snapshot for the detached volumes.

**Comment by vikas027** [comment] 2020-06-25 01:17
Thanks, @yasker .

**Comment by PhanLe1010** [comment] 2020-10-05 20:55
**reproduce steps/manual test steps:**

1. Set `Allow-Recurring-Backup-While-Volume-Detached` to `false`
1. Create a volume
1. Attach the volume, write some data to the volume
1. Detach the volume
1. Set the recurring backup for the volume on every minute
1. Wait for 2 minutes, verify that there is no new backup created

1. Set `Allow-Recurring-Backup-While-Volume-Detached` to `true`
1. Wait until the recurring job begins.
1. Verify that Longhorn automatically attaches the volume, and does backup, then detaches the volume.
1. On very subsequence minutes, verify that Longhorn automatically attaches the volume, but doesn't do backup, then detaches the volume.
   The reason that Longhorn does not do backup is there is no new data.
   
1. Delete the recurring backup
1. Create a PVC from the volume
1. Create a deployment of 1 pod using the PVC
1. Write 1GB data to the volume from the pod.
1. Scale down the deployment. The volume is detached.
1. Set the recurring backup for every 2 minutes.
1. Wait until the recurring backup starts, scale up the deployment to 1 pod.
1. Verify that pod cannot start until the recurring backup finishes.
1. On very subsequence 2 minutes, verify that Longhorn doesn't do backup.
   The reason that Longhorn does not do backup is there is no new data.

1. Delete the recurring job
1. Turn on data locality for the volume
1. Set the number of NumberOfReplicas to 1
1. Let say the volume is attaching to node-1. 
   Wait until there is a healthy replica on node-1 and there is no other replica.
1. Disable scheduling for the node-1. This will force Kubernetes to avoid scheduling new pods on node-1.
1. Write 200MB data to the volume.
1. Detach the volume
1. Set the recurring backup for every 1 minutes.
1. Wait until the recurring backup starts.
   Verify that Longhorn automatically attaches the volume to a node different than node-1, does backup, then detaches the volume.
   However, Longhorn doesn't trigger the replica rebuild, and there is no new replica is created.

**Comment by khushboo-rancher** [comment] 2020-10-15 00:00
Verified with longhorn-master - 10/14/2020

Validation - **Pass**

The recurring backups are taken for detached volume if there is new data.
Validated the below scenarios:
1. The setting Allow-Recurring-Backup-While-Volume-Detached availability.
2. The backup/snapshot job for detached volume.
3. The backup/snapshot job with the attached volume.
4. Deletion and creation of backups when the scheduled recurring job is running.
5. Validated the data of backups.
6. Recurring job run while data writing is in progress.

**Comment by khushboo-rancher** [comment] 2020-12-16 08:59
Test seems little flaky, we can wait for more nightly test run results before closing this.

**Comment by khushboo-rancher** [comment] 2020-12-17 17:58
`Test_recurring_job.test_recurring_jobs_for_detached_volume` is passing for last 4 days. Closing this for now.

**Closed by khushboo-rancher** 2020-12-17 17:58 UTC
Labels: area/manager, enhancement, priority/2, require/LEP, require/automation-e2e, require/doc
