### ISSUE TITLE
[BUG] PV Annotation Isn't Updated After Creating An Oversize Volume

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#9514] opened 2024-09-23 02:35 UTC
## Describe the bug
Since LH PR https://github.com/longhorn/longhorn-manager/pull/1307, the PV annotation `longhorn.io/volume-scheduling-error` should be updated with a related schedule error, however, in LH `v1.7,1`, if creating an oversize volume, the PV annotation is not updated accordingly.

## To Reproduce
- Creating an oversize volume
- The annotation `longhorn.io/volume-scheduling-error` is not updated

## Expected behavior
The annotation `longhorn.io/volume-scheduling-error` should be updated accordingly

## Environment
 - Longhorn version: v1.7.1
 - Harvester version: master-head (`5ad9d940ea98c1b4c67c1f2d9a0212aa2876a663`), v1.4.0

## Additional context and investigation
- This doesn't happen for `LH v1.6.0` (`Harvester v1.3.0`)
- This situation seems to be a regression brought by LH PR [#2918](https://github.com/longhorn/longhorn-manager/pull/2918)
  - [LH controller doesn’t create new replicas in precheck if volume oversizes](https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/controller/volume_controller.go#L2303-L2317)
  - Reconciling volume condition [iterates zero replicas](https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/controller/volume_controller.go#L1729-L1765), and [treat schedule as success](https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/controller/volume_controller.go#L1727)
  - [Updating annotation with empty](https://github.com/longhorn/longhorn-manager/blob/5ff1f83aefb2c17365264d7cc111e04415c9cef8/controller/volume_controller.go#L1806-L1808)
- Harvester depends on such annotation to provide `Insufficient storage` in GUI

**Comment by bk201** [comment] 2024-09-30 10:02
@derekbit @c3y1huang There is a[ similar behavior](https://github.com/harvester/harvester/issues/6669#issuecomment-2382443653) to the annotation if we detach and attach a volume. Should we create another Longhorn issue to track or the cause is identical this Longhorn issue?

**Comment by c3y1huang** [comment] 2024-10-08 02:08
> @derekbit @c3y1huang There is a[ similar behavior](https://github.com/harvester/harvester/issues/6669#issuecomment-2382443653) to the annotation if we detach and attach a volume. Should we create another Longhorn issue to track or the cause is identical this Longhorn issue?

@bk201 @WebberHuang1118 it should be fixed with this issue. Could you help to confirm the fix when the PR is merged?

**Comment by WebberHuang1118** [comment] 2024-10-09 09:46
> > @derekbit @c3y1huang There is a[ similar behavior](https://github.com/harvester/harvester/issues/6669#issuecomment-2382443653) to the annotation if we detach and attach a volume. Should we create another Longhorn issue to track or the cause is identical this Longhorn issue?
> 
> @bk201 @WebberHuang1118 it should be fixed with this issue. Could you help to confirm the fix?

Just checked, and this issue is fixed with PR https://github.com/longhorn/longhorn-manager/pull/3194/, thanks.

**Comment by chriscchien** [comment] 2024-10-21 08:50
Verified **pass** on longhorn v1.8.0-dev-20241020 (https://github.com/longhorn/longhorn-manager/commit/576854e71ba70dd9f5b1e132786fc2afee00a2db)

Dynamic provisioning a oversized PV(v1 and v2), the annotation updated correctly
```bash
> kl get pv -o yaml | grep anno -A 6
    annotations:
      longhorn.io/volume-scheduling-error: insufficient storage;precheck new replica
        failed
      pv.kubernetes.io/provisioned-by: driver.longhorn.io
      volume.kubernetes.io/provisioner-deletion-secret-name: ""
      volume.kubernetes.io/provisioner-deletion-secret-namespace: ""
    creationTimestamp: "2024-10-21T08:40:32Z"

```

**Closed by chriscchien** 2024-10-21 08:50 UTC
Labels: kind/bug, priority/0, require/auto-e2e-test, kind/regression, area/volume-replica-scheduling, area/troubleshoot, require/qa-review-coverage, require/backport, backport/1.7.2
