### ISSUE TITLE
[BUG] Do not copy Host header to API requests forwarded to Longhorn Manager

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5438] opened 2023-02-22 08:27 UTC
## Describe the bug (🐛 if you encounter this issue)

To ensure Longhorn can work with service mesh like Istio, need to change the `Host` header from setting the specified host to the default behavior which is dynamically set to the upstream host (https://docs.nginx.com/nginx/admin-guide/web-server/reverse-proxy/#passing-request-headers) in each proxied request to the upstream server. 

Currently, the request path from user -> longhorn-ui -> longhorn-manager is not working due to the strict host setting. 

https://github.com/longhorn/longhorn-ui/pull/446

## To Reproduce

This was reported by the community, so basically, no reproduction steps were provided. What we should verify is after changing to use `X-Forward-Host`, the UI works as usual w/o issues.

## Expected behavior

Use `X-Forward-Host` to ensure the action endpoints returned from longhorn-manager are still correct and also work well on an Istio-enabled or non-Istio-enabled (current) cluster. (https://github.com/longhorn/longhorn-ui/pull/446#issuecomment-1438073946)

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

## Additional context

cc @longhorn/dev

**Comment by yangchiu** [comment] 2023-02-23 12:05
@innobead Do we need to enable `istio-injection` to test this?

I tried the following steps:
(1) install istio following: https://istio.io/latest/docs/setup/install/helm/#installation-steps
(2) enable `istio-injection` in `longhorn-system` namespace and then install longhorn:
```
kubectl create namespace longhorn-system
kubectl label namespace longhorn-system istio-injection=enabled
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml
```
(3) most of longhorn components can have an istio sidecar injected, but `discover-proc-kubelet-cmdline` will stuck in `NotReady` status
```
NAME                                                  READY   STATUS     RESTARTS        AGE
longhorn-conversion-webhook-7b98d5c6cf-lwmc4          2/2     Running    1 (3m8s ago)    3m18s
longhorn-ui-75578cf6c4-4225n                          2/2     Running    0               3m18s
longhorn-ui-75578cf6c4-qs6lz                          2/2     Running    0               3m18s
longhorn-conversion-webhook-7b98d5c6cf-j4v9l          2/2     Running    1 (3m2s ago)    3m18s
longhorn-recovery-backend-6d7474d7fb-wg45t            2/2     Running    0               3m19s
longhorn-admission-webhook-6df4465d84-2qbf5           2/2     Running    0               3m17s
longhorn-admission-webhook-6df4465d84-6n5zj           2/2     Running    0               3m17s
longhorn-recovery-backend-6d7474d7fb-mw9lm            2/2     Running    0               3m19s
longhorn-manager-6m9w9                                2/2     Running    1 (2m53s ago)   3m21s
longhorn-manager-r2vlw                                2/2     Running    1 (2m54s ago)   3m21s
longhorn-manager-m48v4                                2/2     Running    1 (2m52s ago)   3m21s
engine-image-ei-b907910b-m2wj5                        2/2     Running    0               2m52s
instance-manager-e-26beba4e282951cadc83feec5be64a5d   2/2     Running    0               2m50s
instance-manager-r-26beba4e282951cadc83feec5be64a5d   2/2     Running    0               2m50s
instance-manager-e-6138f470562534c2b12a0474c9ea3eed   2/2     Running    0               2m51s
instance-manager-r-6138f470562534c2b12a0474c9ea3eed   2/2     Running    0               2m51s
instance-manager-r-517ef02478aaf179a0c0591d323dac35   2/2     Running    0               2m52s
instance-manager-e-517ef02478aaf179a0c0591d323dac35   2/2     Running    0               2m52s
engine-image-ei-b907910b-85zdr                        2/2     Running    0               2m52s
engine-image-ei-b907910b-xhxkp                        2/2     Running    0               2m52s
longhorn-driver-deployer-6f49485c8d-kpw67             2/2     Running    2 (26s ago)     3m20s
discover-proc-kubelet-cmdline                         1/2     NotReady   0               11s
```
The log says `kubelet` not found:
```
$ kubectl logs discover-proc-kubelet-cmdline -n longhorn-system
Proc not found: kubelet
```

I can't find related documents about how to setup longhorn + istio, or is there workaround to set kubelet path right?

**Comment by yangchiu** [comment] 2023-02-24 03:11
@innobead 

For [the above istio enabled cluster](https://github.com/longhorn/longhorn/issues/5438#issuecomment-1441647544), although the `discover-proc-kubelet-cmdline` error, `longhorn-ui` can work well (create volume, attach volume, create backup, create snapshot without problems) on master-head (longhorn-ui d3795d9).

And For a normal k3s cluster cluster without istio installed, `longhorn-ui` works well on master-head (longhorn-ui d3795d9) too.

But if I install longhorn v1.4.0 to exclude [the host header commit](https://github.com/longhorn/longhorn-ui/pull/596/files) in [the istio enabled cluster](https://github.com/longhorn/longhorn/issues/5438#issuecomment-1441647544), `longhorn-ui` can still work well.

I'm not quite sure the right way to verify this..

**Comment by innobead** [comment] 2023-02-24 03:23
@yangchiu the goal is to check after changing the nginx setting, the longhorn UI still works with the REST API endpoints provided by longhorn-manager instead of really testing the environment running Istio, but it's good to know it runs well with Istio!

**Comment by innobead** [comment] 2023-02-24 03:52
ref: https://github.com/longhorn/longhorn/issues/1315#issuecomment-723901441

**Comment by yangchiu** [comment] 2023-02-24 06:48
**Summary**:

- To verify this ticket, check `longhorn-ui` still works well with longhorn REST API endpoints after [the host header commit](https://github.com/longhorn/longhorn-ui/pull/596/files), no need to actually test in an `istio` environment

- Verified on master-head (longhorn-ui d3795d9) with a normal k3s cluster without `istio`, operations in `longhorn-ui` still works, and the master branch daily regression runs well too, so close this ticket for now

- Whether longhorn can run with `istio` still needs more investigation. Currently if following [the above steps](https://github.com/longhorn/longhorn/issues/5438#issuecomment-1441647544) to install longhorn in an `istio enabled` environment, `discover-proc-kubelet-cmdline` will stuck in `NotReady` status with error:
 ```
$ kubectl logs discover-proc-kubelet-cmdline -n longhorn-system
Proc not found: kubelet
```

And then `longhorn-driver-deployer` will stuck in `CrashLoopBackOff` with error:
```
$ kubectl logs longhorn-driver-deployer-6f49485c8d-kpw67 -n longhorn-system
time="2023-02-24T01:56:25Z" level=fatal msg="Error deploying driver: failed to start CSI driver: failed to get arg root-dir. Need to specify \"--kubelet-root-dir\" in your Longhorn deployment yaml.: failed to get cmdline of proc kubelet: proc cmdline detection pod discover-proc-kubelet-cmdline didn't complete within 120 seconds"
```

And then all the CSI related components like `csi-provisioner`, `csi-attacher`, `csi-snapshotter`, `longhorn-csi-plugin` etc will fail to start.

Since these CSI components can't be run, volume lifecycle would have issues for sure. So even though you can still access `longhorn-ui` and do operations through it, the underlying functionalities could actually be broken.

**Closed by yangchiu** 2023-02-24 06:48 UTC
Labels: kind/bug, area/ui, backport/1.3.3, backport/1.4.1
