### ISSUE TITLE
[BUG] environment_check.sh does not handle differnt kernel versions in cluster correctly

### ISSUE THREAD

**Issue by achims311** [longhorn/longhorn#5304] opened 2023-01-16 23:26 UTC
## Describe the bug (🐛 if you encounter this issue)

The environment_check.sh uses "uname -r" to get the kernel release and kernel config file.
But the uname -r command is always run locally, not on the node . So the checks against the kernel configuration do not work in case the node is running another kernel version than the local kernel version.

## To Reproduce

1. Set up a cluster on a machine not having the kernel installed which runs on the machine running the "environment_check.sh script (having the required nfs options switched on
e.g. cluster node on server n1 with only kernel 5.19 installed and running the script on o1 with kernel 6.1 running
3. run the environment check from the documentation:
curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.4.0/scripts/environment_check.sh | bash
4. warn about missing nfs setup

## Expected behavior

no warning should be reported

## Log or Support bundle

n/A

## Environment

 - Longhorn version: 1.4.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): n/A
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: different!
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): baremetal
 - Number of Longhorn volumes in the cluster: 0 until now

**Comment by roger-ryao** [comment] 2023-01-18 03:54
I can reproduce it on my local
![Screenshot_20230118_114413](https://user-images.githubusercontent.com/104337648/213079245-e9c3adc7-0c29-4aff-a3ea-e9af4a7dd089.png)

After executed the [PR-5305](https://github.com/longhorn/longhorn/pull/5305)
![Screenshot_20230118_114444](https://user-images.githubusercontent.com/104337648/213079419-787d9033-8108-4d56-ac9e-f5bf893b110a.png)


## Environment

 - Longhorn version: N/A
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): N/A
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04 / keneral **5.4.0-1041-aws**
 - - Local config
   - OS type and version: openSUSE Leap 15.4 / keneral **5.14.21-150400.24.38-default**
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS


CC @derekbit  @PhanLe1010

**Comment by PhanLe1010** [comment] 2023-01-21 02:11
Thanks @roger-ryao for verifying. Could you please run one more test case:

1. Install the NFS client package prerequisite by `kubectl apply -f  https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml`
2. Run the PR https://github.com/longhorn/longhorn/pull/5305 
3. Paste the output here
4. Verify that no error appears and the check passes

**Comment by joshimoo** [comment] 2023-01-23 22:42
@longhorn/qa the pr ended up closing it, can you verify that the updated environment script works correctly.

**Comment by roger-ryao** [comment] 2023-02-06 09:34
> Thanks @roger-ryao for verifying. Could you please run one more test case:
> 
> 1. Install the NFS client package prerequisite by `kubectl apply -f  https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml`
> 2. Run the PR [Fix for bug #5304. #5305](https://github.com/longhorn/longhorn/pull/5305)
> 3. Paste the output here
> 4. Verify that no error appears and the check passes

Hi @PhanLe1010 :
     I verified the [PR-5310](https://github.com/longhorn/longhorn/pull/5310)
     I installed the **NFS** client package, but I didn't  installed **iscsid**.
     The output still displayed the `nfs-common is not found in`. I expect it would show `[ERROR] iscsid is not running`
     
![Screenshot_20230206_171755](https://user-images.githubusercontent.com/104337648/216935010-4045e76e-7559-47aa-a70a-f6461ccadc94.png)

cc @joshimoo

**Comment by roger-ryao** [comment] 2023-02-06 11:23
> Thanks @roger-ryao for verifying. Could you please run one more test case:
> 
> 1. Install the NFS client package prerequisite by `kubectl apply -f  https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml`
> 2. Run the PR [Fix for bug #5304. #5305](https://github.com/longhorn/longhorn/pull/5305)
> 3. Paste the output here
> 4. Verify that no error appears and the check passes

Hi @PhanLe1010 
I verified the https://github.com/longhorn/longhorn/pull/5314
1. Run the PR https://github.com/longhorn/longhorn/pull/5314
![Screenshot_20230206_191001](https://user-images.githubusercontent.com/104337648/216958816-9f3fdfb5-b0fc-4442-b2a7-6795963375aa.png)

2. Install the NFS client package prerequisite by `kubectl apply -f  https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml`
3. Run the PR https://github.com/longhorn/longhorn/pull/5314
![Screenshot_20230206_191439](https://user-images.githubusercontent.com/104337648/216958901-ab9d6bc9-7ef7-4f10-9d03-b19fdb27431e.png)

4. Install the iscsi client package prerequisite by `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-iscsi-installation.yaml`
5. Run the PR https://github.com/longhorn/longhorn/pull/5314
![Screenshot_20230206_191815](https://user-images.githubusercontent.com/104337648/216959206-ceec0ea3-260c-4249-b608-416ee3d5b8cf.png)

CC @joshimoo

**Comment by innobead** [comment] 2023-02-07 07:02
@roger-ryao PRs all merged. Please also verify the script for 1.4.x and 1.3.x in the corresponding issues.

cc @longhorn/qa

**Comment by innobead** [comment] 2023-02-07 07:05
> @roger-ryao PRs all merged. Please also verify the script for 1.4.x and 1.3.x in the corresponding issues.
> 
> cc @longhorn/qa

It seems the backport issues did not created successfully by github action due to the contributor not in the group. @roger-ryao Just verify 1.4.x and 1.3.x in the ticket directly. Thanks.

**Comment by roger-ryao** [comment] 2023-02-07 08:24
> > @roger-ryao PRs all merged. Please also verify the script for 1.4.x and 1.3.x in the corresponding issues.
> > cc @longhorn/qa
> 
> It seems the backport issues did not created successfully by github action due to the contributor not in the group. @roger-ryao Just verify 1.4.x and 1.3.x in the ticket directly. Thanks.

1. Run run script environment_check.sh
2. Install the NFS client package prerequisite by `kubectl apply -f  https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-nfs-installation.yaml`
3. Run run script environment_check.sh
4. Install the iscsi client package prerequisite by `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/prerequisite/longhorn-iscsi-installation.yaml`
5. Run run script environment_check.sh

**1.3.x**
![Screenshot_20230207_155824](https://user-images.githubusercontent.com/104337648/217190876-ee39b8c8-204c-4d5d-a320-ffd4f5762f4c.png)

**1.4.x**
![Screenshot_20230207_161626](https://user-images.githubusercontent.com/104337648/217190909-0b6071d8-2ac1-4f12-a364-15ee5f9e1247.png)

**Closed** 2023-02-08 03:46 UTC
Labels: kind/bug, backport/1.3.3, backport/1.4.1, area/tooling
