### ISSUE TITLE
[BUG] Unable to attach volumes with `node.session.scan = manual`

### ISSUE THREAD

**Issue by tksm** [longhorn/longhorn#1612] opened 2020-07-20 08:18 UTC
**Describe the bug**

When I set `node.session.scan = manual` in iscsid.conf, all pods cannot attach Longhorn volumes. The pod status sticks in ContainerCreating and the Longhorn volume state sticks in attaching/detaching loop.

The reason why I set `node.session.scan = manual` is to avoid the following issues with another CSI Driver.

- [Automatic session scanning discovers all iSCSI devices during login and can cause LUN assignment issues #90982](https://github.com/kubernetes/kubernetes/issues/90982)
- [PV and volume size are different #410](https://github.com/NetApp/trident/issues/410)

`node.session.scan` setting was introduced in [open-iscsi 2.0.874-5ubuntu2.10](https://launchpad.net/ubuntu/+source/open-iscsi/2.0.874-5ubuntu2.10) in Ubuntu.

**To Reproduce**

1. Set `node.session.scan = manual` in `/etc/iscsi/iscsid.conf`
2. Restart iscsid `sudo systemctl restart iscsid`
3. Create Longhorn PVC and Pod
4. Pod sticks in ContainerCreating

**Expected behavior**

Pod can attach volumes with `node.session.scan = manual`.

**Log**

"Instance ... exit status 1" errors appear repeatedly in longhorn-manager

```
time="2020-07-20T06:05:22Z" level=warning msg="Instance pvc-03eb6587-158d-4d5a-bb70-42f68f2c5c37-e-e8b0d898 is state error, error message: exit status 1"
```

"fail to read magic version" errors appear repeatedly in /var/log/tgtd.log

```
tgtd: bs_thread_open(409) 16
lh_client_close_conn: Closing connection
receive_msg: fail to read magic version
response_process: Receive response returned error
lh_client_close_conn: Closing connection
lh_client_close_conn: Connection close complete
tgtd: device_mgmt(246) sz:108 params:path=/var/run/longhorn-pvc-03eb6587-158d-4d5a-bb70-42f68f2c5c37.sock,bstype=longhorn,bsopts=size=2147483648
```

**Environment:**

 - Longhorn version: v1.0.0
 - Kubernetes version: v1.18.3, v1.17.9
 - Node OS type and version: Ubuntu 18.04.4 LTS
 - open-iscsi: [2.0.874-5ubuntu2.10](https://launchpad.net/ubuntu/+source/open-iscsi/2.0.874-5ubuntu2.10)

**Additional context**

**Comment by PhanLe1010** [comment] 2020-07-24 08:15
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at https://github.com/longhorn/go-iscsi-helper/pull/34 , manager_comming, engine_comming

* [ ] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: volume attach/detach/restore/backup

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by PhanLe1010** [comment] 2020-07-24 08:20
*Reproduce:*

1. Setup a cluster with OS Ubuntu 18.04.4 LTS. SSH into each worker node in the cluster. Update the open-iscsi to the latest version (because ):
```
sudo apt-get update
sudo apt-get install open-iscsi
```
1. Set `node.session.scan = manual` in `/etc/iscsi/iscsid.conf`
2. Restart iscsid `sudo systemctl restart iscsid`
3. Create Longhorn PVC and Pod
4. Pod sticks in ContainerCreating

**Comment by PhanLe1010** [comment] 2020-07-24 08:33
@tksm Thank you for reporting. May I ask how you setup Longhorn along with other CSI Drivers? I would like to understand more about your setup to see if there are any other potential problems.

**Comment by tksm** [comment] 2020-07-24 14:00
Thank you so much for the quick fix! I'll check the fix with custom build after this PR is merged.

My setup is based on [deploy/longhorn.yaml](https://github.com/longhorn/longhorn/blob/master/deploy/longhorn.yaml) with some modifications (PSP and StorageClass option). The cluster also runs [NetApp/trident](https://github.com/NetApp/trident) v20.04.0 which requires `node.session.scan = manual` to avoid [the issue](https://github.com/NetApp/trident/issues/410). When I unset `node.session.scan = manual`(auto), both of them work fine.

**Comment by PhanLe1010** [comment] 2020-07-24 17:48
@tksm Thank you for the info

**Comment by shuo-wu** [comment] 2020-07-27 02:56
After the PRs are merged, does Longhorn work fine if `open-iscsi` on some worker nodes is not up-to-date?

**Comment by PhanLe1010** [comment] 2020-07-27 18:21
> After the PRs are merged, does Longhorn work fine if open-iscsi on some worker nodes is not up-to-date?

I tested and it was fine. Still need QA to verify.

**Comment by tksm** [comment] 2020-07-28 13:35
@PhanLe1010 I confirmed that the issue is fixed with the custom longhorn-engine and longhorn-manager images built on v1.0.1 + cherry-pick. Thanks a lot for the fix!

**Comment by khushboo-rancher** [comment] 2020-07-29 00:36
Verified on Master - 07-28-2020

Validation - **Passed**

Followed the steps from https://github.com/longhorn/longhorn/issues/1612#issuecomment-663405053
Verified Longhorn deployment and volume creation and attaching to pod.

Tested below scenarios:
1.  With config ```node.session.scan = manual```
2. Without config ``node.session.scan```
3. With config ```node.session.scan = auto```
4. With dummy config
5. Without update.

**Closed by khushboo-rancher** 2020-07-29 00:36 UTC
Labels: area/engine, bug, priority/3
