### ISSUE TITLE
[BUG] Single Node Longhorn fails to recover after multiple outages

### ISSUE THREAD

**Issue by Blackclaws** [longhorn/longhorn#2204] opened 2021-01-22 16:08 UTC
**Describe the bug**
Longhorn is in a faulted state and spins on attaching and detaching volumes even though there are no pods requesting the volumes.

**To Reproduce**
1. Create Longhorn Volumes
2. Have multiple crashes that result from kernel lockups
3. See Longhorn spinning on volume attaching and detaching

**Expected behavior**
Either the volumes are faulted, detached or attached

**Log**
The log is chuck full of messages like this: 
```
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time=\"2021-01-22T02:35:51Z\" level=info msg=\"Starting with replicas [\\\"tcp://10.42.0.254:10000\\\"]\""
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time=\"2021-01-22T02:35:51Z\" level=info msg=\"Connecting to remote: 10.42.0.254:10000\""
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time=\"2021-01-22T02:35:51Z\" level=warning msg=\"failed to create backend with address tcp://10.42.0.254:10000: Replica must be closed, Can not add in state: error\""
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: time=\"2021-01-22T02:35:51Z\" level=info msg=\"Adding backend: tcp://10.42.0.254:10000\""
time="2021-01-22T02:36:05Z" level=warning msg="pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7-e-bc240ffa: 2021/01/22 02:35:51 cannot create an available backend for the engine from the addresses [tcp://10.42.0.254:10000]"
```

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.
[longhorn-support-bundle_7cbe6bc8-bb79-4c65-b2fe-ce3091685b8d_2021-01-22T16-04-07Z.zip](https://github.com/longhorn/longhorn/files/5857034/longhorn-support-bundle_7cbe6bc8-bb79-4c65-b2fe-ce3091685b8d_2021-01-22T16-04-07Z.zip)

**Environment:**
 - Longhorn version: 1.1
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE 1.19.6
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 1
 - Node config
   - OS type and version: Centos 8.3
   - CPU per node: 20
   - Memory per node: 22GB
   - Disk type(e.g. SSD/NVMe): HDD
   - Network bandwidth between the nodes: N/A
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM
 - Number of Longhorn volumes in the cluster: 6

**Additional context**
The volumes are intact from a data perspective. I've mounted the data manually and the contents look fine, no issues there. It appears that longhorn is fighting against itself here.

Neither restarting longhorn, nor redeploying longhorn has solved the issue. I've tried increasing the replica count so that maybe I can migrate the volumes to another worker I would attach but to no avail. It seem as if I have to restore from backup at this point. 

Just checkec what happens if I delete the persistent volumes. It still keeps trying to attach, faults, detaches, tries to attach again.

**Comment by shuo-wu** [comment] 2021-01-25 04:16
It seems that the replica of the volume was wrong (Longhorn cannot check [the replica status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1146) or [the related disk status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1134))  then the error message cannot be unset even if the check could succeed later (I think it's a Longhorn bug). 

To understand why the replica of volume `pvc-24e08e51-3db8-45b4-8860-4f1adcccd9c7` becomes error, can you check if there are any related error messages in the replica instance manager pod? You can find the name of pod `instance-manager-r-xxxxxxxx` by checking the volume detail page.

To recover the volume, you can check and try the following:
1. Check if the replica and the related disk still works fine. You can log in to the node the replica resides on and check the data directory and the volume head file (a file named `volume-head-xxxx.img` in the data directory) for the replica. The data directory of a replica is already shown on the volume detail page. e.g., `/var/lib/longhorn/replicas/vol-d43093e9`
2. If both work fine, you can detach the volume first, then manually clean up the value of field `Error` in the volume head meta file in the replica data directory. After that, the volume should be recovered.

Notice that you are using the HDD disks. I suspect this may be the reason why the replica failed. Longhorn is designed/optimized for SSD/NVMe. We will investigate if Longhorn would work on spinning disk https://github.com/longhorn/longhorn/issues/2206. But for now, you may encounter unexpected replica crash/failure if you choose spinning disks.

**Comment by Blackclaws** [comment] 2021-01-25 10:54
I've since rolled back the underlying filesystem and the cluster to the last snapshot which restored functionality unfortunately also means I can't check the logs of the instance manager now. 

I'll try the solutions you mentioned if the issue pops up again. Unfortunately I must use spinning disks in this case as these are persistent volumes used for cloud storage and thus are too large for our SSD drives.

If Longhorn does not work in this case this would be very important to mention in big red letters somewhere on the front page, as I'm expecting a lot of people are using it for normal data storage volumes that sit on spinning disks.

**Comment by jenting** [comment] 2021-03-23 05:59
> It seems that the replica of the volume was wrong (Longhorn cannot check [the replica status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1146) or [the related disk status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1134)) then the error message cannot be unset even if the check could succeed later (I think it's a Longhorn bug).

Note: we need to improve this.

**Comment by jenting** [comment] 2021-04-01 09:00
Personally, I'm not pretty sure should we keep still need to fix the issue?
> It seems that the replica of the volume was wrong (Longhorn cannot check [the replica status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1146) or [the related disk status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1134)) then the error message cannot be unset even if the check could succeed later (I think it's a Longhorn bug).

Because there is no healthy replica on the node, the *.img and `volume.meta` both got polluted.
The workaround way to recover it is to remove the Error state message in `volume.meta`.

**Comment by innobead** [comment] 2021-04-01 09:14
Can u automatically try recovering the degraded replica from the error state? If it’s not faulted, it will be recovered. But it’s still faulted, the state keeps in repeated attaching/detaching state looks reasonable to me because the volume actually faulted.

@shuo-wu @joshimoo any ideas?

**Comment by shuo-wu** [comment] 2021-04-02 09:51
1. If a volume contains multiple replicas and one replica encounters this issue, will this issue block the whole attachment?
2. For a failed replica, it can be either reusable or not. If it's not reusable, we don't need to keep retrying it. If it's reusable, we need to verify the replica and remove the error message in the info file if possible. It's not a good idea to do the current meaningless retry. For this case, I think it's reusable. The error message means the replica server cannot `stat` the replica work directory and the server can still modify the info file inside the directory. Maybe cancelling the read permission of the directory can reproduce this step as well... If later the directory is fine when a new replica server tries to reuse the directory, we can remove the error message, right? If NO, this replica directory [should not be reuseable after several retries](https://github.com/longhorn/longhorn-manager/blob/24085e36404ccce242257ebc3c79f602dce71a32/controller/volume_controller.go#L1497).

**Comment by jenting** [comment] 2021-04-06 04:52
I check the support bundle again, although the user uses longhorn version `v1.1.0`, however, the volume's engine image still uses `v1.0.2` version. The below code introduced in v1.1.0, so it's not the root cause for the user's problem.

> It seems that the replica of the volume was wrong (Longhorn cannot check [the replica status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1146) or [the related disk status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1134)) then the error message cannot be unset even if the check could succeed later (I think it's a Longhorn bug).

The root cause should be https://github.com/longhorn/longhorn-engine/blob/v1.0.2/pkg/replica/server.go#L119-L120 and https://github.com/longhorn/longhorn-engine/blob/v1.0.2/pkg/replica/replica.go#L991-L1001, either:
- `os.Open` error: I've no idea now how to easily make this happens :thinking: 
- `json.Decode` error: it's not hard to reproduce the `json.Decode` it, we could change one of the `volume.meta` value from `boolean` to `string`, then the issue happens

We'd like to add a log to [here](https://github.com/longhorn/longhorn-engine/blob/v1.0.2/pkg/replica/server.go#L120) to see what's the root cause of this issue first.

**Comment by innobead** [comment] 2021-04-06 06:38
> I check the support bundle again, although the user uses longhorn version `v1.1.0`, however, the volume's engine image still uses `v1.0.2` version. The below code introduced in v1.1.0, so it's not the root cause for the user's problem.
> 
> > It seems that the replica of the volume was wrong (Longhorn cannot check [the replica status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1146) or [the related disk status](https://github.com/longhorn/longhorn-engine/blob/783624ce3a4829b1162eb74f8736b1b4fcd13ae6/pkg/replica/replica.go#L1134)) then the error message cannot be unset even if the check could succeed later (I think it's a Longhorn bug).
> 
> The root cause should be https://github.com/longhorn/longhorn-engine/blob/v1.0.2/pkg/replica/server.go#L119-L120 and https://github.com/longhorn/longhorn-engine/blob/v1.0.2/pkg/replica/replica.go#L991-L1001, either:
> 
> * `os.Open` error: I've no idea now how to easily make this happens thinking
> * `json.Decode` error: it's not hard to reproduce the `json.Decode` it, we could change one of the `volume.meta` value from `boolean` to `string`, then the issue happens
> 
> We'd like to add a log to [here](https://github.com/longhorn/longhorn-engine/blob/v1.0.2/pkg/replica/server.go#L120) to see what's the root cause of this issue first.

Just a note, in a normal case of `more than one replica`, the issue will be tackled by the auto salvage process to rebuilt the faulty replica, so users will not encounter this issue except all replica faulty.

**Comment by innobead** [comment] 2021-04-13 03:22
@Blackclaws in the next release 1.1.1, we will enhance the logging to help us identify the root cause. We would suggest waiting for the next version to reproduce, then report the result again. Thanks.

**Comment by innobead** [comment] 2021-04-29 04:44
Closing first, because we have enhanced the logging to help figure out the root cause. @Blackclaws feels free to reopen it if you find out more info from the logs. Thanks.

**Closed by innobead** 2021-04-29 04:44 UTC
Labels: area/engine, investigation-needed, kind/bug
