### ISSUE TITLE
[BUG] Crash engine process using SIGKILL will result in a detach/attach loop for volume

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1240] opened 2020-04-22 22:30 UTC
**Describe the bug**
Crashing engine process will result in a detach/attach loop for volume

**To Reproduce**
1. Create a volume, attach it to a node
2. exec into volume  Instance Manager  using 
` kubectl -n longhorn-system exec -it <INSTANCE_MANAGED_ENGINE_POD>  /bin/bash `
3. Use ps command to identify engine process for volume
`ps aux | grep -i <VOLUME_NAME>`
4. Use SIGKILL to kill engine process `kill -9 ENGINE_PID`

**Expected behavior**
volume should be detached, and the re-attached again

**Log**
```
 Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists\\n, error exit status 22\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:46Z\" level=info msg=\"go-iscsi-helper: found available target id 2\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:46Z\" level=info msg=\"go-iscsi-helper: failed to use target id 2, retrying with a new target ID: err Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists\\n, error exit status 22\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:46Z\" level=info msg=\"go-iscsi-helper: found available target id 2\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:46Z\" level=info msg=\"go-iscsi-helper: failed to use target id 2, retrying with a new target ID: err Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists\\n, error exit status 22\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:47Z\" level=info msg=\"go-iscsi-helper: found available target id 2\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:47Z\" level=info msg=\"go-iscsi-helper: failed to use target id 2, retrying with a new target ID: err Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists\\n, error exit status 22\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:47Z\" level=info msg=\"go-iscsi-helper: found available target id 2\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:47Z\" level=info msg=\"go-iscsi-helper: failed to use target id 2, retrying with a new target ID: err Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists\\n, error exit status 22\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: time=\"2020-04-22T22:04:48Z\" level=error msg=\"Failed to startup frontend: Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists\\n, error exit status 22\""
time="2020-04-22T22:13:36Z" level=warning msg="pvc-581142e7-b579-47c1-81a6-47d44729e928-e-22786b2c: 2020/04/22 22:04:48 failed to start up frontend: Failed to execute: tgtadm [--lld iscsi --op new --mode target --tid 2 -T iqn.2019-10.io.longhorn:pvc-581142e7-b579-47c1-81a6-47d44729e928], output , stderr, tgtadm: this target already exists"
```

**Environment:**
 - Longhorn version: master (v0.8.1-rc2+)
 - Kubernetes version: v1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**

**Comment by shuo-wu** [comment] 2020-05-15 13:18
The causes of this issue:
1. There are frontend leftovers (ISCSI target) after the SIGKILL.
2. The frontend leftovers cannot be cleaned up correctly during the engine restarts. 
    Since there is no parameter set when the 1st time the new engine process tries to start up the frontend then the shutdown doesn't work:
https://github.com/longhorn/longhorn-engine/blob/8df2fb156e35d86402314df69a619470ec80e0da/pkg/frontend/tgt/frontend.go#L37

Solution:
Set parameters before the cleanup.

**Comment by shuo-wu** [comment] 2020-05-15 14:30
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by meldafrawi** [comment] 2020-05-19 18:34
Validation: **PASSED**

Steps to test:

1. Create a volume, attach it to a node, create a file system and mount it to a directory on the node.
2. Create a pod using a volume using
 `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/pod_with_pvc.yaml`
3. write some random data to both volumes, and compute it's checksum
4. identify Instance Manager for both volumes, and for each one exec into the pod using
 `kubectl -n longhorn-system exec -it <INSTANCE_MANAGED_ENGINE_POD> /bin/bash`
5. Use ps command to identify engine process for volume
 `ps aux | grep -i <VOLUME_NAME>`
6. Use **SIGKILL** to kill engine process 
`kill -9 ENGINE_PID`
7. Volumes should detach and re-attach again (**PASS**).
8. Pod using the volume should be restarted, and volume data should be accessible. (**PASS**)
9. Data written to the volume attached to the node should be accessible. (**PASS**)
10. Check data checksum in both volumes. (**PASS**)
11.

**Closed** 2020-05-28 21:48 UTC
Labels: area/engine, bug, priority/2, require/automation-e2e, require/automation-engine
