### ISSUE TITLE
[BUG] - longhorn-driver-deployer stucks at Init:0/1 

### ISSUE THREAD

**Issue by opscmkamthe** [longhorn/longhorn#2903] opened 2021-08-19 12:55 UTC
On a new kubernetes cluster (Version 1.21 or 1.22), longhorn installation does not work as status of longhorn-driver-deployer stucks at Init:0/1. 

**To Reproduce**
1. It is ensured that all prerequisites (open-iscsi, nfs-common, etc) and requirements are met.
2. Install longhorn using helm or kubectl
3. Observe that longhorn-driver-deployer stucks at Init:0/1. 

**Expected behavior**
longhorn installation should be successful

**Log**
Please find attached the log file for all the pods.

ubuntu@ip-172-16-0-107:~$ kubectl get po -n longhorn-system
NAME                                        READY   STATUS             RESTARTS   AGE
engine-image-ei-a5a44787-gbzdf              1/1     Running            0          6m54s
engine-image-ei-a5a44787-njmdv              1/1     Running            0          6m54s
engine-image-ei-a5a44787-x4mlc              1/1     Running            0          6m54s
instance-manager-e-82a4833f                 1/1     Running            0          6m51s
instance-manager-e-d3b10b11                 1/1     Running            0          6m53s
instance-manager-e-d9f12f27                 1/1     Running            0          6m54s
instance-manager-r-2038ce0b                 1/1     Running            0          6m50s
instance-manager-r-542bcc23                 1/1     Running            0          6m53s
instance-manager-r-bc9fe816                 1/1     Running            0          6m53s
longhorn-driver-deployer-68cdff85c7-d7d5q   0/1     Init:0/1           0          7m16s
longhorn-manager-9pqff                      1/1     Running            1          7m16s
longhorn-manager-9qckt                      1/1     Running            1          7m16s
longhorn-manager-mq2cx                      1/1     Running            0          7m16s
longhorn-ui-56db5bbb9d-n79fj                0/1     CrashLoopBackOff   6          7m16s

**Environment:**
 - Longhorn version: v1.1.2 (also tried installing v1.1.1)
 - Installation method Helm (tried with Kubectl also)
 - Kubernetes distro : Standard kubernetes 1.21 or 1.22
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2 CPU
   - Memory per node: 4GB
   - Disk type: SSD
   - Network bandwidth between the nodes: 10GB
 - Underlying Infrastructure : AWS EC2 instances
 - Number of Longhorn volumes in the cluster: 0 (fresh installation)

[longhorn-installation-logs.txt](https://github.com/longhorn/longhorn/files/7014474/longhorn-installation-logs.txt)

**Comment by c3y1huang** [comment] 2021-08-23 03:08
Looks similar to
- https://github.com/longhorn/longhorn/issues/1549
- - https://github.com/longhorn/longhorn/issues/1490

**Comment by shuo-wu** [comment] 2021-08-23 03:17
To figure out the cause, can you check the following first:
  1. Check the events for the pod: `kubectl --namespace longhorn-system describe pod longhorn-driver-deployer-xxxxxxxx`
  2. Check if `longhorn-backend:9500` would be resolved successfully inside other Longhorn workload containers.

**Comment by jenting** [comment] 2021-11-05 03:45
Please check if it is a DNS issue, I'm guessing that the DNS name `longhorn-backend` is not available.

**Comment by jenting** [comment] 2021-12-21 07:37
Out of activity, close this issue.

**Closed by jenting** 2021-12-21 07:37 UTC
Labels: kind/bug

**Comment by lcndsmr** [comment] 2024-10-11 07:17
I do have the same Issue right now, dns resolution of longhorn-backup works and there are no events for the longhorn-driver-deployer pod thats stuck in init. Anything else I can do? 
Also my csi-plugin pods are stuck in a crashloop
