### ISSUE TITLE
[BUG] Backup restore fails when the node where restore volume was attached is disconnected during restoration

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1327] opened 2020-05-12 20:35 UTC
**Describe the bug**
Backup restore fails when a node is disconnected during restoration

**To Reproduce**

- Take a backup
- restore from a backup
- While the restore is in progress, Network node to which (restore volume) is attached to is disconnected  (100 seconds)
- The volume is seen in Faulted state and API gives message

```
          "message": "All replica restore failed",
          "reason": "RestoreFailure",
```

**Expected behavior**
Volume should be in detached state after restoration. Replica on the node with disconnected network, should fail and be in "Stopped" State.

**Note:**
Backupstore - S3

**Log**
[longhorn-support-bundle_36282569-1ecb-4e54-a886-d78a82917c9f_2020-05-12T20-30-51Z.zip](https://github.com/longhorn/longhorn/files/4618324/longhorn-support-bundle_36282569-1ecb-4e54-a886-d78a82917c9f_2020-05-12T20-30-51Z.zip)

**Environment:**
 - Longhorn version: master - 05/12/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: RKE Linux Cluster

**Comment by yasker** [comment] 2020-05-12 20:40
Btw, the backupstore is S3, so the connectivity wasn't cut.

**Comment by sowmyav27** [comment] 2020-05-13 23:14
I tried it again on a master setup. I was not able to reproduce this issue.

Volume is in detached state after restoration. Replica on the node disconnected network, fails and is in "Stopped" State.

**Comment by yasker** [comment] 2020-05-13 23:34
@sowmyav27 There are engine fixes checked in yesterday, maybe that's the reason? cc @shuo-wu

**Comment by shuo-wu** [comment] 2020-05-14 11:26
Is this issue similar to the reopened issue #1270?

**Comment by sowmyav27** [comment] 2020-05-14 16:38
@shuo-wu This issue - https://github.com/longhorn/longhorn/issues/1270 was reopened as the restore was "stuck" when a node was powered down,

However, this issue #1327 - is when the restore failed completely, when the network on a node was disconnected.

**Comment by yasker** [comment] 2020-05-15 05:29
@sowmyav27 can you check if this case applies to the node that volume attached to, or the node that only have the replica?

**Comment by sowmyav27** [comment] 2020-05-15 06:06
@yasker This issue https://github.com/longhorn/longhorn/issues/1327#issue-616942796 happens when the network on the node in which restored volume is attached is disconnected for around 100 seconds.

In case where the network on a node, where a replica is scheduled is disconnected, the replica is in "Failed" state. restoration happens and the volume is in detached mode.

**Comment by yasker** [comment] 2020-05-15 06:11
@sowmyav27 Got it. Can you clarify that in the original comment? We want to make sure it's up to date and as accurate as possible since it only mentioned `Network of one of the nodes is disconnected`

**Comment by yasker** [comment] 2020-06-24 16:58
@shuo-wu Is there any update for this issue after we fixed https://github.com/longhorn/longhorn/issues/1366 ?

**Comment by khushboo-rancher** [comment] 2020-06-26 00:02
Verified on Master, Found an intermittent issue.
Most of the time the reported issue works fine. I interrupted the connection of attached node while restore was in progress and it switch to other node and completed restore process. But this case failed once, explained below.

1.  Restore ```restore-test1``` started and got attached to ```khushboo-test-nfs-wk2``` node.
2.  While restore was in progress, connection is interrupted for 100 secs.
3. The replicas on the non-attached nodes```khushboo-test-nfs-wk1 and khushboo-test-nfs-wk3``` failed.
4. After sometime volume went in faulted state.

Logs:
```
2020-06-25T22:47:37Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Engine\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-e-443d795d\	", UID:\"	9d479698-901b-4f4c-a9f8-c87d20bf8b73\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962973\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Delete' Removed unknown replica tcp://10.42.2.9:10000 from engine		
2020-06-25T22:47:37Z	 level=debug msg=	Requeue longhorn-system/restore-test1 due to error <nil> or Operation cannot be fulfilled on engines.longhorn.io \	restore-test1-e-443d795d\	: the object has been modified; please apply your changes to the latest version and try again														
2020-06-25T22:47:37Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Engine\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-e-443d795d\	", UID:\"	9d479698-901b-4f4c-a9f8-c87d20bf8b73\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962976\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Delete' Removed unknown replica tcp://10.42.2.9:10000 from engine		
2020-06-25T22:47:37Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Engine\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-e-443d795d\	", UID:\"	9d479698-901b-4f4c-a9f8-c87d20bf8b73\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962979\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Delete' Removed unknown replica tcp://10.42.2.9:10000 from engine		
2020-06-25T22:47:38Z	 level=debug msg=	Prepare to delete instance restore-test1-r-ca9adbb5																
2020-06-25T22:47:38Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Replica\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-r-ca9adbb5\	", UID:\"	57d8520e-2abd-4f50-98b2-4f44254bb550\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962988\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Stop' Stops restore-test1-r-ca9adbb5		
2020-06-25T22:47:38Z	 level=warning msg=	Try to get requested log for restore-test1-r-ca9adbb5 on node khushboo-test-nfs-wk3																
2020-06-25T22:47:38Z	 level=warning msg=	"cannot get requested log for instance restore-test1-r-ca9adbb5 on node khushboo-test-nfs-wk3, error instancemanager.longhorn.io \"	\	 not found														
2020-06-25T22:47:38Z	 level=debug msg=	Prepare to delete instance restore-test1-r-ca9adbb5																
2020-06-25T22:47:38Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Replica\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-r-ca9adbb5\	", UID:\"	57d8520e-2abd-4f50-98b2-4f44254bb550\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962996\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Stop' Stops restore-test1-r-ca9adbb5		
2020-06-25T22:47:38Z	 level=debug msg=	Prepare to delete instance restore-test1-r-ca9adbb5																
2020-06-25T22:47:38Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Replica\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-r-ca9adbb5\	", UID:\"	57d8520e-2abd-4f50-98b2-4f44254bb550\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962997\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Stop' Stops restore-test1-r-ca9adbb5		
2020-06-25T22:47:38Z	 level=info msg=	Event(v1.ObjectReference{Kind:\	Engine\	", Namespace:\"	longhorn-system\	", Name:\"	restore-test1-e-443d795d\	", UID:\"	9d479698-901b-4f4c-a9f8-c87d20bf8b73\	", APIVersion:\"	longhorn.io/v1beta1\	", ResourceVersion:\"	962990\	", FieldPath:\"	\	}): type: 'Normal' reason: 'Delete' Removed unknown replica tcp://10.42.2.9:10000 from engine		
2020-06-25T22:47:38Z	 level=debug msg=	Requeue longhorn-system/restore-test1 due to error <nil> or Operation cannot be fulfilled on engines.longhorn.io \	restore-test1-e-443d795d\	: the object has been modified; please apply your changes to the latest version and try again														
2020-06-25T22:47:38Z	 level=warning msg=	Try to get requested log for restore-test1-e-443d795d on node khushboo-test-nfs-wk2
```
Looks like it tried to switch to ```khushboo-test-nfs-wk3``` node but failed and started to try again to ```khushboo-test-nfs-wk2```

[longhorn-support-bundle_a47937cf-313e-49af-800a-b78eaab0620b_2020-06-25T23-54-47Z.zip](https://github.com/longhorn/longhorn/files/4834376/longhorn-support-bundle_a47937cf-313e-49af-800a-b78eaab0620b_2020-06-25T23-54-47Z.zip)

**Comment by shuo-wu** [comment] 2020-06-26 04:14
1. The engine on the disconnected node `khushboo-test-nfs-wk2` cannot ping the replicas on `khushboo-test-nfs-wk1` and `khushboo-test-nfs-wk3`, hence it will wrongly mark those replica as ERROR then the longhorn manager pod on the node will try to fail the replicas.
2. Ideally, the longhorn manager pod on node `khushboo-test-nfs-wk2` shouldn't succeed to update the volume since it's disconnected. But actually it did on your cluster. That's weird.

The longhorn manager pod log on node `khushboo-test-nfs-wk2`:
```
2020-06-25T22:45:03.066783145Z time="2020-06-25T22:45:03Z" level=debug msg="Instance handler updated instance restore-test1-e-443d795d state, old state starting, new state running"
2020-06-25T22:45:03.068129115Z time="2020-06-25T22:45:03Z" level=debug msg="Start monitoring restore-test1-e-443d795d"
2020-06-25T22:45:03.08580694Z time="2020-06-25T22:45:03Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test1\", UID:\"85ab9cef-f692-4ea9-a789-ccb8f0cf1947\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962271\", FieldPath:\"\"}): type: 'Normal' reason: 'Attached' volume restore-test1 has been attached to khushboo-test-nfs-wk2"
2020-06-25T22:45:04.386724768Z time="2020-06-25T22:45:04Z" level=info msg="engine restore-test1-e-443d795d prepared to restore backup, backup target: s3://khushboo-longhorn@us-west-1/, backup volume: volume-1, requested restored backup name: backup-f2d4af4963f34758, last restored backup name: "
2020-06-25T22:45:06.582812876Z time="2020-06-25T22:45:06Z" level=debug msg="Backup s3://khushboo-longhorn@us-west-1/?backup=backup-f2d4af4963f34758&volume=volume-1 restored for volume restore-test1"

2020-06-25T22:47:32.404090527Z time="2020-06-25T22:47:32Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test1\", UID:\"85ab9cef-f692-4ea9-a789-ccb8f0cf1947\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962314\", FieldPath:\"\"}): type: 'Normal' reason: 'Degraded' volume restore-test1 became degraded"
2020-06-25T22:47:32.444757248Z time="2020-06-25T22:47:32Z" level=warning msg="Try to get requested log for restore-test1-e-443d795d on node khushboo-test-nfs-wk2"
......
2020-06-25T22:47:32.404090527Z time="2020-06-25T22:47:32Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test1\", UID:\"85ab9cef-f692-4ea9-a789-ccb8f0cf1947\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962314\", FieldPath:\"\"}): type: 'Normal' reason: 'Degraded' volume restore-test1 became degraded"
2020-06-25T22:47:32.444757248Z time="2020-06-25T22:47:32Z" level=warning msg="Try to get requested log for restore-test1-e-443d795d on node khushboo-test-nfs-wk2"

2020-06-25T22:47:33.008563458Z time="2020-06-25T22:47:33Z" level=warning msg="Found unknown replica in the restore status map, address tcp://10.42.2.9:10000, restore status: &{IsRestoring:false LastRestored: Progress:0 Error:Failed to get restoring status on tcp://10.42.2.9:10000: failed to get restore status: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake Filename: State: BackupURL:}"
2020-06-25T22:47:33.008628448Z time="2020-06-25T22:47:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test1\", UID:\"85ab9cef-f692-4ea9-a789-ccb8f0cf1947\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962916\", FieldPath:\"\"}): type: 'Normal' reason: 'Healthy' volume restore-test1 became healthy"
2020-06-25T22:47:34.510388922Z time="2020-06-25T22:47:34Z" level=warning msg="Found unknown replica in the restore status map, address tcp://10.42.2.9:10000, restore status: &{IsRestoring:false LastRestored: Progress:0 Error:Failed to get restoring status on tcp://10.42.2.9:10000: failed to get restore status: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake Filename: State: BackupURL:}"
2020-06-25T22:47:37.415176213Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"restore-test1-e-443d795d\", UID:\"9d479698-901b-4f4c-a9f8-c87d20bf8b73\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962945\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' Detected replica restore-test1-r-ca9adbb5 (10.42.3.6:10000) in error"
2020-06-25T22:47:37.415241743Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"restore-test1-e-443d795d\", UID:\"9d479698-901b-4f4c-a9f8-c87d20bf8b73\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962945\", FieldPath:\"\"}): type: 'Warning' reason: 'Faulted' Detected replica UNKNOWN-tcp://10.42.2.9:10000 (10.42.2.9:10000) in error"
2020-06-25T22:47:37.523497541Z time="2020-06-25T22:47:37Z" level=warning msg="Found unknown replica in the restore status map, address tcp://10.42.2.9:10000, restore status: &{IsRestoring:false LastRestored: Progress:0 Error:Failed to get restoring status on tcp://10.42.2.9:10000: failed to get restore status: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: timed out waiting for server handshake Filename: State: BackupURL:}"
2020-06-25T22:47:37.52468418Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test1\", UID:\"85ab9cef-f692-4ea9-a789-ccb8f0cf1947\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962946\", FieldPath:\"\"}): type: 'Normal' reason: 'Degraded' volume restore-test1 became degraded"
2020-06-25T22:47:37.549871643Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"restore-test1-e-443d795d\", UID:\"9d479698-901b-4f4c-a9f8-c87d20bf8b73\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962959\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' Removed unknown replica tcp://10.42.2.9:10000 from engine"
2020-06-25T22:47:37.581076659Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"restore-test1-e-443d795d\", UID:\"9d479698-901b-4f4c-a9f8-c87d20bf8b73\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962962\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' Removed unknown replica tcp://10.42.2.9:10000 from engine"
2020-06-25T22:47:37.64197717Z time="2020-06-25T22:47:37Z" level=debug msg="Requeue longhorn-system/restore-test1 due to error <nil> or Operation cannot be fulfilled on engines.longhorn.io \"restore-test1-e-443d795d\": the object has been modified; please apply your changes to the latest version and try again"
2020-06-25T22:47:37.642029361Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"restore-test1\", UID:\"85ab9cef-f692-4ea9-a789-ccb8f0cf1947\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962946\", FieldPath:\"\"}): type: 'Normal' reason: 'Degraded' volume restore-test1 became degraded"
2020-06-25T22:47:37.784471495Z time="2020-06-25T22:47:37Z" level=warning msg="Try to get requested log for restore-test1-e-443d795d on node khushboo-test-nfs-wk2"


......
2020-06-25T22:47:37.789378149Z time="2020-06-25T22:47:37Z" level=warning msg="restore-test1-e-443d795d: time=\"2020-06-25T22:47:37Z\" level=error msg=\"Backend tcp://10.42.3.6:10000 monitoring failed, mark as ERR: Ping timeout\""
2020-06-25T22:47:37.789386219Z time="2020-06-25T22:47:37Z" level=warning msg="restore-test1-e-443d795d: Jun 25 22:45:03.304758: ->10.42.3.6:10001 P[  0kB]     2279us"
2020-06-25T22:47:37.789390429Z time="2020-06-25T22:47:37Z" level=warning msg="restore-test1-e-443d795d: time=\"2020-06-25T22:47:37Z\" level=info msg=\"Set replica tcp://10.42.3.6:10000 to mode ERR\""


......
2020-06-25T22:47:37.79534286Z time="2020-06-25T22:47:37Z" level=warning msg="restore-test1-e-443d795d: time=\"2020-06-25T22:47:37Z\" level=error msg=\"Backend tcp://10.42.2.9:10000 monitoring failed, mark as ERR: Ping timeout\""
2020-06-25T22:47:37.79536049Z time="2020-06-25T22:47:37Z" level=warning msg="restore-test1-e-443d795d: time=\"2020-06-25T22:47:37Z\" level=info msg=\"Set replica tcp://10.42.2.9:10000 to mode ERR\""
```

The longhorn manager pod log on `khushboo-test-nfs-wk1`:
```
2020-06-25T22:47:32.421338715Z time="2020-06-25T22:47:32Z" level=debug msg="Prepare to delete instance restore-test1-r-ff4bb247"
2020-06-25T22:47:32.429883424Z time="2020-06-25T22:47:32Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"restore-test1-r-ff4bb247\", UID:\"353f8c25-b5ca-458a-be61-7727c66c32d3\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962911\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops restore-test1-r-ff4bb247"
```
The longhorn manager pod log on `khushboo-test-nfs-wk3`:
```
2020-06-25T22:47:37.553514238Z time="2020-06-25T22:47:37Z" level=debug msg="Prepare to delete instance restore-test1-r-ca9adbb5"
2020-06-25T22:47:37.570252812Z time="2020-06-25T22:47:37Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"restore-test1-r-ca9adbb5\", UID:\"57d8520e-2abd-4f50-98b2-4f44254bb550\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"962960\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops restore-test1-r-ca9adbb5"
```

**Comment by khushboo-rancher** [comment] 2020-06-26 17:03
I used attached script to disconnect the node ```khushboo-test-nfs-wk2``` and cluster config was 1 etc/control plane and 3 workers.
[network_down.sh.zip](https://github.com/longhorn/longhorn/files/4838237/network_down.sh.zip)

**Comment by khushboo-rancher** [comment] 2020-06-30 16:33
The reported issue is resolved and the intermittent issue https://github.com/longhorn/longhorn/issues/1327#issuecomment-649875711 is not getting reproduced again, closing this issue for now.

**Closed by khushboo-rancher** 2020-06-30 16:33 UTC
Labels: area/engine, area/manager, bug, priority/2, require/automation-e2e, require/manual-test-plan
