### ISSUE TITLE
[BUG] Backing Image deletion stuck if it's deleted during uploading process and bids is ready-for-transfer state

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#6086] opened 2023-06-08 06:49 UTC
## Describe the bug (🐛 if you encounter this issue)
backingimage and backingimagedatasource deletion got stuck, if the backing image is deleted during upload process and bids just changes to `ready-for-transfer` state

## To Reproduce
- Via Longhorn GUI, upload backing image from local ![bi_upload](https://github.com/longhorn/longhorn/assets/19387129/7309a630-78b3-4f4c-b24c-1962220cadf5)
- Delete backingimage as bids just turns into `ready-for-transfer` state 
  - Delete backingimage by `$ kubectl -n longhorn-system delete backingimage img1 --cascade=foreground` ![bi_delete_ready_for_transfer](https://github.com/longhorn/longhorn/assets/19387129/e7fb5e7f-e2a0-4178-adc0-253f94d36f56)
- Found backingimage stuck in deletion, the delete operation never finish ![bi_delete_stuck](https://github.com/longhorn/longhorn/assets/19387129/1f841f7b-e05f-4cf2-be6b-3e76e8728ab0)
- Found backingimagedatasource stuck in deletion, the delete operation never finish![bids_delete_stuck](https://github.com/longhorn/longhorn/assets/19387129/3e771cc7-a08b-49b3-a33f-72f4f24b32c0)
- Checking longhorn manager's log, it looped with log "backing image data source status is failed not failed-and-cleanup" ![longhorn_manager_log_looping](https://github.com/longhorn/longhorn/assets/19387129/8476c5e8-a3e5-447f-9b71-c0cdd9383176)

## Expected behavior
The backingimage related resource should be deleted without stucking

## Environment
Harvester v1.2.0 master-head with longhorn embedded, but it could be reproduced without Harvester's operations
 - Longhorn version: v1.4.2

## Additional Context
This is found by Harvester issue https://github.com/harvester/harvester/issues/4027

**Comment by ChanYiLin** [comment] 2023-06-14 07:31
Hi @WebberHuang1118 can you provide the yaml of the BackingImageDataSource and BackingImage CR by
```
kubectl get lhbi/XXX -n longhorn-system -oyaml
kubectl get lhbids/XXX -n longhorn-system -oyaml
``` 
thanks!

**Comment by ChanYiLin** [comment] 2023-06-14 07:51
I can reproduce the issue in my environment
It is because of the timing issue

1. We use lhbids.Spec.FileTransferred to check if this file is transferred and there is no tmp file left
2. if it is not transferred when the deletion happens, we then change the lhbids.Status.CurrentState to `Failed`
3. Then the longhorn-backing-manager controller will check and clean up the tmp file and change the lhbids.Status.CurrentState to `Failed-And-Cleanup`
```
		// Manager waits and fetches the 1st available file from BackingImageDataSource
		if !bids.Spec.FileTransferred {

			// If bids is failed and not transferred, orphan tmp file might be left on the host.
			// Clean up and set the state to failed-and-cleanup
			if bids.Status.CurrentState == longhorn.BackingImageStateFailed {
				if err := cli.Delete(bi.Name, bi.Status.UUID); err != nil {
					return err
				}
				bids.Status.CurrentState = longhorn.BackingImageStateFailedAndCleanUp
				if _, err = c.ds.UpdateBackingImageDataSourceStatus(bids); err != nil {
					return err
				}
				continue
			}
```
5. After the lhbids.Status.CurrentState is `Failed-And-Cleanup` then lbhi and lbhids can be deleted safely


However, in this case, when we deleted the lhbi the file was downloaded and being transferred (in the middle)
- The lhbids.Spec.FileTransferred was still False. So the lhbids controller can mark the lhbids `Failed`
- But lhbim.Status.BackingImageFileMap already got the info of the file and was syncing the file
hence, lhbim skip the check and has no chance to do the clean up and mark the lhbids to `Failed-And-Cleanup`
https://github.com/longhorn/longhorn-manager/blob/master/controller/backing_image_manager_controller.go#L639


One have to do the deletion in a very short period time to reproduce this issue, since the transfer only takes 1~2 sec.
But this issue does exist.

**Comment by WebberHuang1118** [comment] 2023-06-14 08:20
Hi @ChanYiLin,

YAML for BackingImage:
```
apiVersion: longhorn.io/v3beta2
kind: BackingImage
metadata:
  creationTimestamp: "2023-06-14T08:13:42Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-06-14T08:14:02Z"
  finalizers:
  - longhorn.io
  - foregroundDeletion
  generation: 3
  labels:
    longhorn.io/component: backing-image
    longhorn.io/managed-by: longhorn-manager
  name: img1
  namespace: longhorn-system
  resourceVersion: "558622"
  uid: 420616c9-b965-4515-b568-e2d52aea84e4
spec:
  checksum: ""
  disks:
    7a156f1f-a859-4fbf-bd1b-1d0d1235f7e1: ""
  imageURL: ""
  sourceParameters: {}
  sourceType: upload
status:
  checksum: 0a3de125c3207247334bffea9962680d76350b0bad5eb9fd72420d192c4e065c4b07aeefa84423f85e5a34ed1a2037435046f21927472ba977df74cf736dafa7
  diskDownloadProgressMap: null
  diskDownloadStateMap: null
  diskFileStatusMap:
    7a156f1f-a859-4fbf-bd1b-1d0d1235f7e1:
      lastStateTransitionTime: "2023-06-14T08:14:00Z"
      message: ""
      progress: 100
      state: ready-for-transfer
  diskLastRefAtMap:
    7a156f1f-a859-4fbf-bd1b-1d0d1235f7e1: "2023-06-14T08:13:42Z"
  ownerID: harvester-node-1
  size: 278200320
  uuid: 1c0c3051
```
YAML for BackingImageDataSource:
```
apiVersion: longhorn.io/v1beta2
kind: BackingImageDataSource
metadata:
  creationTimestamp: "2023-06-14T08:13:42Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2023-06-14T08:14:02Z"
  finalizers:
  - longhorn.io
  generation: 2
  name: img1
  namespace: longhorn-system
  ownerReferences:
  - apiVersion: longhorn.io/v1beta2
    blockOwnerDeletion: true
    controller: true
    kind: BackingImage
    name: img1
    uid: 420616c9-b965-4515-b568-e2d52aea84e4
  resourceVersion: "558638"
  uid: 55e7a85d-3a77-44de-90dd-22b36ea0fb92
spec:
  checksum: ""
  diskPath: /var/lib/harvester/defaultdisk
  diskUUID: 7a156f1f-a859-4fbf-bd1b-1d0d1235f7e1
  fileTransferred: false
  nodeID: harvester-node-1
  parameters: {}
  sourceType: upload
  uuid: 1c0c3051
status:
  checksum: 0a3de125c3207247334bffea9962680d76350b0bad5eb9fd72420d192c4e065c4b07aeefa84423f85e5a34ed1a2037435046f21927472ba977df74cf736dafa7
  currentState: failed
  ip: ""
  message: backing image is deleted, requesting manager to clean up the tmp file of
    backing image data source
  ownerID: harvester-node-1
  progress: 100
  runningParameters: {}
  size: 278200320
  storageIP: ""
```

**Comment by WebberHuang1118** [comment] 2023-06-14 08:49
Hi @ChanYiLin,

Following is the YAMl for lhbim:
```
apiVersion: v1
items:
- apiVersion: longhorn.io/v1beta2
  kind: BackingImageManager
  metadata:
    creationTimestamp: "2023-06-14T08:44:45Z"
    generation: 1
    labels:
      longhorn.io/component: backing-image-manager
      longhorn.io/disk-uuid: 740895c7-a00d-41ad-8758-62fe88e8cdf5
      longhorn.io/managed-by: longhorn-manager
      longhorn.io/node: harvester-node-0
    name: backing-image-manager-144f-7408
    namespace: longhorn-system
    resourceVersion: "585562"
    uid: 636a934e-c11d-42bb-bd1a-0c9f277e30e6
  spec:
    backingImages:
      img1: 71b5cf47
    diskPath: /var/lib/harvester/defaultdisk
    diskUUID: 740895c7-a00d-41ad-8758-62fe88e8cdf5
    image: longhornio/backing-image-manager:v1.4.2
    nodeID: harvester-node-0
  status:
    apiMinVersion: 3
    apiVersion: 3
    backingImageFileMap:
      img1:
        currentChecksum: 0a3de125c3207247334bffea9962680d76350b0bad5eb9fd72420d192c4e065c4b07aeefa84423f85e5a34ed1a2037435046f21927472ba977df74cf736dafa7
        directory: ""
        downloadProgress: 0
        message: ""
        name: img1
        progress: 100
        senderManagerAddress: ""
        sendingReference: 0
        size: 278200320
        state: ready
        url: ""
        uuid: 71b5cf47
    currentState: running
    ip: 10.52.0.194
    ownerID: harvester-node-0
    storageIP: 10.52.0.194
kind: List
metadata:
  resourceVersion: ""

```

Thanks

**Comment by ChanYiLin** [comment] 2023-06-14 10:19
Hi @WebberHuang1118 Thanks for the info
The results are the same as my testing [above](https://github.com/longhorn/longhorn/issues/6086#issuecomment-1590662594), might need to think if we can improve the process to avoid the stuck.

**Comment by innobead** [comment] 2023-06-20 11:21
@chriscchien There is no backport issue created for 1.4 for this issue, so please verify 1.4 together with 1.5 and master. Thanks.

**Comment by chriscchien** [comment] 2023-06-21 04:00
Hi @ChanYiLin, 

Follow test [steps](https://github.com/longhorn/longhorn/issues/6086#issue-1747197062) the backing image deletion stuck issue can not be reproduced on `master-head` and `v1.5.x`. 
However, in v1.4.x-head, I still hit this issue, could you help if I missed something? thank you
```
time="2023-06-21T03:36:09Z" level=info msg="Forwarding backing image upload request to URL http://10.42.1.17:8000/v1/file?action=upload&size=429916160"
10.42.0.1 - - [21/Jun/2023:03:36:09 +0000] "POST /v1/backingimages/test-backing?action=upload&size=429916160 HTTP/1.1" 200 0 "https://44.199.195.212/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/114.0.0.0 Safari/537.36"
time="2023-06-21T03:38:59Z" level=info msg="Starting to fetch the data source file from the backing image data source work directory /tmp/" backingImage=test-backing backingImageManager=backing-image-manager-fc1a-77ee controller=longhorn-backing-image-manager diskUUID=77eeba0a-3c95-47a7-a048-4e891e3f1575 node=ip-172-31-88-67 nodeID=ip-172-31-88-67
time="2023-06-21T03:38:59Z" level=info msg="Fetched the first file from BackingImageDataSource" backingImage=test-backing backingImageManager=backing-image-manager-fc1a-77ee controller=longhorn-backing-image-manager diskUUID=77eeba0a-3c95-47a7-a048-4e891e3f1575 node=ip-172-31-88-67 nodeID=ip-172-31-88-67
time="2023-06-21T03:38:59Z" level=info msg="Event(v1.ObjectReference{Kind:\"BackingImageManager\", Namespace:\"longhorn-system\", Name:\"backing-image-manager-fc1a-77ee\", UID:\"b73fb2ec-3325-4035-ae02-291529858650\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"2410\", FieldPath:\"\"}): type: 'Normal' reason: 'Fetching' Fetched the first file for backing image test-backing in disk 77eeba0a-3c95-47a7-a048-4e891e3f1575 on node ip-172-31-88-67"
time="2023-06-21T03:39:01Z" level=warning msg="Waiting until backing image data source is cleaned before removing the finalizer" backingImageName=test-backing controller=longhorn-backing-image node=ip-172-31-88-67
time="2023-06-21T03:39:01Z" level=warning msg="Error syncing Longhorn backing image longhorn-system/test-backing" error="failed to sync backing image for longhorn-system/test-backing: backing image data source status is ready-for-transfer not failed-and-cleanup"                                            
```

[supportbundle_d6cedefc-7e8b-4e84-a044-c3110b6248c9_2023-06-21T03-42-58Z.zip](https://github.com/longhorn/longhorn/files/11812015/supportbundle_d6cedefc-7e8b-4e84-a044-c3110b6248c9_2023-06-21T03-42-58Z.zip)

**Comment by innobead** [comment] 2023-06-21 06:14
@chriscchien It seems the 1.4.x image built failed. Please try it again after https://drone-publish.longhorn.io/longhorn/longhorn-manager/1493 is ready.

**Comment by chriscchien** [comment] 2023-06-21 07:06
Verified `pass` in 
- longhorn master (longhorn-manager `ec130d`)
- longhorn v1.5.x (longhorn-manager `c8092b`)
- longhorn v1.4.x (longhorn-manager `36c0a7`)

Tested with issue description [here](https://github.com/longhorn/longhorn/issues/6086#issue-1747197062), delete uploading backingimage in `ready-for-transfer` state will no longer stuck in longhorn master, v1.5.x and v.14.x branches

**Closed by chriscchien** 2023-06-21 07:06 UTC
Labels: kind/bug, area/manager, area/backing-image, backport/1.4.3
