### ISSUE TITLE
[FEATURE] Out of the box ReadWriteMany Support

### ISSUE THREAD

**Issue by wjimenez5271** [longhorn/longhorn#1182] opened 2020-04-13 16:06 UTC
As a user, there are often some use cases in my cluster that require ReadWriteMany storage support, and I would like to be able to offer that from my Longhorn Storage. An ideal solution would be an NFS exporter that can be turned on for any given longhorn volume. Understandably there would be disruption to the NFS service should the node running the active replica that is serving the request should fail. However as long as it was eventually consistent, whereby Longhorn quickly detects the node failure, and assign a new replica to serve NFS protocol, that would be acceptable.

**Comment by yasker** [comment] 2020-06-10 00:12
Duplicate of https://github.com/longhorn/longhorn/issues/1470

**Comment by yasker** [comment] 2020-11-12 02:40
Close as a duplicate.

**Closed by yasker** 2020-11-12 02:40 UTC
Labels: enhancement, feature/rwx
