### ISSUE TITLE
[BUG] longhorn-manager keep losing lease on longhorn-manager-upgrade-lock

### ISSUE THREAD

**Issue by liyimeng** [longhorn/longhorn#2769] opened 2021-07-04 00:31 UTC
**Describe the bug**

I have a cluster running longhorn for a some months, recently I restart longhorn manager for some configurations(changing overprovision rate from 100% to 300% )  Longhorn manager failed to come back.  only very few longhorn-manager pod become ready, others keep struggling like this   this https://github.com/longhorn/longhorn/issues/1379#issuecomment-665808161 

So the cluster is not not usable anymore. :(

What I observe is that those failing pods keep elect new lease for longhorn-manager-upgrade-lock. 

To my understanding, when the first pod up and get ready, it should be keep as leader until it crash. But this is not the case, somehow, longhorn ignore those ready pods as leader, keep select new ones, and then fail "forever"

**To Reproduce**

Not sure, this is just suddenly happen. 

**Expected behavior**

longhorn-manager pods should be possible to restart can get ready. 

**Log**
If applicable, add the Longhorn managers' log when the issue happens.

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.0
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.19.5
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 30
 - Node config
   - OS type and version: k3os
   - CPU per node: 8 
   - Memory per node: 128G
   - Disk type(e.g. SSD/NVMe): ssd
   - Network bandwidth between the nodes: 10G
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 300

**Additional context**

**Comment by liyimeng** [comment] 2021-07-04 06:50
This is likely related to https://github.com/longhorn/longhorn/issues/2582

**Comment by c3y1huang** [comment] 2021-07-05 03:20
@liyimeng glad you are able to resolve [this](https://github.com/longhorn/longhorn/issues/2582#issuecomment-873539050). We would like to have a better understanding of the issue, but it's going to be hard without reproducing steps. It will be really helpful if you can attach the support bundle here or send it to longhorn-support-bundle@Suse.com.

**Comment by shuo-wu** [comment] 2021-07-06 03:31
When the 1st longhorn manager pod finishes the upgrade, it will give up its leadership. The log `Upgrade leader lost` you found may be triggered by this mechanism. Maybe Longhorn team needs to re-check this logic:
https://github.com/longhorn/longhorn-manager/blob/27c93ca97bf6966c7a946ef223366f3ac6e70d62/upgrade/upgrade.go#L100

**Comment by liyimeng** [comment] 2021-07-06 05:03
> @liyimeng glad you are able to resolve [this](https://github.com/longhorn/longhorn/issues/2582#issuecomment-873539050). We would like to have a better understanding of the issue, but it's going to be hard without reproducing steps. It will be really helpful if you can attach the support bundle here or send it to [longhorn-support-bundle@Suse.com](mailto:longhorn-support-bundle@Suse.com) with the issue number.

@c3y1huang Sorry, it is likely too late to collect log now. since @shuo-wu know this pretty well, log might not need either.

**Comment by c3y1huang** [comment] 2021-07-06 05:24
@shuo-wu can you confirm if this is a duplicate of https://github.com/longhorn/longhorn/issues/2582? If it is then we should be able to close this one.

**Comment by shuo-wu** [comment] 2021-07-06 06:48
Yes. Let's discuss this upgrade issue in that ticket and close this:
https://github.com/longhorn/longhorn/issues/2582#issuecomment-874504456

**Closed by shuo-wu** 2021-07-06 06:48 UTC
Labels: kind/bug
