### ISSUE TITLE
[IMPROVEMENT] Busrt ISCSI Connection Errors, and IM Pod Restarting to make LH Volume disconnection

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#9851] opened 2024-11-25 07:25 UTC
## Describe the bug

Burst iSCSI connection errors occur in a short period and after a few seconds, the IM pod is deleted and re-created. This happened to all the nodes and made the LH engines and replicas disconnected.

From one node's log for example:

iSCSI errors in the Kernel log
```
Nov 21 00:54:02 node-xxx kernel:  connection438:0: detected conn error (1020)
Nov 21 00:54:02 node-xxx kernel:  connection437:0: detected conn error (1020)
Nov 21 00:54:02 node-xxx kernel:  connection436:0: detected conn error (1020)
Nov 21 00:54:02 node-xxx kernel:  connection435:0: detected conn error (1020)
Nov 21 00:54:02 node-xxx kernel:  connection434:0: detected conn error (1020)
Nov 21 00:54:02 node-xxx kernel:  connection433:0: detected conn error (1020)
Nov 21 00:54:02 node-xxx kernel:  connection432:0: detected conn error (1020)
....
Nov 21 00:54:02 node-xxx kernel:  connection275:0: detected conn error (1020) 
```

After five seconds, the IM pod is deleted
```
2024-11-21T00:54:07.386734505Z 2024-11-21T00:54:07Z [verbose] deleted pod [longhorn-system/instance-manager-a143f543db5184c134735c76b2c551fe]
```

## Expected behavior

The IM pod shouldn't be restarted to make all the engines and replicas disconnected

## Environment

 - Longhorn version: v1.6.2
 - Harvester version: v1.3.2
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 1
 - Number of Longhorn volumes in the cluster: 1064

## Additional context

- There are massive numbers of engines and replicas on each node/disk,  for each node, all replicas are located on a single SSD disk.
  - 1st node has 599 replicas on a single SSD disk
  - 2nd node has 538 replicas on a single SSD disk
  - 3rd node has 419 replicas on a single SSD disk
  - 4th node has 266 replicas on a single SSD disk
- Related to SURE-9408

**Comment by derekbit** [comment] 2024-11-25 07:39
cc @ChanYiLin @mantissahz @PhanLe1010 @shuo-wu @c3y1huang @innobead

**Comment by derekbit** [comment] 2024-11-25 11:30
Just checked the issue with @WebberHuang1118 
1. Massive LH volume error and iSCSI connection errors (WHY?)
2. After 5 seconds (possible), the instance-manager pod is deleted, but CR is not deleted
3. According to the deleted IM pod name, the instance-manager pod was using default instance-manager image (v1.6.2)
4. Why  LH controller needs to delete IM pod that is using v1.6.2 image

@mantissahz Please help clarify item 3 and 4 as well. Thank you.

**Comment by WebberHuang1118** [comment] 2024-11-26 07:30
I tried to figure out the timeline of the disconnected volumes, following is an example for volume `pvc-c8492121-f657-481f-b281-200f4e406194`:
- Volume started with iSCSI connection ID `193`
  ```
  Nov 21 00:31:32 hci-8xxx iscsid[40435]: iscsid: Connection193:0 to [target: iqn.2019-10.io.longhorn:pvc-c8492121-f657-481f-b281-200f4e406194, portal: 10.52.0.43,3260] through [iface: default] is operational now
  ```
- Volume attached as device `sdh`
  ```
  Nov 21 00:31:32 hci-8xxx kernel: sd 16:0:0:1: [sdh] 125829120 512-byte logical blocks: (64.4 GB/60.0 GiB)
  Nov 21 00:31:32 hci-8xxx kernel: sd 16:0:0:1: [sdh] Write Protect is off
  Nov 21 00:31:32 hci-8xxx kernel: sd 16:0:0:1: [sdh] Mode Sense: 69 00 10 08
  Nov 21 00:31:32 hci-8xxx kernel: sd 16:0:0:1: [sdh] Write cache: disabled, read cache: enabled, supports DPO and FUA
  ```
- Burst iSCSI connection errors occurred, including connection `193`
  ```
  .....
  Nov 21 00:54:02 hci-8xxx kernel:  connection193:0: detected conn error (1020)
  ....
  Nov 21 00:54:02 hci-8xxx kernel:  connection275:0: detected conn error (1020)
  ```
- Disk `sdh` had the medium error
  ```
  Nov 21 00:54:02 hci-8xxx kernel: sd 16:0:0:1: [sdh] tag#21 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=0s
  Nov 21 00:54:02 hci-8xxx kernel: sd 16:0:0:1: [sdh] tag#21 Sense Key : Medium Error [current] 
  Nov 21 00:54:02 hci-8xxx kernel: sd 16:0:0:1: [sdh] tag#21 Add. Sense: Unrecovered read error
  Nov 21 00:54:02 hci-8xxx kernel: sd 16:0:0:1: [sdh] tag#21 CDB: Write(10) 2a 00 05 ab 2e 40 00 00 08 00
  ```
- After a few seconds, the related IM pod was deleted (the logs were from Harvester's Whereabouts deployment)
  ```
  2024-11-21T00:54:07.386734505Z 2024-11-21T00:54:07Z [verbose] deleted pod [longhorn-system/instance-manager-a143f543db5184c134735c76b2c551fe]
  ```

In this environment, I found lots of volume with only one replica:
- #volumes with 1 replica: 583
- #volumes with 2 replicas: 201
- #volumes with 3 replicas: 279

and there are massive replicas only distributed to four disks (266, 538, 419, and 266 respectively).

With such architecture, during heavy I/O loading, is it likely to bring engine timeout (related to the iSCSI connection error)? especially for the volumes that only have one replica, which could be fragile.

For the IM pods to restart, from my code reading, it seems [LH proactively restarts the IM pod only if there is no running instance in the IM](https://github.com/longhorn/longhorn-manager/blob/dcd5164185d7130732f72bb2e978dfdc0338acd1/controller/instance_manager_controller.go#L450-L487). 

So can we assume that while the IM pod was deleted, all its engines and replicas were disconnected? 

Many thanks cc @derekbit @ChanYiLin @PhanLe1010 @c3y1huang @shuo-wu

**Comment by WebberHuang1118** [comment] 2024-11-26 09:42
I also notice the [Guaranteed Instance Manager CPU setting](https://longhorn.io/docs/1.6.2/references/settings/#guaranteed-instance-manager-cpu) with the equation:
```
Guaranteed Instance Manager CPU = The estimated max Longhorn volume engine and replica count on a node * 0.1 / The total allocatable CPUs on the node * 100.
```
The above could imply:
```
The estimated max Longhorn volume engine and replica count on a node  = Guaranteed Instance Manager CPU * The total allocatable CPUs on the node / 10
```
In this environment, the `Guaranteed Instance Manager CPU = 12 (default)` and `The total allocatable CPUs on the node = 88 cores`, we can obtain the `The estimated max Longhorn volume engine and replica count on a node = 12 * 88 / 10 = 105.6 instances `.

However, all the IMs have about 400 - 600 running instances, the number of running instances is much more than the estimated one (around 105 instances). Will this affect IM pods' stability?

Many thanks cc @derekbit @ChanYiLin @PhanLe1010 @c3y1huang @shuo-wu @mantissahz @innobead

**Comment by mantissahz** [comment] 2024-11-29 08:31
>3. According to the deleted IM pod name, the instance-manager pod was using default instance-manager image (v1.6.2)
>4. Why LH controller needs to delete IM pod that is using v1.6.2 image

@derekbit,
3. all instance-manager pods are using the v1.6.2 image.
4. No sure that LH controllers deleted the IM pods because logs from `2024-11-21T00:21:21` to `2024-11-21T14:21` are saved in the two provided support bundles.

**Comment by derekbit** [comment] 2024-11-29 09:00
> > 3. According to the deleted IM pod name, the instance-manager pod was using default instance-manager image (v1.6.2)
> > 4. Why LH controller needs to delete IM pod that is using v1.6.2 image
> 
> @derekbit, 3. all instance-manager pods are using the v1.6.2 image. 4. No sure that LH controllers deleted the IM pods because logs from `2024-11-21T00:21:21` to `2024-11-21T14:21` are not saved in the two provided support bundles.

Is it possible that the user changed the danger zone setting? BTW, do we record the time that setting takes effect?

**Comment by mantissahz** [comment] 2024-11-29 12:57
>Is it possible that the user changed the danger zone setting?

If the danger zone setting is modified and `there is no attached volume`, the instance manager pod will be restarted.

>BTW, do we record the time that setting takes effect?

Longhorn does not record when the modified setting takes effect, but we could check if the settings were modified recently.

All danger zone settings are NOT modified after 2024-09-07 by `metadata.managedFields`
```yaml
- apiVersion: longhorn.io/v1beta2
  kind: Setting
  metadata:
    annotations:
      longhorn.io/configmap-resource-version: "809606925"
    creationTimestamp: "2023-10-03T16:47:26Z"
    generation: 1
    managedFields:
    - apiVersion: longhorn.io/v1beta2
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:longhorn.io/configmap-resource-version: {}
        f:value: {}
      manager: longhorn-manager
      operation: Update
      time: "2024-09-07T20:44:00Z"
    name: taint-toleration
    namespace: longhorn-system
    resourceVersion: "809613858"
    uid: 056abd77-a86f-474e-8b55-fdc4add8c27e
  value: kubevirt.io/drain:NoSchedule
```

**Comment by derekbit** [comment] 2024-11-29 13:39
> Longhorn does not record when the modified setting takes effect, but we could check if the settings were modified recently.

@mantissahz 
Can you create an IMPROVEMENT ticket for recording timestamp? Thanks.

**Comment by derekbit** [comment] 2024-11-29 13:49
> > Is it possible that the user changed the danger zone setting?
> 
> If the danger zone setting is modified and `there is no attached volume`, the instance manager pod will be restarted.
> 

IIUC, the instance manager pod won't be restarted immediately. There are some conditions for restarting an instance-manager pod after modifying the danger zone setting. Could you elaborate more on the conditions?

**Comment by mantissahz** [comment] 2024-12-02 02:11
>IIUC, the instance manager pod won't be restarted immediately. There are some conditions for restarting an instance-manager pod after modifying the danger zone setting. Could you elaborate more on the conditions?

The danger settings can be able to be modified anyway:
1. The setting controller will try to restart instance pods if there is no volume attached (for v1/v2 engine-related settings, it will check if there are corresponding volumes attached, e.g. modifying the setting `guaranteed-instance-manager-cpu` will only check if there are v1 volumes attached.)
2. If the setting controller does not restart the instance pods and the danger setting is modified, it will not restart the instance pods until there is no running instance including engines or replicas in the instance pods (reconciling in the instance manager controller).

The detailed LEP is here https://github.com/longhorn/longhorn/pull/7455 or our doc https://longhorn.io/docs/1.6.0/references/settings/#danger-zone

**Comment by WebberHuang1118** [comment] 2024-12-02 02:42
Around the time IM pods were deleted, from containerd and kubelet' logs, we could find all the `instance-manager` containers terminated first, then brought other situations. 

All the IMs' containers/pods went through the following phases:
- IMs' containers terminated and started to be cleaned up
- iSCSI connection errors occurred
- IMs' pod was deleted
- New pods were created for IMs

Taking IM `instance-manager-29434001a60839c96b6f5b396af23432` as an example:
- Origin pod UID: `9404a730-7334-4788-a9ad-7892138b8c92`
- Origin container ID: `548c02c5bc17426da586373f902e8d5811d5efe4e45d5fbd0495920626d014d9`
- New pod UID: `c382e48e-4613-4c3e-a224-0df7809fffba`
- New container ID: `2184ccc5e18b722d332f6ee0c544233c2c8a5fdd4baa751f012fc1700274b8da`

Following is the timeline for it:
- IM container suddenly terminated
  ```
  time="2024-11-21T06:12:20.651526777Z" level=info msg="shim disconnected" id=548c02c5bc17426da586373f902e8d5811d5efe4e45d5fbd0495920626d014d9 namespace=k8s.io
  time="2024-11-21T06:12:20.651603253Z" level=warning msg="cleaning up after shim disconnected" id=548c02c5bc17426da586373f902e8d5811d5efe4e45d5fbd0495920626d014d9 namespace=k8s.io
  time="2024-11-21T06:12:21.819863412Z" level=info msg="Container to stop \"548c02c5bc17426da586373f902e8d5811d5efe4e45d5fbd0495920626d014d9\" must be in running or unknown state, current state \"CONTAINER_EXITED\""
  ```
- iSCSI connection errors occurred (it seems for the engines)
  ```
  Nov 21 06:12:20 hci-ddxxxx kernel:  connection2340:0: detected conn error (1020)
  ....
  ....
  Nov 21 06:12:20 hci-ddxxxx kernel:  connection1:0: detected conn error (1020)
  ```
- Harvester's Whereabouts controller the found IM pod was going to be deleted
  ```
  2024-11-21T06:12:22.228430700Z 2024-11-21T06:12:22Z [verbose] deleted pod [longhorn-system/instance-manager-29434001a60839c96b6f5b396af23432]
  ```
- IM's container was removed, which was in a stale state
  ```
  E1121 06:12:22.267085    3492 cpu_manager.go:395] "RemoveStaleState: removing container" podUID="9404a730-7334-4788-a9ad-7892138b8c92" containerName="instance-manager"
  I1121 06:12:22.267265    3492 memory_manager.go:346] "RemoveStaleState removing state" podUID="9404a730-7334-4788-a9ad-7892138b8c92" containerName="instance-manager"	
  ```
- The new pod for IM was created
  ```
  024-11-21 06:12:22.687 [INFO][83928] k8s.go 386: Populated endpoint ContainerID="2184ccc5e18b722d332f6ee0c544233c2c8a5fdd4baa751f012fc1700274b8da" Namespace="longhorn-system" Pod="instance-manager-29434001a60839c96b6f5b396af23432" WorkloadEndpoint="hci--ddpxzv2-k8s-instance--manager--29434001a60839c96b6f5b396af23432-eth0" endpoint=&v3.WorkloadEndpoint{TypeMeta:v1.TypeMeta{Kind:"WorkloadEndpoint", APIVersion:"projectcalico.org/v3"}, ObjectMeta:v1.ObjectMeta{Name:"hci--ddpxzv2-k8s-instance--manager--29434001a60839c96b6f5b396af23432-eth0", GenerateName:"", Namespace:"longhorn-system", SelfLink:"", UID:"c382e48e-4613-4c3e-a224-0df7809fffba", ResourceVersion:"1007188361", Generation:0, CreationTimestamp:time.Date(2024, time.November, 21, 6, 12, 22, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"longhorn.io/component":"instance-manager", "longhorn.io/data-engine":"v1", "longhorn.io/instance-manager-image":"imi-0b5e7e43", "longhorn.io/instance-manager-type":"aio", "longhorn.io/managed-by":"longhorn-manager", "longhorn.io/node":"hci-ddpxzv2", "projectcalico.org/namespace":"longhorn-system", "projectcalico.org/orchestrator":"k8s", "projectcalico.org/serviceaccount":"longhorn-service-account"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v3.WorkloadEndpointSpec{Orchestrator:"k8s", Workload:"", Node:"hci-ddpxzv2", ContainerID:"", Pod:"instance-manager-29434001a60839c96b6f5b396af23432", Endpoint:"eth0", ServiceAccountName:"longhorn-service-account", IPNetworks:[]string{"10.52.1.21/32"}, IPNATs:[]v3.IPNAT(nil), IPv4Gateway:"", IPv6Gateway:"", Profiles:[]string{"kns.longhorn-system", "ksa.longhorn-system.longhorn-service-account"}, InterfaceName:"cali3761e9cee54", MAC:"", Ports:[]v3.WorkloadEndpointPort(nil), AllowSpoofedSourcePrefixes:[]string(nil)}}
  ```
  
Even the SB doesn't have early LH logs, however, it seems [LH doesn't log much about the reason for the IM pods' restarting](https://github.com/longhorn/longhorn-manager/blob/dcd5164185d7130732f72bb2e978dfdc0338acd1/controller/instance_manager_controller.go#L450-L487)

Is there any other situation that can make the IM pod restart except for the danger zone setting? 
Regarding this env has lots of running instances in a single IM, could it affect the stability of the instance-manager pods?

Thanks cc @derekbit @ChanYiLin @mantissahz @PhanLe1010 @bk201

**Comment by derekbit** [comment] 2024-12-02 11:36
> Even the SB doesn't have early LH logs, however, it seems [LH doesn't log much about the reason for the IM pods' restarting](https://github.com/longhorn/longhorn-manager/blob/dcd5164185d7130732f72bb2e978dfdc0338acd1/controller/instance_manager_controller.go#L450-L487)

@mantissahz We should log it. Please create a ticket for the improvement. Thanks.

**Comment by derekbit** [comment] 2024-12-02 11:44
@WebberHuang1118
Another thought
```
    livenessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - test $(nc -zv localhost 8500 > /dev/null 2>&1 && nc -zv localhost 8501 >
          /dev/null 2>&1 && nc -zv localhost 8502 > /dev/null 2>&1 && nc -zv localhost
          8503 > /dev/null 2>&1; echo $?) -eq 0
```
Caused by the failure of live probing? Is it possible?

**Comment by mantissahz** [comment] 2024-12-03 03:14
>@mantissahz We should log it. Please create a ticket for the improvement. Thanks.

The improvement ticket is created https://github.com/longhorn/longhorn/issues/9886. cc @WebberHuang1118

**Comment by WebberHuang1118** [comment] 2024-12-03 07:23
> @WebberHuang1118 Another thought
> 
> ```
>     livenessProbe:
>       exec:
>         command:
>         - /bin/sh
>         - -c
>         - test $(nc -zv localhost 8500 > /dev/null 2>&1 && nc -zv localhost 8501 >
>           /dev/null 2>&1 && nc -zv localhost 8502 > /dev/null 2>&1 && nc -zv localhost
>           8503 > /dev/null 2>&1; echo $?) -eq 0
>       failureThreshold: 3
>       initialDelaySeconds: 3
>       periodSeconds: 5
>       successThreshold: 1
>       timeoutSeconds: 4
> ```
> 
> Caused by the failure of live probing? Is it possible?

Hi @derekbit,

As intentionally making the IM containers' liveness probe faulty, the IM pod was terminated and restarted and there are similar logs as the user's environment. 

The following are the steps:
- Updating LH manager daemonset from [this branch](https://github.com/WebberHuang1118/longhorn-manager/tree/v1.6.2-faulty-liveness-probe)
  - This will deploy IM pods with a faulty liveness probe function
- Deleting IM pods, and IM pods will be restarted with the faulty version
- Creating volumes, mounting the volumes to pods, and issuing I/Os to volumes continuously
- After around 15 seconds, finding the IM container terminated
  ```
  time="2024-12-03T04:35:42.543215248Z" level=info msg="shim disconnected" id=aa1058ea2717c24f9d2d3b393300bddc9bff7ca787979a1a02840af8d06df9e2 namespace=k8s.io
  time="2024-12-03T04:35:42.543275589Z" level=warning msg="cleaning up after shim disconnected" id=aa1058ea2717c24f9d2d3b393300bddc9bff7ca787979a1a02840af8d06df9e2 namespace=k8s.io
  time="2024-12-03T04:35:43.996768612Z" level=info msg="Container to stop \"e4e280068a12081293d2f1844f13ba33a704d274e8c4162304bd473ae9af1610\" must be in running or unknown state, current state \"CONTAINER_EXITED\""
  ```
- LH disk had **Medium error** and iSCSI connection errors occurred, for example
  ```
  Dec 03 04:35:27 harvester-node-0 kernel: sd 5:0:0:1: [sdd] tag#111 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=15s
  Dec 03 04:35:27 harvester-node-0 kernel: sd 5:0:0:1: [sdd] tag#111 FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_OK cmd_age=15s
  Dec 03 04:35:27 harvester-node-0 kernel: sd 5:0:0:1: [sdd] tag#111 Sense Key : Medium Error [current] 
  Dec 03 04:35:27 harvester-node-0 kernel: sd 5:0:0:1: [sdd] tag#111 Add. Sense: Unrecovered read error
  Dec 03 04:35:27 harvester-node-0 kernel: sd 5:0:0:1: [sdd] tag#111 CDB: Read(10) 28 00 00 1f ff 80 00 00 08 00
  
  Dec 03 04:35:42 harvester-node-0 kernel:  connection290:0: detected conn error (1020)
  Dec 03 04:37:05 harvester-node-0 kernel:  connection292:0: detected conn error (1020)
  Dec 03 04:37:05 harvester-node-0 kernel:  connection294:0: detected conn error (1020)
  ```
- Harvester's Whereabouts controller found the IM pod was going to be deleted
  ```
  2024-12-03T04:37:05Z [verbose] deleted pod [longhorn-system/instance-manager-7035522e27a25aa5efeecbbdafe4ff99]
  ```
- The new pod for IM was restarted
  ```
  2024-12-03 04:37:05.463 [INFO][2355] k8s.go 386: Populated endpoint ContainerID="c0e91cd5abfca007bd20e3534fc1f8000bb246afaca76cf547931667321f99a5" Namespace="longhorn-system" Pod="instance-manager-7035522e27a25aa5efeecbbdafe4ff99" WorkloadEndpoint="harvester--node--0-k8s-instance--manager--7035522e27a25aa5efeecbbdafe4ff99-eth0" endpoint=&v3.WorkloadEndpoint{TypeMeta:v1.TypeMeta{Kind:"WorkloadEndpoint", APIVersion:"projectcalico.org/v3"}, ObjectMeta:v1.ObjectMeta{Name:"harvester--node--0-k8s-instance--manager--7035522e27a25aa5efeecbbdafe4ff99-eth0", GenerateName:"", Namespace:"longhorn-system", SelfLink:"", UID:"93bb3a7d-4af7-4444-b0f9-a30c937ba5f6", ResourceVersion:"163961", Generation:0, CreationTimestamp:time.Date(2024, time.December, 3, 4, 37, 5, 0, time.Local), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string{"longhorn.io/component":"instance-manager", "longhorn.io/data-engine":"v1", "longhorn.io/instance-manager-image":"imi-0b5e7e43", "longhorn.io/instance-manager-type":"aio", "longhorn.io/managed-by":"longhorn-manager", "longhorn.io/node":"harvester-node-0", "projectcalico.org/namespace":"longhorn-system", "projectcalico.org/orchestrator":"k8s", "projectcalico.org/serviceaccount":"longhorn-service-account"}, Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, Spec:v3.WorkloadEndpointSpec{Orchestrator:"k8s", Workload:"", Node:"harvester-node-0", ContainerID:"", Pod:"instance-manager-7035522e27a25aa5efeecbbdafe4ff99", Endpoint:"eth0", ServiceAccountName:"longhorn-service-account", IPNetworks:[]string{"10.52.0.208/32"}, IPNATs:[]v3.IPNAT(nil), IPv4Gateway:"", IPv6Gateway:"", Profiles:[]string{"kns.longhorn-system", "ksa.longhorn-system.longhorn-service-account"}, InterfaceName:"calid5df8c2f04c", MAC:"", Ports:[]v3.WorkloadEndpointPort(nil), AllowSpoofedSourcePrefixes:[]string(nil)}}
  ```

IIUC, once the liveness probe function can't respond in 15 seconds, the K8S controller will likely kill the IM pods, especially when the IM pod is under heavy loading, like in the user's environment.

Should the IM pod make some adjustments to the liveness probe parameters? 

Many thanks cc @derekbit @ChanYiLin @PhanLe1010 @mantissahz

**Comment by derekbit** [comment] 2024-12-04 04:53
@ChanYiLin @WebberHuang1118 @PhanLe101 @innobead 
What's the action item for the ticket? Increase the liveness probe timeout as we discussed?

**Comment by ChanYiLin** [comment] 2024-12-04 05:54
Ok, lets suggest increase the liveness probe timeout for this issue
And see if community encounters the same issue and has more information.

**Comment by WebberHuang1118** [comment] 2024-12-05 08:26
An information update,

As deploy LH manager with [shorter and stricter liveness probe timeout](https://github.com/WebberHuang1118/longhorn-manager/tree/v1.6.2-shorten-liveness-probe), and creating 300+ PVCs with running I/O using [this script](https://github.com/WebberHuang1118/misc-tools/blob/main/volumes/gradual-create-pods.sh) on a single node Harvester.

The IM pod recreation can be found, and [having a similar situation as the user's](https://github.com/longhorn/longhorn/issues/9851#issuecomment-2510447442).

**Comment by derekbit** [comment] 2024-12-12 12:20
@ChanYiLin Let's move it to ready-for-testing first. The doc part can be merged later. Thank you.

**Comment by derekbit** [comment] 2024-12-18 03:30
Move the issue to `IMPROVMENT` instead.

cc @WebberHuang1118 @innobead

**Comment by chriscchien** [comment] 2024-12-23 04:53
Close this ticket as did not see cascading failures on daily regression
-  master build [1135](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/1135/#showFailuresLink)
- v1.8.x build [5](https://ci.longhorn.io/job/public/job/v1.8.x/job/v1.8.x-longhorn-tests-sles-amd64/5/#showFailuresLink)

**Closed by chriscchien** 2024-12-23 04:53 UTC
Labels: component/longhorn-instance-manager, priority/1, require/knowledge-base, area/stability, kind/improvement, require/qa-review-coverage, require/backport, backport/1.6.4, backport/1.7.3
