### ISSUE TITLE
[BUG][v1.7.2] Memory Leak in longhorn-instance-manager Pods When Using Engine v2

### ISSUE THREAD

**Issue by jangseon-ryu** [longhorn/longhorn#9927] opened 2024-12-09 01:58 UTC
## Describe the bug
There is a memory leak issue in longhorn-instance-manager pods that handle engine processes when using Engine v2. This issue is not observed in all longhorn-instance-manager pods. Specifically:

- The memory leak occurs only in longhorn-instance-manager pods responsible for running engine processes 
- longhorn-instance-manager pods that handle replica processes (data storage) do not exhibit memory leaks.

## To Reproduce
1. Deploy a Longhorn cluster with Engine v2 enabled.
2. Create a volume and attach it to a pod.
3. Monitor the memory usage of the longhorn-instance-manager pod running the engine process.

## Expected behavior
- longhorn-instance-manager pods handling engine processes should maintain stable memory usage.
- Temporary memory spikes during high workloads are expected but should return to baseline after workloads complete.

## Environment

 - Longhorn version: v1.7.2
 - Impacted volume (PV):
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:v1.23.15
   - Number of control plane nodes in the cluster:1
   - Number of worker nodes in the cluster:12
 - Node config
   - OS type and version:RHEL 8.8
   - Kernel version:5.15.27
   - CPU per node:48
   - Memory per node:128G
   - Disk type (e.g. SSD/NVMe/HDD):SSD
   - Network bandwidth between the nodes (Gbps):10Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):Baremetal
 - Number of Longhorn volumes in the cluster:2 

## Additional context
- Over the course of 1 week, the memory usage of an engine-handling longhorn-instance-manager pod increases by approximately 1GB, even with minimal or normal workloads.
<img width="1033" alt="image" src="https://github.com/user-attachments/assets/4d5fa624-c22a-47ee-8b87-a075ccd14901">

- Upon performing memory profiling, the heap usage increase was traced to NSFileLock.
```
(pprof) top
Showing nodes accounting for 694.13MB, 96.71% of 717.71MB total
Dropped 180 nodes (cum <= 3.59MB)
Showing top 10 nodes out of 36
      flat  flat%   sum%        cum   cum%
  364.16MB 50.74% 50.74%   364.16MB 50.74%  runtime.malg
  112.53MB 15.68% 66.42%   112.53MB 15.68%  github.com/longhorn/nsfilelock.(*NSFileLock).Lock.func2
   74.01MB 10.31% 76.73%   118.51MB 16.51%  github.com/longhorn/nsfilelock.(*NSFileLock).Lock
   44.50MB  6.20% 82.93%    44.50MB  6.20%  os.newFile
   36.50MB  5.09% 88.02%    36.50MB  5.09%  time.Sleep
      19MB  2.65% 90.66%       19MB  2.65%  google.golang.org/grpc/internal/transport.(*controlBuffer).get
      18MB  2.51% 93.17%       18MB  2.51%  google.golang.org/grpc/internal/transport.(*http2Server).keepalive
   13.50MB  1.88% 95.05%    14.50MB  2.02%  google.golang.org/grpc/internal/grpcsync.(*CallbackSerializer).run
    6.93MB  0.97% 96.02%     6.93MB  0.97%  runtime.allgadd
       5MB   0.7% 96.71%        5MB   0.7%  google.golang.org/grpc.(*pickerWrapper).pick
```
![image](https://github.com/user-attachments/assets/0539e02c-1a0e-4f9f-8eb3-84e42de790a1)

- Further investigation indicates that the memory leak is likely caused by inactive goroutines that remain in memory and are not properly cleaned up during the lifecycle of NSFileLock.
![image](https://github.com/user-attachments/assets/aaa5636a-6a33-4739-97b7-5655b090714d)

## Workaround and Mitigation
Manually restart the affected longhorn-instance-manager pod to temporarily release memory and clear inactive goroutines

**Comment by derekbit** [comment] 2024-12-09 02:13
cc @shuo-wu @PhanLe1010 @DamiaSan

**Comment by c3y1huang** [comment] 2024-12-09 08:33
In v1.7.x we are using `github.com/longhorn/nsfilelock`, while starting from v1.8.0 we switched to the lock implementation from `go-common-lib`. The two have different implementations, it might be worth checking if this is reproducible in v1.8.0.

**Comment by c3y1huang** [comment] 2024-12-09 09:13
@jangseon-ryu could you help check if this issue is reproducible with v1.8.x? You can use the images listed in  https://github.com/longhorn/longhorn/blob/master/deploy/longhorn-images.txt.

**Comment by jangseon-ryu** [comment] 2024-12-09 09:23
@c3y1huang 
Sure, I will share the results after testing.

**Comment by jangseon-ryu** [comment] 2024-12-10 04:53
@c3y1huang 
I attempted to conduct the reproduction test using the master-head version as requested. However, I encountered issues during the setup process, and the deployment was unsuccessful. Below are the details:

#### Test Progress
- Attempted to upgrade from v1.7.2 to master-head → Failed
- Attempted a clean installation with master-head → The same issue occurred

#### Issue
- The longhorn-instance-manager v2 pod keeps entering a create-delete loop 

#### Manager log
```
time="2024-12-10T04:36:41Z" level=info msg="Creating instance manager pod instance-manager-91996e0b81585b78a282e88f1bf0c8f3 with args [instance-manager --spdk-log all --spdk-cpumask 0x1 --enable-spdk --debug daemon --spdk-enabled --listen 0.0.0.0:8500]" func="controller.(*InstanceManagerController).createInstanceManagerPodSpec" file="instance_manager_controller.go:1429" controller=longhorn-instance-manager node=worker7
time="2024-12-10T04:36:41Z" level=info msg="Creating instance manager pod" func="controller.(*InstanceManagerController).createInstanceManagerPod" file="instance_manager_controller.go:1310" controller=longhorn-instance-manager instanceManager=instance-manager-91996e0b81585b78a282e88f1bf0c8f3 node=worker7 nodeID=worker7
W1210 04:36:41.855222       1 logging.go:55] [core] [Channel #312 SubChannel #313]grpc: addrConn.createTransport failed to connect to {Addr: "10.42.0.34:8500", ServerName: "10.42.0.34:8500", }. Err: connection error: desc = "transport: Error while dialing: dial tcp 10.42.0.34:8500: connect: connection refused"
time="2024-12-10T04:36:41Z" level=error msg="Failed to sync Longhorn instance manager" func=controller.handleReconcileErrorLogging file="utils.go:79" InstanceManager=longhorn-system/instance-manager-91996e0b81585b78a282e88f1bf0c8f3 controller=longhorn-instance-manager error="failed to sync instance manager for longhorn-system/instance-manager-91996e0b81585b78a282e88f1bf0c8f3: failed to check Instance Manager Process Manager Service Client connection for instance-manager-91996e0b81585b78a282e88f1bf0c8f3 IP 10.42.0.34: rpc error: code = Unavailable desc = connection error: desc = \"transport: Error while dialing: dial tcp 10.42.0.34:8500: connect: connection refused\"" node=worker7
time="2024-12-10T04:36:41Z" level=info msg="Instance manager state is updated from starting to error after syncing with the pod" func="controller.(*InstanceManagerController).syncStatusWithPod.func1" file="instance_manager_controller.go:422" controller=longhorn-instance-manager instanceManager=instance-manager-91996e0b81585b78a282e88f1bf0c8f3 node=worker7 nodeID=worker7
time="2024-12-10T04:36:41Z" level=warning msg="Deleting instance manager pod instance-manager-91996e0b81585b78a282e88f1bf0c8f3 since one of the following conditions is met: setting is not synced (true) or data engine CPU mask is not applied (false), instances are running in the pod (false), or the pod is deleted or not running (true)" func="controller.(*InstanceManagerController).handlePod" file="instance_manager_controller.go:606" controller=longhorn-instance-manager instanceManager=instance-manager-91996e0b81585b78a282e88f1bf0c8f3 node=worker7 nodeID=worker7
```

Could you please provide additional guidance or steps to resolve this issue? I will proceed accordingly and share further results.

**Comment by derekbit** [comment] 2024-12-10 05:13
@jangseon-ryu Have you upgraded the longhorn-manager to master-head as well?

**Comment by jangseon-ryu** [comment] 2024-12-10 05:25
@derekbit 
Yes, I have upgraded the longhorn-manager to the master-head version as well.
```
[worker7 longhorn]# k describe po longhorn-manager-44l7b | grep master-head
    Image:         longhornio/longhorn-manager:master-head
      longhornio/longhorn-engine:master-head
      longhornio/longhorn-instance-manager:master-head
      longhornio/longhorn-share-manager:master-head
      longhornio/backing-image-manager:master-head
      longhornio/longhorn-manager:master-head
    Image:         longhornio/longhorn-share-manager:master-head
```

**Comment by derekbit** [comment] 2024-12-10 05:36
@jangseon-ryu Can you provide a support bundle?

**Comment by jangseon-ryu** [comment] 2024-12-10 06:21
@derekbit 
I have attached the requested support bundle. Please review it and let me know if further information is needed.
[supportbundle_6abd47b9-0de7-445e-bce5-a971eb1d4089_2024-12-10T06-14-02Z.zip](https://github.com/user-attachments/files/18072960/supportbundle_6abd47b9-0de7-445e-bce5-a971eb1d4089_2024-12-10T06-14-02Z.zip)

**Comment by c3y1huang** [comment] 2024-12-10 06:39
@jangseon-ryu Could you try with the following command:
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/refs/heads/master/deploy/longhorn.yaml
```

**Comment by jangseon-ryu** [comment] 2024-12-10 06:51
@c3y1huang 
The longhorn-instance-manager v2 is now running normally after executing the provided command. 
I will proceed with the memory leak reproduction test and share the results once completed.
Thank you for your guidance. :D

**Comment by jangseon-ryu** [comment] 2024-12-11 05:36
@c3y1huang 
I conducted tests to verify whether the memory leak issue is reproducible on the master-head version. Below are the test details and observations:

#### Test Environment
- Pods: 2
- PVCs: 2 (each with 3 replicas)
- Nodes : 6

#### Observations
- ``No Significant Memory Leak``
  - The severe memory leak (over 100MB per day) caused by NSFileLock usage was not observed.
- ``Minor Memory Increase``
  - Over approximately 20 hours, a memory increase of around 20MB was detected.
- Scope of Issue
  - The memory increase occurred only on the Longhorn Instance Manager (LHIM) running the engine.
  - LHIM instances running only the replicas did not show any memory increase
<img width="682" alt="image" src="https://github.com/user-attachments/assets/37a4a3f0-1a2c-4ab0-9cda-12bab11b145f">

#### Conclusion
- A consistent increase of approximately 1MB per hour could lead to a 720MB increase per month.
- The memory leak issue has been greatly mitigated, but the observed gradual increase in memory usage could still be problematic for long-term operation.

Please let me know if additional tests or data are required

( cc @derekbit )

**Comment by c3y1huang** [comment] 2024-12-16 01:16
> @c3y1huang I conducted tests to verify whether the memory leak issue is reproducible on the master-head version. Below are the test details and observations:
> 
> #### Test Environment
> * Pods: 2
> * PVCs: 2 (each with 3 replicas)
> * Nodes : 6
> 
> #### Observations
> * `No Significant Memory Leak`
>   
>   * The severe memory leak (over 100MB per day) caused by NSFileLock usage was not observed.
> * `Minor Memory Increase`
>   
>   * Over approximately 20 hours, a memory increase of around 20MB was detected.
> * Scope of Issue
>   
>   * The memory increase occurred only on the Longhorn Instance Manager (LHIM) running the engine.
>   * LHIM instances running only the replicas did not show any memory increase
> 
> <img alt="image" width="682" src="https://private-user-images.githubusercontent.com/22007096/394590136-37a4a3f0-1a2c-4ab0-9cda-12bab11b145f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQzMTA0MDUsIm5iZiI6MTczNDMxMDEwNSwicGF0aCI6Ii8yMjAwNzA5Ni8zOTQ1OTAxMzYtMzdhNGEzZjAtMWEyYy00YWIwLTljZGEtMTJiYWIxMWIxNDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMTYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjE2VDAwNDgyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThkZTAzYzg1MjFkZGI4NmI4ZWFjNDczYjExMjVhNGQ5MzZkNGU1MDg5MDYyYWQ0ZDg3Nzc5NWEwNjUzYzliNTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Ab26MMRrpxKIvu7RvwWC0bBvP3zpj7mWBe2e01haWHA">
> #### Conclusion
> * A consistent increase of approximately 1MB per hour could lead to a 720MB increase per month.
> * The memory leak issue has been greatly mitigated, but the observed gradual increase in memory usage could still be problematic for long-term operation.
> 
> Please let me know if additional tests or data are required
> 
> ( cc @derekbit )

Thank you for sharing the results. Based on your findings, we can conclude that the memory leak caused by `NSFileLock` has been resolved in v1.8.0. We could also consider backporting the fix to 1.7.x to address this issue in the earlier version, even though it was originally introduced as part of a new feature.

Regarding the minor memory leak, have you identified its root cause? Since the codebase for v1.8.0 is still under active development, I recommend conducting another round of testing closer to the release date, particularly after the RCs are available, when the code is more stable. If the issue persists, please create a separate issue to track it.

cc @derekbit @innobead

**Comment by c3y1huang** [comment] 2024-12-16 02:19
After discussing with @derekbit , we won't backport v2 bugs since this feature is still considered experimental.

**Closed** 2024-12-16 02:19 UTC
Labels: kind/bug, wontfix, priority/0, area/performance, area/v2-data-engine, require/qa-review-coverage, require/backport

**Comment by c3y1huang** [comment] 2024-12-16 02:23
This is automatically closed by the bot. 

@jangseon-ryu , feel free to reopen it or leave any comments for additional thoughts or findings.

**Comment by jangseon-ryu** [comment] 2024-12-16 02:24
@c3y1huang 
I agree with your feedback. Since the reported issue regarding the memory leak caused by NSFileLock has been resolved, I believe ``this issue can now be closed.``
Currently, I am conducting memory profiling on master-head. Although the memory increase is minor, it seems a longer observation and analysis period is required. I will ``create a separate issue to track the findings.``

In my personal cluster environment, I have confirmed that the issue has been improved after modifying NSFileLock. ``If NSFileLock is still being used by other modules, please review whether a PR for the improved version is necessary.``
