### ISSUE TITLE
[FEATURE] Make RWX timeo value user configurable

### ISSUE THREAD

**Issue by bentastic27** [longhorn/longhorn#2630] opened 2021-05-27 14:23 UTC
There are very specific workloads that need the higher timeo value (300) back. It's speculated that `kubectl cp` performs better when copying to volumes with it for example. Aside from that just creating this for tracking purposes per this comment:

https://github.com/longhorn/longhorn/issues/2528#issuecomment-825182392

**Comment by jenting** [comment] 2021-06-15 03:56
cc @joshimoo could you please look at this one? We missed this issue before.

**Comment by joshimoo** [comment] 2021-06-16 09:26
@bentastic27 Thanks for writing this up. Currently the performance issue is not caused by the timeo value. In https://github.com/longhorn/longhorn-manager/pull/883 we changed the timeo value to 3s
After each timeout the timeout will be linearly increased (3s, 6s, 9s)
This means that an IO operation has a maximum runtime of 18s before failure.

The performance degradation can be observed as part of low block size writes. For #2293 we can consider which parameters we want to make user configurable, since we might rely on some specific expectations.

Currently exposing this would not make a difference.

**Comment by joshimoo** [comment] 2021-09-23 18:01
In https://github.com/longhorn/longhorn-manager/pull/992 I added a hidden undocumented field to specify a set of `nfsOptions` as part of a storage class. The set is a csv string. This shouldn't really be required anymore since we also fixed the performance regression by no longer enforcing sync mode on the nfs client mount.

**Comment by joshimoo** [comment] 2021-09-23 18:07
If you specify nfsOptions make sure to include the options that we require.
`vers=4.1,noresvport,soft,intr,timeo=XXX,retrans=YYY`

"timeo=30",  // This is tenths of a second, so a 3 second timeout, each retrans the timeout will be linearly increased, 3s, 6s, 9s
"retrans=3", // We try the io operation for a total of 3 times, before failing, max runtime of 18s

**Comment by innobead** [comment] 2021-09-24 09:45
As per @joshimoo , I think the performance issue has already been resolved by changing sync mode to async mode already, so users should avoid doing some customized settings to leave Longhorn have optimized settings first or even relaying on the default mount options of host OS. 

Closing, but feel free to reopen you have better reasons for it officially. Thanks.

**Closed by innobead** 2021-09-24 09:45 UTC
Labels: kind/enhancement, area/rwx
