### ISSUE TITLE
[DOC] Improve the documentation about troubleshooting and worse/best practice of operations

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#3164] opened 2021-10-18 16:43 UTC
Need to improve the documentation for the below areas including troubleshooting, worse/best practice of operations, etc.

- [ ] We need to discourage users from modifying the Longhorn objects (e.g. volume, replica, etc) directly (unless call out explicitly), at least before v1.3. Those are mostly considered as internal states of Longhorn and modifying them might cause Longhorn to malfunction.
- [ ] Also, we should call out that downgrade is not supported.
- [ ] Users need to understand the architecture of the Longhorn system and the Longhorn engine first. This is the bar that cannot be bypassed. For this part, we can post the latest Longhorn demo as well as the slide on the website.
- [ ] Besides, we can write some common issues analysis based on the knowledge we shared. The volume attachment & detachment issue is already there but I don’t think it’s detailed enough.
- [ ] And we need to emphasize that editing Longhorn objects or deleting Longhorn components is a dangerous operation.

cc @shuo-wu

**Comment by innobead** [comment] 2021-10-21 02:31
Hey team! Please [add your planning poker estimate](https://app.zenhub.com/workspaces/Longhorn-Main-Board-59d8105b2fbdf4155c4589ef/issues/longhorn/longhorn/3164?planning-poker) with ZenHub @jenting @PhanLe1010 @shuo-wu @joshimoo

**Comment by shuo-wu** [comment] 2022-02-15 09:07
I just wrote a simple debugging guide for a community user. Hope it works:
https://rancher-users.slack.com/archives/CC2UQM49Y/p1644915734107909?thread_ts=1644585341.803259&cid=CC2UQM49Y

**Comment by innobead** [comment] 2023-08-09 03:33
Duplicate of https://github.com/longhorn/longhorn/issues/5008.

**Closed by innobead** 2023-08-09 03:33 UTC
Labels: kind/doc, priority/0, area/troubleshoot
