### ISSUE TITLE
longhorn-driver-deployer - Error deploying driver: persistentvolumeclaims \"opt\" not found"

### ISSUE THREAD

**Issue by mzac** [longhorn/longhorn#965] opened 2019-12-16 16:35 UTC
I'm trying to deploy longhorn on a 3 node rancher cluster.  My servers are running Ubuntu 18.04 and docker and rancher is running on top of docker.

Every time I try and deploy longhorn, the longhorn-driver-deployer container fails and I cannot assign any PVs to containers.  The deployer gives me this error:

```
time="2019-12-16T16:32:19Z" level=debug msg="Deploying CSI driver"
time="2019-12-16T16:32:19Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-12-16T16:32:20Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-12-16T16:32:21Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2019-12-16T16:32:22Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2019-12-16T16:32:23Z" level=debug msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2019-12-16T16:32:24Z" level=info msg="Proc found: kubelet"
time="2019-12-16T16:32:24Z" level=info msg="Try to find arg [--root-dir] in cmdline: [kubelet --cni-bin-dir=/opt/cni/bin --tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305 --client-ca-file=/etc/kubernetes/ssl/kube-ca.pem --cloud-provider= --cluster-dns=10.43.0.10 --fail-swap-on=false --anonymous-auth=false --make-iptables-util-chains=true --event-qps=0 --authentication-token-webhook=true --cluster-domain=cluster.local --kubeconfig=/etc/kubernetes/ssl/kubecfg-kube-node.yaml --pod-infra-container-image=rancher/pause:3.1 --root-dir=/var/lib/kubelet --cni-conf-dir=/etc/cni/net.d --streaming-connection-idle-timeout=30m --authorization-mode=Webhook --hostname-override=rnode3 --volume-plugin-dir=/var/lib/kubelet/volumeplugins --v=2 --network-plugin=cni --resolv-conf=/etc/resolv.conf --cgroups-per-qos=True --read-only-port=0 --address=0.0.0.0 --cgroup-driver=cgroupfs ]"
time="2019-12-16T16:32:24Z" level=info msg="Detected root dir path: /var/lib/kubelet"
time="2019-12-16T16:32:24Z" level=info msg="Upgrading Longhorn related components for CSI v1.1.0"
time="2019-12-16T16:32:24Z" level=fatal msg="Error deploying driver: persistentvolumeclaims \"opt\" not found"
```

**Comment by shuo-wu** [comment] 2019-12-16 18:46
This issue is the same as #957

**Comment by yasker** [comment] 2019-12-16 20:00
Duplicate of #957

**Closed by yasker** 2019-12-16 20:00 UTC
