### ISSUE TITLE
[BUG] Deploying Longhorn through Flux2 wont apply defaultSettings

### ISSUE THREAD

**Issue by Eagleman7** [longhorn/longhorn#2562] opened 2021-05-04 07:49 UTC
**Describe the bug**
Deploying Longhorn through Flux2 wont apply defaultSettings:

**To Reproduce**

I use the following flux2 config to deploy Longhorn on my cluster:
```
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: longhorn-charts
  namespace: flux-system
spec:
  interval: 1m
  url: https://charts.longhorn.io
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  releaseName: longhorn
  interval: 5m
  chart:
    spec:
      # renovate: registryUrl=https://charts.longhorn.io
      chart: longhorn
      version: 1.1.1
      sourceRef:
        kind: HelmRepository
        name: longhorn-charts
        namespace: flux-system
      interval: 5m
  values:
    persistence:
      defaultClass: true
      reclaimPolicy: Delete
      defaultClassReplicaCount: 3
    defaultSettings:
      backupTarget: s3://longhorn@minio/
      backupTargetCredentialSecret: longhorn-backup-secret
      allowRecurringJobWhileVolumeDetached: false
      createDefaultDiskLabeledNodes: false
      defaultDataPath: /var/lib/longhorn/
      defaultDataLocality: disabled
      replicaSoftAntiAffinity: false
      storageOverProvisioningPercentage: 200
      storageMinimalAvailablePercentage: 10
      upgradeChecker: true
      defaultReplicaCount: 3
      guaranteedEngineCPU: 0.25
      defaultLonghornStaticStorageClass: longhorn-static
      backupstorePollInterval: 300
      autoSalvage: true
      autoDeletePodWhenVolumeDetachedUnexpectedly: true
      disableSchedulingOnCordonedNode: true
      replicaZoneSoftAntiAffinity: true
      volumeAttachmentRecoveryPolicy: wait
      nodeDownPodDeletionPolicy: do-nothing
      allowNodeDrainWithLastHealthyReplica: false
      disableReplicaRebuild: false
      replicaReplenishmentWaitInterval: 600
      disableRevisionCounter: false
      systemManagedPodsImagePullPolicy: if-not-present
      allowVolumeCreationWithDegradedAvailability: true
      autoCleanupSystemGeneratedSnapshot: true
```
However after the deployment on a fresh cluster the defaultSettings cannot be seen in the Longhorn webinterface. I was missing theese settings for example:
```
backupTarget: s3://longhorn@minio/
backupTargetCredentialSecret: longhorn-backup-secret
```

![image](https://user-images.githubusercontent.com/4787591/116974659-bd9ed980-acbe-11eb-8ce3-23396f5a0f54.png)

**Expected behavior**
I would have expected these settings to have been applied:
```
backupTarget: s3://longhorn@minio/
backupTargetCredentialSecret: longhorn-backup-secret
```

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Flux2 (Helm)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: RHEL 8.3
   - CPU per node: 3
   - Memory per node: 14
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: 10Gbe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 25~

**Additional context**

**Comment by jenting** [comment] 2021-05-05 05:06
The _defaultSettings_ would apply to `longhorn-default-setting` ConfigMap, then longhorn-manager sync it to the settings CR if the `settings` CR does not exist. The GUI displays the setting from `settings` CR.

The problem comes that you update the _backupTarget_ and _backupTargetCredentialSecret_ after `settings` CR already exists, it means not it's not a fresh install.

I believe the `helm upgrade --set defaultSettings.backupTarget=<new-s3-url> --set backupTargetCredentialSecret=<new-backup-target-credential-secret>` would have the same problem.

The idea on how to fix it is we drop the `longhorn-default-setting` ConfigMap, and updates the configuration directly to the `settings` CR.

**Comment by innobead** [comment] 2021-05-05 05:17
cc @shuo-wu

**Comment by shuo-wu** [comment] 2021-05-05 06:42
Do you mean the default settings for a fresh Longhorn deployment rather than upgrade don't work? If that's the case, there may be something wrong (e.g., invalid format) in your default settings. And you can check if there are any related error logs in longhorn manager pods.

**Comment by Eagleman7** [comment] 2021-05-05 07:53
@shuo-wu I experienced this issue 3 times on a fresh cluster install. Longhorn did not exist on that cluster before deploying Longhorn with Flux2. @jenting confirmed he was able to reproduce this issue.

**Comment by jenting** [comment] 2021-05-05 10:55
I could only reproduce it on the upgrade case. On a fresh install, I can't reproduce it.
Could you please check the longhorn CRDs do not exist before deploying longhorn by flux v2?

You could remove the CRDs first
```shell
kubectl get crds -n longhorn-system | grep longhorn.io | awk -d'' '{print $1}' | xargs kubectl delete crds
```

**Comment by Eagleman7** [comment] 2021-05-09 00:50
> efault settings. And you can check if there are any related error logs in longhorn manager pods.

No errors:
```
2021/05/09 00:46:19 proto: duplicate proto type registered: VersionResponse
time="2021-05-09T00:46:19Z" level=info msg="Start overwriting built-in settings with customized values"
time="2021-05-09T00:46:19Z" level=error msg="Customized settings are invalid, will give up using them: the value of customized setting guaranteed-engine-cpu is invalid: value 0.25 of settings guaranteed-engine-cpu is invalid: cannot set a value 0.25 for the deprecated setting guaranteed-engine-cpu"
W0509 00:46:19.614319       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-05-09T00:46:19Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/15649/ns/mnt --net=/host/proc/15649/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0509 00:46:19.638957       1 leaderelection.go:241] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I0509 00:46:19.661169       1 leaderelection.go:251] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2021-05-09T00:46:19Z" level=info msg="Start upgrading"
time="2021-05-09T00:46:19Z" level=warning msg="Cannot verify current CRD version, assume it's not v1alpha1: unable to verify if version matches v1alpha1: settings.longhorn.rancher.io \"default-engine-image\" is forbidden: User \"system:serviceaccount:longhorn-system:longhorn-service-account\" cannot get resource \"settings\" in API group \"longhorn.rancher.io\" in the namespace \"longhorn-system\""
time="2021-05-09T00:46:19Z" level=info msg="Initialized CRD API Version to longhorn.io/v1beta1"
time="2021-05-09T00:46:20Z" level=info msg="Finish upgrading"
time="2021-05-09T00:46:20Z" level=info msg="Upgrade leader lost: k8s-staging-refined-1"
W0509 00:46:20.366819       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0509 00:46:20.371409       1 shared_informer.go:197] Waiting for caches to sync for longhorn datastore
I0509 00:46:20.580871       1 shared_informer.go:204] Caches are synced for longhorn datastore
W0509 00:46:20.581051       1 client_config.go:541] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn replica controller" controller=longhorn-replica node=k8s-staging-refined-1
I0509 00:46:20.584123       1 shared_informer.go:197] Waiting for caches to sync for longhorn replicas
I0509 00:46:20.584135       1 shared_informer.go:204] Caches are synced for longhorn replicas
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn engine controller" controller=longhorn-engine node=k8s-staging-refined-1
I0509 00:46:20.584194       1 shared_informer.go:197] Waiting for caches to sync for longhorn engines
I0509 00:46:20.584201       1 shared_informer.go:204] Caches are synced for longhorn engines
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn volume controller" controller=longhorn-volume node=k8s-staging-refined-1
I0509 00:46:20.584308       1 shared_informer.go:197] Waiting for caches to sync for longhorn engines
I0509 00:46:20.584316       1 shared_informer.go:204] Caches are synced for longhorn engines
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn Engine Image controller"
I0509 00:46:20.584382       1 shared_informer.go:197] Waiting for caches to sync for longhorn engine images
I0509 00:46:20.584389       1 shared_informer.go:204] Caches are synced for longhorn engine images
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn node controller"
I0509 00:46:20.584451       1 shared_informer.go:197] Waiting for caches to sync for longhorn node
I0509 00:46:20.584459       1 shared_informer.go:204] Caches are synced for longhorn node
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn websocket controller" controller=longhorn-websocket node=k8s-staging-refined-1
I0509 00:46:20.584543       1 shared_informer.go:197] Waiting for caches to sync for longhorn websocket
I0509 00:46:20.584551       1 shared_informer.go:204] Caches are synced for longhorn websocket
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn Setting controller" controller=longhorn-setting node=k8s-staging-refined-1
I0509 00:46:20.584603       1 shared_informer.go:197] Waiting for caches to sync for longhorn settings
I0509 00:46:20.584611       1 shared_informer.go:204] Caches are synced for longhorn settings
time="2021-05-09T00:46:20Z" level=info msg="Starting Longhorn instance manager controller"
I0509 00:46:20.588285       1 shared_informer.go:197] Waiting for caches to sync for longhorn instance manager
I0509 00:46:20.588297       1 shared_informer.go:204] Caches are synced for longhorn instance manager
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn share manager controller" controller=longhorn-share-manager node=k8s-staging-refined-1
I0509 00:46:20.588374       1 shared_informer.go:197] Waiting for caches to sync for longhorn-share-manager-controller
I0509 00:46:20.588382       1 shared_informer.go:204] Caches are synced for longhorn-share-manager-controller
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn Backing Image controller"
I0509 00:46:20.588475       1 shared_informer.go:197] Waiting for caches to sync for longhorn backing images
I0509 00:46:20.588483       1 shared_informer.go:204] Caches are synced for longhorn backing images
time="2021-05-09T00:46:20Z" level=info msg="Starting Longhorn backing image manager controller"
I0509 00:46:20.588577       1 shared_informer.go:197] Waiting for caches to sync for longhorn backing image manager
I0509 00:46:20.588661       1 shared_informer.go:204] Caches are synced for longhorn backing image manager
time="2021-05-09T00:46:20Z" level=info msg="Start kubernetes controller"
I0509 00:46:20.588784       1 shared_informer.go:197] Waiting for caches to sync for kubernetes
I0509 00:46:20.588793       1 shared_informer.go:204] Caches are synced for kubernetes
time="2021-05-09T00:46:20Z" level=info msg="Start Longhorn Kubernetes node controller"
I0509 00:46:20.588931       1 shared_informer.go:197] Waiting for caches to sync for longhorn kubernetes node
I0509 00:46:20.588937       1 shared_informer.go:204] Caches are synced for longhorn kubernetes node
time="2021-05-09T00:46:20Z" level=info msg="Start longhorn-kubernetes-pod-controller"
I0509 00:46:20.589017       1 shared_informer.go:197] Waiting for caches to sync for longhorn-kubernetes-pod-controller
I0509 00:46:20.589023       1 shared_informer.go:204] Caches are synced for longhorn-kubernetes-pod-controller
time="2021-05-09T00:46:20Z" level=info msg=Start controller=longhorn-kubernetes-configmap-controller node=k8s-staging-refined-1
I0509 00:46:20.589111       1 shared_informer.go:197] Waiting for caches to sync for longhorn-kubernetes-configmap-controller
I0509 00:46:20.589117       1 shared_informer.go:204] Caches are synced for longhorn-kubernetes-configmap-controller
time="2021-05-09T00:46:20Z" level=info msg=Start controller=longhorn-kubernetes-secret-controller node=k8s-staging-refined-1
I0509 00:46:20.595176       1 shared_informer.go:197] Waiting for caches to sync for longhorn-kubernetes-secret-controller
time="2021-05-09T00:46:20Z" level=info msg="Updated the default Longhorn StorageClass: &StorageClass{ObjectMeta:{longhorn   /apis/storage.k8s.io/v1/storageclasses/longhorn 3c122807-453a-4389-96ac-3724a9be426b 3157 0 2021-05-09 00:46:20 +0000 UTC <nil> <nil> map[] map[longhorn.io/last-applied-configmap:kind: StorageClass\napiVersion: storage.k8s.io/v1\nmetadata:\n  name: longhorn\n  annotations:\n    storageclass.kubernetes.io/is-default-class: \"true\"\nprovisioner: driver.longhorn.io\nallowVolumeExpansion: true\nreclaimPolicy: \"Delete\"\nvolumeBindingMode: Immediate\nparameters:\n  numberOfReplicas: \"3\"\n  staleReplicaTimeout: \"30\"\n  fromBackup: \"\"\n  baseImage: \"\"\n storageclass.kubernetes.io/is-default-class:true] [] []  [{longhorn-manager Update storage.k8s.io/v1 2021-05-09 00:46:20 +0000 UTC FieldsV1 FieldsV1{Raw:*[123 34 102 58 97 108 108 111 119 86 111 108 117 109 101 69 120 112 97 110 115 105 111 110 34 58 123 125 44 34 102 58 109 101 116 97 100 97 116 97 34 58 123 34 102 58 97 110 110 111 116 97 116 105 111 110 115 34 58 123 34 46 34 58 123 125 44 34 102 58 108 111 110 103 104 111 114 110 46 105 111 47 108 97 115 116 45 97 112 112 108 105 101 100 45 99 111 110 102 105 103 109 97 112 34 58 123 125 44 34 102 58 115 116 111 114 97 103 101 99 108 97 115 115 46 107 117 98 101 114 110 101 116 101 115 46 105 111 47 105 115 45 100 101 102 97 117 108 116 45 99 108 97 115 115 34 58 123 125 125 125 44 34 102 58 112 97 114 97 109 101 116 101 114 115 34 58 123 34 46 34 58 123 125 44 34 102 58 98 97 115 101 73 109 97 103 101 34 58 123 125 44 34 102 58 102 114 111 109 66 97 99 107 117 112 34 58 123 125 44 34 102 58 110 117 109 98 101 114 79 102 82 101 112 108 105 99 97 115 34 58 123 125 44 34 102 58 115 116 97 108 101 82 101 112 108 105 99 97 84 105 109 101 111 117 116 34 58 123 125 125 44 34 102 58 112 114 111 118 105 115 105 111 110 101 114 34 58 123 125 44 34 102 58 114 101 99 108 97 105 109 80 111 108 105 99 121 34 58 123 125 44 34 102 58 118 111 108 117 109 101 66 105 110 1
105 110 103 77 111 100 101 34 58 123 125 125],}}]},Provisioner:driver.longhorn.io,Parameters:map[string]string{baseImage: ,fromBackup: ,numberOfReplicas: 3,staleReplicaTimeout: 30,},ReclaimPolicy:*Delete,MountOptions:[],AllowVolumeExpansion:*true,VolumeBindingMode:*Immediate,AllowedTopologies:[]TopologySelectorTerm{},}" controller=longhorn-kubernetes-configmap-controller node=k8s-staging-refined-1
I0509 00:46:20.695320       1 shared_informer.go:204] Caches are synced for longhorn-kubernetes-secret-controller
time="2021-05-09T00:46:23Z" level=info msg="Latest Longhorn version is v1.1.1" controller=longhorn-setting node=k8s-staging-refined-1
time="2021-05-09T00:46:24Z" level=debug msg="Cannot update latest Longhorn version" controller=longhorn-setting error="settings.longhorn.io \"latest-longhorn-version\" is invalid: metadata.resourceVersion: Invalid value: 0x0: must be specified for an update" node=k8s-staging-refined-1
time="2021-05-09T00:46:29Z" level=debug msg="Updated setting default-engine-image to longhornio/longhorn-engine:v1.1.1"
time="2021-05-09T00:46:29Z" level=debug msg="Updated setting default-instance-manager-image to longhornio/longhorn-instance-manager:v1_20201216"
time="2021-05-09T00:46:29Z" level=debug msg="Updated setting default-share-manager-image to longhornio/longhorn-share-manager:v1_20210416"
time="2021-05-09T00:46:29Z" level=debug msg="Updated setting default-backing-image-manager-image to longhornio/backing-image-manager:v1_20210422"
time="2021-05-09T00:46:30Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s-staging-refined-1\", UID:\"efbae103-31cc-461f-9dce-f2e946cca850\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3260\", FieldPath:\"\"}): type: 'Warning' reason: 'Ready' Node k8s-staging-refined-1 is down: the manager pod longhorn-manager-m7ngs is not running"
time="2021-05-09T00:46:30Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s-staging-refined-1\", UID:\"efbae103-31cc-461f-9dce-f2e946cca850\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3260\", FieldPath:\"\"}): type: 'Normal' reason: 'Schedulable' "
time="2021-05-09T00:46:30Z" level=debug msg="Prepare to create default instance manager instance-manager-e-1dda6ecc, node: k8s-staging-refined-1, default instance manager image: longhornio/longhorn-instance-manager:v1_20201216, type: engine"
time="2021-05-09T00:46:30Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s-staging-refined-1\", UID:\"efbae103-31cc-461f-9dce-f2e946cca850\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3260\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Disk default-disk-80100000000(/var/lib/longhorn/) on node k8s-staging-refined-1 is ready"
time="2021-05-09T00:46:30Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s-staging-refined-1\", UID:\"efbae103-31cc-461f-9dce-f2e946cca850\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3260\", FieldPath:\"\"}): type: 'Normal' reason: 'Schedulable' Disk default-disk-80100000000(/var/lib/longhorn/) on node k8s-staging-refined-1 is schedulable"
time="2021-05-09T00:46:30Z" level=debug msg="Instance Manager Controller k8s-staging-refined-1 picked up instance-manager-e-1dda6ecc" controller=longhorn-instance-manager instanceManager=instance-manager-e-1dda6ecc node=k8s-staging-refined-1 nodeID=k8s-staging-refined-1
time="2021-05-09T00:46:30Z" level=info msg="Created instance manager pod instance-manager-e-1dda6ecc for instance manager instance-manager-e-1dda6ecc"
time="2021-05-09T00:46:30Z" level=debug msg="Prepare to create default instance manager instance-manager-r-83ef13a7, node: k8s-staging-refined-1, default instance manager image: longhornio/longhorn-instance-manager:v1_20201216, type: replica"
time="2021-05-09T00:46:30Z" level=debug msg="Created engine image ei-611d1496 (longhornio/longhorn-engine:v1.1.1)"
time="2021-05-09T00:46:30Z" level=info msg="Listening on 10.233.114.9:9500"
time="2021-05-09T00:46:30Z" level=debug msg="Engine Image Controller k8s-staging-refined-1 picked up ei-611d1496 (longhornio/longhorn-engine:v1.1.1)" controller=longhorn-engine-image engineImage=ei-611d1496 node=k8s-staging-refined-1
time="2021-05-09T00:46:31Z" level=info msg="Created daemon set engine-image-ei-611d1496 for engine image ei-611d1496 (longhornio/longhorn-engine:v1.1.1)" controller=longhorn-engine-image engineImage=ei-611d1496 node=k8s-staging-refined-1
time="2021-05-09T00:46:31Z" level=debug msg="Instance Manager Controller k8s-staging-refined-1 picked up instance-manager-r-83ef13a7" controller=longhorn-instance-manager instanceManager=instance-manager-r-83ef13a7 node=k8s-staging-refined-1 nodeID=k8s-staging-refined-1
time="2021-05-09T00:46:31Z" level=info msg="Created instance manager pod instance-manager-r-83ef13a7 for instance manager instance-manager-r-83ef13a7"
time="2021-05-09T00:46:36Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"k8s-staging-refined-1\", UID:\"efbae103-31cc-461f-9dce-f2e946cca850\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3394\", FieldPath:\"\"}): type: 'Normal' reason: 'Ready' Node k8s-staging-refined-1 is ready"
10.233.114.11 - - [09/May/2021:00:46:37 +0000] "GET /v1 HTTP/1.1" 200 3457 "" "curl/7.58.0"
10.233.114.11 - - [09/May/2021:00:46:38 +0000] "GET /v1 HTTP/1.1" 200 3457 "" "Go-http-client/1.1"
time="2021-05-09T00:47:17Z" level=debug msg="Start monitoring instance manager instance-manager-e-1dda6ecc" controller=longhorn-instance-manager instance manager=instance-manager-e-1dda6ecc node=k8s-staging-refined-1
time="2021-05-09T00:47:29Z" level=debug msg="Start monitoring instance manager instance-manager-r-83ef13a7" controller=longhorn-instance-manager instance manager=instance-manager-r-83ef13a7 node=k8s-staging-refined-1
time="2021-05-09T00:47:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"EngineImage\", Namespace:\"longhorn-system\", Name:\"ei-611d1496\", UID:\"0c0d93d8-cf99-4ec4-a987-c7aa836891c1\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3310\", FieldPath:\"\"}): type: 'Normal' reason: 'ready' Engine image ei-611d1496 (longhornio/longhorn-engine:v1.1.1) is fully deployed on all ready nodes"
```

**Comment by Eagleman7** [comment] 2021-05-09 00:53
> I could only reproduce it on the upgrade case. On a fresh install, I can't reproduce it.
> Could you please check the longhorn CRDs do not exist before deploying longhorn by flux v2?
> 
> You could remove the CRDs first
> 
> ```shell
> kubectl get crds -n longhorn-system | grep longhorn.io | awk -d'' '{print $1}' | xargs kubectl delete crds
> ```

It is impossible for the Longhorn CRDS to exist before deploying the flux2 HelmRelease. This is how it gets installed:
```
---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base/longhorn-system
  - ../../base/longhorn-system/longhorn
  - ../../base/longhorn-system/longhorn/secrets
```
`- ../../base/longhorn-system/longhorn` contains the Helmchart, `- ../../base/longhorn-system` contains just the namespace for Longhorn.

**Comment by difrost** [comment] 2021-05-14 12:07
I've got exactly same issue while deploying via helm and passing values from file. Default settings are completely ignored (settings in UI) tho the CM shows correct yaml. Deploying 1.1.0 works. Upgrading from 1.1.0 to 1.1.1 retains settings. Clean deployment of 1.1.0 not - I can reproduce it.

**Comment by innobead** [comment] 2021-05-17 10:28
> I've got exactly same issue while deploying via helm and passing values from file. Default settings are completely ignored (settings in UI) tho the CM shows correct yaml. Deploying 1.1.0 works. Upgrading from 1.1.0 to 1.1.1 retains settings. Clean deployment of 1.1.1 not - I can reproduce it.

For the upgrade case, this is an existing issue. We will tackle it in https://github.com/longhorn/longhorn/issues/2562

**Comment by innobead** [comment] 2021-05-17 10:52
> No errors:
> 
> ```
> 2021/05/09 00:46:19 proto: duplicate proto type registered: VersionResponse
> time="2021-05-09T00:46:19Z" level=info msg="Start overwriting built-in settings with customized values"
> time="2021-05-09T00:46:19Z" level=error msg="Customized settings are invalid, will give up using them: the value of customized setting guaranteed-engine-cpu is invalid: value 0.25 of settings guaranteed-engine-cpu is invalid: cannot set a value 0.25 for the deprecated setting guaranteed-engine-cpu"

@Eagleman7 actually what you encountered is invalid settings like @shuo-wu asked, so the settings were fallback to the default setting.

You can check https://longhorn.io/docs/1.1.1/deploy/upgrade/longhorn-manager/#post-upgrade. `guaranteed-engine-cpu` was deprecated and use `guaranteed-engine-manager-cpu` and `guaranteed-replica-manager-cpu` instead.

**Comment by difrost** [comment] 2021-05-17 11:00
A clean install of 1.1.1 on newly provisioned cluster always fails to accept defaultSettings. Currently in order to set a custom default data path I have to install 1.1.0 (which accepts my settings) and upgrade to 1.1.1 as additional step. This indeed could be a result of guaranteedEngineCPU... I'll check that. Thanks

**Comment by innobead** [comment] 2021-05-17 12:29
Closing as the explanation. Feel free to reopen if the issue still exists.

**Closed** 2021-05-17 12:29 UTC
Labels: area/deployment, kind/bug
