### ISSUE TITLE
[TASK] Handle the CRD validation error

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#3352] opened 2021-12-01 00:01 UTC
## What's the task? Please describe
Hit two CRD validation errors on Kubernetes v1.19.7+k3s1 while upgrading from v1.2.2 to v1beta2 version. The errors are not encountered on Kubernetes v1.21.6+k3s1. 

```
upgradeBackupTargets=failed to update for BackupTarget status default: BackupTarget.longhorn.io \"default\" is invalid: status.lastSyncedAt: Invalid value: \"null\": status.lastSyncedAt in body must be of type string: \"null\""
```

```
failed to update=Node.longhorn.io \“ku50-master\” is invalid: [spec.disks.default-disk-745ff2be8d312b52.tags: Invalid value: \“null\“: spec.disks.default-disk-745ff2be8d312b52.tags in body must be of type array: \“null\“, status.diskStatus: Invalid value: \“null\“: status.diskStatus in body must be of type object: \“null\“]”
```
Need to check which Kubernetes versions have the same issue and make sure `backward compatibility` across K8s versions.

**Comment by derekbit** [comment] 2021-12-01 02:29
Hit two CRD validation errors on Kubernetes v1.19.7+k3s1 while upgrading from v1.2.2 to v1beta2 version.

```
upgradeBackupTargets=failed to update for BackupTarget status default: BackupTarget.longhorn.io \"default\" is invalid: status.lastSyncedAt: Invalid value: \"null\": status.lastSyncedAt in body must be of type string: \"null\""
```

```
failed to update=Node.longhorn.io \“ku50-master\” is invalid: [spec.disks.default-disk-745ff2be8d312b52.tags: Invalid value: \“null\“: spec.disks.default-disk-745ff2be8d312b52.tags in body must be of type array: \“null\“, status.diskStatus: Invalid value: \“null\“: status.diskStatus in body must be of type object: \“null\“]”
```

**Comment by innobead** [comment] 2021-12-01 02:32
Moving to `analysis n design` pipeline

**Comment by derekbit** [comment] 2021-12-01 02:32
metav1.Time seems related to https://github.com/kubernetes/kubernetes/issues/86811 which is fixed in 1.20.

**Comment by derekbit** [comment] 2021-12-02 06:16
|   Kubernetes version       | Upgradable |
|-------------------------|-------------|
|  v1.22.2+k3s1                   |      Y             |
|  v1.21.0+k3s1                   |       Y             |
|  v1.20.0+k3s1                  |       Y              |
| v1.19.16+k3s1                  |       N             |

To upgrade to v1beta2 and pass the CRD validation, the Kubernetes cluster should be at least **v1.20**.

cc @innobead

**Comment by jenting** [comment] 2021-12-02 12:01
> The first error, validation of status.lastSyncedAt(metav1.Time), is related to https://github.com/kubernetes/kubernetes/issues/86811 which is fixed in 1.20.
> 
> 
> 
> PR: https://github.com/kubernetes/kubernetes/pull/95423

Is there any workaround that can do at Longhorn side?

**Comment by derekbit** [comment] 2021-12-02 15:11
> > The first error, validation of status.lastSyncedAt(metav1.Time), is related to [kubernetes/kubernetes#86811](https://github.com/kubernetes/kubernetes/issues/86811) which is fixed in 1.20.
> > PR: [kubernetes/kubernetes#95423](https://github.com/kubernetes/kubernetes/pull/95423)
> 
> Is there any workaround that can do at Longhorn side?

Yes. You can add `// +nullable` which marks this field as allowing the "null" value.
e.g.
```
// BackupTargetStatus defines the observed state of the Longhorn backup target
type BackupTargetStatus struct {
	// The node ID on which the controller is responsible to reconcile this backup target CR.
	// +optional
	OwnerID string `json:"ownerID"`
	// Available indicates if the remote backup target is available or not.
	// +optional
	Available bool `json:"available"`
	// Records the reason on why the backup target is unavailable.
	// +optional
	Conditions []Condition `json:"conditions"`
	// The last time that the controller synced with the remote backup target.
	// +optional
	// +nullable
	LastSyncedAt metav1.Time `json:"lastSyncedAt"`
}
```

and

```
type DiskSpec struct {
	// +optional
	Path string `json:"path"`
	// +optional
	AllowScheduling bool `json:"allowScheduling"`
	// +optional
	EvictionRequested bool `json:"evictionRequested"`
	// +optional
	StorageReserved int64 `json:"storageReserved"`
	// +optional
	// +nullable
	Tags []string `json:"tags"`
}
```

**Comment by derekbit** [comment] 2021-12-02 16:02
> I'd choose the above approach rather than change the min k8s version to 1.20+.
Agree. The `// +nullable` is better for the backward compatibility.
The ensuing question is that should we need `// +nullable` to each `meatav1.Time`, slice, map and so one.

**Comment by jenting** [comment] 2021-12-03 01:49
> > I'd choose the above approach rather than change the min k8s version to 1.20+.
> 
> Agree. The `// +nullable` is better for the backward compatibility. The ensuing question is that should we need to add `// +nullable` to each `meatav1.Time`, `slice`, `map` and so on.

I think pointer type, `meatav1.Time`, `slice` needs to add the `// +nullable`. But for the `map`, should not be necessary.

**Comment by jenting** [comment] 2021-12-03 02:07
We need to consider the nightly E2E test with test different Kubernetes versions as well. (k8s 1.18+)
cc @innobead @longhorn/qa

**Comment by innobead** [comment] 2021-12-06 06:42
> We need to consider the nightly E2E test on different Kubernetes versions as well. (k8s 1.18+) cc @innobead @longhorn/qa

For supported OSs and K8s distro versions, more testing is always welcome but need to consider resources/costs as well. 

Right now, we have OS matrix, so probably we need to have K8s version matrix as well only for supported versions. cc @khushboo-rancher

**Comment by innobead** [comment] 2021-12-06 06:44
> 

The problem right now is only for metav1.Time validation, so why we need to ignore the validation for some data types like slice, map, or ref pointer?

**Comment by kaxing** [comment] 2021-12-17 04:43
A possible related problem while trying to upgrade v1.2.3 to master branch, longhorn-manager will not able to bring up:
```
longhorn-driver-deployer-79f57fd669-2gxp6   0/1     Init:0/1           0          7m25s
longhorn-manager-88cqv                      0/1     CrashLoopBackOff   6          7m25s
longhorn-manager-b5f8t                      0/1     CrashLoopBackOff   6          7m25s
longhorn-manager-r9m2r                      0/1     CrashLoopBackOff   6          7m21s
longhorn-ui-68f4dc986b-gk45s                1/1     Running            0          7m26s
```
And with following identical logs across longhorn-manager identical pods:
```
2021/12/17 04:38:02 proto: duplicate proto type registered: VersionResponse
W1217 04:38:02.507156       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-12-17T04:38:02Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I1217 04:38:02.525466       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I1217 04:38:02.562394       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2021-12-17T04:38:02Z" level=info msg="Start upgrading"
time="2021-12-17T04:38:02Z" level=info msg="Upgrading from longhorn.io/v1beta1 to longhorn.io/v1beta2"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading volumes"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading engineImages"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading backupTargets"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading nodes"
time="2021-12-17T04:38:02Z" level=error msg="Upgrade failed: upgrade API version failed: upgrade from v1beta1 to v1beta2: failed: unable to fix up backingImages: v1beta1.BackingImageList.Items: []v1beta1.BackingImage: v1beta1.BackingImage.Spec: v1beta1.BackingImageSpec.Disks: ReadString: expects \" or n, but found {, error found in #10 byte of ...|a2a42dd\":{}},\"imageU|..., bigger context ...|,\"disks\":{\"6cb312da-bd8e-48f3-8ef0-fb635a2a42dd\":{}},\"imageURL\":\"\",\"sourceParameters\":{},\"sourceType|..."
time="2021-12-17T04:38:02Z" level=info msg="Upgrade leader lost: wk2"
time="2021-12-17T04:38:02Z" level=fatal msg="Error starting manager: upgrade API version failed: upgrade from v1beta1 to v1beta2: failed: unable to fix up backingImages: v1beta1.BackingImageList.Items: []v1beta1.BackingImage: v1beta1.BackingImage.Spec: v1beta1.BackingImageSpec.Disks: ReadString: expects \" or n, but found {, error found in #10 byte of ...|a2a42dd\":{}},\"imageU|..., bigger context ...|,\"disks\":{\"6cb312da-bd8e-48f3-8ef0-fb635a2a42dd\":{}},\"imageURL\":\"\",\"sourceParameters\":{},\"sourceType|..."
```
Steps to reproduce:
1. Install v1.2.3 via kubectl with longhorn.yaml
2. Wait till workload deployed finished and healthy
3. Upgrade to master-head images with kubectl

**Comment by kaxing** [comment] 2021-12-17 05:05
A possible related problem while trying to upgrade v1.2.3 to master branch, longhorn-manager will not able to bring up:
```
longhorn-driver-deployer-79f57fd669-2gxp6   0/1     Init:0/1           0          7m25s
longhorn-manager-88cqv                      0/1     CrashLoopBackOff   6          7m25s
longhorn-manager-b5f8t                      0/1     CrashLoopBackOff   6          7m25s
longhorn-manager-r9m2r                      0/1     CrashLoopBackOff   6          7m21s
longhorn-ui-68f4dc986b-gk45s                1/1     Running            0          7m26s
```
And with following identical logs across longhorn-manager identical pods:
```
2021/12/17 04:38:02 proto: duplicate proto type registered: VersionResponse
W1217 04:38:02.507156       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2021-12-17T04:38:02Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I1217 04:38:02.525466       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I1217 04:38:02.562394       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2021-12-17T04:38:02Z" level=info msg="Start upgrading"
time="2021-12-17T04:38:02Z" level=info msg="Upgrading from longhorn.io/v1beta1 to longhorn.io/v1beta2"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading volumes"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading engineImages"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading backupTargets"
time="2021-12-17T04:38:02Z" level=info msg="Finished upgrading nodes"
time="2021-12-17T04:38:02Z" level=error msg="Upgrade failed: upgrade API version failed: upgrade from v1beta1 to v1beta2: failed: unable to fix up backingImages: v1beta1.BackingImageList.Items: []v1beta1.BackingImage: v1beta1.BackingImage.Spec: v1beta1.BackingImageSpec.Disks: ReadString: expects \" or n, but found {, error found in #10 byte of ...|a2a42dd\":{}},\"imageU|..., bigger context ...|,\"disks\":{\"6cb312da-bd8e-48f3-8ef0-fb635a2a42dd\":{}},\"imageURL\":\"\",\"sourceParameters\":{},\"sourceType|..."
time="2021-12-17T04:38:02Z" level=info msg="Upgrade leader lost: wk2"
time="2021-12-17T04:38:02Z" level=fatal msg="Error starting manager: upgrade API version failed: upgrade from v1beta1 to v1beta2: failed: unable to fix up backingImages: v1beta1.BackingImageList.Items: []v1beta1.BackingImage: v1beta1.BackingImage.Spec: v1beta1.BackingImageSpec.Disks: ReadString: expects \" or n, but found {, error found in #10 byte of ...|a2a42dd\":{}},\"imageU|..., bigger context ...|,\"disks\":{\"6cb312da-bd8e-48f3-8ef0-fb635a2a42dd\":{}},\"imageURL\":\"\",\"sourceParameters\":{},\"sourceType|..."
```
Steps to reproduce:
0. With a fresh rke1 v1.20 cluster(1+3 nodes)
1. Install v1.2.3 via kubectl with longhorn.yaml
2. Wait till workload deployed finished and healthy
3. Upgrade to master-head images with kubectl

**Comment by kaxing** [comment] 2022-01-06 10:28
Validating in progress.

Upgrade failure will show CR upgrade error messages.

following Kubernetes versions verified:
|||
| :- | :- |
| v1.18.20+k3s1 | upgrade CRD failed |
| v1.19.16+k3s1 | upgrade CRD failed |
| v1.20.14+k3s1 | upgrade CRD failed |
| v1.21.8+k3s1 | upgrade CRD failed |

Example of upgrade failure messages:
```
2022/01/06 08:41:12 proto: duplicate proto type registered: VersionResponse
W0106 08:41:12.546822       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-06T08:41:12Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0106 08:41:12.581778       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I0106 08:41:12.765507       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2022-01-06T08:41:12Z" level=info msg="Start upgrading"
time="2022-01-06T08:41:12Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v1.1.0 to v1.1.1: UpgradeCRs failed: upgrade instance manager failed: the server could not find the requested resource (get instancemanagers.longhorn.io)"
time="2022-01-06T08:41:12Z" level=info msg="Upgrade leader lost: c1-worker1"
time="2022-01-06T08:41:12Z" level=fatal msg="Error starting manager: upgrade CRD failed: upgrade from v1.1.0 to v1.1.1: UpgradeCRs failed: upgrade instance manager failed: the server could not find the requested resource (get instancemanagers.longhorn.io)"
\\\
I0106 08:47:32.976450       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2022-01-06T08:47:32Z" level=info msg="Start upgrading"
time="2022-01-06T08:47:33Z" level=error msg="Upgrade failed: upgrade CRD failed: upgrade from v1.1.0 to v1.1.1: UpgradeCRs failed: upgrade instance manager failed: the server could not find the requested resource (get instancemanagers.longhorn.io)"
E0106 08:47:33.031736       1 leaderelection.go:360] Failed to update lock: Put "https://10.43.0.1:443/apis/coordination.k8s.io/v1/namespaces/longhorn-system/leases/longhorn-manager-upgrade-lock": context canceled
I0106 08:47:33.032008       1 leaderelection.go:277] failed to renew lease longhorn-system/longhorn-manager-upgrade-lock: timed out waiting for the condition
time="2022-01-06T08:47:33Z" level=info msg="Upgrade leader lost: c1-control"
time="2022-01-06T08:47:33Z" level=fatal msg="Error starting manager: upgrade CRD failed: upgrade from v1.1.0 to v1.1.1: UpgradeCRs failed: upgrade instance manager failed: the server could not find the requested resource (get instancemanagers.longhorn.io)"
```

Notes on test steps:
1. Launch cluster with specific k3s version
2. Install Longhorn v1.1.3
    - $ helm3 install longhorn longhorn/longhorn -n longhorn-system --create-namespace --version v1.1.3
3. Install and deploy basic workload with pvc
4. Wait all pods become healthy
5. Upgrade/Install to master-head Longhorn
    - Modify image.tags to master-head under values.yaml
    - $ helm3 upgrade longhorn ./longhorn-head-repo/chart -n longhorn-system
6. Check the failure messages

**Comment by derekbit** [comment] 2022-01-06 10:58
Need to use
1. The charts in longhorn/longhorn `v1.3.0` branch
2. Replace `v1.2.3` with `master-head` in charts

**Comment by kaxing** [comment] 2022-01-06 14:01
> Need to upgrade by
> 
> 1. The charts in longhorn/longhorn `v1.3.0` branch
> 2. Replace `v1.2.3` with `master-head` in charts

Thank you Derek, I've retested the v1.1.3 upgrade test with the chart under v1.3.0 branch.
I will update back to the comment with a few more rounds of test.

**Comment by kaxing** [comment] 2022-01-07 08:01
Validation - **FAILED**

Unable to upgrade to v1.3.0-master-head there is volume created from previous versions.

Upgrading with following path via helm3:  v1.1.2 → v1.1.3 → v1.2.3 → master-head

longhorn-manager log:
```yaml
2022/01/07 07:25:36 proto: duplicate proto type registered: VersionResponse
W0107 07:25:36.611108       1 client_config.go:552] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2022-01-07T07:25:36Z" level=info msg="cannot list the content of the src directory /var/lib/rancher/longhorn/engine-binaries for the copy, will do nothing: Failed to execute: nsenter [--mount=/host/proc/1/ns/mnt --net=/host/proc/1/ns/net bash -c ls /var/lib/rancher/longhorn/engine-binaries/*], output , stderr, ls: cannot access '/var/lib/rancher/longhorn/engine-binaries/*': No such file or directory\n, error exit status 2"
I0107 07:25:36.658324       1 leaderelection.go:242] attempting to acquire leader lease  longhorn-system/longhorn-manager-upgrade-lock...
I0107 07:25:36.705577       1 leaderelection.go:252] successfully acquired lease longhorn-system/longhorn-manager-upgrade-lock
time="2022-01-07T07:25:36Z" level=info msg="Start upgrading"
time="2022-01-07T07:25:36Z" level=info msg="Upgrading from longhorn.io/v1beta1 to longhorn.io/v1beta2"
time="2022-01-07T07:25:36Z" level=error msg="Upgrade failed: upgrade API version failed: upgrade from v1beta1 to v1beta2: failed: unable to fix up volumes: Volume.longhorn.io \"bi-test-v113-2\" is invalid: spec.replicaAutoBalance: Unsupported value: \"\": supported values: \"ignored\", \"disabled\", \"least-effort\", \"best-effort\""
time="2022-01-07T07:25:36Z" level=info msg="Upgrade leader lost: c1-worker3"
time="2022-01-07T07:25:36Z" level=fatal msg="Error starting manager: upgrade API version failed: upgrade from v1beta1 to v1beta2: failed: unable to fix up volumes: Volume.longhorn.io \"bi-test-v113-2\" is invalid: spec.replicaAutoBalance: Unsupported value: \"\": supported values: \"ignored\", \"disabled\", \"least-effort\", \"best-effort\""
```

<Details>
<Summary>backing image spec:</Summary>

```yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  creationTimestamp: "2022-01-07T06:32:03Z"
  deletionGracePeriodSeconds: 0
  deletionTimestamp: "2022-01-07T07:29:50Z"
  finalizers:
  - longhorn.io
  generation: 4
  labels:
    longhornvolume: bi-test-v113-2
    recurring-job-group.longhorn.io/default: enabled
  name: bi-test-v113-2
  namespace: longhorn-system
  resourceVersion: "47532"
  selfLink: /apis/longhorn.io/v1beta2/namespaces/longhorn-system/volumes/bi-test-v113-2
  uid: 751cbbcb-2730-49dc-8997-89cd6c35f432
spec:
  Standby: false
  accessMode: rwo
  backingImage: bi2-v113
  baseImage: ""
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: longhornio/longhorn-engine:v1.1.3
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: c1-worker3
  nodeSelector: []
  numberOfReplicas: 3
  replicaAutoBalance: ""
  revisionCounterDisabled: false
  size: "12582912"
  staleReplicaTimeout: 20
status:
  actualSize: 0
  cloneStatus:
    snapshot: ""
    sourceVolume: ""
    state: ""
  conditions: {}
  currentImage: longhornio/longhorn-engine:v1.1.3
  currentNodeID: ""
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: default
    pvName: bi-test-v113-2
    pvStatus: Bound
    pvcName: bi-test-v113-2
    workloadsStatus: null
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: ""
  ownerID: c1-worker3
  pendingNodeID: ""
  remountRequestedAt: ""
  restoreInitiated: false
  restoreRequired: false
  robustness: faulted
  shareEndpoint: ""
  shareState: ""
  state: detached
```
</Details>

Trying to resolve the volume error manually, but unable to make `status.conditions` valid,
```yaml
# volumes.longhorn.io "bi-test-v113" was not valid:
# * spec.replicaAutoBalance: Unsupported value: "": supported values: "ignored", "disabled", "least-effort", "best-effort"
# * status.conditions: Invalid value: "object": status.conditions in body must be of type array: "object"
```

**Comment by derekbit** [comment] 2022-01-07 08:30
Need to add the conversion webhook to resolve the backing image error.

Suggest to validate this ticket after merging the conversion webhook.

**Comment by jenting** [comment] 2022-01-08 10:54
```
# volumes.longhorn.io "bi-test-v113" was not valid:
# * spec.replicaAutoBalance: Unsupported value: "": supported values: "ignored", "disabled", "least-effort", "best-effort"
```

so, you install the v1.1.x/v1.2.x Longhorn and it's the Volume CR `spec.replicaAutoBalance` is an empty string?

**Comment by kaxing** [comment] 2022-01-10 02:15
@jenting the`spec.replicaAutoBalance` is not empty, it is printed as a value without double-quotes.

**Comment by kaxing** [comment] 2022-01-10 03:46
@jenting yes, it is an empty string:
```
spec:
  Standby: false
  accessMode: rwo
  backingImage: ""
  baseImage: ""
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: longhornio/longhorn-engine:v1.1.3
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: ""
  nodeSelector: []
  numberOfReplicas: 3
  replicaAutoBalance: ""
  revisionCounterDisabled: false
  size: "12582912"
  staleReplicaTimeout: 30
```
and deploy with template:
```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: $name
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: $size
```

**Comment by jenting** [comment] 2022-01-10 04:34
I see, then we need to consider assigning it the default value either by upgrade path _or_ by [defaulter webhook](https://book.kubebuilder.io/cronjob-tutorial/webhook-implementation.html).
Need to think further about which one is the proper way for all the Longhorn CR resources.

**Comment by jenting** [comment] 2022-01-10 08:55
Just do a verify, upgrade from v1.1.3 to v1.2.3, the Volume CR `spec.replicaAutoBalance` is an empty string.
So for this case, probably it's better to handle within the upgrade path.

**Comment by c3y1huang** [comment] 2022-01-11 02:28
> Just do a verify, upgrade from v1.1.3 to v1.2.3, the Volume CR `spec.replicaAutoBalance` is an empty string. So for this case, probably it's better to handle it within the upgrade path.
> 
> * https://github.com/longhorn/longhorn-manager/blob/1bdd1c978c0d3630e2a9d383e0f7aa3b3d97f706/csi/util.go#L131-L132
> * https://github.com/longhorn/longhorn-manager/blob/1bdd1c978c0d3630e2a9d383e0f7aa3b3d97f706/types/types.go#L474-L484
> 
> WDYT @c3y1huang?

We could also consider falling back to use `values: "ignored"` when is an empty string.

**Comment by jenting** [comment] 2022-01-11 02:31
> > Just do a verify, upgrade from v1.1.3 to v1.2.3, the Volume CR `spec.replicaAutoBalance` is an empty string. So for this case, probably it's better to handle it within the upgrade path.
> > 
> > * https://github.com/longhorn/longhorn-manager/blob/1bdd1c978c0d3630e2a9d383e0f7aa3b3d97f706/csi/util.go#L131-L132
> > * https://github.com/longhorn/longhorn-manager/blob/1bdd1c978c0d3630e2a9d383e0f7aa3b3d97f706/types/types.go#L474-L484
> > 
> > WDYT @c3y1huang?
> 
> We could also consider falling back to use `values: "disabled"` when is an empty string.

Which one do you prefer/suggest? Support empty string for this field? Or add upgrade logic to convert from an empty string to `"disabled"`? (I think either one should backport to longhorn v1.2.x, right?)

**Comment by c3y1huang** [comment] 2022-01-11 03:02
> Which one do you prefer/suggest? Support empty string for this field? Or add upgrade logic to convert from an empty string to `"disabled"`? (I think either one should backport to longhorn v1.2.x, right?)

Since this is an upgrade case then adding it to the upgrade path should just address the issue. Should be backported to v1.2.x.

**Comment by kaxing** [comment] 2022-02-18 14:35
Validation - **PASSED**

Upgrading from v1.1.3 with 1 volume, 1 backing image in-use:
|||
| :- | :- |
| v1.17.7+k3s1 | `longhorn-admission-webhook E0218 14:32:43.770666       1 reflector.go:178] k8s.io/client-go/informers/factory.go:135: Failed to list *v1.CSIDriver: the server could not find the requested resource` |
| v1.18.20+k3s1 | No upgrade blocker |
| v1.19.16+k3s1 | No upgrade blocker |
| v1.20.14+k3s1 | No upgrade blocker |
| v1.21.8+k3s1 | No upgrade blocker |

As for more complex resource scenario will be covered in release test

**Closed by kaxing** 2022-02-18 14:35 UTC
Labels: area/upgrade, priority/1, kind/task, kind/evaluation, area/api, kind/validation-mutation
