### ISSUE TITLE
[IMPROVEMENT] Avoid misleading log messages in longhorn manager while syncing danger zone settings

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7797] opened 2024-01-28 05:20 UTC
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Longhorn Manager emits the message in a fresh installation when there are attached volumes.

```
E0127 15:17:07.376434       1 setting_controller.go:208] failed to sync setting for longhorn-system/guaranteed-instance-manager-cpu: current state prevents this: failed to apply guaranteed-instance-manager-cpu setting to Longhorn components when there are attached volumes. It will be eventually applied
```

Ideally, it would be better to perform a check for verifying whether the setting has already been successfully applied. If the setting is confirmed to be in place, redundant application attempts can be avoided, and unnecessary log messages should not be emitted.

## Additional context

cc @mantissahz

**Comment by innobead** [comment] 2024-01-28 08:34
What's log type of message?

**Comment by derekbit** [comment] 2024-01-28 09:09
> iled to sync setting for

Error message printed by `utilruntime.HandleError(err)`

**Comment by innobead** [comment] 2024-01-28 11:55
@mantissahz please check this first. Go discuss with @derekbit .

**Comment by innobead** [comment] 2024-01-29 15:07
@derekbit @mantissahz 
is this a general issue for all settings, as they will be reconciled every hour? If yes, I would prefer fixing this after 1.6.0.

When it's close to GA, I suggest fixing critical issues or regression instead. WDYT?

**Comment by derekbit** [comment] 2024-01-29 15:10
> @derekbit @mantissahz is this a general issue for all settings, as they will be reconciled every hour? If yes, I would prefer fixing this after 1.6.0.

Just for danger zone setting.
Fixing after v1.6.0 is fine. I don't think it is a real bug, so I just marked it as an improvement.

**Comment by mantissahz** [comment] 2024-01-29 15:16
>Just for danger zone setting.
Fixing after v1.6.0 is fine. I don't think it is a real bug, so I just marked it as an improvement.

Just for danger zone setting and they will be reconciled every hour.

I agree that it is okay to fix this issue after v1.6.0.

**Comment by innobead** [comment] 2024-01-29 15:18
so for other settings except for danger zone settings, we do check if the setting is identical before applying it?

Let's see how the PR review will be. If it gets longer time, let's do it after 1.6.0.

**Comment by mantissahz** [comment] 2024-01-31 05:30
Move the milestone to v1.7.0

**Comment by mantissahz** [comment] 2024-05-02 08:47
@yangchiu,

Yes, it would be back to the `longhorn-critical` priority-class because the `longhorn-default-setting` ConfigMap https://github.com/longhorn/longhorn/blob/9ef72a18bf39317d94e8636c4fadc12b4edaa433/deploy/longhorn.yaml#L55-L67

**Comment by chriscchien** [comment] 2024-05-30 03:51
Verified **pass** on longhorn master(longhorn-manager `ad7420`) with test [steps](https://github.com/longhorn/longhorn/issues/7797#issuecomment-1914853412)

Did not see logs related to danger zone settings are not changed. And the change of danger zone setting applied correctly.(`guaranteed-instance-manager-cpu`)

**Closed by chriscchien** 2024-05-30 03:51 UTC
Labels: require/doc, require/manual-test-plan, kind/improvement, require/backport, backport/1.6.2
