### ISSUE TITLE
[BUG] UI replica list modal for disk, crash in white page 

### ISSUE THREAD

**Issue by marcomezzaro** [longhorn/longhorn#1084] opened 2020-03-05 09:52 UTC
**Describe the bug**
with a high number of replicas in one disk's volume (failed and healthy replica) and you click the replica number it doesn't show the modal but crash in empty page

**To Reproduce**
1. Go to 'Nodes page'
2. Click on 'number of replica in one disk row'
3. the ui crash in a white page

**Expected behavior**
a Modal shows up with the list of replicas

**Log**
Just downloaded the support bundle
In firefox console log shows: 'TypeError: "t.removeUrl is undefined"'

**Environment:**
 - Longhorn version: 0.8rc2
 - Kubernetes version: 1.15.9
 - Node OS type and version: centos 7.7

**Additional context**

**Comment by yasker** [comment] 2020-03-05 14:35
@marcomezzaro Can you share some screenshots or more message from the developer console? I have a single node running 80+ volumes, but it seems I cannot reproduce this issue.

<img width="795" alt="Screen Shot 2020-03-05 at 6 35 03 AM" src="https://user-images.githubusercontent.com/3344618/75991574-827efb80-5eab-11ea-8216-68ac652d623b.png">

**Comment by marcomezzaro** [comment] 2020-03-05 14:46
Hi, Thanks for the fast reply, I'll send you the support bundle I've downloaded  while experiencing the issue. Tomorrow I'll put some loads on the cluster and try to reproduce the situation.
To add some kind of details my disks were full and two of three nodes were in unschedulable status. In one disk I had 254 replicas. most of them in failed state.
I tried to stress Longhorn cluster because I'm very interested in this storage solution and can't wait to see the first stable release.
Keep up the good work.

**Comment by yasker** [comment] 2020-03-05 14:50
Thanks @marcomezzaro . The only unsettling part in your comment is `most of them in failed state`...

**Comment by marcomezzaro** [comment] 2020-03-06 08:16
I created 100 deployment with the following content:

`---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: longhorn-deployment-pvc__I__
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-slow
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment__I__
  labels:
    app: nginx
spec:
  replicas: __I__
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: volume-test
        image: nginx
        imagePullPolicy: IfNotPresent
        livenessProbe:
          exec:
            command:
              - ls
              - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: volv
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: volv
        persistentVolumeClaim:
          claimName: longhorn-deployment-pvc__I__
`

`for i in {1..100}; do sed s/__I__/$i/g longhorn-static-deployment.yml >> all_static-dep-1-100.yml ; done`

and then kubectl apply -f all_static-dep-1-100.yml

after few minutes I had the following situation.

![longhorn2](https://user-images.githubusercontent.com/51125046/76064937-ea584380-5f8a-11ea-9c06-e932ba5e89a7.png)

and I clicked on all the disk's replica number. 

![longhorn1](https://user-images.githubusercontent.com/51125046/76061361-a3b31b00-5f83-11ea-9f6a-c0786e25eb6d.png)

**Comment by smallteeths** [comment] 2020-03-06 17:32
`wangsiye/longhorn-ui:ad2c4c1` This is the latest UI image. Would you please try this and give a feedback. thanks @marcomezzaro 
1. kubectl edit -n longhorn-system deployment longhorn-ui

![Jietu20200307-013133](https://user-images.githubusercontent.com/27733391/76107341-6bf3b400-6013-11ea-8a86-5c4e9aedd4e8.jpg)

**Comment by yasker** [comment] 2020-03-09 05:40
Hi @marcomezzaro , do you have time to test it? We're trying to get this in the v0.8.0 release.

**Comment by marcomezzaro** [comment] 2020-03-09 07:33
Hi, I'm trying right now. I'll report within an hour

**Comment by marcomezzaro** [comment] 2020-03-09 07:44
the error in console changed. the white page shows up while deployments are creating. 

![longhorn3](https://user-images.githubusercontent.com/51125046/76192230-9dba7580-61e1-11ea-91bc-37a9ff208fb4.png)

**Comment by smallteeths** [comment] 2020-03-09 16:31
Sorry, It’s my mistake. `wangsiye/longhorn-ui:710927e` Would you try this again @marcomezzaro . 
If it still doesn't work, would you give me the backend data so I can mock it.
![Jietu20200310-002938](https://user-images.githubusercontent.com/27733391/76235662-5d510b00-6266-11ea-8639-729674a821c3.jpg)
![Jietu20200310-003016](https://user-images.githubusercontent.com/27733391/76235668-5fb36500-6266-11ea-87c6-f736190c3f55.jpg)

Thank you very much @marcomezzaro

**Comment by marcomezzaro** [comment] 2020-03-09 18:27
Hi everyone, I've tested your second version and the issue seems solved. no more errors in console log and no more white pages. 
All modals are shown correctly and all the volumes are listed.
Thank you for your great work.
Feel free to close this issue.

**Comment by yasker** [comment] 2020-03-09 18:28
@marcomezzaro Thanks, I will merge the PR then close the issue then.

**Comment by yasker** [comment] 2020-03-09 18:30
Fixed by https://github.com/longhorn/longhorn-ui/pull/244

**Closed by yasker** 2020-03-09 18:30 UTC
Labels: area/ui, bug
