### ISSUE TITLE
[BUG] nfs backup broken - NFS server: mkdir - file exists

### ISSUE THREAD

**Issue by xamindar** [longhorn/longhorn#4626] opened 2022-09-27 15:52 UTC
## Describe the bug

An nfs backup location, when configured, will work for a little while (but no more than a day or so), then fail to function.

## To Reproduce

In the longhorn UI:
1. Go to 'setting>general-->Backup Target'
2. set an nfs location (my example: nfs://172.16.8.11:/mnt/user/k8s/longhorn/backup)
3. Click 'save' at the bottom
4. it will work for a while, I was able to backup all my volumes yesterday
5. wait maybe a day, then return to the UI backup tab and I see the following error:
error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.3.0/longhorn [backup ls --volume-only nfs://172.16.8.11:/mnt/user/k8s/longhorn/backup], output Cannot create mount directory /var/lib/longhorn-backupstore-mounts/172_16_8_11/mnt/user/k8s/longhorn/backup for NFS server: mkdir /var/lib/longhorn-backupstore-mounts/172_16_8_11/mnt/user/k8s/longhorn/backup: file exists , stderr, time="2022-09-27T15:13:59Z" level=error msg="Cannot create mount directory /var/lib/longhorn-backupstore-mounts/172_16_8_11/mnt/user/k8s/longhorn/backup for NFS server: mkdir /var/lib/longhorn-backupstore-mounts/172_16_8_11/mnt/user/k8s/longhorn/backup: file exists" , error exit status 1

## Expected behavior

The nfs mount should continue to work, or in the event it went stale (should NOT have in my case as this nfs server is up 24/7) it should remount it.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version: 1.3.0
 - Installation method: helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: ks3 v1.24.3+k3s1 
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Debian GNU/Linux 11 (bullseye)   5.15.61-v8+
   - CPU per node: 4 (raspberry pi4)
   - Memory per node: 2-8g
   - Disk type(e.g. SSD/NVMe): nvme over usb3
   - Network bandwidth between the nodes: 1g
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 11

## Additional context

When it breaks, if I go into the settings and make any change to the nfs mount setting (for example, change the last folder backup, to backup1 and make sure it's created on the server), then save the settings again. The new nfs mount will work for a time before eventually breaking again. I can also go back into settings and change it back to the original "backup" folder and again it will work for a time before breaking again.

Note, this nfs server is up 24/7, it is an unraid server. I am able to mount nfs no problem on any normal machine and it works as long as it's mounted. Longhorn for whatever reason consistently breaks in the manner explained above.

**Comment by c3y1huang** [comment] 2022-10-03 09:01
To reproduce:
1. Deploy [NFS backupstore](https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/deploy/backupstores/nfs-backupstore.yaml).
2. Kill `ganesha.nfsd` in the `longhorn-test-nfs` pod.
3. Wait for `longhorn-test-nfs` pod to recover from crashloop and `ganesha.nfsd` process running.
4. Check the UI.
![Screenshot-2022-10-03-16:26:36](https://user-images.githubusercontent.com/22583541/193533515-3861b22d-8bac-4b35-9924-816de5aaf7bb.png)

The result is reproduced on v1.3.0. Different error shows for the current master branch due to [commit-5f5c952](https://github.com/longhorn/backupstore/commit/5f5c95274f2adcd86f1fce23ee9e469e7c68a40a).
```
error listing backup volume names: failed to execute: /var/lib/longhorn/engine-binaries/c3y1huang-research-1974-lh-ei/longhorn [backup ls --volume-only nfs://longhorn-test-nfs-svc.default:/opt/backupstore], output Cannot create mount directory /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore for NFS server: Failed to execute: mkdir [-m 700 -p /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mkdir: cannot stat '/var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore': Stale file handle , error exit status 1 , stderr, time="2022-10-03T08:15:17Z" level=error msg="Cannot create mount directory /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore for NFS server: Failed to execute: mkdir [-m 700 -p /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore], output mkdir: cannot stat '/var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore': Stale file handle\n, error exit status 1" , error exit status 1
```

**Comment by joshimoo** [comment] 2022-11-09 02:05
When we improve the resilience against nfs server issues, we should consider switching the mount to `soft` mode and ensuring that we handle the potential io errors. This will ensure that no go routines end up getting stuck while working on a dead nfs hard mount. REF: https://github.com/longhorn/longhorn/issues/4772

**Comment by innobead** [comment] 2023-01-16 11:48
cc @longhorn/qa need to create tests for backup target availability and resiliency.

**Comment by derekbit** [comment] 2023-02-17 04:26
The issue is resolved in the implementation of [[FEATURE] CIFS Backup Store Support](https://github.com/longhorn/longhorn/issues/3599). Before Longhorn-manager lists the backups, the corrupted mount point is cleaned up ([codes](https://github.com/longhorn/backupstore/blob/master/nfs/nfs.go#L91)).

Since the default Backupstore Poll Interval is 300 seconds, the listing error caused by the NFS server crash will last for up to 300 seconds. The user can reduce this value to speed up the recovery, but the downside is that the backup target sync frequency will increase.

**Comment by yangchiu** [comment] 2023-04-10 08:05
Verified passed on master-head (longhorn-manager 3f5e636) following [the test steps](https://github.com/longhorn/longhorn/issues/4626#issuecomment-1265141610). 

The error message will disappear and the failed backups will be cleaned up after a while like described in https://github.com/longhorn/longhorn/issues/4626#issuecomment-1434086993.

**Closed by yangchiu** 2023-04-10 08:05 UTC
Labels: kind/bug, reproduce/always, priority/0, area/volume-backup-restore, severity/3, area/stability
