### ISSUE TITLE
[BUG] Cannot add block-type disk to node resource due to timeout error

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#7253] opened 2023-12-04 14:38 UTC
## Describe the bug (🐛 if you encounter this issue)

Cannot add block-type disk to node resource after the update of longhorn-spdk-engine and go-spdk-helper in longhorn-instance-manager.

https://github.com/longhorn/longhorn-instance-manager/commit/5652de640e48b47b73a3250941ba7ef92303b491

```
    test-block-1:
      conditions:
      - lastProbeTime: ""
        lastTransitionTime: "2023-12-04T14:34:03Z"
        message: 'Disk test-block-1(/dev/loop0) on node rancher60-worker2 is not ready:
          failed to get disk config: error: rpc error: code = Internal desc = rpc
          error: code = Internal desc = failed to get AIO bdev with name test-block-1:
          error sending message, id 0, method bdev_get_bdevs, params {test-block-1
          0}: timeout 30s waiting for response during async message send'
        reason: NoDiskInfo
        status: "False"
```

UPDATE: The disk became ready after waiting for 30 seconds. 30-seconds timeout seems not enough.

cc @shuo-wu 

## To Reproduce

1. Create a single node cluster
2. Enable v2-data-engine
3. Add a block-type disk

## Expected behavior

The disk should be added and should not trigger timeout error.
 
## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
 - Impacted Longhorn resources:
   - Volume names:

**Comment by derekbit** [comment] 2023-12-04 15:57
@shuo-wu  Can you help check this issue? Thank you.

**Comment by shuo-wu** [comment] 2023-12-05 02:20
> UPDATE: The disk became ready after waiting for 3 seconds. 30-seconds timeout seems not enough.

Sorry... This should mean the 30-second timeout is enough. Is this a typo?

> [longhorn-instance-manager] time="2023-12-04T14:23:44Z" level=info msg="Debug ===> dispatch msg: &{method:bdev_get_bdevs params:<nil> responseChan:0xc0004c6900}" func="jsonrpc.(*Client).dispatcher" file="client.go:187"
[longhorn-instance-manager] time="2023-12-04T14:23:44Z" level=info msg="Debug ==> id=2361" func="jsonrpc.(*Client).handleSend" file="client.go:152"
[longhorn-instance-manager] time="2023-12-04T14:23:44Z" level=info msg="Debug ==> resp.ID=2361" func="jsonrpc.(*Client).handleRecv" file="client.go:168"

Does the last log mean that the response is already received but somehow is not handled correctly?

**Comment by shuo-wu** [comment] 2023-12-05 02:24
I see... It seems that [this timer](https://github.com/longhorn/go-spdk-helper/blob/4dcc6f22bc08a339c793db731021f94cfcd9f156/pkg/jsonrpc/client.go#L222) should be reset before `select` rather than after `select`.

**Comment by derekbit** [comment] 2023-12-05 04:09
> Sorry... This should mean the 30-second timeout is enough. Is this a typo?

Ah, sorry, it's typo.


The issue is still persistent after applying https://github.com/longhorn/go-spdk-helper/pull/53.

**Comment by shuo-wu** [comment] 2023-12-05 08:54
Weird... And I cannot reproduce it...

**Comment by innobead** [comment] 2023-12-13 16:15
@derekbit is this resolved already from your testing? If yes, let's close this issue.

**Comment by yangchiu** [comment] 2023-12-18 08:06
Verified passed on master-head (longhorn-instance-manager 0d57324) following [the test steps](https://github.com/longhorn/longhorn/issues/7253#issue-2024014195). Block type disks can be added, and v2 volumes can be created.

**Closed by yangchiu** 2023-12-18 08:06 UTC
Labels: kind/bug, priority/0, area/v2-data-engine, require/qa-review-coverage, require/backport
