### ISSUE TITLE
[BUG] New Servers with Same Hostname Causes Host to Be Unschedulable

### ISSUE THREAD

**Issue by ekristen** [longhorn/longhorn#1781] opened 2020-09-10 15:35 UTC
**Describe the bug**

If you delete the k8s node and recreate and re-join it to the cluster before you have a chance to tell longhorn to delete the node, when the new node comes online the node will never be usable.

**To Reproduce**
1. Delete a node from an existing k8s cluster
2. Create a new node and name it the same name
3. The node will permanently be unschedulable and the storage information will be all empty.

**Expected behavior**
I would expect that longhorn should either A) cleanup a node from longhorn the minute it's removed from k8s or B) at least detect the node has changed since the node information will be different such as machineID and systemUUID and fix it so the node is usable.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.18.6
 - Node OS type and version: ubuntu 20.04

**Additional Context:**
I am using Rancher 2 with Node Pools and for testing and understanding of how longhorn would respond under certain conditions, I deleted a node and allowed it to be recreated by the node controller.

**Comment by yasker** [comment] 2020-09-10 21:23
it's a duplicate of https://github.com/longhorn/longhorn/issues/1232. We're fixing it for v1.1.0.

Once it's fixed, the node would be automatically removed from Longhorn when it's removed from Kubernetes.

Before v1.1.0, the workaround is to delete the disk on the node following the steps at https://longhorn.io/docs/1.0.2/volumes-and-nodes/maintenance/#removing-a-disk , then re-add the disk on the new node.

Close as duplicate of #1232

**Closed by yasker** 2020-09-10 21:23 UTC
