### ISSUE TITLE
[FEATURE] instance-manager compatibility with Cluster Autoscaler

### ISSUE THREAD

**Issue by drewhemm** [longhorn/longhorn#2203] opened 2021-01-21 17:30 UTC
**Is your feature request related to a problem? Please describe.**
When using Cluster Autoscaler, nodes are not removed from the cluster if they have bare pods; an annotation can be added to pods to let CA know it is safe to evict them:

https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node

```
"cluster-autoscaler.kubernetes.io/safe-to-evict": "true"
```

A node that has no other workloads running should be a candidate for removal from the cluster, but alas:

```
I0121 16:44:11.071945       1 cluster.go:93] Fast evaluation: ip-10-xxx-xx-xxx.eu-west-1.compute.internal for removal
I0121 16:44:11.071966       1 cluster.go:107] Fast evaluation: node ip-10-xxx-xx-xxx.eu-west-1.compute.internal cannot be removed: longhorn-system/instance-manager-e-1c19a568 is not replicated
```

**Describe the solution you'd like**
The option to specify annotations to be added to instance-manager pods would solve this issue. When installing Longhorn via Helm, there is the option to provide annotations for the ingress in the `values.yaml` - similar functionality would be desirable. 

**Describe alternatives you've considered**
A mutating webhook might be an option, but that is a lot of work. 

**Additional context**
Without this functionality, it is not possible to use Longhorn in conjuction with Cluster Autoscaler as it CA will be blocked from removing any nodes from the cluster.

**Comment by drewhemm** [comment] 2021-01-21 17:32
I tried to find the source code for where the pod spec is defined, but could not find it.

**Comment by joshimoo** [comment] 2021-01-21 18:07
If you want to dynamically remove nodes from the cluster you want to use dedicated storage nodes, otherwise you risk removing the last replica of your data.

https://longhorn.io/docs/1.1.0/volumes-and-nodes/storage-tags/
https://longhorn.io/docs/1.1.0/advanced-resources/default-disk-and-node-config/

We implement a poddisruption budget to prevent eviction of the last healthy replica. To prevent a user from doing just that.
We cannot add the above since it's not safe to delete the nodes unless we know there are other nodes with a healthy replica of the data.

**Comment by drewhemm** [comment] 2021-01-21 23:26
Thanks for the quick reply. The problem is not the nodes being used to host the replicas, it's all the other nodes in the cluster - every one gets a longhorn pod, which I assume is to enable them to mount the volumes for the pods that they are hosting. `instance-manager-e-*` pods are the problem, not the `instance-manager-r-*` ones. 

My 'longhorn' nodes are static, but I want every other node to be able to dynamically come and go when needed.

**Comment by munjalpatel** [comment] 2021-01-22 02:35
I agree with @drewhemm . I am facing the same exact problem in my AKS since I introduced longhorn to the cluster a week ago. 

After spending an entire day troubleshooting why autoscaler does not mark a node that has nothing but `instance-manager-e-*` and `instance-manager-r-*` pods with MSFT, we were able to pinpoint the root cause to be these two longhorn pods from the following autoscaler logs:

```
longhorn-system/instance-manager-r-f5b7da98 and  longhorn-system/instance-manager-e-698e6cf0 are not replicated
```

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/2717686/105438173-4fef0600-5c17-11eb-804c-d5fa92b9f7da.png">

**Comment by drewhemm** [comment] 2021-01-22 08:14
I have come across a project called [kube-annotate](https://github.com/chickenzord/kube-annotate), which may provide a short-term solution. It uses a mutating admission controller to perform rule-based annotation of pods; I should be able to enforce annotation of the `instance-manager-e-*` pods with that. Would prefer if this functionality were available without the use of a third-party app though. 

Is there a particular reason bare pods are used instead of a DaemonSet?

**Comment by munjalpatel** [comment] 2021-01-26 05:54
Folks, I would really appreciate some help here. We really want (need) to use `longhorn`.

However, this issue is significant since it completely prevents autoscaler to scale down.
We have a large cluster where proper functioning of autoscaler is vital for cost optimization and has significant material impact on business. I am fairly sure as more folks start utilizing amazing powers of longhorn, they will very likely run into this issue as well.

**Comment by joshimoo** [comment] 2021-01-27 09:45
@munjalpatel please ensure you use always available dedicated storage nodes, if you plan on dynamically adding/removing nodes from your cluster. See for how to set this up: https://github.com/longhorn/longhorn/issues/2203#issuecomment-764836290

For the moment you can use the workaround posted by @drewhemm here: https://github.com/longhorn/longhorn/issues/2203#issuecomment-765224243

To allow autoscaler to remove the nodes, please do not remove `instance-manager-r-*` pods since that will potential lead to data loss, therefore it's important to use always available dedicated storage nodes for this type of setup.

**Comment by drewhemm** [comment] 2021-01-27 13:07
Hi @munjalpatel, I am working on a fork of kube-annotate, which we will use to workaround this issue:

https://github.com/footprintmediaits/kube-annotate/tree/refactor-k8s-1.18

Will post back here once it is ready for use. There were some [issues](https://github.com/chickenzord/kube-annotate/issues/1) in the original repo, plus the code was outdated and not working with more recent versions of k8s.

**Comment by drewhemm** [comment] 2021-01-27 15:09
Well this is highly frustrating! We have got `kube-annotate` working, so that it adds the necessary annotation to the `instance-manager-e` pods:

```
$ k describe pod instance-manager-e-086cec4d -n longhorn-system 
Name:                 instance-manager-e-086cec4d
Namespace:            longhorn-system
Priority:             1000000000
Priority Class Name:  longhorn-node-critical
Node:                 ip-10-xxx-xx-xxx.eu-west-1.compute.internal/10.xxx.xx.xxx
Start Time:           Wed, 27 Jan 2021 14:30:36 +0000
Labels:               longhorn.io/component=instance-manager
                      longhorn.io/instance-manager-image=imi-a7211c27
                      longhorn.io/instance-manager-type=engine
                      longhorn.io/node=ip-10-xxx-xx-xxx.eu-west-1.compute.internal
Annotations:          cluster-autoscaler.kubernetes.io/safe-to-evict: true
```

...but now we hit the pod disruption budget - there is one created for each pod:

```
I0127 15:03:29.833597       1 cluster.go:107] Fast evaluation: node ip-10-xxx-xx-xxx.eu-west-1.compute.internal cannot be removed: not enough pod disruption budget to move longhorn-system/instance-manager-e-4d60be69
```

```
$ k get pdb -n longhorn-system
NAME                          MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
instance-manager-e-086cec4d   1               N/A               0                     31m
instance-manager-e-28bdfdc4   1               N/A               0                     31m
instance-manager-e-3a2f58a6   1               N/A               0                     8m50s
instance-manager-e-4d60be69   1               N/A               0                     8m41s
instance-manager-e-517b42e1   1               N/A               0                     31m
instance-manager-e-58ee7223   1               N/A               0                     31m
instance-manager-e-59f3cdbf   1               N/A               0                     31m
instance-manager-e-5bbb6c47   1               N/A               0                     31m
instance-manager-e-6c38fcd9   1               N/A               0                     31m
instance-manager-e-7bc17525   1               N/A               0                     30m
instance-manager-e-9f3d2f20   1               N/A               0                     31m
```

I must ask again: why are these deployed as bare pods instead of using a daemonset?

**Comment by drewhemm** [comment] 2021-01-27 22:39
Okay, I managed to resolve this. I modified the [generateInstanceManagerPDBManifest function](https://github.com/longhorn/longhorn-manager/blob/f77e4949cf16f72adaf885fc1c89cf1eeb6a1788/controller/instance_manager_controller.go#L617) to set the `minAvailable` for the `instance-manager-e` pods to 0: 

```diff
func (imc *InstanceManagerController) generateInstanceManagerPDBManifest(im *longhorn.InstanceManager) *policyv1beta1.PodDisruptionBudget {
+       var minAvailable int32
+       switch im.Spec.Type {
+       case types.InstanceManagerTypeEngine:
+               minAvailable = 0
+       case types.InstanceManagerTypeReplica:
+               minAvailable = 1
+       }
+
        return &policyv1beta1.PodDisruptionBudget{
                ObjectMeta: metav1.ObjectMeta{
                        Name:      imc.getPDBName(im),
@@ -636,7 +644,7 @@ func (imc *InstanceManagerController) generateInstanceManagerPDBManifest(im *lon
                        Selector: &metav1.LabelSelector{
                                MatchLabels: types.GetInstanceManagerLabels(imc.controllerID, im.Spec.Image, im.Spec.Type),
                        },
-                       MinAvailable: &intstr.IntOrString{IntVal: 1},
+                       MinAvailable: &intstr.IntOrString{IntVal: minAvailable},
                },
        }
 }
```

```
$ k get pdb -n longhorn-system                                                                                                   
NAME                          MIN AVAILABLE   MAX UNAVAILABLE   ALLOWED DISRUPTIONS   AGE
instance-manager-e-1da759a2   0               N/A               1                     7m20s
instance-manager-e-1f738b53   0               N/A               1                     7m15s
instance-manager-e-3bff3057   0               N/A               1                     7m10s
instance-manager-e-3fc08fa7   0               N/A               1                     7m19s
instance-manager-e-4e360a47   0               N/A               1                     7m11s
instance-manager-e-58203680   0               N/A               1                     7m7s
instance-manager-e-64701ec6   0               N/A               1                     7m17s
instance-manager-e-8dca7df2   0               N/A               1                     7m18s
instance-manager-e-9d3d5270   0               N/A               1                     7m20s
instance-manager-e-9f04dedc   0               N/A               1                     7m22s
instance-manager-e-a1db56ad   0               N/A               1                     7m17s
instance-manager-e-ca1649ac   0               N/A               1                     7m1s
instance-manager-e-cba916da   0               N/A               1                     7m19s
instance-manager-e-cea9a16f   0               N/A               1                     7m20s
instance-manager-e-dcea3dd2   0               N/A               1                     7m21s
instance-manager-e-e733cb65   0               N/A               1                     7m24s
instance-manager-e-e7406741   0               N/A               1                     7m21s
instance-manager-e-fc672c06   0               N/A               1                     7m21s
instance-manager-r-22bbd375   1               N/A               0                     7m1s
instance-manager-r-68329745   1               N/A               0                     7m7s
instance-manager-r-9a9ff2dd   1               N/A               0                     7m12s
```

In conjunction with kube-annotate, this allows CA to remove the nodes hosting these pods when no other workloads require the capacity:

```
I0127 22:30:29.675899       1 cluster.go:93] Fast evaluation: ip-10-xxx-xx-xxx.eu-west-1.compute.internal for removal
I0127 22:30:29.676532       1 cluster.go:124] Fast evaluation: node ip-10-xxx-xx-xxx.eu-west-1.compute.internal may be removed
```

Will fork and raise a PR for this tomorrow. In the meantime, it is possible to make that change, build the instance-manager image and use it instead of the published one.

**Comment by drewhemm** [comment] 2021-01-27 23:01
PR: https://github.com/longhorn/longhorn-manager/pull/823

I also found where the annotations are defined for the instance-manager pods:

https://github.com/longhorn/longhorn-manager/blob/f77e4949cf16f72adaf885fc1c89cf1eeb6a1788/controller/instance_manager_controller.go#L818

```go
Annotations:     map[string]string{types.GetLonghornLabelKey(types.LastAppliedTolerationAnnotationKeySuffix): string(tolerationsByte)},
```

Would it be acceptable to add the CA annotation here for [compatibility](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node), rather than using kube-annotate? Only for the `instance-manager-e` pods, naturally.

**Comment by drewhemm** [comment] 2021-01-27 23:44
PR that includes setting the annotation directly within longhorn instead of using kube-annotate:

https://github.com/longhorn/longhorn-manager/pull/824

```diff
@@ -810,12 +818,20 @@ func (imc *InstanceManagerController) createGenericManagerPodSpec(im *longhorn.I
        }
 
        privileged := true
+
+       var annotations map[string]string = make(map[string]string)
+       if im.Spec.Type == types.InstanceManagerTypeEngine {
+               annotations["cluster-autoscaler.kubernetes.io/safe-to-evict"] = "true"
+       }
+
+       annotations[types.GetLonghornLabelKey(types.LastAppliedTolerationAnnotationKeySuffix)] = string(tolerationsByte)
+
        podSpec := &v1.Pod{
                ObjectMeta: metav1.ObjectMeta{
                        Name:            im.Name,
                        Namespace:       imc.namespace,
                        OwnerReferences: datastore.GetOwnerReferencesForInstanceManager(im),
-                       Annotations:     map[string]string{types.GetLonghornLabelKey(types.LastAppliedTolerationAnnotationKeySuffix): string(tolerationsByte)},
+                       Annotations:     annotations,
                },
                Spec: v1.PodSpec{
                        ServiceAccountName: imc.serviceAccount,
```

I understand this may be more controversial than the PR that merely adjusts the PDBs as this one explicitly provides full support for CA.

**Comment by joshimoo** [comment] 2021-01-28 09:27
@drewhemm we discussed some of this last night, is it possible to configure the cluster autoscaler to cordon and drain the node before the check?

Do you have to do anything with the workloads before the cluster autoscaler removes the nodes?
Or does it just delete the node + all resources?

We do want to support cluster auto scaling, so we are looking into how the autoscaler works to get a better understanding of what should be done on our side.

We currently only remove the pdb on the instance-manager-e when it's cordoned (unschedulable) and no active volume is present, we are discussing just having this be when no active engine process is present (no attached volumes).

**Comment by PhanLe1010** [comment] 2021-01-28 09:32
Too add to @joshimoo comment, the reason we need to use `poddisruptionbudget` protect engine manager pod from being deleted when there are volume engines inside it was because this issue https://github.com/longhorn/longhorn/issues/1631#issuecomment-687055380

**Comment by yasker** [comment] 2021-02-01 22:43
@drewhemm It seems we need to understand how cluster autoscaler works. Longhorn is blocking the deletion for engine instance managers because those are hosting Longhorn engine. If the engines are still running inside those pods, that means the Pods haven't been evicted from the node. So if we forcefully remove the engine instance managers, the workload that's running on the node will crash. So in theory, as long as the cluster autoscaler follow the normal Kubernetes cordon/drain/remove logic for nodes, there probably shouldn't be any modification needed on Longhorn part to get it work. 

The concern for annotation is another thing since it didn't bother Kubernetes `drain` logic due to the `ownerReference` of the pod was set. Not sure why cluster autoscaler requires different criteria for drain compare to `kubectl drain`. See https://github.com/longhorn/longhorn/issues/1286 for details on how we fix the `kubectl drain`.

**Comment by drewhemm** [comment] 2021-02-01 23:23
There is a FAQ entry for CA in relation to PDBs [here](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#does-ca-work-with-poddisruptionbudget-in-scale-down):

"Before starting to terminate a node, CA makes sure that PodDisruptionBudgets for pods scheduled there allow for removing at least one replica."

If the LH engine pods' PDBs do not allow for them to be rescheduled, CA will be permanently blocked from removing nodes from the cluster.

Since CA respects [graceful termination](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#does-ca-respect-gracefultermination-in-scale-down), PDB is not required. CA can drain a node and it will wait for any workloads on the node to terminate cleanly and if any had LH volumes mounted, it will also wait for the LH engine pod to shut down also.

**Comment by drewhemm** [comment] 2021-02-01 23:26
> 
> Not sure why cluster autoscaler requires different criteria for drain compare to `kubectl drain`. 

I don't think CA has different criteria than `kubectl drain`, it is just that it has criteria for _deciding_ whether to issue to drain command.

**Comment by jenting** [comment] 2021-03-26 03:44
The pod instance might have the same problem
If the users have replicas across 3 nodes but then a scale in could potentially remove the 3 nodes with the replicas.

ref to https://rancher-users.slack.com/archives/CC2UQM49Y/p1616608281051900

**Comment by innobead** [comment] 2021-04-29 05:25
> > Not sure why cluster autoscaler requires different criteria for drain compare to `kubectl drain`.
> 
> I don't think CA has different criteria than `kubectl drain`, it is just that it has criteria for _deciding_ whether to issue the drain command.

`kubectl drain` adopted by CA is no different, but the only difference is CA has a self-designed pre-check for PDB. However, longhorn has some mechanism to decide to remove engine/replica PDB when `drain` executed, but it's not possible to happen if the CA PDB pre-check is the pre-criteria.

Given we can't change CA behavior, we probably need to do some investigation to understand how/what Longhorn can do for CA support in some conditions. For example, thinking from Longhorn side, if users want to adopt CA, we automatically add the annotation when some conditions met like longhorn node unschedulable and replicas evicted.

**Comment by zbialik** [comment] 2021-07-30 15:03
do we think this will be available in the v1.2.0 release?

**Comment by chris93111** [comment] 2021-11-20 01:31
Hi any update ?

**Comment by innobead** [comment] 2021-12-22 07:27
> Hi any update ?

We will revisit this after 1.3.0 and it will be planned then. Thank you.

**Comment by robjuz** [comment] 2022-01-01 19:35
I'm also really interested in this feature. I have dedicated storage nodes and would love to have dynamic worker nodes.

**Comment by PhanLe1010** [comment] 2022-01-03 23:26
@robjuz 
> I have dedicated storage nodes and would love to have dynamic worker nodes.

Can you check if this blog helps with your use case https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/ ?

**Comment by robjuz** [comment] 2022-01-04 06:49
@PhanLe1010 
It's a very nice article but it's not exactly what I need. I would like to use Cluster Autoscaler. So I would like to be able to schedule workload that uses Longhorn volumes on all nodes, so I need to install longhorn components on ale nodes. This components prevent autoscaler to scale down.

**Comment by PhanLe1010** [comment] 2022-01-04 23:38
@robjuz 

It might work for this specific use case: you have 2 sets of nodes: storage nodes (s1) and worker nodes (s2) with the following assumption:
* s1 is stable. It does use AC
* s2 is dynamic. It can use AC
* Install Longhorn using the first method in the article https://longhorn.io/kb/tip-only-use-storage-on-a-set-of-nodes/ (e.g., Tell Longhorn to create a default disk on s1 nodes)

Now, when you use AC to scale down nodes in s2, I assume that AC will drain then terminate the nodes in S2. When draining a node x in s2, Longhorn engine PDB will block the drain command until the workload that uses Longhorn volumes on node x are drained. At this point, Longhorn removes the engine PDB. The drain command can continue and succeed. AC then can terminate node x. I have not tested the step, but can you give it a try?

**Comment by sharanbabumg** [comment] 2022-01-28 02:43
Hello Team,

Am using longhorn in EKS cluster, whatever the solutions provided above didnt help me to fix the issue with 
I0128 02:23:03.483707       1 cluster.go:107] Fast evaluation: node ip-x-x-x-x.eu-central-1.compute.internal cannot be removed: longhorn/instance-manager-e-6499af6d is not replicated
I0128 02:23:03.483735       1 scale_down.go:548] 3 nodes found to be unremovable in simulation, will re-check them at 2022-01-28 02:28:03.480658881 +0000 UTC m=+227737.684989981

Even i tried to add annotation manually to instance manager e pods directly and the annotations seems working again i saw pdb issue.

0112 08:20:39.684806 1 cluster.go:107] Fast evaluation: node ip-x-x-x-x.eu-central-1.compute.internal cannot be removed: not enough pod disruption budget to move longhorn/instance-manager-e-6b01818a

I have upgraded longhorn to 1.2.2 but still i see this exists. Is there any solution which can be directly added to code and build the new image and updated to latest version of longhorn.

Note: For on-prem cluster dedicated nodes assigned for longhorn storage, hence working fine.

**Comment by c3y1huang** [comment] 2022-04-07 02:30
We could have a new global setting `kubernetes-autoscaler-support`. When enabled, Longhorn adds in the annotation to components and also does instance-manager PDB management.

**Annotation**
The `cluster-autoscaler.kubernetes.io/safe-to-evict` annotation should be on all Longhorn pods with hostPath volume mounts.
- Annotate engine and replica instance-manager pods when no instance process inside the instance manager.
- Annotate longhorn-ui, longhorn-csi-plugin, csi-attacher, csi-provisioner, csi-resizer, and csi-snapshotter.

Ref [What types of pods can prevent CA from removing a node?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#what-types-of-pods-can-prevent-ca-from-removing-a-node)

**PodDisruptionBudget**
Longhorn also needs to manage instance-manager PDB. When CA tries to delete pods from a node through the pod eviction API, the request will fail due to the eviction is not currently allowed because of the configured PodDisruptionBudget.
- Delete engine instance-manager PBD when volumes are detached.
- Delete replica instance-manager PBD when all volumes are detached and there is another healthy volume replica on another node.

Ref [Does CA work with PodDisruptionBudget in scale-down?](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/FAQ.md#does-ca-work-with-poddisruptionbudget-in-scale-down) and [How API-initiated eviction works](https://kubernetes.io/docs/concepts/scheduling-eviction/api-eviction/#how-api-initiated-eviction-works).

**Limitation**
Because of the risk of data loss, Longhorn should not remove the PDB if the replica number in the volume spec is configured to 1 (no healthy replica on another node). In this case, Pod will block scale down by the PDB.

**Comment by c3y1huang** [comment] 2022-04-08 01:02
> **PodDisruptionBudget** Longhorn also needs to manage instance-manager PDB. When CA tries to delete pods from a node through the pod eviction API, the request will fail due to the eviction is not currently allowed because of the configured PodDisruptionBudget.
> 

However, there seems to be a simpler way. Longhorn could probably look for schedulable taint marked by CA.  I think the pre-check only validates the kube-system namspace ([ref](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/utils/drain/drain.go#L76)) and the current failure actually coming from the actual eviction API response ([ref](https://github.com/kubernetes/autoscaler/blob/master/cluster-autoscaler/core/scale_down.go#L1290)). I will verify if longhorn PBD can pass the pre-check.

**Comment by kaxing** [comment] 2022-05-17 11:57
Initial test with Longhorn v1.3.0-preivew1 with GKE result positive with new test case: [test_cluster_autoscaler ](https://github.com/longhorn/longhorn-tests/pull/936)

The new global setting will allow autoscaler to scale down the nodes with longhorn managed pods.

AKS and EKS will be testing with rc image.

**Comment by kaxing** [comment] 2022-06-07 05:51
Validation - **PASSED**

Tested with v1.3.0 branch c2, master-head image.
AKS also tested with [test_cluster_autoscaler ](https://github.com/longhorn/longhorn-tests/pull/936)

I will close this for now as EKS will be tested a bit later in the release cycle.

**Closed by kaxing** 2022-06-07 05:51 UTC
Labels: kind/enhancement, area/manager, area/deployment, priority/1, investigation-needed, area/public-cloud
