### ISSUE TITLE
[BUG] Corruption using XFS after node restart or pod scale

### ISSUE THREAD

**Issue by stephanGarland** [longhorn/longhorn#3597] opened 2022-02-07 22:24 UTC
## Describe the bug

Upon either restarting a kubernetes worker node hosting Longhorn replicas, or during pod scaling (e.g. scaling a StatefulSet to 0), I've sometimes experienced silent data corruption. Following the Longhorn docs for detecting and deleting a failed replica does find a different hash, but deleting the replica doesn't solve the problem. Ultimately restoring from a snapshot is the only fix.

Of note, I'm using XFS as the underlying filesystem, and all affected apps have used SQLite.

Unfortunately/fortunately, this problem seems to be non-deterministic. I've experienced it twice; once when restarting a node for maintenance, and once scaling an app down and up.

## To Reproduce

1. Use StatefulSets with VolumeClaimTemplates to define PVCs.
2. Restart a node containing replicas, or scale StatefulSets utilizing the PVCs to 0 and back to n>0.

## Expected behavior

The replica volumes to return to service with no corruption.

## Log or Support bundle

Example `dmesg` from a `longhorn-manager` pod. Note that while this shows the recovery completing, others do not. I unfortunately don't have timestamps to match up a failed one, although I can confirm that I experienced issues with this linked PVC, requiring a snapshot recovery.

```

[ 1332.278329] XFS (sdc): Metadata CRC error detected at xfs_agfl_read_verify+0xa2/0xf0 [xfs], xfs_agfl block 0x3
[ 1332.278332] XFS (sdc): Unmount and run xfs_repair
[ 1332.278334] XFS (sdc): First 128 bytes of corrupted metadata buffer:
[ 1332.278343] 00000000: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278344] 00000010: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278345] 00000020: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278346] 00000030: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278346] 00000040: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278347] 00000050: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278348] 00000060: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278348] 00000070: 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00 00  ................
[ 1332.278368] XFS (sdc): metadata I/O error in "xfs_trans_read_buf_map" at daddr 0x3 len 1 error 74
[ 1332.365389] XFS (sdc): xfs_do_force_shutdown(0x8) called from line 446 of file fs/xfs/libxfs/xfs_defer.c. Return address = 0000000061a87018
[ 1332.365393] XFS (sdc): Corruption of in-memory data detected.  Shutting down filesystem
[ 1332.365394] XFS (sdc): Please unmount the filesystem and rectify the problem(s)
[ 1447.117969] cni0: port 13(veth6f28afba) entered disabled state
[ 1447.129033] device veth6f28afba left promiscuous mode
[ 1447.129059] cni0: port 13(veth6f28afba) entered disabled state
[ 1448.304291] XFS (sdc): Unmounting Filesystem
[ 1452.882691] sd 7:0:0:1: [sdc] Synchronizing SCSI cache
[ 1459.419198] scsi host7: iSCSI Initiator over TCP/IP
[ 1459.448202] scsi 7:0:0:0: RAID              IET      Controller       0001 PQ: 0 ANSI: 5
[ 1459.450009] scsi 7:0:0:0: Attached scsi generic sg3 type 12
[ 1459.451601] scsi 7:0:0:1: Direct-Access     IET      VIRTUAL-DISK     0001 PQ: 0 ANSI: 5
[ 1459.452849] sd 7:0:0:1: Attached scsi generic sg4 type 0
[ 1459.453233] sd 7:0:0:1: Power-on or device reset occurred
[ 1459.455747] sd 7:0:0:1: [sdc] 4194304 512-byte logical blocks: (2.15 GB/2.00 GiB)
[ 1459.456106] sd 7:0:0:1: [sdc] Write Protect is off
[ 1459.456111] sd 7:0:0:1: [sdc] Mode Sense: 69 00 10 08
[ 1459.456794] sd 7:0:0:1: [sdc] Write cache: enabled, read cache: enabled, supports DPO and FUA
[ 1460.586295] sd 7:0:0:1: [sdc] Attached SCSI disk
[ 1469.044275] XFS (sdc): Mounting V5 Filesystem
[ 1471.123131] XFS (sdc): Starting recovery (logdev: internal)
[ 1471.572637] XFS (sdc): Ending recovery (logdev: internal)
[ 1471.624639] xfs filesystem being mounted at /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-81fb33a4-4b2e-425b-b6df-9dbd7af36034/globalmount supports timestamps until 2038 (0x7fffffff)
[ 1471.850475] xfs filesystem being remounted at /var/lib/kubelet/pods/f0f3ff6b-841c-4c4e-a0f9-28cbd9fbac80/volumes/kubernetes.io~csi/pvc-81fb33a4-4b2e-425b-b6df-9dbd7af36034/mount supports timestamps until 2038
(0x7fffffff)

```

`/sys/devices/system/edac/mc/mc{0,1}` on each node shows 0 corrected and 0 uncorrected errors.

## Environment

 - Longhorn version: v1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.21.5+k3s2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: k3OS v0.21.5-k3s2r1
   - CPU per node: E5-2650 v2
       - Manager: 4
       - Worker: 28
   - Memory per node: DDR3-PC10600R
       - Manager: 8 Gi
       - Worker: 24 Gi
   - Disk type(e.g. SSD/NVMe): SSD (Intel DC S3500 300GB)
   - Network bandwidth between the nodes: 1 GBe
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): KVM (Proxmox)
 - Number of Longhorn volumes in the cluster: 20

**Comment by shuo-wu** [comment] 2022-02-08 03:18
Do you mean the XFS filesystem is corrupted when the issue is triggered? Or is there inconsistency among replicas of the volume?

**Comment by stephanGarland** [comment] 2022-02-08 03:24
There is inconsistency among replicas. In the two times I've seen it, one replica differs in its hash for a given volume. Following the guide to delete the inconsistent replica does not resolve the problem.

**Comment by shuo-wu** [comment] 2022-02-08 04:03
> There is inconsistency among replicas. In the two times I've seen it, one replica differs in its hash for a given volume. Following the guide to delete the inconsistent replica does not resolve the problem.

Does not Longhorn mark the inconsistent replicas as ERROR automatically?

**Comment by stephanGarland** [comment] 2022-02-08 04:06
No, the UI shows them as fine. I only noticed a problem because the app failed to launch (or failed to work properly), so I checked the hashes.

**Comment by shuo-wu** [comment] 2022-02-08 04:10
Weird... What's the underlying filesystem of the replica directories?
We may need to try reproducing it first.

**Comment by stephanGarland** [comment] 2022-02-08 04:17
`/dev/sdb on /mnt/longhorn type xfs (rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota)`

I can try to break it again tomorrow, and capture more logs. Anything in particular you'd like to see?

**Comment by shuo-wu** [comment] 2022-02-08 08:39
Can you export the kubelet log and `dmesg` result besides the Longhorn support bundle? I am not sure if there are more clues in these logs but let's take a look first.

**Comment by stephanGarland** [comment] 2022-02-10 00:42
[k3s_kubelet.log](https://github.com/longhorn/longhorn/files/8037116/k3s_kubelet.log)
[kw01_dmesg.log](https://github.com/longhorn/longhorn/files/8037117/kw01_dmesg.log)
[longhorn_shas.txt](https://github.com/longhorn/longhorn/files/8037118/longhorn_shas.txt)
[longhorn-support-bundle_a0d2f19d-cc3c-40ea-ac41-47baad381803_2022-02-10T00-00-40Z.zip](https://github.com/longhorn/longhorn/files/8037119/longhorn-support-bundle_a0d2f19d-cc3c-40ea-ac41-47baad381803_2022-02-10T00-00-40Z.zip)

Here's an organic event that just happened. Deleting the odd-out replica didn't fix the problem. Weirdly, although the node `dell03-k3s-worker-01` was the one reporting a different SHA (and thus the one I deleted), the dmesg error was from `dell01-k3s-worker-01` - the other two reported no issues in their logs.

Unfortunately my most recent snapshot was also bad, so I had to delete the PVC and recreate it using a manual backup I performed a few weeks ago, copying the files in.

I checked the SSDs on the node for SMART errors but didn't see any, FWIW.

**Comment by jperville** [comment] 2022-02-17 15:53
Hello, we are encountering the issue often on VMs :
 - running kubernetes inside
 - when partitions are formatted in XFS
 - when the VM is shutdown externally (eg. `virtcl stop myvm`, or VM pod evicted on the host cluster)

When the VM restarts, we often have errors in the console about volumes not mounting... then we have to stop the VM again, mount the volumes manually and attempt to repair. Sometimes it works and sometimes it does not (the volume can be mounted and some data recovered, but if we try to `xfs_repair` a partition on the volumes the command will fail because of xfs not finding superblocks).

Also, restoring from earlier backup/snapshot taken by longhorn cronjob may not work because the snapshot was taken when the VM is running and there may dirty filesystem operations.

I am looking for ideas to:
 - have the kubernetes node inside the VM shutdown gracefully (probably using kubernetes Graceful Shutdown feature)
 - have confidence that the backups/snapshots taken by longhorn are viable (that they can be mounted without XFS corruption).

I can help to reproduce the problem for investigation of course.

**Comment by shuo-wu** [comment] 2022-02-18 12:37
@jperville I guess the cause of this issue is that the VM & Longhorn volume is shut down while the metadata of the underlying fs is being modified. Then this shutdown would lead to the fs being broken. 
For this kind of issue, right now Longhorn team is investigating application-level consistency (at least for snapshot and backup) and the feature is tracked in https://github.com/longhorn/longhorn/issues/2128

**Comment by jperville** [comment] 2022-02-18 14:38
Hello @shuo-wu , yes having a feature to do application-aware snapshots of volumes (and even better: groups of related volumes such as all volumes used by a VM) would help a lot.

**Comment by stephanGarland** [comment] 2022-02-19 15:06
I've now encountered this issue without any shutdowns, or even usage. My NAS was shutdown for approximately a week due to a hardware issue, and so I scaled down any deployments or statefulsets utilizing it. The Longhorn volumes associated with them were detached.

When I brought them back up yesterday after having repaired the NAS, one of the volumes refused to mount, citing I/O errors. I noticed while ssh'd into a worker node that it had an XFS error for the mount. I attached the volume in maintenance mode to another node and tried running `xfs_repair`, but it was unable to find any superblocks to run the repair. Also, bizarrely, attempting to revert to the backup (which almost certainly should be good, as it was taken while the container was running) also failed. I may be misunderstanding how Longhorn's backup system works; if it's not concerned with the underlying filesystem, I can see how this would happen.

At this point it's becoming an undue annoyance, and I'm going to copy everything remaining out, re-init all Longhorn volumes as ext4, copy back, and move on.

**Comment by innobead** [comment] 2022-02-21 09:51
> I've now encountered this issue without any shutdowns, or even usage. My NAS was shutdown for approximately a week due to a hardware issue, and so I scaled down any deployments or statefulsets utilizing it. The Longhorn volumes associated with them were detached.
> 
> When I brought them back up yesterday after having repaired the NAS, one of the volumes refused to mount, citing I/O errors. I noticed while ssh'd into a worker node that it had an XFS error for the mount. I attached the volume in maintenance mode to another node and tried running `xfs_repair`, but it was unable to find any superblocks to run the repair. Also, bizarrely, attempting to revert to the backup (which almost certainly should be good, as it was taken while the container was running) also failed. I may be misunderstanding how Longhorn's backup system works; if it's not concerned with the underlying filesystem, I can see how this would happen.
> 
> At this point it's becoming an undue annoyance, and I'm going to copy everything remaining out, re-init all Longhorn volumes as ext4, copy back, and move on.

@stephanGarland so you use NAS for your longhorn disks? also gracefully shutdown all things before stoping the NAS? any failure you see from the backup restore? 

@joshimoo @derekbit any possible reason for the filesystem corruption except incorrect shutdown?  
cc @shuo-wu @jenting for backup part.

**Comment by derekbit** [comment] 2022-02-21 10:14
Not really sure if there is a bug in xfs. 
I think user can switch to use ext4 first and see if it still happens in ext4.

**Comment by stephanGarland** [comment] 2022-02-21 17:49
@innobead no, I have a NAS that my Kubernetes cluster accesses for storage, and is also the backup target for Longhorn via NFS.

Longhorn itself uses LVM groups passed to it from the hypervisor. They are currently two enterprise SSDs (Intel S3500), and were previously formatted with XFS. I'm now using ext4.

I didn't see any failures noted for the backup or restoration; just that after reverting to the backup, I still received the same I/O error from the pod trying to mount its PVC.

**Comment by derekbit** [comment] 2022-02-22 00:16
> I didn't see any failures noted for the backup or restoration; just that after reverting to the backup, I still received the same I/O error from the pod trying to mount its PVC.

Do you mean the xfs filesystem still showed IO error after restoring from the backup?

**Comment by stephanGarland** [comment] 2022-02-22 00:24
Correct.

**Comment by shuo-wu** [comment] 2022-02-22 04:52
> At this point it's becoming an undue annoyance, and I'm going to copy everything remaining out, re-init all Longhorn volumes as ext4, copy back, and move on.

Sure, you can try ext4 first. And some developers consider ext4 as the most stable fs. This conclusion is based on their daily experience without exact reason.

---

> I didn't see any failures noted for the backup or restoration; just that after reverting to the backup, I still received the same I/O error from the pod trying to mount its PVC.

I am not sure if there is data writing when you try to back up the volume. If YES, as we discussed above, Longhorn is not an application/filesystem awared storage solution now hence the backup may contain a corrupted/incomplete xfs.

---

> My NAS was shutdown for approximately a week due to a hardware issue, and so I scaled down any deployments or statefulsets utilizing it. The Longhorn volumes associated with them were detached.

As for this volume, do you mean that there is no downtime but the xfs in the volume becomes unavailable after the re-attachment?

**Comment by stephanGarland** [comment] 2022-02-24 01:42
> I am not sure if there is data writing when you try to back up the volume. If YES, as we discussed above, Longhorn is not an application/filesystem awared storage solution now hence the backup may contain a corrupted/incomplete xfs.

This is true, but since the application _was_ working up until I scaled it down in preparation for maintenance, it seems logical that the backup would also be good.

> As for this volume, do you mean that there is no downtime but the xfs in the volume becomes unavailable after the re-attachment?

There was no pod accessing the volume for a period of days, and when it came back up, it was inaccessible.

**Comment by shuo-wu** [comment] 2022-02-24 03:27
> There was no pod accessing the volume for a period of days
I mean, is there anything special before the volume is detached? After the volume detachment, the node temporary failure would not affect it unless the related disk is gone.

**Comment by WolfspiritM** [comment] 2022-02-24 17:01
Exactly that happened to us, too. We had to restart a few cluster nodes due to an issue an we have 6 xfs volumes attached to mongodb and all of them got broken. We had to manually attach all 3 data volumes and they were only fixable by using "xfs_repair -L /dev/longhorn..." while the log volumes somehow worked without -L.

All other ext4 volumes we are using are working fine and some directly attached xfs volumes are working fine, too.

**Comment by stephanGarland** [comment] 2022-02-24 17:09
> Is there anything special before the volume is detached?

No, I scaled down the StatefulSet to zero. I've done this countless times with no issues on other apps not using Longhorn for PVs.

I have yet to see an issue since reformatting with ext4, but it's only been a few days so far to be fair.

**Comment by stephanGarland** [comment] 2022-03-06 20:39
As a follow-up, since rebuilding with ext4 I have not experienced any issues, even when doing a hard reset of a heavily loaded worker node. The node resets, the pods reschedule, and Longhorn rebuilds the affected volumes.

**Comment by Foritus** [comment] 2022-03-06 20:41
I speculatively tried this out as well (as I could fairly reliably trash my longhorn PVCs by.. gracefully shutting down my nodes, which was distressing), and so far on ext4 it has been much more reliable.

**Comment by stephanGarland** [comment] 2022-03-17 12:49
@WolfspiritM @Foritus @jperville
What OS are you running for your Kubernetes nodes?

**Comment by WolfspiritM** [comment] 2022-03-17 12:55
@stephanGarland 
Ubuntu 20.04.3 LTS
Linux worker01 5.4.0-100-generic #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

**Comment by jperville** [comment] 2022-03-17 13:24
@stephanGarland VM host which is also longhorn host is running CentOS 7 with default kernel, VM guest also.

Linux envm-platform1 3.10.0-1160.36.2.el7.x86_64 #1 SMP Wed Jul 21 11:57:15 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux

**Comment by stephanGarland** [comment] 2022-03-17 17:46
That rules out k3os as the common factor, then - someone I was talking to thought it might be the issue.

If CentOS is experiencing the issues, there is almost no chance it's kernel-related.

**Comment by Foritus** [comment] 2022-03-17 20:39
Inside the worker:
```
> lsb_release -cd
Description:    Ubuntu 20.04.4 LTS
Codename:       focal

> uname -a
Linux kube-worker-4 5.4.0-104-generic #118-Ubuntu SMP Wed Mar 2 19:02:41 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

> kubelet --version
Kubernetes v1.23.4

> fdisk -l
{a bunch of /dev/loop devices}

Disk /dev/sda: 512 GiB, 549755813888 bytes, 1073741824 sectors
Disk model: QEMU HARDDISK
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disklabel type: gpt
Disk identifier: F1C1EBC9-A284-438D-A0BF-82A3B6B05F6F
Device     Start        End    Sectors  Size Type
/dev/sda1   2048       4095       2048    1M BIOS boot
/dev/sda2   4096 1073739775 1073735680  512G Linux filesystem
```

I have 7 worker nodes and 3 control plane nodes. They all have the same machine build.

The VM itself is using the `virtio-scsi` disk driver to provide TRIM-discard support:
```
> virsh edit kube-worker-4

    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2' discard='unmap'/>
      <source file='/vms/kube-worker-4.qcow2'/>
      <target dev='vda' bus='scsi'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <controller type='scsi' index='0' model='virtio-scsi'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
    </controller>
```

`/vms/` on the host machine is running ZFS in raid 1.

**Comment by jperville** [comment] 2022-03-21 08:40
Hello, while converting my XFS-based VMs to ext4 (workaround suggested for this issue), I have noticed that the size of the `ext4` partition was different when accessed by the VM or by the longhorn host. I had to resize2fs my volume down before booting the converted VM or it would just not boot.

Here are the details:
 - I manage my VMs with kubevirt
 - the kubevirt VM references a longhorn-provisioned PVC as "disk" (using virtio driver)
 - the longhorn PV associated with the PVC contains a single `disk.img` file (sparse file)
 - that `disk.img` file is exposed inside the VM as `/dev/vda`

Here is how `/dev/vda` looks like inside the VM:
```sh
[root@vm1.sandbox ~]# fdisk -l /dev/vda

Disk /dev/vda: 11.9 GB, 11866187264 bytes, 23176147 sectors
Units = sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
Disk label type: dos
Disk identifier: 0x000b0d11

   Device Boot      Start         End      Blocks   Id  System
/dev/vda1   *        2048    23176112    11587032+  83  Linux
```

The `/dev/vda1` partition was initially formatted as `xfs` (default for CentOS cloud images) but I converted it to `ext4` by:
 - taking a backup (preserving xattrs acls and selinux labels)
 - turning off the VM
 - attaching the longhorn volume to a longhorn host using the UI
 - mounting the longhorn volume on the longhorn host (`mount /dev/longhorn/pvc-xxxxx /mnt`)
 - setting loopback with offset to access `/dev/vda` as `/dev/loop1` (`losetup -o 1048576 /dev/loop1 /mnt/disk.img`)
 - formatting `/dev/loop1` as `ext4`
 - mounting `/dev/loop1` as `/mnt2`
 - restoring the backup into `/mnt2` (preserving xattrs acls and selinux labels)
 - umounting `/mnt2`
 - detaching `/dev/loop1` with `losetup -d /dev/loop1`
 - umounting the longhorn volume on the longhorn host
 - detaching the longhorn volume using the UI

After trying to boot the VM, boot fails at initramfs because the `/dev/vda1` partition is larger than the underlying device.
As a workaround I had to `resize2fs /dev/loop1 10G` just after formatting and before restoring the backup. The partition will be extended to fit the device size (seen by the VM) during the next boot of the VM.

When I formatted `/dev/loop` on the longhorn host, the partition was `2896762` blocks long:
```
[root@longhorn3 ~]# fsck.ext4 /dev/loop1
e2fsck 1.42.9 (28-Dec-2013)
/dev/loop1: clean, 11/724816 files, 88523/2896762 blocks
```

But when I did the `resize2fs /dev/vda1` inside the booted VM, the same partition is `2896758` blocks long (4 less than on the host):
```sh
[root@vm1.sandbox-labs2 ~]# resize2fs /dev/vda1
resize2fs 1.42.9 (28-Dec-2013)
The filesystem is already 2896758 blocks long.  Nothing to do!
```

I checked the `dmesg` on some VMs that I did not converted and I found the following message:
```
[2327901.557290] XFS (dm-1): Unmounting Filesystem
[2327916.027649] attempt to access beyond end of device
[2327916.028512] dm-1: rw=32, want=419430400, limit=167772160
[2327916.029382] XFS (dm-1): last sector read failed
```

My question: is it possible that the XFS corruption is due to the partition having a different size between longhorn host and VM?
Every time I has the XFS corruption it was when I tried to `xfs_repair /dev/loop1` when the longhorn volume was mounted on longhorn host.

**Comment by shuo-wu** [comment] 2022-04-06 08:55
@Foritus Sorry for the late reply. 
Here I am confused about how you are using Longhorn volume? Is the `volumeMode` `Block` in the corresponding PVC and are you mounting the volume as a block device in the VM? Then which one is responsible for filesystem `xfs` make and mount?

**Comment by shuo-wu** [comment] 2022-04-08 12:14
OK. Got it. Thank you for your detailed explanation!

Based on the description, the block device you checked both inside the VM and on host is actually the `disk.img` prepared by the Containerized Data Importer rather than the Longhorn volume itself (`/dev/longhorn/<volume name>` on host), right? Was the block count you get inside the VM actually that of when the `disk.img` contained the previous XFS filesystem? Here I need to mention that the min size of a Longhorn volume IO is actually 4K (which is restricted by the filesystem of its replicas) even if `fdisk -l /dev/longhorn/<Longhorn volume name>` shows the sector size is 512. Not sure if this would lead to the difference you mentioned. 
As for the Longhorn volume itself, the filesystem it uses seems to be unchanged. If YES, the corruption you encountered is more related to the filesystem used inside `disk.img`... 

BTW, volume block mode involves some capability issues. I am not sure if it applies to kubevirt. Harvester uses block mode volumes + Longhorn backing image feature to launch VM instances so that it can bypass the Containerized Data Importer. 

If I misunderstood anything, please let me know. Thank you!

**Comment by Martin-Weiss** [comment] 2022-09-14 07:58
Might be a bit "off topic" - but could the problem be related to /var/lib/longhorn not correct / clean "umounted" during shutdown / reboot? I have seen that containers and workload still has been running during shutdown blocking a clean umount of /var/lib/longhorn..

**Comment by derekbit** [comment] 2022-09-14 15:36
@stephanGarland 
I tried to reproduce the xfs filesystem corruption issue on AWS platform, but unfortunately, the corruption still cannot be reproduced. I scaled StatefulSet utilizing the PVC to 0 and back to 3 repeatedly, and every mount was successful.
Here is my setting. Any suggestion is appreciated.

- Host OS: Ubuntu 20.04 (kernel 5.4.0-1041-aws)
- K8s: v1.24.4+rke2r1
- Longhorn: v1.2.4

- Storage Class
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-xfs
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Delete
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  fsType: "xfs"
```

- StatefulSet
```
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: volume-test
  namespace: default
spec:
  selector:
    matchLabels:
      app: volume-test
  serviceName: "volume-test"
  replicas: 3
  template:
    metadata:
      labels:
        app: volume-test
    spec:
      #restartPolicy: Always
      terminationGracePeriodSeconds: 10
      containers:
      - image: naturlich/ubuntu:fs-corruption
        name: volume-test
        command: ["/bin/bash", "/root/sqlite.sh"]
        imagePullPolicy: Always
        volumeMounts:
        - name: longhorn-volv
          mountPath: /data
  volumeClaimTemplates:
  - metadata:
      name: longhorn-volv
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "longhorn-xfs"
      resources:
        requests:
          storage: 2Gi
```

- sqlite.sh
```
#!/bin/bash

rm -rf /data/test.db

sqlite3 /data/test.db <<EOF
create table helloworld (id INTEGER PRIMARY KEY,k TEXT,v TEXT);
EOF

for i in {1..100000};
do
KEY=`tr -dc A-Za-z0-9 </dev/urandom | head -c 4096`
VAL=`tr -dc A-Za-z0-9 </dev/urandom | head -c 4096`
sqlite3 /data/test.db <<EOF
insert into helloworld (k,v) values ('${KEY}','${VAL}');
EOF
done
```

cc @PhanLe1010 @shuo-wu @innobead

**Comment by stephanGarland** [comment] 2022-09-15 00:05
@derekbit other than minor version differences, the only difference I note is that you're using EBS which would present a block device. I was using LVM, and had formatted the VG with xfs on my hypervisor, then passed it through to the worker node, and pointed Longhorn to it.

**Comment by derekbit** [comment] 2022-09-20 03:51
We've identified the root cause of the filesystem corruption issue. We will explain how the corruption occurs in an ext4 filesystem and how it occurs in an XFS filesystem in this report.

## Reproduce steps
The script can help reproduce the issue.
- Create a PVC containing 3 replicas
- Attach the volume to one node (worker-1)
- Format the longhorn volume by `mkfs.ext4 -b 1024 /dev/longhorn/<pvc-name>` on worker-1 node
- Run the script on worker-2 node (need to update the DEV path)
```
#!/bin/bash

DEV=/dev/longhorn/<pvc-name>

for x in {1..30}
do
  echo "============== delete $x =============="
  REPLICA=`kubectl -n longhorn-system get --no-headers=true replicas -o name -l longhornnode=rancher50-worker2`
  echo $REPLICA
  kubectl -n longhorn-system delete $REPLICA

  for i in {1..2000}
  do
    echo $i
    date
    umount /mnt/disk
    mount "$DEV" /mnt/disk
    if [ $? != 0 ]; then
      exit 1
    fi
    sleep 0.01
  done
done
```

## Root Cause Analysis

The illustration shows how ext4 filesystem corruption and mount failure are caused.
The root cause is a mismatch between the logical block size (1024 bytes) of the iSCSI block device and the [copy-on-write (COW)](https://github.com/longhorn/longhorn-engine/blob/master/pkg/replica/diff_disk.go#L62) block size (4096 bytes) in Longhorn replica.

![image](https://user-images.githubusercontent.com/12527233/191160327-ba102827-827f-49fc-8b4b-dc1f97720c4d.png)

The full story is

**FIG 1 & 2**
After deleting one replica, LH starts rebuilding the deleted replica, which is marked as WO mode, and then takes a snapshot. Meanwhile, the snapshot is empty.
The new write io (offset=1024, length=1024) is incoming before finishing receiving the snapshot from the healthy replica (FIG2).

**FIG 3**
This write io also triggers the copy-on-write. The block size (replica.volume.sectorSize) used by copy-on-write operation is 4096 bytes. So, the data buffer contains two parts
0-1024 byte and 2048-4096 byte contains zero data reading from the empty snapshot
1024-2048 byte are the new data.
The merged data buffer is written to the volume-head.

**FIG 4 & FIG 5**
After finishing receiving the snapshot from the healthy replica, the prune operation prunes the redundant blocks. So, the snapshots of the two replicas are identical, but the volume-heads are mismatched.


For a **xfs** filesystem, the default data block size is 4096 bytes, but the superblock size is 512. The block size information can be checked by `xfs_info /dev/longhorn/<pvc-name>`.  Hence, the mismatch between the superblock size and Longhorn COW logic will cause the data corruption.


## Impact

- Longhorn volume using xfs filesystem: all versions
   - By deafult, the superblock size is 512.
- Longhorn volume using ext4 filesystem
  - Ext4 filesystem on a Longhorn volume created by Longhorn < v1.3.0's block size is mostly 4096 bytes, but it is set to 1024 bytes from v1.3.0. The value is heuristically determined by the filesystem size and the expected usage of the filesystem ([ref](https://linux.die.net/man/8/mkfs.ext4))
  

## Solution

- Fix Longhorn replica COW logic during rebuilding (https://github.com/longhorn/longhorn-engine/pull/745)

**Comment by derekbit** [comment] 2022-09-29 03:37
The issue is fixed and addressed in https://github.com/longhorn/longhorn/issues/4354 and https://github.com/longhorn/longhorn/issues/3895.

**Closed by derekbit** 2022-09-29 03:37 UTC
Labels: kind/bug, area/engine, severity/1, reproduce/rare, priority/0, require/automation-e2e, require/manual-test-plan, duplicated, backport-needed/1.3.2, area/data-integrity, backport-needed/1.2.6

**Comment by PhanLe1010** [comment] 2022-09-29 22:28
I think this issue is addressed in https://github.com/longhorn/longhorn/issues/4354 and https://github.com/longhorn/longhorn/issues/4594

**Comment by turowicz** [comment] 2024-10-30 11:09
This just happened for me on 1.5.3. How can I repair the volume?

**Comment by turowicz** [comment] 2025-04-14 07:57
Same on 1.7.3, help

**Comment by derekbit** [comment] 2025-04-14 09:00
@turowicz I don't think it is caused by the same issue. Could you create a new ticket and provide more information and support bundle for investigation?

**Comment by turowicz** [comment] 2025-04-14 11:10
That was a different stituation indeed - no node or pod restarts involved - it just broke. Unfortunately I have recovered from backup so I don't know how to create the support bundle that will give you the situation.

**Comment by derekbit** [comment] 2025-04-14 12:43
> That was a different stituation indeed - no node or pod restarts involved - it just broke. Unfortunately I have recovered from backup so I don't know how to create the support bundle that will give you the situation.

Thanks @turowicz. If it occurs again, please help collect the information and create a ticket. Many thanks.
