### ISSUE TITLE
[BUG] v2 volume workload pod failed mount with error: UNEXPECTED INCONSISTENCY

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9196] opened 2024-08-06 08:01 UTC
## Describe the bug

Trying to reproduce https://github.com/longhorn/longhorn/issues/9166 using longhorn-tests [PR #2048](https://github.com/longhorn/longhorn-tests/pull/2048). After a few replica rebuilding, the workload pod accidentally got stuck in `ContainerCreating` state:

https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1020/console

http://35.169.46.132:30000

```
# kubectl get pods
NAME                                    READY   STATUS              RESTARTS      AGE
longhorn-test-minio-7d8ddc774f-gh8r5    1/1     Running             0             31m
longhorn-test-nfs-5f96f8f5f8-xpqjs      1/1     Running             1 (30m ago)   31m
longhorn-test                           2/2     Running             0             29m
e2e-test-deployment-0-b5dd68559-qkfhz   0/1     ContainerCreating   0             22m
```

With error `UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY`:

```
# kubectl describe pod e2e-test-deployment-0-b5dd68559
-qkfhz
Name:             e2e-test-deployment-0-b5dd68559-qkfhz
Namespace:        default
Priority:         0
Service Account:  default
Node:             ip-10-0-1-17/10.0.1.17
Start Time:       Tue, 06 Aug 2024 07:31:19 +0000
Labels:           app=e2e-test-deployment-0
                  pod-template-hash=b5dd68559
                  test.longhorn.io=e2e
Annotations:      <none>
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    ReplicaSet/e2e-test-deployment-0-b5dd68559
Containers:
  sleep:
    Container ID:  
    Image:         busybox
    Image ID:      
    Port:          <none>
    Host Port:     <none>
    Args:
      /bin/sh
      -c
      while true;do date;sleep 5; done
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /data from pod-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-lzz8q (ro)
Conditions:
  Type                        Status
  PodReadyToStartContainers   False 
  Initialized                 True 
  Ready                       False 
  ContainersReady             False 
  PodScheduled                True 
Volumes:
  pod-data:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  e2e-test-claim-0
    ReadOnly:   false
  kube-api-access-lzz8q:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason                  Age   From                     Message
  ----     ------                  ----  ----                     -------
  Normal   Scheduled               23m   default-scheduler        Successfully assigned default/e2e-test-deployment-0-b5dd68559-qkfhz to ip-10-0-1-17
  Warning  FailedAttachVolume      22m   attachdetach-controller  Multi-Attach error for volume "pvc-c6f5e919-915f-4168-806b-ba939ff91cd8" Volume is already exclusively attached to one node and can't be attached to another
  Normal   SuccessfulAttachVolume  22m   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-c6f5e919-915f-4168-806b-ba939ff91cd8"
  Warning  FailedMount             22m   kubelet                  MountVolume.MountDevice failed for volume "pvc-c6f5e919-915f-4168-806b-ba939ff91cd8" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8 but could not correct them: fsck from util-linux 2.39.3
/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: Superblock has an invalid journal (inode 8).
CLEARED.
*** journal has been deleted ***

/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: Note: if several inode or block bitmap blocks or part
of the inode table require relocation, you may wish to try
running e2fsck with the '-b 32768' option first.  The problem
may lie only with the primary block group descriptors, and
the backup block group descriptors may be OK.

/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: Block bitmap for group 0 is not in group.  (block 6286859315928542553)


/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
           (i.e., without -a or -p options)
  Warning  FailedMount  6s (x18 over 22m)  kubelet  MountVolume.MountDevice failed for volume "pvc-c6f5e919-915f-4168-806b-ba939ff91cd8" : rpc error: code = Internal desc = 'fsck' found errors on device /dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8 but could not correct them: fsck from util-linux 2.39.3
/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: Note: if several inode or block bitmap blocks or part
of the inode table require relocation, you may wish to try
running e2fsck with the '-b 32768' option first.  The problem
may lie only with the primary block group descriptors, and
the backup block group descriptors may be OK.

/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: Block bitmap for group 0 is not in group.  (block 6286859315928542553)


/dev/longhorn/pvc-c6f5e919-915f-4168-806b-ba939ff91cd8: UNEXPECTED INCONSISTENCY; RUN fsck MANUALLY.
  (i.e., without -a or -p options)
```

## To Reproduce

Run test case `Degraded Volume Replica Rebuilding` repeatedly. 

## Support bundle for troubleshooting

[supportbundle_88975558-9c8c-4016-9e01-7830a67f18f4_2024-08-06T07-56-26Z.zip](https://github.com/user-attachments/files/16507233/supportbundle_88975558-9c8c-4016-9e01-7830a67f18f4_2024-08-06T07-56-26Z.zip)

## Environment

 - Longhorn version: v1.7.0-rc3
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version: sles 15-sp6
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment] 2024-08-06 09:02
The issue is a duplicate of https://github.com/longhorn/longhorn/issues/9166.

**Comment by yangchiu** [comment] 2024-08-06 09:32
> The issue is a duplicate of #9166.

If this issue is the same as https://github.com/longhorn/longhorn/issues/9166, why did the pod in this ticket get stuck in `FailedMount` while the pod in https://github.com/longhorn/longhorn/issues/9166 was able to run?

**Comment by derekbit** [comment] 2024-08-08 13:01
The root cause is same as https://github.com/longhorn/longhorn/issues/9166#issuecomment-2275299506.

cc @shuo-wu @DamiaSan @shuo-wu

**Comment by derekbit** [comment] 2024-08-09 08:55
## Pre Ready-For-Testing Checklist
* [ ] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:

* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at

[fix(engine): mark replica as ERROR if it is not found by derekbit · Pull Request #195 · longhorn/longhorn-spdk-engine (github.com)](https://github.com/longhorn/longhorn-spdk-engine/pull/195)

* [ ] Which areas/issues this PR might have potential impacts on?
Area: v2 volume, online rebuilding
Issues

**Comment by chriscchien** [comment] 2024-08-15 09:18
Close this ticket as 
- The same steps manually verified in https://github.com/longhorn/longhorn/issues/9166
- From logs in [pipeline](https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1020/console), the deployment pod not mount success, means the pod never running in the frist iteration
- From my local cluster with v1.7.x images, the test pod running and first iteration completed 
![image](https://github.com/user-attachments/assets/3ceff73e-589a-4037-ab67-7c2c1b0a6ce5)
- We may need to investigate the different between script generated cluster and manual created cluster, thank you.

**Closed by chriscchien** 2024-08-15 09:18 UTC
Labels: kind/bug, reproduce/often, priority/1, severity/2, area/v2-data-engine, area/resilience, area/volume-replica-rebuild, require/backport
