### ISSUE TITLE
[BUG] Volume unable to recover when upgrading several StatefulSets

### ISSUE THREAD

**Issue by MikaelSmith** [longhorn/longhorn#2329] opened 2021-03-11 21:30 UTC
A volume is stuck with Unknown health, and several can't be mounted because they're already attached. This probably happened after restarting the Longhorn manager instances.

> Warning  FailedAttachVolume  3m22s (x36 over 60m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ef1550da-b248-4b74-995f-4af189bfcfaa" : rpc error: code = Aborted desc = The volume pvc-ef1550da-b248-4b74-995f-4af189bfcfaa is already attached but it is not ready for workloads

and

> Warning  FailedAttachVolume  3m5s (x36 over 60m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-1a16cfdb-6b14-472a-a104-c8a654da0102" : rpc error: code = FailedPrecondition desc = The volume pvc-1a16cfdb-6b14-472a-a104-c8a654da0102 cannot be attached to the node connect-b since it is already attached to the node connect-a

<img width="1506" alt="Screen Shot 2021-03-11 at 1 28 43 PM" src="https://user-images.githubusercontent.com/8162496/110857435-b4b8fb00-826d-11eb-82e8-b5f29e4e2a51.png">

I'm surprised they aren't automatically fixed based on https://longhorn.io/docs/1.1.0/high-availability/recover-volume/.

---
Version: `v1.1.0`

Support bundle attached: 
[longhorn-support-bundle_ee48a964-d6ec-4141-af7a-84f62c5cea44_2021-03-11T21-31-07Z.zip](https://github.com/longhorn/longhorn/files/6126099/longhorn-support-bundle_ee48a964-d6ec-4141-af7a-84f62c5cea44_2021-03-11T21-31-07Z.zip)

**Comment by ElisaMeng** [comment] 2021-03-11 23:02
might be relative to #2322?

**Comment by MikaelSmith** [comment] 2021-03-11 23:22
My current theory is that restarting the Longhorn managers with volumes still attached left them attached to a specific node and never attempted to stop > detach > start the pods that couldn't mount volumes. I'm not sure what happened with the failed replicas though.

**Comment by shuo-wu** [comment] 2021-03-12 05:26
For volume `pvc-ef1550da-b248-4b74-995f-4af189bfcfaa-e-b5bb8817`
Root cause:
1. All replicas are state `error` but the engine is still state `running`. Ideally, the engine should error out and the volume should become `Faulted`, then auto salvage will help recover the volume. But the field `spec.failedAt` in replica `pvc-ef1550da-b248-4b74-995f-4af189bfcfaa-r-73cbddfa`  is empty, which doesn't match its state `error`. This replica blocks the flow. 
2. This problematic replica is the only replica in engine `currentreplicaaddressmap`: `pvc-ef1550da-b248-4b74-995f-4af189bfcfaa-r-73cbddfa: 10.32.0.8:10015`. But somehow there is no record in engine `replicamodemap`. Based on the implementation, Longhorn will rely on the record in `replicamodemap` to set `spec.failedAt` for the replica. Actually the replica is still in the engine process with mode `ERR`
```
2021-03-11T20:39:05.585916097Z [pvc-ef1550da-b248-4b74-995f-4af189bfcfaa-e-b5bb8817] time="2021-03-11T20:39:05Z" level=error msg="Backend tcp://10.32.0.8:10015 monitoring failed, mark as ERR: EOF"
2021-03-11T20:39:05.585938846Z time="2021-03-11T20:39:05Z" level=info msg="Set replica tcp://10.32.0.8:10015 to mode ERR"
2021-03-11T20:39:05.585946696Z time="2021-03-11T20:39:05Z" level=info msg="Monitoring stopped tcp://10.32.0.8:10015"
```
3. According to the following logs, there is another longhorn manager somehow takes over the engine from the node that the engine supposed to be on. Then the current node `connect-a` stops monitoring the engine and cleans up `replicamodemap`, `endpoint`, as well as some other fields. 
```
2021-03-11T20:18:36.934454632Z time="2021-03-11T20:18:36Z" level=debug msg="Requeue volume due to error <nil> or Operation cannot be fulfilled on replicas.longhorn.io \"pvc-ef1550da-b248-4b74-995f-4af189bfcfaa-r-b46ed366\": the object has been modified; please apply your changes to the latest version and try again" accessMode=rwo controller=longhorn-volume frontend=blockdev node=connect-a owner=connect-a state=attached volume=pvc-ef1550da-b248-4b74-995f-4af189bfcfaa
2021-03-11T20:18:37.134330941Z time="2021-03-11T20:18:37Z" level=info msg="stop monitoring because the engine is no longer running on node" controller=longhorn-engine engine=pvc-ef1550da-b248-4b74-995f-4af189bfcfaa-e-b5bb8817 node=connect-a
```
4. Actually node `connect-a` gets the engine back later. But the engine controller on this node didn't restart the monitoring. This is a longhorn **bug**: When the current engine controller [stops the monitoring due to the owner ID](https://github.com/longhorn/longhorn-manager/blob/278ff44085b967923d6f07dfb43a95a7b2974470/controller/engine_controller.go#L671-L676), [the engine monitor map](https://github.com/longhorn/longhorn-manager/blob/278ff44085b967923d6f07dfb43a95a7b2974470/controller/engine_controller.go#L603) is not cleaned up. When the engine is back later, the engine controller will wrongly consider that [it's still monitoring the engine](https://github.com/longhorn/longhorn-manager/blob/278ff44085b967923d6f07dfb43a95a7b2974470/controller/engine_controller.go#L304).

**Comment by shuo-wu** [comment] 2021-03-12 06:01
For volume `pvc-1a16cfdb-6b14-472a-a104-c8a654da0102`

Workaround:
Manually detach the volume (via Longhorn UI) and clean up the related VolumeAttachment `csi-569be94630dc21616bb66ba5383a0930da5a6d0537f29457642d021d9a4cf5b0`:
```
kubectl delete volumeattachment csi-569be94630dc21616bb66ba5383a0930da5a6d0537f29457642d021d9a4cf5b0` and kubectl patch -p '{"metadata":{"finalizers": null}}' volumeattachment csi-569be94630dc21616bb66ba5383a0930da5a6d0537f29457642d021d9a4cf5b0
```
Then wait for Kubernetes retries the attachment for the workload.

Root cause:
When the volume is crashed then becomes detached (the crash seems to be caused by the instance manager pod crash), Kubernetes sends a CSI detach request to the CSI plugin. At that time, though `spec.nodeID` is not empty, the volume is temporarily become `detached` then the plugin will wrongly response that the detachment success. As a result, Kubernetes considers this volume as ready to be attached to another node.
This is also a Longhorn bug. And I had encountered and reported this bug before. But I cannot find the issue number.

**Comment by PhanLe1010** [comment] 2021-03-12 07:07
I think the issue https://github.com/longhorn/longhorn/issues/1631#issuecomment-664768769 is related to the problem with the second volume (volume pvc-1a16cfdb-6b14-472a-a104-c8a654da0102)

**Comment by MikaelSmith** [comment] 2021-03-12 07:21
I was able to recover all volumes by: stopping the pods attempting to use them, detaching the volumes in the UI, then starting the pods.

Ideally this would be done automatically.

**Comment by shuo-wu** [comment] 2021-03-12 08:36
> I think the issue [#1631 (comment)](https://github.com/longhorn/longhorn/issues/1631#issuecomment-664768769) is related to the problem with the second volume (volume pvc-1a16cfdb-6b14-472a-a104-c8a654da0102)

Oh, that's the PDB issue. Since this case is not caused by node drain, PDB won't help here. We need to find another way to fix it.

**Comment by shuo-wu** [comment] 2021-03-12 08:37
> I was able to recover all volumes by: stopping the pods attempting to use them, detaching the volumes in the UI, then starting the pods.
> 
> Ideally this would be done automatically.

Yes. After fixing these bugs, volumes would be recovered automatically. Thank you for reporting!

**Comment by MikaelSmith** [comment] 2021-03-12 17:24
Ah, sorry this didn't follow the bug format. It seems selecting Open Issue from the Longhorn UI skips that selection.

**Comment by MikaelSmith** [comment] 2021-03-12 20:59
Had another instance of this while making no changes to the system. All 3 replicas were detected to be in error (I'm not sure what triggered this, can try to track it down if you have some pointers what to look for in logs), Longhorn attempted to auto-salvage and thought it got it to a healthy state, then
```
  Warning  FailedAttachVolume  32s (x6 over 9m44s)    attachdetach-controller  AttachVolume.Attach failed for volume "pvc-4b5d462e-ac7c-41f8-9d69-5029ca2cd060" : rpc error: code = FailedPrecondition desc = The volume pvc-4b5d462e-ac7c-41f8-9d69-5029ca2cd060 cannot be attached to the node connect-a since it is already attached to the node connect-b
```

Scaling the pod down didn't automatically detach the pod. After manually detaching, then starting the pod, it came back up successfully; it did have a timeout for some reason
```
  Normal   SuccessfulAttachVolume  3m8s   attachdetach-controller  AttachVolume.Attach succeeded for volume "pvc-4b5d462e-ac7c-41f8-9d69-5029ca2cd060"
  Warning  FailedMount             75s    kubelet                  Unable to attach or mount volumes: unmounted volumes=[data], unattached volumes=[data backup run tmp]: timed out waiting for the condition
  ...
  Normal   Started                 60s    kubelet                  Started container query-postgres
```

**Comment by wpwoodjr** [comment] 2021-03-14 17:03
We are seeing similar issues as reported here: [Longhorn volume doesn't re-attach to pod](https://support.rancher.com/hc/en-us/requests/15114)

One thing I noticed, if instance manager restarts, Longhorn also restarts pods associated with it.  Pods which move to another instance manager are fine, but pods which go to the new one can fail to re-attach.  

We are seeing failures with volumes that have 2 replicas and no data locality, and with volumes that have 1 replica and "best effort" data locality.

The support link above has more detail.

**Comment by PhanLe1010** [comment] 2021-03-25 21:30
> Actually node connect-a gets the engine back later. But the engine controller on this node didn't restart the monitoring. This is a longhorn bug: When the current engine controller stops the monitoring with this function(due to the owner ID), the engine monitor map is not cleaned up. When the engine is back later, the engine controller will wrongly consider that it's still monitoring the engine.

I will fix this bug as part of refactoring the ownership handling logic https://github.com/longhorn/longhorn/issues/2377

**Comment by bmalynovytch** [comment] 2021-04-01 12:57
I you need to release many volumes at once, the following script may help:

```
#!/bin/bash

API=http://longhorn-frontend.longhorn-system.svc.cluster.local

kubectl get pods -A | grep Init: | while read NS POD _ ; do
  PVC=$(kubectl describe pod -n "$NS" "$POD" | grep attachdetach-controller | egrep "Multi-Attach|it is already attached" | grep -Po 'pvc-[a-z0-9-]+' | tail -n1)
  [ -z "$PVC" ] && continue

  (
    echo "Deleting attachment for $PVC, required by $NS/$POD"
    kubectl delete pod -n "$NS" "$POD"
    curl -sX POST -o /dev/null "$API/v1/volumes/$PVC?action=detach"

    ATTACHMENT=$(kubectl get volumeattachment | grep "$PVC" | awk '{print $1}')
    [ -n "$ATTACHMENT" ] && kubectl delete volumeattachment "$ATTACHMENT"
  )

done
echo "Cleanup done, waiting for API to return..."
```

If you wish to speed up the process (and stress your cluster), you may fork the "Deleting attachment" section.

**Comment by joshimoo** [comment] 2021-04-01 19:52
Reproduce steps:
- create volume + pod with single replica + data locality
- turn off node

Problem 01: kubernetes + longhorn out of sync
- before csi changes, kubernetes and longhorn would go out of sync and kubernetes could no longer attach the volume since it's still desired to be attached to the prior node v.spec.NodeID is not unset.

Problem 02: salvage deadloop preventing volume updates
- after csi changes or let's say you manually unset the v.spec.NodeID via a detach from the UI or manual salvage of the replica while it's still on the downed node (manual salvage will first unset v.spec.nodeID) and then process the replicas (this operation will fail since the replica is down)
- the volume will now constantly fail to update since the isNodeDownCheck(v.spec.NodeID) https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L1033 will always return error

Problem 03: monitoring / ownership issue, @PhanLe1010 is working on this in https://github.com/longhorn/longhorn-manager/pull/854

Test Setup:
This fixes issues with salvage of multiple replicas as well, it's just easier to test with a single replica case.
- This should be tested with data locality enabled/disabled.
- This should be tested with replicaset / statefulset
- This should be tested with RWO/RWX volumes

Test steps:
- create RWO|RWX volume with replica count = 1 & data locality = enabled|disabled
- create deployment|statefulset for volume
- power down node of volume/replica
- wait for pod deletion & recreation
- volume will fail to attach since volume is not ready (i.e remains faulted, since single replica is on downed node)
- power up node
- verify auto salvage finishes (i.e pod completes start)
- verify volume attached & accessible by pod (i.e test data is available)

**Comment by khushboo-rancher** [comment] 2021-04-05 08:47
@joshimoo Is this good to test as I see https://github.com/longhorn/longhorn-manager/pull/854 is not merged ?

**Comment by khushboo-rancher** [comment] 2021-04-06 20:50
Verified with Longhorn Master `04/07/2021`

The scenario of statefulSet with 1 replica and data locality enabled is working fine with Longhorn master but I also couldn't repro the problem with this scenario with Longhorn v1.1.0.

I'm validation other scenarios, will update the results.

**Comment by joshimoo** [comment] 2021-04-12 10:12
@PhanLe1010 can you check this part `pods with RWO were able to move to another node and got attached to volume but RWX remains on the same node with unavailable status.` i.e. in regard to the ownership changes/pod creation of the share-manager.

**Comment by meldafrawi** [comment] 2021-04-16 19:04
Closing, will track integration test implementation in a separate issue https://github.com/longhorn/longhorn/issues/2481

**Closed by meldafrawi** 2021-04-16 19:04 UTC
Labels: area/manager, kind/bug, priority/1, require/automation-e2e, require/manual-test-plan
