### ISSUE TITLE
[BUG] Ready for workload incorrectly marked Ready when the volume fails because of "Replica Scheduling Failure"

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1360] opened 2020-05-18 21:16 UTC
**Describe the bug**
Ready for workload incorrectly marked Ready when the volume fails because of "Replica Scheduling Failure"

**To Reproduce**

- Number of worker nodes - 4
- Cordon a worker node. Node is marked "Unschedulable"
- Deploy a volume with 4 replicas in Longhorn
- Volume is in detached state with `Scheduling Failure Replica Scheduling Failure` and `Ready for workload:Ready`

**Expected behavior**
`Ready for workload` in this case should be `No`

**Environment:**
 - Longhorn version: master, ui tag: `wangsiye/longhorn-ui:941d022`

**Comment by shuo-wu** [comment] 2020-05-21 03:50
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by sowmyav27** [comment] 2020-05-22 17:20
**Verified on master - 05/22/2020**

**Steps:**

- Number of worker nodes - 4
- Cordon a worker node. Node is marked "Unschedulable"
- Deploy a volume with 4 replicas in Longhorn
- Volume is in detached state with `Scheduling Failure Replica Scheduling Failure` and `Ready for workload: Not Ready`
<img width="642" alt="Screen Shot 2020-05-22 at 10 19 47 AM" src="https://user-images.githubusercontent.com/26032343/82693170-df21c500-9c15-11ea-95bc-dbbb5f67650e.png">

**Closed** 2020-05-28 21:44 UTC
Labels: area/manager, bug, priority/3, require/automation-e2e

**Comment by koo9** [comment] 2020-12-25 22:17
got the same error message but the volume is ready and working in kubernetes. any update on this?

**Comment by shuo-wu** [comment] 2020-12-28 06:15
@koo9 I think it's due to the new enhancement/setting introduced in v1.1.0: [`Allow volume creation with degraded availability`](https://github.com/longhorn/longhorn/issues/1701). 
The error `Replica Scheduling Failure` means there is no available disk/node that can fit the volume. And the expected HA(running replica count) cannot be guaranteed. In old versions, because of the HA downgrade concerns, the attachment will be disabled once a volume is created with this error. Due to lots of users being blocked by [the related error](https://longhorn.io/kb/troubleshooting-volume-pvc-xxx-not-scheduled/), we decide to introduce the new setting and remove the restriction.

**Comment by koo9** [comment] 2020-12-30 04:02
@shuo-wu  that works! thx
