### ISSUE TITLE
[BUG]Longhorn doesn't work on K3S + CentOS + SELinux

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1273] opened 2020-04-29 10:08 UTC
**Describe the bug**
The engine-image pods have no permission to access the mounted volumes, then the engine image cannot become state `ready`.

**To Reproduce**
1. Deploy K3S with CentOS nodes
2. Deploy the latest longhorn. The engine-image pod will get stuck in `CrashLoopBackOff` status.

**Expected behavior**
Longhorn should work fine.

**Log**
```
[root@ip-172-31-10-68 ~]# k -n longhorn-system logs engine-image-ei-62c02f63-kndkx
cp: cannot create regular file '/data/longhorn': Permission denied
```

**Environment:**
 - Longhorn version: v0.8.1
 - Kubernetes version: v1.17.5-rc2+k3s1
 - Node OS type and version: CentOS Linux release 7.7.1908 (Core)

**Additional context**
1. This issue is more like a docker issue rather than a Longhorn bug. Not sure if we need to track it here. Directly deploying a pod using host volumes can also reproduce this issue.
2. Setting `privileged` security context may help fix this issue. But users have no way to set it for engine image pods since the related DaemonSet is dynamically deployed by longhorn manager.
3. There is a similar issue here: https://stackoverflow.com/questions/24288616/permission-denied-on-accessing-host-directory-in-docker

**Comment by shuo-wu** [comment] 2020-04-29 10:11
@ShylajaDevadiga

Can you provide the steps to deploy the k3s for this issue?

**Comment by erikwilson** [comment] 2020-04-30 16:55
This is probably an issue where selinux is properly enforcing the types and permissions on the host path. 

k3s does not use docker by default, it uses containerd with selinux support. To verify it is not an issue with recent containerd changes the install should be compared to k3s using docker with selinux enabled.

If there is no difference with k3s using docker w/selinux or containerd I think the correct solution is that an admin should relabel the directory with the correct type, but it could be that longhorn can have an option to relabel for us.

**Comment by ShylajaDevadiga** [comment] 2020-05-01 00:14
@shuo-wu To install k3s
```
curl -fL https://get.k3s.io | INSTALL_K3S_VERSION=v1.17.5-rc2+k3s1 sh -s -
```

**Comment by ryandharper** [comment] 2020-05-12 20:57
Can confirm same issue on Fedora 32 today. 

`k3s version v1.17.4+k3s1 (3eee8ac3)`
kubectl version
```
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.4+k3s1", GitCommit:"3eee8ac3a1cf0a216c8a660571329d4bda3bdf77", GitTreeState:"clean", BuildDate:"2020-03-25T16:13:25Z", GoVersion:"go1.13.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by ttpcodes** [comment] 2020-06-02 23:03
Did some investigating, and this is what I've been able to find out:
- `Longhorn` attempts to install the `Engine Image` to `/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-${ENGINE_VERSION}`, which appears to be under the `SELinux` context of `system_u:object_r:container_var_lib_t:s0`. The container runs as `container_t`, which doesn't seem to have write access on `container_var_lib_t` based on [this comment](https://github.com/containers/libpod/issues/1782#issuecomment-437662997) under containers/libpod#1782.
- `Docker` without `SELinux` support installs the `Engine Image` just fine, but fails with the same permission error if `SELinux` support is enabled (I installed `k3s` with this command to use `Docker`: `curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="server --docker" sh -`)
- Based on kubernetes/kubernetes#27282, it doesn't look like we can just use `Kubernetes` to relabel the directory for us.

The proper way seems to be as Erik mentioned, which is to have an admin relabel the directory (with perhaps some documentation or a script for them to use/reference during Longhorn installation). The `Engine Image Pod` will also be able to access the directory successfully if run as `Privileged`, though that probably is unappealing to an admin who's interested in running with `SELinux` to begin with.

**Comment by yasker** [comment] 2020-06-02 23:48
@ttpcodes 

We currently have `longhorn-manager`, `instance-manager`, and `cronjob` pods running as `privileged`. So I am fine with running `engine-image` daemonset as `privileged` as well, given Longhorn is system software.

If https://github.com/kubernetes/kubernetes/issues/27282 can be resolved in the future, we can use Kubernetes to correctly label the volumes. But we cannot wait for that fix at the moment.

**Comment by ttpcodes** [comment] 2020-06-03 18:45
Manual test steps:
1. Set up a node with `CentOS` and make sure that the output of `sestatus` indicates that `SELinux` is enabled and set to `Enforcing`.
2. Run the `k3s` installation script.
3. Install `Longhorn`.
4. The system should come up successfully. The logs of the `Engine Image` pod should only say `installed`, and the system should be able to deploy a `Volume` successfully from the UI.

Note: I ran into some problems with running `k3s` on `CentOS`, presumably due to the `firewalld` rules. This seems to be reported in rancher/k3s#977. I ended up disabling `firewalld` with `systemctl stop firewalld` in order to get `k3s` working.

**Comment by ttpcodes** [comment] 2020-06-03 22:25
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [X] Is the backend code merged?
The PR is at longhorn/longhorn-manager#597.

* [X] Is the reproduce steps/test steps documented?

* [ ] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [ ] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [ ] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [ ] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?~~

* [X] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by khushboo-rancher** [comment] 2020-06-12 00:14
Verified on k3s cluster on Centos with SELinux enabled with Master build - 06-11-2020, it is working. Longhorn can be deployed successfully on this setup.

Verification - **Passed**

1. Set up k3s cluster on Centos 7.
```
# cat /etc/os-release 
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Max kernel policy version:      31
```
2. Installed longhorn.
3. Engine image came up healthy.
4. Verified the P1 worklows.

**Closed by khushboo-rancher** 2020-06-12 00:14 UTC
Labels: area/kubernetes, bug, priority/2, reproduce/always, require/manual-test-plan
