### ISSUE TITLE
[BUG] User is not able to delete a corrupted volume backup on Longhorn UI

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1213] opened 2020-04-16 20:45 UTC
**Describe the bug**
User is not able to delete a corrupted volume backup on Longhorn UI

**To Reproduce**

- Create a volume v1 in longhorn, attach to. a pod
- Create a backup of the volume v1.
- In S3, change the name of config `volume.cfg` to `volume.cfg.tmp`
- Navigate to backup page on Longhorn UI
- Delete v1 -- delete all backups
- Error message is seen on the UI

`error deleting backup volume v2: error deleting backup volume: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup rm --volume v2 s3://<S3>/], output Volume v2 doesn't exist in backupstore , stderr, time="2020-04-16T20:44:08Z" level=error msg="{\n ContentType: \"application/xml\"\n}" pkg=s3 time="2020-04-16T20:44:08Z" level=error msg="Volume v2 doesn't exist in backupstore" , error exit status 1`

**Expected behavior**
User should be able to delete the backup which is corrupted from Longhorn

**Environment:**
 - Longhorn version: master - 04/17/2020
 - Kubernetes version: 1.17.4
 - Node OS type and version: Linus DO. rke

**Comment by sowmyav27** [comment] 2020-05-12 03:54
Another use case:

- In S3, edit a backup b1 file - make it an invalid json data - (removed "}}" from the file in the end)
- Save the file and upload it back to S3.
- Go to Backup --> Backup list page
- The backup b1 will not be listed in the backup list page. 
<img width="1639" alt="Screen Shot 2020-05-11 at 8 30 21 PM" src="https://user-images.githubusercontent.com/26032343/81636791-96723c80-93c9-11ea-9ad6-8722ff318d4f.png">

- Delete this backup
- When the user tried to delete the backup, the backupDelete response gives a 200 status. But the logs in the longhorn-manager throw error: time="2020-05-12T03:32:21Z" level=error msg="error deleting backup s3://<>/?backup=backup-6810f998b8904b6e&volume=v2: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup rm s3://<>/?backup=backup-6810f998b8904b6e&volume=v2], output unexpected EOF\n, stderr, time=\"2020-05-12T03:32:21Z\" level=error msg=\"unexpected EOF\"\n, error exit status 1"

**Comment by joshimoo** [comment] 2020-06-02 00:42
This requires the implementation of orphaned block deletion. longhorn/longhorn#1435
Afterwards we can remove the backup file even if we cannot load the backup file.

**Comment by joshimoo** [comment] 2020-06-02 04:14
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at 

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by joshimoo** [comment] 2020-06-02 04:25
This issues contains 2 different issues, the delete all backups is caused by a check for the existence of volume.cfg. Which should be easily removable since there is no dependency on the content of volume.cfg for the volume delete operation.

The other issue is corrupted backup.cfg, which get fixed in [41](https://github.com/longhorn/backupstore/pull/41)

**Comment by meldafrawi** [comment] 2020-06-12 14:28
Validation: **PASSED**

- Create a volume v1 in longhorn, attach to. a pod
- Create a backup of the volume v1.
- In S3, change the name of config volume.cfg to volume.cfg.tmp
- Navigate to backup page on Longhorn UI, backup volume should be displayed with warning.
![image](https://user-images.githubusercontent.com/18232258/84512117-cada6080-acc7-11ea-87fe-967c95b821fc.png)
- Delete v1 -- delete all backups, backups should be deleted.  (**PASSED**)
- Create 2 more backups b1 & b2
- In S3, edit a backup b1 file - make it an invalid json data - (removed "}}" from the file in the end)
- Save the file and upload it back to S3.
- Go to Backup --> Backup list page
- The backup b1 will  be listed in the backup list page, with warning  (**PASSED**)
![image](https://user-images.githubusercontent.com/18232258/84513227-72a45e00-acc9-11ea-8941-812658c5a624.png)
- User can't restore backup from b1  (**PASSED**)
- User can restore backup from b2  (**PASSED**)

**Closed** 2020-07-09 16:33 UTC
Labels: area/engine, area/manager, bug, require/automation-e2e, require/automation-engine
