### ISSUE TITLE
[BUG] Unused Replicas Are not Correctly Removed from Running Pods

### ISSUE THREAD

**Issue by NickyBoy89** [longhorn/longhorn#1662] opened 2020-08-04 07:28 UTC
**Describe the bug**

Data from a past longhorn install is not correctly removed from the cluster, causing the leftover replicas on the nodes to still have activity

I discovered this after accidentally wiping my Longhorn configuration, and trying to mount the block devices that the disaster recovery guide on the website instructed me to do

**To Reproduce**

**NOTE** the PVC pvc-1234 is solely for example purposes and being a much shorter name

1. Install Longhorn with the default values
1. Create a few Persistent Volumes on the cluster
1. `kubectl remove ns longhorn-system` and remove finalizers from all the resources with the `kubectl patch` command
1. Mount one of the replicas with the recovery methods on the website at [this page](https://longhorn.io/docs/1.0.1/advanced-resources/data-recovery/export-from-replica/) and run `lsof` on the created block device (ex: at `/dev/longhorn/pvc-1234`)
1. Observe the errors that `lsof` puts out

```
lsof: WARNING: can't stat() overlay file system /var/lib/docker/overlay2/80a13652a6a2964bab992b762116d0e2c742815a46032d88dd161444811bc8f6/merged
      Output information may be incomplete.
lsof: WARNING: can't stat() nsfs file system /run/docker/netns/c530302040bd
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /var/lib/kubelet/pods/3ef09e47-c153-4d14-87ad-a58c70118ba3/volumes/kubernetes.io~secret/default-token-966r5
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /var/lib/kubelet/pods/c88aad57-7477-400c-982a-4256ed135953/volumes/kubernetes.io~secret/node-exporter-token-79twk
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /var/lib/kubelet/pods/8e60cbf0-9bd9-4856-8df8-ac1abd2f04cd/volumes/kubernetes.io~secret/longhorn-service-account-token-cgxm5
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /var/lib/kubelet/pods/83483b2b-52c8-4164-8b75-89050a381bca/volumes/kubernetes.io~secret/longhorn-service-account-token-cgxm5
      Output information may be incomplete.
lsof: WARNING: can't stat() tmpfs file system /var/lib/kubelet/pods/0754ef60-f698-4ac4-9ce3-af14ed698fff/volumes/kubernetes.io~secret/longhorn-service-account-token-cgxm5
      Output information may be incomplete.
``` 
1. The command `mount /dev/longhorn/pvc-1234 /mnt/pvc-1234` returns the error `mount: <mountpoint>: /dev/longhorn/pvc-1234 already mounted or mount point busy.`

**Expected behavior**

When mounting the block device created from a replica with the `mount` command, it should be able to be mounted on the filesystem, and not display `mount: <mountpoint>: /dev/longhorn/pvc-1234 already mounted or mount point busy.`

**Log**

**Environment:**

Longhorn `v1.0.1`
All Nodes Running `Ubuntu server 20.04` and `v1.18.4+k3s1` on `x86_64`

**Additional context**

This situation happened due to an unexpected power loss to my main storage node

**Comment by yasker** [comment] 2020-10-04 02:47
Duplicate of #685

**Comment by yasker** [comment] 2020-10-04 02:49
I am a bit confused here. Where do you see `mount: <mountpoint>: /dev/longhorn/pvc-1234 already mounted or mount point busy` ? It's not in the reproduce steps.

**Comment by NickyBoy89** [comment] 2020-10-04 15:48
@yasker I just updated the reproduce steps, but that error occurred when I tried to mount the longhorn block device to a location on the filesystem to move the files out.

It occurs when trying to `mount /dev/longhorn/pvc-1234 /mnt/pvc-1234`, or to some other location

**Comment by yasker** [comment] 2020-10-09 21:33
@NickyBoy89 It sounds like the multipath issue https://github.com/longhorn/longhorn/issues/1210

In short, there might be some processes on the node claimed new block device created by Longhorn automatically before you can mount it, e.g. multipath process.

You can check it using `lsof` to find who is using `/dev/longhorn/pvc-1234` and the other name of the device (likely `/dev/sdxxx`, check the comment starting from https://github.com/longhorn/longhorn/issues/1210#issuecomment-615390844 )

**Comment by NickyBoy89** [comment] 2020-10-09 23:29
@yasker Something of that magnitude definitely seems to be the issue

From the `lsof` command that I ran initially, it seemed like the Docker process itself was using the devices. I killed the docker process, and these errors went away, although then I couldn't use docker-compose to mount the images.

```
lsof: WARNING: can't stat() overlay file system /var/lib/docker/overlay2/80a13652a6a2964bab992b762116d0e2c742815a46032d88dd161444811bc8f6/merged
      Output information may be incomplete.
lsof: WARNING: can't stat() nsfs file system /run/docker/netns/c530302040bd
      Output information may be incomplete.
```

Although, I don't have a reason why docker would be using these devices, thank you for coming up with a reason though!

**Closed** 2020-12-16 08:57 UTC
Labels: wontfix
