### ISSUE TITLE
[Question] support for CustomResourceDefinition in kuberntes 1.19.2

### ISSUE THREAD

**Issue by arturmon** [longhorn/longhorn#1813] opened 2020-09-23 14:11 UTC
Good day. updated kubernetes to 1.19.2 and got an error:  
```
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "engines.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "replicas.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "settings.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "volumes.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "engineimages.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "nodes.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
Error from server (Invalid): error when creating "longhorn.yaml": CustomResourceDefinition.apiextensions.k8s.io "instancemanagers.longhorn.io" is invalid: spec.versions[0].schema.openAPIV3Schema: Required value: schemas are required
```
after tweaking CustomResourceDefinition.
```
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: Engine
  name: engines.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: Engine
    listKind: EngineList
    plural: engines
    shortNames:
    - lhe
    singular: engine
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: Replica
  name: replicas.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: Replica
    listKind: ReplicaList
    plural: replicas
    shortNames:
    - lhr
    singular: replica
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: Setting
  name: settings.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: Setting
    listKind: SettingList
    plural: settings
    shortNames:
    - lhs
    singular: setting
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: Volume
  name: volumes.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: Volume
    listKind: VolumeList
    plural: volumes
    shortNames:
    - lhv
    singular: volume
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: EngineImage
  name: engineimages.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: EngineImage
    listKind: EngineImageList
    plural: engineimages
    shortNames:
    - lhei
    singular: engineimage
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: Node
  name: nodes.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: Node
    listKind: NodeList
    plural: nodes
    shortNames:
    - lhn
    singular: node
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  labels:
    longhorn-manager: InstanceManager
  name: instancemanagers.longhorn.io
spec:
  group: longhorn.io
  names:
    kind: InstanceManager
    listKind: InstanceManagerList
    plural: instancemanagers
    shortNames:
    - lhim
    singular: instancemanager
  scope: Namespaced
  versions:
    - name: v1beta1
      served: true
      storage: true

```
Maybe you already have support for the new version of Kubernetes?

**Comment by yasker** [comment] 2020-09-23 21:40
@meldafrawi Can you test on v1.19.2 to see if we have any issues with the deployment?

**Comment by yasker** [comment] 2020-09-23 23:22
@arturmon Ok, after looking into it, I found it's due to you have changed the API group of Longhorn CRDs from `apiextensions.k8s.io/v1beta1` to `apiextensions.k8s.io/v1`. We haven't made that change yet and will do it soon. I think you've updated the CRDs due to the deprecation warning?

**Comment by arturmon** [comment] 2020-09-24 08:06
Good afternoon. we updated kubernetes to 1.19.2 and ran into a problem during deployment, after that we changed some fields (crd, ingress) here is the full deployment file. Tell me, is there a solution to this problem without waiting for version v1.1.0?
[longhorn.txt](https://github.com/longhorn/longhorn/files/5274402/longhorn.txt)

**Comment by meldafrawi** [comment] 2020-09-24 16:23
@yasker 

Couldn't reproduce the issue.

**Steps to test:**
1. Install k3s v1.18.8+k3s1
2. Install Longhorn v1.0.2
3. Create volumes attached to nodes, and other volumes consumed by pods
4. Write random data to volumes, and compute it's checksum.
5. Upgrade k3s to v1.19.2+k3s1
6. Check data checksum
7. Detach and attach the volumes, and compute data checksum
8. Write more data to volumes and verify data can be Read/Write
9. Create new volumes on the upgraded cluster

Volumes, are healthy, and usable in all situations

**Comment by yasker** [comment] 2020-09-24 16:28
@arturmon Hi, I am not sure what issue caused you to change the deployment yaml here. It seems the original Longhorn deployment yaml works fine with v1.19.2 in our test. We won't able to support modified deployment method. Can you tell me more about the problem you had during the deployment?

**Comment by arturmon** [comment] 2020-09-25 12:11
> @arturmon Hi, I am not sure what issue caused you to change the deployment yaml here. It seems the original Longhorn deployment yaml works fine with v1.19.2 in our test. We are not able to support modified deployment method. Can you tell me more about the problem you had during the deployment?

Good afternoon.
This problem appeared after I decided to get rid of warnings. I decided to replace all outdated api with new ones. For example, the new ingress was fixed without problems. The problem arose precisely with the CR, since the new api require to describe openAPIV3Schema.

**Comment by yasker** [comment] 2020-09-25 18:53
@arturmon The old API group is not 100% compatible with the new API group, which caused problems if you decide to modify them manually. We will update our API groups to the latest for the upcoming v1.1.0 and v1.0.3 release.

**Comment by yasker** [comment] 2020-09-28 22:11
Note: we do need to check for all of our API groups for every release cycle, make sure we're properly migrate to the new APIs.

**Comment by PhanLe1010** [comment] 2020-10-31 08:08
**Reproduce Steps:**
Install Longhorn v1.0.2 by:
```
kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v1.0.2/deploy/longhorn.yaml
```
See the warning: 
```
Warning: apiextensions.k8s.io/v1beta1 CustomResourceDefinition is deprecated in v1.16+, unavailable in v1.22+; use apiextensions.k8s.io/v1 CustomResourceDefinition
```

**Comment by PhanLe1010** [comment] 2020-10-31 08:22
### Tests Steps:
**Note:** It is very important that we make sure this PR contains no bug. Even a small mistake in this PR will likely corrupt user's data because we are modifying the Longhorn CRDs. I have tested this PR extensively. However, it still needs QA to verify carefully.

**Case -1: Upgrading from old versions**
1. Install Longhorn <= v1.0.2
1. Deploy workloads that use Longhorn volumes
1. Manually create volumes and attach to nodes
1. Upgrade Longhorn to master
1. Verify that all workloads still be able to access volumes. The data in volumes are not corrupted.
1. Verify that backup and restore work ok

**Case -2: New Installation**
1. Install Longhorn master
1. Deploy workloads that use Longhorn volumes
1. Manually create volumes and attach to nodes
1. Verify that all workloads are able to access volumes. The data in volumes are not corrupted.
1. Verify that backup and restore work ok

We need to repeat the above 2 cases for Kubernetes v1.16, v.17, v1.18, and v.19

**Comment by PhanLe1010** [comment] 2020-10-31 08:28
Beside of upgrading Longhorn CRDs, we should also update Longhorn's Kubernetes dependencies ((client-go, Kubernetes, metric-client, etc..) to  v.1.16+. This is tracked at https://github.com/longhorn/longhorn/issues/1938

**Comment by khushboo-rancher** [comment] 2020-11-06 22:29
The longhorn chart should also be updated. Moving to implementation.

**Comment by yasker** [comment] 2020-11-10 17:11
@shuo-wu is going to take care of the chart part.

**Comment by meldafrawi** [comment] 2020-11-18 21:43
Validation:
1. install using yaml : **PASSED**

2. install using helm chart : waiting for PR:https://github.com/longhorn/longhorn/pull/1971 to be reviewed and merged.

**Comment by meldafrawi** [comment] 2020-12-02 22:44
Validation: **PASSED**

**Closed by meldafrawi** 2020-12-02 22:44 UTC
Labels: area/deployment, backport-needed, bug, priority/2
