### ISSUE TITLE
Failed to bind volumes: provisioning failed for PVC "milvus-release"

### ISSUE THREAD

**Issue by jcamilsa** [longhorn/longhorn#2273] opened 2021-02-24 22:28 UTC
Created a Azure kubernetes cluster and deployed Milvus cluster. 3 out of 4 pods are NOT running due to volume mount errors.  "milvus-release-mysql" was mounted successful but not "milvus-release" . Followed the steps from https://milvus.io/docs/v0.10.6/mishards.md for Mishards installation

Kubernetes version: 1.18.14 

Logs:

```
/milvus-helm/charts/milvus> kubectl get pods
NAME                                       READY   STATUS     RESTARTS   AGE
milvus-release-mishards-5fb75ffb94-t6phx   0/1     Init:0/1   0          22m
milvus-release-mysql-5896b9d6d6-8745b      1/1     Running    0          22m
milvus-release-readonly-7d59f58445-8lbjf   0/1     Pending    0          22m
milvus-release-writable-5f575b47f5-n5nds   0/1     Pending    0          22m


/milvus-helm/charts/milvus> kubectl get pvc
NAME                   STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
milvus-release         Pending                                                                        default        23m
milvus-release-mysql   Bound     pvc-53eb34bb-817b-4bfd-bae6-4da8f394b8b3   4Gi        RWO            default        23m


/milvus-helm/charts/milvus> kubectl describe pod milvus-release-readonly-7d59f58445-8lbjf
Name:           milvus-release-readonly-7d59f58445-8lbjf
Namespace:      default
Priority:       0
Node:           <none>
Labels:         app.kubernetes.io/instance=milvus-release
                app.kubernetes.io/name=milvus
                component=readonly
                pod-template-hash=7d59f58445
Annotations:    checksum/config: 62f78d913d57b15069cc974eed4302df7d5e99e2f758f797b7b8a009055bfe62
Status:         Pending
IP:
IPs:            <none>
Controlled By:  ReplicaSet/milvus-release-readonly-7d59f58445
Init Containers:
  wait-for-mysql:
    Image:      alpine:3.8
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      until nc -z -w 2 milvus-release-mysql 3306 && echo mysql database ok; do
        sleep 2;
      done;

    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jkvvv (ro)
  check-for-share-storage:
    Image:      alpine:3.8
    Port:       <none>
    Host Port:  <none>
    Command:
      sh
      -c
      until test -f /var/lib/milvus/db/test/milvus-release.txt && echo read from share storage; do
        sleep 2;
      done;

    Environment:  <none>
    Mounts:
      /var/lib/milvus/db from milvus-data-disk (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jkvvv (ro)
Containers:
  milvus:
    Image:        milvusdb/milvus:0.10.6-cpu-d022221-64ddc2
    Ports:        19530/TCP, 19121/TCP
    Host Ports:   0/TCP, 0/TCP
    Liveness:     http-get http://:19121/system/status delay=30s timeout=10s period=15s #success=1 #failure=5
    Readiness:    http-get http://:19121/system/status delay=15s timeout=10s period=15s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/lib/milvus/conf/server_config.yaml from milvus-configmap (rw,path="readonly_server_config.yaml")
      /var/lib/milvus/db from milvus-data-disk (rw)
      /var/lib/milvus/logs from milvus-logs-disk (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-jkvvv (ro)
Conditions:
  Type           Status
  PodScheduled   False
Volumes:
  milvus-configmap:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      milvus-release
    Optional:  false
  milvus-data-disk:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  milvus-release
    ReadOnly:   false
  milvus-logs-disk:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  default-token-jkvvv:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-jkvvv
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age   From               Message
  ----     ------            ----  ----               -------
  Warning  FailedScheduling  31m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  31m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  24m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  22m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  19m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  17m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  15m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"
  Warning  FailedScheduling  13m   default-scheduler  Failed to bind volumes: provisioning failed for PVC "milvus-release"



/milvus-helm/charts/milvus> kubectl get pvc -o yaml
apiVersion: v1
items:
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: milvus-release
      meta.helm.sh/release-namespace: default
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
      volume.kubernetes.io/selected-node: aks-gpunodepool-39563107-vmss000000
    creationTimestamp: "2021-02-24T21:40:24Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app.kubernetes.io/instance: milvus-release
      app.kubernetes.io/managed-by: Helm
      app.kubernetes.io/name: milvus
      app.kubernetes.io/version: 0.10.6-cpu-d022221-64ddc2
      helm.sh/chart: milvus-0.10.6
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app.kubernetes.io/instance: {}
            f:app.kubernetes.io/managed-by: {}
            f:app.kubernetes.io/name: {}
            f:app.kubernetes.io/version: {}
            f:helm.sh/chart: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
        f:status:
          f:phase: {}
      manager: Go-http-client
      operation: Update
      time: "2021-02-24T21:40:24Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:volume.beta.kubernetes.io/storage-provisioner: {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-02-24T21:40:25Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:volume.kubernetes.io/selected-node: {}
      manager: kube-scheduler
      operation: Update
      time: "2021-02-24T22:03:36Z"
    name: milvus-release
    namespace: default
    resourceVersion: "9210"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/milvus-release
    uid: f8c4e412-559b-45c9-91c6-12d34ccc8d71
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 50Gi
    storageClassName: default
    volumeMode: Filesystem
  status:
    phase: Pending
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    annotations:
      meta.helm.sh/release-name: milvus-release
      meta.helm.sh/release-namespace: default
      pv.kubernetes.io/bind-completed: "yes"
      pv.kubernetes.io/bound-by-controller: "yes"
      volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk
      volume.kubernetes.io/selected-node: aks-cpunodepool-39563107-vmss000001
    creationTimestamp: "2021-02-24T21:40:24Z"
    finalizers:
    - kubernetes.io/pvc-protection
    labels:
      app: milvus-release-mysql
      app.kubernetes.io/managed-by: Helm
      chart: mysql-1.6.4
      heritage: Helm
      release: milvus-release
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            .: {}
            f:meta.helm.sh/release-name: {}
            f:meta.helm.sh/release-namespace: {}
          f:labels:
            .: {}
            f:app: {}
            f:app.kubernetes.io/managed-by: {}
            f:chart: {}
            f:heritage: {}
            f:release: {}
        f:spec:
          f:accessModes: {}
          f:resources:
            f:requests:
              .: {}
              f:storage: {}
          f:volumeMode: {}
      manager: Go-http-client
      operation: Update
      time: "2021-02-24T21:40:24Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:pv.kubernetes.io/bind-completed: {}
            f:pv.kubernetes.io/bound-by-controller: {}
            f:volume.beta.kubernetes.io/storage-provisioner: {}
        f:spec:
          f:volumeName: {}
        f:status:
          f:accessModes: {}
          f:capacity:
            .: {}
            f:storage: {}
          f:phase: {}
      manager: kube-controller-manager
      operation: Update
      time: "2021-02-24T21:40:25Z"
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:annotations:
            f:volume.kubernetes.io/selected-node: {}
      manager: kube-scheduler
      operation: Update
      time: "2021-02-24T21:40:25Z"
    name: milvus-release-mysql
    namespace: default
    resourceVersion: "5461"
    selfLink: /api/v1/namespaces/default/persistentvolumeclaims/milvus-release-mysql
    uid: 53eb34bb-817b-4bfd-bae6-4da8f394b8b3
  spec:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 4Gi
    storageClassName: default
    volumeMode: Filesystem
    volumeName: pvc-53eb34bb-817b-4bfd-bae6-4da8f394b8b3
  status:
    accessModes:
    - ReadWriteOnce
    capacity:
      storage: 4Gi
    phase: Bound
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

**Comment by shuo-wu** [comment] 2021-02-26 02:52
I saw that all PVCs are created by the StorageClass `default`. Is this StorageClass a Longhorn StorageClass? 
Based on the annotation `volume.beta.kubernetes.io/storage-provisioner: kubernetes.io/azure-disk` in the stuck PVC `milvus-release`, you may not even use Longhorn.
Notice that this PVC is mode `ReadWriteMany`, make sure you config the RWX Longhorn volume correctly based on the Longhorn version if you are using Longhorn: https://longhorn.io/docs/1.1.0/advanced-resources/rwx-workloads/

**Comment by shuo-wu** [comment] 2021-04-27 01:47
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by shuo-wu** 2021-04-27 01:47 UTC
