### ISSUE TITLE
[TEST] test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly failed on v1.4.x pipeline

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#6533] opened 2023-08-16 06:24 UTC
## What's the test to develop? Please describe

Test case `test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly` worked well on master and v1.5.x pipeline
but continue failed on [v1.4.x](https://ci.longhorn.io/job/public/job/v1.4.x/job/v1.4.x-longhorn-tests-sles-arm64/261/testReport/)

```
def finalizer():
        api = get_core_api_client()
        client = get_longhorn_api_client()
>       delete_and_wait_statefulset(api, client, statefulset_manifest)

common.py:1390: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:632: in delete_and_wait_statefulset
    wait_delete_pod(api, pod['pod_uid'])
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0xffff6b6bc460>
pod_uid = 'a682da42-1a1d-451f-b72a-15c50124b56a', namespace = 'default'

    def wait_delete_pod(api, pod_uid, namespace='default'):
        for i in range(DEFAULT_POD_TIMEOUT):
            ret = api.list_namespaced_pod(namespace=namespace)
            found = False
            for item in ret.items:
                if item.metadata.uid == pod_uid:
                    found = True
                    break
            if not found:
                break
            time.sleep(DEFAULT_POD_INTERVAL)
>       assert not found
E       AssertionError

common.py:915: AssertionError
```

## Describe the tasks for the test

- [ ] `item1`

## Additional context

N/A

**Comment by khushboo-rancher** [comment] 2023-10-19 22:16
This can reproduced locally with 1.4.4-rc1 according to @nitendra-suse 
cc: @innobead @longhorn/qa

**Comment by innobead** [comment] 2023-10-19 23:19
It looks like a failure happened in the test teardown step? Or the test case is actually failed? @khushboo-rancher

**Comment by innobead** [comment] 2023-10-19 23:20
@shuo-wu Please help check this.

**Comment by khushboo-rancher** [comment] 2023-10-19 23:27
This is a test teardown failure, but I'm curious to know if something is preventing the pod to get deleted?

@nitendra-suse Did the pod stuck in terminating state or it got deleted eventually?

**Comment by nitendra-suse** [comment] 2023-10-20 12:55
> This is a test teardown failure, but I'm curious to know if something is preventing the pod to get deleted?
> 
> @nitendra-suse Did the pod stuck in terminating state or it got deleted eventually?

Pod stuck in terminating state 

`block-device-disconnect-unexpectedly-test-0   0/1     Terminating   0          69m`

**Comment by yangchiu** [comment] 2023-10-22 05:12
Seems this test case has never passed in v1.4.x since it's been implemented.
Is it possible to use longhorn-tests `master` image to run this test case in v1.4.x? If it passed, it probably means some code/commits are missing in longhorn-tests v1.4.x.

**Comment by chriscchien** [comment] 2023-10-23 03:47
This test case with v1.4.x images will [fail](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5074/testReport/junit/tests/test_kubernetes/) when kubernetes version is `v1.25.3+k3s1`(v1.4.x pipeline currently using), [pass](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/5077/testReport/tests/test_kubernetes/) when kubernetes version is `v1.27.1+k3s1`(which is currently v1.5.x and mater pipeline using)

**Comment by yangchiu** [comment] 2023-10-24 13:10
I think there is an issue here.

In the step 3 and step 4 of this test case, it should wait for pod actually terminated before go to the next step:
```
    3. Delete the workload pod
    4. Verify that the pod is able to terminated and a new pod is able
        start
```

But in the current implementation, it doesn't wait for the pod termination:
```
    crash_engine_process_with_sigkill(client, core_api,
                                      sspod_info['pv_name'])
    delete_and_wait_pod(core_api,
                        pod_name=sspod_info['pod_name'],
                        wait=False)
```

If we remove the `wait=False` option in the `delete_and_wait_pod` to let it wait for the pod termination, we can see this test case failed at this step instead of the tear down function:
```
=================================== FAILURES ===================================
___ test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly ____

client = <longhorn.Client object at 0x7f4f88be3640>
core_api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f4f88a03a30>
statefulset = {'apiVersion': 'apps/v1', 'kind': 'StatefulSet', 'metadata': {'name': 'block-device-disconnect-unexpectedly-test', 'na...usybox:1.34.0', 'imagePullPolicy': 'IfNotPresent', 'name': 'sleep', ...}], 'terminationGracePeriodSeconds': 10}}, ...}}
storage_class = {'allowVolumeExpansion': True, 'apiVersion': 'storage.k8s.io/v1', 'kind': 'StorageClass', 'metadata': {'name': 'longhorn-test'}, ...}

    @pytest.mark.csi  # NOQA
    def test_csi_umount_when_longhorn_block_device_is_disconnected_unexpectedly(client, core_api, statefulset, storage_class):  # NOQA
        """
        Test CSI umount when Longhorn block device is disconnected unexpectedly
    
        GitHub ticket: https://github.com/longhorn/longhorn/issues/3778
    
        1. Deloy a statefulset that has volumeClaimTemplates with
            volumeMode: Block
        2. Crash the engine process of the volume to simulate Longhorn block
            device is disconnected unexpectedly
        3. Delete the workload pod
        4. Verify that the pod is able to terminated and a new pod is able
            start
        """
        device_path = "/dev/longhorn/longhorn-test-blk"
        statefulset['spec']['template']['spec']['containers'][0]['volumeMounts'] = [] # NOQA
        statefulset['spec']['template']['spec']['containers'][0]['volumeDevices'] = [ # NOQA
            {'name': 'pod-data', 'devicePath': device_path}
        ]
        statefulset['spec']['volumeClaimTemplates'][0]['spec']['volumeMode'] = 'Block' # NOQA
        statefulset['spec']['replicas'] = 1
        statefulset_name = 'block-device-disconnect-unexpectedly-test'
        update_statefulset_manifests(statefulset,
                                     storage_class,
                                     statefulset_name)
    
        create_storage_class(storage_class)
        create_and_wait_statefulset(statefulset)
        sspod_info = get_statefulset_pod_info(core_api, statefulset)[0]
    
        crash_engine_process_with_sigkill(client, core_api,
                                          sspod_info['pv_name'])
>       delete_and_wait_pod(core_api,
                            pod_name=sspod_info['pod_name'])

test_kubernetes.py:820: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
common.py:602: in delete_and_wait_pod
    wait_delete_pod(api, target_pod.metadata.uid, namespace=namespace)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

api = <kubernetes.client.api.core_v1_api.CoreV1Api object at 0x7f4f88a03a30>
pod_uid = '86da79d4-2b50-4ce5-a4eb-4fc677b77708', namespace = 'default'

    def wait_delete_pod(api, pod_uid, namespace='default'):
        for i in range(DEFAULT_POD_TIMEOUT):
            ret = api.list_namespaced_pod(namespace=namespace)
            found = False
            for item in ret.items:
                if item.metadata.uid == pod_uid:
                    found = True
                    break
            if not found:
                break
            time.sleep(DEFAULT_POD_INTERVAL)
>       assert not found
E       AssertionError

common.py:940: AssertionError
```

Which means the pod is **not** able to be terminated, and definitely not what the behavior the test case expects to.

Unless this test case is not applicable in k8s version <= 1.25, otherwise there is an issue here.

cc @longhorn/qa @innobead

**Comment by yangchiu** [comment] 2023-10-25 06:59
Could related to https://github.com/longhorn/longhorn/issues/6919

**Comment by ejweber** [comment] 2023-10-26 01:34
My gut reaction is that this is not #6919, because that one requires a kubelet restart to hit.

**Comment by yangchiu** [comment] 2023-10-26 02:07
> My gut reaction is that this is not #6919, because that one requires a kubelet restart to hit.

Thanks for the clarification! So it's back to https://github.com/longhorn/longhorn/issues/6533#issuecomment-1777176535. Still need investigation to know what happened.

**Comment by innobead** [comment] 2023-10-26 02:33
@yangchiu @chriscchien do we have a support bundle?

**Comment by derekbit** [comment] 2023-10-26 03:18
Saw the error messages in the kubelet log (v1.25.3+k3s1)

```
Oct 26 03:14:58 ubuntu2004 k3s[3704]: E1026 03:14:58.522314    3704 nestedpendingoperations.go:348] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445 podName:f3d02095-1d37-4704-842f-a6bc63d9efb4 nodeName:}" failed. No retries permitted until 2023-10-26 03:17:00.522301451 +0000 UTC m=+2359.758012633 (durationBeforeRetry 2m2s). Error: UnmapVolume.UnmapBlockVolume failed for volume "pod-data" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445") pod "f3d02095-1d37-4704-842f-a6bc63d9efb4" (UID: "f3d02095-1d37-4704-842f-a6bc63d9efb4") : blkUtil.DetachFileDevice failed. globalUnmapPath:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445/dev, podUID: f3d02095-1d37-4704-842f-a6bc63d9efb4, bindMount: true: failed to unmount linkPath /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445/dev/f3d02095-1d37-4704-842f-a6bc63d9efb4: unmount failed: exit status 1
Oct 26 03:14:58 ubuntu2004 k3s[3704]: Unmounting arguments: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445/dev/f3d02095-1d37-4704-842f-a6bc63d9efb4
Oct 26 03:14:58 ubuntu2004 k3s[3704]: Output: umount: can't unmount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445/dev/f3d02095-1d37-4704-842f-a6bc63d9efb4: Resource busy
```

**Comment by innobead** [comment] 2023-10-26 03:23
This is an upstream issue, https://github.com/longhorn/longhorn/issues/3778#issuecomment-1572999855. 

@chriscchien you verified it before :), the fix was just fixed into K8s 1.27, so the failure here is expected. 

ref: https://github.com/longhorn/longhorn-tests/pull/1475

**Closed by innobead** 2023-10-26 03:23 UTC
Labels: kind/test, priority/0, kind/regression

**Comment by innobead** [comment] 2023-10-26 03:28
@yangchiu probably we can also update the K8s version for 1.4?

**Comment by derekbit** [comment] 2023-10-26 03:40
Workaound

- For the pod stuck in `Terminating ` state
   ```
   kubectl delete pod <name>> --force
   ```

- Detach the problematic block device
   - Find the problematic block device
      ```
      # losetup -a
      /dev/loop1: [1048679]:7340510 (/var/nfs-data/data.img)
      /dev/loop2: [0006]:426 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445/dev/f3d02095-1d37-4704-842f-a6bc63d9efb4 (deleted))
      /dev/loop0: [64515]:6816043 (/home/vagrant/blockfile)
      ```
  - Detach the device
     ```
     losetup --detach /dev/loop2
     ```

**Comment by innobead** [comment] 2023-10-26 03:43
> @yangchiu probably we can also update the K8s version for 1.4?

https://github.com/longhorn/infra/pull/146
