### ISSUE TITLE
[BUG] Nightly Upgrade Test: test_salvage_auto_crash_replicas_short_wait sometimes failed

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1244] opened 2020-04-23 20:13 UTC
**Describe the bug**
sometimes `test_salvage_auto_crash_replicas_short_wait`  test failed after upgrade

**To Reproduce**
1. Install Longhorn v0.7.0
2. Upgrade Longhorn to `master`
3. Run `test_salvage_auto_crash_replicas_short_wait` test

**Expected behavior**
test should pass

**Log**
```
client = <longhorn.Client object at 0x7f5fd00ec6d0>
core_api = <kubernetes.client.apis.core_v1_api.CoreV1Api object at 0x7f5fcfaf3c90>
volume_name = 'longhorn-testvol-ehkgti'
pod_make = <function pod_make.<locals>.make_pod at 0x7f5fcfe91830>

    def test_salvage_auto_crash_replicas_short_wait(client, core_api, volume_name, pod_make):  # NOQA
        """
        [HA] Test automatic salvage feature, with replica building pending
    
        1. Create a PV/PVC/Pod with liveness check.
        2. Create volume and start the pod.
        3. Generate `test_data` and write to the pod.
        4. Run `sync` command inside the pod to make sure data flush to the volume.
        5. Crash one of the replica. Wait for 5 seconds.
        6. Crash all the replicas.
        7. Make sure volume and Pod recovers.
        8. Check `test_data` in the Pod.
    
        FIXME: step 5 should wait for the replica to start rebuilding.
        """
        pod_name, pv_name, pvc_name, test_data = \
            prepare_pod_with_data(client, core_api, volume_name, pod_make)
    
        volume = client.by_id_volume(volume_name)
        replica0 = volume.replicas[0]
    
        crash_replica_processes(client, core_api, volume_name, [replica0])
    
        # Not enough time for rebuild
        time.sleep(5)
    
        volume = client.by_id_volume(volume_name)
    
        replicas = []
        for r in volume.replicas:
            if r.running is True:
                replicas.append(r)
    
        crash_replica_processes(client, core_api, volume_name, replicas)
    
        wait_pod_for_auto_salvage(client, core_api, volume_name,
>                                 pod_name, pv_name, pvc_name, test_data)

test_ha.py:525: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_ha.py:451: in wait_pod_for_auto_salvage
    wait_for_pod_remount(core_api, pod_name)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

core_api = <kubernetes.client.apis.core_v1_api.CoreV1Api object at 0x7f5fcfaf3c90>
pod_name = 'longhorn-testvol-ehkgti-pod'

    def wait_for_pod_remount(core_api, pod_name):
        check_command = [
            '/bin/sh',
            '-c',
            'ls /data/lost+found'
        ]
    
        ready = False
        for i in range(RETRY_EXEC_COUNTS):
            try:
                output = stream(core_api.connect_get_namespaced_pod_exec,
                                pod_name,
                                'default',
                                command=check_command,
                                stderr=True, stdin=False,
                                stdout=True, tty=False)
                if "Input/output error" not in output:
                    ready = True
                    break
            except Exception:
                pass
            if ready:
                break
            time.sleep(RETRY_EXEC_INTERVAL)
>       assert ready
E       AssertionError

common.py:3104: AssertionError
```

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.17.2
 - Node OS type and version: Ubuntu 18.04

**Additional context:**
longhorn-upgrade-tests/63

**Comment by yasker** [comment] 2020-04-23 21:27
Duplicate of https://github.com/longhorn/longhorn/issues/1141

**Comment by shuo-wu** [comment] 2020-05-01 10:35
This failure is different from #1141.

**Comment by shuo-wu** [comment] 2020-05-01 10:49
The following race condition will lead to this failure:
1. One replica is crashed 
2. Wait for 5 seconds.
3. The rebuild is triggered. A new replica is created but **hasn't been updated to running state**.
4. All **running** replicas get crashed.
5. The new replica is in running state.
6. Auto salvage cannot be triggered since there is still an available replica for the volume

The solution:
1. Wait for the new replica running before crashing all replicas.
2. To make sure the rebuild is still in progress when the new replica becomes running, writing more data to volume is necessary.
3. Need to wait for the rebuild start rather than waiting for 5 seconds.

**Comment by yasker** [comment] 2020-05-01 16:48
@shuo-wu on step 5, you meant the new replica finished rebuild before crashing? That's also probably why #1141 failed recently: https://jenkins.int.rancher.io/job/longhorn-upgrade-tests/66/testReport/tests/test_ha/test_salvage_auto_crash_replicas_short_wait/

**Comment by shuo-wu** [comment] 2020-05-04 04:31
No. The error I fixed seems to be different from both.

In the race condition I mentioned, the rebuilt replica seems to become the running state after the test crashing all existing running replicas. Then the volume **cannot be `Faulted` state**. 

Since the test and the related implementation have been updated, we can keep the issue open now and check if those failures can be still triggered.

**Comment by meldafrawi** [comment] 2020-05-08 19:31
`test_salvage_auto_crash_replicas_short_wait` passed for two consecutive runs `longhorn-tests/421` & `longhorn-tests/422`

**Closed** 2020-05-08 19:31 UTC
Labels: area/test, bug, priority/3
