### ISSUE TITLE
[Question] Expand a RWX volume

### ISSUE THREAD

**Issue by kcao3** [longhorn/longhorn#2181] opened 2021-01-13 20:46 UTC
**Question**
Does anyone know if it's currently possible to expand a RWX volume?  I followed the documentation from this link: https://longhorn.io/docs/1.1.0/volumes-and-nodes/expansion/ and attempted to expand a RWO Longhorn volume.

For some unknown reason, after the RWX volume was successfully expanded (i.e kubernetes showed the new size for the PVC), the volume WAS no longer able to be attached by any pods. The pod(s) is stuck in ContainerCreating mode. I see this message when describing the pod: 

From:  attached-controller
Message:  AttacheVolume.Attach failed from volume "pvc-xxxx": rpc error: code = Aborted desc = The volume pvc-xxxx is not ready for workloads. 

However, from the Longhorn web UI under Volume Details, I see the following:
State: Detached
Health: Unknown
Ready for workload: Ready
Frontend: Block Device
Size <NEW_SIZE>
However, on the right side, all of the (3) replicas are shown as Stopped.

Note that I do NOT see this behavior when expanding a RWO Longhorn volume. 

Is this expected? If yes, why? Does anyone have any luck expanding a RWX Longhorn volume? 

**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes version: v1.19.4
 - Node config
   - OS type and version: Centos8
   - CPU per node:
   - Memory per node:
   - Disk type
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**

**Comment by khushboo-rancher** [comment] 2021-01-13 23:12
I see this working with Longhorn-v1.1.0-rc1 but doesn't work with Longhorn v1.1.0.
@joshimoo Could this be because of the modification(adding `share-manager` prefix) of the share-manager pod name?

**Comment by joshimoo** [comment] 2021-01-14 16:32
Will have to investigate.

**Comment by khushboo-rancher** [comment] 2021-01-20 20:12
Reproduction steps:
1. Create a rwx pvc using `longhorn` storage class of size 1 Gi.
2. Attach it to a workload (deployment) and write some data of size 200 Mi.
3. Scale down the workload to detach the volume.
4. Expand the volume to 5 Gi using the Longhorn UI.
5. Scale up the workload once the expansion of volume is completed.
6. The workload gets stuck with error `The volume pvc-ae72f8d7-9f97-4d5f-83e7-46b16bcecc39 is not ready for workloads`.
7. The `share-manager` pod doesn't get created by Longhorn.

**Comment by joshimoo** [comment] 2021-02-12 02:36
The problem is that the expansion call disables the frontend and never enables it again which prohibits the share-manager from controlling the volume. We rely on the attach call to reenable the frontend, the pr https://github.com/longhorn/longhorn-manager/pull/829 reworks the csi + api interaction so that we call attach for each volume type.

Workaround:
After expansion is completed, manually attach the volume to a node.
This will reset the frontendDisable flag.
After which the share-manager will take over.

**Comment by khushboo-rancher** [comment] 2021-03-19 18:12
Verified with Longhorn-master `03/19/2021`

Validation - **Pass**

The expansion of RWX volumes is working fine now.

**Comment by meldafrawi** [comment] 2021-04-16 19:05
Closing, will track integration test implementation in a separate issue https://github.com/longhorn/longhorn/issues/2484

**Closed by meldafrawi** 2021-04-16 19:05 UTC
Labels: kind/bug, kind/question, priority/1, require/automation-e2e
