### ISSUE TITLE
[BUG] Engine upgrade to v1.0.0-rc2 - Failed to remove unknown replica

### ISSUE THREAD

**Issue by meldafrawi** [longhorn/longhorn#1597] opened 2020-07-16 20:11 UTC
**Describe the bug**
Live Engine Upgrade caused some replicas to be removed, and volume turn into degraded state

**To Reproduce**
1. Install Longhorn v1.0.0
2. Create a statefulset using https://raw.githubusercontent.com/longhorn/longhorn/master/examples/statefulset.yaml
3. Scale statefulset number of pods to 5
4. Write data to volumes.
5. Upgrade Longhorn to v1.0.1-rc2
6. Select multiple volumes, do live upgrade.

Noticed that volumes get degraded, and when checked event log, found the following in the event log

```
Failed to remove unknown replica tcp://10.42.1.7:10195 from engine: failed to rm replica address='tcp://10.42.1.7:10195' from controller 'pvc-8294588e-643b-4774-a5b6-aabbbe206557': Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.1-rc2/longhorn [--url 10.42.2.11:10001 rm tcp://10.42.1.7:10195], output , stderr, time="2020-07-16T19:55:07Z" level=fatal msg="Error running rm replica command: failed to delete replica tcp://10.42.1.7:10195 for volume 10.42.2.11:10001: rpc error: code = Unknown desc = Cannot remove last replica if volume is up" , error exit status 1
```

**Expected behavior**
Volume replica should not be removed, volume should be in a healthy state after upgrade.

**Log**
Support bundle: 
[longhorn-support-bundle_19fb3cb6-48bd-49be-a292-8a97445e3f32_2020-07-16T20-10-40Z.zip](https://github.com/longhorn/longhorn/files/4933961/longhorn-support-bundle_19fb3cb6-48bd-49be-a292-8a97445e3f32_2020-07-16T20-10-40Z.zip)

**Environment:**
 - Longhorn version: v1.0.0-rc2
 - Kubernetes version: v1.17
 - Node OS type and version: Ubuntu 18.04

**Additional context**

**Comment by yasker** [comment] 2020-07-16 22:43
Not sure why our integration test didn't catch it. https://github.com/longhorn/longhorn-tests/blob/master/manager/integration/tests/test_engine_upgrade.py

**Comment by shuo-wu** [comment] 2020-07-17 11:50
This bug is caused by the following race condition:
1. The [engine upgrade call](https://github.com/longhorn/longhorn-manager/blob/c176722662546a487cdeda9370fdc260e9ea7a0e/controller/engine_controller.go#L283) succeeds and `engine.Status.CurrentReplicaAddressMap` is updated. But the volume controller [hasn't upgraded `engine.Spec.ReplicaAddressMap`](https://github.com/longhorn/longhorn-manager/blob/c176722662546a487cdeda9370fdc260e9ea7a0e/controller/volume_controller.go#L1363)
2. The engine controller [update `engine.Status.CurrentReplicaAddressMap`](https://github.com/longhorn/longhorn-manager/blob/c176722662546a487cdeda9370fdc260e9ea7a0e/controller/engine_controller.go#L287) based on the expired `engine.Spec.ReplicaAddressMap`
3. The engine monitor found the [mismatching](https://github.com/longhorn/longhorn-manager/blob/c176722662546a487cdeda9370fdc260e9ea7a0e/controller/engine_controller.go#L702) between the engine process actual replica address map and `engine.Status.CurrentReplicaAddressMap`. Then the bug is triggered.

**Comment by shuo-wu** [comment] 2020-07-17 12:02
Solution:
Make sure the engine upgrade complete (`len(engine.Spec.UpgradedReplicaAddressMap) == 0`) before updating `engine.Status.CurrentReplicaAddressMap` based on `engine.Spec.ReplicaAddressMap` and starting the engine monitor refreshing.

**Comment by shuo-wu** [comment] 2020-07-17 12:06
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at
https://github.com/longhorn/longhorn-manager/pull/631

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: volume attachment/detachment
Issues: The status transition during the volume attachment/detachment

* [x] ~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~

* [x] ~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~

* [x] ~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~

* [x] ~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~

* [x] ~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~

* [x] ~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~

**Comment by yasker** [comment] 2020-07-17 16:09
Why did our integration test fail to catch it?

**Comment by meldafrawi** [comment] 2020-07-17 18:35
Validation: **PASSED**

**Closed** 2020-07-17 18:35 UTC
Labels: area/engine, bug, priority/1, reproduce/always, require/automation-e2e
