### ISSUE TITLE
[BUG] Backups on Google Cloud Storage aren't deleted

### ISSUE THREAD

**Issue by aimbot31** [longhorn/longhorn#1404] opened 2020-05-26 08:12 UTC
**Describe the bug**
When using a Google Cloud Storage bucket, "Backups" aren't deleted.

**To Reproduce**

1. Configure a Google Cloud Sotrage bucket to be the endpoint for your backups
2. Create a volume (PVC) of 5gb, attach it to a pod, write data, take backups b1, b2 for the volume
3. Navigate to Backup Page
4. From operations select "Delete All Backups" for the backup volume

**Expected behavior**
All my backups should have been deleted

**Log**
This is the popup i get when i try to delete all my backups :
>error deleting backup volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080: error deleting backup volume: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v0.8.1/longhorn [backup rm --volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080 s3://k8s_dev_bucket@europe-west4/longhorn], output failed to remove all the backups for volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080: failed to remove objects with param { Bucket: "k8s_dev_bucket", Delete: { Objects: [{ Key: "longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-90b6a98a2839486b.cfg" },{ Key: "longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-d169fb81f7c043ff.cfg" }], Quiet: true } }: AWS Error: InvalidArgument Invalid argument. 400 , stderr, time="2020-05-25T16:35:33Z" level=error msg="{\n\n}" pkg=s3 time="2020-05-25T16:35:33Z" level=error msg="failed to remove all the backups for volume pvc-2971047b-9be9-4ed2-a127-48d1a57e0080: failed to remove objects with param {\n Bucket: "k8s_dev_bucket",\n Delete: {\n Objects: [{\n Key: "longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-90b6a98a2839486b.cfg"\n },{\n Key: "longhorn/backupstore/volumes/1c/36/pvc-2971047b-9be9-4ed2-a127-48d1a57e0080/backups/backup_backup-d169fb81f7c043ff.cfg"\n }],\n Quiet: true\n }\n}: AWS Error: InvalidArgument Invalid argument. \n400 \n" , error exit status 1

**Environment:**
 - Longhorn version: v0.8.1
 - Kubernetes version: v1.16.8
 - Node OS type and version: Ubuntu 18.04

**Additional context**
I tried to configure automatic backups with some retain policy, it also fail to delete the backups without giving errors.
When i try to delete a single backup nothing happens, just a simple reload.
My Google Service Account has all the needed rights on my bucket.

**Comment by meldafrawi** [comment] 2020-05-28 18:41
Could be reproduced using latest `master`:

Reproduce steps:
1. Deploy Longhorn using latest master images.
2. Create GCP bucket, and create backupstore secret
3. Set backupstore  target to point to GCP bucket, and backup target credentials to backup store secret name
4. Create a pod using volume, create a backup for that volume
5. In Backup page, try to delete all backups for the volume   **FAILED**
```
error deleting backup volume pvc-ad7c01d4-9aff-4b4d-8658-8bd249fb181e: error deleting backup volume: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup rm --volume pvc-ad7c01d4-9aff-4b4d-8658-8bd249fb181e s3://meldafrawi-longhorn@us-east1/backupstore], output failed to remove all the backups for volume pvc-ad7c01d4-9aff-4b4d-8658-8bd249fb181e: failed to delete objects with param: { Bucket: "meldafrawi-longhorn", Delete: { Objects: [{ Key: "backupstore/backupstore/volumes/02/af/pvc-ad7c01d4-9aff-4b4d-8658-8bd249fb181e/backups/backup_backup-2210d531c2ac4cce.cfg" }], Quiet: true } } response: { } error: AWS Error: InvalidArgument Invalid argument. <nil> 400 , stderr, time="2020-05-28T18:39:16Z" level=error msg="failed to remove all the backups for volume pvc-ad7c01d4-9aff-4b4d-8658-8bd249fb181e: failed to delete objects with param: {\n Bucket: \"meldafrawi-longhorn\",\n Delete: {\n Objects: [{\n Key: \"backupstore/backupstore/volumes/02/af/pvc-ad7c01d4-9aff-4b4d-8658-8bd249fb181e/backups/backup_backup-2210d531c2ac4cce.cfg\"\n }],\n Quiet: true\n }\n} response: {\n\n} error: AWS Error: InvalidArgument Invalid argument. <nil>\n400 \n" , error exit status 1
```
7. Try to delete individual backup, backup will not be deleted    **FAILED**
> Response of backupDelete POST request will be empty

**Comment by joshimoo** [comment] 2020-05-29 01:12
The reason the backup deletion does not work, is that google cloud storage is not have full s3 interoperability. In particular it is missing the s3 multi object delete functionality that we are using for our deletion operation.

There is a tiny footnote [here](https://cloud.google.com/storage/docs/migrating#methods-comparison)

For 1.0.1 we plan to switch to individual object deletion, which will allow us to support google cloud storage.

**Comment by aimbot31** [comment] 2020-05-29 11:42
Thanks for yours answers, I hope the v1.0.0 or v1.0.1 is going to be released soon :)

**Comment by joshimoo** [comment] 2020-06-02 04:13
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at

* [ ] Is the reproduce steps/test steps documented?

* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at

* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at

* [ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at 

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by khushboo-rancher** [comment] 2020-06-08 21:15
Verified on Master - 06-08-2020

Verification - **Failed**

**Scenarios tested:** 
1. Delete all backups on google backup store - Passed.
2. Delete individual backup on google backup store - Failed.

**Steps follow**
1. Set up a google backup store.
2. Set the backup target as google backup store in longhorn.
3. Create a volume, attach to a pod. Write into the volume.
4. Take multiple backups.
5. Try to delete individual backup or all the backups.
6. Individual backup deletion fails most of the times and on trying multiple times it gets deleted sometimes.

In case where individual backup fails to get deleted, API call of deletion return 200 response.

[longhorn-support-bundle_e75960bf-d43f-4124-b8b4-96c44f555ee2_2020-06-08T21-05-54Z.zip](https://github.com/longhorn/longhorn/files/4748639/longhorn-support-bundle_e75960bf-d43f-4124-b8b4-96c44f555ee2_2020-06-08T21-05-54Z.zip)

**Closed** 2020-06-08 23:05 UTC
Labels: area/engine, enhancement, priority/2, require/manual-test-plan
