### ISSUE TITLE
[REFACTOR] Remove outdated go-rancher from longhorn manager and CSI driver

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8026] opened 2024-02-26 02:48 UTC
## Is your improvement request related to a feature? Please describe

go-racnher is outdated w/o maintenance and it will impact our dependency update in general, as the libraries it uses could be outdated as well. It is being used in Longhorn Manager API implementation. The API is used by the UI frontend, CSI driver, and existing automated test cases. 

The goal is:
- Replace it with a general web framework with swagger (OpenAPI) support. 
- Ensure UI and CSI have corresponding adjustments if needed.
- Operate Longhorn CR directly instead of Longhorn API in the CSI controller.
- Have a doc to describe the changes for potential informal users. 

## Additional context

@longhorn/dev

**Comment by shuo-wu** [comment] 2024-02-26 05:32
Just curious, what's the replacement of go-rancher?

**Comment by innobead** [comment] 2024-02-26 06:52
> Just curious, what's the replacement of go-rancher?

Need investigation, but basically a general HTTP framework w/ swagger support. Also, need to resolve the current usage as described in the description.

**Comment by ejweber** [comment] 2024-02-26 16:02
Potential duplicate of https://github.com/longhorn/longhorn/issues/6407. That one has one possible suggestion after @PhanLe1010 and I discussed it, but I think it is fine to close it in favor of this one if desired.

**Comment by innobead** [comment] 2024-02-26 16:12
Exactly, they are the same.

@ejweber already self-assigned to u, so I would like you to continue working on that as planned.

**Closed** 2024-02-26 16:12 UTC
Labels: component/longhorn-manager, kind/refactoring, priority/0, area/csi, duplicated, require/ui
