### ISSUE TITLE
[FEATURE] Use AWS IAM Role for Backup / Restore

### ISSUE THREAD

**Issue by Wykiki** [longhorn/longhorn#1526] opened 2020-06-26 07:45 UTC
**Is your feature request related to a problem? Please describe.**
In my organization, we cannot create IAM User or generate static credentials, so we cannot provide credentials to the Backup / Restore mechanism of Longhorn.

But we can attach roles to EC2 instances, and with tools like [Kiam](https://github.com/uswitch/kiam), we are able to associate roles to specific containers.

**Describe the solution you'd like**
I think that, when providing credentials to the Backup / Restore, we can choose to either **provide the secret containing IAM User credentials**, or **provide the IAM Role ARN** we want Longhorn to use.

Or we can have a variable called **AWS_ROLE_ARN** standing next to **AWS_** credentials variables, and Longhorn would be able to pick the credentials if they exists, or fall back to role if not.

**Describe alternatives you've considered**
Considered alternative would be running a Minio instance, which will be synchronized to an AWS S3 bucket.
But we will have to maintain this Minio installation in addition to Longhorn.

**Additional context**
Not much

**Comment by yasker** [comment] 2020-06-26 19:08
Adding the environment variable AWS_ROLE_ARN sounds like a good solution here.

**Comment by jackivanov** [comment] 2020-09-30 14:52
Any progress on this?

**Comment by c3y1huang** [comment] 2021-01-28 02:29
Currently, I have no permission to create IAM roles with my SUSE  account. The permission needs to be sorted first before I can progress the investigation.

**Comment by innobead** [comment] 2021-01-28 02:47
> Currently, I have no permission to create IAM roles with my SUSE account. The permission needs to be sorted first before I can progress the investigation.

Let's raise to SUSE Eng IT to see how it will work. Move it to icebox first, then triage later.

**Comment by ElZakariyae** [comment] 2021-02-02 10:45
also @here, for security reasons we can't use the AWS credentials, therefore is there any update regarding the solution mentioned above? from my point of view the environment variable is not needed since once the iam role is attached to the instance profile longhorn should access the resources defined in the role policies.

**Comment by innobead** [comment] 2021-03-24 05:25
This ticket needs two types of test planes. 

`request/automation-e2e` for annotation management
`requrest/manual-test-plan` for the complete e2e flow including S3 operation

cc @khushboo-rancher @meldafrawi

**Comment by innobead** [comment] 2021-03-29 10:05
> This ticket needs two types of test planes.
> 
> * `request/automation-e2e` for annotation management
> * `request/manual-test-plan` for the complete e2e flow including S3 operation
> 
> cc @khushboo-rancher @meldafrawi

After discussing with @jenting, we decide to defer the automation-e2e to later because it needs more effort than expectation and possibly impacts the current test regression.

**Comment by meldafrawi** [comment] 2021-04-01 17:23
Validation: **PASSED**

Test Steps:
> https://github.com/longhorn/longhorn-tests/pull/571

**Comment by meldafrawi** [comment] 2021-04-16 19:04
Closing, will track integration test implementation in a separate issue https://github.com/longhorn/longhorn/issues/2483

**Comment by khushboo-rancher** [comment] 2021-06-08 01:58
Reopening this as this seems broken on v1.1.1 and Longhorn-v1.1.2-head

cc: @jenting @innobead

**Comment by innobead** [comment] 2021-06-08 08:52
> Reopening this as this seems broken on v1.1.1 and Longhorn-v1.1.2-head
> 
> cc: @jenting @innobead

@khushboo-rancher please help verify again after discussing with @jenting . Thanks.

**Comment by khushboo-rancher** [comment] 2021-06-11 05:01
Validated with Longhorn v1.1.2-head and Longhorn-master `06/10/2021` this is working fine, the problem was in testing env, the iam role permission was not proper to access s3.

**Closed by khushboo-rancher** 2021-06-11 05:01 UTC
Labels: area/engine, area/manager, highlight, kind/enhancement, priority/1, require/automation-e2e, require/doc, require/manual-test-plan
