### ISSUE TITLE
[BUG] MountVolume.MountDevice failed for volume Output: mount.nfs: Protocol not supported

### ISSUE THREAD

**Issue by Alxandr** [longhorn/longhorn#6887] opened 2023-10-13 21:14 UTC
## Describe the bug (🐛 if you encounter this issue)

My pods (using a specific volume) is no longer starting (they used to), and I get an error stating the following:

```
MountVolume.MountDevice failed for volume "pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: /usr/local/sbin/nsmounter Mounting arguments: mount -t nfs -o vers=4.1,noresvport,intr,hard 10.43.76.13:/pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/12de6c62f175ce990f279cc34d4f579f36032e64e5d21392aa59f1ed192758cd/globalmount Output: mount.nfs: Protocol not supported for 10.43.76.13:/pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58 on /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/12de6c62f175ce990f279cc34d4f579f36032e64e5d21392aa59f1ed192758cd/globalmount
```

## To Reproduce

I don't know how to reproduce this error. It happens for one of my volumes, and I don't know how to resolve it.

The configuration I have is the following:

```yaml
apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58
  uid: 080fa053-2048-41fb-9ed7-c4f9e9214cc1
  resourceVersion: '318384351'
  creationTimestamp: '2023-10-03T19:53:29Z'
  annotations:
    longhorn.io/volume-scheduling-error: ''
    pv.kubernetes.io/provisioned-by: driver.longhorn.io
    volume.kubernetes.io/provisioner-deletion-secret-name: ''
    volume.kubernetes.io/provisioner-deletion-secret-namespace: ''
  selfLink: /api/v1/persistentvolumes/pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58
status:
  phase: Bound
spec:
  capacity:
    storage: 10Gi
  csi:
    driver: driver.longhorn.io
    volumeHandle: pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58
    fsType: ext4
    volumeAttributes:
      dataLocality: disabled
      fromBackup: ''
      fsType: ext4
      numberOfReplicas: '2'
      share: 'true'
      staleReplicaTimeout: '30'
      storage.kubernetes.io/csiProvisionerIdentity: 1696306401569-8081-driver.longhorn.io
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  claimRef:
    kind: PersistentVolumeClaim
    namespace: attic
    name: attic-db
    uid: d11e720d-2d0d-48d0-8b11-82ddf4ca7a58
    apiVersion: v1
    resourceVersion: '318373363'
  persistentVolumeReclaimPolicy: Delete
  storageClassName: longhorn
  volumeMode: Filesystem
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: attic-db
  namespace: attic
  uid: d11e720d-2d0d-48d0-8b11-82ddf4ca7a58
  resourceVersion: '318373431'
  creationTimestamp: '2023-10-03T19:53:27Z'
  labels:
    kustomize.toolkit.fluxcd.io/name: 99-attic
    kustomize.toolkit.fluxcd.io/namespace: flux-system
  annotations:
    pv.kubernetes.io/bind-completed: 'yes'
    pv.kubernetes.io/bound-by-controller: 'yes'
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
    volume.kubernetes.io/storage-provisioner: driver.longhorn.io
  selfLink: /api/v1/namespaces/attic/persistentvolumeclaims/attic-db
status:
  phase: Bound
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  capacity:
    storage: 10Gi
spec:
  accessModes:
    - ReadWriteOnce
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  volumeName: pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58
  storageClassName: longhorn
  volumeMode: Filesystem
```

this is then used in a pod (owned by a deployment) with the following config:

```yaml
      volumes:
        - name: db
          persistentVolumeClaim:
            claimName: attic-db
```

## Expected behavior

The volume should get mounted normally and the pod start

## Support bundle for troubleshooting

[supportbundle_fb30f00f-8c5c-46cf-9f98-f097746ddc7e_2023-10-13T21-09-15Z.zip](https://github.com/longhorn/longhorn/files/12899227/supportbundle_fb30f00f-8c5c-46cf-9f98-f097746ddc7e_2023-10-13T21-09-15Z.zip)

## Environment

 - Longhorn version: v1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s v1.28.2+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: OpenSuse MicroOS
   - Kernel version: 6.5.6-1-default
   - CPU per node: 3
   - Memory per node: 8G
   - Disk type(e.g. SSD/NVMe/HDD): SSD
   - Network bandwidth between the nodes: All nodes are VMs on the same physical machine, so I don't think there's much of a limit.
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal
 - Number of Longhorn volumes in the cluster: 6
 - Impacted Longhorn resources: 1
   - Volume names: pvc-d11e720d-2d0d-48d0-8b11-82ddf4ca7a58

**Comment by derekbit** [comment] 2023-10-14 01:18
It is an OS issue. The workaround is rolling back to previous MicroOS version.
Please refer to https://github.com/longhorn/longhorn/issues/6857

**Comment by janosmiko** [comment] 2023-10-14 04:45
Or you can pin the nfs-client version
```
transactional-update shell
zypper install -y https://download.opensuse.org/history/20231008/tumbleweed/repo/oss/x86_64/nfs-client-2.6.3-39.4.x86_64.rpm
zypper addlock nfs-client
```

**Comment by derekbit** [comment] 2023-10-14 05:24
@janosmiko 
Do you know which verision of nfs-client is problematic? I will take a look on the changes.

**Comment by janosmiko** [comment] 2023-10-14 05:26
It's this one: `nfs-client-2.6.3-39.5`

See the related issue and discussion for more useful info:
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/discussions/1018
https://github.com/kube-hetzner/terraform-hcloud-kube-hetzner/issues/1016

**Comment by Alxandr** [comment] 2023-10-14 16:30
> zypper addlock nfs-client

I did this on all 3 nodes, and restarted them, and it did not seem to help.

```
alxandr@home-lab-server-2:~> zypper info nfs-client
Loading repository data...
Reading installed packages...


Information for package nfs-client:
-----------------------------------
Repository     : openSUSE-Tumbleweed-Oss
Name           : nfs-client
Version        : 2.6.3-39.5
Arch           : x86_64
Vendor         : openSUSE
Installed Size : 874.5 KiB
Installed      : Yes
Status         : out-of-date (version 2.6.3-39.4 installed)
Source package : nfs-utils-2.6.3-39.5.src
Upstream URL   : https://kernel.org/pub/linux/utils/nfs-utils/
Summary        : Support Utilities for NFS
Description    : 
    This package contains common NFS utilities which are needed for client
    and kernel based server.
```

**Comment by derekbit** [comment] 2023-10-15 02:23
@Alxandr 
The nfs-client is still 2.6.3-39.4 in your environment.
Or, can you roll back to previous MicroOS  version?

**Comment by Alxandr** [comment] 2023-10-15 10:18
@derekbit 2.6.3-39.4 was supposed to be the last good one, no? 2.6.3-39.5 is what's causing issues according to the comments in this thread. I can probably roll back the MicroOS version (though I've never had to, so I would have to figure out how) - but I imagine it's just going to auto-update within 24 hours anyways - so it's not really a good solution.

**Comment by whezzel** [comment] 2023-10-19 17:14
I have this same issue with arch linux has the host os. Nfs-client is 2.6.3 which was last updated in march. I was able to mount rwx volumes as recent as 3 days ago. I rebuilt my cluster (including the host os) 2 days ago and thats when i lost the ability to mount rwx volumes. I do have the nfs-client install on my hosts and it supports v4.1. Rolling back the os isnt really an option for me since partial updates are not supported on arch.

**Comment by a13xie** [comment] 2023-10-21 05:42
I'm also on Arch, after a system update today I started encountering this issue.

I also noticed this message in my system journal:

```
kernel: nfs: Deprecated parameter 'intr'
```

Kernel: linux-bcachefs-git - `6.5.6.arch2.r1204783.d0c3d7ceb202-1`
nfs-utils: `2.6.3-1` (build date Thu 20 Apr 2023)

**Comment by derekbit** [comment] 2023-10-27 03:39
@Alxandr @whezzel @a13xie 
The issue is identified as a linux kernel bug in kernel 6.5.6 and please refer to https://github.com/longhorn/longhorn/issues/6857#issuecomment-1765376826 .

It is fixed in linux kernel 6.5.7 and newer. Before an OS distro releases with a newer kernel, you can downgrade the kernel to an older one.

**Comment by derekbit** [comment] 2023-10-27 03:53
Duplicate https://github.com/longhorn/longhorn/issues/6857

**Comment by derekbit** [comment] 2023-10-27 03:54
Let's track the issue in https://github.com/longhorn/longhorn/issues/6857.

**Comment by a13xie** [comment] 2023-10-27 04:50
@derekbit Awesome! Thanks for letting us know!

**Comment by whezzel** [comment] 2023-10-27 16:47
Thanks for this info. I updated all of my hosts from kernel 6.5.7 to 6.5.9 and this has resolved my issue with RWX volumes.

**Comment by Alxandr** [comment] 2023-10-27 17:07
Same here. Volumes are successfully mounting again. Feel free to close this issue.

**Comment by a13xie** [comment] 2023-11-07 05:54
I was finally able to do a kernel update today as well. The issue is gone, all volumes mounted successfully!

**Comment by lcapka** [comment] 2024-02-08 14:12
> I am experiencing the same issue after updating my Ubuntu 20.04 workers to kernel 5.15.0-94-generic which was just released from Canonical. Maybe a faulty backport?

We have exactly the same problem with the same Kernel version.

**Comment by Isotop7** [comment] 2024-02-11 13:01
Downgrade to `5.15.0-92` fixed it, but this seems to be related to a kernel change...

**Comment by Isotop7** [comment] 2024-02-13 16:58
Could be related to this

https://bugs.launchpad.net/bugs/2052842

as I noticed, that no block devices were created after the longhorn volume was mounted under `/dev/longhorn`.

**Comment by baskinsy** [comment] 2024-02-14 13:58
There is a fix for the next kernel update for the above issue. Let's see if that was the problem.

https://bugs.launchpad.net/ubuntu/+source/linux/+bug/2049689

**Comment by derekbit** [comment] 2024-02-14 23:54
We've identified the kernel issue before and had a [KB doc](https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/) for the issue.
Unfortunately, the problematic PR is backported to 5.15.0-94.104-generic...

Let's open the ticket and highlight the newly affected kernel versions in the KB doc.

**Comment by derekbit** [comment] 2024-02-15 04:29
> Could be related to this
> 
> https://bugs.launchpad.net/bugs/2052842
> 
> as I noticed, that no block devices were created after the longhorn volume was mounted under `/dev/longhorn`.
> 
> @derekbit IMHO this needs to be reopened as it might effect other users with other distris that implement that kernel version.

@baskinsy, @Isotop7 and @lcapka 
I'm unable to reproduce the issue using the disto and kernel version
```
# uname -a
Linux rancher60-master 5.15.0-94-generic #104-Ubuntu SMP Tue Jan 9 15:25:40 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
```

Can you provide the steps to reproduce? Thank you.

BTW, are you able to create a new ticket for the issue which is different than the original issue?  Thanks.

**Comment by baskinsy** [comment] 2024-02-15 09:52
@derekbit I just upgraded 5 worker nodes from kernel 5.15.0-92 to  5.15.0-94 and after rebooting all my RWX volumes started to fail with the Protocol not supported message. Downgrading the kernel and rebooting again fixes the issue. Nodes are running for over 1 year without issues.

**Comment by lcapka** [comment] 2024-02-15 11:28
@derekbit 

Hi!

The issue is connected with **RWX** volumes that are using NFS in Longhorn. Our cluster has a few nodes, all based on **Ubuntu 22.04** and we are running currently **RKE2 v1.27.10 +rke2r1**. All worked till 5.15.0-92 and since **5.15.0-94** it stopped. The longhorn has been (unfortunately) installed using RKE2's apps so it's on the latest available version via RKE2 apps which is **102.3.1+up1.5.3**.

The problem can be simulated even out of the cluster itself when a pod is in back-off loop because of mount error. In our case we tried manually run the comment (we found it in the failing POD's kubectl describe info) on the Ubuntu node directly.
[mount-nfs-longhorn.dump.zip](https://github.com/longhorn/longhorn/files/14296145/mount-nfs-longhorn.dump.zip)


```
Events:
  Type     Reason       Age                   From     Message
  ----     ------       ----                  ----     -------
  Warning  FailedMount  8m5s (x752 over 25h)  kubelet  MountVolume.MountDevice failed for volume "pvc-f7f7aa18-999e-44aa-8391-00df9e099168" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /usr/local/sbin/nsmounter
Mounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,softerr 10.43.50.95:/pvc-f7f7aa18-999e-44aa-8391-00df9e099168 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/b5aa5195e7e7969102a79de3e5f76163fa63e95687985a08e93f840019b74f48/globalmount
Output: mount.nfs: Protocol not supported
  Warning  FailedMount  3m25s (x671 over 25h)  kubelet  Unable to attach or mount volumes: unmounted volumes=[ghost-data], unattached volumes=[], failed to process volumes=[]: timed out waiting for the condition
```

Example from the node machine:

```
# mount -v -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,softerr 10.43.50.95:/pvc-f7f7aa18-999e-44aa-8391-00df9e099168 /mnt/x
mount.nfs: timeout set for Thu Feb 15 11:17:14 2024
mount.nfs: trying text-based options 'vers=4.1,noresvport,timeo=600,retrans=5,softerr,addr=10.43.50.95,clientaddr=10.77.1.9'
mount.nfs: mount(2): Protocol not supported
mount.nfs: Protocol not supported
```

We have even captured and looked into TCP frames using tcpdump but honestly - no error are visible there and we don't have NFS protocol experts in our team. Anyway - you can find the tcpdump output attached.

I'm not sure whether it helps or not but here it is. Let me know what information you might need.

**Comment by derekbit** [comment] 2024-02-15 14:23
@lcapka @baskinsy 

Thanks for your information.

I've reviewed your [symptom description ](https://github.com/longhorn/longhorn/issues/6887#issuecomment-1945906153)and the [kernel 5.15.0-94 code](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/log/?h=Ubuntu-5.15.0-94.104&ofs=100). It appears the issue is related to [an NFS commit](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=Ubuntu-5.15.0-94.104&id=b8bcda78d824e521d31300dd7b1f0766cd01ce91), not the bug reported at https://bugs.launchpad.net/bugs/2052842.

The [fix](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=Ubuntu-5.15.0-100.110&id=e8104b224c3d60a0f384f6b38419523aed4912dd) is applied to [5.15.0-100.110](https://git.launchpad.net/~ubuntu-kernel/ubuntu/+source/linux/+git/jammy/commit/?h=Ubuntu-5.15.0-100.110&id=e8104b224c3d60a0f384f6b38419523aed4912dd), but it seems not released yet.

**Comment by derekbit** [comment] 2024-02-15 14:59
@james-munson 

Can you help add the [problematic version](https://github.com/longhorn/longhorn/issues/6887#issuecomment-1946197456) 
 in the [KB doc](https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/) and update the check environment script as @innobead metioned in https://github.com/longhorn/longhorn/issues/6857#issuecomment-1945507658? Thank you.

**Comment by innobead** [comment] 2024-02-15 15:25
@derekbit let's not reopen an existing resolved issue in a released milestone. Create another issue instead. Can just use https://github.com/longhorn/longhorn/issues/6857#issuecomment-1945507658.

**Closed** 2024-02-15 15:29 UTC
Labels: kind/bug, require/knowledge-base, area/volume-rwx, area/environment-issue, require/qa-review-coverage, require/backport

**Comment by Siradjedd** [comment] 2024-02-27 16:06
@baskinsy  did you solve the issue ? my kernel version is -97 and i have same issue

**Comment by baskinsy** [comment] 2024-02-27 16:09
Nope still the same with -97 kernel, we have to wait for -100 as it seems.

**Comment by baskinsy** [comment] 2024-02-27 16:27
RWO volumes were not affected at all for me.

**Comment by Siradjedd** [comment] 2024-02-27 16:29
@baskinsy  yes the issue is only with RWM i geuss.

**Comment by vojtechmares** [comment] 2024-02-27 16:41
Hi @baskinsy, since this issue is connected to NFS and Kernel and NFS-backed volumes are only for ReadWriteMany (RWX) access mode. Volumes with access mode ReadWriteOnce (RWO) are unaffected.

And I can confirm that as well with our production Longhorn deployment.

**Comment by Siradjedd** [comment] 2024-02-27 17:52
@vojtechmares  we just updated longhorn to 1.6.0 and it solved the problem.

**Comment by rotilho** [comment] 2024-03-05 07:35
1.6.0 also fixed the issue for me
