### ISSUE TITLE
Listing backups may fail during backup deletion

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#710] opened 2019-09-04 23:18 UTC
```
clients = {'longhorn-staging-tests-01': <longhorn.Client object at 0x7f0e589e2cd0>, 'longhorn-staging-tests-02': <longhorn.Client object at 0x7f0e58491e10>, 'longhorn-staging-tests-03': <longhorn.Client object at 0x7f0e589e2f50>}
volume_name = 'longhorn-testvol-b4pqea'

    @pytest.mark.coretest   # NOQA
    def test_backup(clients, volume_name):  # NOQA
>       backup_test(clients, volume_name, SIZE)

test_basic.py:396: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
test_basic.py:430: in backup_test
    backupstore_test(client, lht_hostId, volume_name, size)
test_basic.py:538: in backupstore_test
    backups = bv.backupList().data
longhorn.py:248: in cb
    *args, **kw)
longhorn.py:442: in action
    return self._post_and_retry(url, *args, **kw)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <longhorn.Client object at 0x7f0e589e2f50>
url = 'http://10.42.1.5:9500/v1/backupvolumes/longhorn-testvol-b4pqea?action=backupList'
args = (), kw = {}, retries = 3, last_error = None, i = 0
e = ApiError(ApiError(...), '500 : error listing backups for volume \'longhorn-tes... exist. <nil>\\\\n404 \\\\n"\\n, error exit status 1\', \'type\': u\'error\'}')

    def _post_and_retry(self, url, *args, **kw):
        retries = kw.get('retries', 3)
        last_error = None
        for i in range(retries):
            try:
                return self._post(url, data=self._to_dict(*args, **kw))
            except ApiError as e:
                if e.error.code == 409:
                    last_error = e
                    time.sleep(.1)
                else:
>                   raise e
E                   ApiError: (ApiError(...), '500 : error listing backups for volume \'longhorn-testvol-b4pqea\': error listing backups: Failed to execute: /var/lib/rancher/longhorn/engine-binaries/longhornio-longhorn-engine-staging/longhorn [backup ls --volume longhorn-testvol-b4pqea s3://backupbucket@us-east-1/backupstore], output AWS Error:  NoSuchKey The specified key does not exist. <nil>\n404 \n\n, stderr, time="2019-09-04T08:54:11Z" level=error msg="{\\n  AcceptRanges: \\"bytes\\",\\n  Body: <nil>,\\n  ContentLength: 511,\\n  ContentType: \\"application/xml\\",\\n  Metadata: {\\n\\n  }\\n}" pkg=s3\ntime="2019-09-04T08:54:11Z" level=error msg="AWS Error:  NoSuchKey The specified key does not exist. <nil>\\n404 \\n"\n, error exit status 1\n{\'status\': 500, \'code\': 500, \'links\': {\'self\': u\'http://10.42.1.5:9500/v1/backupvolumes/longhorn-testvol-b4pqea\'}, \'self\': <function cb at 0x7f0e58bd8230>, \'detail\': u\'\', \'actions\': {}, \'message\': u\'error listing backups for volume \\\'longhorn-testvol-b4pqea\\\': error listing backups: Failed to execute: /var/lib/rancher/longhorn/engine-binaries/longhornio-longhorn-engine-staging/longhorn [backup ls --volume longhorn-testvol-b4pqea s3://backupbucket@us-east-1/backupstore], output AWS Error:  NoSuchKey The specified key does not exist. <nil>\\n404 \\n\\n, stderr, time="2019-09-04T08:54:11Z" level=error msg="{\\\\n  AcceptRanges: \\\\"bytes\\\\",\\\\n  Body: <nil>,\\\\n  ContentLength: 511,\\\\n  ContentType: \\\\"application/xml\\\\",\\\\n  Metadata: {\\\\n\\\\n  }\\\\n}" pkg=s3\\ntime="2019-09-04T08:54:11Z" level=error msg="AWS Error:  NoSuchKey The specified key does not exist. <nil>\\\\n404 \\\\n"\\n, error exit status 1\', \'type\': u\'error\'}')
```

When Longhorn tried to list the backup which was being deleted, this error may occur.

**Comment by shuo-wu** [comment] 2019-09-04 23:20
Currently the above PR is more like a workaround: ignore and retry

**Comment by yasker** [comment] 2019-09-06 18:03
Need the workaround for v0.6.0, move the real fix to v0.7.0

**Comment by joshimoo** [comment] 2020-07-17 21:07
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at longhorn/longhorn-tests#372 
longhorn/backupstore#53 
longhorn/longhorn-manager#632
longhorn/longhorn-engine#517

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area backup tests
Issues #710 #1604 #1603 

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] ~~**if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

**Comment by yasker** [comment] 2020-07-17 21:18
What's the reproduce steps for the issue?

**Comment by joshimoo** [comment] 2020-07-17 21:37
So there are 2 cases in which this issue could happen:
The core problem is that listing the backup volume names is a multi step process.
Since we have 2 intermediate folders for each backup volume.

Case 1: 
could happen previously when deleting the last backup for a backup volume.
we solved this case a while ago when we split the backup / backup volume deletion.

Case 2:
A: If during the execution of the list operation after evaluating the first level or second level of folders.
B: The backup volume gets deleted. It will cleanup all the empty intermediate folders down to the root of the backupstore.
A: The now deleted folder will lead to an error since the list operation assumes the folder should still be present.

**Comment by khushboo-rancher** [comment] 2020-07-20 16:57
Validation - **Passed**

Integration tests related to backup deletion are not failing from last few runs.

**Closed by khushboo-rancher** 2020-07-20 16:57 UTC
Labels: area/engine, area/test, bug, reproduce/rare
