### ISSUE TITLE
[BUG] Pod creation fails due to the failed volume mounting 

### ISSUE THREAD

**Issue by rajesh-u** [longhorn/longhorn#2880] opened 2021-08-13 10:30 UTC
**Pod creation fails due to the failed mounting of volumes**

**Steps to reproduce the behavior:**
1. Tried installing a pod using helm chart
2. the pod with pv requirements fail to get initialized as there are error in attaching volumes to it.

**Expected behavior**
Volumes should be mounted and pods get initialized

**Log**
*mariadb pod description*
Events:
  Type     Reason              Age                      From                     Message
  ----     ------              ----                     ----                     -------
  Warning  FailedMount         57m (x12 over 3h40m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[datadir import import-mariadb-cm import-users default-token-mf5sr cluster-cm importdb]: timed out waiting for the condition
  Warning  FailedMount         36m (x10 over 3h33m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[default-token-mf5sr cluster-cm importdb datadir import import-mariadb-cm import-users]: timed out waiting for the condition
  Warning  FailedMount         21m (x10 over 3h17m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[import-mariadb-cm import-users default-token-mf5sr cluster-cm importdb datadir import]: timed out waiting for the condition
  Warning  FailedMount         16m (x14 over 3h37m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[cluster-cm importdb datadir import import-mariadb-cm import-users default-token-mf5sr]: timed out waiting for the condition
  Warning  FailedMount         7m25s (x19 over 3h35m)   kubelet                  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[import import-mariadb-cm import-users default-token-mf5sr cluster-cm importdb datadir]: timed out waiting for the condition
  Warning  FailedAttachVolume  2m31s (x117 over 3h44m)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-f3b70eaa-5396-401f-bfd3-f5d447193087" : rpc error: code = NotFound desc = ControllerPublishVolume: the node dawn-cc-wrkr6 does not exist
  Warning  FailedMount         38s (x14 over 3h31m)     kubelet                  Unable to attach or mount volumes: unmounted volumes=[datadir], unattached volumes=[import-users default-token-mf5sr cluster-cm importdb datadir import import-mariadb-cm]: timed out waiting for the condition

**Longhorn instance manager [log*]**
[longhorn-manager.log](https://github.com/longhorn/longhorn/files/6981727/longhorn-manager.log)

**Environment:**
 - Longhorn version: 1.1.2
 - Installation method: Helm3
 - Kubernetes distro and version: RKE -v2.5.1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 6
 - Node config
   - OS type and version: rhel-7.8
   - CPU per node: 8 per control nodes and 16 per worker node
   - Memory per node: 32gb RAM per control node /  64gb RAM per worker node
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes:
 - Underlying Infrastructure: VMWare/KVM
 - Number of Longhorn volumes in the cluster: 4

**Comment by c3y1huang** [comment] 2021-08-24 02:45
@rajesh-u we cannot see the volume with the longhorn-manager.log provided.
You can provide the support bundle with this issue or mail it to longhorn-support-bundle@suse.com .

BTW, does this also happens to the pod not deployed by helm chart?

**Comment by PatrickHuetter** [comment] 2021-08-24 12:34
I can confirm this issue. Mostly same setup but using current Ubuntu LTS. For me only one node in the whole cluster has this problem. Scheduling pods on different nodes works with mounting. I couldn't figure out why this is happening on the specific node. Restart also didn't help. The nodes should be 100% identically since I setupped them from the same base VM image with terraform. 

I'm thinking about re-installing the specific node since I can't figure out the problem.

**Comment by rajesh-u** [comment] 2021-08-31 05:19
@c3y1huang Has deleted the setup. Will provide the logs ASAP.

**Comment by rajesh-u** [comment] 2021-09-01 10:13
[longhorn-support-bundle_5dd994bd-4c16-49d7-8b60-1370561b0877_2021-09-01T10-11-30Z.zip](https://github.com/longhorn/longhorn/files/7090237/longhorn-support-bundle_5dd994bd-4c16-49d7-8b60-1370561b0877_2021-09-01T10-11-30Z.zip)
PFA the support bundle zip file

**Comment by c3y1huang** [comment] 2021-09-01 10:52
Thank you @rajesh-u , we will look into it.

**Comment by c3y1huang** [comment] 2021-09-03 05:17
@rajesh-u is the issue reproducible on your newly setup cluster? From the [support-bundle](https://github.com/longhorn/longhorn/issues/2880#issuecomment-910140732) I cannot see the FailedMount error.

**Comment by jenting** [comment] 2021-11-05 03:54
Out of activity, close this issue. Feel free to reopen it when you could provide more information on this one.

**Closed** 2021-12-21 07:35 UTC
Labels: kind/bug
