### ISSUE TITLE
Mark nodes with/without certain label as disabled/enabled by default

### ISSUE THREAD

**Issue by paalkr** [longhorn/longhorn#583] opened 2019-05-31 06:24 UTC
Ref: https://github.com/rancher/longhorn/issues/574

Only some of the nodes in my cluster has disks attached that is intended for Longhorn. So I would like to store Longhorn data only on nodes that has a specific label. All other nodes should by default be marked as disabled. 

![image](https://user-images.githubusercontent.com/9726307/58685890-7b0b4e80-837d-11e9-81db-bd69f788c786.png)

**Comment by yasker** [comment] 2019-07-08 20:02
@ttpcodes 

`Create Default Disk` setting can be enhanced to address this. We can `Create Default Disk Only With Annotation` only when a certain label annotation has been found in the new node. If the setting is empty, then we will create a default disk for every new node. Otherwise, we will check for the existence of the annotation. We can suggest using `longhorn: storage-node` as the annotation. It still only applies to the new nodes.

**Comment by ttpcodes** [comment] 2019-07-08 20:37
Per discussion with @yasker, it seems like `Create Default Disk` should still be a `boolean` setting, but modified so that instead of switching between enabling and disabling default `Disk` creation, it should switch between creation on all `Nodes` versus creation on `Nodes` that are labeled with a certain label that we will decide on.

**Comment by yasker** [comment] 2019-07-08 20:47
@ttpcodes We want to use annotations in this case instead of labels since we didn't expect users to frequently search for the annotation. And it's a one-time operation, happens only when adding the node.

**Comment by paalkr** [comment] 2019-07-08 22:57
I would strongly encourage to follow @ttpcodes suggestion to use node labels and not node annotations to determine if a node is suitable for a longhorn disk or not. The common way in Kubernetes is to specify node capabilities using labels, not annotations. Annotations is usually describing arbitrary node metadata, not node capabilities.

**Comment by yasker** [comment] 2019-07-08 23:20
@paalkr Fair enough. Labels are more likely used for classification in Kubernetes.

Though what if the user removed a label from the node? I don't think we can remove the default disk automatically.

**Comment by paalkr** [comment] 2019-07-08 23:32
Will that be any different then if a user removed an annotation? Never the less,
my intention when creating this ticket was to address the one shot process that executes once when a new node is added to a cluster. I did not have in mind that changing a node label (or annotation for that matter) at a later time would have any impact on the node status in Longhorn.

**Comment by yasker** [comment] 2019-07-08 23:42
@paalkr Yeah, I was talking about another thing, not related to use label or annotation. We can use the label.

How about this:

Setting option: `Create default disk only with labeled node`.
1. If it's false, we will create a default disk specified by `Default Data Path` and enable scheduling on all new nodes.

2. if it's true, we will create a default disk and enable scheduling on the node only when:
    1. the node is labeled `longhorn: storage-node`, and
    2. the node has no disk available
Other nodes will have no default disk created and scheduling disabled by default when added.

**Comment by paalkr** [comment] 2019-07-08 23:49
Sounds reasonable. I assume that the ability to define a custom default data path (https://github.com/longhorn/longhorn/issues/582) will apply in both scenarios?

**Comment by yasker** [comment] 2019-07-08 23:54
@paalkr Yeah, it will work with #582

**Comment by paalkr** [comment] 2019-07-09 00:51
So how is these settings specified during longhorn system deployment? In a configmap?

**Comment by yasker** [comment] 2019-07-09 01:19
@paalkr That's a good question. We didn't support set up Longhorn settings before the deployment, but it can be done. I've filed #623 for this.

**Comment by paalkr** [comment] 2019-07-09 01:29
Excellent, thanks! It makes perfect sense to be able to define settings related to default data path (https://github.com/longhorn/longhorn/issues/582) and node labels to automatically enable/disable scheduling, during the initial deployment.

**Comment by meldafrawi** [comment] 2019-07-11 20:51
Steps to test:
  - Create a k8s cluster (1 controller, 1 worker)
  - Install Longhorn
  - On settings page, Check `Create Default Disk on Labeled Nodes` = true, Click `Save`
  - Add two more workers to k8s cluster, one of them labeled with `node.longhorn.io/role: storage`

I expected that after the nodes gets added to the cluster, only the node labeled will be `Schedulable` on Longhorn UI, but both of them are `Disabled`.

**Comment by yasker** [comment] 2019-07-12 19:43
@ttpcodes ^^ I think we haven't updated the label in the setting usage yet.

**Comment by yasker** [comment] 2019-07-12 21:16
@meldafrawi Fix merged.

**Comment by meldafrawi** [comment] 2019-07-12 21:51
Validation FAILED.

@yasker @ttpcodes ^

**Comment by yasker** [comment] 2019-07-12 21:53
@meldafrawi what's your reproduce step?

**Comment by meldafrawi** [comment] 2019-07-12 21:55
Steps to test:

- Create a k8s cluster (1 controller, 1 worker)
- Install Longhorn
- On settings page, Check `Create Default Disk on Labeled Nodes`  =  true, Click Save
- Add two more workers to k8s cluster, one of them labeled with `node.longhorn.io/role: storage`

**Comment by yasker** [comment] 2019-07-12 21:56
@meldafrawi The instruction for setting should have changed.

**Comment by meldafrawi** [comment] 2019-07-12 22:05
Validation PASSED.

Steps to test:

- Create a k8s cluster (1 controller, 1 worker)
- Install Longhorn
- On settings page, Check `Create Default Disk on Labeled Nodes`  =  true, Click Save
- Add two more workers to k8s cluster, one of them labeled with `node.longhorn.io/create-default-disk: true`
_Expected Result:_ Only the node labeld  `node.longhorn.io/create-default-disk: true` get default disk create and become **Schedulable**, the other node is **Disabled**.

**Closed** 2019-07-12 22:05 UTC
Labels: area/manager, enhancement
