### ISSUE TITLE
[BUG] Close WS if data not used on page

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#2593] opened 2021-05-13 09:57 UTC
**Describe the bug**
Some WS is only used on specific pages, for example, event log at the dashboard. Visiting other pages loads all WS seems unnecessary.

**To Reproduce**
`n/a`

**Expected behavior**
Only keep necessary WS open for what data is used on the page.

**Log**
`n/a`

**Environment:**
`n/a`

**Additional context**
https://github.com/longhorn/longhorn/issues/2372

**Comment by c3y1huang** [comment] 2021-05-13 10:35
cc @smallteeths

**Comment by smallteeths** [comment] 2021-05-14 01:08
ok @c3y1huang

**Comment by smallteeths** [comment] 2021-05-24 10:16
![Jietu20210524-180019](https://user-images.githubusercontent.com/27733391/119331946-836f9900-bcba-11eb-8909-58b3aa8f31c9.jpg)

Now all pages will open and close ws on demand, the only thing that needs to be confirmed is the event ws. Now the default is to close this ws. Only when the user clicks the switch will ws be turned on.

Would you please check this. @c3y1huang thanks

image: `wangsiye/longhorn-ui:381c5aa`

**Comment by innobead** [comment] 2021-05-24 11:30
I don't think this UI change is what we want, even the workaround. We need to deal with the root cause first. @c3y1huang please work with @smallteeths for the following discussion. Thanks.

**Comment by smallteeths** [comment] 2021-05-25 01:22
The ui change does not fundamentally solve the problem of excessive traffic, but this change should have some effect. When the user is not on the volume page, the traffic will be less than before (the volume page is because it depends on other data. , So it not reduce the traffic too much than before).

I feel that the real solution is
 (1) Pagination 
 (2) push empty data ([]) when the data is not updated. 
 
Among them (2) has been optimized, as for (1) does it need to wait for the api to be refactored before it can be realized.

**Comment by smallteeths** [comment] 2021-05-25 05:53
![Jietu20210525-134306](https://user-images.githubusercontent.com/27733391/119445666-c2a3f580-bd5f-11eb-8020-64a5367335e8.jpg)
![Jietu20210525-134338](https://user-images.githubusercontent.com/27733391/119445672-c3d52280-bd5f-11eb-9d2f-c6b7809c786d.jpg)

After discussing with @c3y1huang. The ui modified that each page will only have the ws that it requires...Not like before we have all 6 ws opened for every page.

**Comment by innobead** [comment] 2021-05-25 07:00
> The ui change does not fundamentally solve the problem of excessive traffic, but this change should have some effect. When the user is not on the volume page, the traffic will be less than before (the volume page is because it depends on other data. , So it not reduce the traffic too much than before).
> 
> I feel that the real solution is
> (1) Pagination

For pagination, probably it's related to #2183 

cc @jenting

**Comment by jenting** [comment] 2021-05-25 07:02
> After discussing with @c3y1huang. The ui modified that each page will only have the ws that it requires...Not like before we have all 6 ws opened for every page.

+1

**Comment by kaxing** [comment] 2021-06-09 10:38
Verifying on environment with following versions:
- Rancher Server 2.5.8
- Longhorn Image: master (20210609) + longhorn-ui: wangsiye/longhorn-ui:381c5aa

By observing the WebSocket connections it will open and close while switching to different pages,
also the indicator match with the connection record.[0]

[0]Attaching networking log for reference: [Lonhorn-UI-WS-change.har.tar.gz](https://github.com/longhorn/longhorn/files/6623065/Lonhorn-UI-WS-change.har.tar.gz)
 (recording with Chrome Dev Tool)

**Comment by kaxing** [comment] 2021-06-11 09:04
Validation - **Passed**

Check again with Longhorn `v1.1.2-head` + longhorn-ui: `wangsiye/longhorn-ui:381c5aa`

**Closed by kaxing** 2021-06-11 09:05 UTC
Labels: area/performance, area/ui, backport-needed, kind/bug, priority/1
