### ISSUE TITLE
[BUG] Degraded v2 volume write error after replica rebuild

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#9166] opened 2024-08-02 10:06 UTC
## Describe the bug

Delete 1 replica of a degrade V2 volume,  after replica rebuild complete, write data in pod mount point, the wirte process will never complete and workload pod restarted, data in mount point disappered.

longhorn-manager
```log
2024-08-02T09:50:44.040674525Z time="2024-08-02T09:50:44Z" level=info msg="Deleted pod test-deployment-555bb6db67-srbnv so that Kubernetes will handle remounting volume pvc-1ad26bcc-9072-48e3-9c56-e0800807e707" func="controller.(*KubernetesPodController).handlePodDeletionIfVolumeRequestRemount" file="kubernetes_pod_controller.go:516" controller=longhorn-kubernetes-pod node=ip-10-0-1-80
```

data write hang
```bash
> k exec -it test-deployment-555bb6db67-srbnv -- /bin/bash
root@test-deployment-555bb6db67-srbnv:/# dd if=dev/urandom of=/mnt/data/1 bs=1M count=200 && sync
200+0 records in
200+0 records out
209715200 bytes (210 MB, 200 MiB) copied, 3.54033 s, 59.2 MB/s
root@test-deployment-555bb6db67-srbnv:/# echo test >> /mnt/data/2
root@test-deployment-555bb6db67-srbnv:/# echo test >> /mnt/data/2
bash: echo: write error: Read-only file system
root@test-deployment-555bb6db67-srbnv:/# echo test >> /mnt/data/2
bash: /mnt/data/2: Read-only file system
root@test-deployment-555bb6db67-srbnv:/# echo test >> /mnt/data/2
bash: /mnt/data/2: Read-only file system
root@test-deployment-555bb6db67-srbnv:/# echo test >> /mnt/data/2
bash: /mnt/data/2: Read-only file system
root@test-deployment-555bb6db67-srbnv:/# echo test >> /mnt/data/2command terminated with exit code 13
```

deployment pod restarted
```bash
> k get pods -w
NAME                               READY   STATUS    RESTARTS   AGE
test-deployment-555bb6db67-srbnv   1/1     Running   0          8m20s
test-deployment-555bb6db67-srbnv   1/1     Terminating   0          10m
test-deployment-555bb6db67-7wqw2   0/1     Pending       0          0s
test-deployment-555bb6db67-7wqw2   0/1     Pending       0          0s
test-deployment-555bb6db67-7wqw2   0/1     ContainerCreating   0          0s
test-deployment-555bb6db67-srbnv   0/1     Terminating         0          10m
test-deployment-555bb6db67-srbnv   0/1     Terminating         0          10m
test-deployment-555bb6db67-srbnv   0/1     Terminating         0          10m
test-deployment-555bb6db67-srbnv   0/1     Terminating         0          10m
test-deployment-555bb6db67-7wqw2   1/1     Running             0          21s
```

data gone after pod running
```bash
> k exec -it test-deployment-555bb6db67-7wqw2 -- /bin/bash
root@test-deployment-555bb6db67-7wqw2:/# ls /mnt/data
lost+found
```

## To Reproduce

1. In a 3 nodes cluser, enable v2 data engine.
2. Add 2 block disks
3. Create a 3 replicas v2 volume, attach it with workload(deployment)
4. After pod running, volume degraded
5. Write data into mount point
6. Delete 1 replica, wait the rebuild complete
7. Write data into mount point
8. Repeat several times of step 6 and step 7.
9.  Eentually the wirte process in step 7 will not complete, deployment pod restarted, after pod running, in pod mount point, data disappered.  

## Expected behavior

After the degraded v2 volume replica rebuild complete, write data into volume should work

## Support bundle for troubleshooting

[supportbundle_4ed73a8c-f348-4ac0-95a8-d7a175e5af53_2024-08-02T10-01-54Z.zip](https://github.com/user-attachments/files/16468961/supportbundle_4ed73a8c-f348-4ac0-95a8-d7a175e5af53_2024-08-02T10-01-54Z.zip)

## Environment

 - Longhorn version:  v1.7.0-rc3
 - Impacted volume (PV): pvc-1ad26bcc-9072-48e3-9c56-e0800807e707
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.30.0+k3s1
 - Node config
   - OS type and version: SLES 15-SP6 (AWS EC2 t2.xlarge)
   - Kernel version: 6.4.0-150600.23.7-default
  
## Additional context

N/A

**Comment by shuo-wu** [comment] 2024-08-06 00:05
I tried this multiple times and only encountered a **similar** (not the same) case once:

When I try to write data into the filesystem backed by a SPDK volume, it gets stuck for 1-3 minutes. 
The `dmesg` shows:
```
[197640.843661] nvme nvme1: rescanning namespaces.
[197643.570919] nvme nvme1: starting error recovery
[197643.571194] nvme nvme1: Reconnecting in 10 seconds...
[197643.652443] nvme nvme1: Removing ctrl: NQN "nqn.2023-01.io.longhorn.spdk:vol-e-0"
[197643.652632] nvme nvme1: Property Set error: 880, offset 0x14
[197643.679664] nvme nvme1: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 10.42.177.206:20006
[197643.680549] nvme nvme1: Removing ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery"
[197643.718312] nvme nvme1: creating 8 I/O queues.
[197643.797452] nvme nvme1: mapped 8/0/0 default/read/poll queues.
[197643.799135] nvme nvme1: new ctrl: NQN "nqn.2023-01.io.longhorn.spdk:vol-e-0", addr 10.42.177.206:20006
[197643.939832] nvme nvme1: rescanning namespaces.
[197651.204690] block nvme0n2: no available path - failing I/O
[197651.271644] block nvme0n2: no available path - failing I/O
[197651.271659] block nvme0n2: no available path - failing I/O
[197651.271662] block nvme0n2: no available path - failing I/O
[197651.271981] block nvme0n2: no available path - failing I/O
[197651.271993] block nvme0n2: no available path - failing I/O
[197651.271996] Buffer I/O error on dev dm-0, logical block 262144, lost sync page write
[197651.272976] JBD2: Error -5 detected when updating journal superblock for dm-0-8.
[197651.274822] Aborting journal on device dm-0-8.
[197651.275708] block nvme0n2: no available path - failing I/O
[197651.275714] Buffer I/O error on dev dm-0, logical block 262144, lost sync page write
[197651.276664] JBD2: Error -5 detected when updating journal superblock for dm-0-8.
[197651.277617] EXT4-fs error (device dm-0): ext4_put_super:1204: comm umount: Couldn't clean up the journal
[197651.278697] block nvme0n2: no available path - failing I/O
[197651.278702] Buffer I/O error on dev dm-0, logical block 0, lost sync page write
[197651.280236] EXT4-fs (dm-0): I/O error while writing superblock
[197651.283421] EXT4-fs (dm-0): Remounting filesystem read-only
[197740.647919] nvme nvme1: starting error recovery
[197740.648112] nvme nvme1: Reconnecting in 10 seconds...
[197740.730599] nvme nvme1: Removing ctrl: NQN "nqn.2023-01.io.longhorn.spdk:vol-e-0"
[197740.730873] nvme nvme1: Property Set error: 880, offset 0x14
[197740.754636] nvme nvme0: new ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery", addr 10.42.177.206:20006
[197740.756006] nvme nvme0: Removing ctrl: NQN "nqn.2014-08.org.nvmexpress.discovery"
[197740.795185] nvme nvme0: creating 8 I/O queues.
[197740.873156] nvme nvme0: mapped 8/0/0 default/read/poll queues.
[197740.874676] nvme nvme0: new ctrl: NQN "nqn.2023-01.io.longhorn.spdk:vol-e-0", addr 10.42.177.206:20006
[197862.094238] EXT4-fs (dm-0): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
```
But after that, everything worked as usual. The write finally succeeded. And I didn't do anything like remount for this filesystem.

**Comment by chriscchien** [comment] 2024-08-06 02:41
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vol1
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  # volumeMode: Block
  storageClassName: longhorn-v2-data-engine
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-deployment
  namespace: default
  labels:
    name: test-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      name: test-deployment
  template:
    metadata:
      labels:
        name: test-deployment
    spec:
      containers:
        - name: test-deployment
          image: ubuntu:20.04
          stdin: true
          stdinOnce: false
          tty: true
          volumeMounts:
            - name: vol1
              mountPath: /mnt/data
      volumes:
        - name: vol1
          persistentVolumeClaim:
            claimName: vol1
```

**Comment by yangchiu** [comment] 2024-08-06 07:52
Reproduced in https://ci.longhorn.io/job/private/job/longhorn-e2e-test/1021/console with longhorn-tests [PR #2048](https://github.com/longhorn/longhorn-tests/pull/2048).

Initially the test case writes `2GB` data to the workload pod in `/data/data.txt`, and stores the checksum as `2eb72d04b26aa0fd05405cdd4197e38d`:

```
Writing 2048 MB random data to pod e2e-test-deployment-0-b5dd68559-bvsq5 file data.txt
Waiting for pod e2e-test-deployment-0-b5dd68559-bvsq5 status Running, current status Running (0) ...
Storing pod e2e-test-deployment-0-b5dd68559-bvsq5 file data.txt checksum = 2eb72d04b26aa0fd05405cdd4197e38d
```

After a few test runs, workload pod restart is observed:

```
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (136) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (137) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (138) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (139) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (140) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (141) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (142) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (143) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (144) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (145) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (146) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (147) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (148) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (149) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (150) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (151) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (152) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (153) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (154) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (155) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (156) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (157) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (158) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (159) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (160) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (161) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (162) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (163) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (164) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (165) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (166) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (167) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (168) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (169) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (170) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (171) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (172) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-bvsq5', 'e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (173) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82', 'e2e-test-deployment-0-b5dd68559-bvsq5'] stable, retry (174) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (175) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (176) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (177) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (178) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (179) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (180) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (181) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (182) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (183) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (184) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (185) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (186) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (187) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (188) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (189) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (190) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (191) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (192) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (193) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (194) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (195) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (196) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (197) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (198) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (199) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (200) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (201) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (202) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (203) ...
Waiting for e2e-test-deployment-0 pods ['e2e-test-deployment-0-b5dd68559-fst82'] stable, retry (204) ...
```

Enter the new workload pod and check the checksum of the `/data/data.txt` file. The file is missing:

```
Checking checksum for file data.txt in pod e2e-test-deployment-0-b5dd68559-fst82
Waiting for pod e2e-test-deployment-0-b5dd68559-fst82 status Running, current status Running (0) ...
Checked e2e-test-deployment-0-b5dd68559-fst82 file data.txt checksum:         Got /data/data.txt checksum = md5sum: can't open '/data/data.txt': No such file or directory
 Expected checksum = 2eb72d04b26aa0fd05405cdd4197e38d

Checked e2e-test-deployment-0-b5dd68559-fst82 file data.txt checksum failed.         Got /data/data.txt checksum = md5sum: can't open '/data/data.txt': No such file or directory
 Expected checksum = 2eb72d04b26aa0fd05405cdd4197e38d
```

[supportbundle_ae0a4887-ac76-45e1-a69a-f8ecdc36423a_2024-08-06T07-51-13Z.zip](https://github.com/user-attachments/files/16507126/supportbundle_ae0a4887-ac76-45e1-a69a-f8ecdc36423a_2024-08-06T07-51-13Z.zip)

**Comment by shuo-wu** [comment] 2024-08-07 23:12
There are some clues in the support bundle Yang Chiu provides. But due to the unexpected instance manager pod restart, some important logs are missed.

Here is the analysis for the beginning of the test, which is abnormal:
1. At `2024-08-06T07:27:12`
        1. Node (end with) `172` Scheduling is disabled
        2. Replica `pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-0a234c12` owned by node `172` is being removed. This replica **should be an unscheduled one but somehow there is a schedule log**:
        ```        
        2024-08-06T07:26:57.316008291Z time="2024-08-06T07:26:57Z" level=info msg="Schedule replica to node ip-10-0-1-164" func="scheduler.(*ReplicaScheduler).scheduleReplicaToDisk" file="replica_scheduler.go:535" dataDirectoryName=pvc-33bcb869-631f-4cca-8473-655ae60085d3-d9db75e8 disk=444d0269-ae48-4281-92c5-d4f7bb51f048 diskPath=/dev/xvdh replica=pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-0a234c12
        ```
        3. Replica `pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-4ec4dd34` scheduled on node `157` is being removed
        4. A new replica `pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-bbe2f47b` scheduled on node `157` is launched. But somehow it's **directly marked as mode RW**. There is **no log rebuilding start/finish log** `Start rebuilding replica ...` `Replica %v with Address %v has been rebuilt for volume %v`. And the IM pod log is missed since the pod is restarted at `07:43:19`.
        ```
        // These logs indicates that the replica is already mode RW
        2024-08-06T07:28:03.390934291Z time="2024-08-06T07:28:03Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"pvc-33bcb869-631f-4cca-8473-655ae60085d3-e-0\", UID:\"1bfb25fd-8ee2-4a7f-8b31-8de8ecd66596\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"2544\", FieldPath:\"\"}): type: 'Normal' reason: 'Rebuilt' Detected replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-bbe2f47b (10.42.2.15:20001) has been rebuilt" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:377"
        2024-08-06T07:27:58.920195180Z time="2024-08-06T07:27:58Z" level=info msg="Replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-bbe2f47b address 10.42.2.15:20001 has been added to the engine already" func="controller.(*EngineController).startRebuilding" file="engine_controller.go:1835" controller=longhorn-engine node=ip-10-0-1-172
        ```
        5. Replica `pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-61a4784a` scheduled on node `164` is being removed **but gets rejected since it's somehow the last RW replica**.
        ```
        2024-08-06T07:26:57.346872079Z time="2024-08-06T07:26:57Z" level=info msg="Schedule replica to node ip-10-0-1-164" func="scheduler.(*ReplicaScheduler).scheduleReplicaToDisk" file="replica_scheduler.go:535" dataDirectoryName=pvc-33bcb869-631f-4cca-8473-655ae60085d3-0522429f disk=444d0269-ae48-4281-92c5-d4f7bb51f048 diskPath=/dev/xvdh replica=pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-61a4784a
        2024-08-06T07:27:57.927507869Z time="2024-08-06T07:27:57Z" level=warning msg="Rejected operation: Request (user: system:serviceaccount:default:longhorn-test-service-account, longhorn.io/v1beta2, Kind=Replica, namespace: longhorn-system, name: pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-61a4784a, operation: DELETE)" func="admission.(*Handler).admit" file="admission.go:106" error="cannot delete replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-61a4784a because volume pvc-33bcb869-631f-4cca-8473-655ae60085d3 only has one available replica" service=admissionWebhook
        ```
2. At `2024-08-06T07:28:04`
        1. Replica `pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-61a4784a` deletion mentioned above Succeeds.
        2. A new replica `pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-0f238fe3` scheduled on node `164` is launched. I don't know why And the same, somehow it directly becomes **mode RW without rebuilding logs**. And the IM pod log is missed.
        ```
        2024-08-06T07:28:04.119683326Z time="2024-08-06T07:28:04Z" level=info msg="Schedule replica to node ip-10-0-1-164" func="scheduler.(*ReplicaScheduler).scheduleReplicaToDisk" file="replica_scheduler.go:535" dataDirectoryName=pvc-33bcb869-631f-4cca-8473-655ae60085d3-6ba3eb57 disk=444d0269-ae48-4281-92c5-d4f7bb51f048 diskPath=/dev/xvdh replica=pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-0f238fe3
        ......
        2024-08-06T07:28:04.690837192Z time="2024-08-06T07:28:04Z" level=info msg="Replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-0f238fe3 address 10.42.1.16:20001 has been added to the engine already" func="controller.(*EngineController).startRebuilding" file="engine_controller.go:1835" controller=longhorn-engine node=ip-10-0-1-172
        2024-08-06T07:28:08.404621569Z time="2024-08-06T07:28:08Z" level=error msg="Failed to check if replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-0f238fe3 transitioned to mode RW after it was last healthy" func="controller.(*VolumeController).ReconcileEngineReplicaState" file="volume_controller.go:752" accessMode=rwo controller=longhorn-volume currentEngine=pvc-33bcb869-631f-4cca-8473-655ae60085d3-e-0 frontend=blockdev migratable=false node=ip-10-0-1-172 owner=ip-10-0-1-172 state=attached volume=pvc-33bcb869-631f-4cca-8473-655ae60085d3
        ```
                
Besides, there are tons of weird error logs printed by the engine monitor thread, which should fail the engine mode map update but actually NO:
```
2024-08-06T07:28:18.397894212Z E0806 07:28:18.397739       1 engine_controller.go:879] failed to update status for engine pvc-33bcb869-631f-4cca-8473-655ae60085d3-e-0: proxyServer=10.42.3.15:8501 destination=10.42.3.15:20001: failed to get backup restore status: rpc error: code = Internal desc = failed to get restore status: rpc error: code = Internal desc = failed to get restore status for engine pvc-33bcb869-631f-4cca-8473-655ae60085d3-e-0: rpc error: code = NotFound desc = cannot find replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-4ec4dd34
2024-08-06T07:28:23.397607877Z E0806 07:28:23.397477       1 engine_controller.go:879] failed to update status for engine pvc-33bcb869-631f-4cca-8473-655ae60085d3-e-0: proxyServer=10.42.3.15:8501 destination=10.42.3.15:20001: failed to get backup restore status: rpc error: code = Internal desc = failed to get restore status: rpc error: code = Internal desc = failed to get restore status for engine pvc-33bcb869-631f-4cca-8473-655ae60085d3-e-0: rpc error: code = NotFound desc = cannot find replica pvc-33bcb869-631f-4cca-8473-655ae60085d3-r-4ec4dd34
```

**Comment by shuo-wu** [comment] 2024-08-08 00:44
I suddenly reproduced it once. I cannot find any noticeable logs in the instance manager so far. Will continue checking it.

**Comment by derekbit** [comment] 2024-08-08 07:52
Initially, the degraded volume has 2 running replicas (A and B) and 1 stopped replica (C).
- Replica A: running
- Replica B: running
- Replica C: stopped

After deleting the running Replica A, the stopped Replica C is immediately scheduled to a node to replace the deleted Replica A, and then Replica C becomes running.
- Replica B: running
- Replica C: running

Meanwhile, the [verify()](https://github.com/longhorn/longhorn-spdk-engine/blob/main/pkg/spdk/engine.go#L646-L650) function in the SPDK engine cannot find Replica A and consistently returns a `NotFound` error. However, this error is ignored, and the replica remains in the RW state. As a result, the control plane cannot rebuild the replica because the data plane considers it healthy.

This situation can lead to a deletion operation mistakenly applied to the healthy replica (the other one replica is running but without any data).

Therefore, the solution is to mark the NotFound replica as ERROR in the data plane. This will trigger the data plane to clean up the failed replica and initiate the rebuilding process.

cc @shuo-wu @innobead

**Comment by shuo-wu** [comment] 2024-08-08 08:30
@derekbit Great analysis! But there comes one more question: Why is the newly created replica considered as a RW one without rebuilding? In your example, Replica C should not be in the engine cached maps.

**Comment by derekbit** [comment] 2024-08-08 08:54
After deleting a replica resource, the replica (logical volume) is deleted, but the engine’s verify() function doesn’t mark it as an ERROR. The stopped replica is then scheduled and assigned the same port as the deleted replica, resulting in the **same replica address**.

Before rebuilding a replica, the engine controller retrieves the replica list (code reference). However, the returned list is in the format `map[URL]Replica`, causing the engine controller to mistakenly believe the rebuilt replica is already present (similar to the behavior in v1 volumes).

As a result, the new replica cannot be rebuilt and is incorrectly regarded as a rebuilt replica.

**Comment by derekbit** [comment] 2024-08-08 08:54
> @derekbit Great analysis! But there comes one more question: Why is the newly created replica considered as a RW one without rebuilding? In your example, Replica C should not be in the engine cached maps.

After deleting a replica resource, the replica (logical volume) is deleted, but the engine’s verify() function doesn’t mark it as an ERROR. The stopped replica is then scheduled and assigned the same port as the deleted replica, resulting in the **same replica address**.

Before rebuilding a replica, the engine controller retrieves the replica list (code reference). However, the returned list is in the format `map[URL]Replica`, causing the engine controller to mistakenly believe the rebuilt replica is already present (similar to the behavior in v1 volumes).

As a result, the new replica cannot be rebuilt and is incorrectly regarded as a rebuilt replica.

**Comment by shuo-wu** [comment] 2024-08-08 09:08
Got it! The instance manager proxy function `ReplicaList` discards replica name related info and returns `map[ReplicaURL]ReplicaMode` instead. This kind of parsing totally confuses the upper caller.

**Comment by derekbit** [comment] 2024-08-08 09:12
> Got it! The instance manager proxy function `ReplicaList` discards replica name related info and returns `map[ReplicaURL]ReplicaMode` instead. This kind of parsing totally confuses the upper caller.

Yeah, I also suspect if the confusion can result in some bugs in v1 volume such as data missing and all replica missing.

**Comment by shuo-wu** [comment] 2024-08-08 09:16
Is there a plan to update that API?

**Comment by derekbit** [comment] 2024-08-08 09:20
> Is there a plan to update that API?

I think yes in v1.8 or v1.9. We can handle it with v1 data engine together. v1 data engine has the similar issue https://github.com/longhorn/longhorn/issues/9216.

We can mark the new replica as ERROR first https://github.com/longhorn/longhorn-spdk-engine/pull/195.

**Comment by derekbit** [comment] 2024-08-09 08:56
## Pre Ready-For-Testing Checklist
* [ ] Where is the reproduce steps/test steps documented?
The reproduce steps/test steps are at:

* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at

[fix(engine): mark replica as ERROR if it is not found by derekbit · Pull Request #195 · longhorn/longhorn-spdk-engine (github.com)](https://github.com/longhorn/longhorn-spdk-engine/pull/195)

* [ ] Which areas/issues this PR might have potential impacts on?
Area: v2 volume, online rebuilding
Issues

**Comment by chriscchien** [comment] 2024-08-12 09:16
Verified **pass** on longhorn master(longhorn-instance-manager `9f8c92`), v1.7.x(longhorn-instance-manager `5f3873`)

Steps:
1. In a 3 nodes cluser, enable v2 data engine.
2. Add 2 block disks
3. Create a 3 replicas v2 volume, attach it with workload(deployment)
4. After pod running, volume degraded
5. Write data into mount point
6. Delete 1 replica, wait the rebuild complete
7. Write data into mount point
8. Repeat several times of step 6 and step 7 `50` times
9. Afert step 8 complete, data read and write worked properly

Regarding the detach -> attaching loop issue mentioned in previous [comment](https://github.com/longhorn/longhorn/issues/9166#issuecomment-2283043601), the symptom is already recorded in https://github.com/longhorn/longhorn/issues/9216. Since the bug of this ticket has already been fixed and verified, I would like to close this ticket if there are no other concerns. Thank you.

cc @innobead @derekbit

**Closed** 2024-08-13 01:12 UTC
Labels: kind/bug, severity/1, reproduce/always, priority/0, require/auto-e2e-test, area/volume-replica-scheduling, area/v2-data-engine, area/resilience, require/qa-review-coverage, require/backport
