### ISSUE TITLE
[BUG] User is not able to create backups from volume details page

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1300] opened 2020-05-06 22:13 UTC
**Describe the bug**
User is not able to create backups from volume details page

**To Reproduce**

- Create a volume, attach to a node, write data in the volume
- Go to volume details page
- Click on Create Backup.
- The page is stuck in loading state
- Error in console

```
Uncaught (in promise) TypeError: Cannot read property 'replace' of undefined
    at main.692bd993.async.js?cf2fc1043c6812f21d63:40
    at C (main.692bd993.async.js?cf2fc1043c6812f21d63:40)
    at main.692bd993.async.js?cf2fc1043c6812f21d63:40
    at l (main.692bd993.async.js?cf2fc1043c6812f21d63:21)
    at Generator._invoke (main.692bd993.async.js?cf2fc1043c6812f21d63:21)
    at Generator.forEach.e.<computed> [as next] (main.692bd993.async.js?cf2fc1043c6812f21d63:21)
    at a (main.692bd993.async.js?cf2fc1043c6812f21d63:7)
    at c (main.692bd993.async.js?cf2fc1043c6812f21d63:7)
    at main.692bd993.async.js?cf2fc1043c6812f21d63:7
    at new Promise (<anonymous>)
```
<img width="1677" alt="Screen Shot 2020-05-06 at 3 12 37 PM" src="https://user-images.githubusercontent.com/26032343/81233693-0f2d5f00-8fac-11ea-989a-79252acf5011.png">

**Expected behavior**
User should be able to take backups

**Environment:**
 - Longhorn version: master-05/06/2020

**Comment by yasker** [comment] 2020-05-07 02:23
Sounds like a duplicate of https://github.com/longhorn/longhorn/issues/1297 . @smallteeths can you confirm?

**Comment by smallteeths** [comment] 2020-05-08 03:15
Yes, it has been fixed in issues1297 @yasker

**Comment by sowmyav27** [comment] 2020-05-08 19:04
Verified using ui image: `wangsiye/longhorn-ui:c45d726`

**Steps:**

- Create a volume, attach to a node, write data in the volume
- Go to volume details page
- Click on Create Backup.
- User is able to create backups

**Closed** 2020-05-12 00:40 UTC
Labels: area/ui, bug
