### ISSUE TITLE
Problem with reattaching volume on different node

### ISSUE THREAD

**Issue by KuroObi** [longhorn/longhorn#294] opened 2018-09-18 13:01 UTC
When deleting a pod of a statefullset with PVC-Template and active deployed longhorn volume.
The pod gets redeployed on a different node it is not able to reattach the volume with the following error message:
`Multi-Attach error for volume "pvc-XXXX" Volume is already exclusively attached to one node and can't be attached to another`
On the new and old now i see in the kublet log the follwing log message:
`kubelet_volumes.go:140] Orphaned pod "XXXX" found, but volume paths are still present on disk : There were a total of 3 errors similar to this. Turn up verbosity to see them.`

We are using Rancher v2.0.8 with RKE 1.11.2 and Longhorn v0.3.0 with CSI

Is this even a longhorn issue or a k8s CSI bug?

**Comment by yasker** [comment] 2018-09-18 22:13
We would need to reproduce it to see. From the message sounds like the Kubernetes failed to detach the volume from another node, which should had been done by CSI.

Currently Kubernetes CSI has issues with node down scenario, e.g. https://github.com/rancher/longhorn/issues/199 . Flexvolume isn't much better though. We're working on it and should get to the bottom of it in the next stable release v0.3.2.

**Comment by KuroObi** [comment] 2018-09-19 08:42
That was my theory as well, that it didn't succeeded to detach (or unmount) the volume in time for pod deletion and cant attach and mount it into any other pod.

If You need more logs or settings, feel free to ask so I can help resolve this issue.

**Comment by KaelBaldwin** [comment] 2018-12-19 18:43
I've been using longhorn quite a bit and do notice that if the detach process takes a little while (which it normally does with fairly large volumes) the attach process will fail.

I'm having to manually scale down my deployments to 0, wait for the volume to show detached in longhorns UI then scale back up to 1 in order to have a smooth transition.

**Comment by yasker** [comment] 2018-12-19 19:19
@KaelBaldwin Your case sounds like the race condition in the Kubernetes CSI attachment. Can you take a look at https://github.com/rancher/longhorn/issues/267 to see if that's the case?

**Comment by KaelBaldwin** [comment] 2018-12-19 19:32
other than that it needs to be created and deleted repeatedly it might be the same.
Here's what I do to reproduce my case:

1. scale down a deployment (with a longhorn volume attached) to 0
2. once it disappears from rancher's interface immediately scale back up (don't wait for longhorns interface to show detached)
3. notice the volume is already exclusively attached message.

Depending on how large the volume is, that initial detach process can take longer, and if long enough, kubernetes may try multiple times before it detached (with increasing delays between attempts) which may result in a rather long wait time for the new pod to be ready.

**Comment by yasker** [comment] 2019-02-01 01:20
@KuroObi I am working on this issue. How did `the pod gets redeployed on a different node`? Have you manually delete the original pod? I think that's the only way I know to get pod relocated.

I found out that if you force delete the pod (e.g. in the case of the node failure), it will take Kubernetes (v1.12 as I tested) extremely long time to delete the `volumeattachment` object thus detach the volume. In my test, after the pod was deleted, it would take about 6 minutes for the volumeattachment associated with the volume get deleted, before it can be attached again.

**Comment by yasker** [comment] 2019-02-05 01:39
Also, see https://github.com/rancher/longhorn/blob/v0.4/docs/node-failure.md for what would expect in the upcoming v0.4.0 release.

**Comment by KuroObi** [comment] 2019-02-07 12:43
Yes, the pod was manual deleted and redeployed.
After updating to the newest rancher and longhorn version it doesn't take that long till the old volumeattachment gets released.

**Comment by yasker** [comment] 2019-02-07 18:25
@KuroObi Sounds good. We are improving Longhorn resiliency in v0.4.0 release, and trying to figure out the way to speed up the detach process once the pod was deleted. The latter would likely involve in Kubernetes upstream changes, and we're working on that.

**Comment by yasker** [comment] 2019-02-15 05:20
Move this to v0.5.0. Workaround Kubernetes's long timeout would need Longhorn to know more about Kubernetes status.

**Comment by yasker** [comment] 2019-05-02 18:42
We've implemented the speed up for volume detach for Kubernetes on failed nodes. But we need to look into the Kubernetes on normal pod deletion process to see if it's OK to apply the same logic here. Move to v0.6.0.

**Comment by yasker** [comment] 2019-12-06 02:49
Close this one since we haven't seen it since v0.6.0. Feel free to reopen if it happens again.

**Closed by yasker** 2019-12-06 02:49 UTC
Labels: area/driver, area/kubernetes, bug
