### ISSUE TITLE
[Question] why it takes forever to delete snapshots?

### ISSUE THREAD

**Issue by ElisaMeng** [longhorn/longhorn#2221] opened 2021-01-28 23:57 UTC
**Question**

**Environment:**
 - Longhorn version:
 - 1.1.0
 - Kubernetes version: 1.19
 - Node config
   - OS type and version: k3os
   - CPU per node: 48
   - Memory per node: 256G
   - Disk type: 10K sas
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):

**Additional context**

After rebuilding replicas, it seems take years to clear up snapshots, why? even longer than rebuilding procedure.

**Comment by joshimoo** [comment] 2021-01-29 10:16
Are you able to provide additional details about the specific scenario you are facing?
- How many nodes/volumes/snapshots?
- Why was a rebuild necessary?

Are you able to attach a support bundle?

**Comment by ElisaMeng** [comment] 2021-01-29 12:34
Hi @joshimoo, we decide to take some nodes offline to performan hardware maintenance, so we disable schedules
 on those nodes, evict replicas from them.  Eviction procedure trigger rebuild. That went well but it take unacceptable time to cleanup after replica is relocated to other nodes.   

It is unlikely the volume number matter here, since evicting 20-30 or a single replica seems behave the same: painfully waiting  in cleaning up the snapshots.

**Comment by yasker** [comment] 2021-02-01 21:48
@ElisaMeng Snapshot cleanup is an O(n) operation (n is the size of the replica) since each snapshot in Longhorn is a delta disk. To remove one snapshot, we need to merge the snapshot with its child, to keep the data correct in the volume. So it indeed will take a while for the snapshots to get merged correctly.

You can also refer to https://longhorn.io/docs/1.1.0/concepts/#231-how-read-and-write-operations-work-for-replicas on how snapshot works in Longhorn.

**Comment by ElisaMeng** [comment] 2021-02-04 20:52
@yasker You are right, I dig into details and find there are about 240 snapshots was created by system. I don't know why. Base the link, yes, it will take a while.  Thanks yasker.  Most of the volumes back into normal as expected after a while.  However, I got one volume look very strange. 

In the UI, I try to create snapshot, it complains too many snapshot created.  I click on "show  system snapshots", yes indeed there're  a lot snapshots 
![Screen Shot 2021-02-04 at 21 45 54](https://user-images.githubusercontent.com/69029899/106953482-bbb29200-6732-11eb-9820-daaba73ce27f.png)

while I use the lhexec script to list the snapshots, none was found

```
./lhexec pvc-77a0a94e-09eb-4852-b344-d7564c8b1590 snapshots ls 
+ kubectl -n longhorn-system exec -it instance-manager-e-e17948f6 -- bash -c '/engine-binaries/longhornio-longhorn-engine-v1.1.0/longhorn --url localhost:10007 snapshots ls'
ID

```

What could go wrong here? where dose the UI/script pulling data? while it looks different?

**Comment by PhanLe1010** [comment] 2021-02-10 18:01
@ElisaMeng 
> where dose the UI/script pulling data?

The UI pull data from volumes, engines, replicas CRDs. 

> Is any way to clean up snapshot? The UI block me from deleting anyone of them.

You can manually delete an user-created snapshot (the blue one) to trigger system snapshots (yellow ones) purge;

>  why it looks different? 

I am not sure why atm. Can you can us a support bundle so I can take a look?

**Comment by ElisaMeng** [comment] 2021-02-14 22:49
@PhanLe1010 Since it was a lab env. I have destroyed the cluster. :(
I suspected it is something wrong in the snapshot ls function, which overflow somewhere since I only see this when I have up to 249 snapshots. Other volumes that there are less snapshots, I never saw this problem.

**Comment by joshimoo** [comment] 2021-02-17 18:24
Closing since you currently don't have this issue anymore.
From your message that you have 249 snapshots, it most likely means that your environment isn't stable and you have lots of replica failures, since each replica failure will lead to a system generated snapshot.

This can be caused by exhausting cpu, memory, network bandwith or a flaky network.

**Closed by joshimoo** 2021-02-17 18:24 UTC
Labels: question
