### ISSUE TITLE
[IMPROVEMENT] Resilience handling for the last replica timeout

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#8711] opened 2024-06-05 10:40 UTC
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Retry to connect the last replica instead of failing it immediately if it's disconnected due to timeout.

Context:
> If there are 3 replicas for a volume and 2 are already marked as ERROR due to timeout, unfortunately, the last one is going to encounter timeout afterward. Will we treat it differently or just use the same approach to mark it as ERROR as the previous two replicas?
>
> If yes, this would be prone to make the volume hit IO read-only issue. Can we do it differently for the last replica before we decide to mark it as ERROR due to timeout? For example, retry a configured time to wait until the replica becomes ready.
> 
> For non-last replicas, we still need to make it fail due to timeout to unblock IO as usual (setting it indefinite does not make sense for us in the current design. Also, even if a replica is marked as failed, it will be possibly reused after rebuild wait time). However, for the last replica, I think we should treat it differently to prevent users from easily encountering IO read-only problems.  

## Describe the solution you'd like

- [ ] Resilience handling via retries instead of timeout only
- [ ] Align the timeout between the engine and replica, for v1 and v2

**Comment by shuo-wu** [comment] 2024-06-07 07:39
Today I had a discussion with David about this issue and came out with a new idea.
First of all, after a regular timeout, I don't think returning an IO error then asking the last replica to retry is a good idea. Returning an error is dangerous as the upper layer may consider the block device as no longer available. For example, the filesystem may become read-only. 
Instead, directly using a longer timeout may be slightly better than a retry. More specifically, the idea is:
1. If there is only one RW replica, the engine should directly use a longer timeout for the data connection.
2. Otherwise,
    1. If there is one replica getting a result within the regular timeout, then the engine will apply this regular timeout to all other replica data connections.
    2. After the regular timeout returns, if there is no response from any replica, the engine will apply the longer timeout to all replicas.

Anyway, this is a simple thought. I am not sure if it's practicable enough.

**Comment by derekbit** [comment] 2024-06-07 14:46
I believe the purposes of a long timeout and EIO/EAGAIN are different. A long timeout can accommodate long latency caused by underlying networking or storage issues. However, once the timeout is reached, the current behavior is to fail the replica. If we instead return EIO or EAGAIN, the application can decide the next step, such as retrying or error handling. A mature application should be able to handle both types of errors. Too long timeout make the application stuck, and it is not acceptable for some applications. That's why I think we should return an appropriate error instead of failing the last replica.

**Comment by ejweber** [comment] 2024-06-07 15:00
So far, I think the suggestion from @shuo-wu and @innobead makes sense. 

From the practical side, today there is a setting `engine-replica-timeout`. I guess we would add the setting `engine-last-replica-timeout` (or `no-backend-timeout`) and make it configurable, but default to much longer.

We can document that the tradeoffs:

- If the timeouts are the same, and short, we will respond very quickly to unrecoverable failures (e.g. all replicas go offline or are unreachable), but the volume may crash in some situations where it is not strictly necessary. The sameness means we aren't likely to drop "slow" replicas (e.g. remote ones) while keeping "fast" ones (e.g. local ones).
- If the timeouts are the same, and long, we will respond slowly to unrecoverable failures (e.g. all replicas go offline or are unreachable), but the volume is less likely to crash. The sameness means we aren't likely to drop "slow" replicas (e.g. remote ones) while keeping "fast" ones (e.g. local ones).
- If the timeouts are different and `engine-last-replica-timeout` is long, we will respond slowly to unrecoverable failures (e.g. all replicas go offline or are unreachable), but the volume is less likely to crash. The difference means we are likely to drop "slow" replicas (e.g. remote ones) while keeping "fast" ones (e.g. local ones). This keeps the volume alive and operating acceptable (not hindered by "slow" replicas), but it also means volumes may spend a lot of time degraded.

**Comment by ejweber** [comment] 2024-06-07 15:04
> I think the purposes of a long timeout and EIO/EAGAIN are different. A long timeout can accommodate long latency caused by underlying networking or storage issues. However, once the timeout is reached, the current behavior is to fail the replica. If we instead return EIO or EAGAIN, the application can decide the next step, such as retrying or error handling. A mature application should be able to handle both types of errors. Too long timeout make the application stuck, and it is not acceptable for some applications. That's why I think we should return an appropriate error instead of failing the last replica.

When should we fail the replica with this implementation? In the normal flow, it is usually the engine that marks all replicas failed, leading to a volume crash/restart. If the last replica is unreachable, but we don't mark it failed, we will continue to send errors, but won't recover.

**Comment by derekbit** [comment] 2024-06-07 17:06
> > I think the purposes of a long timeout and EIO/EAGAIN are different. A long timeout can accommodate long latency caused by underlying networking or storage issues. However, once the timeout is reached, the current behavior is to fail the replica. If we instead return EIO or EAGAIN, the application can decide the next step, such as retrying or error handling. A mature application should be able to handle both types of errors. Too long timeout make the application stuck, and it is not acceptable for some applications. That's why I think we should return an appropriate error instead of failing the last replica.
> 
> 
> 
> When should we fail the replica with this implementation? In the normal flow, it is usually the engine that marks all replicas failed, leading to a volume crash/restart. If the last replica is unreachable, but we don't mark it failed, we will continue to send errors, but won't recover.

I don't think the increase of timeout is a good idea. I would suggest using a retry count (which can be configurable). If excessing the max retry count, we can crash the volume. Before the max count, an error should make sense.

**Comment by derekbit** [comment] 2024-06-07 17:58
> Returning an error is dangerous as the upper layer may consider the block device as no longer available. For example, the filesystem may become read-only.

Yes. EAGAIN is better than EIO. EIO will make the file system read only if errors of mount options is remount-ro.

https://linux.die.net/man/8/mount

**Comment by shuo-wu** [comment] 2024-06-08 06:19
Do you mean that Longhorn will return `EAGAIN` or `EBUSY` and retain the replicas when all replicas/the last replica has not triggered the timeout for MAX_RETRY times?

**Comment by derekbit** [comment] 2024-06-08 08:26
> Do you mean that Longhorn will return `EAGAIN` or `EBUSY` and retain the replicas when all replicas/the last replica has not triggered the timeout for MAX_RETRY times?

Only for the last replica. If the last replica is somehow unreachable and unresponsive, iSCSI tgt sets an appropriate error code, and the error code maps it to EBUSY (or EAGAIN) in the initiator side. Then, the application can catch the errno. It might retry the IO multiple times. After MAX_RETRY, the last replica is marked as ERROR.

**Comment by derekbit** [comment] 2024-06-11 09:38
After discussing with @innobead this morning, we have some thoughts for the timeouts and retries in the data path

- Ping: The current implementation sets a ping timeout of 2 seconds ([codes](https://github.com/longhorn/longhorn-engine/blob/master/pkg/backend/remote/remote.go#L25)). For IO-intensive volumes, ping latencies can increase significantly for both busy and idle volumes. As a result, the ping might become unresponsive within the 2-second timeout, potentially triggering unnecessary replica rebuilds for both busy and idle volumes. Should we consider adding a retry or backoff mechanism to the ping process to prevent marking healthy replicas as disconnected or unrecoverable?

- Timeout between engine and replica: As previously mentioned, despite increasing the timeout for the last replica, we are still unable to prevent volume crashes without any error notifications to applications. To address this, we propose the following:
  - Use the same timeout value for both non-last replicas and the last replica.
  - Introduce a maximum retry mechanism for the last replica. Before reaching the maximum retry count (MAX_RETRY), the iSCSI target will return an iSCSI sense code (0x08) to the iSCSI initiator. This sense code is then mapped to EBUSY in the block layer. The filesystem will receive the EBUSY and handle it accordingly (need to check how the filesystem handles this). This method allows the application to handle the errors and retry the I/O request. If the connection to the replica is genuinely problematic, the volume will crash after the retries. If not, the I/O should continue successfully.
  - Both the timeout and MAX_RETRY are configurable to suit different applications or environments.

**Comment by derekbit** [comment] 2024-06-17 04:32
Best effort in v1.7.0

**Comment by ejweber** [comment] 2024-07-10 22:00
> Ping: The current implementation sets a ping timeout of 2 seconds ([codes](https://github.com/longhorn/longhorn-engine/blob/master/pkg/backend/remote/remote.go#L25)). For IO-intensive volumes, ping latencies can increase significantly for both busy and idle volumes. As a result, the ping might become unresponsive within the 2-second timeout, potentially triggering unnecessary replica rebuilds for both busy and idle volumes. Should we consider adding a retry or backoff mechanism to the ping process to prevent marking healthy replicas as disconnected or unrecoverable?

I started by looking into this part. However, I think the ping today doesn't work quite how we expect. In the past, each operation type (including ping) had its own timeout. Failure to receive a response within the timeout would cause an error. Then, https://github.com/longhorn/longhorn-engine/pull/630 removed the per-operation timeout in favor of a rolling timeout that ONLY affected I/O operations. Now, if there are inflight I/Os, we reset the per-operation timeout each time we receive a response to an I/O operation. Pings, however, are completely excluded from this mechanism.

https://github.com/longhorn/longhorn-engine/blob/0bfac42c4aff28364459c35b753d7fe5387c93a9/pkg/dataconn/client.go#L149-L197

As a result, pings can result in an error for one of two reasons:

1. A transport error occurs while SENDING the ping.
   - https://github.com/longhorn/longhorn-engine/blob/0bfac42c4aff28364459c35b753d7fe5387c93a9/pkg/dataconn/client.go#L255-L267
   - https://github.com/longhorn/longhorn-engine/blob/0bfac42c4aff28364459c35b753d7fe5387c93a9/pkg/dataconn/client.go#L172-L175
2. The replica intentionally responds with an error.
   - https://github.com/longhorn/longhorn-engine/blob/fee7f37ae498bed046bfebf60b072ec0c74add3b/pkg/replica/server.go#L361-L370

It does not look like we will ever error out for a ping that the replica receives but doesn't have time to respond to. During periods of heavy I/O, I/O requests and ping requests are (IMO) equally likely to experience a transport error on send, so the ping timeout is likely not a concern.

I'm still experimenting on this to confirm the behavior.

**Comment by ejweber** [comment] 2024-07-11 18:04
I discussed my ping findings with @PhanLe1010, @shuo-wu, and @james-munson today. I will follow up by looking into:

Given that ping seems to be "broken", do we actually really need it?

1. Without the ping, does the engine recognize when a replica crashes (due to a closed connection)?
2. Would we need something like TCP keepalives to ensure the above works without ping?
3. Does https://github.com/longhorn/longhorn-engine/pull/630 mention why we still need the ping (or how it was intended to work after the introduced changes)?

**Comment by ejweber** [comment] 2024-07-11 22:11
Experimenting with https://github.com/longhorn/longhorn-engine/compare/master...ejweber:longhorn-engine:8711-remove-ping to check if ping is necessary. The following test cases suggest it is not:

1. Delete an instance-manager containing a replica:

```
eweber@laptop:~/longhorn> date && kl delete pod instance-manager-6852914a55e4566d3ddea43529df22e0
Thu 11 Jul 2024 04:38:56 PM CDT
pod "instance-manager-6852914a55e4566d3ddea43529df22e0" deleted

[test-e-0] time="2024-07-11T21:38:56Z" level=error msg="Error reading from wire 10.42.4.188:10001" func="dataconn.(*Client).read.func1" file="client.go:268" error=EOF
time="2024-07-11T21:38:56Z" level=error msg="Error reading from wire 10.42.4.188:10001" func="dataconn.(*Client).read.func1" file="client.go:268" error=EOF
```

2. Kill a replica process inside an instance-manager.

```
instance-manager-6852914a55e4566d3ddea43529df22e0:/ # date && kill -9 83
Thu Jul 11 21:40:58 UTC 2024

[test-e-0] time="2024-07-11T21:40:58Z" level=error msg="Error reading from wire 10.42.4.189:10001" func="dataconn.(*Client).read.func1" file="client.go:268" error=EOF
time="2024-07-11T21:40:58Z" level=error msg="Error reading from wire 10.42.4.189:10001" func="dataconn.(*Client).read.func1" file="client.go:268" error=EOF
```

However, I am thinking the behavior will be different in a network partition, as the connection may not explicitly be closed. Unfortunately, my changes break the volume for actual I/O, so I will need to dig a little deeper to understand why.

```
timeout_handler: Timeout request 81 due to disconnection
tgtd: bs_longhorn_request(183) Failed to punch hole for UNMAP at offset:0 length:-2147483648
tgtd: bs_longhorn_request(210) io error 0x1a4e820 42 0 16 0, Success
timeout_handler: Timeout request 82 due to disconnection
tgtd: bs_longhorn_request(111) fail to read at 0 for 512
tgtd: bs_longhorn_request(210) io error 0x1a4e820 28 -14 512 0, Success
response_process: Unknown response sequence 82
```

**Comment by PhanLe1010** [comment] 2024-07-12 18:33
> However, I am thinking the behavior will be different in a network partition, as the connection may not explicitly be closed.

Can we simulate this by turning off the network interface of the replica node suddenly? 

In the worst case, I think it is still acceptable because:
1. This issue is not permanent. Volume doesn't do any IO at the moment. When it does IO, it will detect the connection issue
2. It should be rare. 
3. The only (small?) consequence is that we react to the event slower. This might be a benefit as when the network is restored it automatically works again without any replica rebuilding?

**Comment by ejweber** [comment] 2024-07-12 19:09
> Can we simulate this by turning off the network interface of the replica node suddenly?

Good thinking. I am experimenting with a different approach using `iptables` to drop packets bound for a particular pod. I ran into some roadblocks at first, but it's working pretty well now. I'll update my experimental results in a bit.

**Comment by ejweber** [comment] 2024-07-29 16:39
cc @PhanLe1010 

I finished a deep dive on the various timeout that might contribute to the behaviors in https://github.com/longhorn/longhorn/issues/8711#issuecomment-2224031118 at https://github.com/longhorn/longhorn/wiki/TCP-and-gRPC-Timeouts-in-Longhorn-Engine.

The most important TLDR is probably that the 40 seconds to replica failure in case 3 (network partition) is the result of:

- Engine monitor syncs sometime within 5 s.
- Engine monitor fails to list snapshots due to failure to establish connection between engine and replica in 20s. Results in a log and an engine CR status update, but nothing else.
- Engine monitor fails to get purge status of replica due to failure to establish connection between engine and replica in 20s. Results in the volume controller marking the replica as failed.

It's kind of a strange way for a replica to be marked as failed, since the engine itself still considers the replica to be healthy. (And continues to do so until an actual I/O request times out.)

**Comment by ejweber** [comment] 2024-08-01 16:52
> After discussing with @innobead this morning, we have some thoughts for the timeouts and retries in the data path
> 
> * Ping: The current implementation sets a ping timeout of 2 seconds ([codes](https://github.com/longhorn/longhorn-engine/blob/master/pkg/backend/remote/remote.go#L25)). For IO-intensive volumes, ping latencies can increase significantly for both busy and idle volumes. As a result, the ping might become unresponsive within the 2-second timeout, potentially triggering unnecessary replica rebuilds for both busy and idle volumes. Should we consider adding a retry or backoff mechanism to the ping process to prevent marking healthy replicas as disconnected or unrecoverable?
> * Timeout between engine and replica: As previously mentioned, despite increasing the timeout for the last replica, we are still unable to prevent volume crashes without any error notifications to applications. To address this, we propose the following:

The PingInterval is currently NOT a concern for this ticket, as it does not result in a replica being marked as ERR. After a lot of discussion, @PhanLe1010 has convinced me that this existing behavior is correct. See https://github.com/longhorn/longhorn-engine/pull/1170 for details.

>   * Use the same timeout value for both non-last replicas and the last replica.
>   * Introduce a maximum retry mechanism for the last replica. Before reaching the maximum retry count (MAX_RETRY), the iSCSI target will return an iSCSI sense code (0x08) to the iSCSI initiator. This sense code is then mapped to EBUSY in the block layer. The filesystem will receive the EBUSY and handle it accordingly (need to check how the filesystem handles this). This method allows the application to handle the errors and retry the I/O request. If the connection to the replica is genuinely problematic, the volume will crash after the retries. If not, the I/O should continue successfully.
>   * Both the timeout and MAX_RETRY are configurable to suit different applications or environments.

I will now move on to looking at this.

**Comment by ejweber** [comment] 2024-08-01 21:36
> Timeout between engine and replica: As previously mentioned, despite increasing the timeout for the last replica, we are still unable to prevent volume crashes without any error notifications to applications. To address this, we propose the following:
> 
> * Use the same timeout value for both non-last replicas and the last replica.
> * Introduce a maximum retry mechanism for the last replica. Before reaching the maximum retry count (MAX_RETRY), the iSCSI target will return an iSCSI sense code (0x08) to the iSCSI initiator. This sense code is then mapped to EBUSY in the block layer. The filesystem will receive the EBUSY and handle it accordingly (need to check how the filesystem handles this). This method allows the application to handle the errors and retry the I/O request. If the connection to the replica is genuinely problematic, the volume will crash after the retries. If not, the I/O should continue successfully.
> * Both the timeout and MAX_RETRY are configurable to suit different applications or environments.

For this part, I am unsure @derekbit and @innobead.

From the [SCSI Architecture Model](https://www.cs.cmu.edu/afs/club/usr/jhutz/project/Archives/scsi/sam3r13.pdf), BUSY means:

This status indicates that the logical unit is busy. This status shall be returned whenever a logical unit is
temporarily unable to accept a command. The recommended application client recovery action is to issue the
command again at a later time. 

Usually, we return SAM_STAT_CHECK_CONDITION, MEDIUM_ERROR, ASC_READ_ERROR when all replicas time out. 

https://github.com/rancher/tgt/blob/64a3443ad6ab829343167e744a757d8ec044185a/usr/bs_longhorn.c#L63-L68

If we instead return SAM_STAT_BUSY, it seems the filesystem layer should interpret it as meaning we never accepted the command for processing. However, if we are just waiting on slow responses from at least one remaining replica, then that replica maybe HAS received the command and is executing it. Returning SAM_STAT_BUSY in this case would lead the application layer to assume we were never going to complete the command. Maybe it could lead to filesystem corruption?

---

Thinking about the various scenarios that might lead to us triggering some new retry logic:

1. The TCP connection between the engine and the replica is actually closed. Either it timed out due to failed keepalives, or the replica side closed it (probably due to the replica actually going down).

This is currently an unrecoverable situation for us. We don't have any ability baked in to re-establish the connection. When it closes, we mark a replica as failed.

I'm having a bit of trouble understanding why we would WANT to try to re-establish the connection here. TCP already tries quite hard to keep it alive, so if it closed unintentionally, it is only after ~2 min 30 s (in the keepalive case) with the client side retrying 9 times (in the keepalive case) to communicate. If we think ~2 min 30 s is too short, we have the ability to increase that.

2. The TCP connection between the engine and the replica is not closed, but is really slow.

If commands are already actually making it to the replica, repeating the commands seems like it would not help the situation.

3. The TCP connection between the engine and the replica is fine, but the replica is responding slowly.

In this case, the replica may already be processing received commands. If we return (with SAM_STAT_BUSY for example) now, the file system layer will assume we did not process the received commands.

---

TBH, it seems to me that the different timeout for the LAST replica is most appropriate. A healthy replica should return a response for SOME I/O in 8 s if it still working. If the reason is a temporary network disruption, then maybe it makes sense to allow the LAST replica to have an increased timeout in case the issue resolves quickly without a crash. (Even this can be controversial, since continuing to allow writes while degraded may be seen as a violation of a data protection guarantee.) But I am not sure what a retry mechanism can do for us.

WDYT? Can you help clarify the exact scenarios in which we should return SAM_STAT_BUSY?

**Comment by derekbit** [comment] 2024-08-01 23:58
> If we instead return SAM_STAT_BUSY, it seems the filesystem layer should interpret it as meaning we never accepted the command for processing. However, if we are just waiting on slow responses from at least one remaining replica, then that replica maybe HAS received the command and is executing it. 

I see. I didn't think about filesystem corruption. Returning EBUSY is not correct here. The best solution might be increasing the timeout of the last replica.

**Comment by derekbit** [comment] 2024-08-02 00:19
Another question
If the timeout between SCSI and iSCSI is 60 seconds, for a 3-replica volume, the timeout of the first two replica is 8 seconds,  does it mean we have 44 (60-8-8) seconds for the last replica?

**Comment by ejweber** [comment] 2024-08-02 18:05
> Another question If the timeout between SCSI and iSCSI is 60 seconds, for a 3-replica volume, the timeout of the first two replicas is 8 seconds, does it mean we can set 44 (60-8-8) seconds for the last replica? Make sense?

I am not sure why the math here is 8 + 8 + 44. I think we should be willing to timeout the first two replicas in 8 seconds (even in parallel if that's what happens) with a full 60 second timeout for the last one. 

I think it makes sense in principle. A couple of things to consider:

- There is a practical limit of ~45 seconds today that a replica can survive a network disruption before being failed due to https://github.com/longhorn/longhorn/issues/8711#issuecomment-2256405414. If our responses are just slow on the I/O side, but the network and replica process are live, this doesn't matter. If the network is actually disrupted, we won't make it to 60 seconds.
- [ ] Off the top of my head I'm not sure why we should time out on the engine side at all due to our internal timer. What would happen if we did the following. Have we tried it before? (I'm going to give it a shot this afternoon to increase my understanding.)
   - Fail "extra" replicas in engine-replica-timeout.
   - NEVER crash the volume due to engine-replica-timeout.
   - Respond to upper layer error handling for SCSI/iSCSI timeouts. I'm not super familiar with the protocol yet, but reading through it, it seems like we should get identifiable reset commands.

**Comment by PhanLe1010** [comment] 2024-08-02 19:15
>I am not sure why the math here is 8 + 8 + 44. I think we should be willing to timeout the first two replicas in 8 seconds (even in parallel if that's what happens) with a full 60 second timeout for the last one.

I am curious why 44 too?

> NEVER crash the volume due to engine-replica-timeout (never timeout the last replica)

I don't have concert counter-evidence on the top of my head. But I feel like never timeout and wait for the IO for ever sounds extreme. I think 60s for the last replica is good enough.

**Comment by ejweber** [comment] 2024-08-05 22:01
> I don't have concert counter-evidence on the top of my head. But I feel like never timeout and wait for the IO forever sounds extreme. I think 60s for the last replica is good enough.

I didn't mean we should wait forever. I meant we should wait until we received a signal from the SCSI layer that it was trying to reset the bus, etc., then crash. But I am not yet sure what that might look like from the Longhorn side.

For now, I working on a POC of code that allows setting a separate timeout for the last replica. It's a bit more complex than expected because we typically allow the each backend (within the engine) to manage its own in-flight I/O and timeouts. Since each backend does not know whether there are other available backends experiencing timeouts (and thus whether it is correct to timeout now or wait for the "long" timeout), we must move the logic that actually triggers the timeout to an upper layer. I should be able to test the behavior in the next day or so.

**Comment by derekbit** [comment] 2024-08-17 02:27
> > Another question If the timeout between SCSI and iSCSI is 60 seconds, for a 3-replica volume, the timeout of the first two replicas is 8 seconds, does it mean we can set 44 (60-8-8) seconds for the last replica? Make sense?
> 

Yes, it should be full 60 seconds. Sorry for my brain fog..

**Comment by yangchiu** [comment] 2024-09-06 07:28
Verification passed on `v1.8.0-dev-20240825` following [the test plan](https://github.com/longhorn/longhorn/issues/8711#issuecomment-2302809322).

**Closed by yangchiu** 2024-09-06 07:28 UTC
Labels: area/v1-data-engine, component/longhorn-instance-manager, priority/2, require/auto-e2e-test, require/doc, area/stability, kind/improvement, area/v2-data-engine, area/resilience, backport/1.7.1
