### ISSUE TITLE
[BUG] OpenShift 4.15.3 - Lonhorn 1.6.1 - longhorn-ui nginx (13: Permission denied)

### ISSUE THREAD

**Issue by n00bsi** [longhorn/longhorn#8300] opened 2024-04-03 11:31 UTC
## Question

How to run 1.6.1 on OpenShift 4.15.3 ?
1.4.2 worked on OpenShift 4.15.3

## Environment

 - Longhorn version: 1.6.1
 - Kubernetes version:  v1.28.7+6e2789b
 - Node config
   - OS type and version: Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)
   - Kernel version: 5.14.0-284.55.1.el9_2.x86_64
   - CPU per node: 4
   - Memory per node: 8 GB worker / 16 GB controlplane
   - Disk type: Virtual Disk
   - Network bandwidth and latency between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):  VMWare

## Additional context

```
[core@osdemo1 ~]$ oc get nodes -o wide
NAME                 STATUS     ROLES                  AGE   VERSION           INTERNAL-IP   EXTERNAL-IP   OS-IMAGE                                                       KERNEL-VERSION                 CONTAINER-RUNTIME
osdemo1.ourdomain.tld   Ready      control-plane,master   15d   v1.28.7+6e2789b   192.168.7.221   <none>        Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)   5.14.0-284.55.1.el9_2.x86_64   cri-o://1.28.4-4.rhaos4.15.git92d1839.el9
osdemo2.ourdomain.tld   Ready      control-plane,master   15d   v1.28.7+6e2789b   192.168.7.222   <none>        Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)   5.14.0-284.55.1.el9_2.x86_64   cri-o://1.28.4-4.rhaos4.15.git92d1839.el9
osdemo3.ourdomain.tld   Ready      control-plane,master   15d   v1.28.7+6e2789b   192.168.7.223   <none>        Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)   5.14.0-284.55.1.el9_2.x86_64   cri-o://1.28.4-4.rhaos4.15.git92d1839.el9
osdemo4.ourdomain.tld   Ready      worker                 15d   v1.28.7+6e2789b   192.168.7.224   <none>        Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)   5.14.0-284.55.1.el9_2.x86_64   cri-o://1.28.4-4.rhaos4.15.git92d1839.el9
osdemo5.ourdomain.tld   Ready      worker                 15d   v1.28.7+6e2789b   192.168.7.225   <none>        Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)   5.14.0-284.55.1.el9_2.x86_64   cri-o://1.28.4-4.rhaos4.15.git92d1839.el9
osdemo6.ourdomain.tld   Ready      worker                 15d   v1.28.7+6e2789b   192.168.7.226   <none>        Red Hat Enterprise Linux CoreOS 415.92.202403080220-0 (Plow)   5.14.0-284.55.1.el9_2.x86_64   cri-o://1.28.4-4.rhaos4.15.git92d1839.el9

```

wget  https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
copy to controlplane
oc apply -f longhorn.yaml
oc adm policy add-scc-to-user anyuid -z default -n longhorn-system
oc adm policy add-scc-to-user privileged -z longhorn-service-account -n longhorn-system

oc apply -f longhorn-route.yaml

```
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: longhorn
  namespace: longhorn-system
  labels:
    app: longhorn-ui
    app.kubernetes.io/instance: longhorn
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.6.1
spec:
  host: longhorn.apps.osc.ourdomain.tld
  to:
    kind: Service
    name: longhorn-frontend
    weight: 100
  port:
    targetPort: http
  wildcardPolicy: None

```

kubectl get clusterroles longhorn-role -o yaml > longhorn-role.yaml

add

```
- apiGroups:
  - longhorn.io
  resources:
  - engineimages/finalizers
  - instancemanagers/finalizers
  - sharemanagers/finalizers
  - backingimagemanagers/finalizer
  - nodes/finalizers
  verbs:
  - '*'

```
oc apply -f longhorn-role.yaml

oc get pods -n longhorn-system

```
[core@osdemo1 ~]$ oc get pods -n longhorn-system
NAME                                                READY   STATUS             RESTARTS        AGE
csi-attacher-5c4bfdcf59-2rssp                       1/1     Running            0               15m
csi-attacher-5c4bfdcf59-964n4                       1/1     Running            0               15m
csi-attacher-5c4bfdcf59-wmhpn                       1/1     Running            0               15m
csi-provisioner-667796df57-9mklv                    1/1     Running            0               15m
csi-provisioner-667796df57-m9n99                    1/1     Running            0               15m
csi-provisioner-667796df57-v5wlz                    1/1     Running            0               15m
csi-resizer-694f8f5f64-7mc5x                        1/1     Running            0               15m
csi-resizer-694f8f5f64-g7nbj                        1/1     Running            0               15m
csi-resizer-694f8f5f64-zdhdf                        1/1     Running            0               15m
csi-snapshotter-959b69d4b-dgxxq                     1/1     Running            0               15m
csi-snapshotter-959b69d4b-hvjks                     1/1     Running            0               15m
csi-snapshotter-959b69d4b-vjdps                     1/1     Running            0               15m
engine-image-ei-5cefaf2b-fbfp5                      1/1     Running            0               17m
engine-image-ei-5cefaf2b-jthk6                      1/1     Running            0               17m
engine-image-ei-5cefaf2b-k5tgc                      1/1     Running            0               17m
instance-manager-26d3e3e1b04c9e675a720b194c633a25   1/1     Running            0               16m
instance-manager-b422ca0f562b542741091e59c7e72dd6   1/1     Running            0               16m
instance-manager-f7cf196dfd5ab2261108a0131d2ec443   1/1     Running            0               16m
longhorn-csi-plugin-9fphh                           3/3     Running            0               15m
longhorn-csi-plugin-d4spq                           3/3     Running            0               15m
longhorn-csi-plugin-gbl22                           3/3     Running            0               15m
longhorn-driver-deployer-7449f56699-zz7md           1/1     Running            1 (16m ago)     17m
longhorn-manager-4ntcz                              1/1     Running            0               17m
longhorn-manager-k4srr                              1/1     Running            0               17m
longhorn-manager-kzlsc                              1/1     Running            0               17m
longhorn-ui-6c8c4fcbb8-8dhfl                        0/1     CrashLoopBackOff   6 (4m37s ago)   10m
longhorn-ui-6c8c4fcbb8-mrkhc                        0/1     CrashLoopBackOff   6 (4m52s ago)   10m

```

```
[core@osdemo1 ~]$ oc logs -n longhorn-system longhorn-ui-6c8c4fcbb8-mrkhc
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2024/04/03 11:29:18 [emerg] 10#10: mkdir() "/var/lib/nginx/tmp/" failed (13: Permission denied)
[core@osdemo1 ~]$ 

```

can not go inside the pod

```
[core@osdemo1 ~]$ kubectl exec -it longhorn-ui-6c8c4fcbb8-mrkhc -- sh
Error from server (NotFound): pods "longhorn-ui-6c8c4fcbb8-mrkhc" not found

```

What did I wrong ?

```
[core@osdemo1 ~]$ oc describe pod longhorn-ui-6c8c4fcbb8-mrkhc -n longhorn-system
Name:                 longhorn-ui-6c8c4fcbb8-mrkhc
Namespace:            longhorn-system
Priority:             1000000000
Priority Class Name:  longhorn-critical
Service Account:      longhorn-ui-service-account
Node:                 osdemo6.ourdomain.tld/192.168.7.226
Start Time:           Wed, 03 Apr 2024 11:18:26 +0000
Labels:               app=longhorn-ui
                      app.kubernetes.io/instance=longhorn
                      app.kubernetes.io/name=longhorn
                      app.kubernetes.io/version=v1.6.1
                      pod-template-hash=6c8c4fcbb8
Annotations:          k8s.ovn.org/pod-networks:
                        {"default":{"ip_addresses":["10.199.8.22/23"],"mac_address":"0a:58:0a:c7:08:16","gateway_ips":["10.199.8.1"],"routes":[{"dest":"10.199.0.0...
                      k8s.v1.cni.cncf.io/network-status:
                        [{
                            "name": "ovn-kubernetes",
                            "interface": "eth0",
                            "ips": [
                                "10.199.8.22"
                            ],
                            "mac": "0a:58:0a:c7:08:16",
                            "default": true,
                            "dns": {}
                        }]
                      openshift.io/scc: restricted-v2
                      seccomp.security.alpha.kubernetes.io/pod: runtime/default
Status:               Running
SeccompProfile:       RuntimeDefault
IP:                   10.199.8.22
IPs:
  IP:           10.199.8.22
Controlled By:  ReplicaSet/longhorn-ui-6c8c4fcbb8
Containers:
  longhorn-ui:
    Container ID:   cri-o://5a6ede9de805b040fdef71c23c62d7a8e8062affebfb9cb100df6350322ca38f
    Image:          longhornio/longhorn-ui:v1.6.1
    Image ID:       docker.io/longhornio/longhorn-ui@sha256:4e8ca245c26260892c23a995410c0b2b51fb37405f305e2591730947ad24f26b
    Port:           8000/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Wed, 03 Apr 2024 12:09:56 +0000
      Finished:     Wed, 03 Apr 2024 12:09:56 +0000
    Ready:          False
    Restart Count:  15
    Environment:
      LONGHORN_MANAGER_IP:  http://longhorn-backend:9500
      LONGHORN_UI_PORT:     8000
    Mounts:
      /var/cache/nginx/ from nginx-cache (rw)
      /var/config/nginx/ from nginx-config (rw)
      /var/run/ from var-run (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-vz52q (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  nginx-cache:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  nginx-config:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  var-run:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  kube-api-access-vz52q:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
    ConfigMapName:           openshift-service-ca.crt
    ConfigMapOptional:       <nil>
QoS Class:                   BestEffort
Node-Selectors:              <none>
Tolerations:                 node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason          Age                    From               Message
  ----     ------          ----                   ----               -------
  Normal   Scheduled       52m                    default-scheduler  Successfully assigned longhorn-system/longhorn-ui-6c8c4fcbb8-mrkhc to osdemo6.ourdomain.tld
  Normal   AddedInterface  52m                    multus             Add eth0 [10.199.8.22/23] from ovn-kubernetes
  Normal   Pulling         52m                    kubelet            Pulling image "longhornio/longhorn-ui:v1.6.1"
  Normal   Pulled          52m                    kubelet            Successfully pulled image "longhornio/longhorn-ui:v1.6.1" in 7.096s (7.096s including waiting)
  Normal   Created         50m (x5 over 52m)      kubelet            Created container longhorn-ui
  Normal   Started         50m (x5 over 52m)      kubelet            Started container longhorn-ui
  Normal   Pulled          50m (x4 over 52m)      kubelet            Container image "longhornio/longhorn-ui:v1.6.1" already present on machine
  Warning  BackOff         2m12s (x236 over 52m)  kubelet            Back-off restarting failed container longhorn-ui in pod longhorn-ui-6c8c4fcbb8-mrkhc_longhorn-system(dcd44fba-0fd2-4e1a-9891-1c1e308f6d75)

```

**Comment by mantissahz** [comment] 2024-04-08 01:55
Hi @n00bsi,
Could you try to add this secret https://github.com/longhorn/longhorn/pull/8078/files#diff-cb43de5286db54612c9e0976162aeea5a4a2b6058f64dbba1a3122bed22580e2 to check if it will work?

**Comment by n00bsi** [comment] 2024-04-08 07:11
@mantissahz 
thanks for your help

do you mean this:

```
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "longhorn.labels" . | nindent 4 }}
    app: longhorn-ui
  name: longhorn-ui-service-account
  namespace: {{ include "release_namespace" . }}
  annotations:
    kubernetes.io/service-account.name: longhorn-ui-service-account
type: kubernetes.io/service-account-token

```

**Comment by akienz99** [comment] 2024-04-09 12:41
Seems like this is a permission issue inside the container (file system permissions inside the container maybe?)

Had the same issue on OKD 4.15.0-0.okd-2024-02-23-163410 and could resolve it (temporarily) by making the longhorn-ui container privileged

```
oc adm policy add-scc-to-user privileged -z longhorn-ui-service-account -n longhorn-system
```

```
spec:
  template:
    spec:
      containers:
      - name: longhorn-ui
        securityContext:
          privileged: true
```

Not ideal though, because it gives the longhorn-ui container more permissions than needed, but seems working fine as a workaround for now.

**Comment by n00bsi** [comment] 2024-04-10 08:25
Hi @akienz 

thanks

[core@osdemo1 ~]$ oc adm policy add-scc-to-user privileged -z longhorn-ui-service-account -n longhorn-system
clusterrole.rbac.authorization.k8s.io/system:openshift:scc:privileged added: "longhorn-ui-service-account"


[core@osdemo1 ~]$ oc logs longhorn-ui-6c8c4fcbb8-ncvqt -n longhorn-system
nginx: [alert] could not open error log file: open() "/var/log/nginx/error.log" failed (13: Permission denied)
2024/04/10 08:24:31 [emerg] 10#10: mkdir() "/var/lib/nginx/tmp/" failed (13: Permission denied)

**Comment by akienz** [comment] 2024-04-10 12:43
Might have found a clue here. Seems like when installing longhorn via helm chart the RoleBinding I mentioned is set when specifying installation on openshift `openshift.enabled: true`

Reference:

https://github.com/longhorn/longhorn/blob/603f173acf721c3dc909cad5897b4d6d3a18eda9/chart/templates/clusterrolebinding.yaml#L43

The instructions for installation via kubectl mention neither the privileged cluster role binds nor any openshift/okd specific instructions.

https://longhorn.io/docs/1.6.1/advanced-resources/os-distro-specific/okd-support/#install-longhorn only mentions helm based installation.

Can someone from Longhorn dev team confirm that installation via kubectl on openshift is a supported/tested setup? (ping @mantissahz) If I have the time i will try to reproduce this issue with helm based installation to confirm if this is specific to kubectl based installation

From my experience using longhorn on openshift/okd the only issue seems with SCC (security context) on initial deployment and update to v1.6.1. Rest worked out of the box for me

**Comment by n00bsi** [comment] 2024-04-10 13:09
@akienz 

If I understand right I need to install longhorn:

**helm install longhorn longhorn/longhorn --namespace longhorn-system --create-namespace --set openshift.enabled=true**


insead of this way:

wget https://raw.githubusercontent.com/longhorn/longhorn/v1.6.1/deploy/longhorn.yaml
copy to controlplane
oc apply -f longhorn.yaml

**Comment by akienz** [comment] 2024-04-10 13:42
Installation via helm seems to include all the required security settings for openshift, still not quite sure where the error comes from. Managed to deploy longhorn-ui via helm on a local openshift test vm, seems to run just fine

@n00bsi  If you have a fresh cluster without any existing longhorn installation, please try installation via helm, the command you provided should be correct. used

```
helm repo add longhorn https://charts.longhorn.io
helm repo update
kubectl create namespace longhorn-system
helm install longhorn longhorn/longhorn --namespace longhorn-system --set openshift.enabled=true
```
in my test install. If you have an existing longhorn installation with running volumes installed via kubectl, i would not risk upgrading with the helm chart

**Comment by n00bsi** [comment] 2024-04-10 13:46
thanks a lot - I will try tomorrow!

and update you !

**Comment by mantissahz** [comment] 2024-04-11 02:07
@innobead @akienz, yeah Installing the Longhorn with openshift by Helm is the better way.
And here is a README https://github.com/longhorn/longhorn/blob/master/chart/ocp-readme.md for your reference.

**Comment by n00bsi** [comment] 2024-04-11 11:30
@akienz 

I am behind a HTTP Proxy

so I tryed:

HTTPS_PROXY=http://proxy.domain.tld:3128 helm install longhorn longhorn/longhorn --namespace longhorn-system --set openshift.enabled=true

WARNING: Kubernetes configuration file is group-readable. This is insecure. Location: /var/home/core/.kube/config
WARNING: Kubernetes configuration file is world-readable. This is insecure. Location: /var/home/core/.kube/config
Error: INSTALLATION FAILED: Kubernetes cluster unreachable: Get "https://api.osctest.schuler.de:6443/version": x509: certificate signed by unknown authority

**Comment by n00bsi** [comment] 2024-04-12 04:52
Got it installed - but no GUI is there

did it this way:

sudo curl --proxy http://user:password@proxy.domain.tld:3128 -L https://mirror.openshift.com/pub/openshift-v4/clients/helm/latest/helm-linux-amd64 -o /usr/local/bin/helm

sudo chmod 755 /usr/local/bin/helm

HTTPS_PROXY=http://user:password@proxy.domain.tld:3128  helm repo add longhorn https://charts.longhorn.io

oc create namespace longhorn-system

export NO_PROXY=api.clustername.domain.tld

HTTPS_PROXY=http://user:password@proxy.domain.tld:3128 helm install longhorn longhorn/longhorn --namespace longhorn-system --set openshift.enabled=true




```
[core@osdemo1 ~]$ oc get pod -n longhorn-system
NAME                                                READY   STATUS    RESTARTS      AGE
csi-attacher-5c4bfdcf59-6lhj9                       1/1     Running   0             83s
csi-attacher-5c4bfdcf59-hblpn                       1/1     Running   0             83s
csi-attacher-5c4bfdcf59-ml9lz                       1/1     Running   0             83s
csi-provisioner-667796df57-8bkn2                    1/1     Running   0             83s
csi-provisioner-667796df57-f7xh6                    1/1     Running   0             83s
csi-provisioner-667796df57-vwv9g                    1/1     Running   0             83s
csi-resizer-694f8f5f64-22wfw                        1/1     Running   0             83s
csi-resizer-694f8f5f64-5t54x                        1/1     Running   0             83s
csi-resizer-694f8f5f64-x4mg8                        1/1     Running   0             83s
csi-snapshotter-959b69d4b-4s6hk                     1/1     Running   0             83s
csi-snapshotter-959b69d4b-mfbj6                     1/1     Running   0             83s
csi-snapshotter-959b69d4b-tdtb6                     1/1     Running   0             83s
engine-image-ei-5cefaf2b-842fc                      1/1     Running   0             88s
engine-image-ei-5cefaf2b-cblp2                      1/1     Running   0             88s
engine-image-ei-5cefaf2b-v9fxp                      1/1     Running   0             88s
instance-manager-26d3e3e1b04c9e675a720b194c633a25   1/1     Running   0             88s
instance-manager-b422ca0f562b542741091e59c7e72dd6   1/1     Running   0             88s
instance-manager-f7cf196dfd5ab2261108a0131d2ec443   1/1     Running   0             86s
longhorn-csi-plugin-2hf76                           3/3     Running   0             83s
longhorn-csi-plugin-6hsxr                           3/3     Running   0             83s
longhorn-csi-plugin-h22j2                           3/3     Running   0             83s
longhorn-driver-deployer-9f4fc86-crlzp              1/1     Running   1 (87s ago)   108s
longhorn-manager-456dp                              1/1     Running   0             107s
longhorn-manager-dltdm                              1/1     Running   0             107s
longhorn-manager-fsglx                              1/1     Running   0             108s
longhorn-ui-865869d445-b6sbs                        2/2     Running   0             108s
longhorn-ui-865869d445-bgjmj                        2/2     Running   0             108s

```


https://longhorn.apps.clustername.domain.tld/

![image](https://github.com/longhorn/longhorn/assets/66995098/76f896c6-2c36-4cb0-93ac-c6f00d590cf1)

**Comment by derekbit** [comment] 2024-04-12 05:26
@mantissahz is working on the issue with the users, so assigned it to @mantissahz first.

**Comment by n00bsi** [comment] 2024-04-12 05:32
by the way it is openshift **4.15.6** in the meantime

**Comment by n00bsi** [comment] 2024-04-12 08:35
HTTPS_PROXY=http://user:password@proxy.domain.tld:3128 helm upgrade longhorn longhorn/longhorn --namespace longhorn-system --set openshift.enabled=true --set ingress.enabled=true --set ingress.host=longhorn.apps.clustername.domain.tld

Now I can access:

http://longhorn.apps.clustername.domain.tld/#/volume

**Comment by derekbit** [comment] 2024-07-08 00:39
@mantissahz What's the status of the ticket? Any obstacles?

**Comment by mantissahz** [comment] 2024-07-08 01:15
>@mantissahz What's the status of the ticket? Any obstacles?

Now I am installing OpenShift 4.15.3 with Longhorn 1.6.1 on my local environment and testing if any error occurred.

**Comment by derekbit** [comment] 2024-07-08 15:47
Also need to update doc for OKD

**Comment by derekbit** [comment] 2024-07-09 02:40
@longhorn/qa need to validate the OKD installation by both longhorn-okd.yaml and helm.

**Comment by roger-ryao** [comment] 2024-07-11 06:13
**Verified on master-head 20240711**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/40b4207c14fe95a6fc084c8600e90e7a9d947620


**The test steps**

https://github.com/longhorn/longhorn/issues/8300#issuecomment-2214021354

1. Deploy an OKD 4.15 cluster
    - `openshift-install version` [4.15.0-0.okd-2024-03-10-010116](https://github.com/okd-project/okd/releases/download/4.15.0-0.okd-2024-03-10-010116/openshift-install-linux-4.15.0-0.okd-2024-03-10-010116.tar.gz)
    - `openshift-client (oc, kubectl) version` [4.15.0-0.okd-2024-03-10-010116](https://github.com/okd-project/okd/releases/download/4.15.0-0.okd-2024-03-10-010116/openshift-client-linux-4.15.0-0.okd-2024-03-10-010116.tar.gz)
    - `Fedora CoreOS metal raw image version` 39.20240407.3.0
    - https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240407.3.0/x86_64/fedora-coreos-39.20240407.3.0-metal.x86_64.raw.xz
    - https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240407.3.0/x86_64/fedora-coreos-39.20240407.3.0-metal.x86_64.raw.xz.sig
    - `Fedora CoreOS ISO image version` fedora-coreos-39.20240407.3.0-live.x86_64.iso
    - https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240407.3.0/x86_64/fedora-coreos-39.20240407.3.0-live.x86_64.iso


**Result passed**

- [x] require/doc: https://github.com/longhorn/website/pull/941
- [x] Deploy Longhorn using the manifest [deploy/longhorn-okd.yaml](https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn-okd.yaml)
- [x] Deploy Longhorn using Helm
- [x] Create a ticket for adding documentation on how to deploy an OKD cluster on KVM
  - https://github.com/longhorn/longhorn/issues/8978

**Closed by roger-ryao** 2024-07-11 06:13 UTC
Labels: kind/bug, area/install-uninstall-upgrade, priority/0, require/doc
