### ISSUE TITLE
[Question] NFS ganesha fails continously.

### ISSUE THREAD

**Issue by anissmajlovic** [longhorn/longhorn#2284] opened 2021-03-02 09:00 UTC
**Question**

**Environment:**
 - Longhorn version: 1.1.0
 - Kubernetes version: v1.18.14
 - Node config
   - Ubuntu 18.04.05
   - 16 vCPU
   - 32 GB RAM
   - DSSD
   - 20 Gbps between 5 ESXi nodes
 - VMware

**Additional context**

Hello everyone

I have a share-manager pod that is crashing all the time. I am not sure what to check, it is something about: "ganesha.nfsd failed with error: signal: killed, output: "

Anyone who can help me, please?

Logs output from share-manager:
-------------------------------------
time="2021-03-02T08:50:15Z" level=info msg="starting RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
--
Tue, Mar 2 2021 9:50:15 am | time="2021-03-02T08:50:15Z" level=info msg="ending RLIMIT_NOFILE rlimit.Cur 1048576, rlimit.Max 1048576"
Tue, Mar 2 2021 9:50:15 am | time="2021-03-02T08:50:15Z" level=warning msg="waiting with nfs server start, volume is not attached" volume=pvc-d0e5dbd9-d2f3-4505-940f-e84aea64c74d
Tue, Mar 2 2021 9:50:20 am | time="2021-03-02T08:50:20Z" level=info msg="starting nfs server, volume is ready for export" volume=pvc-d0e5dbd9-d2f3-4505-940f-e84aea64c74d
Tue, Mar 2 2021 9:50:20 am | time="2021-03-02T08:50:20Z" level=info msg="Running NFS server!"
Tue, Mar 2 2021 9:50:20 am | time="2021-03-02T08:50:20Z" level=info msg="starting health check for volume" volume=pvc-d0e5dbd9-d2f3-4505-940f-e84aea64c74d
Tue, Mar 2 2021 9:50:33 am | time="2021-03-02T08:50:33Z" level=info msg="share manager received signal terminated to exit"
Tue, Mar 2 2021 9:50:33 am | time="2021-03-02T08:50:33Z" level=info msg="nfs server is shutting down"
Tue, Mar 2 2021 9:50:33 am | time="2021-03-02T08:50:33Z" level=error msg="nfs server exited with error" error="ganesha.nfsd failed with error: signal: killed, output: "
Tue, Mar 2 2021 9:50:33 am | time="2021-03-02T08:50:33Z" level=fatal msg="Error running start command: ganesha.nfsd failed with error: signal: killed, output: ."
-------------------------------------

Thanks

**Comment by joshimoo** [comment] 2021-03-02 14:58
@anissmajlovic Can you check if you have ipv6 enabled on your host node.
probably related to https://github.com/longhorn/longhorn/issues/2197

If the issue is indeed disabled IPV6 you can test the new share-manager image that will be released with v1.1.1
`longhornio/longhorn-share-manager:v1_20210302`

**Comment by anissmajlovic** [comment] 2021-03-02 23:35
> @anissmajlovic Can you check if you have ipv6 enabled on your host node.
> probably related to #2197
> 
> If the issue is indeed disabled IPV6 you can test the new share-manager image that will be released with v1.1.1
> `longhornio/longhorn-share-manager:v1_20210302`

Hi Joshimoo

I tried to disable ipv6 for all nodes and it didn't help, also I reboted worker nodes.

-> sudo tee -a /etc/sysctl.d/99-kubernetes.conf <<EOF
-> net.ipv6.conf.all.disable_ipv6 = 1
-> net.ipv6.conf.default.disable_ipv6 = 1
-> EOF
-> sudo vi /etc/sysctl.d/99-kubernetes.conf
-> sudo sysctl --system

Then I upgraded share manager to:
-> longhornio/longhorn-share-manager:v1_20210302
also didn't help.

Any other idea? I am checking on Internet but I can't find anything..

Thanks for replay.

**Comment by joshimoo** [comment] 2021-03-03 08:03
@anissmajlovic I meant that if the cluster has ipv6 disabled at boot time, ganesha will fail to come up.
The above image should fix that issue, best to wait for longhorn v1.1.1

**Comment by anissmajlovic** [comment] 2021-03-03 08:43
@joshimoo

First thank you very much for your replay.

I am sorry, just one more time to clarify.
I thought that if is enabled that I have to disable IPv6. For now I enabled IPv6 again using the commands above and also I upgraded share manager to latest version : longhornio/longhorn-share-manager:v1_20210302
Proper will be that IPv6 is enabled in cluster, right and then to upgrade share-manager to latest version or wait for Longhorn 1.1.1?

Thanks

**Comment by joshimoo** [comment] 2021-03-03 09:02
@c3y1huang if you have time can you follow up with this, after the new e2e test is ran successfully.

**Comment by anissmajlovic** [comment] 2021-03-03 09:07
Thank you both @joshimoo  and @c3y1huang 

Kind regards

**Comment by c3y1huang** [comment] 2021-03-05 03:43
@anissmajlovic this seems related to https://github.com/longhorn/longhorn-share-manager/pull/7 and should be fixed in the next release.

**Comment by c3y1huang** [comment] 2021-03-05 05:32
> @anissmajlovic this seems related to [longhorn/longhorn-share-manager#7](https://github.com/longhorn/longhorn-share-manager/pull/7) and should be fixed in the next release.

Actually, on a second look, wipe my previous comment, it's possibly not related.

**Comment by c3y1huang** [comment] 2021-03-05 05:53
@anissmajlovic are you able to extract `/tmp/ganesha.log` from within the share-manager before it crash? Could you also provide the support bundle?

**Comment by smajlovica** [comment] 2021-03-08 08:24
Hi

Sorry for late reply. I am waiting for app team to troubleshoot issue from their side. I want to be sure that is not a problem on the app side and then I will attach logs.

Thank you very much for your support.

**Comment by PhanLe1010** [comment] 2021-07-23 00:30
Close this one because of no response from the user. Feel free to reopen it if you have update

**Closed by PhanLe1010** 2021-07-23 00:30 UTC
Labels: area/rwx, kind/question
