### ISSUE TITLE
[BUG] Unable to backup backing image through Longhorn UI

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#10023] opened 2024-12-20 02:21 UTC
## Describe the bug

Trying to backup backing image through Longhorn UI on v1.8.x-head (longhorn-ui 4f6b1eb)  or master-head (longhorn-ui cf5fcff), got `500 Internal Server Error`:

![backup-button](https://github.com/user-attachments/assets/74e9fed8-8008-4768-bfdb-3c000d1229a7)

```
POST http://54.209.76.137:30000/v1/backingimages/test?action=backupBackingImageCreate
{"actions":{},"code":"Internal Server Error","detail":"","links":{"self":"http://54.209.76.137:30000/v1/backingimages/test"},"message":"EOF","status":500,"type":"error"}
```

Both v1 and v2 backing image have the same issue.

## To Reproduce

Backup backing image through Longhorn UI

## Environment

 - Longhorn version: master-head and v1.8.x-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of control plane nodes in the cluster:
   - Number of worker nodes in the cluster:
 - Node config
   - OS type and version:
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment] 2024-12-20 02:30
cc @houhoucoop

**Comment by houhoucoop** [comment] 2024-12-20 03:11
I can see `500` when attempting to back up the same image twice.
`"message": "failed to create backup backing image 'parrot': backup backing image 'parrot' already exists"`

**Comment by houhoucoop** [comment] 2024-12-20 03:12
Since it's a 500 error, I think the root cause is likely on the backup side.

**Comment by yangchiu** [comment] 2024-12-20 03:23
> I can see `500` when attempting to back up the same image twice. `"message": "failed to create backup backing image 'parrot': backup backing image 'parrot' already exists"`

It doesn't seem to be what I encountered. Also I observed inconsistent behavior when trying to back up from the following two locations. Could you try both of them?
 
![backup-button](https://github.com/user-attachments/assets/618f914f-2fd6-459a-a014-e31697fcc7c4)

![backup-menu](https://github.com/user-attachments/assets/e1f275d7-79a7-404a-b784-75f9183d1580)

**Comment by houhoucoop** [comment] 2024-12-20 03:58
These are all the cases I have tested, not sure which ones are expected and which are defects.
#### One backup target: default
- Backup single backing image
  - **If the backup exists:** `500` (backup already exists)
  - **If the backup does not exist:** `200` (success)

#### Multiple backup targets: default, cifs
- Backup the same backing image
  - **Select backup target `default`:** `200` (success)
  - **Select backup target `cifs`** `500` (backup already exists)

#### Bulk backup action:
- Attempt bulk backup for one or multiple backing images
  - **Select one backing image** `500` (EOF)
  - **Select multiple backing images** `500` (EOF)

**Comment by houhoucoop** [comment] 2024-12-20 04:00
cc @a110605

**Comment by houhoucoop** [comment] 2024-12-23 04:30
@mantissahz Can you confirm if Case 2 is a defect? frontend needs to make corresponding UI adjustments.

**Comment by houhoucoop** [comment] 2024-12-23 06:37
> > @mantissahz Can you confirm if Case 2 is a defect? frontend needs to make corresponding UI adjustments.
> 
> It is not allowed because UI creates the `BackupBackingImage` of a backing image using the same BackupBackingImage name (the backing name) for different backup targets.
> 
> 1. UI can allow users to fill in a custom name when (and passed it by the payload) creating a backup backing image.
>    https://github.com/longhorn/longhorn-manager/blob/5187ffde3c6c2d009b5406db7193966463505b46/api/model.go#L180-L196.
> 2. or the Backend can use a random name to create the `BackupBackingImage`, then UI displays the
>    name of a `BackupBackingImage` by the backing image name in the response payload.

I see, I prefer option 2. 
After checking the frontend code, we don't generate UUIDs, so generating them on backend may ensure more consistency. What do you think?

**Comment by mantissahz** [comment] 2024-12-23 08:27
>I see, I prefer option 2.
After checking the frontend code, we don't generate UUIDs, so generating them on backend may ensure more consistency. What do you think?

The backend can handle that if the `name` in the request payload is empty or equal to the backing image name, it will generate a random name to create a backup of the backing image.

The UI can still allow users to have a costume `BackupBackingName` name when creating a backup of the backing image if you want to.

**Comment by ChanYiLin** [comment] 2024-12-23 10:06
I will fix the issue tomorrow

**Comment by derekbit** [comment] 2024-12-23 12:56
Recent issues are mostly related to the APIs and the integration between the backend and frontend.

@houhoucoop In addition to implementing the UI part, remember to self-validate if the functionalities work before moving it to ready-for-testing. This will make you familiar with Longhorn more.

cc @a110605 @ChanYiLin @mantissahz  @innobead

**Comment by ChanYiLin** [comment] 2024-12-24 02:29
cc @yangchiu 
I didn't encounter this issue when doing the backup
```
{"actions":{},"code":"Internal Server Error","detail":"","links":{"self":"http://54.209.76.137:30000/v1/backingimages/test"},"message":"EOF","status":500,"type":"error"}`
```

Please try again with the test steps https://github.com/longhorn/longhorn/issues/10023#issuecomment-2559589425
And see if this happens again

**Comment by chriscchien** [comment] 2024-12-25 10:09
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-ui/commit/f903b6a4b724a7e05cce1509d5465e48d98c6967), v1.8.x(https://github.com/longhorn/longhorn-ui/commit/47c97e0dc42f0431909e6992ccb42884332bd648) with test [steps](https://github.com/longhorn/longhorn/issues/10023#issuecomment-2559589425)

**Closed by chriscchien** 2024-12-25 10:09 UTC
Labels: kind/bug, area/ui, severity/1, reproduce/always, priority/0, area/volume-backup-restore, area/backing-image, require/backport
