### ISSUE TITLE
[QUESTION] How to debug Longhorn

### ISSUE THREAD

**Issue by ternes3** [longhorn/longhorn#3043] opened 2021-09-21 17:10 UTC
**Question**

I've been working with Rancher and Longhorn for a relatively short time now. So far, everything has worked as expected, until now. Now I have chosen RKE2 instead of RKE1 to build a Kubernetes "cluster" (:=1 node). In doing so, I ran into a first problem, having trouble identifying this exactly. So my question is, how do I debug Longhorn. So far I have looked at the logs of the workloads (pods), as well as syslog and dmesg of my "host" system. As far as I understand Longhorn is a block device provider, which uses iscsi under the hood. Creating the image on my host's filesystem seems to work (I can see an intact image; /var/lib/longhorn). 

How can I proceed now. 

**Environment:**
 - Longhorn version: 1.1.2 (Rancher Catalog Apps, recent version)
 - Kubernetes version: v1.21.4 (#RKE2)
 - Node config 1 single node
   - OS type and version Ubuntu 20.04.3 (latest updates installed)
   - CPU per node: 6
   - Memory per node: 16GB
   - Disk type NVMe SSD
   - Network bandwidth and latency between the nodes: N/A := 1 single node
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Proxmox (kvm)

**Additional context**

I could only see a warning within the logs so far. Ref: https://github.com/longhorn/go-iscsi-helper/issues/40

I am running an ubuntu 20.04.3 host with RKE2 on top. Current version of rancher := 2.6.0 and longhorn := 1.1.2 installed via Rancher Catalog Apps.

It is not possible for me to attach a volume to an pod. Following warnings I see inside of the logs.

```shell
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Connecting to remote: 10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Opening: 10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Adding backend: tcp://10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Start monitoring tcp://10.42.0.118:10000\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"Get backend tcp://10.42.0.118:10000 revision counter 0\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: time=\"2021-09-20T08:09:07Z\" level=info msg=\"device pvc-abf2502c-bd3a-41cf-88be-f25743c2f742: SCSI device /dev/longhorn/pvc-abf2502c-bd3a-41cf-88be-f25743c2f742 shutdown\""
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: go-iscsi-helper: command failed: fork/exec /usr/sbin/tgtd: exec format error"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: panic: fork/exec /usr/sbin/tgtd: exec format error"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: "
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: goroutine 101 [running]:"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: github.com/longhorn/go-iscsi-helper/iscsi.startDaemon(0xc0000100c8, 0x100)"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: \t/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go:201 +0x449"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: created by github.com/longhorn/go-iscsi-helper/iscsi.StartDaemon"
time="2021-09-20T08:09:14Z" level=warning msg="pvc-abf2502c-bd3a-41cf-88be-f25743c2f742-e-203df684: \t/go/src/github.com/longhorn/longhorn-engine/vendor/github.com/longhorn/go-iscsi-helper/iscsi/target.go:165 +0xad"```
```

**Comment by jenting** [comment] 2021-09-21 21:37
@ternes3

Could you please use the issue at this repo to help us easy to track it? In general, we won't track the issue in the [go-iscsi-helper repo](https://github.com/longhorn/go-iscsi-helper).

Back to your question, please make sure your requirement meet these [requirements](https://longhorn.io/docs/1.2.0/deploy/install/#installation-requirements). Especially to check all your host machine have to install `iscsiadm` and enable the `iscsid` daemon. Or you could apply the [yaml manifest](https://github.com/longhorn/longhorn/blob/master/deploy/prerequisite/longhorn-iscsi-installation.yaml) into your cluster.

Besides that, please check the `/usr/bin/tgtd` command is correctly, ref to [Ubuntu issue](https://ubuntuforums.org/showthread.php?t=2402704).

**Comment by ternes3** [comment] 2021-09-22 07:21
Thank you for the answer. I will take this into account for future issues. 

I have checked the requirements on my system according to the linked resource. So far everything is in place and installed. 

tgt is running. tgtd does not exist as systemctl service. 

```ternes3@kubernetes:/$ sudo service tgt status
● tgt.service - (i)SCSI target daemon
     Loaded: loaded (/lib/systemd/system/tgt.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-09-22 07:15:16 UTC; 2min 32s ago
       Docs: man:tgtd(8)
    Process: 3227262 ExecStartPost=/usr/sbin/tgtadm --op update --mode sys --name State -v offline (code=exited, status=0/SUCCESS)
    Process: 3227269 ExecStartPost=/usr/sbin/tgt-admin -e -c /etc/tgt/targets.conf (code=exited, status=0/SUCCESS)
    Process: 3227280 ExecStartPost=/usr/sbin/tgtadm --op update --mode sys --name State -v ready (code=exited, status=0/SUCCESS)
   Main PID: 3227260 (tgtd)
     Status: "Starting event loop..."
      Tasks: 1
     Memory: 1.3M
     CGroup: /system.slice/tgt.service
             └─3227260 /usr/sbin/tgtd -f

Sep 22 07:15:16 kubernetes systemd[1]: Starting (i)SCSI target daemon...
Sep 22 07:15:16 kubernetes tgtd[3227260]: tgtd: iser_ib_init(3431) Failed to initialize RDMA; load kernel modules?
Sep 22 07:15:16 kubernetes tgtd[3227260]: tgtd: work_timer_start(146) use timer_fd based scheduler
Sep 22 07:15:16 kubernetes tgtd[3227260]: tgtd: bs_init(387) use signalfd notification
Sep 22 07:15:16 kubernetes systemd[1]: Started (i)SCSI target daemon.
```

```
ternes3@kubernetes:/$ sudo service tgtd status
Unit tgtd.service could not be found.
```

```
ternes3@kubernetes:/$ service iscsid status
● iscsid.service - iSCSI initiator daemon (iscsid)
     Loaded: loaded (/lib/systemd/system/iscsid.service; enabled; vendor preset: enabled)
     Active: active (running) since Wed 2021-09-22 07:12:21 UTC; 8min ago
TriggeredBy: ● iscsid.socket
       Docs: man:iscsid(8)
    Process: 3221802 ExecStartPre=/lib/open-iscsi/startup-checks.sh (code=exited, status=0/SUCCESS)
    Process: 3221806 ExecStart=/sbin/iscsid (code=exited, status=0/SUCCESS)
   Main PID: 3221809 (iscsid)
      Tasks: 2 (limit: 11794)
     Memory: 3.3M
     CGroup: /system.slice/iscsid.service
             ├─3221808 /sbin/iscsid
             └─3221809 /sbin/iscsid

Sep 22 07:12:20 kubernetes systemd[1]: Starting iSCSI initiator daemon (iscsid)...
Sep 22 07:12:20 kubernetes iscsid[3221806]: iSCSI logger with pid=3221808 started!
Sep 22 07:12:20 kubernetes systemd[1]: iscsid.service: Failed to parse PID from file /run/iscsid.pid: Invalid argument
Sep 22 07:12:21 kubernetes systemd[1]: Started iSCSI initiator daemon (iscsid).
Sep 22 07:12:21 kubernetes iscsid[3221808]: iSCSI daemon with pid=3221809 started!
```

```
ternes3@kubernetes:/$ curl -sSfL https://raw.githubusercontent.com/longhorn/longhorn/v1.2.0/scripts/environment_check.sh | bash
daemonset.apps/longhorn-environment-check created
waiting for pods to become ready (0/1)
all pods ready (1/1)

  MountPropagation is enabled!

cleaning up...
daemonset.apps "longhorn-environment-check" deleted
clean up complete
```

**Comment by jenting** [comment] 2021-09-22 07:33
How did you create the volume, from the GUI with `Frontend=iSCSI`? Or from PV/PVC by yaml manifest?

![Screenshot from 2021-09-22 15-32-34](https://user-images.githubusercontent.com/49380831/134301556-d5f49b7f-e66f-456f-8fb3-57051b844074.png)

**Comment by jenting** [comment] 2021-09-22 07:46
Beside that, could you please exec into one of the longhorn-manager-r-xxx _or_ longhorn-manager-e-xxx Pod to see if the binary `/usr/sbin/tgtd` is there? And check the file format `file /usr/sbin/tgtd`.

**Comment by ternes3** [comment] 2021-09-22 08:25
I used a PVC

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test
  namespace: default
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
```

current:

```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: driver.longhorn.io
  creationTimestamp: "2021-09-21T13:59:25Z"
  finalizers:
  - kubernetes.io/pvc-protection
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        f:accessModes: {}
        f:resources:
          f:requests:
            .: {}
            f:storage: {}
        f:storageClassName: {}
        f:volumeMode: {}
    manager: rancher
    operation: Update
    time: "2021-09-21T13:59:25Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:pv.kubernetes.io/bind-completed: {}
          f:pv.kubernetes.io/bound-by-controller: {}
          f:volume.beta.kubernetes.io/storage-provisioner: {}
      f:spec:
        f:volumeName: {}
      f:status:
        f:accessModes: {}
        f:capacity:
          .: {}
          f:storage: {}
        f:phase: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-09-21T13:59:27Z"
  name: test
  namespace: default
  resourceVersion: "1129303"
  uid: 37f99108-5c98-498f-9e77-632b2a0af2f6
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-37f99108-5c98-498f-9e77-632b2a0af2f6
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 1Gi
  phase: Bound
```

Besides of that, tgtd is on both pods "empty".

```
root@instance-manager-e-012c797d:/# file /usr/sbin/tgtd
/usr/sbin/tgtd: empty

root@instance-manager-r-c77beea5:/# file /usr/sbin/tgtd
/usr/sbin/tgtd: empty
```

<img width="1395" alt="Bildschirmfoto 2021-09-22 um 11 24 29" src="https://user-images.githubusercontent.com/1932977/134308899-5fd8a622-a33e-4c77-be9b-79653fb19123.png">

**Comment by jenting** [comment] 2021-09-22 09:31
Could you please check your longhorn-engine image? Is it from the longhornio/longhorn-engine?
Besides that, what's the CPU architecture the host is? AMD64 or ARM64?

**Comment by ternes3** [comment] 2021-09-22 09:44
Its is the mirrored version from rancher: rancher/mirrored-longhornio-longhorn-engine:v1.1.2
:= sha256:f4a3aa420d26fb9d396959af36bec84b58a1cb374ead9ab3f9b82e46e6357115

CPU architecture is AMD64

**Comment by jenting** [comment] 2021-09-23 02:16
Oops, typo. I mean the `instance-manager-image` image.

**Comment by ternes3** [comment] 2021-09-23 06:34
Thats rancher/mirrored-longhornio-longhorn-instance-manager:v1_20210621
sha256:84808d9bc60844e8a88d91a2b5b0289aea465d2c8340696d4dc396fd47674dba

**Comment by jenting** [comment] 2021-09-23 06:57
No clue now, don't know why your `/usr/sbin/tgtd` inside the instance-manager Pods is invalid.
Perhaps you could try deleting all the instance manager Pods, and Longhorn manager will help recreate these.
```shell
kubectl delete pod -l longhorn.io/component=instance-manager
```

**Comment by ternes3** [comment] 2021-09-23 07:21
Alright, thanks. Delete and recreate was my first attempt at a solution. 

This did not work, I have now tested the instance manager image against 
longhornio/longhorn-instance-manager:v1_20210917. 

```
root@instance-manager-e-6ad90251:/# file /usr/sbin/tgtd
/usr/sbin/tgtd: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, BuildID[sha1]=bb1c7e9bd61ef46726b9daa84b291348c9243712, for GNU/Linux 3.2.0, stripped
```

it works! 

<img width="1424" alt="Bildschirmfoto 2021-09-23 um 10 19 00" src="https://user-images.githubusercontent.com/1932977/134468572-884e79b6-a8c9-43a2-be70-aeae10d25e20.png">

**Comment by jenting** [comment] 2021-09-23 07:27
We can't 100% sure if using the newer instance manager without any side effects.

Could you please check the `longhornio/longhorn-instance-manager:v1_20210621` works for you?

**Comment by ternes3** [comment] 2021-09-23 08:25
longhornio/longhorn-instance-manager:v1_20210621 does not work := 
```
root@instance-manager-e-5d4af7ae:/# file /usr/sbin/tgtd
/usr/sbin/tgtd: empty
```

**Comment by kaxing** [comment] 2021-09-23 09:17
Hey ternes3 , it works on my local environment, can you check again?

```console
root@instance-manager-e-0ae12af8:/# which tgtd; longhorn-instance-manager |grep VER -A1
/usr/sbin/tgtd
VERSION:
   v1_20210621

root@instance-manager-e-0ae12af8:/# file $(which tgtd)
/usr/sbin/tgtd: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=e981c7211cf212db7bfe7ef53efeaa6a211eea99, stripped
```

**Comment by ternes3** [comment] 2021-09-23 09:19
sure

```
root@instance-manager-e-debae733:/# which tgtd; longhorn-instance-manager |grep VER -A1
/usr/sbin/tgtd
VERSION:
   v1_20210621
root@instance-manager-e-debae733:/# file $(which tgtd)
/usr/sbin/tgtd: empty
```

**Comment by jenting** [comment] 2021-09-23 13:16
No further clue now, probably you could try to change the System Managed Pod Image Pull Policy as `always` to delete all the longhorn-instance-manager Pods to make the image pull from remote again.

Or you could just pull the image by docker command `docker pull onghornio/longhorn-instance-manager:v1_20210621` and check if the `/usr/sbin/tgtd` is valid or not.

**Comment by jenting** [comment] 2021-10-01 00:42
I'll close this issue now since we can't reproducible at our site, also the current workaround you find is to use a new instance manager container image.
Feel free to reopen it if you have further questions.

**Closed by jenting** 2021-10-01 00:42 UTC
Labels: kind/question
