### ISSUE TITLE
[BUG] Service account secret mount spam on longhorn-manager restart

### ISSUE THREAD

**Issue by excieve** [longhorn/longhorn#1877] opened 2020-10-13 14:53 UTC
**Describe the bug**
On some nodes where `longhorn-manager`s have been restarting a lot for some reason, there were growing numbers of `/run/secrets/kubernetes.io/serviceaccount` tmpfs mounts. At some point reaching 4k+ duplicate mounts leading to `df` taking 20s to execute and grinding docker to timeout on kubelet communication.

It appears that service account mounts grow exponentially with each restart.

This doesn't happen when restarting other pods.

**To Reproduce**
1. Install Longhorn on the cluster
2. On any node with `longhorn-manager` pod on it, observe current mounts (e.g. `/etc/mtab` or execute `df`), note how many `/run/secrets/kubernetes.io/serviceaccount` mounts are there
3. Kill the `longhorn-manager` pod on this node and let it successfully start again
4. Observe the mounts on this node again and see duplicate mount added

**Expected behavior**
No duplicate mounts present on the node.

**Environment:**
 - Longhorn version: 1.0.2
 - Kubernetes version: 1.17.9-eks
 - Node OS type and version: EKS-optimised AL2

**Additional context**
Might be related to #1757.

Probably an issue on itself, but the reason `longhorn-manager` restarts (without us killing it) is this panic:
```
E1010 09:17:42.204022       1 runtime.go:69] Observed a panic: &runtime.TypeAssertionError{_interface:(*runtime._type)(0x15c9880), concrete:(*runtime._type)(0x16855a0), asserted:(*runtime._type)(0x17d40c0), missingMethod:""} (interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1beta1.Replica)
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:76
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:65
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:51
/usr/local/go/src/runtime/panic.go:967
/usr/local/go/src/runtime/iface.go:260
/go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:106
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:209
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:556
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:265
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546
/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71
/usr/local/go/src/runtime/asm_amd64.s:1373
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1beta1.Replica [recovered]
    panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1beta1.Replica
goroutine 245 [running]:
k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x105
panic(0x1615760, 0xc009fd4ba0)
    /usr/local/go/src/runtime/panic.go:967 +0x166
github.com/longhorn/longhorn-manager/controller.NewReplicaController.func3(0x16855a0, 0xc00d6e1020)
    /go/src/github.com/longhorn/longhorn-manager/controller/replica_controller.go:106 +0x69
k8s.io/client-go/tools/cache.ResourceEventHandlerFuncs.OnDelete(...)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/controller.go:209
k8s.io/client-go/tools/cache.(*processorListener).run.func1.1(0xc0000a4018, 0x0, 0x0)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:556 +0x17e
k8s.io/apimachinery/pkg/util/wait.ExponentialBackoff(0x989680, 0x3ff0000000000000, 0x3fb999999999999a, 0x5, 0x0, 0xc0095c5e18, 0x1, 0x0)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:265 +0x51
k8s.io/client-go/tools/cache.(*processorListener).run.func1()
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:548 +0x79
k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000a91f60)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5f
k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc0095c5f60, 0xdf8475800, 0x0, 0x1, 0xc000614660)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
k8s.io/apimachinery/pkg/util/wait.Until(...)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88
k8s.io/client-go/tools/cache.(*processorListener).run(0xc0002a1a00)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/client-go/tools/cache/shared_informer.go:546 +0x9b
k8s.io/apimachinery/pkg/util/wait.(*Group).Start.func1(0xc0008341b0, 0xc000275a70)
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:71 +0x51
created by k8s.io/apimachinery/pkg/util/wait.(*Group).Start
    /go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:69 +0x62
```

**Comment by joshimoo** [comment] 2020-10-13 16:32
Thanks for reporting this, we will look into this.

**Comment by excieve** [comment] 2020-10-15 21:05
One more data point — when checking mounts inside the `longhorn-manager` container after the restart, it looks like this:
```
root@longhorn-manager-dqmhj:/# cat /etc/mtab |grep service
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs ro,relatime 0 0
```

The duplicate one is mounted as `rw` it seems.

**Comment by PhanLe1010** [comment] 2020-10-15 21:28
This is an interesting issue. 
Left a comment to subscribe.

**Comment by joshimoo** [comment] 2020-10-21 22:35
@excieve thanks for reporting, I fixed the longhorn manager crash in https://github.com/longhorn/longhorn-manager/pull/725
which will be available when we release longhorn v1.1 please let us know if you are still having issues then :)

**Comment by yasker** [comment] 2020-12-22 18:49
Close this one for now, since the fix has shipped with v1.1.0 release.

If you continue to experience issues, feel free to reopen again.

**Comment by excieve** [comment] 2021-02-01 17:17
@yasker We just had another instance of this issue. It seems the mount is still there for our deployments of `longhorn-manager` with Longhorn v1.1.0 (upgraded from v1.0.2), installed through a Rancher app. Is there something extra we need to do about it?

The `longhorn-manager` DaemonSet looks like this:
```.yaml
apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    deprecated.daemonset.template.generation: "14"
    longhorn.io/last-applied-tolerations: '[{"key":"nodetype","operator":"Exists","effect":"NoSchedule"}]'
  creationTimestamp: "2020-07-19T00:16:58Z"
  generation: 14
  labels:
    app: longhorn-manager
    app.kubernetes.io/instance: longhorn-system
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/name: longhorn
    app.kubernetes.io/version: v1.1.0
    helm.sh/chart: longhorn-1.1.0
    io.cattle.field/appId: longhorn-system
  name: longhorn-manager
  namespace: longhorn-system
  resourceVersion: "227857942"
  selfLink: /apis/apps/v1/namespaces/longhorn-system/daemonsets/longhorn-manager
  uid: 4082c2e6-bf80-4097-937e-f455cf7626b4
spec:
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: longhorn-manager
  template:
    metadata:
      annotations:
        cattle.io/timestamp: "2020-08-18T23:06:35Z"
        field.cattle.io/ports: '[[{"containerPort":9500,"dnsName":"longhorn-manager","kind":"ClusterIP","name":"manager","protocol":"TCP"}]]'
        kubectl.kubernetes.io/restartedAt: "2020-08-23T23:49:18+03:00"
      creationTimestamp: null
      labels:
        app: longhorn-manager
        app.kubernetes.io/instance: longhorn-system
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/name: longhorn
        app.kubernetes.io/version: v1.1.0
        helm.sh/chart: longhorn-1.1.0
    spec:
      containers:
      - command:
        - longhorn-manager
        - -d
        - daemon
        - --engine-image
        - longhornio/longhorn-engine:v1.1.0
        - --instance-manager-image
        - longhornio/longhorn-instance-manager:v1_20201216
        - --share-manager-image
        - longhornio/longhorn-share-manager:v1_20201204
        - --manager-image
        - longhornio/longhorn-manager:v1.1.0
        - --service-account
        - longhorn-service-account
        env:
        - name: DEFAULT_SETTING_PATH
          value: /var/lib/longhorn-setting/default-setting.yaml
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        image: longhornio/longhorn-manager:v1.1.0
        imagePullPolicy: IfNotPresent
        name: longhorn-manager
        ports:
        - containerPort: 9500
          name: manager
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          tcpSocket:
            port: 9500
          timeoutSeconds: 1
        resources: {}
        securityContext:
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /host/dev/
          name: dev
        - mountPath: /host/proc/
          name: proc
        - mountPath: /var/run/
          mountPropagation: Bidirectional
          name: varrun
        - mountPath: /var/lib/longhorn/
          mountPropagation: Bidirectional
          name: longhorn
        - mountPath: /var/lib/longhorn-setting/
          name: longhorn-default-setting
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      serviceAccount: longhorn-service-account
      serviceAccountName: longhorn-service-account
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: nodetype
        operator: Exists
      volumes:
      - hostPath:
          path: /dev/
          type: ""
        name: dev
      - hostPath:
          path: /proc/
          type: ""
        name: proc
      - hostPath:
          path: /var/run/
          type: ""
        name: varrun
      - hostPath:
          path: /var/lib/longhorn/
          type: ""
        name: longhorn
      - configMap:
          defaultMode: 420
          name: longhorn-default-setting
        name: longhorn-default-setting
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 100%
    type: RollingUpdate
status:
  currentNumberScheduled: 24
  desiredNumberScheduled: 24
  numberAvailable: 24
  numberMisscheduled: 0
  numberReady: 24
  observedGeneration: 14
  updatedNumberScheduled: 24
```

**Comment by shuo-wu** [comment] 2021-02-09 04:51
1. Do you mean the previous mount records? Can you try to manually umount the extra layers for each longhorn manager pod then restart it? (Do it one by one to prevent crashing the whole system)
2. I cannot reproduce this issue with the following step
    1. Deploy Longhorn v1.1
    2. Run `docker kill "$(docker ps | grep longhornio/longhorn-manager| awk '{print $1}')"` on a worker node. So that the existing manager pod will be restarted rather than being replaced by a new pod.
    3. Check the mount inside the manager pod. No redundant mount record.
    ```
    root@longhorn-manager-mq2wd:/# df
    Filesystem                                     1K-blocks     Used Available Use% Mounted on
    overlay                                         82018832 25096464  52737928  33% /
    tmpfs                                              65536        0     65536   0% /dev
    tmpfs                                            2019568        0   2019568   0% /sys/fs/cgroup
    /dev/sda                                        82018832 25096464  52737928  33% /etc/hosts
    udev                                             1988216        0   1988216   0% /host/dev
    tmpfs                                            2019568        0   2019568   0% /host/dev/shm
    shm                                                65536        0     65536   0% /dev/shm
    tmpfs                                            2019568       12   2019556   1% /run/secrets/kubernetes.io/serviceaccount
    longhorn-test-nfs-svc.default:/opt/backupstore   4063232   842752   2995200  22% /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore
    ```

**Comment by PhanLe1010** [comment] 2021-02-24 01:54
**Reproduce steps:**
1. Install Longhorn v1.1.0 from Rancher UI
1. SSH into a worker node that has a longhorn-manager pod running
1. check the mount point `/run/secrets/kubernetes.io/serviceaccount` by running
   ```
   root@phan-cluster-v44-worker-1:~# findmnt  /run/secrets/kubernetes.io/serviceaccount
   TARGET                                    SOURCE FSTYPE OPTIONS
   /run/secrets/kubernetes.io/serviceaccount tmpfs  tmpfs  rw,relatime
   ```
1. Kill the longhorn-manager pod on the above node
1. Check the mount point `/run/secrets/kubernetes.io/serviceaccount` by running
   ```
   root@phan-cluster-v44-worker-1:~# findmnt  /run/secrets/kubernetes.io/serviceaccount
   TARGET                                    SOURCE FSTYPE OPTIONS
   /run/secrets/kubernetes.io/serviceaccount tmpfs  tmpfs  rw,relatime
   /run/secrets/kubernetes.io/serviceaccount tmpfs  tmpfs  rw,relatime
   ```
1. Observe that each time the longhorn-manager pod restarts, the number of mount point increase by 1

**Cause:**
It is because we forgot to remove the bidirectional mount `/var/run` from the Helm chart installation. We fixed it this in https://github.com/longhorn/longhorn/issues/2200. The fix is available in v1.1.1 release

**Workaround:**
@excieve, you can try to manually edit the `longhorn-manager` DaemonSet to remove the bidirectional mount `/var/run` same as in https://github.com/longhorn/longhorn/pull/2216
```
kubectl edit ds longhorn-manager -n longhorn-system
```
After apply the workaround, Helm upgrade is still ok

**Comment by khushboo-rancher** [comment] 2021-03-03 21:26
Verified with Longhorn-master `03/03/2021`

Validation - **Partially fail**

1. Scenario passed for new Longhorn master installation or if the `longhorn-manager` daemon-set is edited. 
2. Upgrade scenario (Longhorn yaml file used for installation and upgrade using kubectl command) failed where If I add bidirectional mount `/var/run` in the yaml of v1.1.0 and upgrade to master which doesn't have `/var/run/` mount I can still see the `/var/run/` mount in the `longhorn-manager` daemon-set yaml. @PhanLe1010 Can you please confirm?

**Comment by khushboo-rancher** [comment] 2021-03-08 14:31
>> Upgrade scenario (Longhorn yaml file used for installation and upgrade using kubectl command) failed where If I add bidirectional mount /var/run in the yaml of v1.1.0 and upgrade to master which doesn't have /var/run/ mount I can still see the /var/run/ mount in the longhorn-manager daemon-set yaml. @PhanLe1010 Can you please confirm?

@PhanLe1010 I think the scenario 2nd failed because I altered the Yaml file and added the mount path `/var/run`. Because of the functionality of `kubectl.kubernetes.io/last-applied-configuration`, the mount path got retained on upgrading Longhorn to the master. Can you please confirm this?

**Comment by shuo-wu** [comment] 2021-03-09 04:42
BTW, I think we need to ask How the Longhorn get installed in section `Environment`. I just check the reproducing step. The reason why I cannot reproduce it is that I was using YAML file installation while the user was using Helm or Rancher.

**Comment by khushboo-rancher** [comment] 2021-03-10 12:15
Closing this as the scenario 2 is working as expected. If user add/modify the yaml file of Longhorn manager and upgrade it, the previous value will come from the metadata of the yaml file.

**Closed by khushboo-rancher** 2021-03-10 12:15 UTC
Labels: area/kubernetes, area/manager, bug, priority/2, require/manual-test-plan
