### ISSUE TITLE
[BUG] Deleting a backup from backup page in longhorn doesn't delete the blocks in backup store

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1431] opened 2020-05-29 20:28 UTC
**Describe the bug**
Deleting a backup from backup page in longhorn doesn't delete the blocks in backup store

**To Reproduce**
1. Create a volume, attach to a pod and write into it.
2. Set up an S3/NFS backup store.
3. Take a backup. Wait for it to complete.
4. Check the size of backup in backup store.
5. Delete the backup.
6. Check the size in the backup storage. It is same as earlier. 
7. Blocks are not deleted.

**Expected behavior**
Blocks should get deleted.

**Environment:**
 - Longhorn version: v1.0.0-rc3
 - Kubernetes version: v1.17.4
 - Node OS type and version: Ubuntu 18.04

**Comment by yasker** [comment] 2020-05-30 03:18
## Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged?
The PR is at https://github.com/longhorn/backupstore/pull/40

* [ ] Is the reproduce steps/test steps documented?

* [ ] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [ ] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at~~

* [ ] **If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
~~The automation skeleton PR is at 
The automation test case PR is at~~
Separate PR filed at https://github.com/longhorn/longhorn/issues/1434

* [ ] **if labeled: require/automation-engine** Has the engine integration test been merged?
~~The engine automation PR is at~~
Separate PR filed at https://github.com/longhorn/longhorn/issues/1433

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at https://github.com/longhorn/longhorn-tests/wiki/Test-Scenarios-for-Backups-&-Restore#1431-backup-block-deletion-test

**Comment by khushboo-rancher** [comment] 2020-05-30 04:31
Verified on master- 05-29-2020

Verification : **Passed**

Deletion of backup from backup page in longhorn delete the corresponding block in backup store.

Tested scenario:
1. Configure NFS/S3 backup store
2. Create a backup.
3. Delete the backup and verify in backup store if the block is removed

1. Configure NFS/S3 backup store
2. Create a backup.
3. Delete all the backups and verify in backup store if the block is removed

**Comment by yasker** [comment] 2020-05-30 04:43
Close this issue for now since e2e test will be covered by https://github.com/longhorn/longhorn/issues/1434

**Closed by yasker** 2020-05-30 04:43 UTC
Labels: bug, priority/1, reproduce/always, require/automation-e2e, require/automation-engine, require/manual-test-plan
