### ISSUE TITLE
[FEATURE] Automatic identifying of corrupted replica (bit rot detection)

### ISSUE THREAD

**Issue by chickeaterbanana** [longhorn/longhorn#3198] opened 2021-10-31 11:22 UTC
see also: https://longhorn.io/docs/1.2.2/advanced-resources/data-recovery/corrupted-replica/

**Describe the solution you'd like**
You already described a way of identifying corrupted replicas. This could also work on blocks. If you add some meta data to the snapshot in form of hashes of the changed blocks. It would be possible to identify corrupted blocks automatically. This would help to identify common storage problems. These hashes don't have to be cryptography correctly(sha). You could use [CRC](https://en.wikipedia.org/wiki/Cyclic_redundancy_check) for this. This wouldn't lower the performance drastically but increase the snapshot, backup and replica integrity significantly.

**Describe alternatives you've considered**
A cron job which automatically calculates a hash of the mounted devices and compare these. If a corrupt volume is detected with the python interface remove the replica. To work like this, the disk have to be without changes for some time. This would lead to a drastically performance decrease if we set them read only for the hash time. We also considered if we could use the snapshot data for this...

**Additional context**
Consumer SSDs are dying in a very bad way. We already saw disks which start to add 0-Bytes somewhere on the disks. We also saw different other situation where the data is completely corrupted at the end of live of the ssd. We know Ceph is using some automatic healing and detection of disk failures, but ceph is quite more complicated than longhorn. We like the simplicity of longhorn and would like to use consumer hardware for the storage. But without automatic detection/healing it would end in a couple of problems which would cost a lot of manual work, individual development on our side or cost in form of buying enterprise ssds. So we have to consider if these costs would compensate the costs of the introduction of ceph.

**Comment by jenting** [comment] 2021-11-09 01:03
Probably we could choose [hash](https://cyan4973.github.io/xxHash/) since the calculation time is faster.

Adding a hash to the replica is a good idea, to automatically detect the corrupted replica.

The hash calculation could based on per-replica or per-sector. I think per-sector is more suitable because we could calculate the hash of each write operation to the sector, instead of after each writes operation is finished, calculate the full replica hash.

The current sector size is 512, so the overhead after each write operation would be affected a lot. But we need to do the performance test on write IOPS after doing the code change.

**Comment by jenting** [comment] 2022-01-07 02:02
I think we need this one to automatic identifying which replica is corrupted.
Moving to the planning.

cc @innobead

**Comment by voarsh2** [comment] 2022-06-26 16:02
> 2\. Predict the disk failure: monitor the per-disk SMART

In this case my system will not expose smart data - smartctl can't pickup my disks in the raid controller, the HP Smart Array P420i Controller itself checks the disks though but the hypervisor won't. And since I am running on VM's with virtual disks, it would make smart data for data integrity pointless in my case.

**Comment by chickeaterbanana** [comment] 2022-06-27 08:40
You could add a option to enable/disable the hash check. I would also recommend to make the hash configurable. Some CPUs have special hardware support for hash algorithms:
https://en.wikipedia.org/wiki/Intel_SHA_extensions

For us data reliability has equal priority to performance. If we had to accept performance decrease, but afterwards we can be sure to have reliable data, we would accept the performance hit.

If the hash will be calculated after a snapshot without blocking it. We could schedule the calculation to other nodes to have it seperated from the production setup. Maybe on secondary/replicas nodes.

**Comment by yasker** [comment] 2022-06-27 18:05
Maybe we can utilize `dm-integrity` for this.

**Comment by innobead** [comment] 2022-08-03 08:38
ref: https://github.com/longhorn/longhorn/issues/4210

**Comment by innobead** [comment] 2022-09-14 09:34
cc @l-mb

**Comment by innobead** [comment] 2022-11-14 01:52
This needs @longhorn/qa to update upgrade testing engine image. cc @chriscchien

**Comment by derekbit** [comment] 2022-11-18 04:43
For the **silent corruption** caused by the bit rot, I don't find a good emulation method. I will update the test steps if I have any update. Any idea is appreciated.

**Comment by yangchiu** [comment] 2022-11-23 08:00
@derekbit Following `[the test steps](https://github.com/longhorn/longhorn/issues/3198#issuecomment-1286534879)`, after the replica rebuilding in step (11), I also observe there is a new snapshot created. Is it the right behavior?
![snapshot](https://user-images.githubusercontent.com/5709208/203496424-dbfe49d0-fbac-49a7-a4db-22f03753975f.png)

**Comment by yangchiu** [comment] 2022-11-24 07:31
Verified passed on master-head (longhorn 2d40004) by following [the test steps](https://github.com/longhorn/longhorn/issues/3198#issuecomment-1286534879). 

For both `Snapshot Data Integrity` set to `enabled` and `fast-checked`, after the snapshot file corrupted, the replica rebuilding can be triggered, and the checksum of the rebuilt snapshot file can match with the disk file and the snapshot CR as expected.

**Closed by yangchiu** 2022-11-24 07:31 UTC
Labels: kind/enhancement, area/engine, area/manager, priority/0, require/automation-e2e, require/LEP, area/stability
