### ISSUE TITLE
[Question] why does Longhorn mention a path doesn't look like a replica data path?

### ISSUE THREAD

**Issue by rondlite** [longhorn/longhorn#2245] opened 2021-02-09 08:45 UTC
**Question**

Why is `/mnt/longhorn/replicas` not a valid path?
Posting as a question since it seems I am missing something.
`fail to sync replica for longhorn-system/pvc-bf535eff-847f-42fa-9061-16a056c4dc2b-r-0971f863: /mnt/longhorn/replicas doesn't look like a replica data path`

However, the sync gets done so this is the more confusing part.

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version:
 - Node config
   - OS type and version
   - CPU per node:
   - Memory per node: 32M
   - Disk type ext4
   - Network bandwidth and latency between the nodes: 0.533 ms
 - Underlying Infrastructure Baremetal

**Comment by PhanLe1010** [comment] 2021-02-12 00:16
@rondlite 
The error message comes from [this line of code](https://github.com/longhorn/longhorn-manager/blob/c2e1728c2dbfb05f8060bc182c9ad5c23d4171ee/controller/replica_controller.go#L283), Longhorn is trying to delete the replica and it finds that the `replica.Spec.DataDirectoryName` is empty. So, it doesn't fit the format. We are wondering why the `replica.Spec.DataDirectoryName` is empty. Can you send us a support bundle to `longhorn-support-bundle@rancher.com`?

**Comment by PhanLe1010** [comment] 2021-02-12 00:36
You can use Longhorn UI to generate a support bundle. The link on the bottom in the below picture:
<img width="573" alt="Screen Shot 2021-02-11 at 4 19 12 PM" src="https://user-images.githubusercontent.com/22139961/107716918-53f6cc80-6c87-11eb-8f46-407f861c145c.png">

**Comment by joshimoo** [comment] 2021-02-17 18:27
@rondlite can you confirm that you are indeed using Longhorn version: 1.1.1 which we haven't released yet.
Also can you attach a support bundle so we can have a look why there is no replica data path specified.
I assume you meant 32GB of memory per node, can you confirm this?

**Comment by shuo-wu** [comment] 2021-04-27 01:48
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by shuo-wu** 2021-04-27 01:48 UTC
Labels: kind/question
