### ISSUE TITLE
[IMPROVEMENT] System restore unable to restore volume with backing image

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#5085] opened 2022-12-16 07:48 UTC
## Describe the bug (🐛 if you encounter this issue)

A system restore fails to restore a volume with backing image if backing image is not present in the cluster.

## To Reproduce

1. Create a volume with backing image.
2. Take a system backup.
3. Restore the backup in a new cluster.
4. Restore stuck while restoring the volume with backing image.

## Expected behavior

System restore should trigger backing image download and proceed with the volume restore.

## Log or Support bundle
```
time="2022-12-16T07:40:49Z" level=debug msg="Restoring VolumeList" backupTargetURL="s3://<abc>/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:v1.4.x-head" error="admission webhook \"validator.longhorn.io\" denied the request: backingimage.longhorn.io \"bi-1\" not found" systemRestore=sys-restore-1
```
[supportbundle_9ba88591-a0d8-44c9-84c8-50a700f2e7f1_2022-12-16T07-39-27Z.zip](https://github.com/longhorn/longhorn/files/10243706/supportbundle_9ba88591-a0d8-44c9-84c8-50a700f2e7f1_2022-12-16T07-39-27Z.zip)

## Environment

 - Longhorn version: v1.4.x-head

**Comment by innobead** [comment] 2022-12-16 07:51
This is the current limitation and needed to note in the doc. This will be fixed together with #4165 and https://github.com/longhorn/longhorn/issues/5005.

The workaround should be mentioned in the doc as well, and that should be users need to create those backing images before restoring the system backup. @c3y1huang can you help confirm this? @khushboo-rancher can you help try this?

**Comment by khushboo-rancher** [comment] 2022-12-16 07:54
@innobead If I create the backing image before restoring the volume, it works fine.

**Comment by ChanYiLin** [comment] 2023-07-21 01:35
Is this a duplicate of https://github.com/longhorn/longhorn/issues/4165 ?

**Comment by innobead** [comment] 2023-12-20 11:12
Moved to 1.7.0, but we can backport the fix to 1.6.x.

**Comment by roger-ryao** [comment] 2024-05-23 07:14
> Moved to 1.7.0, but we can backport the fix to 1.6.x.

Hi @ChanYiLin 
    According to the previous comment, does https://github.com/longhorn/longhorn-manager/pull/2710 still need to be backported to fix in v1.6.x?

**Comment by roger-ryao** [comment] 2024-05-23 10:13
**Verified on master-head 20240522**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/0886abcc8bc3484202e693ef22c53faa8417b67b
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/23ccdd17f9ef3000038f66ef5b0380134fd7c335

**The test steps**
https://github.com/longhorn/longhorn/issues/5085#issuecomment-2056306793

    1. Create a BackingImage `vol-0` ,  Created From `Download From URL` and a volume using it
    1. Create another  BackingImage `vol-1`, Created From `Upload form local` and create another volume using it
    1. Create a system-backup
    1. `kubectl get lhbbi, lhb -n longhorn-system` will see the backup of the Volume and the Backingimage
    1. Delete the Volume and the BackingImage
    1. Restore the system-backup
    1. The BackingImage and The BackingImage source type will be `restored`, but the Volume will not be restored. 

**Result Failed**
    The Volume will not be restored. 
    
[supportbundle_65954c8b-3654-42ca-baeb-8aac630a220b_2024-05-23T10-08-51Z.zip](https://github.com/longhorn/longhorn/files/15415284/supportbundle_65954c8b-3654-42ca-baeb-8aac630a220b_2024-05-23T10-08-51Z.zip)

```console
     time="2024-05-23T10:10:22Z" level=warning msg="Restoring PersistentVolumeList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="volume.longhorn.io \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:22Z" level=warning msg="Restoring PersistentVolumeClaimList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="persistentvolume \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:23Z" level=warning msg="Restoring PersistentVolumeClaimList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="persistentvolume \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:23Z" level=warning msg="Restoring PersistentVolumeList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="volume.longhorn.io \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:24Z" level=warning msg="Restoring PersistentVolumeList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="volume.longhorn.io \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:24Z" level=warning msg="Restoring PersistentVolumeClaimList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="persistentvolume \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:25Z" level=warning msg="Restoring PersistentVolumeList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="volume.longhorn.io \"vol1\" not found" systemRestore=222res
time="2024-05-23T10:10:25Z" level=warning msg="Restoring PersistentVolumeClaimList" func="controller.(*SystemRolloutController).restore" file="system_rollout_controller.go:796" backupTargetURL="s3://backupbucket@us-east-1/" controller=longhorn-system-rollout engineImage="longhornio/longhorn-engine:master-head" error="persistentvolume \"vol1\" not found" systemRestore=222res
```

**Comment by ChanYiLin** [comment] 2024-05-24 02:22
Thanks @roger-ryao 
This is a bug and has created a ticket to handle it: https://github.com/longhorn/longhorn/issues/8601
Lets verified it after the fix has been merged.

**Comment by roger-ryao** [comment] 2024-05-30 09:11
**Verified on master-head 20240530**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/f79dc9bb2bc7907955e8174f774b593b62775640
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/ad7420087dd5e9c706d8462c62cb756812544c55

**The test steps**
https://github.com/longhorn/longhorn/issues/5085#issuecomment-2126735260

**Result Passed**

**Comment by c3y1huang** [comment] 2024-06-24 03:26
Reopen because the document is not updated.

https://github.com/longhorn/website/blob/master/content/docs/1.7.0/advanced-resources/system-backup-restore/backup-longhorn-system.md?plain=1#L40

**Comment by roger-ryao** [comment] 2024-06-26 11:45
**Verified on master-head 20240626**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7e01ba13b41dd74689da8ec9e474baaf91363acc
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/77ac26d09a1bc18e743efa2e6bb94efc7d0fa4da

**The test steps**
https://github.com/longhorn/longhorn/issues/5085#issuecomment-2056306793
https://github.com/longhorn/longhorn/issues/5085#issuecomment-2126735260

**Result Passed**

1. The test `test_system_backup_and_restore_volume_with_backingimage` passed 50 times : https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7050/
2. require/doc : https://github.com/longhorn/website/pull/926

**Closed by roger-ryao** 2024-06-26 11:45 UTC
Labels: kind/bug, component/longhorn-manager, severity/1, priority/0, require/doc, area/volume-backup-restore, area/backing-image, area/system-backup-restore, backport/1.6.3
