### ISSUE TITLE
[BUG] mountPropagation: Bidirectional for /var/run broke longhorn-manager on openshift/okd/crio

### ISSUE THREAD

**Issue by tvanderka** [longhorn/longhorn#1757] opened 2020-09-02 18:41 UTC
**Describe the bug**
PR #1585 broke longhorn-manager on OKD. After deleting manager pod, crio is unable to create a new one. Something breaks on the node and crio is unable to mount secrets or some other fs in the new pod until reboot.

**To Reproduce**
1. Install longhorn on okd
2. Delete longhorn-manager pod
4. See error: container create failed ...

**Expected behavior**
New longhorn-manager pod should be created.

**Log**

**Environment:**
 - Longhorn version: 1.0.2
 - Server Version: 4.5.0-0.okd-2020-08-12-020541
 - Kubernetes Version: v1.18.3
 - Node OS type and version: Fedora CoreOS 32.20200629.3.0

**Additional context**
Is /var/run hostPath mount even necessary? I did not see it being used, so I just removed it and everything seems fine to me.

**Comment by yasker** [comment] 2020-09-02 18:54
@STASiAN @jdunhamvrtx any thoughts?

**Comment by STASiAN** [comment] 2020-09-06 15:57
@yasker 
I thinks its related:
https://kubernetes.io/docs/concepts/storage/volumes/#configuration
https://github.com/cri-o/cri-o/issues/1962

I did not find any mention of /var/run in the longhorn-manager code - is it even necessary there?
https://github.com/longhorn/longhorn-engine/blob/3d16e138eb94a6bc859a39f723dc819685e5e464/integration/common/constants.py#L14

Maybe we should put socket file to /var/lib/longhorn/ instead of /var/run

@tvanderka can you provide some logs
kubectl describe pods %longhorn-manager%
journalctl -u crio

**Comment by tvanderka** [comment] 2020-09-07 17:33
That crio issue does not seem related, bidirectional mount on /var/lib/longhorn seems fine. This is broken specifically for /var/run, I guess because secrets/sa-token/whatever are mounted there.

There are no socket files in /var/run or anywhere else I looked, longhorn-manager daemon listens on tcp:9500 only

CRIO logs are gone/cycled. Pods without varrun mounted:

```
Name:         longhorn-manager-flp52
Namespace:    longhorn-system
Priority:     0
Node:         okd-worker-3/10.201.35.33
Start Time:   Wed, 02 Sep 2020 19:54:31 +0200
Labels:       app=longhorn-manager
              app.kubernetes.io/instance=longhorn
              app.kubernetes.io/managed-by=Helm
              app.kubernetes.io/name=longhorn
              app.kubernetes.io/version=v1.0.2
              controller-revision-hash=7cc6c5757
              helm.sh/chart=longhorn-1.0.2
              pod-template-generation=3
Annotations:
              openshift.io/scc: privileged
Status:       Running
IP:           10.129.2.6
IPs:
  IP:           10.129.2.6
Controlled By:  DaemonSet/longhorn-manager
Containers:
  longhorn-manager:
    Container ID:  cri-o://08c84395c63d9efd1fa1cc9ef3dc060e10582ff54323429dd75af38fc39a3c00
    Image:         longhornio/longhorn-manager:v1.0.2
    Image ID:      docker.io/longhornio/longhorn-manager@sha256:a0ef6144f543000ff7c6ca2a7aa095e788467fe5e1aafc3f774fbfde752a7042
    Port:          9500/TCP
    Host Port:     0/TCP
    Command:
      longhorn-manager
      -d
      daemon
      --engine-image
      longhornio/longhorn-engine:v1.0.2
      --instance-manager-image
      longhornio/longhorn-instance-manager:v1_20200514
      --manager-image
      longhornio/longhorn-manager:v1.0.2
      --service-account
      longhorn-service-account
    State:          Running
      Started:      Wed, 02 Sep 2020 19:54:33 +0200
    Ready:          True
    Restart Count:  0
    Readiness:      tcp-socket :9500 delay=0s timeout=1s period=10s #success=1 #failure=3
    Environment:
      POD_NAMESPACE:         longhorn-system (v1:metadata.namespace)
      POD_IP:                 (v1:status.podIP)
      NODE_NAME:              (v1:spec.nodeName)
      DEFAULT_SETTING_PATH:  /var/lib/longhorn-setting/default-setting.yaml
    Mounts:
      /host/dev/ from dev (rw)
      /host/proc/ from proc (rw)
      /var/lib/longhorn-setting/ from longhorn-default-setting (rw)
      /var/lib/longhorn/ from longhorn (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from longhorn-service-account-token-9dgsr (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  dev:
    Type:          HostPath (bare host directory volume)
    Path:          /dev/
    HostPathType:  
  proc:
    Type:          HostPath (bare host directory volume)
    Path:          /proc/
    HostPathType:  
  varrun:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/
    HostPathType:  
  longhorn:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/longhorn/
    HostPathType:  
  longhorn-default-setting:
    Type:      ConfigMap (a volume populated by a ConfigMap)
    Name:      longhorn-default-setting
    Optional:  false
  longhorn-service-account-token-9dgsr:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  longhorn-service-account-token-9dgsr
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/disk-pressure:NoSchedule
                 node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute
                 node.kubernetes.io/pid-pressure:NoSchedule
                 node.kubernetes.io/unreachable:NoExecute
                 node.kubernetes.io/unschedulable:NoSchedule
Events:          <none>
...
```

**Comment by yasker** [comment] 2020-09-10 22:53
@STASiAN has a good point. We might no longer need `/var/run` bind mount for the manager. We will check it to see if it's possible to remove it from the manager deployment yaml.

**Comment by Born2Bake** [comment] 2020-09-28 14:34
> 
> 
> **Describe the bug**
> PR #1585 broke longhorn-manager on OKD. After deleting manager pod, crio is unable to create a new one. Something breaks on the node and crio is unable to mount secrets or some other fs in the new pod until reboot.
> 
> **To Reproduce**
> 
>     1. Install longhorn on okd
> 
>     2. Delete longhorn-manager pod
> 
>     3. See error: container create failed ...
> 
> 
> **Expected behavior**
> New longhorn-manager pod should be created.
> 
> **Log**
> 
> **Environment:**
> 
>     * Longhorn version: 1.0.2
> 
>     * Server Version: 4.5.0-0.okd-2020-08-12-020541
> 
>     * Kubernetes Version: v1.18.3
> 
>     * Node OS type and version: Fedora CoreOS 32.20200629.3.0
> 
> 
> **Additional context**
> Is /var/run hostPath mount even necessary? I did not see it being used, so I just removed it and everything seems fine to me.

Hi,

Would you be able to share what's the correct way of deploying longhorn in OKD-latest? 
SSC & what changes needs to be added to [yaml ](https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml)file so I can run it?

**Comment by yasker** [comment] 2020-10-02 02:00
Mark as a duplicate of #1831 . Need to add a document on how to use on OKD (of course, ideally it should work out of the box).

**Closed** 2020-10-02 02:01 UTC
Labels: area/manager, enhancement

**Comment by yasker** [comment] 2020-10-02 02:03
@tvanderka Do you have some steps you can share to get Longhorn running on OKD? It would be great if you can share them on #1831. We want to see if we can fix the `/var/run` issue as a part of #1831 as well. But we will need to reproduce the issue and get Longhorn running on OKD first.

**Comment by excieve** [comment] 2020-10-06 15:25
I think we encountered an issue that might be related to this. On some nodes where longhorn-managers have been restarting a lot for some reason, there were growing numbers of `/run/secrets/kubernetes.io/serviceaccount` tmpfs mounts. At some point reaching 4k+ duplicate mounts leading to `df` taking 20s to execute and grinding docker to timeout on kubelet communication.

This isn't with OKD though, rather k8s 1.17.9 on EKS with Docker 19.03.6.

That's how a relevant part of `/etc/mtab` looks on this node:
```
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /var/lib/kubelet/pods/4dff21d5-8a0e-473b-9efe-a8339f51f0a6/volumes/kubernetes.io~secret/longhorn-service-account-token-wxz7k tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
tmpfs /run/secrets/kubernetes.io/serviceaccount tmpfs rw,relatime 0 0
```

Pod `4dff21d5-8a0e-473b-9efe-a8339f51f0a6` is `longhorn-manager`.

Not seeing this on any other nodes where `longhorn-manager` wasn't restarting.

We also replicated this by killing the `longhorn-manager` pod letting it start again and this added another `serviceaccount` mount to the node.

Does it need a separate issue?

**Comment by yasker** [comment] 2020-10-09 21:21
@excieve can you file a separate issue for this? `/run/secrets/kubernetes.io/serviceaccount` is managed by Kubernetes. We want to check if something is triggering Longhorn manager to restart.

It's possible the repeated mount is a Kubernetes bug though.
