### ISSUE TITLE
[BUG] Long delay to attach volume when statefulset restart

### ISSUE THREAD

**Issue by ElisaMeng** [longhorn/longhorn#2322] opened 2021-03-10 22:43 UTC
**Describe the bug**
When using volumeClaimTemplates with longhorn in a statefulset, initial deployment goes ok, but if running 

kubectl rollout restart statefulset, longhorn volume will get failed to mount again. It seems stuck in being state, which is not supposed being like that. 

**To Reproduce**
1. Deploy statefulset workload with volumeClaimTemplates 
2. Wait for all pods get ready
3. run kubectl rollout restart statefulset ...
4. no pod can be started since longhorn volume is being deleted

**Expected behavior**
pod should just restart

**Log**
.
```
7m30s       Normal    Scheduled                pod/seafile-srv-0                                       Successfully assigned cloudoffice/seafile-srv-0 to iserver
7m18s       Normal    SuccessfulAttachVolume   pod/seafile-srv-0                                       AttachVolume.Attach succeeded for volume "pvc-12ee35dc-15f7-4b61-9394-63251b02be18"
6m59s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "seafileltd/seafile-mc:8.0.3" already present on machine
6m59s       Normal    Created                  pod/seafile-srv-0                                       Created container setup
6m59s       Normal    Started                  pod/seafile-srv-0                                       Started container setup
6m58s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "mariadb:10" already present on machine
6m58s       Normal    Created                  pod/seafile-srv-0                                       Created container mariadb
6m58s       Normal    Started                  pod/seafile-srv-0                                       Started container mariadb
6m58s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "seafileltd/elasticsearch-with-ik:5.6.16" already present on machine
6m57s       Normal    Created                  pod/seafile-srv-0                                       Created container seafile-elasticsearch
6m57s       Normal    Started                  pod/seafile-srv-0                                       Started container seafile-elasticsearch
6m57s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "memcached:1.5.6" already present on machine
6m57s       Normal    Created                  pod/seafile-srv-0                                       Created container seafile-memcached
6m57s       Normal    Started                  pod/seafile-srv-0                                       Started container seafile-memcached
6m57s       Normal    Pulled                   pod/seafile-srv-0                                       Container image "seafileltd/seafile-mc:8.0.3" already present on machine
6m56s       Normal    Created                  pod/seafile-srv-0                                       Created container seafile
6m56s       Normal    Started                  pod/seafile-srv-0                                       Started container seafile
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container mariadb
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container seafile
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container seafile-memcached
3m51s       Normal    Killing                  pod/seafile-srv-0                                       Stopping container seafile-elasticsearch
3m43s       Normal    Scheduled                pod/seafile-srv-0                                       Successfully assigned cloudoffice/seafile-srv-0 to iserver
100s        Warning   FailedMount              pod/seafile-srv-0                                       Unable to attach or mount volumes: unmounted volumes=[seafile-srv-store], unattached volumes=[seafile-srv-store default-token-w5pdn]: timed out waiting for the condition
31s         Warning   FailedMount              pod/seafile-srv-0                                       MountVolume.WaitForAttach failed for volume "pvc-12ee35dc-15f7-4b61-9394-63251b02be18" : volume attachment is being deleted
7m35s       Normal    ExternalProvisioning     persistentvolumeclaim/seafile-srv-pvc                   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
7m35s       Normal    Provisioning             persistentvolumeclaim/seafile-srv-pvc                   External provisioner is provisioning volume for claim "cloudoffice/seafile-srv-pvc"
7m32s       Normal    ProvisioningSucceeded    persistentvolumeclaim/seafile-srv-pvc                   Successfully provisioned volume pvc-12ee35dc-15f7-4b61-9394-63251b02be18
60m         Normal    ExternalProvisioning     persistentvolumeclaim/seafile-srv-store-seafile-srv-0   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
60m         Normal    Provisioning             persistentvolumeclaim/seafile-srv-store-seafile-srv-0   External provisioner is provisioning volume for claim "cloudoffice/seafile-srv-store-seafile-srv-0"
60m         Normal    ProvisioningSucceeded    persistentvolumeclaim/seafile-srv-store-seafile-srv-0   Successfully provisioned volume pvc-639c918d-e1b5-47c9-87ed-f4c69d452d5e
32m         Normal    ExternalProvisioning     persistentvolumeclaim/seafile-srv-store-seafile-srv-0   waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
32m         Normal    Provisioning             persistentvolumeclaim/seafile-srv-store-seafile-srv-0   External provisioner is provisioning volume for claim "cloudoffice/seafile-srv-store-seafile-srv-0"
32m         Normal    ProvisioningSucceeded    persistentvolumeclaim/seafile-srv-store-seafile-srv-0   Successfully provisioned volume pvc-e2e5da4d-c206-422f-9640-c0696dfa9baa
60m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Claim seafile-srv-store-seafile-srv-0 Pod seafile-srv-0 in StatefulSet seafile-srv success
60m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
37m         Warning   FailedCreate             statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv failed error: The POST operation against Pod could not be completed at this time, please try again.
37m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
32m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Claim seafile-srv-store-seafile-srv-0 Pod seafile-srv-0 in StatefulSet seafile-srv success
20m         Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
20m         Normal    SuccessfulDelete         statefulset/seafile-srv                                 delete Pod seafile-srv-0 in StatefulSet seafile-srv successful
3m43s       Normal    SuccessfulCreate         statefulset/seafile-srv                                 create Pod seafile-srv-0 in StatefulSet seafile-srv successful
3m51s       Normal    SuccessfulDelete         statefulset/seafile-srv                                 delete Pod seafile-srv-0 in StatefulSet seafile-srv successful

```
**Environment:**
 - Longhorn version: v1.1.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s 1.19.8
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: k3os
   - CPU per node: 4
   - Memory per node: 16G
   - Disk type(e.g. SSD/NVMe): 
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Additional context**

**Comment by PhanLe1010** [comment] 2021-03-10 22:46
What is the yaml file of the stateset and the longhorn storageclass ?

**Comment by ElisaMeng** [comment] 2021-03-11 11:52
```

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    app: test-server
  name: test-server
  
spec:
  replicas: 1
  serviceName: test
  selector:
    matchLabels:
      app: test-server
  template:
    metadata:
      labels:
        app: test-server
    spec:
      
      initContainers:
        - image: alpine:3.12
          name: setup
          command:
            - sh 
            - -c 
            - for i in mariadb; do mkdir -p /data/$i;done
          volumeMounts:
          - mountPath: /data
            name: test-server-store
          resources:
            limits:
              cpu: 10m
              memory: 40M
      containers:
      - image: mariadb:10
        name: mariadb
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: test
        ports:
        - containerPort: 3306
          name: mariadb
        volumeMounts:
        - name: test-server-store
          subPath: mariadb
          mountPath: /var/lib/mysql
        resources:
          limits:
            cpu: 1000m
            memory: 2G
  volumeClaimTemplates:
    - metadata:
        name: test-server-store
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: longhorn
        resources:
          requests:
            storage: 512Gi

---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: test-server
  name: test
  
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    app: test-server
```

@PhanLe1010  btw, If set the volume size to 1G, it works without issue.

**Comment by ElisaMeng** [comment] 2021-03-11 14:30
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    longhorn.io/last-applied-configmap: |
      kind: StorageClass
      apiVersion: storage.k8s.io/v1
      metadata:
        name: longhorn
      provisioner: driver.longhorn.io
      allowVolumeExpansion: true
      reclaimPolicy: Delete
      volumeBindingMode: Immediate
      parameters:
        numberOfReplicas: "2"
        staleReplicaTimeout: "2880"
        fromBackup: ""
      #  diskSelector: "ssd,fast"
      #  nodeSelector: "storage,fast"
        recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 3 * * 1", "retain":3},
                         {"name":"backup", "task":"backup", "cron":"0 5 * * 1", "retain":3,
                          "labels": {"interval":"weekly"}}]'
parameters:
  fromBackup: ""
  numberOfReplicas: "2"
  recurringJobs: '[{"name":"snap", "task":"snapshot", "cron":"0 3 * * 1", "retain":3},
    {"name":"backup", "task":"backup", "cron":"0 5 * * 1", "retain":3, "labels": {"interval":"weekly"}}]'
  staleReplicaTimeout: "2880"
provisioner: driver.longhorn.io
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

`Some more update.  it actually was not failing, but taking a very long time to attach, far longer than the first time it attach.

**Comment by cclhsu** [comment] 2021-03-12 08:23
Add some note on behavior of statefulset:

1. Create Statefulset:

```
YAML=statefulset_backend.yaml
kubectl apply -f ${YAML}
```

Events:

```
33s         Normal    SuccessfulCreate         statefulset/db                    create Claim db-db-0 Pod db-0 in StatefulSet db success
33s         Normal    SuccessfulCreate         statefulset/db                    create Pod db-0 in StatefulSet db successful
33s         Normal    Provisioning             persistentvolumeclaim/db-db-0     External provisioner is provisioning volume for claim "default/db-db-0"
33s         Normal    ExternalProvisioning     persistentvolumeclaim/db-db-0     waiting for a volume to be created, either by external provisioner "driver.longhorn.io" or manually created by system administrator
31s         Normal    ProvisioningSucceeded    persistentvolumeclaim/db-db-0     Successfully provisioned volume pvc-2a827689-82ab-4ed5-a71c-f019b559930d
17s         Normal    SuccessfulAttachVolume   pod/db-0                          AttachVolume.Attach succeeded for volume "pvc-2a827689-82ab-4ed5-a71c-f019b559930d"
10s         Normal    Pulled                   pod/db-0                          Container image "alpine:3.12" already present on machine
10s         Normal    Created                  pod/db-0                          Created container setup
10s         Normal    Started                  pod/db-0                          Started container setup
8s          Normal    Started                  pod/db-0                          Started container mariadb
8s          Normal    Pulled                   pod/db-0                          Container image "mariadb:10" already present on machine
8s          Normal    Created                  pod/db-0                          Created container mariadb

```

2. Rollout restart:

```
STATEFULSET=db
kubectl rollout restart statefulset.apps/${STATEFULSET}
```

Pod will restart one by one, and pvc/pv will not deleted.

Events:

```
17s         Normal    SuccessfulDelete         statefulset/db                    delete Pod db-0 in StatefulSet db successful
17s         Normal    Killing                  pod/db-0                          Stopping container mariadb
8s          Normal    SuccessfulCreate         statefulset/db                    create Pod db-0 in StatefulSet db successful
7s          Normal    Pulled                   pod/db-0                          Container image "alpine:3.12" already present on machine
6s          Normal    Created                  pod/db-0                          Created container setup
6s          Normal    Started                  pod/db-0                          Started container setup
5s          Normal    Pulled                   pod/db-0                          Container image "mariadb:10" already present on machine
5s          Normal    Created                  pod/db-0                          Created container mariadb
5s          Normal    Started                  pod/db-0                          Started container mariadb
```

3. Delete Statefulset:

```
YAML=statefulset_backend.yaml
APP=mariadb
kubectl delete -f ${YAML}
kubectl delete pvc -l app=${APP}
```

Need to manual delete pvc. pvc and pv existed even after YAML deleted.

Events:

```
69s         Normal    Killing                  pod/db-0                          Stopping container mariadb
```

NOTE: As size of PVC request increase, restarting or terminating time seems also increase.

**Comment by ElisaMeng** [comment] 2021-03-12 12:47
@cclhsu Statefulset is designed to not delete pic/pv when pod get deleted.

**Comment by joshimoo** [comment] 2021-03-19 11:41
Long delay times for mount, can be caused by kubernetes recursive chown/chmod, if your volume contains lots of files.
If you don't need this have a look here https://kubernetes.io/blog/2020/12/14/kubernetes-release-1.20-fsgroupchangepolicy-fsgrouppolicy/#allow-users-to-skip-recursive-permission-changes-on-mount

`fsGroupChangePolicy: "OnRootMismatch"`
@ElisaMeng can you check if your volume contains lots of files and if the above change fixes your delay?

**Comment by ElisaMeng** [comment] 2021-03-22 23:48
@joshimoo It is empty volume. You can try to re-produce it what the yaml I provided to see if it is the case for u. For me, I delay is quite obvious when volume size is big.

**Comment by cclhsu** [comment] 2021-03-26 02:15
Hi! @ElisaMeng Just wondering if the option `fsGroupChangePolicy: "OnRootMismatch"` helps you while attaching when restarting?  We have some previous tests and cases relating to stateful with large volume:

- https://github.com/longhorn/longhorn/issues/2168
- https://github.com/longhorn/longhorn/issues/2131

Those are resolved with the option.

**Comment by PhanLe1010** [comment] 2021-09-13 23:53
Close because of lacking of activity

**Closed by PhanLe1010** 2021-09-13 23:53 UTC
