### ISSUE TITLE
Volumes stuck in attaching (Backup restores & containers)

### ISSUE THREAD

**Issue by dcplaya** [longhorn/longhorn#1988] opened 2020-11-17 00:10 UTC
I recently had a power failure and my cluster went down. Normally, its no big deal, but this time is different.

I have multiple PVCs stuck in `attaching` and the containers never create. I can scale the deployments back and sometimes Longhorn reports `detached` while other times I have to select the `detach` option. 

In my effort to restore normal operation, I decided to delete some PVs that were showing this issue and then restore from a backup, but that too caused the PVs to get stuck in `attaching`

A support bundle has been attached as well. 

[longhorn-support-bundle_0c735fa4-c8bd-45a1-8537-4d822e8b35fe_2020-11-17T00-10-59Z.zip](https://github.com/longhorn/longhorn/files/5550403/longhorn-support-bundle_0c735fa4-c8bd-45a1-8537-4d822e8b35fe_2020-11-17T00-10-59Z.zip)

---
Version: `v1.0.2`

**Comment by shuo-wu** [comment] 2020-11-19 11:48
Custom Resource (CR) instance manager (e.g., `instance-manager-r-54eb0aeb`) somehow cannot be updated then some volume replicas cannot be set to `running` based on instance manager status. Here is the related logs in longhorn-manager `longhorn-manager-5hd42`:
```
2020-11-16T15:58:06.357720964-08:00 time="2020-11-16T23:58:06Z" level=error msg="failed to update instance map for instance manager instance-manager-r-54eb0aeb: Operation cannot be fulfilled on instancemanagers.longhorn.io \"instance-manager-r-54eb0aeb\": StorageError: invalid object, Code: 4, Key: /registry/longhorn.io/instancemanagers/longhorn-system/instance-manager-r-54eb0aeb, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: UID in precondition: acc30e08-d60c-45fc-bb7a-c4e8daf04ac1, UID in object meta: "
```
```
2020-11-16T15:58:09.259517470-08:00 time="2020-11-16T23:58:09Z" level=debug msg="Instance handler updated instance home-assistant-postgresql-r-b6047ddb state, old state unknown, new state stopped"
2020-11-16T15:58:14.697857213-08:00 time="2020-11-16T23:58:14Z" level=debug msg="Instance process node-red-config-r-741501a3 had been created, need to wait for instance manager update"
2020-11-16T15:58:14.697885259-08:00 time="2020-11-16T23:58:14Z" level=debug msg="Instance process plex-config-r-29d7c827 had been created, need to wait for instance manager update"
2020-11-16T15:58:14.697898052-08:00 time="2020-11-16T23:58:14Z" level=debug msg="Instance process nzbhydra2-config-r-b4b555a3 had been created, need to wait for instance manager update"
.......
```

According to the issue reported [here](https://github.com/kubernetes/kubernetes/issues/82130#issuecomment-527665796). It's like a etcd/cache issue. But I am not sure what's wrong with this part.

There are 2 more weird things in the support bundle:
1. It seems that some longhorn workloads are restarted. The related instance manager creation timestamp is `2020-09-25T11:54:51Z`. The longhorn manager pod `longhorn-manager-5hd42` is restarted at `2020-11-16T23:30:14Z`. The instance manager pod (this pod should be created once the instance manager CR is created) creation timestamp is `2020-11-16T22:03:38Z`. Some components should be launched in the same period.
2. Some instance manager CRs has empty kind and apiversion, which is weird:
```
typemeta:
  kind: ""
  apiversion: ""
```

**Comment by dcplaya** [comment] 2020-11-19 12:19
After staring at the logs long enough and doing enough Google searching, I ran the command located in #1801 on one of my `esphome` replicas that was stuck `detaching`. Once that completed and that replica was removed, everything took off and started to either properly attach or create replicas. The whole process was being held up by 1 task it seems.

**Comment by yasker** [comment] 2020-11-19 17:10
@dcplaya Glad that you worked around it. We still need to understand how this happened and make sure it won't be an issue for Longhorn future releases.

**Comment by dcplaya** [comment] 2020-11-20 00:02
It seems like longhorn tried to rebuild a replica and then that node got lost (ie, reboot) and then it just kind of hung out for a bit. 

I also noticed someone submitted bug #1999, which seems semi-related. (Could be completely independent)

I am happy to provide as much info as I can though, just let me know what is needed!

**Comment by dcplaya** [comment] 2020-11-29 16:02
A volume got stuck attaching (ombi) again. This time, it also seems like a random volume also go deleted (home-assistant)!  Luckily I had a backup to restore. I've attached another support bundle in the hope it gives you guys a bit more info. 

[longhorn-support-bundle_0c735fa4-c8bd-45a1-8537-4d822e8b35fe_2020-11-29T15-37-56Z.zip](https://github.com/longhorn/longhorn/files/5612394/longhorn-support-bundle_0c735fa4-c8bd-45a1-8537-4d822e8b35fe_2020-11-29T15-37-56Z.zip)

This one is slightly different than the previous one because I can scale back the Ombi pod and Longhorn will report the PVC is detatched. But as soon as I scale back up, it goes to "attaching" and Kubernetes reports `AttachVolume.Attach failed for volume "ombi-config" : rpc error: code = Aborted desc = The volume ombi-config is attaching` forever. This pod, I can leave in this weird state to help debug/troubleshoot if the devs would like too

**Comment by shuo-wu** [comment] 2020-12-02 08:26
For the attaching volume `ombi-config`, the related engine somehow get deleted and recreated (this shouldn't happen). then the engine name saved in old replicas doesn't match the the newly recreated engine name. As a result, [Longhorn consider there is no valid replica](https://github.com/longhorn/longhorn-manager/blob/ba4ca64ad03911194c8586932e9f529e19c884a4/controller/volume_controller.go#L1047) and the volume attachment gets stuck there.
  - The final error log:
```
2020-11-28T19:58:22.843646757-08:00 time="2020-11-29T03:58:22Z" level=warning msg="Error syncing Longhorn volume longhorn-system/ombi-config: fail to sync longhorn-system/ombi-config: fail to reconcile volume state for ombi-config: no healthy replica for starting"
```
  - The difference between volume/replica creation timestamp and engine creation timestamp :
```
objectmeta:
    name: ombi-config
    creationtimestamp: "2020-11-17T01:43:48Z"
```
```
  objectmeta:
    name: ombi-config-r-cdb83186
    creationtimestamp: "2020-11-17T01:43:49Z"
```
```
objectmeta:
    name: ombi-config-e-8a541be8
    creationtimestamp: "2020-11-29T03:58:22Z"
```
  - The mismatching of engine name:
```
  objectmeta:
    name: ombi-config-e-8a541be8
```
```
  objectmeta:
    name: ombi-config-r-cdb83186
  spec:
    enginename: ombi-config-e-3f8bbc0b
```

---

For the unexpected deleted volume `home-assistant`, I cannot find any critical log that indicated why it's deleted. The log of longhorn manager pods start at `2020-11-29T03:58:19Z`, at which the volume deletion is already started. This means we cannot find why the volume is deleted. And I cannot find the related pod `12edf140-ccd5-4428-9b36-69382db26ec7`, neither. If the volume is deleted with the pod, there should be some logs in `longhorn-csi-plugin`. But what I can find in `longhorn-csi-plugin` is just mount error.
  - The moment that the related engine and replicas get deleted:
```
2020-11-28T19:58:49.658063077-08:00 time="2020-11-29T03:58:49Z" level=info msg="Longhorn replica longhorn-system/home-assistant-r-9c449ad4 has been deleted"
2020-11-28T19:58:49.701694155-08:00 time="2020-11-29T03:58:49Z" level=info msg="Longhorn engine longhorn-system/home-assistant-e-65f011d4 has been deleted"
```
  - The error log in `longhorn-csi-plugin` during the deletion
```
2020-11-28T19:58:26.989824818-08:00 time="2020-11-29T03:58:26Z" level=info msg="GRPC request: {\"target_path\":\"/var/lib/kubelet/pods/12edf140-ccd5-4428-9b36-69382db26ec7/volumes/kubernetes.io~csi/home-assistant/mount\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"diskSelector\":\"\",\"nodeSelector\":\"\",\"numberOfReplicas\":\"2\",\"staleReplicaTimeout\":\"20\"},\"volume_id\":\"home-assistant\"}"
2020-11-28T19:58:26.989854967-08:00 time="2020-11-29T03:58:26Z" level=info msg="NodeServer NodePublishVolume req: volume_id:\"home-assistant\" target_path:\"/var/lib/kubelet/pods/12edf140-ccd5-4428-9b36-69382db26ec7/volumes/kubernetes.io~csi/home-assistant/mount\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"diskSelector\" value:\"\" > volume_context:<key:\"nodeSelector\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"2\" > volume_context:<key:\"staleReplicaTimeout\" value:\"20\" > "
2020-11-28T19:58:36.990927101-08:00 time="2020-11-29T03:58:36Z" level=error msg="GRPC error: rpc error: code = Internal desc = Get \"http://longhorn-backend:9500/v1/volumes/home-assistant\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"

2020-11-28T19:59:12.588696824-08:00 time="2020-11-29T03:59:12Z" level=info msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
2020-11-28T19:59:12.588716042-08:00 time="2020-11-29T03:59:12Z" level=info msg="GRPC request: {}"
2020-11-28T19:59:12.588719606-08:00 time="2020-11-29T03:59:12Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":3}}}]}"
2020-11-28T19:59:23.659665303-08:00 time="2020-11-29T03:59:23Z" level=info msg="GRPC call: /csi.v1.Node/NodeGetCapabilities"
2020-11-28T19:59:23.659943077-08:00 time="2020-11-29T03:59:23Z" level=info msg="GRPC request: {}"
2020-11-28T19:59:23.660562078-08:00 time="2020-11-29T03:59:23Z" level=info msg="GRPC response: {\"capabilities\":[{\"Type\":{\"Rpc\":{\"type\":3}}}]}"
```

I guess somehow your cluster (ETCD) is messed up then these weird bugs happens. Sorry for being not able to pinpoint the root cause.

**Comment by dcplaya** [comment] 2020-12-02 16:59
Does a replica get marked invalid when engine for that replica gets restarted (either by killing the pod or a reboot)?

What happens if I only have 1 replica of a PV and the replica gets marked as invalid (due to the above)? Will it throw that replica out but since there are no other replicas to rebuild from, the entire PV is gone? My Home Assistant PV only had 1 replica at the time (its been increased now). The log probably doesn't show the deletion because I didn't notice the problem until over 24 hours after it happened. 

---

As for the Ombi PV, is there a way to update the engine name in the replica manually? Or is it better to just delete the PV and restore it from a backup?

**Comment by shuo-wu** [comment] 2020-12-03 03:55
1. killing the pod or a reboot won't cause the above issue. The cause of the above issue is that the engine object (it's a Custom Resource) of the volume is directly deleted then the entire volume cannot work correctly. The **lifecycle of an engine object** should be **the same as** that of the **related volume**.
2. You can run the following command to directly update field `spec.engineName` for the replica:
```
kubectl -n longhorn-system edit replicas.longhorn.io ombi-config-r-cdb83186
```
But I would recommend you to check the cluster first. Otherwise, there will be more weird cases later.

**Comment by dcplaya** [comment] 2020-12-03 16:22
That got that PV back and running again!

I suspect my master node might have NVMe issues maybe?  That's the only NVMe that was purchased 2nd hand so I will investigate that closer. Adding a 2nd master might prevent the weird stuff from happening (as long as the 2nd master doesn't have hardware issues) but would only mask the actual hardware issue, if I have one. I have had additional weird stuff that has happened since my last post as well, so something definitely is up.

Thanks for the help, this has actually helped me understand a bit more how all the Longhorn containers integrate with each other too. I feel a little less helpless now!

**Comment by yasker** [comment] 2020-12-22 19:53
Close the issue since:
1. The issue has been resolved in the user's setup.
2. The issue seems due to an ETCD issue, in which there isn't much Longhorn can do now.

**Closed by yasker** 2020-12-22 19:53 UTC
Labels: area/manager, bug, priority/2
