### ISSUE TITLE
PoC: Kubernetes upgrade

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#763] opened 2019-09-24 01:28 UTC
PoC for #703 

- [x] Why the volumes are detaching during the upgrade?
- [x] Figure out possible ways to keep volume attached (or reattached) and still usable by the workload after Kubernetes upgrade.

**Comment by shuo-wu** [comment] 2019-10-11 19:49
After Kubernetes upgrade, the containers of instance manager pods will be restarted and all engine/replica processes info will be lost. Then `attached` volumes will become error status and be detached automatically.
  - We can know the restart by checking the event message of the instance manager pods:
    `Container engine-manager definition changed, will be restarted`
  - This behavior is already informed by [the Kubernetes doc](https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/kubeadm-upgrade/#additional-information)
  - Why the pod definition suddenly gets changed? It's [a Kubernetes bug](https://github.com/kubernetes/kubernetes/issues/53644): Once Kubernetes adds new fields for the pod container, the existing container definition/spec will be considered as changed. This issue is fixed in the version `v1.16`, see [this PR](https://github.com/kubernetes/kubernetes/pull/57741) for details.

**Comment by yasker** [comment] 2019-10-14 21:07
Maybe there is something we can do for 3.2.2.

In the worst-case scenario, we can remount to RW on the node manually
```
sudo mount -o remount,rw <disk> <mountpoint>
```
We should be able to find the mount point through the `mount` command

**Comment by shuo-wu** [comment] 2019-10-15 18:54
The uninstallation blocking issue occasionally happens in the docker/node reboot tests, too. This issue maybe not caused by the Kubernetes upgrade. We can check it after fixing the issue mentioned #743 (wrong owner reference).

**Comment by yasker** [comment] 2019-10-16 20:58
We need to verify the above remount works if we incorporate the logic.

**Comment by yasker** [comment] 2019-10-25 15:50
Tried a bit POC:
1. `remount` doesn't work. It's probably because we've changed the major:minor number of the device after reattaching it, so it's essentially a new device, even though the `/dev/longhorn/xxx` is the same.
2. But run `mount` again works, as it put another layer of the mount on top of the original mount path. Though it will result in the mount point become multiple layers. We would need to run `umount` multiple times until there is no reference to the device when we executing the `umount`, e.g. from CSI plugin.
3. It's very risky to run `umount` then `mount` again. During the process of the pod restarting, it might accidentally bind-mount the host path between the gap of `umount` and `mount` instead of the real device. That would result in pod writing data to the host path.
4. The pod needs to restart to pick up the new mount since it was bind-mounted to the previous layer of the mount point. Fortunately, the pod should restart by itself if the liveness probe was configured correctly.

**Comment by shuo-wu** [comment] 2019-10-25 20:14
We don't need to worry about the multi-layer unmount. The current CSI plugin will check the mount point after unmount. If the mount point still exists, `NodeUnpublishVolume()` will error out and be re-invoked later:
```
time="2019-10-25T20:06:13Z" level=info msg="NodeServer NodeUnpublishVolume req: volume_id:\"pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d\" target_path:\"/var/lib/kubelet/pods/20f5a635-f762-11e9-a0a8-f23c9226dc9d/volumes/kubernetes.io~csi/pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d/mount\" "
ERROR: logging before flag.Parse: E1025 20:06:13.028086       1 utils.go:100] GRPC error: rpc error: code = Internal desc = Failed to unmount path /var/lib/kubelet/pods/20f5a635-f762-11e9-a0a8-f23c9226dc9d/volumes/kubernetes.io~csi/pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d/mount
time="2019-10-25T20:06:13Z" level=info msg="NodeServer NodeUnpublishVolume req: volume_id:\"pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d\" target_path:\"/var/lib/kubelet/pods/20f5a635-f762-11e9-a0a8-f23c9226dc9d/volumes/kubernetes.io~csi/pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d/mount\" "
ERROR: logging before flag.Parse: E1025 20:06:13.641736       1 utils.go:100] GRPC error: rpc error: code = Internal desc = Failed to unmount path /var/lib/kubelet/pods/20f5a635-f762-11e9-a0a8-f23c9226dc9d/volumes/kubernetes.io~csi/pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d/mount
time="2019-10-25T20:06:14Z" level=info msg="NodeServer NodeUnpublishVolume req: volume_id:\"pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d\" target_path:\"/var/lib/kubelet/pods/20f5a635-f762-11e9-a0a8-f23c9226dc9d/volumes/kubernetes.io~csi/pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d/mount\" "
time="2019-10-25T20:06:14Z" level=debug msg="NodeUnpublishVolume: done pvc-20f43f8d-f762-11e9-a0a8-f23c9226dc9d"
```

**Comment by yasker** [comment] 2019-11-01 00:57
@shuo-wu I think it's better if we can handle it gracefully. Each error out would cause a backoff. If there are too many layers, it may take a few minutes to unmount them all. 

Also, we should try to see how many layers can we put on one mount point.

**Comment by meldafrawi** [comment] 2019-11-14 01:43
Verified.

**Closed by meldafrawi** 2019-11-14 01:43 UTC
Labels: area/engine, area/kubernetes, area/manager, poc
