### ISSUE TITLE
[BUG] Backup created in prior release takes considerable time to show up on the backup page first time.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2902] opened 2021-08-19 05:24 UTC
**Describe the bug**
For the first time, the backups created in prior release take lot of time to show up on backup page.
50 Volumes with 10 backups each, takes about 7-10 min to load properly on the backup page. (User will have to refresh the page to see the all the backups getting loaded.
At first user might get confused that the older backups are not appearing but should see them after a while.

**To Reproduce**
1. Deploy Longhorn v1.1.2
2. Create 50 volumes and take 10 backups of each volume.
3. Deploy Longhorn v1.2.0-preview-1 on another cluster.
4. The backup page in second cluster fails to list initially and slowly load them in about 7-10 min.

**Expected behavior**
UI can have some indication message that backup sync up is in progress.

**Environment:**
 - Longhorn version: v1.2.0-preview1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE - K8s 1.21.4
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Ubuntu 20.04
   - CPU per node: 2
   - Memory per node: 4
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: Upto 10 Gi
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): DO
 - Number of Longhorn volumes in the cluster: 0

**Comment by jenting** [comment] 2021-08-25 03:34
I think the problem is the same as https://github.com/longhorn/longhorn/issues/2915#issuecomment-905111637

> UI can have some indication message that backup sync up is in progress.

For this, we'll add Backup state https://github.com/longhorn/longhorn/issues/2916#issuecomment-904319017 to indicate the current backup status.

We also move backup creation from the HTTP API layer to the backup_controller layer. It means that backup creation is also asynchronous. 50 Volumes with 10 backups each will cause 500 backup CRs created and need to wait for the backup_controller to perform 500 backups in parallel. Every backup creation completed would request backup_target_controller/backup_volume_controller/backup_controller to pull the latest information from the remote backup target.

I'm thinking that how to achieve show the backup sync up is in progress indication message.
- If without local cluster backup creation, it seems doable by set `spec.syncRequestedAt=time.Now().UTC()` of the BackupTarget CR, and waits all the BackupVolume and Backup CRs `status.lastSyncedAt >= spec.syncRequestedAt=time.Now().UTC()`.
- If with local cluster backup creation, we have to make sure all the Backup CR `status=Completed` and as above, set `spec.syncRequestedAt=time.Now().UTC()` and waits all the BackupVolume and Backup CRs `status.lastSyncedAt >= spec.syncRequestedAt=time.Now().UTC()`.

**Comment by jenting** [comment] 2021-09-07 06:30
@khushboo-rancher We had added the WebSocket support on the Backup page on v1.2.0. Could you please double verify it to check if it meets the requirement?

**Comment by kaxing** [comment] 2021-09-14 09:26
Validating in progress,

Cluster info:
- 1 control node + 3 worker nodes
- Node spec:
  - EC2 t2.large, 2 cpus, 8GB ram
- K8s distro:
  - v1.20.10 deploy via rancher 2.5.9

Test:
1. Setting up two identical clusters, 1 with v1.2.0-preview1 and the other one with master-head version (2021-09-14)
2. On the first cluster, deploy 50 volumes (size 128Mi) with 10 backups of each volume
3. Then point the 2nd cluster to the same s3 bucket

then observe the backup page


Result:
I can tell with latest master version it is much faster also the display will be showing the backup-volumes when they are being pulled.
But I would like to find a way to get a metric/measurement before close this issue.

**Comment by kaxing** [comment] 2021-09-15 11:51
@khushboo-rancher please take a look.

By observing `v1/ws/1s/backupvolumes` with today's master (ui: 4de5ec1), the WS messaging stops in about 2.5mins.

And the in-progress backups will look like this:
![image](https://user-images.githubusercontent.com/602540/133427950-5c9ac19a-2c63-4327-85a6-2f1c9cadbf98.png)

HAR file for reference: [ui-50x3-backups.har.zip](https://github.com/longhorn/longhorn/files/7169751/ui-50x3-backups.har.zip)

**Comment by khushboo-rancher** [comment] 2021-09-16 01:00
I see, there is improvement.
Earlier with 50 volumes having 10 backups each, it was taking around 7 mins. Now on the master, it takes around 2 mins.

@jenting As @kaxing has mentioned that WS messaging stops in about 2.5mins, so user have to refresh the page to see the backups loaded after 2.5 min.

For example, 50 volumes with 50 backups takes around 8 mins, in that case backups stop getting updated the backup page after 2.5 min and user has to refresh the page to see all the backups.

**Comment by jenting** [comment] 2021-09-16 01:47
We'll check the culprit is backend _or_ frontend first. Thanks for the testing effort.

**Comment by kaxing** [comment] 2021-09-16 03:46
Hey @jenting @khushboo-rancher, sorry for the miswording here.
When I say WS messaging stops, means the communication finished loading the information for `backupvolumes`.

Attaching screen recording for clarifying, you can see the backup polling is about to finished, and data will silently fill up in the table: [Click to open the clip](https://user-images.githubusercontent.com/602540/133545620-18955926-84d4-45d9-855c-6139db034e8c.mp4)

**Comment by kaxing** [comment] 2021-09-27 12:37
Testing again with v1.2.1-rc2, with more than 100 volumes, the backups items can be downloaded in about 5mins. cc @khushboo-rancher maybe there is other combination(size x volume numbers) to be tested with, but as for now I don't have to refresh page to see all the `backupvolumes` being downloaded.

**Comment by kaxing** [comment] 2021-09-28 04:44
Validation: **PASSED**

Check again with master-head(20210928) on local k3s cluster with 1000+ backups, the data pulling can be finished around 10mins.

Measure by observing WebSocket messaging and the Backup CRDs status at the same time:
```console
$ kubectal get backups -n longhorn-system -w
```

Also comparing with the `LASTSYNCEDAT` time when the pulling finished:
```console
$ kubectl get backups -n longhorn-system | sort -k6
```

**Closed by kaxing** 2021-09-28 04:44 UTC
Labels: kind/bug, reproduce/always, priority/3, severity/3, area/performance
