### ISSUE TITLE
[IMPROVEMENT] Deprecate the setting `allow-node-drain-with-last-healthy-replica` and replace it by `node-drain-policy` setting

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#5585] opened 2023-03-17 22:43 UTC
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

We introduced the new setting `node-drain-policy` in https://github.com/longhorn/longhorn-manager/pull/1775. The new setting covers all use cases of the old setting `allow-node-drain-with-last-healthy-replica` and have extra options.  Therefore we should deprecate the setting `allow-node-drain-with-last-healthy-replica` and replace it by `node-drain-policy` setting.

Work needs to be done:
* Document
* Longhorn manager logic
* Possibly upgrade/migration if needed

**Comment by yangchiu** [comment] 2023-04-28 07:12
For `Make sure that Longhorn UI setting page indicates that the setting Allow Node Drain with the Last Healthy Replica is deprecated`, I'm unable to find any description on Longhorn UI setting page indicates it's deprecated on `master-head`. Do we have a ticket about this UI change? @innobead

**Comment by innobead** [comment] 2023-04-28 08:24
@PhanLe1010 I believe we need to change the setting to `SettingTypeDeprecated`. Please help with this change. 
[/types/setting.go#L693](https://github.com/longhorn/longhorn-manager/blob/5baf2395594e9f2b0b216fddd88099c1a3a60bf5/types/setting.go#L693)
```go
		Type:     SettingTypeBool,
		Required: true,
```

**Comment by PhanLe1010** [comment] 2023-04-28 09:45
Changing setting type to SettingTypeDeprecated will removed the setting from UI and user will not be able to set it. 

Should we do this in 1.3 and 1.4 @innobead ?

**Comment by innobead** [comment] 2023-04-28 13:32
Oh should not. I think the UI should be refined, the deprecated item should not be removed but highlighted instead. 

Let's just need to remove this setting from 1.5.0.

I will create an issue for UI improvement for deprecated setting.

**Comment by PhanLe1010** [comment] 2023-05-01 19:39
> the deprecated item should not be removed but highlighted instead

I agree

**Comment by innobead** [comment] 2023-05-29 01:38
In 1.5.0, this old setting should be removed, since it has been introduced in the previous patches like 1.4.x. https://github.com/longhorn/longhorn/wiki/Deprecation-Policy

This issue is still pending in `implement` phase, @PhanLe1010 could you help with this to move this to ready-for-testing for QA? thanks.

**Comment by innobead** [comment] 2023-05-29 01:52
This is actually a duplicate of https://github.com/longhorn/longhorn/issues/5620. Let's close this for 1.5.0.

**Closed by innobead** 2023-05-29 01:52 UTC
Labels: priority/0, require/doc, kind/improvement, backport/1.3.3, backport/1.4.2
