### ISSUE TITLE
[QUESTION] Cyclic/Scheduled restore-to-file of backup

### ISSUE THREAD

**Issue by quasarchimaere** [longhorn/longhorn#2649] opened 2021-06-01 14:35 UTC
**Question**
We are running a cluster with multiple nodes and just recently switched from microk8s over to rke. although we hope that our rke cluster is more stable than the microk8s based one we used, we would still like to store some form of backup that can be mounted independently of a running cluster.

We have around 3 PVs that we are cyclically backing up using a nfsv4 based storage (on a machine outside of the cluster), as i have seen on the nfs storage, these backups are stored in a (seemingly to me) longhorn proprietary format and thus not mountable by a given unix machine by default (please correct me if i am missing something)

However: I found out that there is a way to store (any) saved backup into its own file (which can be mounted), this uses a pod on a running worker node and thus makes it necessary to have a running cluster. this would be perfectly fine with me.

My Question is: Is there a way to schedule a job (lets say once or twice a week) that would create these restore-to-file pods based on the latest available backup of one of the scheduled PVs and copy the mountable file back onto our nfsv4 storage?

thx in advance for any guidance and help

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes version: 1.20.something

**Comment by PhanLe1010** [comment] 2021-06-01 20:31
> We have around 3 PVs that we are cyclically backing up using a nfsv4 based storage (on a machine outside of the cluster), as i have seen on the nfs storage, these backups are stored in a (seemingly to me) longhorn proprietary format and thus not mountable by a given unix machine by default (please correct me if i am missing something)

Yes, you are correct. Backups are in the Longhorn format.

Correct me if I am wrong. So I am understanding that you want to:
1. Create recurring backups for your 3 PVCs into NFS storage outside of your cluster
2. Periodically restore the backups to Longhorn volume and attach the volume to one of the worker nodes.
3. Copy the files of the volumes back to NFS storage so that they can be understood by anyone

I don't think that we ever try the above process but I think yes, you can write a script to achieve that goal. The step 1 is done by Longhorn. The step 2 will be done by your scripts talking to Longhorn APIs. See more about how to create a python script that can control Longhorn https://longhorn.io/docs/1.1.1/references/longhorn-client-python/ . The step 3 would be don by your script talking to the NFS storage.

However, I not sure if you really need to have raw files on the NFS storage. In my opinion, you can just keep backups in the NFS storage in Longhorn format. Then when you want your data in a different cluster, you can install Longhorn, point Longhorn to the NFS storage, copy data from NFS to your new cluster.

**Comment by PhanLe1010** [comment] 2021-06-02 20:05
@quasarchimaere 

Thank you for explaining your use case.

> Can one just attach the backup nfs store to a new/clean cluster in the longhorn configuration and access the old backups from a previous installation?

Yes, you can. By design, you can attach the NFS backup store to a brand new cluster that have Longhorn installed and restore the data into the new cluster.

We even push this approach further with the feature [disaster recovery volumes](https://longhorn.io/docs/1.1.1/snapshots-and-backups/setup-disaster-recovery-volumes/). The idea is that you have a backup cluster along with the production cluster. Longhorn is installed in both the backup cluster and the prod cluster. The 2 clusters point to the same NFS backup store. In the prod cluster, you can set recurring backup jobs that periodically backup the data to the NFS storage. Then in the backup cluster, you create disaster recovery volumes that periodically syncs data from NFS storage into the backup cluster. In case the prod goes down, you can quickly activate the disaster recovery volumes and have all of your data ready for your application. 

> as i can see the longhorn formatted backup doesn't nearly amount to the size of the actually stored data (our nfs backup folder currently is around 78mb and stores daily backups of 3pv with a size from 200-1600mb) this somehow indicates to me that the actual data is still stored within the cluster, and thus makes a backup to another cluster impossible if the first cluster goes down.

No need to worry, the backups in NFS storage have full data of PVCs. The reason that the size of the backup is smaller than the size of the PVC is Longhorn only backups the region that has the actual data (e.g., Longhorn ignores the regions with `0s` in the block device that backs the PVCs). See https://longhorn.io/docs/1.1.1/concepts/#21-thin-provisioning-and-volume-size for more details. Furthermore, Longhorn compresses the backups before sending them to the NFS server.

**Comment by jenting** [comment] 2021-11-05 03:28
I think the question be answered already.
I'd prefer to close this question, feel free to reopen it once you have more.

**Closed by jenting** 2021-11-05 03:28 UTC
Labels: kind/question
