### ISSUE TITLE
[BUG] High CPU usage on one node.

### ISSUE THREAD

**Issue by fmq** [longhorn/longhorn#6578] opened 2023-08-23 02:32 UTC
## Describe the bug (🐛 if you encounter this issue)

We have a cluster with 3 worker nodes running 3 environments + Loki + Prometheus + Grafana + Minio, one of the servers have high cpu usage from the Instance manager, it basically consumes over 1 CPU when in the other nodes it consumes < 100m.

We also detected the following log in the instance manager pod

`
[longhorn-instance-manager] time="2023-08-23T02:22:11Z" level=error msg="Failed to receive next item in process watch" error="rpc error: code = Unavailable desc = keepalive ping failed to receive ACK within timeout"
`
## To Reproduce

N/A

## Expected behavior

All nodes behave in the same maner and consume a reasonable amount of CPU

## Support bundle for troubleshooting

[supportbundle_a1cc04ad-a7b1-44c1-a239-b8a956ed43fc_2023-08-23T02-28-23Z.zip](https://github.com/longhorn/longhorn/files/12414560/supportbundle_a1cc04ad-a7b1-44c1-a239-b8a956ed43fc_2023-08-23T02-28-23Z.zip)

## Environment

 - Longhorn version: v1.5.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K8 1.28
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: CentOS 7
   - Kernel version: 3.10.0-1160.95.1.el7.x86_64
   - CPU per node: 3
   - Memory per node: 16g
   - Disk type(e.g. SSD/NVMe/HDD): ssd
   - Network bandwidth between the nodes: 
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Azure VM
 - Number of Longhorn volumes in the cluster: 18

## Additional context

Some additional Info:

kubectl top po
instance-manager-5b4f8e9293673b61843ec90d86572317                 62m          466Mi
instance-manager-cd6e4595e2282572b9b2580deb2b9024                 1163m        460Mi
instance-manager-de8c80e633236a07311ae611a2e7adc8                 87m          866Mi

This is our Grafana monitor showing CPU usage (note that 90% of this CPU usage comes from one node):

![image](https://github.com/longhorn/longhorn/assets/881660/5c44d3e5-82cf-43ab-ac6b-7071214d216c)

## Workaround

Before the release v1.5.2, please refer to the steps and temporary longhorn-instance-manager with the fix in https://github.com/longhorn/longhorn/issues/6645#issuecomment-1756807554.

**Comment by derekbit** [comment] 2023-08-23 02:59
According to the error message, the communication between the instance service and the other services in the instance-manager pod looks somehow unavailable.
Can you log into the instance-manager pod and provide the output of `ss -tunap`? Thank you.

**Comment by fmq** [comment] 2023-08-23 03:34
Sure.. 

![image](https://github.com/longhorn/longhorn/assets/881660/a60d727c-5d83-4f4c-9c4b-64ad8c2e265f)

**Comment by derekbit** [comment] 2023-08-23 04:11
@fmq Not `longhorn-manager `pod, should be `instance-manager` pod with high CPU usage.

**Comment by fmq** [comment] 2023-08-23 04:33
Sorry about that!

[instance-manager-ss.txt](https://github.com/longhorn/longhorn/files/12415134/instance-manager-ss.txt)

**Comment by fmq** [comment] 2023-08-23 04:38
Just in case it's related.. I'm also seeing in the same node that there is a pod "longhorn-driver-deployer....." that is Crashing also with the following log:

`
W0823 04:29:41.147763 1 client_config.go:618] Neither --kubeconfig nor --master was specified. Using the inClusterConfig. This might not work.
time="2023-08-23T04:29:41Z" level=info msg="Deploying CSI driver"
time="2023-08-23T04:29:41Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2023-08-23T04:29:42Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Pending"
time="2023-08-23T04:29:43Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:44Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:45Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:46Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:47Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:48Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:49Z" level=info msg="proc cmdline detection pod discover-proc-kubelet-cmdline in phase: Running"
time="2023-08-23T04:29:50Z" level=info msg="Proc found: kubelet"
time="2023-08-23T04:29:50Z" level=info msg="Try to find arg [--root-dir] in cmdline: [/usr/bin/kubelet --bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf --kubeconfig=/etc/kubernetes/kubelet.conf --config=/var/lib/kubelet/config.yaml --container-runtime-endpoint=unix:///var/run/containerd/containerd.sock --pod-infra-container-image=k8s.gcr.io/pause:3.7 ]"
time="2023-08-23T04:29:50Z" level=warning msg="Cmdline of proc kubelet found: \"/usr/bin/kubelet\x00--bootstrap-kubeconfig=/etc/kubernetes/bootstrap-kubelet.conf\x00--kubeconfig=/etc/kubernetes/kubelet.conf\x00--config=/var/lib/kubelet/config.yaml\x00--container-runtime-endpoint=unix:///var/run/containerd/containerd.sock\x00--pod-infra-container-image=k8s.gcr.io/pause:3.7\x00\". But arg \"--root-dir\" not found. Hence default value will be used: \"/var/lib/kubelet\""
time="2023-08-23T04:29:50Z" level=info msg="Detected root dir path: /var/lib/kubelet"
time="2023-08-23T04:29:50Z" level=info msg="Upgrading Longhorn related components for CSI v1.1.0"
time="2023-08-23T04:29:50Z" level=info msg="Detected CSI Driver driver.longhorn.io CSI Git commit 8ce69c8f280a5a2715c528034e0274391ad761c0 version v1.5.1 Kubernetes version v1.28.0 has already been deployed"
time="2023-08-23T04:31:50Z" level=fatal msg="Error deploying driver: failed to start CSI driver: failed to deploy service csi-attacher: failed to cleanup service csi-attacher: foreground deletion of service csi-attacher timed out"
`

**Comment by derekbit** [comment] 2023-08-23 05:02
Other services in the instance-manager pod are still alive.
Can you download the [grpc client cli tool](https://github.com/vadimi/grpc-client-cli/releases/tag/v1.18.0) in the instance-manager pod and try
```
grpc-client-cli :8500
```

8500 port is used by the process service. I'd like to check if the service is really alive.

cc @shuo-wu @PhanLe1010 @ejweber any thought?

BTW, I think we need to error out or add a sleep in https://github.com/longhorn/longhorn-instance-manager/blob/master/pkg/instance/instance.go#L520? But how to distinguish the error is recoverable or unrecoverable?

**Comment by fmq** [comment] 2023-08-23 11:42
Hello.. sorry for the delay but I'm GMT-3 :-)

It seems to be responding correctly..

![image](https://github.com/longhorn/longhorn/assets/881660/800d3be7-3500-42ed-9c24-80f71a76e4f2)

**Comment by fmq** [comment] 2023-08-24 22:03
Any ideas?

**Comment by derekbit** [comment] 2023-08-24 23:33
No idea for the `keepalive ping failed to receive ACK within timeout` currently.
You can scale down applications using the volumes on the problematic node, drain and restart the node. Check if the issue can be resolved. 
We will improve the error handling first.

**Comment by fmq** [comment] 2023-08-25 02:56
Ok, will do that and let you know

**Comment by fmq** [comment] 2023-08-25 04:07
So I did as proposed and the error disappeared, I would have loved to understand the cause of the error in order to be able to prevent it.

Thanks for your help

**Comment by derekbit** [comment] 2023-08-25 04:43
Reopen the ticket. Let's keep the issue open and improve the error handling.

**Comment by fmq** [comment] 2023-08-25 21:15
The error returned, so any help you can give would be greatly appreciated.

**Comment by derekbit** [comment] 2023-08-28 03:09
@fmq 
Weird. I will try to reproduce the issue first and keep you posted.

**Comment by fmq** [comment] 2023-08-28 11:15
@derekbit if you think of anything I can do to help don’t hesitate to contact me

**Comment by derekbit** [comment] 2023-08-28 11:22
Can you provide me with the latest support bundle? I'd check if I can find any clue. Thank you.

**Comment by fmq** [comment] 2023-08-28 12:21
Here you go.. 

[supportbundle_a1cc04ad-a7b1-44c1-a239-b8a956ed43fc_2023-08-23T02-28-23Z.zip](https://github.com/longhorn/longhorn/files/12454274/supportbundle_a1cc04ad-a7b1-44c1-a239-b8a956ed43fc_2023-08-23T02-28-23Z.zip)

**Comment by ejweber** [comment] 2023-09-01 18:26
@fmq, can you confirm which process in particular is consuming CPU? In some cases, it has been tgtd, though with the symptoms you and @derekbit have discussed, I'm guessing its actually longhorn-instance-manager itself. Something like:

```
-> kubectl exec -n longhorn-system -it instance-manager-e-7c972230 top
top - 18:25:44 up 38 days, 22:38,  0 users,  load average: 0.12, 0.25, 0.45
Tasks:   7 total,   1 running,   6 sleeping,   0 stopped,   0 zombie
%Cpu(s):  6.4 us,  3.2 sy,  0.0 ni, 88.0 id,  0.0 wa,  0.0 hi,  0.5 si,  1.9 st
MiB Mem : 3923.961 total, 1223.188 free, 1309.906 used, 1390.867 buff/cache
MiB Swap:    0.000 total,    0.000 free,    0.000 used. 2390.414 avail Mem 

    PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                                                                                                                                                                 
      7 root      20   0 1608184  13452   5616 S 1.000 0.335  23:22.24 longhorn-instan                                                                                                                                                                                         
    301 root      20   0 1312820  17044  10828 S 0.667 0.424   5:02.98 longhorn                                                                                                                                                                                                
      1 root      20   0    4564     96      0 S 0.000 0.002   0:03.53 tini                                                                                                                                                                                                    
      9 root      20   0  409816  39536   2404 S 0.000 0.984   0:23.72 tgtd                                                                                                                                                                                                    
     10 root      20   0    4580     92      0 S 0.000 0.002   0:00.00 tee                                                                                                                                                                                                     
    700 root      20   0 1313744  62544  13864 S 0.000 1.557   5:06.99 longhorn                                                                                                                                                                                                
    862 root      20   0   40456   4204   3652 R 0.000 0.105   0:00.09 top    
```

**Comment by fmq** [comment] 2023-09-01 19:53
@ejweber as you guessed it is the instance manager itself...

![image](https://github.com/longhorn/longhorn/assets/881660/aed65573-684f-4b28-b84b-4028ffa4b38e)

**Comment by derekbit** [comment] 2023-09-13 14:47
@m3nax 
A support bundle is appreciated. I didn't see any clue from @fmq's support bundle for now. Thank you.

**Comment by derekbit** [comment] 2023-09-14 02:46
The symptom of the issue `keepalive ping failed to receive ACK within timeout` is similar with https://github.com/grpc/grpc-go/issues/5308

**Comment by m3nax** [comment] 2023-09-14 06:42
> @m3nax A support bundle is appreciated. I didn't see any clue from @fmq's support bundle for now. Thank you.

Ok, next time I'll attach a support package

**Comment by m3nax** [comment] 2023-09-14 07:01
@derekbit Support bundle generated, how can I send it?

**Comment by derekbit** [comment] 2023-09-14 07:03
@m3nax 
You can mail to longhorn-support-bundle@suse.com. Thank you.

**Comment by m3nax** [comment] 2023-09-14 07:06
@derekbit Sent

**Comment by derekbit** [comment] 2023-09-15 12:53
@m3nax  Same issue, but the root cause of the broken keepalive between gRPC server and client is unknown from the support bundle. I'm working on the error handling, and it should be included in the upcoming v1.5.2. Before that, you can apply the workaround described in https://github.com/longhorn/longhorn/issues/6578#issuecomment-1718816096.

**Comment by derekbit** [comment] 2023-09-25 06:33
@fmq @m3nax I've fixed the issue. Can you help us test if the fix work in your env? If yes, I can build a custom image for you.

**Comment by shuo-wu** [comment] 2023-10-10 04:09
Found one more high memory/CPU usage case caused by the broken keep-alive BUG: https://github.com/longhorn/longhorn/issues/6645#issuecomment-1754321228

**Comment by fmq** [comment] 2023-10-10 11:51
Sorry I misssed the notification, we had to move out of Longhorn since the bug had spread to another one of the servers and it was causing hell on our application (we have a lot of services for the number of cpu's) , I will return to Longhorn eventually, when the new version comes out with this fixed. 

Thanks for the effort

**Comment by cianomutech** [comment] 2023-10-18 08:34
> @fmq @m3nax I've fixed the issue. Can you help us test if the fix work in your env? If yes, I can build a custom image for you.

Hi, I'm a coworker of @m3nax. We want to try the fixed version so you're welcome to build a custom image that we could use.
bye

**Comment by derekbit** [comment] 2023-10-18 11:26
> [BUG] longhorn-manager process is consuming high memory on nodes #6645

@cianomutech Please refer to the steps in https://github.com/longhorn/longhorn/issues/6645#issuecomment-1756807554. Thank you.

**Comment by cianomutech** [comment] 2023-10-19 08:30
> > [BUG] longhorn-manager process is consuming high memory on nodes #6645
> 
> @cianomutech Please refer to the steps in [#6645 (comment)](https://github.com/longhorn/longhorn/issues/6645#issuecomment-1756807554). Thank you.

@derekbit hello. We installed the modified version of instance manager. We'll monitor if the problem may rise again.

**Comment by m3nax** [comment] 2023-10-27 08:35
@derekbit One week passed and the fix seems to work

**Comment by derekbit** [comment] 2023-10-27 08:43
@m3nax 
Thank you for the update. The update makes us more confident for the fix.

**Comment by chriscchien** [comment] 2023-11-03 06:48
It is hard to reproduce the high CPU usage int the test environment. However, after user have been using the fixing image for more than 1 weeks(https://github.com/longhorn/longhorn/issues/6578#issuecomment-1782521734), the instance-manager pod has been working properly in user's environment, I would like to close this ticket, thanks.

**Closed by chriscchien** 2023-11-03 06:48 UTC
Labels: kind/bug, area/instance-manager, priority/0, require/qa-review-coverage, backport/1.5.2

**Comment by m3nax** [comment] 2023-11-03 07:17
@chriscchien I confirm, the fix still work
