### ISSUE TITLE
Attaching/detaching/deleting takes a very very long time

### ISSUE THREAD

**Issue by ColonelBundy** [longhorn/longhorn#1058] opened 2020-02-15 14:00 UTC
Attaching/detaching/deleting takes over an hour, this started happening before my upgrade from 0.6.2 to 0.7.0 and to my disappointment it did not solve it.

Events:

> AttachVolume.Attach failed for volume "pvc-2d597c9c-354b-4acf-9309-991df142811d" : rpc error: code = Aborted desc = The volume pvc-2d597c9c-354b-4acf-9309-991df142811d is attaching

> AttachVolume.Attach failed for volume "pvc-56dbe41b-da29-4442-b662-a593a8f545ef" : rpc error: code = DeadlineExceeded desc = context deadline exceeded

**Comment by yasker** [comment] 2020-02-15 17:04
How long it take to attach a volume in UI? it should be in the matter of seconds.

**Comment by ColonelBundy** [comment] 2020-02-15 18:00
@yasker Same thing, an hour or more.

**Comment by yasker** [comment] 2020-02-15 18:09
@ColonelBundy Something seems wrong. Can you send us a support bundle to longhorn-support-bundle@rancher.com ?

**Comment by yasker** [comment] 2020-02-15 18:09
And which OS you're using on the node?

**Comment by ColonelBundy** [comment] 2020-02-15 18:17
@yasker Ubuntu 18.04, cpu and memory have not gone over 30% (16 cores 64gb per node)

support bundle has been sent.

**Comment by yasker** [comment] 2020-02-15 18:32
@ColonelBundy I think you're hitting a scalability issue similar to https://github.com/longhorn/longhorn/issues/1054 . 

Can you give me the output of `kubectl -n longhorn-system top pods`

We're having a new release soon. Let me see if we can reproduce the issue in house and fix it in the upcoming release.

**Comment by ColonelBundy** [comment] 2020-02-15 18:52
@yasker here's the output:

```
NAME                                        CPU(cores)   MEMORY(bytes)
compatible-csi-attacher-7b94ffbf47-26v7k    1m           12Mi
csi-attacher-68dc579f54-6prl9               1m           9Mi
csi-attacher-68dc579f54-mpb5q               1m           6Mi
csi-attacher-68dc579f54-vpkf4               1m           6Mi
csi-provisioner-c48cd9cc9-nlccp             1m           6Mi
csi-provisioner-c48cd9cc9-vqsrp             1m           6Mi
csi-provisioner-c48cd9cc9-xqjqc             1m           10Mi
engine-image-ei-ec95b5ad-r8rhr              2m           19Mi
instance-manager-e-c993a1db                 67m          297Mi
instance-manager-r-81de4f23                 71m          1324Mi
longhorn-csi-plugin-27tcv                   5m           30Mi
longhorn-driver-deployer-584b7bf585-g5jgd   1m           8Mi
longhorn-manager-6gltq                      257m         77Mi
longhorn-ui-b58fc6968-86tpr                 1m           9Mi
```

Looked at the issue you linked and that may be the case since I currently have around 40 volumes.
But nothing alarming about cpu usage etc spikes when creating or attaching a volume.

**Comment by yasker** [comment] 2020-02-15 19:16
@ColonelBundy Yeah, so I think it's probably some bottlenecks inside the manager code stop it from responding faster. I am looking into it.

**Comment by yasker** [comment] 2020-02-16 00:00
I've found the reason. It's caused by some unnecessary writes to the Kubernetes API server. The issue has already been fixed in the upcoming v0.8.0 release, as a part of https://github.com/longhorn/longhorn-manager/commit/c07e40500af68eba751fad2ddbc3338b5619981c

**Comment by yasker** [comment] 2020-02-16 06:48
It seems not caused by a single issue. It seems starting with the 30 volumes on the node, the time used for creating/attaching volume increased exponentially even with v0.8.0. Still investigating.

**Comment by ColonelBundy** [comment] 2020-02-18 18:14
@yasker Thanks for the update.

**Comment by yasker** [comment] 2020-03-01 19:07
We have managed to dramatically improve the attach/detach performance with large numbers of volume. If you're using more than 30 volumes per node, you might see 100 times+ improvement.

A few test results with the latest fix in place.

**Longhorn setup:** v0.8.0-rc2 (to be released), 3 replicas per volume, soft anti-affinity enabled.
**Environment:** Single node Kubernetes cluster v1.16.7. **16 vCPU/64 GB RAM**.
**Yaml:** https://github.com/longhorn/longhorn/blob/master/examples/statefulset.yaml
Test method: create/scale the statefulset to 80.
Notice the statefulset scales one pod at a time. It's not done in parallel.
The number **80** was chosen because the cluster will be running with 106 pods when fully scaled. And Kubernetes has per node Pod number limitation of 110.
1. Creating the statefulset with scale 80. From `kubectl create` to the pod 79 starts running: 26m32s. **19.9s per pod**
2. Scale the statefulset to 0. From `kubectl scale` to the pod 0 stops: 5m. **3.75s per pod.**
3. Scale the statefulset to 80 again. From `kubectl scale` to the pod 79 starts running: 14m20s. **10.75s per pod**

**Comment by ColonelBundy** [comment] 2020-03-02 16:59
@yasker That's awesome! I'm looking forward to the 0.8.0 release. Thank you and good work!

**Comment by meldafrawi** [comment] 2020-03-05 20:31
Results using **same instance** specs, and same **kubernetes** and **Longhorn** versions:

1. **[Create + Attach]** Create the statefulset with scale 80. From kubectl create to the pod 79 starts running: 25min 10 sec
    * **18.875: per pod on average**

2. **[Detach]** Scale the statefulset to 0. From kubectl scale to the pod 0 stops: 4 min 13 sec
    * **3.1625 per pod on average**

3. **[Attach]** Scale the statefulset to 80 again. From kubectl scale to the pod 79 starts running: 13 min 28 sec
    * **10.1 per pod on average**

CPU utilization with 80 idle volumes (and 80 engines as well as 240 replicas) attached on the node:

```
$ kubectl top -n longhorn-system pod

NAME                                        CPU(cores)   MEMORY(bytes)   
compatible-csi-attacher-d9fb48bcf-8mg8h     1m           10Mi            
csi-attacher-78bf9b9898-5mzpz               1m           6Mi             
csi-attacher-78bf9b9898-bplmh               1m           5Mi             
csi-attacher-78bf9b9898-svncn               1m           12Mi            
csi-provisioner-8599d5bf97-5f9p8            1m           6Mi             
csi-provisioner-8599d5bf97-qfcdq            1m           12Mi            
csi-provisioner-8599d5bf97-zl2l7            1m           7Mi             
csi-resizer-586665f745-97s6m                1m           8Mi             
csi-resizer-586665f745-djpf2                1m           5Mi             
csi-resizer-586665f745-zjdx2                1m           5Mi             
engine-image-ei-f5bd42a2-k6lcz              2m           19Mi            
instance-manager-e-b71e9582                 292m         547Mi           
instance-manager-r-2a3b1145                 330m         2312Mi          
longhorn-csi-plugin-mwrb4                   13m          31Mi            
longhorn-driver-deployer-7b6b74d87d-2mlbv   1m           8Mi             
longhorn-manager-9rtgt                      1289m        109Mi           
longhorn-ui-68d6bf44b7-v77wv                1m           3Mi       
```

**Closed** 2020-03-05 22:39 UTC
Labels: area/manager, bug, highlight

**Comment by maxiloEmmmm** [comment] 2021-11-10 08:25
v1.2.2 the same problem arises
![image](https://user-images.githubusercontent.com/16779121/141076797-06adf5b0-9232-49de-8029-1f7a0fcef8d2.png)
