### ISSUE TITLE
SnapshotPurge error cases handle improvement

### ISSUE THREAD

**Issue by boknowswiki** [longhorn/longhorn#1895] opened 2020-10-21 00:50 UTC
Currently, for snapshot purge there are two steps, first step to start the purge seems missing some error status return [here](https://github.com/longhorn/longhorn-engine/blob/86fada305f2331aba0f10f20b575e28b206f6933/pkg/sync/sync.go#L166-L174). which is get start failure or success. Second step is to do the actual work with a separate go routine [here](https://github.com/longhorn/longhorn-engine/blob/86fada305f2331aba0f10f20b575e28b206f6933/pkg/sync/rpc/server.go#L830). 

We need to revisit this part to make sure the error case is handled properly.

Some notes:
If there is any error maybe we should mark the replica as 'ERR' state, and let volume controller to trigger a rebuild from a good one. Also tried to failed the purge by resize the new snapshot with a smaller size to mimic this error
```[instance-manager-r-1faf369f] time="2020-10-21T00:36:24Z" level=info msg="Coalescing volume-snap-d189d75b-8680-450b-9ffe-ea9ff78ef004.img to volume-snap-89fb93c6-8097-4102-a06f-ae704bf5adf2.img" 
[instance-manager-r-1faf369f] time="2020-10-21T00:36:24Z" level=error msg="failed to coalesce volume-snap-d189d75b-8680-450b-9ffe-ea9ff78ef004.img on volume-snap-89fb93c6-8097-4102-a06f-ae704bf5adf2.img: file sizes are not equal and the parent file is larger than the child file" 
```

And currently there is no rebuild or replica is not marked as error, but we have an exclamation mark on the replica to indicate the error

![Screen Shot 2020-10-20 at 5.49.04 PM.png](https://images.zenhubusercontent.com/5ea86ddb41903e5d4e29e34f/346a894a-09ad-4db7-a4a9-d7cfff4cf818)

**Comment by PhanLe1010** [comment] 2021-01-07 02:24
There are 2 problems in this issue:
1. Error when starting SnapshotPurge is not reported back to Longhorn manager
2. How do we handle the situation when we detect a bad replica while doing SnapshotPurge?

The problem #1 is fixed by https://github.com/longhorn/longhorn-engine/pull/556
The problem #2 is part of a bigger problem: how do we monitor/handle the situation where the files in some replicas are corrupted (by users or external error). I think `detecting and marking a bad replica while doing SnapshotPurge` is not a complete solution for this problem because it depends on whether Longhorn pick the corrupted replica to be the source for rebuilding. Also, if SnapshotPurge doesn't happened, we don't detect the bad replica.

Currently we don't detect if a replica has corrupted files until the engine reads/writes to the location of that file.
I am thinking if we should have some background process/controller that periodically check the consistent of volume's replicas

@yasker @shuo-wu @joshimoo

**Comment by shuo-wu** [comment] 2021-01-07 06:04
I think the case here is similar to what we encountered in the restore part. I can take a look first: There may be errors before the restore start (failed to execute the cmd) or during the restoring progress. For the error returned by the cmd, Longhorn manager will [record it in the status by itself](https://github.com/longhorn/longhorn-manager/blob/73b66414ce281a91658d2b120a1933dd84ad99cb/controller/engine_controller.go#L1084). For the error during the restoring progress, it will be recorded by the engine/replica process automatically. Then once there is an error in the restore status, the volume controller of longhorn manager will [mark the replica as failed](https://github.com/longhorn/longhorn-manager/blob/73b66414ce281a91658d2b120a1933dd84ad99cb/controller/volume_controller.go#L544).

As for the periodic data check, it's almost impossible. Since the replica directory on each node may store thousands of gigabyte data, checking/syncing these data may consume lots of CPU/IO/Network resources then degrade the whole cluster greatly. Besides, the data/files in the replica directory may be always changing, which means the checking result may be out-of-date in the next second.

**Comment by PhanLe1010** [comment] 2021-01-07 18:33
Thanks @shuo-wu for the suggestion 

Regarding to the error during the snapshot purge progress, it might the case that the replica fail to delete a snapshot because a transient error. Marking replica faulty has a big cost and not every snapshot purge error is critical and require marking the replica as faulty. Therefore, I am thinking we should design an error/response codes as mentioned in https://github.com/longhorn/longhorn/issues/1875 . Something similar to http repose code.

**Comment by PhanLe1010** [comment] 2021-01-08 06:28
**Reproduce Steps:**
1. Create a volume of 3 replicas. Attach to a pod.
2. Take a snapshot. Delete a replica. Wait for the rebuild to finish. Take an other snapshot. The end result should look like:
   <img width="843" alt="Screen Shot 2021-01-06 at 2 41 32 PM" src="https://user-images.githubusercontent.com/22139961/103981641-10b0b780-5137-11eb-87ed-6882bc410c97.png">
3. ssh into a node, reside the snapshot on the left side of the volume-head in the above picture. (e.g `dd if=/dev/urandom count=50 bs=1M of=<SNAPSHOT-NAME>.img`)
4. Triggle snapshot purge by delete the snapshot on the right most
5. Verify that the replica is not marked as failed. Longhorn doesn't rebuild the replica. Similar to the picture at https://github.com/longhorn/longhorn/issues/1895#issue-726043071

**Test Steps:**
Verify that Longhorn rebuilds the replica in step 5 above

**Comment by PhanLe1010** [comment] 2021-01-08 22:40
**Test steps for Error when starting SnapshotPurge**
1. Create a volume. Attach it to a pod. Write 500MB to the volume
2. Take 2 snapshots.
2. Delete a replica to trigger replica rebuilding
3. While the rebuilding is happening, delete a snapshot to trigger SnapshotPurge. 
4. Verify that Longhorn manager reporting error similar to this format `Failed to purge snapshots: REPLICA_ADDRESS: cannot purge snapshots because REPLICA_ADDRESS is rebuilding`
   ```
   [longhorn-manager-xm6w5] time="2021-01-08T22:35:15Z" level=error msg="Error in request: fail to purge snapshot: error starting snapshot purge: failed to execute: /var/lib/longhorn/engine-binaries/phanle1010-longhorn-engine-purge_error_2/longhorn [--url 10.42.2.21:10000 snapshot purge --skip-if-in-progress], output , stderr, time=\"2021-01-08T22:35:15Z\" level=fatal msg=\"Error running purge snapshot command: Failed to purge snapshots: tcp://10.42.2.44:10000: cannot purge snapshots because tcp://10.42.2.44:10000 is rebuilding\"\n, error exit status 1" 

   ```

**Comment by khushboo-rancher** [comment] 2021-01-15 02:16
Verified with Longhorn-master - `01/14/2020`

Validation - **Pass**

**Scenario 1**
With master, on triggering the purge at step 4 as mentioned https://github.com/longhorn/longhorn/issues/1895#issuecomment-756575857, the Longhorn-manager reported the the failure of the purge and rebuild the failed replica.
```
[longhorn-manager-r2ljs] time="2021-01-15T02:06:05Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-04fd9ebb-fd8b-483a-bb06-b0ab7a800dad\", UID:\"71d16427-2307-47f3-a969-6493640e73eb\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"4727801\", FieldPath:\"\"}): type: 'Warning' reason: 'FailedSnapshotPurge' replica pvc-04fd9ebb-fd8b-483a-bb06-b0ab7a800dad-r-db18fd9d failed the snapshot purge: file sizes are not equal and the parent file is larger than the child file"
```

**Scenario 2**: Trigger a snapshot when a rebuilding is in progress.
The Longhorn-manager reports the error.
```
[longhorn-manager-r2ljs] time="2021-01-15T02:14:19Z" level=error msg="Error in request: fail to purge snapshot: error starting snapshot purge: failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [--url 10.42.3.176:10000 snapshot purge --skip-if-in-progress], output , stderr, time=\"2021-01-15T02:14:19Z\" level=fatal msg=\"Error running purge snapshot command: Failed to purge snapshots: cannot purge snapshots because tcp://10.42.3.177:10000 is rebuilding\"\n, error exit status 1" 
```

**Closed** 2021-01-19 18:06 UTC
Labels: area/engine, area/manager, bug, priority/1, require/manual-test-plan

**Comment by R-Studio** [comment] 2023-07-11 07:23
Same issue here with Longhorn v1.4.2. Any news?

**Comment by innobead** [comment] 2023-07-11 07:33
cc @ejweber @shuo-wu is something related to unexpected volume expansion?

**Comment by shuo-wu** [comment] 2023-07-11 13:20
Probably YES... @R-Studio Have you seen that similar longhorn-manager pod error mentioned in issue https://github.com/longhorn/longhorn/issues/6078?

**Comment by R-Studio** [comment] 2023-07-11 15:14
@shuo-wu no I have similar errors like boknowswiki mentioned

**Comment by ejweber** [comment] 2023-07-11 20:35
I think #6078 have the same cause (inappropriate replica expansion, as suggested by @innobead), but different external factors. In #6078, the engine and all the replicas crashed due to node shutdown. When the engine came back, it was started with one (inappropriately expanded) replica. This caused its engine.status.size = wrong and the particular error in that issue.

If @R-Studio and @wirwolf are seeing "failed to prune" and/or "failed to coalesce" and NOT seeing #6078's "expansion error", your engines probably did not crash (and are still running with the right engine.status.size). You are trying to rebuild a replica from a source replica that has the wrong size. The possibility for a replica to be expanded to the wrong size incorrectly is the underlying issue we are tracking in #6078, so this discussion probably fits well there.

The workaround in #6078 should work in these cases as well. However, it may be possible to proceed without expanding these volumes or restoring from backup assuming we still have one healthy replica that is the right size. We could just delete the incorrectly sized one and allow rebuilds to proceed from the healthy one. The challenge is to determine which replica needs to be deleted.
