### ISSUE TITLE
[FEATURE] Make ImagePullPolicy configurable in engine_image_controller

### ISSUE THREAD

**Issue by davdiv** [longhorn/longhorn#1491] opened 2020-06-14 15:55 UTC
**Is your feature request related to a problem? Please describe.**
I would like to use Longhorn in an air gap installation and I am frustrated to have to use a registry because of `ImagePullPolicy: v1.PullAlways` which is hard-coded in the following file (as mentioned by @yasker in https://github.com/longhorn/longhorn/issues/812#issuecomment-541112471):
https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_image_controller.go#L598
More precisely, I would like to run a registry in the cluster that would be stored on a Longhorn volume, so I would need Longhorn not to depend on a registry to start, because the registry would depend on Longhorn.

**Describe the solution you'd like**
I would like to have a configuration option in the [kubectl yaml installation file](https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml) to remove the hard-coded `ImagePullPolicy` that makes a registry mandatory.

**Describe alternatives you've considered**
When using `ImagePullPolicy: Always`, there does not seem to be any alternative than running a registry.
I can, however, update the `ImagePullPolicy` setting of the engine-image-ei-eee5f438 daemon set after Longhorn is installed, but it would be good to have this option configurable from the beginning.

**Additional context**
I use k3s and I can deploy the required images as documented in https://rancher.com/docs/k3s/latest/en/installation/airgap/.

**Comment by yasker** [comment] 2020-06-23 23:38
There is one thing we need to pay attention to as a developer: if the default ImagePullPolicy for the engine daemonset is `NotPresent`, deleting the engine daemonset will not automatically refresh the default engine image (which is `longhornio/longhorn-engine:master`). It sounds like editing the engine image daemonset during the development process is needed.

**Comment by PhanLe1010** [comment] 2020-06-26 19:39
@yasker, Here is my solution as well as some concerns. Could you please take a look?

# Solution:

# Concern:

**Comment by yasker** [comment] 2020-06-26 21:36
@PhanLe1010 Nice write-up!

Yes, the approach sounds good. We can ask devs to use the script instead if needed.

Regarding the questions:
1. Yes, put it under `dev/scripts` for `longhorn/longhorn`
2. Yes, we should update the guide.
3. Not sure what did you mean. You can always submit PRs.
4. Search for `imagePullPolicy` in the `longhorn/longorn` repo, you can find them in e.g. https://github.com/longhorn/longhorn/blob/master/chart/templates/daemonset-sa.yaml#L20

Regarding the concerns:
1. It's OK for devs to manually update the images again. In fact, regarding updating the image, will update the imagePullPolicy automatically re-pull all the images? When developers start to use the script, I assume that because some images needs to be updated. 
2. I don't think any test will build the image with the same tag. So we should be fine there.

**Comment by PhanLe1010** [comment] 2020-06-26 21:45
Thanks @yasker for the quick response. 
Regrading question #3, I am sorry I made a typo. I mean we need to change this static file file but I do not have permission to change it. It is not inside any repo, so I can not create a PR. https://raw.githubusercontent.com/longhorn/longhorn/master/deploy/longhorn.yaml

**Comment by yasker** [comment] 2020-06-26 21:51
@PhanLe1010 Oh, it's generated automatically by concatenated the yamls in `longhorn-manager/deploy/install`, so you only need to modify that part. The `longhorn.yaml` will be automatically updated during the release.

**Comment by PhanLe1010** [comment] 2020-06-26 21:53
@yasker Awesome! Thank you for the explanation

**Comment by PhanLe1010** [comment] 2020-06-26 23:33
> In fact, regarding updating the image, will update the imagePullPolicy automatically re-pull all the images? When developers start to use the script, I assume that because some images needs to be updated.

@yasker Yes, k8s will kill all existing pods and start new pods with updated images. That is the reason that I put some `sleep 5` and `echo "Warning: Make sure to check and wait for all pods running again!"` in the script. I just retested this behavior.

**Comment by PhanLe1010** [comment] 2020-06-29 07:50
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [x] ~~Is the backend code merged?
The PR is at~~

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: Live upgrade, manager upgrade, Air-Gap installation, Helm installation, Rancher app catalog installation

* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [x] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at ~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [x] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at [here](https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan#change-imagepullpolicy-to-ifnotpresent-test)

**Comment by PhanLe1010** [comment] 2020-06-29 17:48
Reproduce steps:
1. Install Longhorn using any method: Helm chart, Rancher App Catalog, or Air-Gap installation
2. See that Engine Image daemonset, Manager daemonset, UI deployment, Driver Deployer deployment has the field `spec.template.spec.containers.imagePullPolicy` is set to`Always`
3. In Air-Gap installation, Engine Image daemonset will fail to start if there are not a registry to pull image for Engine Image daemonset from

**Comment by meldafrawi** [comment] 2020-07-06 23:46
Validation: **PASSED**

**Closed** 2020-07-06 23:46 UTC
Labels: area/deployment, area/manager, enhancement, highlight, priority/3, require/manual-test-plan
