### ISSUE TITLE
All replicas on same node

### ISSUE THREAD

**Issue by paulmorabito** [longhorn/longhorn#410] opened 2019-02-24 08:39 UTC
Using Longhorn 0.4.0 and Rancher 2.1.6. After taking a node down for maintenance, I am noticing many volumes are reporting this on the web UI:

No node redundancy: all the healthy replicas are running on the same node

Both of my nodes are schedulable and replica count is set to 2. The node that was down for maintenance is the one that doesn't seem to have replicated volumes.

Thanks,

**Comment by yasker** [comment] 2019-02-25 19:51
Yeah, that's due to the node maintenance.

Longhorn would try to maintain the replica counts all the time. So if one node was rebooted, Longhorn would detect an error to that replica, then decide to give up that replica, rebuild one on the available node. If there is only one available node, Longhorn would decide to reuse it (since the other node is down anyway).

That's why in https://github.com/rancher/longhorn/issues/393#issuecomment-465277848 we recommended to scale the replica count down to 1 for the maintenance period.

After the node come back, you can get back healthy node redundancy by: 
1. Increase the volume replica count to node count + 1 (3, in your case)
2. A new replica would be rebuilt for the volume on the other node.
3. Once rebuild was completed, make sure the volume is healthy.
4. Decrease the volume replica count back to 2.
4. Delete one of the replicas on the old node. Now you should have two replicas across two nodes.

**Comment by jocarren** [comment] 2019-07-29 15:06
I have this exact same problem, tried what you suggest but when increasing volume replica count, the new replicas are created on the same node (tried 4 replicas and all of them are created in the same node).

**Comment by yasker** [comment] 2019-07-29 16:58
@jocarren You meant, for example, the node 1 has multiple disks e.g. disk A, B, and disk A is full while disk B is still usable, Longhorn somehow skipped the disk B even it's usable while no other replicas exists on node 1?

**Comment by jocarren** [comment] 2019-07-29 17:01
Exactly.

**Comment by yasker** [comment] 2019-07-29 17:03
@meldafrawi Can you help to reproduce the issue? It sounds like a scheduler bug.

**Comment by jocarren** [comment] 2019-07-29 17:07
Of course, 
What do you need?

**Comment by jocarren** [comment] 2019-07-29 17:08
@yasker can I help? looks like I have the same issue.

**Comment by yasker** [comment] 2019-11-22 20:25
Keep this open.

**Comment by meldafrawi** [comment] 2019-12-03 00:24
I couldn't reproduce the issue.

**Steps (1):**
1. Using Rancher 2.1.6, Created a single node k8s cluster, Install Longhorn v0.4.0
2. Create multiple volumes, attach them to a node till diskA is full.
3. Added a new disk to node-1, kept scheduling Disabled  on that disk
4. add new worker node to the cluster.
5. Enabled scheduling on node-1 new disk
6. Create a new volume.
> Replicas scheduled on both node-1's new disk & node-2 without issues
7. deleted replicas from already created volumes,  
> Replicas re-scheduled on both node-1's new disk & node-2 without issues.
---

**Steps (2):**

1. Using Rancher 2.1.6, Created a 2-node k8s cluster, Install Longhorn v0.4.0
2. Create multiple volumes, attach them to a node.
3. Added a new disk to node-1, kept scheduling Disabled  on that disk
4. Power off node-2,  
> all node-2 replicas scheduled to node-1.
5. Enabled scheduling on node-1 new disk
6. Power on node-2
7. Create a new volume, 
> Replicas scheduled on both node-1 & node-2 disk without issues
8. tried to delete replicas, 
> Replicas scheduled successfully to both nodes.

**Comment by meldafrawi** [comment] 2019-12-03 00:26
@jocarren Can check the reproduce steps, and provide more information on how issue can be reproduced ?

**Comment by meldafrawi** [comment] 2022-01-27 00:01
@jocarren 
Longhorn has evolved a lot since v0.4, will close this issue now.
feel free to report any issue if you encounter another issue.

**Closed by meldafrawi** 2022-01-27 00:01 UTC
Labels: kind/bug, area/manager
