### ISSUE TITLE
[BUG] Longhorn does not delete snapshots

### ISSUE THREAD

**Issue by amir-bialek** [longhorn/longhorn#9747] opened 2024-11-03 07:48 UTC
## Describe the bug

Longhorn does not delete the snapshot of a PVC.
Running k8s on prem, use longhorn v1.7.1 to manage the PVC.
I am trying to delete one of the snapshots:
![image](https://github.com/user-attachments/assets/9144fc0a-0de9-4960-8b36-2715aed16e2c)

Tried via the UI, so it is marked as remove:
![image](https://github.com/user-attachments/assets/4f3b1e5e-0c7b-4f63-8955-64298e7e156f)

Created a snapshot delete and snapshots cleanup job:
![image](https://github.com/user-attachments/assets/8a2d39ef-f65a-4ef0-bf46-cef9a7ea7e7a)

Logs of job:
```
time="2024-11-03T07:41:00Z" level=info msg="Setting allow-recurring-job-while-volume-detached is false" func=app.recurringJob file="recurring_job.go:143"
time="2024-11-03T07:41:00Z" level=info msg="Got volumes from label recurring-job.longhorn.io/c-d6pkjx=enabled" func=app.getVolumesBySelector file="recurring_job.go:927"
time="2024-11-03T07:41:00Z" level=info msg="Found 1 volumes with recurring job c-d6pkjx" func=app.recurringJob file="recurring_job.go:158"
time="2024-11-03T07:41:00Z" level=info msg="Creating job" func=app.startVolumeJob file="recurring_job.go:197" concurrent=1 executionCount=2 groups= job=c-d6pkjx labels="{\"RecurringJob\":\"c-d6pkjx\"}" parameters="map[]" retain=0 task=snapshot-cleanup volume=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:41:00Z" level=info msg="job starts running" func="app.(*Job).run" file="recurring_job.go:310" executionCount=2 labels="map[RecurringJob:c-d6pkjx]" namespace=longhorn-system retain=0 snapshotName=c-d6pkjx-489c615c-9623-474c-8863-9b60634d1abb task=snapshot-cleanup volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:41:00Z" level=info msg="Running recurring snapshot for volume pvc-6add4708-e1cd-4449-9016-77fe488beda0" func="app.(*Job).run" file="recurring_job.go:345" executionCount=2 labels="map[RecurringJob:c-d6pkjx]" namespace=longhorn-system retain=0 snapshotName=c-d6pkjx-489c615c-9623-474c-8863-9b60634d1abb task=snapshot-cleanup volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:41:05Z" level=info msg="Purged snapshots" func="app.(*Job).purgeSnapshots" file="recurring_job.go:540" executionCount=2 labels="map[RecurringJob:c-d6pkjx]" namespace=longhorn-system retain=0 snapshotName=c-d6pkjx-489c615c-9623-474c-8863-9b60634d1abb task=snapshot-cleanup volume=pvc-6add4708-e1cd-4449-9016-77fe488beda0 volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:41:05Z" level=info msg="Finished recurring snapshot" func="app.(*Job).doRecurringSnapshot.func1" file="recurring_job.go:354" executionCount=2 labels="map[RecurringJob:c-d6pkjx]" namespace=longhorn-system retain=0 snapshotName=c-d6pkjx-489c615c-9623-474c-8863-9b60634d1abb task=snapshot-cleanup volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:41:05Z" level=info msg="Created job" func=app.startVolumeJob file="recurring_job.go:220" concurrent=1 executionCount=2 groups= job=c-d6pkjx labels="{\"RecurringJob\":\"c-d6pkjx\"}" parameters="map[]" retain=0 task=snapshot-cleanup volume=pvc-6add4708-e1cd-4449-9016-77fe488beda0

```
and
```
time="2024-11-03T07:38:00Z" level=info msg="Setting allow-recurring-job-while-volume-detached is false" func=app.recurringJob file="recurring_job.go:143"
time="2024-11-03T07:38:00Z" level=info msg="Got volumes from label recurring-job.longhorn.io/c-y09g1n=enabled" func=app.getVolumesBySelector file="recurring_job.go:927"
time="2024-11-03T07:38:00Z" level=info msg="Found 1 volumes with recurring job c-y09g1n" func=app.recurringJob file="recurring_job.go:158"
time="2024-11-03T07:38:00Z" level=info msg="Creating job" func=app.startVolumeJob file="recurring_job.go:197" concurrent=2 executionCount=13 groups= job=c-y09g1n labels="{\"RecurringJob\":\"c-y09g1n\"}" parameters="map[]" retain=0 task=snapshot-delete volume=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:38:00Z" level=info msg="job starts running" func="app.(*Job).run" file="recurring_job.go:310" executionCount=13 labels="map[RecurringJob:c-y09g1n]" namespace=longhorn-system retain=0 snapshotName=c-y09g1n-caba70dc-d876-4cab-9b77-cf645f46f804 task=snapshot-delete volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:38:00Z" level=info msg="Running recurring snapshot for volume pvc-6add4708-e1cd-4449-9016-77fe488beda0" func="app.(*Job).run" file="recurring_job.go:345" executionCount=13 labels="map[RecurringJob:c-y09g1n]" namespace=longhorn-system retain=0 snapshotName=c-y09g1n-caba70dc-d876-4cab-9b77-cf645f46f804 task=snapshot-delete volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:38:00Z" level=info msg="Cleaned up snapshot CR f24ea9e0-6844-4fef-93ec-5f88d7d5f442 for pvc-6add4708-e1cd-4449-9016-77fe488beda0" func="app.(*Job).doSnapshotCleanup" file="recurring_job.go:476" executionCount=13 labels="map[RecurringJob:c-y09g1n]" namespace=longhorn-system retain=0 snapshotName=c-y09g1n-caba70dc-d876-4cab-9b77-cf645f46f804 task=snapshot-delete volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:38:00Z" level=info msg="Finished recurring snapshot" func="app.(*Job).doRecurringSnapshot.func1" file="recurring_job.go:354" executionCount=13 labels="map[RecurringJob:c-y09g1n]" namespace=longhorn-system retain=0 snapshotName=c-y09g1n-caba70dc-d876-4cab-9b77-cf645f46f804 task=snapshot-delete volumeName=pvc-6add4708-e1cd-4449-9016-77fe488beda0
time="2024-11-03T07:38:00Z" level=info msg="Created job" func=app.startVolumeJob file="recurring_job.go:220" concurrent=2 executionCount=13 groups= job=c-y09g1n labels="{\"RecurringJob\":\"c-y09g1n\"}" parameters="map[]" retain=0 task=snapshot-delete volume=pvc-6add4708-e1cd-4449-9016-77fe488beda0

```

However snapshot remains.

## To Reproduce

Tried the same steps for different snapshots, in different k8s, same issue.

## Expected behavior

Longhorn should delete the snapshot

**Comment by derekbit** [comment] 2024-11-03 11:34
This is expected behavior. The parent of the volume-head is unable to be deleted because it stores immutable data. What Longhorn does is only marked it as deleted.

**Closed** 2024-11-03 11:35 UTC
Labels: kind/bug, invalid, area/snapshot, require/qa-review-coverage, require/backport

**Comment by amir-bialek** [comment] 2024-11-04 07:22
Hey @derekbit , can you share more info or reference to the documentation?
I do not understand why would the data be immutable, why would longhorn mark it as deleted, and why it created the snapshot to begin with..

**Comment by derekbit** [comment] 2024-11-04 07:52
> I do not understand why would the data be immutable

It is a snapshot file, so the data in the file is immutable.

Assume there is a snapshot chain
```
snap3->snap2->snap1->volume-head
```
While deleting `snap2`, Longhorn will merge `snap2` and `snap1`, and then delete `snap2`.

If you delete `snap1`, Longhorn only marks it as deleted.

**Comment by amir-bialek** [comment] 2024-11-04 09:20
Is there a way to allod snapshot 1 to be deleted? 
Setting retention for 0 or something?

**Comment by derekbit** [comment] 2024-11-04 10:16
> Is there a way to allow snapshot 1 to be deleted? Setting retention for 0 or something?

No.

**Comment by derekbit** [comment] 2024-11-04 10:29
@amir-bialek 
Can you try https://longhorn.io/docs/1.7.2/references/settings/#remove-snapshots-during-filesystem-trim?
