### ISSUE TITLE
[IMPROVEMENT] Pre-pull images (share-manager image and instance-manager image) on each Longhorn node

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#8376] opened 2024-04-17 02:46 UTC
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Pre-pull on each Longhorn node 
- share-manager image for speeding up RWX volume failover
- instance-manager image 
## Additional context

https://suse.slack.com/archives/C02DR3N5T24/p1713318153020089?thread_ts=1713265309.479039&cid=C02DR3N5T24

**Comment by derekbit** [comment] 2024-04-17 02:46
cc @james-munson

**Comment by derekbit** [comment] 2024-04-17 08:07
Do we need a CRD for share-manager image like `engineImage`?
Further, we can generalize the `engineImage` CRD to `image` CRD that can manage the pre-pull images.

**Comment by shuo-wu** [comment] 2024-04-17 17:33
> Further, we can generalize the engineImage CRD to image CRD that can manage the pre-pull images.

Agree with this. We can launch a general image-pull daemonset for engine, instance-manager, and share-manager.

**Comment by ejweber** [comment] 2024-07-01 19:20
I was filing this as a bug, but we can probably just handle it here since the issue isn't closed yet:

## Describe the bug

After https://github.com/longhorn/longhorn/pull/8778 merged, there are now two containers in the longhorn-manager DaemonSet spec instead of one. This always causes the longhorn-post-upgrade job to fail.

## To Reproduce

1. `helm install -n longhorn-system longhorn ./chart`
2. `helm upgrade -n longhorn-system longhorn ./chart`

## Expected behavior

The Helm upgrade completes successfully.

## Additional context

```
eweber@laptop:~/longhorn> kl logs longhorn-post-upgrade-n67xg
warning: GOCOVERDIR not set, no coverage data emitted
time="2024-07-01T19:12:30Z" level=info msg="Running post-upgrade..." func=main.main.PostUpgradeCmd.func6 file="post_upgrade.go:41"
W0701 19:12:30.507888       1 client_config.go:659] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
time="2024-07-01T19:12:30Z" level=warning msg="found 2 containers in manager spec" func="app.(*postUpgrader).waitManagerUpgradeComplete" file="post_upgrade.go:99"
time="2024-07-01T19:12:30Z" level=warning msg="found 2 containers in manager spec" func="app.(*postUpgrader).waitManagerUpgradeComplete" file="post_upgrade.go:99"
time="2024-07-01T19:12:30Z" level=warning msg="found 2 containers in manager spec" func="app.(*postUpgrader).waitManagerUpgradeComplete" file="post_upgrade.go:99"
...
```

```
eweber@laptop:~/longhorn> helm upgrade -n longhorn-system longhorn ./chart
Error: UPGRADE FAILED: post-upgrade hooks failed: 1 error occurred:
        * job longhorn-post-upgrade failed: BackoffLimitExceeded
```

Probably this is a super easy fix [here](https://github.com/longhorn/longhorn-manager/blob/4647dce47feedc1f5420dbd210db4e7badf20c53/app/post_upgrade.go#L98-L101), but I think it makes sense to have @mantissahz implement and check it as an extension of https://github.com/longhorn/longhorn/issues/8376.

**Comment by derekbit** [comment] 2024-07-01 23:22
cc @mantissahz 👆

**Comment by PhanLe1010** [comment] 2024-07-03 01:35
> Looks like @PhanLe1010 took care of it in [longhorn/longhorn-manager#2938](https://github.com/longhorn/longhorn-manager/pull/2938).

Oh. Didn't notice that it is already discussed here when I created that PR for the ticket https://github.com/longhorn/longhorn/issues/8866 .

Btw, I swear that I did not cheat by reading the your comment here @ejweber :))))

**Comment by mantissahz** [comment] 2024-07-04 02:14
Thank you @PhanLe1010 for the quick fix.

**Comment by chriscchien** [comment] 2024-07-04 04:32
Verified **pass** on longhorn master(longhorn `c3e1f6`)

Steps
1. Fresh install Longhorn master by kubectl
2. Observed share manager images pulled on all nodes
```bash
> crictl images | grep share-manager
docker.io/longhornio/longhorn-share-manager      master-head         d552788913fe5       92.1MB
```
3. Uninstall Longhorn master and use `crictl` to delete all Longhohrn images
4. Upgrade Longhorn from v1.6.2 to master
5. After upgrade complete, observed share manager images pulled on all nodes just like step2
6. Perform step1 ~ stpe5 by helm, did not encounter any problems
7. [test_rwx](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/7148/) all passed

**Closed by chriscchien** 2024-07-04 04:32 UTC
Labels: priority/0, require/doc, require/lep, require/manual-test-plan, area/volume-rwx, area/performance, kind/improvement, component/longhorn-share-manager, require/backport

**Comment by derekbit** [comment] 2024-10-17 12:38
> Hello! When will this be in helm release longhorn?

It is already in v1.7.0.
