### ISSUE TITLE
Change multiple volumes backup schedule - UI

### ISSUE THREAD

**Issue by ainiml** [longhorn/longhorn#946] opened 2019-12-07 09:37 UTC
Something about individually doing things is breaking the user experience. Our production server has 680 Volumes. 

Porting 680 Volumes into Longhorn, and then needing to individually schedule 680 backups is daunting.

Or maybe an option to create a schedule for multiple selections:

![Screenshot from 2019-12-07 04-33-54](https://user-images.githubusercontent.com/28725423/70372292-2821cf00-18ab-11ea-9816-fe9facfa3fc6.png)

**Comment by yasker** [comment] 2019-12-09 19:31
The default recurring schedule part is a duplicate of #467 . Multi-choice one is a new feature request.

**Comment by meldafrawi** [comment] 2020-01-21 21:09
Validation: **Partially Failed**

Longhorn ui version: `longhornio/longhorn-ui:master`

**Steps to test:**
- Create multiple volumes, attach them to nodes
- For one of the volumes volume-1, In Volume details page, create a Snapshot/Backup schedule.
- In Volume page, select multiple volumes including volume-1
- Click Update Schedule , Create snapshot schedule, Click `Save`
- A confirmation message should appear state that `Updated schedule will override any existing schedule`
  - Click `OK` New schedule should be created for selected volumes. **(PASS)**
  - Press `Enter` button on keyboard, New schedule should be created for selected volumes. **(FAILED)** #942 
   > multiple Confirmation messages kept appearing every time Enter key is pressed.

**Comment by meldafrawi** [comment] 2020-01-22 21:02
Validation: **Partially Failed**

Longhorn ui version: `wangsiye/longhorn-ui:39737a6`

**Steps to test:**
- Create multiple volumes, attach them to nodes
- For one of the volumes `volume-1`, In Volume details page, create a Snapshot/Backup schedule.
- In Volume page, select multiple volumes including `volume-1`
- Click Update Schedule, In `Bulk Update Recurring Snapshot and Backup` Modal, Click `New`
- Click to on schedule to edit Cron, Edit cron and Click `Enter`
- Cron modal should disappear and Cron should be set to `Schedule` column in `Bulk Update Recurring Snapshot and Backup` modal **(FAILED)**

> **Confirmation modal appear on top of cron modal** 
![image](https://user-images.githubusercontent.com/18232258/72933510-84ad5080-3d6a-11ea-88d7-2de833f38d83.png)

**Comment by meldafrawi** [comment] 2020-01-23 17:25
Validation: **PASSED**

Longhorn UI version: `wangsiye/longhorn-ui:4eb7843`

**Closed** 2020-01-23 19:33 UTC
Labels: area/ui, enhancement
