### ISSUE TITLE
[Question] MountVolume.SetUp failed  -  There is no block device frontend 

### ISSUE THREAD

**Issue by rsoika** [longhorn/longhorn#1712] opened 2020-08-23 16:37 UTC
I am running longhorn 1.0.2 in a self managed kubernetes cluster
Everything works fine. 
But I observer the following warning when I launch a new POD (in this case a postgresdb)

    MountVolume.SetUp failed for volume "xxx : rpc error: code = InvalidArgument desc = There is no block device frontend for volume xxx

These are the events form the pod description after successful deployment:

```
 Events:                                                                                                                                                                   │
│   Type     Reason                  Age                  From                      Message                                                                                 │
│   ----     ------                  ----                 ----                      -------                                                                                 │
│   Warning  FailedScheduling        <unknown>            default-scheduler         persistentvolumeclaim "dbdata" not found                                                │
│   Warning  FailedScheduling        <unknown>            default-scheduler         persistentvolumeclaim "dbdata" not found                                                │
│   Warning  FailedScheduling        <unknown>            default-scheduler         running "VolumeBinding" filter plugin for pod "postgres-6f8fc59cd8-p5p4g": pod has unbound immediate PersistentVolumeClaims                                                                                                                                      │
│   Normal   Scheduled               <unknown>            default-scheduler         Successfully assigned documents-imixs-com/postgres-6f8fc59cd8-p5p4g to ixchel-worker-2  │
│   Normal   SuccessfulAttachVolume  4m11s                attachdetach-controller   AttachVolume.Attach succeeded for volume "documents-imixs-com-dbdata"                   │
│   Warning  FailedMount             4m6s (x2 over 4m7s)  kubelet, ixchel-worker-2  MountVolume.SetUp failed for volume "documents-imixs-com-dbdata" : rpc error: code = InvalidArgument desc = There is no block device frontend for volume documents-imixs-com-dbdata                                                                              │
│   Normal   Pulled                  4m4s                 kubelet, ixchel-worker-2  Container image "postgres:9.6.1" already present on machine                             │
│   Normal   Created                 4m4s                 kubelet, ixchel-worker-2  Created container postgres                                                              │
│   Normal   Started                 4m4s                 kubelet, ixchel-worker-2  Started container postgres   
```     

My PVC/PV configuation looks like this:

```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: documents-imixs-com-dbdata
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: documents-imixs-com
    name: dbdata
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: xxx
  storageClassName: longhorn-durable

----
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-durable
  resources:
    requests:
      storage: 2Gi
  volumeName: "xxx"
```

Is this warning something I should be concerned of or can I still ignore this warning?

Thanks for Help

===
Ralph

**Comment by shuo-wu** [comment] 2020-08-24 02:59
No, this error message is misleading... It's actually a transient/intermediate error during the attachment, and Kubernetes/Longhorn will try it when the error happens.

**Comment by rsoika** [comment] 2020-08-24 06:46
ok, thanks for clarifying.

**Comment by yasker** [comment] 2020-08-25 03:40
The error message issue has been reported multiple times. Let's use this issue to track the fix for the error message.

**Comment by yasker** [comment] 2020-10-02 00:49
We can change the error message for the volume is not attached to `the volume %v hasn't been attached yet`. Keep the error message for other conditions to `there is no block device frontend xxx`.

**Comment by yasker** [comment] 2020-10-04 03:01
Also, we need to check why FailedMount was reported, since in the previous step it's already said the attachment is successful.

**Comment by boknowswiki** [comment] 2020-10-26 23:13
At beginning I failed to reproduce this issue with creating a pod. Thanks @khushboo-rancher for pointing out it's easier to reproduce it with deployment.
The reason we see `FailedMount` after attachment succeed is because in the [ControlPublishVolume](https://github.com/longhorn/longhorn-manager/blob/39eb345604ec391e8c6f5025321ebf19debcc8e7/csi/controller_server.go#L272) we don't check the endpoint, but in `NodePublishVolume` we check [the endpoint](https://github.com/longhorn/longhorn-manager/blob/39eb345604ec391e8c6f5025321ebf19debcc8e7/csi/node_server.go#L61) .

**Comment by boknowswiki** [comment] 2020-10-26 23:40
Put a test deploy yaml:
```
kind: PersistentVolume
apiVersion: v1
metadata:
  name: existing
spec:
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  claimRef:
    namespace: default
    name: dbdata
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: existing
  storageClassName: longhorn

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dbdata
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi
  volumeName: "existing"

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: volume-pv-test
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: volume-pv-test
        image: nginx:stable-alpine
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
              - ls
              - /data/lost+found
          initialDelaySeconds: 5
          periodSeconds: 5
        volumeMounts:
        - name: vol 
          mountPath: /data
        ports:
        - containerPort: 80
      volumes:
      - name: vol 
        persistentVolumeClaim:
          claimName: dbdata
```

**Comment by khushboo-rancher** [comment] 2020-10-29 19:11
Verified with longhorn-master - 10/29/2020

Validation - **Pass**

No failed ```FailedScheduling``` is seen after the successful attachment. 
```
Events:
  Type    Reason                  Age        From                           Message
  ----    ------                  ----       ----                           -------
  Normal  Scheduled               <unknown>  default-scheduler              Successfully assigned default/wk-5-0 to khushboo-test-lh-wk1
  Normal  SuccessfulAttachVolume  2m1s       attachdetach-controller        AttachVolume.Attach succeeded for volume "volume-5"
  Normal  Pulling                 113s       kubelet, khushboo-test-lh-wk1  Pulling image "ubuntu:xenial"
  Normal  Pulled                  113s       kubelet, khushboo-test-lh-wk1  Successfully pulled image "ubuntu:xenial"
  Normal  Created                 113s       kubelet, khushboo-test-lh-wk1  Created container wk-5
  Normal  Started                 113s       kubelet, khushboo-test-lh-wk1  Started container wk-5
```

**Comment by shuo-wu** [comment] 2020-10-30 13:10
The modification leads to a bug:
The volume can not be used by a pod after the CSI expansion complete.

And it leads to the related integration tests failed, e.g.,
test_csi_offline_expansion
test_csi_expansion_with_replica_failure

The fix of this bug: https://github.com/longhorn/longhorn-manager/pull/752

**Comment by khushboo-rancher** [comment] 2020-11-04 22:26
Verified with longhorn-master - 11/04/2020 after https://github.com/longhorn/longhorn-manager/pull/752 got merged.

Validation - **Pass**

No failed FailedScheduling is seen after the successful attachment.

**Closed by khushboo-rancher** 2020-11-04 22:26 UTC
Labels: area/driver, bug, priority/2

**Comment by venomone** [comment] 2020-11-07 18:15
Hey, im new to rancher and longhorn, can smb say me how to get this fix inside of my deployment?!

**Comment by khushboo-rancher** [comment] 2020-11-08 05:12
@venomone The fix will be available on Longhorn v1.1.0 which is planned to be released soon. Currently, the fix is only available with the Longhorn master image. 
We recommend to use the released version v1.1.0 once available and upgrade your Longhorn to v1.1.0 to get this fix and other cool features.

**Comment by venomone** [comment] 2020-11-08 17:21
Can you please be so nice and give me a quick hint on how to do a upgrade to the latest available version. I already tried this myself by editing the longhorn deployment yaml to use the images with the master tags from dockerhub but my deployment wont come up. I already redeployed my whole k8s with no success

**Comment by rsoika** [comment] 2020-11-09 08:05
Maybe our install guide from the [imixs-cloud project](https://github.com/imixs/imixs-cloud/blob/master/doc/LONGHORN.md) can help you. It is nealy the same as in longhorn docs but maybe you can find some hint to solve your issue there.

**Comment by yasker** [comment] 2020-11-09 17:47
@venomone This issue is not a blocker and shouldn't affect the functionality of Longhorn. It should succeed eventually. If the mount operation cannot succeed in the end, then there is something else in play there.
