### ISSUE TITLE
performance degradation after 60 volumes

### ISSUE THREAD

**Issue by marcomezzaro** [longhorn/longhorn#1054] opened 2020-02-14 15:02 UTC
Hi all,
I'm testing different solution of kubernetes storage and I came across Longhorn. 
In order to do some stress test I created 100 deployments with replica 1 and nginx with one volume attached.
After 55-60 volumes, longhorn system hung and the api became really slow. 
Pod creation went in timeout due to missing volume.
At 100 volumes the system became completely unusable.

current hardware setup:
3 nodes Kubernetes cluster on Centos 7, one master, two worker, tainting disabled on 3 HP DL380 G10, 64 core, 512 GB RAM, 20Gb ethernet between nodes. 2 disks pool 5TB

The operating system was pretty in idle. Longhorn-manager Pods had 30% cpu load (docker stats)

There are some limitations I need to know or some tweaks need to be applied on order to resolve this situation?

I've downloaded the support bundle in case of need.

thank you for your help.

**Comment by yasker** [comment] 2020-02-14 19:32
@marcomezzaro Thanks for the reporting. And it's really nice you've saved the support bundle. Can you send the support bundle to longhorn-support-bundle@rancher.com ? We will take a look. I have some suspects in mind. 

Also, anything else other than Longhorn manager taking a large amount of CPU?

**Comment by yasker** [comment] 2020-02-15 23:58
Mark as a duplicate of https://github.com/longhorn/longhorn/issues/1058 . It will be fixed in upcoming v0.8.0 release.

**Closed by yasker** 2020-02-15 23:58 UTC
Labels: area/manager, enhancement
