### ISSUE TITLE
[REFACTOR] Shrink Longhorn container image

### ISSUE THREAD

**Issue by w13915984028** [longhorn/longhorn#7072] opened 2023-11-09 11:14 UTC
## Is your improvement request related to a feature? Please describe

Some Longhorn container images are fairly big.

```
harv41:~ # crictl image ls | grep "longhorn"

docker.io/longhornio/backing-image-manager                                  v1.4.3                                     db916c3638c1c       353MB
docker.io/longhornio/csi-attacher                                           v3.4.0                                     03e115718d258       56.2MB
docker.io/longhornio/csi-node-driver-registrar                              v2.5.0                                     cb03930a2bd42       20.9MB
docker.io/longhornio/csi-provisioner                                        v2.1.2                                     0f0a0f7990768       52.9MB
docker.io/longhornio/csi-resizer                                            v1.3.0                                     1df30f0e25552       55.4MB
docker.io/longhornio/csi-snapshotter                                        v5.0.1                                     53ae5b88a3380       56.5MB
docker.io/longhornio/livenessprobe                                          v2.8.0                                     e899260153aed       19.6MB
docker.io/longhornio/longhorn-engine                                        v1.4.3                                     97b06aa073605       749MB  // note
docker.io/longhornio/longhorn-instance-manager                              v1.4.3                                     58e18670be17a       751MB  // note
docker.io/longhornio/longhorn-manager                                       v1.4.3                                     f70f099c6183f       282MB
docker.io/longhornio/longhorn-share-manager                                 v1.4.3                                     4e4f3ddc7424c       202MB
docker.io/longhornio/longhorn-ui                                            v1.4.3                                     16f0d1cc414ba       209MB
docker.io/longhornio/support-bundle-kit                                     v0.0.25                                    53f2d6ac20fa1       415MB
```

For example, the instance manager container image has `make, gcc`

```
harv41:~ # kk exec -i -t -n longhorn-system instance-manager-e-ee7f9a38f72f904d35a052dde1f403e4 -- /bin/sh

sh-4.4# make --help
Usage: make [options] [target] ...
Options:
  -b, -m                      Ignored for compatibility.
  -B, --always-make           Unconditionally make all targets.

sh-4.4# gcc  --help
Usage: gcc [options] file...
Options:

sh-4.4# which gcc
/usr/bin/gcc

sh-4.4# which make
/usr/bin/make
```

From the instance manager docker file, it has such blocks:

https://github.com/longhorn/longhorn-engine/blob/8d6d46b7a70cd882213ca2f4debec70f300e66e7/package/Dockerfile#L22C1-L36C17

```
# Build liblonghorn
...
# Build TGT
```

The final docker image is a mixture of building environment and running process.

## Describe the solution you'd like

Decouple the building and running, shrink the published container image size.

**Comment by derekbit** [comment] 2023-11-09 11:53
It will be handled in https://github.com/longhorn/longhorn/issues/5911 and optimized by the multi-statged build like https://github.com/longhorn/longhorn-instance-manager/commit/1158c45467d94dde9d29cff5a887c2704d88e3f9.

cc @ChanYiLin

**Comment by w13915984028** [comment] 2023-11-09 13:39
@derekbit Thanks, good to know this is on track. Your commit https://github.com/longhorn/longhorn-instance-manager/commit/1158c45467d94dde9d29cff5a887c2704d88e3f9. has been standing for some days. Hopefully it can be merged soon.

Harvester is more sensitive to Container image size.

cc @bk201 @markhillgit

**Comment by derekbit** [comment] 2023-11-09 13:44
@w13915984028 
https://github.com/longhorn/longhorn-instance-manager/commit/1158c45467d94dde9d29cff5a887c2704d88e3f9 is merged. I mean all components can be optimized like it.  :)

**Comment by derekbit** [comment] 2023-11-09 15:31
> are they also backported? 

It only stays in Longhorn v1.5+

**Comment by ejweber** [comment] 2023-11-29 22:44
Closing as a duplicate of https://github.com/longhorn/longhorn/issues/5911.

**Closed by ejweber** 2023-11-29 22:44 UTC
Labels: kind/refactoring, duplicated
