### ISSUE TITLE
[BUG] Fresh Single Node longhorn Install Not able to attach pod volume

### ISSUE THREAD

**Issue by vineetsingh5** [longhorn/longhorn#2244] opened 2021-02-08 11:47 UTC
**Describe the bug**
I have created a single node RKE2 cluster on bare metal Azure VM's. I have attached 512Gb SSD and partition disk using command. 
`mkfs -t ext4 /dev/sdc`
`mkdir -p /mnt/sdc`
`mount /dev/sdc /mnt/sdc`

I have also installed longhorn required dependencies **open-iscsi** and verified the setup via the script available in the document.

I am testing my setup using the example `kubectl create -f https://raw.githubusercontent.com/longhorn/longhorn/v1.0.0/examples/pod_with_pvc.yaml` but pod pvc stuck in Detaching mode. 

<img width="1672" alt="Screenshot 2021-02-08 at 4 58 01 PM" src="https://user-images.githubusercontent.com/42463267/107214034-4ba45480-6a2f-11eb-94b2-937180f4055a.png">

**To Reproduce**
3. Perform '....'

**Expected behavior**
PVC should get attached to the pod

**Log**
Longhorn managers' log 
[longhorn-manager-log.txt](https://github.com/longhorn/longhorn/files/5943433/longhorn-manager-log.txt)

*Support Bundle* 
[longhorn-support-bundle_f92c58fa-8374-4ed9-8327-b772d11965b4_2021-02-08T11-44-01Z.zip](https://github.com/longhorn/longhorn/files/5943441/longhorn-support-bundle_f92c58fa-8374-4ed9-8327-b772d11965b4_2021-02-08T11-44-01Z.zip)

**Environment:**
 - Longhorn version: 1.1.1
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE2
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 0
 - Node config
   - OS type and version: RHEL 8.2
   - CPU per node: 8
   - Memory per node: 32
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: NA
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Azure VM's

**Comment by joshimoo** [comment] 2021-02-08 14:40
Looking at the logs, there is a communication problem between the manager and the instance-managers.
@shuo-wu any idea what could be causing this, and how to recover from this state? `failed to get version` 
```
2021-02-08T11:38:13.398964180Z time="2021-02-08T11:38:13Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-r-e5f217c8: fail to sync instance manager for longhorn-system/instance-manager-r-e5f217c8: failed to get version: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.0.13:8500: i/o timeout\""

2021-02-08T11:38:13.888753587Z time="2021-02-08T11:38:13Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-e-0ac582d6: fail to sync instance manager for longhorn-system/instance-manager-e-0ac582d6: failed to get version: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.0.12:8500: i/o timeout\""
```

**Comment by shuo-wu** [comment] 2021-02-09 03:14
There may be something wrong with your network/firewall settings. Can you try to ping the instance manager pods manually inside the longhorn manager pods and see if the communication is fine?

BTW, there is one related issue with RHEL8 + RKE:
https://github.com/rancher/rke/issues/2432

**Comment by gdznela** [comment] 2021-02-23 18:12
I had same issue with RHEL8 + RKE (k8s 1.19.7 + calico 3.16.5) + Longhorn(same error message in longhorn manager logs).
Disabling firewalld helped.

**Comment by cclhsu** [comment] 2021-03-12 12:27
> Looking at the logs, there is a communication problem between the manager and the instance-managers.
> @shuo-wu any idea what could be causing this, and how to recover from this state? `failed to get version`
> 
> ```
> 2021-02-08T11:38:13.398964180Z time="2021-02-08T11:38:13Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-r-e5f217c8: fail to sync instance manager for longhorn-system/instance-manager-r-e5f217c8: failed to get version: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.0.13:8500: i/o timeout\""
> 
> 2021-02-08T11:38:13.888753587Z time="2021-02-08T11:38:13Z" level=warning msg="Error syncing Longhorn instance manager longhorn-system/instance-manager-e-0ac582d6: fail to sync instance manager for longhorn-system/instance-manager-e-0ac582d6: failed to get version: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = \"transport: Error while dialing dial tcp 10.42.0.12:8500: i/o timeout\""
> ```

After some testing, a working cluster starts to have these errors appearing after turn on `firewalld`, and cannot communicate with other node.

**Comment by cclhsu** [comment] 2021-03-18 07:33
@vineetsingh5 Are you able to resolve the issue by turning off the `firewalld`?

**Comment by shuo-wu** [comment] 2021-04-27 01:49
Close this issue since there is no update for a long time. Feel free to reopen it if the issue is reproduced or you have anything new for sharing and debugging.

**Closed by shuo-wu** 2021-04-27 01:49 UTC
Labels: kind/question
