### ISSUE TITLE
[BUG] Scaling down the replica count should delete the extra unscheduled replica

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1638] opened 2020-07-27 21:40 UTC
**Describe the bug**
The unscheduled replica should be deleted if the user scales down the replica count and there are more replicas present than the replica count. No healthy or failed replicas should get deleted.

**To Reproduce**
1. Create a volume with 3 replicas in a 3 worker node set up. and attach it to a node.
2. Go to the volume detail page and increase the replica count by 1.
3. The new replica becomes unschedulable and volume becomes degraded.
4. Reduce the replica count by 1.
5. The unscheduled replica doesn't get deleted and volume still shows unschedulable.

**Expected behavior**
The unscheduled replica should get deleted.
No healthy or failed replicas should get deleted.

**Environment:**
 - Longhorn version: v1.0.1
 - Kubernetes version: 18.6 
 - Node OS type and version: Ubuntu 18.04

**Comment by yasker** [comment] 2020-10-01 18:32
Duplicate of https://github.com/longhorn/longhorn/issues/1679

**Closed by yasker** 2020-10-01 18:32 UTC
Labels: area/manager, enhancement, priority/3, require/automation-e2e
