### ISSUE TITLE
[BUG] Nightly Test: Salvage related tests failed

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1926] opened 2020-10-29 12:17 UTC
**Describe the bug**
The following tests should be modified after the implementation of #1719 .

test_salvage_auto_crash_all_replicas
test_salvage_auto_crash_replicas_short_wait
test_salvage_auto_crash_replicas_long_wait

The remount handling method is changed, the function `wait_pod_for_auto_salvage` in the integration test should be updated, too.

**Expected behavior**
The tests should get passed.

**Log**
Found this log after all replica crash:
```
[longhorn-manager-55wpp] time="2020-10-29T12:05:27Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"longhorn-testvol-bwuqqb\", UID:\"eff46b3b-66dc-4344-acbc-c0989ea50459\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"4853087\", FieldPath:\"\"}): type: 'Warning' reason: 'AutoSalvaged' Replica longhorn-testvol-bwuqqb-r-4cb7f47b of volume longhorn-testvol-bwuqqb will be automatically salvaged"
[longhorn-manager-55wpp] time="2020-10-29T12:05:27Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"longhorn-testvol-bwuqqb\", UID:\"eff46b3b-66dc-4344-acbc-c0989ea50459\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"4853087\", FieldPath:\"\"}): type: 'Normal' reason: 'Remount' Volume longhorn-testvol-bwuqqb requested remount at 2020-10-29T12:05:27Z"
```

But the logs in `handlePodDeletionIfVolumeRequestRemount()` is not found
```
kc.logger.Infof("Deleted pod %v so that Kubernetes will handle remounting volume %v", pod.GetName(), vol.GetName())
```

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.18
 - Node OS type and version: Ubuntu 18.04

**Additional context**

**Comment by khushboo-rancher** [comment] 2020-10-29 16:48
This could be a duplicate of https://github.com/longhorn/longhorn/issues/1914

**Comment by yasker** [comment] 2020-10-29 23:18
Duplicate of #1914.

**Closed by yasker** 2020-10-29 23:18 UTC
Labels: area/test, bug, reproduce/always
