### ISSUE TITLE
[FEATURE] Online Volume Expansion

### ISSUE THREAD

**Issue by dbpolito** [longhorn/longhorn#2314] opened 2021-03-09 17:23 UTC
Currently we can only expand a volume if it's `detached`, is there any plan for supporting `Online Volume Expansion`?

Maybe not really online but allowing to do it and restarting the pod as it currently does with `Automatically Delete Workload Pod when The Volume Is Detached Unexpectedly`.

My use case is that i deploy things using helm charts like wordpress which uses longhorn as persistent volume and i want to increase the disk size...

Even with recreate strategy it doesn't work.

I have a workaround which is scaling down all deployments before running helm upgrade but would be good to have a better UX for this as i think it should be a common use case.

**Comment by joshimoo** [comment] 2021-03-10 08:37
Thanks for opening this enhancement, we currently do not support online expansion.
cc @yasker @innobead there are some technical difficulties for  adding online expansion support @shuo-wu will leave some dev notes on what he encounted prevoiusly in this regard.

**Comment by mfbrj** [comment] 2021-03-12 05:02
Could item 2 be mitigated by a snapshot revert done by the user?

 So, Longhorn could do an automatic snapshot before the expansion, and delete de snapshot after a successful expansion

**Comment by shuo-wu** [comment] 2021-03-17 09:19
> Could item 2 be mitigated by a snapshot revert done by the user?

Snapshot revert is different from the expansion cancelling. And Yes, a snapshot will be created before expansion or backup.

**Comment by yasker** [comment] 2021-03-22 16:11
@dbpolito @mfbrj 

Thanks for reporting. We will close this one as a duplicate of https://github.com/longhorn/longhorn/issues/1674 .

Feel free to continue the discussion there.

**Closed by yasker** 2021-03-22 16:11 UTC
Labels: kind/enhancement
