### ISSUE TITLE
[BUG] Backups are not getting deleted even after crossing retain count.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1267] opened 2020-04-28 19:26 UTC
**Describe the bug**
Retain count is not getting applied to backups. Older backups are not getting deleted when backup counts are exceeding the count of retain.

**To Reproduce**
1. Create a volume(3 replicas, 3 nodes), attach to a pod
2. Write data to volume. Take a snapshot s1.
3. Enable recurring backup with retain count 10.
4. After system takes 5 backups, **revert to s1**.
5. Recurring backups will start to be taken from s1 similar as shown in below screenshot.
6. Backups taken before reverting to s1 would not get deleted even the count of recursive backups exceeds the retain count.

**Expected behavior**
Backups up to retain count should only be retained.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.17.5
 - Node OS type and version: ubuntu, aws node

**Additional context**
Also, the editing of retain count is not getting applied to backup retain functionality. 

<img width="1516" alt="Screen Shot 2020-04-28 at 12 16 04 PM" src="https://user-images.githubusercontent.com/60111667/80528953-96932680-894b-11ea-96dc-e7ed6fa9f709.png">
<img width="1516" alt="Screen Shot 2020-04-28 at 12 15 37 PM" src="https://user-images.githubusercontent.com/60111667/80528977-9d219e00-894b-11ea-9a63-69e2773ec41c.png">

**Comment by yasker** [comment] 2020-04-28 20:43
Is it because the backup retain was changed to 5? Can you try to retain at 5 when creating the new recurring job?

**Comment by khushboo-rancher** [comment] 2020-04-28 23:30
Actually, After reverting to snapshot, it is keeping backups till retain count starting from there and not deleting the backups taken before reverting. Is it something expected? 
Recurring snapshots get deleted in above scenario.

I've updated the steps to reproduce.

**Comment by yasker** [comment] 2020-04-29 00:14
I don't expect a revert to affect anything here. We will take a look.

**Comment by joshimoo** [comment] 2020-05-12 01:42
The backup retention code works correctly, the reason this happened is that to determine whether to include a backup in our cleanup we compare all the backup labels with the job labels. One of these labels is the Kubernetes status, which comes from the volume directly.

If you have look at your screenshot you will see that the volume switched to a different pod, which means that the content of the kubernetes status label is different from the previous backups kubernetes status label.

@yasker we should discuss whether we want to change the logic to exclude the kubernetes status label from that comparison. Since it seems to really be transient information.

**Comment by yasker** [comment] 2020-05-13 01:13
Pre-merged Checklist
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by khushboo-rancher** [comment] 2020-05-14 22:44
Verified in master - 9069373 commit id
Verification- **Passed**

Backups are getting deleted after reaching over retain count.

Steps followed to test:
1. Created a volume(3 replicas) and attached it to a pod.
2. Created a backup b1.
2. Enable recurring backup with count 5.
3. After system takes 5 backups, Scaled down the workload to 0 and reverted to b1.
4. Scaled up the workload volume got attached to a different pod.
5. As a new recurring backup was created the oldest recurring backup got deleted.

**Closed** 2020-05-14 22:45 UTC
Labels: area/manager, bug, priority/3, require-automation-e2e
