### ISSUE TITLE
[BUG] Longhorn UI websockets fails when exposed via Ingress with Basic authentication 

### ISSUE THREAD

**Issue by mathieubodin** [longhorn/longhorn#1946] opened 2020-11-03 07:29 UTC
After applying what's described in [Create an Ingress with Basic Authentication (nginx)](https://longhorn.io/docs/1.0.2/deploy/accessing-the-ui/longhorn-ingress/), it seems websocket connections fail with 401 status.

---
Version: `v1.0.2`

**Comment by yasker** [comment] 2020-11-03 17:36
@khushboo-rancher can you check if you can reproduce the issue?

**Comment by khushboo-rancher** [comment] 2020-11-03 19:11
With MacOs, Chrome version 85.0.4183.121 and Firefox version 81.0.2, I'm not able to reproduce the issue.

In the past, there have been some issues around it as while opening a WebSocket connection which requires basic authentication, the header info gets eliminated causing the 401 failure. But those are fixed now.
https://bugs.chromium.org/p/chromium/issues/detail?id=123862

@mathieubodin Can you please let us know the OS and browser you're using? Also, can you update the browser or use other browsers to see if the error occurs?

**Comment by khushboo-rancher** [comment] 2020-11-03 19:31
@yasker Using Safari Version 14.0, I was able to reproduce the issue.

**Comment by mathieubodin** [comment] 2020-11-03 19:44
> @yasker Using Safari Version 14.0, I was able to reproduce the issue.
> 
> In the console, the below logs can be seen. However, the basic functionality of UI is working.
> 
> ```
> WebSocket connection to 'ws://ui-url/v1/ws/1s/volumes' failed: Unexpected response code: 401
> WebSocket connection to 'ws://ui-url/v1/ws/1s/settings' failed: Unexpected response code: 401
> WebSocket connection to 'ws://ui-url/v1/ws/1s/engineimages' failed: Unexpected response code: 401
> WebSocket connection to 'ws://ui-url/v1/ws/1s/nodes' failed: Unexpected response code: 401
> ```

That's exactly my case !

**Comment by yasker** [comment] 2020-11-03 23:28
Thanks for confirming @mathieubodin . It is a browser issue for not sending authorization header over WebSocket, so I am afraid there isn't much we can do on our side. I will close this as `won't fix` .

**Closed by yasker** 2020-11-03 23:28 UTC

**Comment by Joao-1** [comment] 2024-01-11 19:24
I was getting 504 (Gateway Timeout) when accessing the UI in Opera GX. All works well in Chrome and Edge. Thanks for insight. I wouldn't notice this without reading this issue.
