### ISSUE TITLE
Attach failed for volume (identical to #569)

### ISSUE THREAD

**Issue by cail41** [longhorn/longhorn#625] opened 2019-07-10 04:47 UTC
Hi, I have the same problem with the mentioned issue #, but with no resolution

Steps
Install Longhorn with default sc = true
Create pvc  (note the status below)

> kubectl get pvc
NAME             STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
longhorn-pvc     Bound    pvc-17417ec1-a2ca-11e9-99d2-0050568b72ee   25Gi       RWO            longhorn       14m
postgres-pvc-2   Bound    pvc-72fdff08-a296-11e9-99d2-0050568b72ee   30Gi       RWO            ceph           6h23m
> kubectl get pvc longhorn-pvc -o yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    field.cattle.io/creatorId: user-2wbsc
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/longhorn
  creationTimestamp: 2019-07-10T04:20:46Z
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    cattle.io/creator: norman
  name: longhorn-pvc
  namespace: default
  resourceVersion: "1234866"
  selfLink: /api/v1/namespaces/default/persistentvolumeclaims/longhorn-pvc
  uid: 17417ec1-a2ca-11e9-99d2-0050568b72ee
spec:
  accessModes:
  - ReadWriteOnce
  dataSource: null
  resources:
    requests:
      storage: 25Gi
  storageClassName: longhorn
  volumeMode: Filesystem
  volumeName: pvc-17417ec1-a2ca-11e9-99d2-0050568b72ee
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 25Gi
  phase: Bound
> 

So far so good  - pvc is bound 

Next, create a postgres deployment

apiVersion: extensions/v1beta1 
kind: Deployment 
metadata: 
  name: postgres-longhorn
spec: 
  replicas: 1 
  template: 
    metadata: 
      labels: 
        app: postgres 
    spec: 
     containers: 
     - name: postgres 
       image: postgres:10 
       imagePullPolicy: "IfNotPresent" 
       ports: 
       - containerPort: 5432 
       env: 
       - name: POSTGRES_USER 
         value: pgbench 
       - name: POSTGRES_PASSWORD 
         value: pgbench 
       - name: PGBENCH_PASSWORD 
         value: pgbench 
       - name: PGDATA 
         value: /var/lib/postgresql/data/pgdata 
       volumeMounts: 
       - mountPath: /var/lib/postgresql/data 
         name: datadir 
     volumes: 
     - name: datadir 
       persistentVolumeClaim: 
         claimName: longhorn-pvc 

Result - POD  is container creating with the event

> kubectl describe pod postgres-longhorn-8678b7cffb-bxtp9
Name:               postgres-longhorn-8678b7cffb-bxtp9
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               ams3-rancher-app-5/10.176.205.62
Start Time:         Wed, 10 Jul 2019 04:28:51 +0000
Labels:             app=postgres
                    pod-template-hash=8678b7cffb
Annotations:        <none>
Status:             Pending
IP:                 
Controlled By:      ReplicaSet/postgres-longhorn-8678b7cffb
Containers:
  postgres:
    Container ID:   
    Image:          postgres:10
    Image ID:       
    Port:           5432/TCP
    Host Port:      0/TCP
    State:          Waiting
      Reason:       ContainerCreating
    Ready:          False
    Restart Count:  0
    Environment:
      POSTGRES_USER:      pgbench
      POSTGRES_PASSWORD:  pgbench
      PGBENCH_PASSWORD:   pgbench
      PGDATA:             /var/lib/postgresql/data/pgdata
    Mounts:
      /var/lib/postgresql/data from datadir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-t6q7n (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  datadir:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  longhorn-pvc
    ReadOnly:   false
  default-token-t6q7n:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-t6q7n
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason              Age                  From                         Message
  ----     ------              ----                 ----                         -------
  Normal   Scheduled           9m19s                default-scheduler            Successfully assigned default/postgres-longhorn-8678b7cffb-bxtp9 to ams3-rancher-app-5
  Warning  FailedAttachVolume  63s (x5 over 9m11s)  attachdetach-controller      AttachVolume.Attach failed for volume "pvc-17417ec1-a2ca-11e9-99d2-0050568b72ee" : rpc error: code = Internal desc = Bad response statusCode [500]. Status [500 Internal Server Error]. Body: [message=unable to attach volume pvc-17417ec1-a2ca-11e9-99d2-0050568b72ee to ams3-rancher-app-5: volume pvc-17417ec1-a2ca-11e9-99d2-0050568b72ee not scheduled, code=Server Error, detail=] from [http://longhorn-backend:9500/v1/volumes/pvc-17417ec1-a2ca-11e9-99d2-0050568b72ee?action=attach]
  Warning  FailedMount         34s (x4 over 7m16s)  kubelet, ams3-rancher-app-5  Unable to mount volumes for pod "postgres-longhorn-8678b7cffb-bxtp9_default(37db28b6-a2cb-11e9-99d2-0050568b72ee)": timeout expired waiting for volumes to attach or mount for pod "default"/"postgres-longhorn-8678b7cffb-bxtp9". list of unmounted volumes=[datadir]. list of unattached volumes=[datadir default-token-t6q7n]
> 

This is RKE cluster 2.2.4

Kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.7", GitCommit:"6f482974b76db3f1e0f5d24605a9d1d38fad9a2b", GitTreeState:"clean", BuildDate:"2019-03-25T02:52:13Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.5", GitCommit:"2166946f41b36dea2c4626f90a77706f426cdea2", GitTreeState:"clean", BuildDate:"2019-03-25T15:19:22Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
> 
I note that in the referred issue the solution was to 'move' or 'relocate' pods - not sure what is meant by that.
Thanks, Phil

**Comment by cail41** [comment] 2019-07-10 07:13
UPDATE: The issue for me seems to have been a PV stuck in terminating state. I needed to look at kubectl get volumeattachment and identify attachments that should not be there and manually delete them. So right now things are ok, but I am concerned about the stuck pv volume. I believe I have a problem with one node so that when a pod was created, it was evicted, and that eviction caused the longhorn pv to hand. Either that or some other pod failure caused it, so this is worrying behavior.

**Comment by yasker** [comment] 2019-07-10 17:42
Add a link to #569 

@cail41 Pod eviction is probably the reason, which would be similar to what @tiger0425 mentioned in #569 . I would still like to know how @tiger0425 "migrated" the pod in the first place to trigger the issue though. Sounds like an easier way to reproduce than forcing a pod eviction.

**Comment by tedder** [comment] 2019-11-22 22:00
boop. not stale. Not commenting on the other one because this seems to be documented better.

**Comment by yasker** [comment] 2019-11-22 22:05
@tedder So you have the same issue with the latest release? Do you have any information we can use to troubleshoot this one?

**Comment by tedder** [comment] 2019-11-22 22:07
The [similar issue I had](https://github.com/longhorn/longhorn/issues/389#issuecomment-551326179) was related to volume taints; I haven't been able to reproduce or make a simple repro case, feel free to close if you think this is a nonissue (ignoring "my" issue above).

**Comment by yasker** [comment] 2019-11-22 22:16
@tedder I see. I will close this one and keep the issue you mentioned ( #389 ) open. This one is pretty old, many things has changed since then, so I am not sure if this one still applies to your case.

Feel free to reopen if this is reproducible in the latest release.

**Closed by yasker** 2019-11-22 22:16 UTC
