### ISSUE TITLE
[BUG] [v1.3.x] Can not delete backingimage

### ISSUE THREAD

**Issue by chriscchien** [longhorn/longhorn#5626] opened 2023-03-21 10:08 UTC
## Describe the bug (🐛 if you encounter this issue)

In v1.3.x head, backingimage can not delete from UI and command line (from https://ci.longhorn.io/job/public/job/v1.3.x/job/v1.3.x-longhorn-tests-sles-amd64/327/testReport/tests/test_backing_image/ and can be manually reproduced.)

## To Reproduce

1. Deploy Longhorn with all v1.3.x-head images
2. Use https://longhorn-backing-image.s3-us-west-1.amazonaws.com/parrot.qcow2 create backing image
3. Delete the backingimage from UI or command line, the deletion stuck

## Expected behavior

backingimage delete success

## Log or Support bundle

[longhorn-support-bundle_acce0a91-05f8-4340-9cca-8569dc93caf1_2023-03-21T10-00-08Z.zip](https://github.com/longhorn/longhorn/files/11026990/longhorn-support-bundle_acce0a91-05f8-4340-9cca-8569dc93caf1_2023-03-21T10-00-08Z.zip)

## Environment

 - Longhorn version: v1.3.x
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.24.7+k3s1
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): AWS

## Additional context

After the first backimage delete stuck, new created backimages can be delete success.

**Comment by innobead** [comment] 2023-03-21 10:12
cc @ChanYiLin @shuo-wu

**Comment by innobead** [comment] 2023-03-21 10:15
```
023-03-21T09:59:53.678355949Z goroutine 739 [running]:
2023-03-21T09:59:53.678361441Z k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1cf89a0, 0x345b020})
2023-03-21T09:59:53.678365816Z 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0x7d
2023-03-21T09:59:53.678370029Z k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0xc000dcb220})
2023-03-21T09:59:53.678374258Z 	/go/src/github.com/longhorn/longhorn-manager/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x75
2023-03-21T09:59:53.678378694Z panic({0x1cf89a0, 0x345b020})
2023-03-21T09:59:53.678382931Z 	/usr/local/go/src/runtime/panic.go:1038 +0x215
2023-03-21T09:59:53.678387267Z github.com/longhorn/longhorn-manager/controller.(*BackingImageController).IsBackingImageDataSourceCleanup(0xc000153600, 0xc000dbd398)
2023-03-21T09:59:53.678391493Z 	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_controller.go:295 +0x60
2023-03-21T09:59:53.678395844Z github.com/longhorn/longhorn-manager/controller.(*BackingImageController).syncBackingImage(0xc000153600, {0xc000dacea0, 0x14})
2023-03-21T09:59:53.678399961Z 	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_controller.go:214 +0xdee
2023-03-21T09:59:53.678403883Z github.com/longhorn/longhorn-manager/controller.(*BackingImageController).processNextWorkItem(0xc000153600)
2023-03-21T09:59:53.678407742Z 	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_controller.go:134 +0xdb
2023-03-21T09:59:53.678411700Z github.com/longhorn/longhorn-manager/controller.(*BackingImageController).worker(...)
2023-03-21T09:59:53.678415738Z 	/go/src/github.com/longhorn/longhorn-manager/controller/backing_image_controller.go:122
2023-03-21T09:59:53.678419633Z k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7f730f386130)
```

**Comment by ChanYiLin** [comment] 2023-03-21 10:40
Root cause: 
Controller tried to cleanup the tmp file When deleting the backing image.
Controller failed to get bids but the not found error was not caught so it crashed because of nil pointer.

Question: Why there is no BIDS and BIM. BIDS has ownership of BI, so it should be there and wouldn't be deleted first.

**Comment by innobead** [comment] 2023-03-21 10:50
> Root cause: Controller tried to cleanup the tmp file When deleting the backing image. Controller failed to get bids but the not found error was not caught so it crashed because of nil pointer.
> 
> Question: Why there is no BIDS and BIM. BIDS has ownership of BI, so it should be there and wouldn't be deleted first.

@shuo-wu any idea? however, still need to do the null check surely.

**Comment by innobead** [comment] 2023-03-21 11:24
oh it is caused by no BlockOwnerDeletion for BI as owner reference in BIDS. 

[/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L322-L329](https://github.com/longhorn/longhorn-manager/blob/b52816b74193578744e306a47d5fb9a739148624/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/types.go#L322-L329)
```go
	// If true, AND if the owner has the "foregroundDeletion" finalizer, then
	// the owner cannot be deleted from the key-value store until this
	// reference is removed.
	// Defaults to false.
	// To set this field, a user needs "delete" permission of the owner,
	// otherwise 422 (Unprocessable Entity) will be returned.
	// +optional
	BlockOwnerDeletion *bool `json:"blockOwnerDeletion,omitempty" protobuf:"varint,7,opt,name=blockOwnerDeletion"`
```

**Comment by ChanYiLin** [comment] 2023-03-21 11:36
@innobead does it mean that deleting bi would delete bids right away
And bids would be deleted without waiting bi to be deleted first?

**Comment by innobead** [comment] 2023-03-21 11:37
> @innobead does it mean that deleting bi would delete bids right away And bids would be deleted without waiting bi to be deleted first?

No, I just deleted my original comment. It seems there is `BlockOwnerDeletion` true and when deleting BI is also foreground.

**Comment by ChanYiLin** [comment] 2023-03-21 11:38
Oh got it 
So still need to reproduce to see what will happen

**Comment by ChanYiLin** [comment] 2023-03-21 11:49
Then use bids status to check if it is cleaned wouldn’t work if bids will be deleted first
Manager wouldnt have the chance to see it is failed and try to cleanup

**Comment by innobead** [comment] 2023-03-21 12:14
When the data source CR will be deleted?

**Comment by ChanYiLin** [comment] 2023-03-22 01:41
@chriscchien @roger-ryao @innobead 
This issue could also happen in v1.4.x
I have reproduced it successfully in v1.4.x

**Comment by ChanYiLin** [comment] 2023-03-22 06:09
## Test Steps:

### Case1: delete during in-progress
1. create a backing image (upload or download type)
2. delete the backing image when it is in-progress
    - remember to add `--cascade=foreground` e.g. `kubectl delete bi/test -n longhorn-system --cascade=foreground`
    - from UI, it already applies the option to the command
3. delete successfully

### Case2: delete after ready
1. create a backing image (upload or download type)
2. delete the backing image when it is ready
    - remember to add `--cascade=foreground` e.g. `kubectl delete bi/test -n longhorn-system --cascade=foreground`
    - from UI, it already applies the option to the command
3. delete successfully

**Comment by ChanYiLin** [comment] 2023-03-22 08:52
bug in our e2e test also related to this issue
https://github.com/longhorn/longhorn-tests/pull/1287

**Comment by khushboo-rancher** [comment] 2023-03-23 02:06
@ChanYiLin Can you help moving this to ready for testing?

**Comment by ChanYiLin** [comment] 2023-03-23 03:24
@khushboo-rancher moved, thanks!

**Comment by roger-ryao** [comment] 2023-03-31 09:22
**Verified on v1.3.x-head 20230331**

- longhorn v1.3.x-head ([b5d5f69](https://github.com/longhorn/longhorn/commit/b5d5f69477f22ed3254e3e7b16f788d6e40aee02))
- longhorn-manager v1.3.x-head ([a4d58fb](https://github.com/longhorn/longhorn-manager/commit/a4d58fb66b4c682a57d3d6905c136c3adec9ce4b))

**The test steps**

https://github.com/longhorn/longhorn/issues/5626#issuecomment-1478972279

**Result Passed**

**Closed as completed** 2023-03-31 09:22 UTC
Labels: kind/bug, severity/1, priority/0, kind/regression, area/backing-image
