### ISSUE TITLE
[BUG] Restore from backup when S3 target is invalid creates a Healthy volume

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1255] opened 2020-04-27 21:07 UTC
**Describe the bug**
Restore from backup when S3 target is invalid creates a Healthy volume

**To Reproduce**

- Create a volume and a backup
- Invalidate the target URL in Settings page.
- Restore from backup into a volume - `v1`
- The volume `v1` is seen. in Healthy. state
- The. replicas are seen in "Running" state
- Create PV/PVC for the volume
- Attach the volume through Rancher in a workload and deploy the workload.
- The workload fails to deploy

<img width="1256" alt="Screen Shot 2020-04-27 at 12 11 24 PM" src="https://user-images.githubusercontent.com/26032343/80420820-40ad7880-8890-11ea-9b17-bb2a62856211.png">
 with error - 

**Expected behavior**
The volume should not be in "Healthy" state and the replicas should have failed rebuilding as the S3 target values are invalid

**Environment:**
 - Longhorn version: master - 04/27/2020
 - Kubernetes version: 1.17.5 
 - Node OS type and version:  RKE do Linux

**Comment by yasker** [comment] 2020-04-30 03:38
It's ok if we restored the volume, but the workload shouldn't fail.

**Comment by yasker** [comment] 2020-05-01 18:45
We should prevent the CSI plugin to attach/mount the volume that's in restoration or DR phase.

**Comment by shuo-wu** [comment] 2020-05-12 12:44
Longhorn already prevented the CSI plugin to use the restore/DR volume and the expanding volume. I will update the go client and check `v.ready` anyway.

Test steps:
1. Create a pod with Longhorn volume.
2. Write some data and create a backup.
3. Restore a volume from the backup.
4. Create another pod using the restoring volume when the restore is in progress. (Make sure `spec.nodeName` of this pod is the same as the restore volume current node ID).
5. Check if the pod cannot become Running state.

**Comment by yasker** [comment] 2020-05-12 23:06
Pre-merged Checklist
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by shuo-wu** [comment] 2020-05-13 03:35
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [ ] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by yasker** [comment] 2020-05-13 17:27
@sowmyav27 Can you check if https://github.com/longhorn/longhorn/issues/1255#issuecomment-627318982 makes sense to you? If PR for #1260 has already fixed the issue in this case, we can close this one.

**Comment by sowmyav27** [comment] 2020-05-13 17:53
@yasker @shuo-wu I have one question about this comment https://github.com/longhorn/longhorn/issues/1255#issuecomment-627318982

"Whether we need to disable the PV/PVC creation for the restoring volume" --> But we could disable this from the Longhorn perspective? As per we discussed yesterday?

**Comment by yasker** [comment] 2020-05-13 18:32
@sowmyav27 I don't think we need to disable PV/PVC creation in this case. As I mentioned yesterday:
1. If Longhorn disabled PV/PVC creation, the user can still do it using Rancher or kubectl.
2. When does the user create the PV/PVC is not related to when the user wants to use the volume. For example, to speed up the recovery process, the user can choose to create PV/PVC when restoring is happening, but only use it later when the restore completed. In this way, the volume will become immediately usable after the restore completed. And if there are any issues when creating PV/PVC, they can be identified and addressed before the restore completed, so the user won't waste time addressing it after the restore is done.

**Comment by sowmyav27** [comment] 2020-05-13 20:01
@yasker When a volume is "Faulted" because of this issue here https://github.com/longhorn/longhorn/issues/1255#issue-607853895, Can we **`disable`** the attach to node/Create PV/PVC options in longhorn UI.

But this should not affect other volumes "faulted" (due to some other issue where it can be salvaged). 

Do we need a distinction of these two use cases?

**Comment by yasker** [comment] 2020-05-13 22:14
@sowmyav27 

If the volume is `Faulted`, the attach operation will be disallowed from UI and API. But we don't have ability to differentiate it's `Faulted` due to replica disconnection or failed restoration at the moment. You can file an issue for that. For the corrupted volume, we shouldn't allow salvage or auto-salvage operation. In fact, @shuo-wu I think we mentioned this already. Do we have an issue for that?

I am not sure if `Create PV/PVC` is disabled for `faulted` volume. We can do that if it's not done. Can you check and file a UI issue if it's not there?

**Comment by sowmyav27** [comment] 2020-05-13 23:36
@yasker  When the heath of the volume is `Faulted`, Create PV/PVC is disabled on the UI
<img width="1875" alt="Screen Shot 2020-05-13 at 4 34 33 PM" src="https://user-images.githubusercontent.com/26032343/81876515-be7fae00-9537-11ea-8afd-142b145aae3a.png">

I will file an issue for this --> `But we don't have ability to differentiate it's Faulted due to replica disconnection or failed restoration at the moment` (as per comments)

**Comment by sowmyav27** [comment] 2020-05-15 22:51
**Verified on master - 05/15/2020**

Validation: **`PASSED`**

- Create a volume and a backup
- Invalidate the target URL in Settings page.
- Restore from backup into a volume - v1
- The volume v1 is seen. in Healthy. state for a second ( approx)
- The volume is then in "Faulted" state in Volume detail page.
- Backup restore - fails in this case - which is expected 
- Volume details page shows status as
<img width="625" alt="Screen Shot 2020-05-15 at 3 46 31 PM" src="https://user-images.githubusercontent.com/26032343/82102095-46de8a00-96c3-11ea-99f0-c4e8032c9630.png">
- But in this use case - UI shows Create PV/PVC option enabled. And user is able to create a PV and PVC
<img width="1888" alt="Screen Shot 2020-05-15 at 3 48 29 PM" src="https://user-images.githubusercontent.com/26032343/82102187-945af700-96c3-11ea-84d8-320eea417c1a.png">
Logging issue - https://github.com/longhorn/longhorn/issues/1356- to track this separately

**Closed** 2020-05-15 22:51 UTC
Labels: area/engine, area/manager, bug, priority/2
