### ISSUE TITLE
[FEATURE] Import and export SPDK longhorn volumes to longhorn sparse file directory

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#4100] opened 2022-06-09 13:03 UTC
Create a JSON-RPC command to import a directory of sparse files into a thinly provisioned SPDK logical volume store and a JSON-RPC command to export a logical volume in SPDK to a directory of sparse files.  

You can make a directory of sparse files with longhorn by setting up with one replica:
https://github.com/longhorn/longhorn/wiki/How-to-run-longhorn-engine-without-containers

To make snapshots, you can mount the longhorn volume, write some data, then run `./longhorn-engine snapshot create <snapshot-name>`.

In longhorn-engine, sparse files are read with https://github.com/longhorn/sparse-tools and the `fiemap ioctl.`
https://www.kernel.org/doc/html/latest/filesystems/fiemap.html

In longhorn-engine, sparse files are created with `ftruncate(2)`.  Extents are created whenever data is written to an offset.

In SPDK, the logical volume is implemented as a blob.  In `lib/blob/blobstore.h`, there is `struct spdk_blob_mut_data`.  The `clusters` member of `struct spdk_blob_mut_data` is an array of addresses within the blobstore; a value of 0 for an element in the array implies that that cluster is zero and no cluster is allocated for it.

For SPDK, I have been creating an empty file on my computer.  Then I register it as an aio block device.  Then I create a logical volume store with that block device and create a logical volume in that logical volume store.

https://spdk.io/doc/bdev.html
https://spdk.io/doc/nvmf.html
https://spdk.io/doc/logical_volumes.html

**Comment by innobead** [comment] 2022-06-23 01:01
@DamiaSan are you working on this? any update.

**Comment by DamiaSan** [comment] 2022-06-23 02:16
Hi David,
sorry for the late I come back to you but last 2 weeks I have studied spdk code to understand how to make the task Keith assigned to me.
Just today I asked him on Slack some questions to confirm my last doubts, now I have a clear idea of the work to do.
Tomorrow I will start writing some notes about steps of the development and drowning a simple diagram of the code architecture; I will share with you and Keith when finished.
At that point I will have an idea of how much time I will need to make the task.

Bye
Damiano
________________________________

**Comment by innobead** [comment] 2022-09-06 02:22
@DamiaSan I moved this ticket to the current sprint. For any ticket you are working on, please move to the sprint. 

Also, we use zenhub board to understand the development pipeline, so I believe the issue is under implementation. 
![image](https://user-images.githubusercontent.com/899492/188533402-5a2de802-eac7-4695-867d-fe232e0a6450.png)

**Comment by DamiaSan** [comment] 2022-09-06 08:02
Pushed over spdk Gerrit upstream

https://review.spdk.io/gerrit/c/spdk/spdk/+/14360
https://review.spdk.io/gerrit/c/spdk/spdk/+/14361
https://review.spdk.io/gerrit/c/spdk/spdk/+/14362
https://review.spdk.io/gerrit/c/spdk/spdk/+/14363

**Comment by DamiaSan** [comment] 2022-09-06 08:04
> 

The issue is under review by SPDK members. All the work should be done, maybe I will have to change something according to review that will be made

**Comment by DamiaSan** [comment] 2022-09-06 09:17
If a sparse file is created exporting a logical volume, it will have the size of this bdev. So maybe it will have to be truncated to the desired size.
For example, if we import fileA in a logical volume and then we export this volume to fileB, fileB may not have the same size of fileA. Because lvol can have a different size of fileA and however real logical volume size is a multiple of blob cluster size (logical volume is made with a blob).

**Comment by innobead** [comment] 2023-01-05 15:49
Closing this, we enhanced spdk_dd application at the upstream, but it's not for runtime operation.

**Closed by innobead** 2023-01-05 15:49 UTC
Labels: kind/enhancement, area/engine, area/spdk
