### ISSUE TITLE
[BUG]  Scale replica snapsots warning

### ISSUE THREAD

**Issue by FaraSys** [longhorn/longhorn#4126] opened 2022-06-16 09:19 UTC
When reducing the number of replicas via the web interface:
type: 'Warning' reason: 'SnapshotError' lost track of the corresponding snapshot info inside volume engine"
type: 'Warning' reason: 'SnapshotDelete' snapshot is marked as removed"

longhorn-manager says:

```
time="2022-06-16T08:55:14Z" level=info msg="Deleting snapshot CR for the snapshot 4220c48f-1509-4363-8d84-1bf9a675a009" controller=longhorn-engine node=k-node-1
time="2022-06-16T08:55:14Z" level=info msg="Creating snapshot CR for the snapshot 4d8bd402-9e0e-4e2b-98f9-bb79871d9480" controller=longhorn-engine node=k-node-1
time="2022-06-16T08:55:14Z" level=info msg="Removing finalizer for snapshot 4220c48f-1509-4363-8d84-1bf9a675a009" controller=longhorn-snapshot node=k-node-1 snapshot=4220c48f-1509-4363-8d84-1bf9a675a009
time="2022-06-16T08:55:14Z" level=info msg="snapshot CR 4d8bd402-9e0e-4e2b-98f9-bb79871d9480 lost track of its snapshotInfo" controller=longhorn-snapshot node=k-node-1 snapshot=4d8bd402-9e0e-4e2b-98f9-bb79871d9480
time="2022-06-16T08:55:14Z" level=info msg="snapshot CR 4d8bd402-9e0e-4e2b-98f9-bb79871d9480 lost track of its snapshotInfo" controller=longhorn-snapshot node=k-node-1 snapshot=4d8bd402-9e0e-4e2b-98f9-bb79871d9480
time="2022-06-16T08:55:14Z" level=info msg="Event(v1.ObjectReference{Kind:\"Snapshot\", Namespace:\"longhorn-system\", Name:\"4d8bd402-9e0e-4e2b-98f9-bb79871d9480\", UID:\"8dc23b1a-8139-4659-80a3-4fbd93377aee\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"1113008\", FieldPath:\"\"}): type: 'Warning' reason: 'SnapshotError' lost track of the corresponding snapshot info inside volume engine"
time="2022-06-16T08:55:14Z" level=info msg="Deleting snapshot CR for the snapshot 4d8bd402-9e0e-4e2b-98f9-bb79871d9480" controller=longhorn-engine node=k-node-1
time="2022-06-16T08:55:14Z" level=info msg="Creating snapshot CR for the snapshot 76ea635a-86b0-422a-ad71-bf0d7db5d022" controller=longhorn-engine node=k-node-1
time="2022-06-16T08:55:14Z" level=info msg="Removing finalizer for snapshot 4d8bd402-9e0e-4e2b-98f9-bb79871d9480" controller=longhorn-snapshot node=k-node-1 snapshot=4d8bd402-9e0e-4e2b-98f9-bb79871d9480
time="2022-06-16T08:55:14Z" level=info msg="Event(v1.ObjectReference{Kind:\"Snapshot\", Namespace:\"longhorn-system\", Name:\"76ea635a-86b0-422a-ad71-bf0d7db5d022\", UID:\"54650e2f-ff4a-468e-ad7f-f2a3397bd086\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"1113012\", FieldPath:\"\"}): type: 'Warning' reason: 'SnapshotDelete' snapshot is marked as removed"
```

## To Reproduce

pvc yaml example
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc-longhorn
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: "longhorn"
  resources:
    requests:
      storage: 1Gi
```

1. Сreate pvc from above example
2. Attach volume to node
3. Scale replicas to 5
4. Scale replicas to 3
5. type: 'Warning' reason: 'SnapshotError' lost track of the corresponding snapshot info inside volume engine"
    type: 'Warning' reason: 'SnapshotDelete' snapshot is marked as removed"

## Log or Support bundle

[longhorn-support-bundle.zip](https://github.com/longhorn/longhorn/files/8917475/longhorn-support-bundle_40ff7206-cd00-4dd4-8a35-e04df63f299a_2022-06-16T09-16-05Z.zip)

## Environment

Longhorn version: v1.3.0
Kubernetes version: v1.20.7/v1.23.6
Node config
    OS type and version: Ubuntu 20.04
    CPU per node: 4/8
    Memory per node: 2G/8G
    Disk type: ssd
    Network bandwidth and latency between the nodes: 10G
Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hyper-v/Vmware

**Comment by FaraSys** [comment] 2022-06-16 09:21
KEYWORD #4120

**Comment by c3y1huang** [comment] 2022-06-16 09:30
cc @PhanLe1010

**Comment by PhanLe1010** [comment] 2022-06-16 21:34
I tried to the reproducing steps. This behavior is expected because:
1. When users increase number of replica count for volume by 2, Longhorn will retry to rebuild replica one by one
2. For each replica rebuild, Longhorn make a new system snapshot before rebuilding (hence you see the `Creating snapshot CR for the snapshot ..` message). After each rebuilding, Longhorn will do an automatic snapshot purge (hence you see the event ` 'SnapshotDelete' snapshot is marked as removed`) . However, the snapshot cannot be removed yet because it is the snapshot right next to the volume head.
3. Next, you see the `lost track of its snapshotInfo` message because the snapshot is being removed from engine CR first so snapshot controller see this event first before engine monitoring kick in and delete the snapshot
4. Now in the next rebuilding, Longhorn repeat step 1 and 2 above for a new system snapshot. However, at this time, the first system snapshot can be remove because it is no longer the snapshot next to volume head. Hence you see `Deleting snapshot CR for the snapshot ` and `Removing finalizer for snapshot`

**Comment by innobead** [comment] 2022-06-17 05:53
cc @shuo-wu

**Comment by FaraSys** [comment] 2022-06-17 07:56
@PhanLe1010 If this is normal behavior, why are we getting a **warning** instead of an **info**?
Wanging's message says: 
type: 'Warning' **reason: 'SnapshotError'** lost track of the corresponding snapshot info inside volume engine"

**Comment by shuo-wu** [comment] 2022-06-17 08:59
> Next, you see the lost track of its snapshotInfo message because the snapshot is being removed from engine CR first so snapshot controller see this event first before engine monitoring kick in and delete the snapshot

I think you mean the snapshot file & the record in `engine.Status.Snapshots` will be removed first, then this log will be printed before the monitor cleans up the corresponding CR.

---

In the next version Longhorn will remove `engine.Status.Snapshots` hence there should not be such kinds of confusing logs.

**Comment by FaraSys** [comment] 2022-06-17 11:23
> 

I understand. Thank you

**Comment by danielb42** [comment] 2022-08-23 22:14
I'm seeing that warning too, not scaling anything but reaching the retain value for hourly snapshots (48). Do I understand correctly that the message (`'SnapshotError' lost track of the corresponding snapshot info inside volume engine"`) is related to purging the snapshot beyond the threshold, and does not imply any issue?

**Comment by CrazyMushu** [comment] 2022-08-24 07:15
> I'm seeing that warning too, not scaling anything but reaching the retain value for hourly snapshots (48). Do I understand correctly that the message (`'SnapshotError' lost track of the corresponding snapshot info inside volume engine"`) is related to purging the snapshot beyond the threshold, and does not imply any issue?

join the question. 
if this is the normal behavior of the longhorn system - why is there a warning here?

**Comment by shuo-wu** [comment] 2022-08-24 09:37
> if this is the normal behavior of the longhorn system 
I think YES.

cc @PhanLe1010 We may need to change the log level first to avoid misunderstanding.

**Comment by PhanLe1010** [comment] 2022-08-25 23:52
The log level is already info `time="2022-06-16T08:55:14Z" level=info msg="snapshot CR 4d8bd402-9e0e-4e2b-98f9-bb79871d9480 lost track of its snapshotInfo" controller=longhorn-snapshot node=k-node-1 snapshot=4d8bd402-9e0e-4e2b-98f9-bb79871d9480
`

But the event type is warning. Yeah, we can change the event type

**Comment by getsomebread** [comment] 2022-12-05 15:47
On Longhorn 1.3.1, I got this snapshot error after scaling replicas 3->2. After reading this, I scaled them back 2->3, however, the warnings still happen at every snapshot event. How do I resolve this issue?

**Comment by dseralathan** [comment] 2023-03-30 18:44
How we can alter the snapshot deletion day and time .. The system tries to create a new replica to delete old snaps and that time we hit a heavy load and all replica creation getting failed....

**Comment by innobead** [comment] 2023-09-14 06:23
https://github.com/longhorn/longhorn/issues/4126#issuecomment-1227865267
https://github.com/longhorn/longhorn/issues/4126#issuecomment-1158658735

**Comment by derekbit** [comment] 2024-06-17 03:56
@roger-ryao Can you help verify the issue if valid? Thank you.

**Comment by roger-ryao** [comment] 2024-06-18 05:20
Same as @PhanLe1010 [previous comment](https://github.com/longhorn/longhorn/issues/4126#issuecomment-1227865267),

The log level is already info `2024-06-18T03:45:33.864835648Z time="2024-06-18T03:45:33Z" level=info msg="Event(v1.ObjectReference{Kind:\"Snapshot\", Namespace:\"longhorn-system\", Name:\"850e4efe-3f50-45dd-b1d8-55f82cdd8ab7\", UID:\"9e44b4e7-6bd5-4d82-a449-a80fac48742b\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"598974\", FieldPath:\"\"}): type: 'Warning' reason: 'SnapshotDelete' snapshot is marked as removed"`
, but the event type is warning.

[supportbundle_4bbd2b07-548b-45d7-9e6d-6213443404f0_2024-06-18T04-26-39Z.zip](https://github.com/user-attachments/files/15880741/supportbundle_4bbd2b07-548b-45d7-9e6d-6213443404f0_2024-06-18T04-26-39Z.zip)

**Comment by yangchiu** [comment] 2024-07-02 02:44
Verified passed on master-head (longhorn-manager 4647dce) following [the test steps](https://github.com/longhorn/longhorn/issues/4126#issuecomment-2197520942).

The events are `Normal` instead of `Warning` level as expected:
```
$ kubectl logs longhorn-manager-9n8qg -c longhorn-manager -n longhorn-system | grep type
time="2024-07-02T02:31:35Z" level=info msg="Event(v1.ObjectReference{Kind:\"Snapshot\", Namespace:\"longhorn-system\", Name:\"c04e829a-0682-4256-a3be-ca10796f7f2d\", UID:\"3e29457d-24f8-46c2-9143-d2bf7e7ac7f3\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"2884\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' snapshot was removed from engine" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:377"
time="2024-07-02T02:31:36Z" level=info msg="Event(v1.ObjectReference{Kind:\"Snapshot\", Namespace:\"longhorn-system\", Name:\"6aa80c2f-e0b4-4f7d-b3be-3fb4ca62018f\", UID:\"e9cc2793-8644-4293-b2e5-f9969872bc85\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"2888\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' snapshot is marked as removed" func="record.(*eventBroadcasterImpl).StartLogging.func1" file="event.go:377"
```

**Closed by yangchiu** 2024-07-02 02:44 UTC
Labels: kind/bug, component/longhorn-manager, priority/0, severity/4, backport/1.5.6, backport/1.6.3
