### ISSUE TITLE
[BUG] A failed backup sometimes does not transition to Error state; gets stuck in InProgress; may prevent recurring backups from running

### ISSUE THREAD

**Issue by cdhowie** [longhorn/longhorn#9417] opened 2024-09-07 21:10 UTC
See #9361 for context. Per [this comment](https://github.com/longhorn/longhorn/issues/9361#issuecomment-2336452935) I am splitting that issue into two.

This issue represents the second half of the behavior described in that report: sometimes when a backup fails, it gets stuck in the InProgress state. If that backup was triggered from a recurring job, this can block all future recurring backup jobs from running, with no notification to the cluster operator that there is any problem.

**Comment by derekbit** [comment] 2024-09-08 02:39
It sounds caused by https://github.com/longhorn/longhorn/issues/9168. If so, it will be fixed in the upcoming v1.6.3.

cc @ChanYiLin

**Comment by derekbit** [comment] 2024-09-08 02:40
@ChanYiLin Can you help check if it is the same issue? Thanks.

**Comment by ChanYiLin** [comment] 2024-09-10 08:20
Hi @cdhowie 
Agree with the team members, I think this is caused by the issue we found in here: https://github.com/longhorn/longhorn/issues/9168

Since the recurring job pod keeps waiting the backup to be completed or failed, it hangs forever if the backup gets stuck in InProgress status.

**Workaround**
- Delete the InProgress Backup directly, it won't cause any harm.
- After the Backup is deleted, the recurring job pod should become failed immediately since it can't find the Backup anymore (You can also delete the pod manually). Our recurring job retries 3 times. After the pod is deleted, it will recreate the pod to back up the volume again.

The fix of this issue will be released in the following version
- v1.7.2
- v1.6.3
- v1.8.0

Thanks

**Comment by derekbit** [comment] 2024-09-11 05:18
Let's close the ticket. Feel free to reopen it if you run into the issue in the fixed versions. Thanks.

**Closed by derekbit** 2024-09-11 05:18 UTC
Labels: kind/bug, wontfix, area/volume-backup-restore, duplicated, require/qa-review-coverage, require/backport
