### ISSUE TITLE
[ENHANCEMENT] Speed up rebuilding by getting checksum simultaneously

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1948] opened 2020-11-03 12:12 UTC
**Is your feature request related to a problem? Please describe.**
We can speed up the rebuilding by [requesting the server block checksum](https://github.com/longhorn/sparse-tools/blob/bb457e12173d2073ce3f8193cf5e3208c828ac43/sparse/client.go#L248) and [calculating the local block checksum](https://github.com/longhorn/sparse-tools/blob/bb457e12173d2073ce3f8193cf5e3208c828ac43/sparse/client.go#L262) simultaneously.

**Describe the solution you'd like**
See above.

**Comment by shuo-wu** [comment] 2020-11-10 11:39
The reason that failed replica reuse time and new replica rebuilding time are the same is:
1. Since there is actually no data on the receiver side for the new replica rebuilding case, `client.getServerChecksum` takes less time.
```
[instance-manager-r-3dab8865] [vol-r-793b61f8] time="2020-11-10T06:19:14Z" level=info msg="Sync batchInterval length 131072, total time 3.668229ms, checksum time 1.359858ms, percentage 37.0712406450088%"
[instance-manager-r-3dab8865] [vol-r-793b61f8] time="2020-11-10T06:19:14Z" level=info msg="Sync batchInterval length 131072, total time 2.857143ms, checksum time 741.813µs, percentage 25.963453701827316%"
[instance-manager-r-3dab8865] [vol-r-793b61f8] time="2020-11-10T06:19:14Z" level=info msg="Sync batchInterval length 131072, total time 2.603783ms, checksum time 760.654µs, percentage 29.213417554381454%"
[instance-manager-r-3dab8865] [vol-r-793b61f8] time="2020-11-10T06:19:14Z" level=info msg="Sync batchInterval length 131072, total time 3.549488ms, checksum time 1.706659ms, percentage 48.08183602818209%"
```
2. Though there is no writing for the failed replica reuse case, `client.getServerChecksum` takes a longer time and the client needs to calculate the local checksum. 
```
[instance-manager-r-b148c9fb] [vol-r-839c225b] time="2020-11-10T06:33:56Z" level=info msg="Sync batchInterval length 131072, total time 1.479149ms, checksum time 1.478969ms, percentage 99.98783084057116%"
[instance-manager-r-b148c9fb] [vol-r-839c225b] time="2020-11-10T06:33:56Z" level=info msg="Sync batchInterval length 131072, total time 1.729528ms, checksum time 1.729388ms, percentage 99.99190530595631%"
[instance-manager-r-b148c9fb] [vol-r-839c225b] time="2020-11-10T06:33:56Z" level=info msg="Sync batchInterval length 131072, total time 1.980584ms, checksum time 1.980444ms, percentage 99.99293137781584%"
[instance-manager-r-b148c9fb] [vol-r-839c225b] time="2020-11-10T06:33:56Z" level=info msg="Sync batchInterval length 131072, total time 1.397808ms, checksum time 1.397618ms, percentage 99.98640728912697%"
```
As a result, the rebuilding time in both cases are almost the same in general.

---

It seems that removing the checksum mechanism won't speed up the rebuilding comparing with using 2 goroutines to handle checksums simultaneously. Because the client still needs time to read data from the local file.

---

A simple test result for this enhancement:
The time of rebuilding 10Gi data in ext4 filesystem of a Longhorn volume:
Before introducing this feature: 2min40sec;
After introducing this feature: 2min.

If necessary, we can use a larger data set to test the improvement.

**Comment by meldafrawi** [comment] 2020-11-19 21:11
**Observations:**

Cluster specs:
1 controlplane node  (4 vCPUs / 8 GB /160 GB)
3 worker nodes  (4 vCPUs / 8 GB /160 GB)

**Rebuilding replica with 10 GB of data**
- Longhorn v1.0.2: 5 min, 47 seconds
- Longhorn master: 5 min, 27 seconds

**Rebuilding replica with 16 GB of data**
- Longhorn v1.0.2:  15 min, 7 seconds
- Longhorn master: 12 min, 27 seconds

**Comment by shuo-wu** [comment] 2020-11-27 11:17
I just tested 50GB data rebuilding today. The result is almost the same as Mohamed's. I will re-check this feature later.

**Comment by shuo-wu** [comment] 2020-12-03 04:16
I just retry the test with some additional debug logs added. Here is the test step and the result :
1. Deploy Longhorn system with the `master` image
2. Deploy 2 engine images: 
  - `shuowu/longhorn-engine:master-1948` (Based on the `longhornio/longhorn-engine:master `and just add some addtional debug logs)
  - `shuowu/longhorn-engine:v1.0.x-1948` (Based on the `longhornio/longhorn-engine:master` but revert the (sparse file sync) PR commits and add some additional debug logs)
3. Create and attach a volume, write 50GB data to it.
4. Crash and delete one replica. Check the rebuilding time of the volume with different engine images.

Result:
1. `shuowu/longhorn-engine:master-1948`
Time: around 42.5min
Log:
```
[vol-r-048aec79] time="2020-12-02T09:01:25Z" level=info msg="Sending file volume-snap-d2fe55bb-fb15-44ae-b0fe-5006554c3671.img to 10.42.1.214:10004"
time="2020-12-02T09:01:25Z" level=info msg="source file size: 59055800320, setting up directIo: true"
......
[instance-manager-r-de3b0700] [vol-r-048aec79] time="2020-12-02T09:45:17Z" level=info msg="syncFileContent succeed: server checksum time 544619 ms, client checksum time 828134 ms, send time 1721255 ms"
``` 

2. `shuowu/longhorn-engine:v1.0.x-1948`
Time: around 50.7min
Log:
```
[vol-r-048aec79] time="2020-12-02T11:46:32Z" level=info msg="Sending file volume-snap-94e4b90e-3094-4941-b661-a698483135cc.img to 10.42.1.221:10004"
time="2020-12-02T11:46:32Z" level=info msg="source file size: 59055800320, setting up directIo: true"
......
[vol-r-048aec79] time="2020-12-02T12:37:13Z" level=info msg="syncFileContent succeed: server checksum time 510819 ms, client checksum time 638785 ms, send time 1891356 ms"
```

The result is different. The main cause (besides the debug logs) may be the Longhorn system version is always `master` rather than upgrading from `v1.0.2` to `master` comparing with the previous test. Currently, I am not sure if there are other modifications that degrade the overall rebuilding speed. I will test it as the next step.

**Comment by mfbrj** [comment] 2021-03-04 18:38
Performance improvements in replica rebuild are very apreciated. I use Ubuntu nodes that ask for a restarts due updates almost every week and on every restart, all replicas on the node are rebuilted.

My current metric when rebuild a replica on SSD diskand 10 Gb/s network:
Size: 50 Gi
Actual Size:38.8 Gi
Time to rebuild a replica: 648s
Replica rate: (38.8Gi/648) = 61.3 MB/s

**Comment by yasker** [comment] 2021-03-05 19:46
One possible explanation (thanks to the discussion with @mfbrj ):

In https://github.com/longhorn/sparse-tools/blob/c1877f4a574f57a461f7a69709defd20bc52718a/sparse/client.go#L95 , we depends on the holes to separate the sections for checksum.

But what if one section (data interval) is very big (hundreds of MB or even GB) but only changed a small amount, we will have to resync the whole section due to the difference of the checksum.

We should be able to sync more efficiently by cutting the big chunk of the data area into smaller pieces.

**Comment by joshimoo** [comment] 2021-06-08 21:34
## Pre Ready-For-Testing Checklist
* [x] Is the reproduce steps/test steps documented?

* [x] Is there a workaround for the issue? If so, is it documented?

* [x] Does the PR include the explanation for the fix or the feature?

* [x] ~~Does the PR include deployment change (YAML/Chart)? If so, have both YAML file and Chart been updated in the PR?~~

* [x] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed`)?
The PR is at https://github.com/longhorn/sparse-tools/pull/76
https://github.com/longhorn/longhorn-engine/pull/622
https://github.com/longhorn/longhorn-engine/pull/625

* [x] Which areas/issues this PR might have potential impacts on?
Area replica rebuild, snapshot coalescing,
Issues https://github.com/longhorn/longhorn/issues/2629

* [x] ~~**If labeled: require/LEP** Has the Longhorn Enhancement Proposal PR submitted?
The LEP PR is at ~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged (including `backport-needed`)?
The UI issue/PR is at~~

* [x] ~~**If labeled: require/doc** Has the necessary document PR submitted or merged (including `backport-needed`)?
The Doc issue/PR is at~~

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case? (including `backport-needed`)
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**If labeled: require/automation-engine** Has the engine integration test been merged (including `backport-needed`)?
The engine automation PR is at~~

* [x] ~~**If labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at~~

* [x] ~~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

**Comment by joshimoo** [comment] 2021-06-08 22:10
Testing instructions in a couple of comments in this issue: https://github.com/longhorn/longhorn/issues/2507
Split them up into multiple comments for context.

**Comment by innobead** [comment] 2021-06-09 09:23
cc @khushboo-rancher @kaxing

**Comment by khushboo-rancher** [comment] 2021-06-21 21:39
Verified with Longhorn v1.1.2-head `06/21/2021`

Validation - **In Progress**

| Version | Data in Gi | Time taken to rebuild replica |
| -------- | --------- | ----------------------------  |
| V1.1.1     |  30 | ~16 mins |
| v1.1.2-head | 30 | ~5 mins |

**Closed** 2021-06-24 03:44 UTC
Labels: area/engine, area/performance, backport-needed/1.1.2, highlight, kind/enhancement, priority/1
