### ISSUE TITLE
[BUG] nodeDownPodDeletionPolicy setting is not reflected on the UI

### ISSUE THREAD

**Issue by trieszecg** [longhorn/longhorn#2611] opened 2021-05-20 16:40 UTC
**Describe the bug**
setting nodeDownPodDeletionPolicy to delete-both-statefulset-and-deployment-pod value (either directly in the yaml values or via upgrade form) is not reflected in longhorn UI Settings page

**To Reproduce**
1) cluster explorer / apps & marketplace / installed apps
2) Edit/Upgrade longhorn
3) set nodeDownPodDeletionPolicy value to delete-both-statefulset-and-deployment-pod
4) complete upgrade process
5) open longhorn UI Settings/General
6) check Pod Deletion Policy When Node is Down value

**Expected behavior**
expected value: delete-both-statefulset-and-deployment-pod
actual value: do-nothing

**Log**
no error reported during upgrade process

**Environment:**
 - Longhorn version: v1.1.1

Rancher | v2.5.8
User Interface | v2.5.8
Helm | v2.16.8-rancher1
Machine | v0.15.0-rancher55

 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Rancher Catalog App
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: rke 20.10.5
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 5
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): openstack
 - Number of Longhorn volumes in the cluster: 3

**Additional context**
starting the same Edit/Upgrade process again the value is delete-both-statefulset-and-deployment-pod in the settings.
Reproduced via terraform as well, with longhorn.default_settings = true and false values too.
Saving the value via the UI it is shown correctly the next time.

**Comment by cclhsu** [comment] 2021-05-21 02:43
Currently, during upgrade process, Longhorn currently do not update the config to existing cluster.  We do have feature plan to resolve it https://github.com/longhorn/longhorn/issues/2570.

**Comment by trieszecg** [comment] 2021-05-21 08:16
thank you for pointing out @cclhsu
is there any workaround we can do in the meantime to change setting programmatically? I mean longorn is not something that can be  easily dropped and fresh deployed on a prod system...
thanks.

**Comment by cclhsu** [comment] 2021-05-21 09:36
Although It is possible to change the setting by calling Longhorn API.  However, it is not something we recommend, it might cause inconsistency between frontend and backend due to cache.    We would suggest to change to use UI until new solution is ready.

**Comment by jenting** [comment] 2021-06-25 01:14
> starting the same Edit/Upgrade process again the value is delete-both-statefulset-and-deployment-pod in the settings.
Reproduced via terraform as well, with longhorn.default_settings = true and false values too.
Saving the value via the UI it is shown correctly the next time.

Related to https://github.com/longhorn/longhorn/issues/2570

**Comment by jenting** [comment] 2021-11-10 06:01
Let's use #2570 to track this issue, close this one.

**Closed by jenting** 2021-11-10 06:01 UTC
Labels: kind/bug
