### ISSUE TITLE
[BUG] Failed to upgrade helm deployment due to hardcoded namespace (v1.2.3)

### ISSUE THREAD

**Issue by LukasAuerbeck** [longhorn/longhorn#3433] opened 2021-12-17 16:35 UTC
## Describe the bug

Installing the longhorn chart in a namespace other than `longhorn-system` is not possible with version `1.2.3` due to hardcoded namespaces in https://github.com/longhorn/longhorn/blob/v1.2.3/chart/templates/services.yaml.

There already is a helm helper function that is used in all other resources: https://github.com/longhorn/longhorn/blob/v1.2.3/chart/templates/_helpers.tpl#L57

## Environment

 - Longhorn version: 1.2.3
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Helm

**Comment by GeroL** [comment] 2021-12-17 17:02
Affected on my side: 
- longhorn-engine-manager
- longhorn-replica-manager

**Comment by jenting** [comment] 2021-12-21 02:08
The Longhorn is designed to be installed on the `longhorn-system` namespace only.
So, it's better to install it on the `longhorn-system` namespace.

**Comment by jenting** [comment] 2021-12-21 06:43
Related to #1844 and #2034.

**Comment by LukasAuerbeck** [comment] 2021-12-22 22:19
I'm not sure if this restriction is reflected in the possible configuration possibilities of the helm chart, since there are specific values to install the chart in a namepsace other than `longhorn-system`: https://github.com/longhorn/longhorn/blob/master/chart/values.yaml#L225
I also didn't notice any issues with installing the chart in a namespace other than `longhorn-system` so I think it would be better to not break this in a patch upgrade. Especially since the change just involves changing the namespace to use the already existing helper function: https://github.com/longhorn/longhorn/pull/3453/files

**Comment by jenting** [comment] 2021-12-22 22:56
> I'm not sure if this restriction is reflected in the possible configuration possibilities of the helm chart, since there are specific values to install the chart in a namepsace other than `longhorn-system`: https://github.com/longhorn/longhorn/blob/master/chart/values.yaml#L225 I also didn't notice any issues with installing the chart in a namespace other than `longhorn-system` so I think it would be better to not break this in a patch upgrade. Especially since the change just involves changing the namespace to use the already existing helper function: https://github.com/longhorn/longhorn/pull/3453/files

cc @innobead

**Comment by innobead** [comment] 2021-12-23 19:16
Agree, this should be fixed because we already have that configuration in values.yaml.

Also, thanks for your info about longhorn is working fine in a different namespace than longhorn-system, but as @jenting mentioned other issues needed to clarify before we can make sure longhorn working w/o any errors in non longhorn-system namespace. 

cc @khushboo-rancher @kaxing

**Comment by kaxing** [comment] 2021-12-30 08:51
Hello @LukasAuerbeck can I check with you on how you install v1.2.3 with helm into different namespace?
Are you using commands like this: `helm3 install longhorn longhorn/longhorn --set namespaceOverride="lh-test" --namespace l-test --create-namespace`

---
Notes on testing: The fix in master branch is allowing helm installation to appoint longhorn into different namespace without step onto any problems.

**Comment by LukasAuerbeck** [comment] 2022-01-02 06:17
I use helmfile to deploy longhorn. The file I use should translate roughly to your example. However, I don't set the `namespaceOverride` value, it's just something I saw while looking through the values.

This is the helmfile I use, excluding my values since they shouldn't be related to the issue:
```yaml
---
repositories:
- name: longhorn
  url: https://charts.longhorn.io

releases:
- name: longhorn
  namespace: longhorn
  chart: longhorn/longhorn
  version: 1.2.2
  atomic: true
  cleanupOnFail: true
  values: []
```

**Comment by kaxing** [comment] 2022-01-03 04:09
Hey @LukasAuerbeck, thanks for _helmfile_, I just want to see if older version with different NS can be upgrade to the latest master version.

**Comment by kaxing** [comment] 2022-01-03 04:30
Validation - **PASSED**

User can now install longhorn components into customized namespace with helm both version 2 and 3.

Additionally, with helmfile I am able to upgrade from older v1.2.2 to master version mock as v1.2.3 under configured namespace:
```yaml
---
releases:
- name: longhorn
  namespace: longhorn-test
  chart: ./longhorn/chart
  version: 1.2.3
  atomic: true
  cleanupOnFail: true
  values:
    - ./longhorn/chart/values.yaml
```

**Closed by kaxing** 2022-01-03 04:30 UTC
Labels: kind/bug, area/deployment, backport-needed/1.2.4, backport-needed/1.1.4

**Comment by angelakis** [comment] 2022-01-31 14:51
> Agree, this should be fixed because we already have that configuration in values.yaml.
> 
> Also, thanks for your info about longhorn is working fine in a different namespace than longhorn-system, but as @jenting mentioned other issues needed to clarify before we can make sure longhorn working w/o any errors in non longhorn-system namespace.
> 
> cc @khushboo-rancher @kaxing

I can confirm that Longhorn seems to work alright in a namespace different than longhorn-system (observed in multiple clusters, longhorn deployed with Helm3 in `longhorn` namespace). However, I am worried because of the warning in the README and want to figure out what issues are needed to be clarified in order to make sure that everything is functioning correctly in different namespaces. Is there an issue or a document tracking the possible problems? Should, we try to move the installations in the `longhorn-system` namespace?

Sorry for hijacking this issue, I can try creating a new one if there is no issue such as the one I'm looking for.

**Comment by jenting** [comment] 2022-02-09 08:57
> > Agree, this should be fixed because we already have that configuration in values.yaml.
> > Also, thanks for your info about longhorn is working fine in a different namespace than longhorn-system, but as @jenting mentioned other issues needed to clarify before we can make sure longhorn working w/o any errors in non longhorn-system namespace.
> > cc @khushboo-rancher @kaxing
> 
> I can confirm that Longhorn seems to work alright in a namespace different than longhorn-system (observed in multiple clusters, longhorn deployed with Helm3 in `longhorn` namespace). However, I am worried because of the warning in the README and want to figure out what issues are needed to be clarified in order to make sure that everything is functioning correctly in different namespaces. Is there an issue or a document tracking the possible problems? Should, we try to move the installations in the `longhorn-system` namespace?
> 
> Sorry for hijacking this issue, I can try creating a new one if there is no issue such as the one I'm looking for.

We have some code is hard-code with `longhorn-system` namespace.
- https://github.com/longhorn/longhorn-manager/blob/840ae441597ac6af0904946db7d40916d959f9f8/controller/uninstall_controller.go#L186
- https://github.com/longhorn/longhorn-manager/blob/840ae441597ac6af0904946db7d40916d959f9f8/manager/kubernetes.go#L53

Therefore, there are probably some functions not working as expected if longhorn is not installed in the `longhorn-system` namespace.

Ref issue https://github.com/longhorn/longhorn/issues/2034
