### ISSUE TITLE
[BUG] Chart v1.6.0-rc2 is not synced between longhorn/longhorn and longhorn/charts

### ISSUE THREAD

**Issue by FrankYang0529** [longhorn/longhorn#7743] opened 2024-01-22 03:45 UTC
## Describe the bug

In [longhorn/longhorn v1.6.0-rc2](https://github.com/longhorn/longhorn/tree/v1.6.0-rc2/chart/templates): there is priorityclass.yaml and servicemonitor.yaml.

In [longhorn/charts v1.6.x](https://github.com/longhorn/charts/tree/v1.6.x/charts/longhorn/templates): these two files are not in it.

## Expected behavior

Chart files should be synced between two folder.

## Environment

 - Longhorn version: v1.6.0-rc2

**Comment by innobead** [comment] 2024-01-22 05:40
The issue is the newly added files were not included in the automatically merged PR for RC2 at https://github.com/longhorn/charts/pull/139.

That has been fixed in the [PR](https://github.com/innobead/renote/commit/d8b6f6b647974d050bb80956f8da9b60dff37d5c) of the tool, which we use in our automatic release at https://github.com/longhorn/release

**Comment by innobead** [comment] 2024-01-22 05:42
@chriscchien Please help check whether the built-in priority class and service monitor will be created correctly in https://github.com/longhorn/charts/tree/v1.6.x. Thanks. 

cc @longhorn/qa

**Closed** 2024-01-22 07:50 UTC
Labels: kind/bug
