### ISSUE TITLE
[Question]Does Longhorn support the use of Aliyun S3 storage as a backup target? How should it be configured?

### ISSUE THREAD

**Issue by xfrogcn** [longhorn/longhorn#1552] opened 2020-07-06 15:43 UTC
Does Longhorn support the use of Aliyun S3 storage as a backup target? How should it be configured?

**Comment by yasker** [comment] 2020-07-07 17:24
Yes, see https://longhorn.io/docs/1.0.0/snapshots-and-backups/backup-and-restore/set-backup-target/#set-up-a-local-testing-backupstore for example (it applies to all S3 storages).

**Comment by gerwim** [comment] 2020-07-08 14:54
However, I noticed you don't need to encode the `AWS_ENDPOINT` in base64. Doing so will result in an error.

**Comment by yasker** [comment] 2020-07-08 15:47
@gerwim For AWS, yes you don't need to encode `AWS_ENDPOINT`. It's only necessary for other vendors.

**Comment by gerwim** [comment] 2020-07-08 16:05
@yasker That's not the case. I'm using Backblaze B2 (S3 compatible) and I do not need to encode. When I do encode, I get an error (it's not decoding the string, so it's trying to connect to something like `aHR0cHM6Ly9zMy51cy13ZXN0LTAwMS5iYWNrYmxhemViMi5jb20=` instead of `https://s3.us-west-001.backblazeb2.com`).

**Comment by xfrogcn** [comment] 2020-07-09 06:03
@yasker 
I create a secret with name ali-backup-s3 in the longhorn-system namespace, the secret inclue fllow content:
  AWS_ACCESS_KEY_ID: ***
  AWS_ENDPOINTS: aHR0cHM6Ly9vc3MtY24tc2hlbnpoZW4uYWxpeXVuY3MuY29t  // https://oss-cn-shenzhen.aliyuncs.com
  AWS_SECRET_ACCESS_KEY: *** 
And then, I config longhorn backup target with: 
s3://xkj-backup@shenzhen/test-env/

goto the longhorn ui Backup tab, I get fllow error:
`error listing backups: error listing backup volumes: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.0.0/longhorn [backup ls --volume-only s3://xkj-backup@shenzhen/test-env/], output failed to list objects with param: { Bucket: "xkj-backup", Delimiter: "/", Prefix: "test-env/" } response: { } error: AWS Error: SecondLevelDomainForbidden Please use virtual hosted style to access. <nil> 403 5F06B3129F0653363227DB52 , stderr, time="2020-07-09T06:02:58Z" level=error msg="Fail to list s3: failed to list objects with param: {\n Bucket: \"xkj-backup\",\n Delimiter: \"/\",\n Prefix: \"test-env/\"\n} response: {\n\n} error: AWS Error: SecondLevelDomainForbidden Please use virtual hosted style to access. <nil>\n403 5F06B3129F0653363227DB52\n" pkg=s3 time="2020-07-09T06:02:58Z" level=error msg="failed to list objects with param: {\n Bucket: \"xkj-backup\",\n Delimiter: \"/\",\n Prefix: \"test-env/\"\n} response: {\n\n} error: AWS Error: SecondLevelDomainForbidden Please use virtual hosted style to access. <nil>\n403 5F06B3129F0653363227DB52\n" , error exit status 1`

**Comment by yasker** [comment] 2020-07-09 17:03
Looks like it's an issue caused by virtual host vs path style of access, e.g. https://github.com/rclone/rclone/issues/2401 . More information can be found by googling `Please use virtual hosted style to access`.

Seems AWS is deprecating the path style as well (https://aws.amazon.com/blogs/aws/amazon-s3-path-deprecation-plan-the-rest-of-the-story/ ). We need to add the support of virtual host style.

**Comment by shuo-wu** [comment] 2020-07-14 09:33
## Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?

* [ ] Is the backend code merged (Manager, Engine, Instance Manager, BackupStore etc)?
The PR is at
https://github.com/longhorn/backupstore/pull/51
https://github.com/longhorn/longhorn-engine/pull/516
https://github.com/longhorn/longhorn-manager/pull/627

* [x] Is the reproduce steps/test steps documented?

* [x] Which areas/issues this PR might have potential impacts on?
Area: backup
Issues: if backup related operations work fine or not with/without this option

* [x] ~~**If the fix introduces the code for backward compatibility** Has a separate issue been filed with the label `release/obsolete-compatibility`?
The compatibility issue is filed at~~

* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?
The UI issue/PR is at~~

* [ ] **if labeled: require/doc** Has the necessary document PR submitted or merged?
The Doc issue/PR is at 
https://github.com/longhorn/website/pull/165

* [x] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
The automation skeleton PR is at
The automation test case PR is at~~

* [x] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by shuo-wu** [comment] 2020-07-14 09:49
Manual test1:
1. Create an OSS bucket in Alibaba Cloud(Aliyun)
2. Create a secret without `VIRTUAL_HOSTED_STYLE` for the OSS bucket. (If you haven't got an Alibaba cloud account, you can ask me for an existing OSS bucket.)
3. Set backup target and the secret in Longhorn UI.
4. Try to list backup. Then the error `error: AWS Error: SecondLevelDomainForbidden Please use virtual hosted style to access.` is triggered.
5. Follow the instruction in the doc PR to enable the option.
6. Backup list/create/delete/restore work fine after the configuration.

Test plan 2:
1. Create an S3 bucket in AWS.
2. Create a secret without `VIRTUAL_HOSTED_STYLE` for the S3 bucket.
3. Set backup target and the secret in Longhorn UI.
4. Verify backup list/create/delete/restore work fine without the configuration.
5. Follow the instruction in the doc PR to enable the option and update the secret.
6. Verify backup list/create/delete/restore still work fine after the configuration.

**Comment by yasker** [comment] 2020-07-14 18:05
@shuo-wu 

Wait for the #1460 to be done first.

**Comment by yasker** [comment] 2020-07-15 19:49
#1460 is merged.

**Comment by yasker** [comment] 2020-07-15 21:27
Move to merged for rc2 test. @shuo-wu Remember to update the manual test plan.

**Comment by khushboo-rancher** [comment] 2020-07-16 02:38
Verified one of the scenario with s3 in AWS

The ```list/create/delete/restore``` functionality is working fine with and without ```VIRTUAL_HOSTED_STYLE```

**Comment by shuo-wu** [comment] 2020-07-16 03:20
Notice that the virtual-hosted-style restriction doesn't work for OSS on Europe (Germany) region, which means users don't need to config `VIRTUAL_HOSTED_STYLE` if they are using OSS on EU. 
And we need to config the OSS bucket in China for the manual test 1.

**Comment by meldafrawi** [comment] 2020-07-16 18:36
Validation: PASSED Using Aliyun OSS bucket -- Manual test (1)

**Comment by meldafrawi** [comment] 2020-07-17 16:17
Running backup related integration tests with `VIRTUAL_HOSTED_STYLE = true` 
```
## Backup tests:
test_basic.py::test_backup_status_for_unavailable_replicas PASSED
test_basic.py::test_backup_block_deletion PASSED
test_basic.py::test_backup_volume_list PASSED
test_basic.py::test_backup PASSED
test_basic.py::test_backup_labels PASSED
test_basic.py::test_listing_backup_volume PASSED
test_basic.py::test_storage_class_from_backup PASSED
test_basic.py::test_dr_volume_with_last_backup_deletion PASSED
test_csi.py::test_csi_backup PASSED
test_ha.py::test_ha_backup_deletion_recovery PASSED
test_ha.py::test_restore_volume_with_invalid_backupstore PASSED
test_kubernetes.py::test_backup_kubernetes_status PASSED
test_statefulset.py::test_statefulset_backup PASSED
test_statefulset.py::test_statefulset_recurring_backup PASSED

## Restore tests
test_basic.py::test_restore_inc PASSED
test_basic.py::test_restore_inc_with_expansion PASSED
test_ha.py::test_restore_volume_with_invalid_backupstore PASSED
test_ha.py::test_all_replica_restore_failure PASSED
test_ha.py::test_single_replica_restore_failure PASSED
test_ha.py::test_dr_volume_with_restore_command_error PASSED
test_node.py::test_replica_scheduler_rebuild_restore_is_too_big  PASSED
test_statefulset.py::test_statefulset_restore PASSED


### Failed testss
test_basic.py::test_backup_metadata_deletion FAILED
test_basic.py::test_deleting_backup_volume FAILED

```

**Comment by yasker** [comment] 2020-07-17 16:30
`test_backup_metadata_deletion` seems failing in our latest nightly test: https://ci.longhorn.io/job/longhorn-tests/20/

So does `test_deleting_backup_volume` in https://jenkins.int.rancher.io/job/longhorn-tests/514/

**Comment by meldafrawi** [comment] 2020-07-17 16:51
Submitted issues to track failed tests
- longhorn/longhorn#1603 for test_backup_metadata_deletion
- longhorn/longhorn#1604 for test_deleting_backup_volume

**Comment by meldafrawi** [comment] 2020-07-17 18:01
Validation: **PASSED**

**Closed by meldafrawi** 2020-07-17 18:01 UTC
Labels: area/engine, area/manager, enhancement, highlight, priority/2, require/doc
