### ISSUE TITLE
[BUG] when volume degraded and rebuild, the filesystem in every mounted pod were read-only 

### ISSUE THREAD

**Issue by zshi456** [longhorn/longhorn#1500] opened 2020-06-17 02:30 UTC
**Describe the bug**
When I did a performance test for Minio，some longhorn volumes are degraded and rebuilded，stop the test，after all volumes rebuild finished，all minio pod log error

**Expected behavior**
Expected all minio work normal

**Log**
![image](https://user-images.githubusercontent.com/16299136/84848091-194f7c80-b085-11ea-8757-8b31f836f5a5.png)
![image](https://user-images.githubusercontent.com/16299136/84848369-93800100-b085-11ea-8ab3-f1dfa5c70c08.png)

**Environment:**
 - Longhorn version:0.8.1
 - Kubernetes version:1.14.5
 - Node OS type and version:centos7.4，xfs

**Comment by shuo-wu** [comment] 2020-06-17 13:31
There is one (relative) common case that leads to the filesystem becoming ReadOnly:
1. The volume (engine) gets crashed unexpectedly.
2. The volume cannot be recovered automatically. Or the volume is recovered automatically(Reattach and remount) but the related workload is not restarted:

Here is the doc. I am not sure if the error you report is related to this:
https://longhorn.io/docs/1.0.0/high-availability/recover-volume/#requirements

**Comment by runningman84** [comment] 2020-06-18 17:51
I have also found out that from time to time filesytems in longhorn gets mounted ReadOnly due to lnode reboots or some other longhorn problems... it would be cool if longhorn would detect such problem and fix the problem by killing the corresponding pod.

**Comment by shuo-wu** [comment] 2020-06-18 19:55
Killing the pod is too aggressive. Maybe Longhorn can record an event as a warning if the case is detected.

**Comment by runningman84** [comment] 2020-06-18 20:25
A corresponding Prometheus metric would also help a lot

**Comment by yasker** [comment] 2020-06-23 19:04
@runningman84 Prometheus metrics are tracking at #1180 (just realized you raised that issue as well 😄 )

As @shuo-wu said, we do try to cover from the read-only situation. But there are limitations so far as you can see in the [doc](https://longhorn.io/docs/1.0.0/high-availability/recover-volume/#requirements) 
1. You need to use `ext4` as the filesystem inside the pod
2. You need to setup liveness check for the pod in order to get it restarted automatically.

IMO, killing the pod is a bit too aggressive. If you've configured the liveness check, Kubernetes should restart the pod automatically if the read-only mount happened.

Btw, normally node reboot shouldn't cause the read-only mount to happen since the engine is running on the same node as the workload. Both of them will be recreated and it should be fine after the node is back up.

Read-only mount more likely happened when the CPU or network cannot satisfy the speed required by the storage. We've added `GuaranteedEngineCPU` option in v1.0.0 to help with the CPU starving issue. See [here](https://longhorn.io/docs/1.0.0/references/settings/#guaranteed-engine-cpu) for details.

**Comment by sergiocharpineljr** [comment] 2020-08-28 17:05
I'm also experiencing this issue with v 1.0.1. My cluster doesn't seem to have any resource pressure. 

After the problem, longhorns devices seems to be mounted twice, ro and rw mounts.

```
# mount | grep aadc81dc
/dev/longhorn/pvc-aadc81dc-38e6-403a-be00-1f9c1373c122 on /var/lib/kubelet/pods/54e931ec-f854-4b57-bcff-af725eafa932/volumes/kubernetes.io~csi/pvc-aadc81dc-38e6-403a-be00-1f9c1373c122/mount type ext4 (ro,relatime)
/dev/longhorn/pvc-aadc81dc-38e6-403a-be00-1f9c1373c122 on /var/lib/kubelet/pods/54e931ec-f854-4b57-bcff-af725eafa932/volumes/kubernetes.io~csi/pvc-aadc81dc-38e6-403a-be00-1f9c1373c122/mount type ext4 (rw,relatime)
```

I can see some timeouts and some errors:
```
2020-08-27T03:32:52.223419922Z [pvc-de5f204e-3f2a-41c5-b15b-588c42bbd654-e-4afeeac9] time="2020-08-27T03:32:52Z" level=error msg="Write timeout on replica 10.42.1.33:10001 seq= 29908 size= 4 (kB)"
2020-08-27T03:32:52.223462799Z time="2020-08-27T03:32:52Z" level=error msg="Retry  1 on replica 10.42.1.33:10001 seq= 29908 size= 4 (kB)"
...
2020-08-28T07:02:37.290019768Z tgtd: bs_longhorn_request(91) fail to write at 13022289920 for 28672
2020-08-28T07:02:37.290191901Z tgtd: bs_longhorn_request(150) io error 0x560b35a664e0 2a -14 28672 13022289920, Success
2020-08-28T07:02:37.290199347Z response_process: Receive error for response 3 of seq 599217
2020-08-28T07:02:37.290205772Z response_process: Receive error for response 3 of seq 599209
2020-08-28T07:02:37.290211984Z response_process: Receive error for response 3 of seq 599212
2020-08-28T07:02:37.290218135Z tgtd: bs_longhorn_request(91) fail to write at 12884910080 for 4096
2020-08-28T07:02:37.290224225Z tgtd: bs_longhorn_request(150) io error 0x560b359ae400 2a -14 4096 12884910080, Success
2020-08-28T07:02:37.290230436Z response_process: Receive error for response 3 of seq 599205
2020-08-28T07:02:37.290245026Z tgtd: bs_longhorn_request(91) fail to write at 13019717632 for 4096
2020-08-28T07:02:37.290253088Z response_process: Receive error for response 3 of seq 599211
2020-08-28T07:02:37.290259400Z tgtd: bs_longhorn_request(150) io error 0x560b35a3e7a0 2a -14 4096 13019717632, Success
2020-08-28T07:02:37.290265778Z response_process: Receive error for response 3 of seq 599219
2020-08-28T07:02:37.290272196Z tgtd: bs_longhorn_request(91) fail to write at 12885131264 for 4096
2020-08-28T07:02:37.290278494Z tgtd: bs_longhorn_request(150) io error 0x560b359aec40 2a -14 4096 12885131264, Success
2020-08-28T07:02:37.290284801Z tgtd: bs_longhorn_request(91) fail to write at 12885098496 for 4096
2020-08-28T07:02:37.290290997Z tgtd: bs_longhorn_request(150) io error 0x560b359ae980 2a -14 4096 12885098496, Success
2020-08-28T07:02:37.290297229Z tgtd: bs_longhorn_request(91) fail to write at 12885274624 for 49152
2020-08-28T07:02:37.290303584Z tgtd: bs_longhorn_request(150) io error 0x560b359b7980 2a -14 49152 12885274624, Success
2020-08-28T07:02:37.290309832Z tgtd: bs_longhorn_request(91) fail to write at 13019234304 for 4096
2020-08-28T07:02:37.290316049Z tgtd: bs_longhorn_request(150) io error 0x560b359c26c0 2a -14 4096 13019234304, Success
..
2020-08-28T07:02:44.676124473Z time="2020-08-28T07:02:36Z" level=info msg="Ignore set replica tcp://10.42.1.33:10030 to mode ERR due to it's ERR"
2020-08-28T07:02:44.676136754Z time="2020-08-28T07:02:36Z" level=error msg="Setting replica tcp://10.42.0.167:10045 to ERR due to: r/w timeout"
2020-08-28T07:02:44.676148963Z time="2020-08-28T07:02:36Z" level=info msg="Ignore set replica tcp://10.42.0.167:10045 to mode ERR due to it's ERR"
2020-08-28T07:02:44.676161355Z time="2020-08-28T07:02:36Z" level=error msg="I/O error: tcp://10.42.1.33:10030: r/w timeout; tcp://10.42.0.167:10045: r/w timeout"
..
2020-08-28T07:02:44.677091317Z time="2020-08-28T07:02:36Z" level=error msg="I/O error: No backend available"
2020-08-28T07:02:44.677103559Z time="2020-08-28T07:02:36Z" level=error msg="I/O error: No backend available"
2020-08-28T07:02:44.677115727Z time="2020-08-28T07:02:36Z" level=error msg="I/O error: No backend available"
```

But in the end it gets synchronized:
```
2020-08-28T09:20:09.600157775Z [pvc-aadc81dc-38e6-403a-be00-1f9c1373c122-e-d7155fd2] time="2020-08-28T09:20:09Z" level=info msg="Get backend tcp://10.42.0.167:10045 revision counter 4870313"
2020-08-28T09:20:09.600229889Z time="2020-08-28T09:20:09Z" level=info msg="Set revision counter of 10.42.1.33:10030 to : 4870313"
2020-08-28T09:20:09.608348372Z [pvc-aadc81dc-38e6-403a-be00-1f9c1373c122-e-d7155fd2] time="2020-08-28T09:20:09Z" level=info msg="Set backend tcp://10.42.1.33:10030 revision counter to 4870313"
2020-08-28T09:20:09.608410556Z time="2020-08-28T09:20:09Z" level=info msg="WO replica tcp://10.42.1.33:10030's chain verified, update mode to RW"
2020-08-28T09:20:09.610017710Z [pvc-aadc81dc-38e6-403a-be00-1f9c1373c122-e-d7155fd2] time="2020-08-28T09:20:09Z" level=info msg="Set replica tcp://10.42.1.33:10030 to mode RW"
```

livenessProbe is not a good solution for me because I've already have one for monitoring HTTP. I could create a script to acomplish both things but it would complicate things. I think longhorn should be able to recover.

**Comment by yasker** [comment] 2020-08-28 17:41
@sergiocharpineljr Yes, there was a disconnection happened. Since you said seems there is no resource pressure, so it might be caused by the temporary network outage.

The reason you saw two mounts is Longhorn tried to recover the volume so when the volume comeback, it remounted the volume back to the same location, in the hope that the workload would restart and pick up the correct mountpoint again.

Now thinking about it, maybe kill a stateful set or deployment pod would be the easier path to the recovery of the workload, compare to require the user to set the liveness probe and piling up mounts on the disk. cc @shuo-wu

**Comment by DarianAnjuhal** [comment] 2020-10-10 10:18
I have the same issue with minio. In the read-only case minio keeps running and there are missing images ocurring on the software using the minio storage. 
Mongodb and mysql crashes instantly.

Are there solutions or ideas already?

**Comment by derzufall** [comment] 2020-10-25 20:32
Having this issue as well. Always occurs when/shorty after longhorn components are automatically restarted. Our VM provider shifts VMs on a daily basis which causes the longhorn cluster components to lose quorum.
Thats why the read-only issue comes up once or twice a week.

We are already looking into other storage providers since this is a big issue for us.

**Comment by DarianAnjuhal** [comment] 2020-10-26 13:44
@derzufall Hi, its a big issue for us as well. Which storage provider do you use? And which others do you check out?

**Comment by yasker** [comment] 2020-10-27 03:49
We've switched to delete the pod (who will be recreated by Kubernetes automatically) in v1.1.0 release ( #1719). The current way of using the liveness probe indeed has quite a few shortcomings.

Btw, @derzufall there is no quorum in Longhorn. As long as there is one healthy replica, Longhorn would work. By shifting VM, you meant VMs are live migrated from one node to another? Yes, that would cause a network outage and Longhorn will likely be disconnected, but it's designed to recover automatically after. But to recover gracefully in v1.0.x, a liveness probe to restart the pod automatically is needed.

**Comment by derzufall** [comment] 2020-10-28 12:45
> Btw, @derzufall there is no quorum in Longhorn. As long as there is one healthy replica, Longhorn would work. By shifting VM, you meant VMs are live migrated from one node to another? Yes, that would cause a network outage and Longhorn will likely be disconnected, but it's designed to recover automatically after. But to recover gracefully in v1.0.x, a liveness probe to restart the pod automatically is needed.

Hey @yasker, thank you for clearing that up! Yes I meant the VMs are moved between nodes. Then the CSI workloads of longhorn might lose their leader and then the CSI pod crashes. After that we occasionally see the read-only problem. It happens about once a week that a part of workloads see a read-only filesystem. However this is a operational nightmare...

Liveness probe doesnt seem to cover this problem tho. Our gitlab instance will die if the filesystem becomes read only. Kubernetes will instantly restart, but the read-only issue keeps persisting. We have to scale the workload down to 0 and then back up again to fix this.

Hoping 1.1.0 will make sure that the system recovers automatically.

**Comment by DarianAnjuhal** [comment] 2020-10-28 15:09
Lets say the new longhorn version recovers by scaling down and up automatically and the pod comes back after couple of seconds. Can we say its stable enough to deploy a production service? We would always have downtimes x times a day ( in my case nextcloud/gitlab/..etc crashes each day)?

**Comment by yasker** [comment] 2020-10-29 22:59
@derzufall There are a few features in the upcoming v1.1.0 that should help in your live migration case:
1. the data locality feature can keep a replica always local to the workload, so even after the live migration, the workload should still have a local replica to it, then it can continue to function even with a small network outage.
2. existing replica rebuild feature should pick up the remaining replicas (which might be considered error out) and quickly rebuild them.
3. finally, if the volume still failed due to some reason, Longhorn can delete the workload pod (as long as it's controlled by a deployment or statefulset) to allow Kubernetes to recreate it, which will redo the attach/mount operations to ensure the workload will be up and running correctly with the volume.

**Comment by yasker** [comment] 2020-10-29 23:09
@DarianAnjuhal You're right. It's not the full answer since the expectation is zero downtime. In the future, we should expect the Longhorn system to tell us it's short on CPU, or memory, or network, or even disk IO. In that way, we should know the cause of any outage and find ways to mitigate it. I've filed https://github.com/longhorn/longhorn/issues/1930 to track that effort.

**Comment by unixfox** [comment] 2020-12-29 08:58
bump

**Comment by DarianAnjuhal** [comment] 2020-12-29 10:47
Hi,

thanks a lot for the new version. It makes things easier and better. Pods very often recover automatically.
But I still notice down times for couple of services.

@yasker Can I send you a new support bundle. Maybe it helps to figure out the issue?

Greetings Darian

**Comment by shuo-wu** [comment] 2021-01-13 09:12
@DarianAnjuhal Here is the doc about troubleshooting this issue, you can take a look first:
https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/

**Comment by joshimoo** [comment] 2021-01-27 18:42
Leaving a note.
@PhanLe1010 is currently investigating, using longhorn with spinning disks.
https://github.com/longhorn/longhorn/issues/2206

**Comment by ElisaMeng** [comment] 2021-02-26 22:33
I see this quite often in my hobby lab as well. I only have 1G connection and run ssd, but I have small load on the system.

**Comment by derzufall** [comment] 2021-02-27 07:33
We still have this very same issue on a regular basis. Ssds, VMs (see my answers above). Newest version with all the stuff in place that was supposed to counteract the issue, like data locality and all. It even got worse. Now when a volume goes read-only and I restart the container all replicas of the volume will be corrupt and i cannot remount any of the volumes.

Even the checksums of all replicas are identical...

We have lost a lot of data and time to this issue by now.

**Comment by ElisaMeng** [comment] 2021-02-28 22:34
@joshimoo may you share some insight about how #2206 will help? this is pretty scary problem to have data stored on longhorn. :(

**Comment by derzufall** [comment] 2021-03-08 18:56
All Volumes just dies today with this issue. We lost all our data. We are now moving to Ceph via Rook.

**Comment by joshimoo** [comment] 2021-03-08 20:00
@ElisaMeng longhorn currently doesn't support spinning disks. If you are having a different issue when not using spinning disks, can you open a new github issue for us to investigate & track.

**Comment by yasker** [comment] 2021-03-08 20:29
@derzufall Sorry to hear that. But I don't think you can lose your data even with replica issues. The volume might need to be salvage, or in the worst case, you can recover your data from single replica by following https://longhorn.io/docs/1.1.0/advanced-resources/data-recovery/export-from-replica/

**Comment by GeroL** [comment] 2022-01-03 19:45
I can reproduce that issue. The RWX volume is mounted in some pods as read-only and one pod is responsible for populating the data. If the the volume get out of sync somehow it is re-mounted as read-only and does not ever get writable until EVERY pod that mounts it is deleted at once. If there is no more pod that mounts the volume it can be mounted as writable again. That is very annoying. This happens regularly

**Comment by PhanLe1010** [comment] 2022-01-03 22:41
@GeroL 

> If the the volume gets out of sync somehow

Can you give more detail about how to trigger this condition?

Can you also provide your env info:
```
## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:
```

**Comment by GeroL** [comment] 2022-01-04 10:53
StorageClass:
```
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: longhorn-reportdata
provisioner: driver.longhorn.io
allowVolumeExpansion: true
reclaimPolicy: Retain
volumeBindingMode: Immediate
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "2880"
  fromBackup: ""
  dataLocality: "best-effort" #Data should be where its needed
  replicaAutoBalance: "least-effort" 
```

PVC:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-report-data-rep01
spec:
  accessModes:
    - ReadWriteMany 
  volumeMode: Filesystem
  resources:
    requests:
      storage: 20Gi
  storageClassName: longhorn-reportdata
```
Longhorn looses the sync regularly and re-mounts the volume as read-only.
I guess you know a way to provoke this.
The consumer pods are working as they only need to read the data.
The producer node is crashing repeatedly and does not recover.
Only way to solve this is to delete all consumer and producer deployments. 
Not just pods as they would be recreated immediately. 
I guess Longhorn can't recover from this state when the volume is still in use.

Longhorn version 1.2.2
Installed via ArgoCD using Helm
Kubernetes is microk8s 1.2.4 on 4 KVM Ubuntu 20.04 nodes (4 Cores, 16GB Ram)
Bandwidth is 2.5Gbit/s
SSD Disks

**Comment by michafn** [comment] 2022-03-08 19:58
Having the same issue using v1.2.3. We had those issues with all previous versions as well and were hoping the latest version might fix it. 

We use rancher with longhorn avv ext4 nodes. There is no pressure on any node and some volumes (especially for our sentry deployment but also for a simple postgres) keep getting mounted read only. This is indeed a nightmare since it requires attention continuously.  

I also observed ext4 errors on the nodes which seem to be related, however can't say if this is potentially an iscsi issue which causes longhorn to fail or vice versa.
I'd love to use longhorn in production but this is most concerning. Any thoughts on that?

**Comment by voarsh2** [comment] 2022-04-05 17:37
Am I missing something?
I am often running into read-only file system for volumes (I can't say the cause while typing this, but I would assume it's around rebuilding replica's).
I have one app running 10 volumes and I am not sure which one is read-only.... but Longhorn has fixed this state.... so I must down the workload to 0 and then increase it again....

**Comment by PhanLe1010** [comment] 2022-04-06 23:37
@voarsh2 Have you take a look at this doc https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/ ?

You can setup a liveness probe in the pod to know which pod has a volume that is in read-only state.

**Comment by voarsh2** [comment] 2022-04-07 22:07
I've tried to look for a health check that can help me kill a pod if it's read only, but I could not find an example online.
Longhorn is setup to kill deployments and statefulsets in the event of an unexpected detachment... But this issue still happens frequently....

Regards,
Reese

**Comment by PhanLe1010** [comment] 2022-04-08 23:23
@voarsh2, I think are 2 different topic here:
1. Why the volumes get unexpected detachment frequently. There are a few causes for this problem. Could you check your cluster: https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/
2. Why Longhorn doesn't kill the deployment pods? Can you send us a support bundle when you hit this case again?

**Comment by voarsh2** [comment] 2022-04-09 21:11
> @voarsh2, I think are 2 different topic here:
> 
> 1. Why the volumes get unexpected detachment frequently. There are a few causes for this problem. Could you check your cluster: https://longhorn.io/kb/troubleshooting-volume-readonly-or-io-error/
Probably because some replicas become faulted... 

> 2. Why Longhorn doesn't kill the deployment pods? Can you send us a support bundle when you hit this case again?
Not sure, I know one volume was attached to more than one deployment that is separate, not sure if that makes a difference.

Generating a support bundle is just showing me "generating" and not seemingly finishing for a while.
If I get one I'll update.

**Comment by innobead** [comment] 2023-09-14 05:01
There seems no feedback from the last conversation. We can focus on https://github.com/longhorn/longhorn/issues/6386 instead. 

cc @longhorn/dev

**Closed by innobead** 2023-09-14 05:01 UTC
Labels: kind/enhancement, investigation-needed, area/performance, area/stability
