### ISSUE TITLE
[BUG] degraded RWX performance

### ISSUE THREAD

**Issue by smalchow** [longhorn/longhorn#2584] opened 2021-05-11 13:07 UTC
**Longhorn RWX performance very bad**

we installed a new rancher cluster with longhorn and tested downloads within 3 containers using one RWX volume.
The bottleneck is obviously the RWX volume and allows for 200KB/s.
In a read-write-one volume we can do the same thing at 100MB/s

This issue happens on clusters on Hetzner Cloud (german hoster) and on a Cluster on AWS

**To Reproduce**
1. Deploy daemon set with RWX volume
2. go into volumes mount point on any container
3. download large iso file
4. only 200KB/s

**Expected behavior**
The performance when writing into the RWX volume should be similar to read-write-one, maybe not 100% as fat, but in the same ballpark

**Log**
no relevant output

You can also attach a *Support Bundle* here. You can generate a Support Bundle using the link at the footer of the Longhorn UI.

**Environment:**
 - Longhorn version: 1.1.1
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Catalog
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: ubuntu 20.04
   - CPU per node: 4
   - Memory per node: 16GB
   - Disk type(e.g. SSD/NVMe): i would assume SSD
   - Network bandwidth between the nodes: 1Gbit
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Hetzner Cloud (probably KVM)
 - Number of Longhorn volumes in the cluster: one RWX volume

**Additional context**
Here is a screenshot with "dd" into the disks, where the RWX volume is mounted to "/tmp"

![image](https://user-images.githubusercontent.com/8308427/117820186-93bf5700-b26a-11eb-979e-e388cddc3c67.png)

**Comment by smalchow** [comment] 2021-05-11 13:18
seems to be related to

https://github.com/longhorn/longhorn/issues/2528

**Comment by joshimoo** [comment] 2021-05-11 14:18
I did a quick test on my dev cluster, and I can verify that this is an issue.
I did a quick test with dd with different block size, we can see that with bigger block sizes the performance is as expected.

I am guessing that this might be related to a lower nfs write/read size, since we are running in sync mode.
So if there is a high io latency, with tiny blocks that could explain this issue.

Will test with an older share-manager image next.

```
root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero
^C114+0 records in
114+0 records out
58368 bytes (58 kB, 57 KiB) copied, 2.0433 s, 28.6 kB/s

root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero status=progress bs=4K
491520 bytes (492 kB, 480 KiB) copied, 2.02101 s, 243 kB/s^C
149+0 records in
149+0 records out
610304 bytes (610 kB, 596 KiB) copied, 2.56178 s, 238 kB/s

root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero status=progress bs=16K
2392064 bytes (2.4 MB, 2.3 MiB) copied, 2.00193 s, 1.2 MB/s^C
194+0 records in
194+0 records out
3178496 bytes (3.2 MB, 3.0 MiB) copied, 2.73393 s, 1.2 MB/s

root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero status=progress bs=32K
2457600 bytes (2.5 MB, 2.3 MiB) copied, 2.02244 s, 1.2 MB/s^C
121+0 records in
121+0 records out
3964928 bytes (4.0 MB, 3.8 MiB) copied, 2.72449 s, 1.5 MB/s

root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero status=progress bs=256K
15728640 bytes (16 MB, 15 MiB) copied, 2.04216 s, 7.7 MB/s ^C
62+0 records in
62+0 records out
16252928 bytes (16 MB, 16 MiB) copied, 2.17792 s, 7.5 MB/s

root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero status=progress bs=1M  
26214400 bytes (26 MB, 25 MiB) copied, 2.03757 s, 12.9 MB/s^C
31+0 records in
31+0 records out
32505856 bytes (33 MB, 31 MiB) copied, 2.66676 s, 12.2 MB/s

root@rwx-speed-test-778f5c5bff-fthrv:/# dd if=/dev/zero of=/mnt/rwx/zero status=progress bs=4M
58720256 bytes (59 MB, 56 MiB) copied, 3.01373 s, 19.5 MB/s^C
17+0 records in
17+0 records out
71303168 bytes (71 MB, 68 MiB) copied, 3.76082 s, 19.0 MB/s
```

**Comment by innobead** [comment] 2021-05-26 01:18
This is a duplicate of #2549. We will tackle this together with #2549.

**Comment by wargamez** [comment] 2021-06-27 13:32
This is super important to fix imho, I'm sad it has been moved to 1.3.0... Are there any workarounds we can do in the meantime?

**Comment by fascinatedcow** [comment] 2021-07-07 18:43
@wargamez This appears to be a workaround. Seems a good bit slower than RWO but lots faster than native RWX:
https://github.com/longhorn/longhorn/issues/2549#issuecomment-829265306

**Comment by innobead** [comment] 2021-08-24 04:22
Closing the duplicated bug, and we can track #2549.

**Closed by innobead** 2021-08-24 04:22 UTC
Labels: kind/bug, priority/1, require/automation-e2e, require/manual-test-plan, area/rwx, duplicated
