### ISSUE TITLE
[BUG] Test case `test_node_metrics` fails in Talos due to missing cpu/memory usage metrics

### ISSUE THREAD

**Issue by yangchiu** [longhorn/longhorn#9885] opened 2024-12-02 11:47 UTC
## Describe the bug

Setting up Talos v1.8.3 by [the refined terraform script](https://github.com/longhorn/longhorn-tests/pull/2172) and installing Longhorn. Test case `test_node_metrics` fails because the following metrics are not found:

```
longhorn_node_cpu_usage_millicpu
longhorn_node_memory_usage_bytes
```

https://ci.longhorn.io/job/public/job/master/job/talos/job/amd64/job/longhorn-tests-talos-amd64/28/testReport/junit/

## To Reproduce

Run test case `test_node_metrics`.

## Environment

 - Longhorn version: master-head
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.31.1
   - Number of control plane nodes in the cluster: 1
   - Number of worker nodes in the cluster: 3 
 - Node config
   - OS type and version: talos v1.8.3
   - Kernel version:
   - CPU per node:
   - Memory per node:
   - Disk type (e.g. SSD/NVMe/HDD):
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by c3y1huang** [comment] 2024-12-04 02:49
```
2024-12-02T08:17:07.596184133Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*InstanceManagerCollector).collectActualUsage" file="instance_manager_collector.go:147" collector=instance_manager error="the server could not find the requested resource (get pods.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.596844557Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*NodeCollector).collectNodeActualCPUMemoryUsage" file="node_collector.go:249" collector=node error="the server could not find the requested resource (get nodes.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.596858092Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*ManagerCollector).Collect" file="manager_collector.go:85" collector=manager error="the server could not find the requested resource (get pods.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.633247524Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*ManagerCollector).Collect" file="manager_collector.go:85" collector=manager error="the server could not find the requested resource (get pods.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.633366345Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*NodeCollector).collectNodeActualCPUMemoryUsage" file="node_collector.go:249" collector=node error="the server could not find the requested resource (get nodes.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.633753061Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*InstanceManagerCollector).collectActualUsage" file="instance_manager_collector.go:147" collector=instance_manager error="the server could not find the requested resource (get pods.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.666223431Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*NodeCollector).collectNodeActualCPUMemoryUsage" file="node_collector.go:249" collector=node error="the server could not find the requested resource (get nodes.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.666411118Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*ManagerCollector).Collect" file="manager_collector.go:85" collector=manager error="the server could not find the requested resource (get pods.metrics.k8s.io)" node=ip-10-0-1-219
2024-12-02T08:17:07.666785480Z time="2024-12-02T08:17:07Z" level=warning msg="Error during scrape" func="metrics_collector.(*InstanceManagerCollector).collectActualUsage" file="instance_manager_collector.go:147" collector=instance_manager error="the server could not find the requested resource (get pods.metrics.k8s.io)" node=ip-10-0-1-219
```

**Comment by c3y1huang** [comment] 2024-12-04 02:56
**Cause:** Missing metric server in the Talos Linux cluster.
**Fix:** Install the metric server. See: https://www.talos.dev/v1.8/kubernetes-guides/configuration/deploy-metrics-server/

Closing this issue as it is not a bug.

cc @derekbit @yangchiu

**Closed by c3y1huang** 2024-12-04 02:56 UTC
Labels: kind/bug, reproduce/always, priority/1, kind/regression, area/monitoring, severity/2, area/distro-platform-arch

**Comment by c3y1huang** [comment] 2024-12-04 04:31
Additional issue ref: https://github.com/longhorn/longhorn/issues/9764
