### ISSUE TITLE
[BUG] longhorn-manager seems to crash rpm-DB on the host by continously calling rpm -q ...

### ISSUE THREAD

**Issue by JohnnyAW** [longhorn/longhorn#10019] opened 2024-12-19 11:31 UTC
## Describe the bug

we have continiously problems with our rpm-DB after upgrading to longhorn 1.7.2. After some time we have 2000-3000 processes waiting for rpm where most of them coming from longhorn-manager. I see a commit 5 month ago: 46bcabc, where syncPackagesInstalled was added to node_controller.go, what seems to cause the problems on our hosts

## Environment

 - Longhorn version: 1.7.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): helm
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3S, v1.30.6+k3s1
   - Number of control plane nodes in the cluster: 3
   - Number of worker nodes in the cluster: 14
 - Node config
   - OS type and version: Rocky 8
   - Kernel version: 4.18.0-553.30.1.el8_10.x86_64
   - CPU per node: 4-12
   - Memory per node: 8 - 70
   - Disk type (e.g. SSD/NVMe/HDD): ssd
   - Network bandwidth between the nodes (Gbps):
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster: 20-30

**Comment by derekbit** [comment] 2024-12-19 11:34
`After some time we have 2000-3000 processes waiting for rpm where most of them coming from longhorn-manager.` 
Can the process hang? @mantissahz @COLDTURNIP?

**Comment by JohnnyAW** [comment] 2024-12-19 11:40
![RPMs](https://github.com/user-attachments/assets/d0873c91-2940-4c1e-b279-0c2a7bf22650)

**Comment by JohnnyAW** [comment] 2024-12-19 11:41
@derekbit I attached a screenshot of waiting processes

**Comment by derekbit** [comment] 2024-12-19 11:42
Yes, but this is quite weird. Why does `rqm -q` hang? Anyway, we will investigate and improve it.

**Comment by derekbit** [comment] 2024-12-19 11:48
`rpm -q wget...` this seems the first command hang in the host. Can you check why it is stuck?

**Comment by JohnnyAW** [comment] 2024-12-19 11:53
not right now, I need to wait for next time processes hanging and provide more infos

**Comment by JohnnyAW** [comment] 2024-12-19 12:00
nvm. I got another weird problem on one of the hosts:
![grafik](https://github.com/user-attachments/assets/32cd6c12-66ea-4dd0-9d15-8d42447744ef)

"rpm -q nfs-utils" is running at 100% CPU right now

**Comment by derekbit** [comment] 2024-12-19 12:08
I think it is due to rpm's issue. Can you check why rpm consumes high CPU usage on your host?
What Longhorn can do is to find an alternative.

**Comment by JohnnyAW** [comment] 2024-12-19 14:21
I couldn't find any exact reason, why the process used 100% CPU. After killing the process I found this in longhorn-manager logs:

> time="2024-12-19T12:35:56Z" level=debug msg="Package device-mapper is not found in node xxx" func="controller.(*NodeController).syncPackagesInstalled" file="node_controller.go:997" controller=longhorn-node error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/3013255/ns/mnt --net=/host/proc/3013255/ns/net rpm -q device-mapper], output , stderr : signal: killed" node=xxx
> time="2024-12-19T12:35:56Z" level=debug msg="Package nfs-utils is not found in node xxx" func="controller.(*NodeController).syncPackagesInstalled" file="node_controller.go:997" controller=longhorn-node error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/3013255/ns/mnt --net=/host/proc/3013255/ns/net rpm -q nfs-utils], output package nfs-utils is not installed\n, stderr error: rpmdb: BDB0113 Thread/process 667765/140606332983168 failed: BDB1507 Thread died in Berkeley DB library\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery\nerror: cannot open Packages index using db5 -  (-30973)\nerror: cannot open Packages database in /var/lib/rpm\nerror: rpmdb: BDB0113 Thread/process 667765/140606332983168 failed: BDB1507 Thread died in Berkeley DB library\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery\nerror: cannot open Packages index using db5 -  (-30973)\nerror: cannot open Packages database in /var/lib/rpm\n: exit status 1" node=xxx
> 
> time="2024-12-19T12:35:56Z" level=debug msg="Package iscsi-initiator-utils is not found in node xxx" func="controller.(*NodeController).syncPackagesInstalled" file="node_controller.go:997" controller=longhorn-node error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/3013255/ns/mnt --net=/host/proc/3013255/ns/net rpm -q iscsi-initiator-utils], output package iscsi-initiator-utils is not installed\n, stderr error: rpmdb: BDB0113 Thread/process 667765/140606332983168 failed: BDB1507 Thread died in Berkeley DB library\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery\nerror: cannot open Packages index using db5 -  (-30973)\nerror: cannot open Packages database in /var/lib/rpm\nerror: rpmdb: BDB0113 Thread/process 667765/140606332983168 failed: BDB1507 Thread died in Berkeley DB library\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery\nerror: cannot open Packages index using db5 -  (-30973)\nerror: cannot open Packages database in /var/lib/rpm\n: exit status 1" node=xxx
> 
> time="2024-12-19T12:35:56Z" level=debug msg="Package device-mapper is not found in node xxx" func="controller.(*NodeController).syncPackagesInstalled" file="node_controller.go:997" controller=longhorn-node error="failed to execute: /usr/bin/nsenter [nsenter --mount=/host/proc/3013255/ns/mnt --net=/host/proc/3013255/ns/net rpm -q device-mapper], output package device-mapper is not installed\n, stderr error: rpmdb: BDB0113 Thread/process 667765/140606332983168 failed: BDB1507 Thread died in Berkeley DB library\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery\nerror: cannot open Packages index using db5 -  (-30973)\nerror: cannot open Packages database in /var/lib/rpm\nerror: rpmdb: BDB0113 Thread/process 667765/140606332983168 failed: BDB1507 Thread died in Berkeley DB library\nerror: db5 error(-30973) from dbenv->failchk: BDB0087 DB_RUNRECOVERY: Fatal error, run database recovery\nerror: cannot open Packages index using db5 -  (-30973)\nerror: cannot open Packages database in /var/lib/rpm\n: exit status 1" node=xxx

I found more errors in longhorn-manager logs, like:

> time="2024-12-19T12:21:49Z" level=debug msg="Package nfs-utils is not found in node xxx" func="controller.(*NodeController).syncPackagesInstalled" file="node_controller.go:997" controller=longhorn-node error="timeout executing: /usr/bin/nsenter [nsenter --mount=/host/proc/3013255/ns/mnt --net=/host/proc/3013255/ns/net rpm -q nfs-utils]" node=xxx

**Comment by JohnnyAW** [comment] 2024-12-19 14:50
great, thank you

**Comment by COLDTURNIP** [comment] 2024-12-20 05:06
A way to check dependency is [what we've done for Talos](https://github.com/longhorn/longhorn-manager/blob/master/controller/node_controller.go#L1065): execute the tool we need and check their version if necessary, instead of read the package DB from the system.

**Comment by derekbit** [comment] 2024-12-23 00:35
> A way to check dependency is [what we've done for Talos](https://github.com/longhorn/longhorn-manager/blob/master/controller/node_controller.go#L1065): execute the tool we need and check their version if necessary, instead of read the package DB from the system.

@COLDTURNIP Let's use this method make it happen before v1.8.0-rc2. `command -v <bin>` might be enough. WDYT? @mantissahz 

We need to make sure it works in the OSes https://longhorn.io/docs/1.8.0/best-practices/#operating-system except for Container-Optimized OS (GKE).

**Comment by mantissahz** [comment] 2024-12-23 00:52
>@COLDTURNIP Let's use this method make it happen before v1.8.0-rc2. command -v <bin> might be enough. WDYT? @mantissahz

Agree with you.

**Comment by derekbit** [comment] 2024-12-25 04:14
@COLDTURNIP Merged. Please update the status.

**Comment by COLDTURNIP** [comment] 2024-12-25 08:05
## Test Steps ##

1. Given a Longhorn-installed cluster, make sure all necessary packages are installed on given nodes. e.g.
   ```
   $ kubectl -n longhorn-system get lhn worker-node-1 -o jsonpath='{.status.conditions[?(@.type=="RequiredPackages")]}'
   {"lastProbeTime":"","lastTransitionTime":"2024-12-24T10:11:48Z","message":"All required packages [open-iscsi cryptsetup dmsetup nfs-common] are installed","reason":"","status":"True","type":"RequiredPackages"}
   ```
2. Remove the package management tools from host node.
   - deb-based distros (e.g. Debian, Ubuntu): `sudo mv /usr/bin/dpkg{,.bkup}`
   - rpm-based distros (e.g. SUSE, RHEL, CentOS): `sudo mv /usr/bin/rpm{,.bkup}`
   - pacman-based distros (e.g. Arch, Manjaro): `sudo mv /usr/sbin/pacman{,.bkup}`
   - Gentoo: `sudo mv /usr/sbin/qlist{,.bkup}`
3. Wait a while for Longhorn Node (`lhn`) update, then check the node's `RequiredPackages` condition, it should indicate all needed packages are installed.
4. Restore the package management tools, remove any Longhorn needed package. Remove the package management tool again, Wait a while for Longhorn Node (`lhn`) update, then check the node's `RequiredPackages` condition, it should indicate the given package is missing.
5. Restore the package management tools, reinstall the missing packages, then finish the test.

**Comment by roger-ryao** [comment] 2024-12-26 07:05
**Verified on master-head 20241226**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7cd6412137171db36e06eeae82e97364558a877d
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/1b30ba25aab7ee808e6537dac34642342d84c53f


**Verified on v1.8.x-head 20241226**

- longhorn `v1.8.x-head` https://github.com/longhorn/longhorn/commit/ede8f46a75704352e33fbc45b01f14fa2770a827
- longhorn-manager `v1.8.x-head` https://github.com/longhorn/longhorn-manager/commit/4b11061e857945b7482c2a5d8b0ee12889981d8a


**The test steps**
https://github.com/longhorn/longhorn/issues/10019#issuecomment-2561700572


**Result Passed**

**Closed by roger-ryao** 2024-12-26 07:05 UTC
Labels: kind/bug, component/longhorn-manager, priority/1, require/qa-review-coverage, require/backport, backport/1.7.3

**Comment by davidhrbac** [comment] 2025-01-21 09:27
We are also affected by this bug. Our setup included the following components:  
- **dnf-automatic**  
- **kured**  
- **Longhorn**  

After further investigation and testing all possible combinations, we have determined that the RPM crash is directly related to Longhorn itself. This issue occurs exclusively on Rocky 8, while Rocky 9 remains unaffected.  

Notably, even after the recent RPM update on Rocky 8 (*rpm-4.14.3-31.el8.x86_64*), the bug persists.

**Comment by derekbit** [comment] 2025-01-21 09:41
> We are also affected by this bug. Our setup included the following components:
> 
> * **dnf-automatic**
> * **kured**
> * **Longhorn**
> 
> After further investigation and testing all possible combinations, we have determined that the RPM crash is directly related to Longhorn itself. This issue occurs exclusively on Rocky 8, while Rocky 9 remains unaffected.
> 
> Notably, even after the recent RPM update on Rocky 8 (_rpm-4.14.3-31.el8.x86_64_), the bug persists.

We will improve it in the upcoming v1.7.3 in the end of Feb.

**Comment by davidhrbac** [comment] 2025-03-30 09:50
I can confirm that in `v1.7.3`, the RPM DB crash issue is resolved.
