### ISSUE TITLE
Engine image DaemonSet will be created even if the engine image is incompatible

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#769] opened 2019-09-26 19:51 UTC
When the Longhorn system is upgraded from `v0.5.0` to `v0.6.0`, the new version engine image will be created by the new longhorn manager pod. But the old longhorn manger pods are still capable of creating DaemonSet for the new engine image object. Then something unexpected may happen. 

e.g. The engine image DaemonSet created by old longhorn manager will use the deprecated label `longhorn=engine-image` rather than the new labels `longhorn.io/component: engine-image, longhorn.io/engine-image: ei-xxxxxx`

**Comment by shuo-wu** [comment] 2019-10-02 00:48
There is no way to get the engine image version info and decide if an engine image is incompatible before deploying the related DaemonSet. This issue is unavoidable.

Now we plan to delete the engine image DaemonSet when the engine image is compatible and the labels are mismatching. It's actually a workaround and it can be removed after v0.6.x upgrade. 
The consequence of this workaround is that we cannot use the new engine image temporarily when upgrading to v0.6.x. It's acceptable.

**Comment by meldafrawi** [comment] 2019-10-02 20:34
Validation: **Failed**

Engine image DaemonSet still exists after the upgrade

> $ kubectl -n longhorn-system get engineimage --output=jsonpath="{.items[?(@.spec.image==\"longhornio/longhorn-engine:v0.6.0\")].metadata.name}" 

`ei-7c102650`

> $ kubectl describe daemonsets -n longhorn-system engine-image-ei-7c102650
```
Name:           engine-image-ei-7c102650
Selector:       longhorn.io/component=engine-image,longhorn.io/engine-image=ei-7c102650
Node-Selector:  <none>
Labels:         longhorn.io/component=engine-image
                longhorn.io/engine-image=ei-7c102650
Annotations:    deprecated.daemonset.template.generation: 1
Desired Number of Nodes Scheduled: 3
Current Number of Nodes Scheduled: 3
Number of Nodes Scheduled with Up-to-date Pods: 3
Number of Nodes Scheduled with Available Pods: 3
Number of Nodes Misscheduled: 0
Pods Status:  3 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           longhorn.io/component=engine-image
                    longhorn.io/engine-image=ei-7c102650
  Service Account:  longhorn-service-account
  Containers:
   engine-image-ei-7c102650:
    Image:      longhornio/longhorn-engine:v0.6.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/bash
    Args:
      -c
      cp /usr/local/bin/longhorn* /data/ && echo installed && trap 'rm /data/longhorn* && echo cleaned up' EXIT && sleep infinity
    Readiness:    exec [ls /data/longhorn] delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /data/ from data (rw)
  Volumes:
   data:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/rancher/longhorn/engine-binaries/longhornio-longhorn-engine-v0.6.0
    HostPathType:  
Events:
  Type    Reason            Age    From                  Message
  ----    ------            ----   ----                  -------
  Normal  SuccessfulCreate  6m41s  daemonset-controller  Created pod: engine-image-ei-7c102650-4q2vh
  Normal  SuccessfulCreate  6m41s  daemonset-controller  Created pod: engine-image-ei-7c102650-gvr6n
  Normal  SuccessfulCreate  6m41s  daemonset-controller  Created pod: engine-image-ei-7c102650-mzsgq
```

**Comment by meldafrawi** [comment] 2019-10-03 01:48
Validation: **PASSED**

Steps to test: thanks to @shuo-wu 

1- using Rancher v2.2.7, k8s 1.13.9
2- deploy longhorn v0.5.0
3- create the pv that trigger upgrade to v0.6.0 error. Create a pod with Longhorn volume and keep r/w data during upgrade.
4- try upgrade to v0.6.0, upgrade failed.
5- try to rollback to v0.5.0, rollback failed
6- delete all workloads (longhorn-driver-deployer, longhorn-manager, longhorn-post-upgrade, and longhorn-ui)
7- delete release histories of Helm
8- clean up the resources introduced by the failed v0.6.0 upgrade
9- upgrade to v0.6.1 from the charts, upgrade completed, longhorn app is in active state:
 9.1- Check the data for the pod using old Longhorn volume to see if reading/writing data works fine during the workaround. Then delete this pod and the v0.5.0 engine image
 9.2- #769 is not fixed in this version. This issue is trigger at this step:
   9.2.1- Check and record the labels of the engine image daemonset whose engine image is longhornio/longhorn-engine:v0.6.0. This is the old labels.
   9.2.2- Pick a random test case (e.g. test_volume_basic) and run it, the test will fail and the failure should be caused by func check_longhorn.
10- upgrade to v0.6.2 from the charts, upgrade completed, longhorn app is in active state.
 10.1- #769 is fixed in this version. Re-check the engine image daemonset whose engine image is longhornio/longhorn-engine:v0.6.0. You will find that the daemonset is re-created and its labels are different from the old labels.
11- Run integration test. All integration tests should succeed (edited)

**Closed** 2019-10-03 01:49 UTC
Labels: area/manager, bug
