### ISSUE TITLE
[BUG] Since 1.4.0 RWX volume failing regularly

### ISSUE THREAD

**Issue by tbertenshaw** [longhorn/longhorn#5224] opened 2023-01-06 14:49 UTC
## Describe the bug (🐛 if you encounter this issue)

As per #5183 and work with @derekbit. 

If more than one pod utilising the RWX volume (which is kind of the purpose of it 😄 ) the `share-manager` pod regularly restarts every few minutes resulting in errors from the consuming pods.

This is an existing volume created some time back and updated regularly to latest fixes.

The changes made last were

- upgrade longhorn to 1.4.0
- upgrade aks to 1.25.2 (using the create new nodepool method. (which have used before successfully))

## Log or Support bundle
[supportbundle_cf947ccc-9d7e-490f-8df5-f22db6f413f7_2023-01-06T14-28-35Z.zip](https://github.com/longhorn/longhorn/files/10360826/supportbundle_cf947ccc-9d7e-490f-8df5-f22db6f413f7_2023-01-06T14-28-35Z.zip)
Logs using the latest patch from @derekbit 
[longhorn-manager-2.zip](https://github.com/longhorn/longhorn/files/10360827/longhorn-manager-2.zip)

## Environment

 - Longhorn version: **1.4.0**
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): **helm (upgraded from previously deployed 1.3.2)**
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: **AKS 1.25.2**
   - Number of management node in the cluster: 
   - Number of worker node in the cluster: **3**
 - Node config
   - OS type and version: **Ubuntu 22.04.1 LTS**
   - CPU per node: **2**
   - Memory per node: **8Gb**
   - Disk type(e.g. SSD/NVMe): **Premium SSD LRS**
   - Network bandwidth between the nodes: ?
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): **AKS**
 - Number of Longhorn volumes in the cluster: **1**

**Comment by derekbit** [comment] 2023-01-06 15:25
@tbertenshaw 
Thanks for your help and cooperation.

Some questions need your help
1. Did the issue happen in v1.3.2?
2. If available, can you try `https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml` and see if the restarts of the new deployment continue?

**Comment by tbertenshaw** [comment] 2023-01-06 15:53
@derekbit 


> * Did the issue happen in v1.3.2?
No
> * If available, can you try to deploy `https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml` and see if the restarts of the new deployment continue?
Just done and after 15 mins of the share manager looking to be successfull then it restarted. (im still using your patched `longhorn-manager`)

**Comment by tbertenshaw** [comment] 2023-01-06 15:56
[supportbundle_cf947ccc-9d7e-490f-8df5-f22db6f413f7_2023-01-06T15-55-03Z.zip](https://github.com/longhorn/longhorn/files/10361344/supportbundle_cf947ccc-9d7e-490f-8df5-f22db6f413f7_2023-01-06T15-55-03Z.zip)

**Comment by tbertenshaw** [comment] 2023-01-06 15:57
Incidentally have scaled my moodle workload down to 1 pod. Can scale back up but just been trying to provide a more stable experience to users. They will be offline soonish (its 15:57 on Friday here)

**Comment by derekbit** [comment] 2023-01-06 16:07
It is fine. I can check the latest support bundle first. Appreciated.

**Comment by derekbit** [comment] 2023-01-07 00:07
@tbertenshaw Can you provide the `dmesg -T` of each longhorn node?

**Comment by tbertenshaw** [comment] 2023-01-07 08:13
[dmesg_T.zip](https://github.com/longhorn/longhorn/files/10365762/dmesg_T.zip)
@derekbit

**Comment by derekbit** [comment] 2023-01-07 10:10
@tbertenshaw 
From the dmesg, I saw a tons of error messages `ganesha.nfsd[278263]: segfault at 118 ip 00007f1bb2220692 sp 00007f1ba21f3fb0 error 4 in libganesha_nfsd.so.4.2[7f1bb2191000+194000]`. It means the nfs-ganesha server in the shared-manager somehow crashed repeatedly.

Also tried to locate the poition in nfs-ganesha
```
# addr2line -e libganesha_nfsd.so.4.2 -fCi 8F692
dec_nfs4_state_ref
:?
```
where 8F692 is 00007f1bb2220692-7f1bb2191000.
It looks the issue is not from our recovery backend C codes in nfs-ganesha.

I'd report the issue to nfs-ganesha community, but the question is that I cannot reproduce it in our environment and hard to open a ticket.

It seems nfs-ganesha v4.2 has some issues from the log. I can backport the recovery backend codes to nfs-ganesha v3.x and hope @tbertenshaw do us a favor for testing it. WDYT? @tbertenshaw @innobead

**Comment by derekbit** [comment] 2023-01-08 15:20
> @tbertenshaw From the dmesg, I saw a tons of error messages `ganesha.nfsd[278263]: segfault at 118 ip 00007f1bb2220692 sp 00007f1ba21f3fb0 error 4 in libganesha_nfsd.so.4.2[7f1bb2191000+194000]`. It means the nfs-ganesha server in the shared-manager somehow crashed repeatedly.
> 
> Also tried to locate the poition in nfs-ganesha
> 
> ```
> # addr2line -e libganesha_nfsd.so.4.2 -fCi 8F692
> dec_nfs4_state_ref
> :?
> ```
> 
> where 8F692 is 00007f1bb2220692-7f1bb2191000. It looks the issue is not from our recovery backend C codes in nfs-ganesha.
> 
> I'd report the issue to nfs-ganesha community, but the question is that I cannot reproduce it in our environment and hard to open a ticket...
> 
> It seems nfs-ganesha v4.2 has some issues. I can backport the recovery backend codes to nfs-ganesha v3.x and hope @tbertenshaw do us a favor for testing it. WDYT? @tbertenshaw @innobead

Hello @tbertenshaw,

As I explained, I've built the longhorn-manger image and the share-manager image. If available, you can try them.
1. Replace the longhorn-manager daemonset `image` with `derekbit/longhorn-manager:1.4.0-rwx`
2. Replace the longhorn-manager daemonset `command`'s share-manager-image with `derekbit/longhorn-share-manager:v_20230107`. Here is an example.
```
      containers:
      - command:
        - longhorn-manager
        ...
        - --share-manager-image
        - derekbit/longhorn-share-manager:v_20230107
```

You can revert the images back to the original ones after testing.  Also help provide us the the support bundle and `dmesg -T`. Many thanks. :)

**Comment by tbertenshaw** [comment] 2023-01-08 16:45
![image](https://user-images.githubusercontent.com/2010002/211208479-1600d15e-ba7d-4e44-863d-789db6edbd72.png) Is this correct? Also how long do you think we need this running to get enough logs? @derekbit

**Comment by derekbit** [comment] 2023-01-09 00:00
@tbertenshaw 
Correct. 30 minutes to 1 hour should be enough.

**Comment by innobead** [comment] 2023-01-09 00:49
Let's test it with @tbertenshaw first. I am curious if this is only able to reproduce in a specific env 🤔.

**Comment by derekbit** [comment] 2023-01-09 01:11
There are at two issues in this ticket.

The first one is that the share-manager pod is deleted and created repeatedly bacause of the ticket https://github.com/longhorn/longhorn-manager/commit/ed1f74273fb2d86d85d910ec7a08e2654f477536. Immediate check `pod.spec.nodeName` ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go#L604)) after creating a pod ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go#L596)) would lead to an error that the pod is not scheduled by kubelet. For this issue, I added a verifyCreation logic in the share-manager controller, but I doubt there are some issues not resolved in the controller.

The second issue is I mentioned in https://github.com/longhorn/longhorn/issues/5224#issuecomment-1374431192. Actually, not sure if related to the first one or the NFS-ganesha issue. So, the customized images is to clarify if it is introduced by NFS-ganesha.

**Comment by derekbit** [comment] 2023-01-09 01:12
There are at least two issues in this ticket.

The first one is that the share-manager pod is deleted and created repeatedly bacause of the ticket https://github.com/longhorn/longhorn-manager/commit/ed1f74273fb2d86d85d910ec7a08e2654f477536. Immediate check `pod.spec.nodeName` ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go#L604)) after creating a pod ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go#L596)) would lead to an error that the pod is not scheduled by kubelet. For this issue, I added a verifyCreation logic in the share-manager controller, but I doubt there are some issues not resolved in the controller.

The second issue is I mentioned in https://github.com/longhorn/longhorn/issues/5224#issuecomment-1374431192. Actually, not sure if related to the first one or the NFS-ganesha issue. So, the customized images is to clarify if it is introduced by NFS-ganesha first.

cc @innobead

**Comment by innobead** [comment] 2023-01-09 01:48
> There are at least two issues in this ticket.
> 
> The first one is that the share-manager pod is deleted and created repeatedly bacause of the ticket [longhorn/longhorn-manager@ed1f742](https://github.com/longhorn/longhorn-manager/commit/ed1f74273fb2d86d85d910ec7a08e2654f477536). Immediate checking `pod.spec.nodeName` ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go?rgh-link-date=2023-01-09T01%3A12%3A16Z#L604)) after creating a pod ([code](https://github.com/longhorn/longhorn-manager/blob/master/controller/share_manager_controller.go?rgh-link-date=2023-01-09T01%3A12%3A16Z#L596)) would lead to an error that the pod is not scheduled by kubelet. For this issue, I added a verifyCreation logic in the share-manager controller, but I doubt there are some issues not resolved in the controller.

cc @joshimoo

**Comment by tbertenshaw** [comment] 2023-01-09 08:09
[dmesg_T.zip](https://github.com/longhorn/longhorn/files/10371436/dmesg_T.zip)
[supportbundle_cf947ccc-9d7e-490f-8df5-f22db6f413f7_2023-01-09T08-05-02Z.zip](https://github.com/longhorn/longhorn/files/10371440/supportbundle_cf947ccc-9d7e-490f-8df5-f22db6f413f7_2023-01-09T08-05-02Z.zip)
@derekbit 
- `share-manager` not restarted in 13hours  (massive improvement but still has restarted since new `longhorn-manager` pods) 
-  `longhorn-manager` pods started 15 hours ago
-  scaled up the production workload to 3 pods during this period as well as the test volume/workload

**Comment by derekbit** [comment] 2023-01-09 08:50
@tbertenshaw 

Appreciated your update!

Checked the share-manager pod `share-manager-pvc-f5952e3a-d202-4e8f-9fcf-277d70bec191` which is created at `2023-01-08T18:17:04Z` and using`derekbit/longhorn-share-manager:v_20230107`. The restarts looks not happen anymore.

> but still has restarted since new longhorn-manager pods

BTW, what does it mean? A bit of confused.

**Comment by tbertenshaw** [comment] 2023-01-09 08:58
just that if you look at the output 
![image](https://user-images.githubusercontent.com/2010002/211271150-2349e418-4b06-48b7-93a1-5a6f03e06e5c.png)
you can see one `share-manager`'s latest pod instance is 2 hours after the `longhorn-manager` instances which were created when i edited the `daemonset`. So implying that that `share-manager` (the one for the moodle workload) has restarted once at least?  Certainly significantly less restarts if just one anyway @derekbit

**Comment by derekbit** [comment] 2023-01-09 09:01
> you can see one `share-manager`'s latest pod instance is 2 hours after the `longhorn-manager` instances which were created when i edited the `daemonset`. So implying that that `share-manager` (the one for the moodle workload) has restarted once at least? Certainly significantly less restarts if just one anyway

Got it, thank you. Will check the restart.
Now, we can confirm the restarts are caused by the issue in nfs-ganesha 4.2. 
cc @innobead

**Comment by tbertenshaw** [comment] 2023-01-09 09:04
FYI the restart shows as  
14h 45m ago 2023-01-08T18:17:04Z for `share-manager-pvc-f5952e3a-d202-4e8f-9fcf-277d70bec191`
verses
16h 19m ago 2023-01-08T16:43:21Z for `longhorn-manager-dfzxz`

**Comment by innobead** [comment] 2023-01-09 09:42
@yangchiu Could you help verify this on AKS based on what env the user has? @derekbit can't reproduce this locally, so we guess this is specially related to AKS, but also not sure if ubuntu 22.04 LTS is customized on Azure for AKE. 

cc @longhorn/qa

**Comment by innobead** [comment] 2023-01-09 09:44
@tbertenshaw Could you share how you provision the cluster on AKS? Did you use any tools like terraform? Any scripts or steps provided will be helpful. We would like to reproduce this on our own to identify the reproduce steps.

**Comment by innobead** [comment] 2023-01-09 09:47
https://github.com/Azure/AKS/blob/master/CHANGELOG.md#release-notes (2022-12-04)

> Kubernetes 1.25 is now Generally available. 1.25.4 patch version was added
Ubuntu 22.04 for AMD and ARM64 architectures will be the default host.
Windows Server 2022 will be the default Windows host. Important, old windows 2019 containers will not work on windows server 2022 hosts.

**Comment by innobead** [comment] 2023-01-09 09:48
@tbertenshaw Have you tried the AKS 1.24 with Longhorn 1.4.0? I am just curious about the result if you have tried it before.

**Comment by tbertenshaw** [comment] 2023-01-09 09:51
no after upgrading longhorn i immediately upgraded AKS so didn't at the point notice if there were issues or not.

**Comment by tbertenshaw** [comment] 2023-01-09 10:02
1.24. I have been using longhorn since 1.1.2 i think and upgraded as a new version was available. 
you can see here i  was using at  AKS1.23 #3873  also was using AKS 1.21 here #2787

**Comment by innobead** [comment] 2023-01-09 10:03
> 1.24. I have been using longhorn since 1.1.2 i think and upgraded as a new version was available. you can see here i was using at AKS1.23 #3873 also was using AKS 1.21 here #2787

Very nice, thanks for the info.

**Comment by innobead** [comment] 2023-01-09 10:04
Adding `require/qa-reproduce` to reproduce this first before @derekbit works on this issue. cc @longhorn/qa

**Comment by derekbit** [comment] 2023-01-09 11:17
I just noticed there are warning messags

```
2023-01-09T08:05:03.971666617Z time="2023-01-09T08:05:03Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"aks-nodepoolres-14028323-vmss000001\", UID:\"ecb320ad-2b7e-4aac-b34f-d6e71c2fe736\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"277262223\", FieldPath:\"\"}): type: 'Warning' reason: 'UnknownNodeConditionTrue' Unknown condition true of kubernetes node aks-nodepoolres-14028323-vmss000001: condition type is ReadonlyFilesystem, reason is FilesystemIsReadOnly, message is EXT4-fs (sdb): Remounting filesystem read-only"
```

Is the filesystem of the rwx volume (pvc-f5952e3a-d202-4e8f-9fcf-277d70bec191) `read-only` now?

**Comment by derekbit** [comment] 2023-01-09 11:19
I just noticed there are warning messags

```
2023-01-09T08:05:03.971666617Z time="2023-01-09T08:05:03Z" level=info msg="Event(v1.ObjectReference{Kind:\"Node\", Namespace:\"longhorn-system\", Name:\"aks-nodepoolres-14028323-vmss000001\", UID:\"ecb320ad-2b7e-4aac-b34f-d6e71c2fe736\", APIVersion:\"longhorn.io/v1beta2\", ResourceVersion:\"277262223\", FieldPath:\"\"}): type: 'Warning' reason: 'UnknownNodeConditionTrue' Unknown condition true of kubernetes node aks-nodepoolres-14028323-vmss000001: condition type is ReadonlyFilesystem, reason is FilesystemIsReadOnly, message is EXT4-fs (sdb): Remounting filesystem read-only"
```

Is the filesystem of the rwx volume (pvc-f5952e3a-d202-4e8f-9fcf-277d70bec191) `read-only` now? @tbertenshaw

**Comment by tbertenshaw** [comment] 2023-01-09 11:24
strange. Thats new. Just sshed into a pod and did a `touch timtest.txt` in the shared mounted volume folder. This was immediately available in another pod's shared volume.  When students offline i will recycle the node and see if that clears the message.

**Comment by derekbit** [comment] 2023-01-09 11:29
> strange. Thats new. Just sshed into a pod and did a `touch timtest.txt` in the shared mounted volume folder. This was immediately available in another pod's shared volume. When students offline i will recycle the node and see if that clears the message.

Sure. Take your time.
Interesting. The conditioin is from kubernetes's `node.status.conditions`.

**Comment by tbertenshaw** [comment] 2023-01-09 11:30
yeah not sure what that is or means if i can write to the disks 😄 
![image](https://user-images.githubusercontent.com/2010002/211298564-4ad2d99c-8d7d-4b2e-8201-c8522a0a22de.png)

**Comment by derekbit** [comment] 2023-01-10 02:05
> FYI the restart shows as 14h 45m ago 2023-01-08T18:17:04Z for `share-manager-pvc-f5952e3a-d202-4e8f-9fcf-277d70bec191` verses 16h 19m ago 2023-01-08T16:43:21Z for `longhorn-manager-dfzxz`

The share-manager controller started share manage at `2023-01-08T18:17:04.888533465Z` because the share-manager state is `error`.
When does the share-manager resource state become `error`?
- share-manager pod is not at `Running` or `Pending`
- share-manager pod is `Running`, but share-manager resource state is not `Running`

From the support bundle, it looks the pod somehow became non-running state and then restart the pod.

You can keep observing if there is any restart of the share-manager pod. cc @tbertenshaw

**Comment by yangchiu** [comment] 2023-01-10 08:49
I've tried to reproduced this on AKS, but still unable to observe share-manager restart yet.

With the following 3 scenarios, the share-manager is running stably without restart.

* Directly running v1.25.2 cluster
(1) create v1.25.2 cluster
(2) helm install longhorn v1.4.0
(3) kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml
(4) wait at least 15 mins for share-manager restart

* Upgrade longhorn from v1.3.2 to v1.4.0, and upgrade k8s from v1.24.6 to v1.25.2
(1) create v1.24.6 cluster
(2) helm install longhorn v1.3.2
(3) kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml
(4) helm upgrade longhorn v1.4.0
(5) upgrade k8s version from v1.24.6 to v1.25.2 following the steps: https://longhorn.github.io/longhorn-tests/manual/pre-release/managed-kubernetes-clusters/aks/upgrade-k8s/
(6) wait at least 15 mins for share-manager restart

* Upgrade longhorn from v1.3.2 to v1.4.0, and upgrade k8s from v1.22.11 to v1.23.12, then from v1.23.12 to v1.24.6, then from v1.24.6 to v1.25.2
(1) create v1.22.11 cluster
(2) helm install longhorn v1.3.2
(3) kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/master/examples/rwx/rwx-nginx-deployment.yaml
(4) helm upgrade longhorn v1.4.0
(5) upgrade k8s version  from v1.22.11 to v1.23.12, then from v1.23.12 to v1.24.6, then from v1.24.6 to v1.25.2 following the steps: https://longhorn.github.io/longhorn-tests/manual/pre-release/managed-kubernetes-clusters/aks/upgrade-k8s/
(6) wait at least 15 mins for share-manager restart

Just wondering is there any extra settings customized when creating the cluster (since I only create the cluster with default settings)? Is this issue always reproducible in your azure environment (like does this issue only happen in this specific cluster + node pool? or it is always reproducible when you create a new cluster. moreover, if create another new node pool and migrate workloads to this new node pool just like what we did when upgrade k8s https://longhorn.github.io/longhorn-tests/manual/pre-release/managed-kubernetes-clusters/aks/upgrade-k8s/, will the restart sustain?) Thanks!

**Comment by innobead** [comment] 2023-01-11 03:04
cc @PhanLe1010

**Comment by derekbit** [comment] 2023-03-14 01:32
@tbertenshaw 
Please try v1.4.1 and feel free to open the issue if there is any issue. Thank you.

**Closed by derekbit** 2023-03-14 01:32 UTC
Labels: kind/bug, priority/0, investigation-needed, area/volume-rwx, area/public-cloud, area/share-manager, require/qa-reproduce, reproduce/none

**Comment by tbertenshaw** [comment] 2023-04-22 15:46
@derekbit upgraded and all well now. Thanks for the help 👍
