### ISSUE TITLE
[BUG] Restoring volume stuck forever if the backup is already deleted.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1867] opened 2020-10-08 22:43 UTC
**Describe the bug**
Restoring volume stuck with null state forever if the backup is already deleted.

**To Reproduce**
1. Create a volume and write 100 mb data to it.
2. Take a backup.
2. Restore the backup and immediately delete the backup.
3. The restoring volume stuck and never recovers or become faulted.

**Expected behavior**
The restoring volume should become faulted after retrying for some time, there should be a time out for retry.

**Log**
[longhorn-support-bundle_e636dffc-08d6-4fd1-8aad-7a5fe167b4d2_2020-10-08T22-41-51Z.zip](https://github.com/longhorn/longhorn/files/5351598/longhorn-support-bundle_e636dffc-08d6-4fd1-8aad-7a5fe167b4d2_2020-10-08T22-41-51Z.zip)

Backup volume - pvc-f8473372-108d-4667-a54b-23b99595de66
Backup name - backup-708a7f01339f467a
Restoring volume - restore-2
Time - ~2020-10-08 22:24:00

**Environment:**
 - Longhorn version: Longhorn Master - 10/08/2020
 - Kubernetes version: 19.2
 - Node OS type and version: Ubuntu 18.04

**Additional context**
The ```backupfrom``` of the restoring volume is referring to a non-existent backup because the backup is deleted.

**Comment by innobead** [comment] 2022-11-23 13:48
@mantissahz need to backport to 1.3 and 1.2.

**Comment by chriscchien** [comment] 2022-11-24 02:51
**Verified in longhorn master `2d4000` with [steps](https://github.com/longhorn/longhorn/issues/1867#issuecomment-1324742094)
Result pass**

1. Restore volume from backup then immediately delete the backup -  volume become faulted immediately
2. Restore volume from backup then delete the backup while restoring was in progress - volume become faulted after awhile

**Comment by innobead** [comment] 2023-03-03 06:49
This needs to retest because of the new fix introduced from https://github.com/longhorn/longhorn/issues/5458 to 1.4.1. 

cc @longhorn/qa

**Comment by chriscchien** [comment] 2023-03-03 08:06
Move to pipeline implement from testing. Waiting https://github.com/longhorn/longhorn-manager/pull/1729 merged then I will start the testing.

**Comment by derekbit** [comment] 2023-03-03 08:13
Update the test steps and expectation
https://github.com/longhorn/longhorn/issues/5458#issuecomment-1452894901

**Comment by derekbit** [comment] 2023-03-07 05:40
Because of the latest [PR](https://github.com/longhorn/longhorn-manager/commit/bb6dd1a312f0a032a87af81e38018c22153912c9), so the behavior won't be changed.

cc @longhorn/qa

**Comment by chriscchien** [comment] 2023-03-07 10:31
Hi, in longhorn-manager master `44f425`, I can delete backup from UI while volume is restoring. After the restoration complete, the volume will keep attached and the `ROBUSTNESS` = `healthy`, `Ready for workload `= `Not Ready`, do we have a definition of backup can be deleted while volume restoring? 
[supportbundle_39effd03-dffd-4f82-97c7-04fb2aa8e577_2023-03-07T10-26-53Z.zip](https://github.com/longhorn/longhorn/files/10908368/supportbundle_39effd03-dffd-4f82-97c7-04fb2aa8e577_2023-03-07T10-26-53Z.zip)

By the way, restore volume from backup then immediately delete the backup the volume become faulted immediately as expected, thank you

cc @derekbit @longhorn/qa

**Comment by chriscchien** [comment] 2023-03-07 13:58
> > Hi, in longhorn-manager master 44f425, I can delete backup from UI while volume is restoring. After the restoration complete, the volume will keep attached and the ROBUSTNESS = healthy, Ready for workload = Not Ready, do we have a definition of backup can be deleted while volume restoring?
> 
> @chriscchien A bit confused. I didn't see any `backupDelete` API call in the support bundle. I tried the backup deletion while restoring backup again. The backup was deleted after restoration, and the volume becomes detached in the end.

Hi @derekbit , 
I can reproduce the situation by clicking `Delete All Backups ` in UI while volume restoration is in progress, from terminal I can see the backup CR deleted(disappear) too. Below is the support bundle
[supportbundle_4cb5bb67-7d01-4b27-91ef-775a969a3043_2023-03-07T13-54-09Z.zip](https://github.com/longhorn/longhorn/files/10910054/supportbundle_4cb5bb67-7d01-4b27-91ef-775a969a3043_2023-03-07T13-54-09Z.zip)


If I try delete backup CR by command during volume restoraation, the restoration will complete and backup deleted after restoration,  volume become detached.

**Comment by derekbit** [comment] 2023-03-07 14:26
@chriscchien 

Got it. This is different than the backup deletion, and it is a backupVolume deletion case.

The backupVolume does [code](https://github.com/longhorn/longhorn-manager/blob/master/controller/backup_volume_controller.go#L236)
1. Delete all backups CR and trigger the deletions of backups in backupstore 
2. Delete the backup volume in backupstore 

Deleting all backups CR should succeed, but the deletions in backupstore are stuck until the restoration process is complete.

The restoration is succesful, but the volume state is stuck in attached with `frontendDisabled=true` because the error
```
time="2023-03-07T14:23:37Z" level=warning msg="Dropping Longhorn volume longhorn-system/bbb out of the queue" controller=longhorn-volume error="failed to sync longhorn-system/bbb: failed to reconcile volume state for bbb: failed to get backup volume: bbb: backupvolume.longhorn.io \"pvc-0639d954-0043-4ae8-a274-05ab7731204c\" not found" node=rancher60-worker1
```

The root cause is [here](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L2941) in `checkForAutoDetachment`. We should ignore the `IsNotFound` error.

cc @weizhe0422

**Comment by innobead** [comment] 2023-03-07 14:39
> 
> The root cause is the [check](https://github.com/longhorn/longhorn-manager/blob/master/controller/volume_controller.go#L2941) in `checkForAutoDetachment`. We should ignore the `IsNotFound` error.
> 
> cc @weizhe0422

@chriscchien @derekbit I feel this is a day 1 issue? 

@chriscchien , let's create another specific issue for this bulk backup deletion to cause restoring to finish with the attached state. Well done.

**Comment by derekbit** [comment] 2023-03-07 14:51
Yeah. I think ignoring the `IsNotFound` error might be not a good solution. Probably need to check if the backupVolume is being used for any restoration before removing it from the backupstore, and it will be consistent with the backup deletion.

**Comment by weizhe0422** [comment] 2023-03-07 15:57
Maybe the backup volume CR could be checked in webhook to see if there is any exists volume CR referenced.

**Comment by chriscchien** [comment] 2023-03-08 01:53
Close this ticket because in longhorn-manager master `44f425` below, actions worked as expected

- Restore volume from backup then immediately delete the backup.  
   - Volume become faulted immediately
- Restore volume from backup then delete the backup while restoring was in progress. 
   - Backup deleted after restoration complete and volume in detached state after resotrion

**Closed by chriscchien** 2023-03-08 01:53 UTC
Labels: kind/bug, area/manager, reproduce/always, priority/0, area/volume-backup-restore, release/retest-needed, backport/1.3.3, backport/1.2.7
