### ISSUE TITLE
[TEST] Cascading test failures in daily regression run

### ISSUE THREAD

**Issue by c3y1huang** [longhorn/longhorn#4957] opened 2022-11-29 02:25 UTC
## What's the test to develop? Please describe

Seems to have cascading test failures in the daily regression run.
```
Exception when cleanup volume
```

https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/325/console

## Describe the items of the test development (DoD, definition of done) you'd like

- [ ] fix cascading failures

## Additional context

https://github.com/longhorn/longhorn-tests/commit/de2fa205b758474218e76ad479bc81655a9763ba

**Comment by c3y1huang** [comment] 2022-11-29 02:25
cc @chriscchien

**Comment by chriscchien** [comment] 2022-11-29 03:40
Recently test script modified related to delete volume was https://github.com/longhorn/longhorn-tests/commit/de2fa205b758474218e76ad479bc81655a9763ba, so the cascading error may caused by this (this PR backported to v1.3.x and v1.2.x but not seen the cascading error) 

I triggered 2 pipelines, 1 is master-head and another is code before https://github.com/longhorn/longhorn-tests/commit/de2fa205b758474218e76ad479bc81655a9763ba for analize/compare
- longhorn-test [master-head](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2583/)
- longhorn-test [af452d](https://ci.longhorn.io/job/private/job/longhorn-tests-regression/2584/)

**Comment by chriscchien** [comment] 2022-11-29 07:25
By execute case `test_replica_schedule_to_disk_with_most_usable_storage` with https://github.com/longhorn/longhorn-tests/commit/de2fa205b758474218e76ad479bc81655a9763ba inculded, I can reproduce volume clean stuck situation my local, if run test case without https://github.com/longhorn/longhorn-tests/commit/de2fa205b758474218e76ad479bc81655a9763ba, volume will be deleted eventually

**Comment by innobead** [comment] 2022-11-29 08:06
Have we tested this before?

**Comment by chriscchien** [comment] 2022-11-29 08:14
Sorry I tested it before by pytest option `-k disk' but did not notice that volume not cleanup clearly for the test case was latest 1 execute, I will modify `test_replica_schedule_to_disk_with_most_usable_storage` and submit PR to fix it today

**Comment by innobead** [comment] 2022-11-29 08:26
> Sorry I tested it before by pytest option `-k disk` but did not notice that volume not cleanup clearly for the test case was last 1 execute, I will modify `test_replica_schedule_to_disk_with_most_usable_storage` and submit PR to fix it today

I see, no worries, just fix this. However, why did you mention `test_replica_schedule_to_disk_with_most_usable_storage`? In https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/325/console, many teardown failures not just `test_replica_schedule_to_disk_with_most_usable_storage`?

**Comment by chriscchien** [comment] 2022-11-30 01:48
Cascading error not happening on latest build after https://github.com/longhorn/longhorn-tests/pull/1209 merged
Here is test result [build326](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/326/)

**Closed by chriscchien** 2022-11-30 01:48 UTC
Labels: kind/test
