### ISSUE TITLE
[IMPROVEMENT]  Add websocket for backup backing image

### ISSUE THREAD

**Issue by ChanYiLin** [longhorn/longhorn#8849] opened 2024-06-28 08:14 UTC
## Is your improvement request related to a feature? Please describe (👍 if you like this request)

Add websocket to backup backing image so the UI can directly show the current backup progress and status without reloading the page

## Describe the solution you'd like

.

## Describe alternatives you've considered

.

## Additional context

.

**Comment by roger-ryao** [comment] 2024-07-03 10:03
**Verified on master-head 20240703**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/c3e1f66bd67f5eeec837a5ee6522ac17391031ff
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/b8cd50b9af0044f341d9766142ee42829f708dce


**The test steps**

https://github.com/longhorn/longhorn/issues/8849#issuecomment-2202183441

**Result Passed**

- [x] 1. can't backup backing image if backup already exists
- [x] 2. can't restore backing image if backing image already exists
- [x] 3. UI can connect to backup backing image websocket to update the status of the backup

**Comment by a110605** [comment] 2024-07-08 10:12
The `/v1/ws/1s/backupbackingimages` can't got the latest bbi list. 

Still investigating...

**Comment by roger-ryao** [comment] 2024-07-09 04:49
Hi @a110605 :
     After following your steps, I was able to reproduce it. Delete the `backup backing image` by calling DELETE `http://[LH cluster IP]:30001/v1/backupbackingimages/[backing_image_name]` <- backup backing image websocket `ws://[LH cluster IP]:30001/v1/ws/1s/backupbackingimages` did not update.
     
![Screenshot_20240709_120109](https://github.com/longhorn/longhorn/assets/104337648/32e2b49a-90dd-47f7-b6ff-4ff6758120e1)

![Screenshot_20240709_123837](https://github.com/longhorn/longhorn/assets/104337648/c53e3faa-7352-4393-9f82-c2b9393b3bdb)

![Screenshot_20240709_123900](https://github.com/longhorn/longhorn/assets/104337648/692c4426-66b3-4e1d-b337-e99186f33bd8)

**Comment by ChanYiLin** [comment] 2024-07-09 06:46
Hi 
I and @derekbit we found the reason of the websocket issue
we need to add the informer sync in this controller.
https://github.com/longhorn/longhorn-manager/blob/master/controller/websocket_controller.go

**Comment by a110605** [comment] 2024-07-10 01:38
Thanks @ChanYiLin fix. UI is able to get latest backupbackingimage from websocket. (See https://github.com/longhorn/longhorn-ui/pull/763)

Since [fixed PR](https://github.com/longhorn/longhorn-manager/pull/2958) is already merged, it's good to close this issue. cc @roger-ryao

**Comment by derekbit** [comment] 2024-07-10 01:51
@roger-ryao
Can you help check it again and close if everything goes well? Thank you.

**Comment by roger-ryao** [comment] 2024-07-10 02:37
**Verified on master-head 20240710**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7427c5f672488197e458e55e3263cd85a539b6da
- longhorn-manager `master-head` https://github.com/longhorn/longhorn-manager/commit/9a9a6fe126d6798d2b3d1bdffd5b6a959698960a

**The test steps**

https://github.com/longhorn/longhorn/issues/8849#issuecomment-2216507516

**Result Passed**

After deleted the backup backing image by calling **DELETE** `http://172.19.96.163:30001/v1/backupbackingimages/vol-0` ,b ackup backing image websocket `ws://172.19.96.163:30001/v1/ws/1s/backupbackingimages` will update 
![Screenshot_20240710_103107](https://github.com/longhorn/longhorn/assets/104337648/9cbed391-bba4-4332-83af-92ab0ec6dd43)

**Closed by roger-ryao** 2024-07-10 02:37 UTC
Labels: area/ui, require/auto-e2e-test, area/backing-image, kind/improvement
