### ISSUE TITLE
[QUESTION] PVC Refuses To Mount - exit status 32  - multipath issue

### ISSUE THREAD

**Issue by dcplaya** [longhorn/longhorn#1819] opened 2020-09-25 07:29 UTC
PVCs refuse to mount. I can kill the container and it tries to recreate but will always show the following error until I reboot the node (but that doesn't always fix the issue either). It will report the same error for hours even though Longhorn says its attached in the GUI. GUI reports "no available mount points"

```
│   Normal   Scheduled         <unknown>  default-scheduler  Successfully assigned media-management/plex-668d559787-7bbpz to node02                                                                               │
│   Warning  FailedMount       33s        kubelet, node02    MountVolume.SetUp failed for volume "plex-config" : rpc error: code = Internal desc = mount failed: exit status 32                                   │
│ Mounting command: mount                                                                                                                                                                                         │
│ Mounting arguments: -t ext4 -o defaults /dev/longhorn/plex-config /var/lib/kubelet/pods/2fb7dc1f-d2aa-4f9d-80c1-60a7bb692171/volumes/kubernetes.io~csi/plex-config/mount                                        │
│ Output: mount: /var/lib/kubelet/pods/2fb7dc1f-d2aa-4f9d-80c1-60a7bb692171/volumes/kubernetes.io~csi/plex-config/mount: /dev/longhorn/plex-config already mounted or mount point busy.                           │
│   Warning  FailedMount  19s  kubelet, node02  Unable to attach or mount volumes: unmounted volumes=[config], unattached volumes=[config transcode media shared shared-logs default-token-64485]: timed out wait │
│ ing for the condition
```

---
Version: `v1.0.2`

A support bundle has been attached as well.
[longhorn-support-bundle_0c735fa4-c8bd-45a1-8537-4d822e8b35fe_2020-09-25T07-29-40Z.zip](https://github.com/longhorn/longhorn/files/5281229/longhorn-support-bundle_0c735fa4-c8bd-45a1-8537-4d822e8b35fe_2020-09-25T07-29-40Z.zip)

Edit:

Hmmm.... I didn't think this was a multipath issue since the error is `error 32` and not `error 1`. But I did just add the multipath blacklist from [here](https://github.com/longhorn/longhorn/issues/1210#issuecomment-671689746) and it immediately created the pod. Not sure if these 2 errors are related, I could also be interpreting (AKA reading) the error incorrectly too.

**Comment by rene-demonsters** [comment] 2021-02-24 21:36
Ran into the exact same issue after some storage issues at our provider.

We have a 3 server cluster, symptoms were as follows:

- Anything from Longhorn that was attached to server 1 would fail to actually mount the storage
- Addressing the same PVC but from any other server or creating a new workload addressing it worked fine
- Kicking the server out of the cluster, scrubbing it from Rancher entirely using https://github.com/theAkito/rancher-helpers/blob/master/scripts/cleanup_rancher.sh and then re-importing it still resulted in the same errors coming from that server

As soon as I added the multipath blacklist to the server and restarted the multipath service I was able to bring workloads online on that server without any issues.

**Comment by almorgv** [comment] 2021-03-05 15:23
Same here.
- Longhorn `1.1.0`
- Ubuntu 20.04.01 
- k8s cluster with pretty slow hdd disks

It happens on one node and all workloads on that node cant get volume mount 

```
MountVolume.SetUp failed for volume "pvc-97cbcfbc-3b11-4402-a16c-1b58013eba85" : kubernetes.io/csi: mounter.SetupAt failed: rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-97cbcfbc-3b11-4402-a16c-1b58013eba85 /var/lib/kubelet/pods/ffac9178-907f-4d4b-9a0e-4b9abd501e1b/volumes/kubernetes.io~csi/pvc-97cbcfbc-3b11-4402-a16c-1b58013eba85/mount Output: mount: /var/lib/kubelet/pods/ffac9178-907f-4d4b-9a0e-4b9abd501e1b/volumes/kubernetes.io~csi/pvc-97cbcfbc-3b11-4402-a16c-1b58013eba85/mount: /dev/longhorn/pvc-97cbcfbc-3b11-4402-a16c-1b58013eba85 already mounted or mount point busy. 
```

Reboot fixes this but another network lag very likely brings this again

**Comment by wahyd4** [comment] 2021-04-12 03:29
I had experienced a similar issue here, it happened was I accidentally upgraded the kubelet of one storage node. And unfortunately, the postgres pod was on the same node as the one that got upgraded.  Then caused the postgres pod to fail to run, and recreate the pod didn't work either.

The error details are:
```
Events:
  Type     Reason                  Age              From                     Message
  ----     ------                  ----             ----                     -------
  Normal   Scheduled               24s              default-scheduler        Successfully assigned db/new-postgres-postgresql-0 to server-3
  Normal   SuccessfulAttachVolume  13s              attachdetach-controller  AttachVolume.Attach succeeded for volume "postgres-db"
  Warning  FailedMount             4s (x4 over 9s)  kubelet                  MountVolume.SetUp failed for volume "postgres-db" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: mount
Mounting arguments: -t xfs -o defaults /dev/longhorn/postgres-db /var/lib/kubelet/pods/e1c2db70-f155-453d-a8ed-6ad78ab77c93/volumes/kubernetes.io~csi/postgres-db/mount
Output: mount: /var/lib/kubelet/pods/e1c2db70-f155-453d-a8ed-6ad78ab77c93/volumes/kubernetes.io~csi/postgres-db/mount: wrong fs type, bad option, bad superblock on /dev/longhorn/postgres-db, missing codepage or helper program, or other error.
```
I had to restart the node to solve this issue.

**Comment by PatrickHuetter** [comment] 2021-10-04 10:07
I can confirm this issue with v1.1.2. Only one node is affected within a 3-node cluster.

**Comment by EugenMayer** [comment] 2022-01-06 17:54
i can confirm this issue with 1.2.3. For me, restarting the node does rarely fix it, the pod that is affected is different every time, interestingly it is always exactly 1, not more. Right now of 2 nodes/agents, one is affected.

```
MountVolume.MountDevice failed for volume "pvc-8ffdf006-f66c-4b1e-8c52-bc3641a3d96c" : rpc error: code = Internal desc = mount failed: exit status 32 Mounting command: mount Mounting arguments: -t ext4 -o defaults /dev/longhorn/pvc-8ffdf006-f66c-4b1e-8c52-bc3641a3d96c /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8ffdf006-f66c-4b1e-8c52-bc3641a3d96c/globalmount Output: mount: /var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-8ffdf006-f66c-4b1e-8c52-bc3641a3d96c/globalmount: /dev/longhorn/pvc-8ffdf006-f66c-4b1e-8c52-bc3641a3d96c already mounted or mount point busy.
```

So it finally leads to

```
Unable to attach or mount volumes: unmounted volumes=[confluence-data], unattached volumes=[confluence-data kube-api-access-sjb84]: timed out waiting for the condition
```

This is a fairly critical issue, it renders at least one of my services disfunctional.

**Comment by EugenMayer** [comment] 2022-01-06 21:55
**Update**: not sure i did pick the wrong issue here in the first place, but if anybody comes accross the error message above, it could be multipath causing it. I followed https://longhorn.io/kb/troubleshooting-volume-with-multipath/ and fixed the issue for me.

**Comment by joshimoo** [comment] 2022-07-27 21:46
I am closing this issue since we have a knowledge base article for multipathd claiming the volume which prevents mounting it here: https://longhorn.io/kb/troubleshooting-volume-with-multipath/

**Closed by joshimoo** 2022-07-27 21:46 UTC
Labels: kind/enhancement, kind/question, require/knowledge-base
