### ISSUE TITLE
[BUG] test related to backup with backing file fail inconsistently on with master longhorn-engine 

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#2783] opened 2021-07-08 16:24 UTC
**Describe the bug**
The test `test_backup_hole_with_backing_file_raw`, `test_backup_with_backing_file_raw`  fail sometimes.
https://drone-publish.longhorn.io/longhorn/longhorn-engine/214
https://drone-publish.longhorn.io/longhorn/longhorn-engine/213

**To Reproduce**
Run the longhorn-engine build

**Log**
```
def test_backup_hole_with_backing_file_raw(grpc_backing_raw_replica1, grpc_backing_raw_replica2, grpc_backing_controller, backup_targets):  # NOQA
--
24222 | for backup_target in backup_targets:
24223 | backup_hole_with_backing_file_test(backup_target,
24224 | grpc_backing_controller,
24225 | grpc_backing_raw_replica1,
24226 | >                                              grpc_backing_raw_replica2)
24227 |  
24228 | data/test_backup.py:493:
24229 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
24230 | data/test_backup.py:176: in backup_hole_with_backing_file_test
24231 | verify_data(dev, offset1, snap1_data)
24232 | common/core.py:528: in verify_data
24233 | write_dev(dev, offset, data)
24234 | common/core.py:515: in write_dev
24235 | return dev.writeat(offset, data)
24236 | common/frontend.py:77: in writeat
24237 | return writeat_direct(self.dev, offset, data)
24238 | common/frontend.py:43: in writeat_direct
24239 | pg_data = readat_direct(dev, pg_offset, PAGE_SIZE)
24240 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
24241 |  
24242 | dev = '/dev/longhorn/test-4d5a227b-volume-backing', offset = 512, length = 512
24243 |  
24244 | def readat_direct(dev, offset, length):
24245 | pg = offset / PAGE_SIZE
24246 | in_page_offset = offset % PAGE_SIZE
24247 | # either read less than a page, or whole pages
24248 | if in_page_offset != 0:
24249 | assert pg == (offset + length) / PAGE_SIZE
24250 | to_read = PAGE_SIZE
24251 | else:
24252 | assert length % PAGE_SIZE == 0
24253 | to_read = length
24254 | pg_offset = pg * PAGE_SIZE
24255 |  
24256 | f = os.open(dev, os.O_DIRECT \| os.O_RDONLY)
24257 | try:
24258 | os.lseek(f, pg_offset, os.SEEK_SET)
24259 | >           ret = directio.read(f, to_read)
24260 | E           OSError: [Errno 61] No data available
---------------------------------------------------------------------------------------

def test_backup_with_backing_file_raw(grpc_backing_raw_replica1, grpc_backing_raw_replica2, grpc_backing_controller, backup_targets):  # NOQA
--
24395 | for backup_target in backup_targets:
24396 | backup_with_backing_file_test(backup_target,
24397 | grpc_backing_controller,
24398 | grpc_backing_raw_replica1,
24399 | >                                         grpc_backing_raw_replica2)
24400 |  
24401 | data/test_backup.py:469:
24402 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
24403 | data/test_backup.py:138: in backup_with_backing_file_test
24404 | VOLUME_BACKING_NAME, ENGINE_BACKING_NAME, backup_target)
24405 | data/test_backup.py:79: in backup_test
24406 | backup3_info["URL"])
24407 | common/core.py:344: in restore_with_frontend
24408 | cmd.backup_restore(url, backup)
24409 | common/cmd.py:118: in backup_restore
24410 | return subprocess.check_output(cmd, encoding='utf-8').strip()
24411 | /usr/lib/python3.6/subprocess.py:356: in check_output
24412 | **kwargs).stdout
24413 | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
24414 |  
24415 | input = None, timeout = None, check = True
24416 | popenargs = (['/go/src/github.com/longhorn/longhorn-engine/integration/common/../../bin/longhorn', '--url', 'localhost:30001', '--debug', 'backup', 'restore', ...],)
24417 | kwargs = {'encoding': 'utf-8', 'stdout': -1}
24418 | process = <subprocess.Popen object at 0x7fbf1b2d79b0>
24419 | stdout = '{\n\t"ReplicaErrors": [\n\t\t{\n\t\t\t"Address": "tcp://localhost:10015",\n\t\t\t"Message": "can not restore backup from replica in mode ERR"\n\t\t}\n\t]\n}\n'
24420 | stderr = None, retcode = 1
24421 |  
24422 | def run(*popenargs, input=None, timeout=None, check=False, **kwargs):
24423 | """Run command with arguments and return a CompletedProcess instance.
24424 |  
24425 | The returned instance will have attributes args, returncode, stdout and
24426 | stderr. By default, stdout and stderr are not captured, and those attributes
24427 | will be None. Pass stdout=PIPE and/or stderr=PIPE in order to capture them.
24428 |  
24429 | If check is True and the exit code was non-zero, it raises a
24430 | CalledProcessError. The CalledProcessError object will have the return code
24431 | in the returncode attribute, and output & stderr attributes if those streams
24432 | were captured.
24433 |  
24434 | If timeout is given, and the process takes too long, a TimeoutExpired
24435 | exception will be raised.
24436 |  
24437 | There is an optional argument "input", allowing you to
24438 | pass a string to the subprocess's stdin.  If you use this argument
24439 | you may not also use the Popen constructor's "stdin" argument, as
24440 | it will be used internally.
24441 |  
24442 | The other arguments are the same as for the Popen constructor.
24443 |  
24444 | If universal_newlines=True is passed, the "input" argument must be a
24445 | string and stdout/stderr in the returned object will be strings rather than
24446 | bytes.
24447 | """
24448 | if input is not None:
24449 | if 'stdin' in kwargs:
24450 | raise ValueError('stdin and input arguments may not both be used.')
24451 | kwargs['stdin'] = PIPE
24452 |  
24453 | with Popen(*popenargs, **kwargs) as process:
24454 | try:
24455 | stdout, stderr = process.communicate(input, timeout=timeout)
24456 | except TimeoutExpired:
24457 | process.kill()
24458 | stdout, stderr = process.communicate()
24459 | raise TimeoutExpired(process.args, timeout, output=stdout,
24460 | stderr=stderr)
24461 | except:
24462 | process.kill()
24463 | process.wait()
24464 | raise
24465 | retcode = process.poll()
24466 | if check and retcode:
24467 | raise CalledProcessError(retcode, process.args,
24468 | >                                        output=stdout, stderr=stderr)
24469 | E               subprocess.CalledProcessError: Command '['/go/src/github.com/longhorn/longhorn-engine/integration/common/../../bin/longhorn', '--url', 'localhost:30001', '--debug', 'backup', 'restore', 'vfs:///data/backupbucket?backup=backup-a5e36a812ec74b63&volume=test-3d5f9650-volume-backing']' returned non-zero exit status 1.

```

**Environment:**
 - Longhorn version: Master

**Comment by keithalucas** [comment] 2021-07-08 17:49
In 213 and 214, there is a revision counter disabled setting mismatch in both outputs:

[test-3d5f9650-engine] time="2021-07-08T11:59:37Z" level=error msg="Revision Counter Disabled setting mismatch at engine true, replica tcp://localhost:10015: false, mark this replica as ERR."
time="2021-07-08T11:59:37Z" level=info msg="Set replica tcp://localhost:10015 to mode ERR"
[test-3d5f9650-engine] time="2021-07-08T11:59:37Z" level=info msg="Monitoring stopped tcp://localhost:10015"
[test-3d5f9650-engine] time="2021-07-08T11:59:37Z" level=info msg="device test-3d5f9650-volume: SCSI device /dev/longhorn/test-3d5f9650-volume shutdown"

**Comment by yasker** [comment] 2021-07-08 17:56
5 of the last 7 engine integration test on master failed. https://drone-publish.longhorn.io/longhorn/longhorn-engine/ 

Mark as P1.

**Comment by keithalucas** [comment] 2021-07-08 21:11
Somehow, the controller is being created by the NewController with disableRevCounter=true.  I added logging to NewController to show what the value of disableRevCounter is and ran the tests until it failed.  It failed on  test_backup_with_backing_file_raw (which is one of the test failures the builder failed on) and logged the same message above for the Revision Counter Disabled mismatch.  My new log message showed that NewController was called with disableRevCounter set to true.  When I run test_backup_with_backing_file_raw via `dapper ./scripts/integration-test -- -s -x -k test_backup_hole_with_backing_file_raw`,  my log message will show disableRevCounter=false when NewController was called.   The python test fixture that should be created the parameters to test_backup_with_backing_file_raw doesn't set the disable_revision_counter paramater to True.   I am going to try to determine the exact command line parameters the longhorn controller process is executed with to see if that has --disableRevCounter which it shouldn't for this test.

  https://github.com/longhorn/longhorn-engine/blob/fd7c58ca7bc5c2e52ddb248d7cd8551a304ec4eb/pkg/controller/control.go#L62

**Comment by keithalucas** [comment] 2021-07-12 11:34
I believe the disableRevCounter thing is wrong.   I fixed something that I believed was unrelated to this issue in 
https://github.com/longhorn/longhorn-engine/pull/637 and have not been able to reproduce this problem since.    I believe this is a duplicate of https://github.com/longhorn/longhorn/issues/1628

**Comment by innobead** [comment] 2021-07-13 05:12
> I believe the disableRevCounter thing is wrong. I fixed something that I believed was unrelated to this issue in
> [longhorn/longhorn-engine#637](https://github.com/longhorn/longhorn-engine/pull/637) and have not been able to reproduce this problem since. I believe this is a duplicate of #1628

Let's see the result of #1628  before closing this issue.

**Comment by innobead** [comment] 2021-08-02 06:58
Closing because the test case passed recently.

**Closed by innobead** 2021-08-02 06:58 UTC
Labels: area/engine, duplicated, kind/bug, kind/test, priority/1, reproduce/often
