### ISSUE TITLE
[BUG] longhorn-engine controller rebuilding crash

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#3822] opened 2022-04-06 17:56 UTC
## Describe the bug

In a customer support bundle, the longhorn-engine controller is crashing because it attempts to access the first element in an array whose length is zero.

https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/controller/rebuild.go#L30

This code crashes:
```
	head := rep.Chain[0]
```
The replica's gRPC method to get the chain of disk images looks like it is returning an empty array of disk images:

https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/replica/replica.go#L592

## To Reproduce

TBD

## Expected behavior

The longhorn engine doesn't crash.

## Log or Support bundle

```
panic: runtime error: index out of range [0] with length 0
2022-04-02T13:06:48.724853291-04:00
2022-04-02T13:06:48.724857895-04:00 goroutine 230939 [running]:
2022-04-02T13:06:48.724862901-04:00 github.com/longhorn/longhorn-engine/pkg/controller.getReplicaDisksAndHead(0xc0000fa1e0, 0x16, 0x0, 0x0, 0x0, 0x0, 0x0)
2022-04-02T13:06:48.724865758-04:00     /go/src/github.com/longhorn/longhorn-engine/pkg/controller/rebuild.go:30 +0x565
2022-04-02T13:06:48.725259388-04:00 github.com/longhorn/longhorn-engine/pkg/controller.(*Controller).VerifyRebuildReplica(0xc0001d57a0, 0xc0000fa1e0, 0x16, [pvc-78ee6a8b-36e5-46e2-9986-15c5a519b3e3-e-e9b63647] 0x0, 0x0)
2022-04-02T13:06:48.725280480-04:00     /go/src/github.com/longhorn/longhorn-engine/pkg/controller/rebuild.go:94 +0x246
2022-04-02T13:06:48.725283601-04:00 github.com/longhorn/longhorn-engine/pkg/controller/rpc.(*ControllerServer).ReplicaVerifyRebuild(0xc0003a4078, 0x1091660, 0xc00045c6f0, 0xc00045c750, 0xc0003a4078, 0xc00045c6f0, 0xc00006aa20)
2022-04-02T13:06:48.725286256-04:00     /go/src/github.com/longhorn/longhorn-engine/pkg/controller/rpc/server.go:223 +0x48
2022-04-02T13:06:48.725288492-04:00 github.com/longhorn/longhorn-engine/proto/ptypes._ControllerService_ReplicaVerifyRebuild_Handler(0xe534a0, 0xc0003a4078, 0x1091660, 0xc00045c6f0, 0xc000522aa0, 0x0, 0x1091660, 0xc00045c6f0, 0xc0000fa1c0, 0x18)
2022-04-02T13:06:48.725291135-04:00     /go/src/github.com/longhorn/longhorn-engine/proto/ptypes/controller.pb.go:1673 +0x217
2022-04-02T13:06:48.725293798-04:00 google.golang.org/grpc.(*Server).processUnaryRPC(0xc00044c000, 0x1099200, 0xc000366000, 0xc00031c100, 0xc000516060, 0x1697f10, 0x0, 0x0, 0x0)
2022-04-02T13:06:48.725300522-04:00     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:998 +0x46a
2022-04-02T13:06:48.725303318-04:00 google.golang.org/grpc.(*Server).handleStream(0xc00044c000, 0x1099200, 0xc000366000, 0xc00031c100, 0x0)
2022-04-02T13:06:48.725305437-04:00     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:1278 +0xd3d
2022-04-02T13:06:48.725307525-04:00 google.golang.org/grpc.(*Server).serveStreams.func1.1(0xc0003a6020, 0xc00044c000, 0x1099200, 0xc000366000, 0xc00031c100)
2022-04-02T13:06:48.725309894-04:00     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:717 +0xa1
2022-04-02T13:06:48.725311790-04:00 created by google.golang.org/grpc.(*Server).serveStreams.func1
2022-04-02T13:06:48.725314990-04:00     /go/src/github.com/longhorn/longhorn-engine/vendor/google.golang.org/grpc/server.go:715 +0xa1
```

## Environment

 - Longhorn version: 1.2.4
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by innobead** [comment] 2022-04-07 00:11
Is this reproducible?

cc @derekbit @shuo-wu

**Comment by keithalucas** [comment] 2022-04-07 18:53
I haven't been able to reproduce it.   The one thing I tried was editing all of the replica's meta files to set `"Removed":true`, restarting the replica, and adding it to the volume.   That didn't work.   I would be interested in the exact result of the gRPC call when this occurs.  The [ReplicaInfo](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/types/resource.go#L3) struct has an array of the chain of non-removed disk names and a map of all the disks which will include removed ones.

**Comment by PhanLe1010** [comment] 2022-04-07 19:14
Could it be the case that the `r.info.Head` is empty so [the for loop](https://github.com/longhorn/longhorn-engine/blob/cda02873ef0789a56fcca9ffcdbc5bea76f09018/pkg/replica/replica.go#L599) never runs? I search the code base for the location where we assign value to `r.info.Head` but couldn't find where we set it.

**Comment by shuo-wu** [comment] 2022-04-08 05:22
Post the way to send gRPC calls to the replica process manually. This may help reproduce the issue:
```
# Install grpcurl
apt-get update
apt-get install -y wget
wget https://github.com/fullstorydev/grpcurl/releases/download/v1.8.6/grpcurl_1.8.6_linux_x86_64.tar.gz
tar -zxvf grpcurl_1.8.6_linux_x86_64.tar.gz
mv grpcurl /usr/local/bin/

# Call Replica gRPC service APIs. Need to modify the replica address.
git clone https://github.com/longhorn/longhorn-engine.git
cd longhorn-engine/
grpcurl -d '' -plaintext -import-path ./proto/vendor/protobuf/src/ -import-path ./proto/ptypes -proto replica.proto 0.0.0.0:10000 ptypes.ReplicaService/ReplicaGet
```

**Comment by innobead** [comment] 2022-04-18 06:22
As per https://github.com/longhorn/longhorn/issues/3822#issuecomment-1092091343, it's unable to reproduce atm, so closing and see if this issue will happen in the future or not. 

cc @kaxing

**Closed by innobead** 2022-04-18 06:22 UTC
Labels: kind/bug, area/engine, severity/1, priority/1, backport-needed/1.2.5
