### ISSUE TITLE
Volumes are failing to attach after upgrade (not very clean one)

### ISSUE THREAD

**Issue by zeppelinux** [longhorn/longhorn#1448] opened 2020-06-01 22:22 UTC
**Describe the bug**
After Offline upgrade from Longhorn 0.81 to 1.0.0 cluster ended up in a state where previosly existing volumes failed to attach to the pods 

**To Reproduce**
1. Scale deployment to 0 and verify volume is detached
2. Shutdown Kubernetes API Server
3. Click on 'Upgrade' using Rancher Helm Longhorn App (nothing visually happens because API server is down)
4. Bring up API Server
5. Click on 'Upgrade' again - see upgrade started
6. Observe some problem in the Longhorn deployment
7. Restart all the nodes, observe no problem after restart anymore
8. Scale pod to 1 and observe the volume attachment fails 

**Expected behavior**
Volume can be attached after upgrade

**Environment:**
 - Longhorn version: v0.81 -> v1.0.0 
 - Kubernetes version: v1.17.4
 - Node OS type and version: CentOS Linux 7 3.10.0-957.21.3.el7.x86_64

**Comment by yasker** [comment] 2020-06-01 22:56
We've found the issue was caused by old driver name `io.rancher.longhorn`.

```
csi-725f459b055f7d9330316dbb1bd5a2860cc251cd46d3dfbaa99ed4804b99d828   io.rancher.longhorn   pvc-b4228257-b988-11e9-bc5e-00241dac3968   192.168.2.232   false      6h40m
csi-bbec8e607bd2178b596436464cc4fb030a0f4981d2fb5f84acb05537185c2247   io.rancher.longhorn   pvc-d5930876-b8a8-11e9-bc5e-00241dac3968   192.168.2.232   false      298d
csi-e5157aca666ba42c9837eb1b48280009a3a82abff87995f2609e79f7cc5bb904   io.rancher.longhorn   pvc-1952ead2-fced-11e9-98dd-00241dac3968   192.168.2.238   true       36d
csi-eaba52b8a8ceb03baf772ebdf85b939f1361ab577e64b937c4458cf3d1360f55   io.rancher.longhorn   pvc-d5930876-b8a8-11e9-bc5e-00241dac3968   192.168.2.216   false      298d
csi-f0297476812bbdbdc7892425beb8a80adb0e5499240bb9137f6b2c828ffd89ec   io.rancher.longhorn   pvc-b14ce48e-b4ac-11e9-bc5e-00241dac3968   192.168.2.232   false      304d
csi-f15d84c5a34b4ff01994137cf8e6260f961ba4d37b7d46f02575f7e4a7f732a6   driver.longhorn.io    pvc-0fad961e-d15e-489d-b031-6c3063fd8536   192.168.2.236   true       19h
csi-f24b7dec5bae1917df9376228f6306c191322e2ae30a32d4a5b68654fd4c20d5   io.rancher.longhorn   pvc-c6c95827-b492-11e9-bc5e-00241dac3968   192.168.2.232   false      18h
```

Due to a bug reporting at https://forums.rancher.com/t/failed-upgrade-from-v0-8-1-to-v1-0-0-caused-by-pv-created-before-v0-6-2/17586/2 , we're revalidating the steps for migrating `io.rancher.longhorn` to `driver.longhorn.io`.

**Comment by meldafrawi** [comment] 2020-06-02 02:25
**Reproduce Steps:**

1. Install Longhorn v0.6.2: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v0.6.2/deploy/longhorn.yaml`
2. Create Longhorn StorageClass: `kubectl apply -f  https://github.com/longhorn/longhorn/blob/v0.6.2/examples/storageclass.yaml`
3. Create a StatefulSet using Longhorn volumes: `kubectl apply -f https://raw.githubusercontent.com/longhorn/longhorn/v0.6.2/examples/statefulset.yaml`
4. Write some data volume and compute it's checksum
5. Cleanup old storage class `kubectl delete -f https://raw.githubusercontent.com/longhorn/longhorn/v0.7.0/examples/storageclass.yaml`
6. Upgrade Longhorn to v0.7.0: `kubectl apply https://raw.githubusercontent.com/longhorn/longhorn/v0.7.0/deploy/longhorn.yaml`
7. Scale down StatefulSet number of replicas to `0`
8. Upgrade Engine for volumes to v0.7.0
9. Scale up StatefulSet number of replicas back to `2`
10. Do some IO operations to make sure volumes are still usable inside pods
11. Upgrade Longhorn to v0.8.0: `kubectl apply https://raw.githubusercontent.com/longhorn/longhorn/v0.8.0/deploy/longhorn.yaml`
12. Scale down StatefulSet number of replicas to `0`
13. Upgrade Engine for volumes to v0.8.0
14. Scale up StatefulSet number of replicas back to `2`
15. Do some IO operations to make sure volumes are still usable inside pods
16. Upgrade Longhorn to v0.8.1: `kubectl apply https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/deploy/longhorn.yaml`
17. Live Upgrade Engine for volumes to v0.8.1
18. Do some IO operations to make sure volumes are still usable inside pods
19. Scale down StatefulSet number of replicas to `0`   <- **Note that scaling down here is done before upgrading to v1.0.0**
20. Upgrade Longhorn to v1.0.0: `kubectl apply https://raw.githubusercontent.com/longhorn/longhorn/v1.0.0/deploy/longhorn.yaml`
21. Live Upgrade Engine for volumes to v1.0.0
22. Scale up StatefulSet number of replicas back to `2`
> Pods failed to mount
23. Follow PV migration steps here: https://longhorn.io/docs/0.8.1/deploy/upgrade/longhorn-manager/#migration-steps
**Migration script output:**
>Error migrate PVs and PVCs for the volumes: Failed to migrate PV and PVC for the volume pvc-48acd5fb-053d-4424-8ab6-636ea44c37ff: failed to delete then recreate PV/PVC, users need to manually check the current PVC/PV then recreate them if needed: failed to wait for the old PV deletion complete

**Comment by shuo-wu** [comment] 2020-06-02 09:02
As the user reports in the [forum](https://forums.rancher.com/t/failed-upgrade-from-v0-8-1-to-v1-0-0-caused-by-pv-created-before-v0-6-2/17586/2), there is a PV finalizer that blocks the migration. We will update the doc now.

If you have failed to migrate some volumes/PVs, you can:
    1. Use `kubectl edit pv <the name of the PV that fails the migration>` to remove the finalizer `external-attacher/io-rancher-longhorn`
    2. Click `Create PV/PVC`(keep `Create PVC` and `Use Previous PVC` checked) to recreate PV and PVC for the volume on the UI page.
    3. Scale up your workloads.
Notice that the above fix won't lead to volume deletion.

**Comment by zeppelinux** [comment] 2020-06-02 16:16
@shuo-wu in the step 2 (I'm using Longhorn UI) I can see the 'Create PV/PVC' button, but it is in disabled state. Please advise.

**Comment by yasker** [comment] 2020-06-02 16:28
@zeppelinux Please hold on for now. We're validating the updated documentation at https://github.com/longhorn/website/pull/140 . After it's done, you should be able to follow it to migrate.

**Comment by khushboo-rancher** [comment] 2020-06-02 19:57
Verified the steps to migrate the volume from https://github.com/longhorn/website/pull/140, it works and I'm able to migrate volume successfully.

**Scenario tested**
**Pre upgrade migration**
1. Install longhorn v0.6.2. Create a volume and attach it to pod.
2. Write data into volume and compute checksum.
3. Upgrade to v0.7.0 --> v0.8.0 --> v0.8.1 and write data into volume, compute checksum.
4. Follow the steps mentioned from https://github.com/longhorn/website/pull/140.
a. Find out the volumes need migration by running ```kubectl get pv --output=jsonpath="{.items[?(@.spec.csi.driver==\"io.rancher.longhorn\")].spec.csi.volumeHandle}"```
b. Scale down the relevant workloads.
c. Edit the related pv ```kubectl edit pv <The corresponding PV of the volume found in step a>``` and remove ```finalizer `external-attacher/io-rancher-longhorn```
d. Run the script to migrate the volume ```curl -s https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/scripts/migrate-for-pre-070-volumes.sh |bash -s -- <volume name>```
5. Upgrade longhorn to v1.0.0 
6. Upgrade the volume to v1.0.0
7. Scale up the workloads.

**Post upgrade migration**
1. Install longhorn v0.6.2. Create a volume and attach it to pod.
2. Write data into volume and compute checksum.
3. Upgrade to v0.7.0 --> v0.8.0 --> v0.8.1 and write data into volume, compute checksum.
4. Upgrade longhorn to v1.0.0 
5. Follow the steps mentioned from https://github.com/longhorn/website/pull/140.
a. Find out the volumes need migration by running ```kubectl get pv --output=jsonpath="{.items[?(@.spec.csi.driver==\"io.rancher.longhorn\")].spec.csi.volumeHandle}"```
b. Scale down the relevant workloads.
c. Edit the related pv ```kubectl edit pv <The corresponding PV of the volume found in step a>``` and remove ```finalizer `external-attacher/io-rancher-longhorn```
d. Run the script to migrate the volume ```curl -s https://raw.githubusercontent.com/longhorn/longhorn/v0.8.1/scripts/migrate-for-pre-070-volumes.sh |bash -s -- <volume name>```
e. Scale up the workloads.
6. Volume attach to workload successfully.

**Comment by yasker** [comment] 2020-06-02 20:37
@zeppelinux Can you check out https://longhorn.io/docs/1.0.0/references/settings/#custom-mkfsext4-parameters for the steps to migrate old volume drivers? Let us know if it works for you.

**Comment by zeppelinux** [comment] 2020-06-02 23:59
@yasker It did, all volumes are attaching successfully! Thanks Guys!

**Comment by yasker** [comment] 2020-06-03 00:57
@zeppelinux Glad to hear that! I will close the issue for now. Feel free to reopen it if you found any issues with the newly migrated volumes.

**Closed by yasker** 2020-06-03 00:57 UTC
Labels: bug, doc, priority/1
