### ISSUE TITLE
[BUG] After network disconnection replicas cannot be reattached 

### ISSUE THREAD

**Issue by andreshamedfernandez** [longhorn/longhorn#2561] opened 2021-05-04 07:08 UTC
On 29-04-2021 at 02:18:26 we encountered some network disconnection. On to different clusters we encounterd the replicas to come into faulted status. When trying to reattach the replicas by restarting the deployment we encounter the following errors:
```
FailedAttachVolume	14 secs ago	AttachVolume.Attach failed for volume "pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b" : rpc error: code = Aborted desc = The volume pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b is attaching

FailedAttachVolume	22 secs ago	AttachVolume.Attach failed for volume "pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b" : attachdetachment timeout for volume pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b

FailedMount	27 secs ago	Unable to attach or mount volumes: unmounted volumes=[prometheus-rancher-monitoring-prometheus-db], unattached volumes=[rancher-monitoring-prometheus-token-w4vmk config prometheus-nginx nginx-home config-out tls-assets prometheus-rancher-monitoring-prometheus-db prometheus-rancher-monitoring-prometheus-rulefiles-0]: timed out waiting for the condition

FailedAttachVolume (4)	2.4 mins ago	AttachVolume.Attach failed for volume "pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b" : volume attachment is being deleted

Scheduled	2.4 mins ago	Successfully assigned cattle-monitoring-system/prometheus-rancher-monitoring-prometheus-0 to tekub55
```
The only solution we have now is stopping the deployment removing the replica and starting the deployment. With loss of data as a result. (prometheus)

We don't understand why this specific persistent volume fails and keeps in this failed status and why it won't reattach.

**Comment by jenting** [comment] 2021-05-05 10:57
Can you please generate a support bundle and attach it here _or_ send it to longhorn-support-bundle@suse.com?
Thank you.

**Comment by shuo-wu** [comment] 2021-05-10 08:25
Did you try to reattach volume `pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b` around `2021-05-03T09:44:41Z`?

The volume somehow get stuck in `attaching` state after receiving the reattachment calls:
```
2021-05-03T09:50:30.507397576Z time="2021-05-03T09:50:30Z" level=info msg="GRPC request: {\"node_id\":\"tekub55\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"fromBackup\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"30\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1614692751072-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b\"}"
2021-05-03T09:50:30.507415376Z time="2021-05-03T09:50:30Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b\" node_id:\"tekub55\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"fromBackup\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"30\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1614692751072-8081-driver.longhorn.io\" > "
2021-05-03T09:50:30.510229902Z time="2021-05-03T09:50:30Z" level=error msg="GRPC error: rpc error: code = Aborted desc = The volume pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b is attaching"
2021-05-03T09:50:31.514055335Z time="2021-05-03T09:50:31Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume"
......
2021-05-03T16:49:01.723227583Z time="2021-05-03T16:49:01Z" level=info msg="GRPC request: {\"node_id\":\"tekub55\",\"volume_capability\":{\"AccessType\":{\"Mount\":{\"fs_type\":\"ext4\"}},\"access_mode\":{\"mode\":1}},\"volume_context\":{\"fromBackup\":\"\",\"numberOfReplicas\":\"3\",\"staleReplicaTimeout\":\"30\",\"storage.kubernetes.io/csiProvisionerIdentity\":\"1614692751072-8081-driver.longhorn.io\"},\"volume_id\":\"pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b\"}"
2021-05-03T16:49:01.723243683Z time="2021-05-03T16:49:01Z" level=info msg="ControllerServer ControllerPublishVolume req: volume_id:\"pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b\" node_id:\"tekub55\" volume_capability:<mount:<fs_type:\"ext4\" > access_mode:<mode:SINGLE_NODE_WRITER > > volume_context:<key:\"fromBackup\" value:\"\" > volume_context:<key:\"numberOfReplicas\" value:\"3\" > volume_context:<key:\"staleReplicaTimeout\" value:\"30\" > volume_context:<key:\"storage.kubernetes.io/csiProvisionerIdentity\" value:\"1614692751072-8081-driver.longhorn.io\" > "
2021-05-03T16:49:01.731302055Z time="2021-05-03T16:49:01Z" level=error msg="GRPC error: rpc error: code = Aborted desc = The volume pvc-d91ca2f1-a734-43cf-ba67-a72648fa592b is attaching"
2021-05-03T16:50:01.275747075Z time="2021-05-03T16:50:01Z" level=info msg="GRPC call: /csi.v1.Controller/ControllerPublishVolume"
```

Since the log of the longhorn manager pod (on node `tekub55`) that handles the related volume engine somehow missed, I don't know the root cause. 
All replicas on other nodes were started successfully. Then I guess the replica/engine on node `tekub55` cannot be started or the related instance manager didn't work correctly. Since I found that the longhorn manager pod on node `tekub55` starts from `2021-05-06T04:56:52Z` and there were tons of the following error log, which means it lost the connection with the related instance manager pods. If this disconnection already existed in `2021-05-03`, the volume stuck in attaching may be caused by this issue:
```
2021-05-06T04:56:52.801918244Z time="2021-05-06T04:56:52Z" level=error msg="error receiving next item in engine watch: rpc error: code = Unavailable desc = transport is closing"
```

Please check if the manager pod is still printing the error or not. If YES, you can directly delete the pod. Then Longhorn will restart a new one and try to do recovery automatically.


Some background:
1. longhorn manager pods are used to update the state from volumes and the related replicas, engines...
2. instance manager pods are used to launch the actual engine/replica processes. 
3. A volume being attached means all processes are launched and the manager pod updated the state based on the processes state.
4. All Longhorn workloads are in namespace `longhorn-system`

**Comment by andreshamedfernandez** [comment] 2021-05-10 09:36
We didn't try to reattach the pvc, we did restart the deployment and then we got that error message.
We  did remove the volume and restarted the deployment because that was the only way we could get our prometheus monitoring working again.
Now everything is working fine but we lost the data in the process.

**Comment by shuo-wu** [comment] 2021-05-10 12:01
Does restarting deployment mean scaling down then re-scaling up? If YES, this will lead to volume reattachment. 

Besides, does the data loss mean the volume removal? Next time when you encounter a similar issue, you can ask for help rather than directly removing the volume. Most of the time the volume can be recovered, or at least the data can be recovered. And I suggest you set a backup store to prevent data loss.

Although Prometheus seems to work fine right now. Just in case, please check the longhorn manager pod log on node `tekub55` and see if you need to restart it.

**Comment by innobead** [comment] 2021-06-21 03:58
@longhorn/qa This is a backport issue, and please verify if this is fixed in the latest build, then close it.

**Comment by meldafrawi** [comment] 2021-06-28 20:43
Validation: **PASSED**

Longhorn version: v1.1.2 & master `2021-06-28`

[Test steps](https://longhorn.github.io/longhorn-tests/manual/release-specific/v1.1.2/instance-manager-streaming-connection-recovery)

**Closed** 2021-06-28 20:43 UTC
Labels: area/manager, backport-needed/1.1.2, kind/bug
