### ISSUE TITLE
[BUG] Replica should get rebuilt even If a snapshot corrupt in a replica.

### ISSUE THREAD

**Issue by khushboo-rancher** [longhorn/longhorn#1253] opened 2020-04-27 19:20 UTC
**Describe the bug**
Scenario where there is wrong info in ```parent``` tag in snapshot meta data i.e. volume-snap.img.meta. Replica should get rebuild from other healthy replica. 

**To Reproduce**
1. Create a longhorn volume (3 replicas 3 nodes) attach it to one pod.
2. Write data to volume and take snapshots (3 times). say snapshots s1, s2 s3
3. Go to one of the node and give a dummy value in parent tag in s2 - volume-snap.img.meta
e.g.
```{"Name":"volume-snap-03dfb213-c00d-4b52-91bb-b6a1161f7ff0.img","Parent":"dummy.img","Removed":true,"UserCreated":true,"Created":"2020-04-22T20:32:23Z","Labels":null}``` 

**Expected behavior**
Replica should be identified as bad and rebuild from other healthy replica.

**Environment:**
 - Longhorn version: master
 - Kubernetes version: v1.17.4
 - Node OS type and version: 4.4.0-177-generic #207-Ubuntu

**Comment by yasker** [comment] 2020-05-04 03:53
Maybe related to https://github.com/longhorn/longhorn/issues/1243

**Comment by shuo-wu** [comment] 2020-05-07 04:27
This issue is similar to #1243: There is something wrong with the replica. But the replica can be still available as long as the issue is not triggered by some specific operations.

For this issue, the only place that the replica reads the (invalid) snapshot meta file is in the replica construction function. This means the replica always works fine as long as the volume is not reattached. 

When users try to reattach a volume whose replicas contain invalid snapshot meta info, Longhorn should mark the replicas as ERROR and rebuild them. But now **the volume will loop in attach and detach**. I think the key point of this issue is to fix this bug.

@yasker @khushboo-rancher What do you think about it?

**Comment by yasker** [comment] 2020-05-07 05:08
@shuo-wu Make sense. Why volume will be in the loop? Is it related to #995 ?

**Comment by shuo-wu** [comment] 2020-05-07 05:16
Yes. The root causes may be different. But in both cases, the engine needs to mark the replica as ERROR if it cannot use the replica as the backend.

**Comment by yasker** [comment] 2020-05-07 05:23
On the `replica is open` case, once we closed the replica then it would be fine. Not sure if we want to mark it as error.

Here we definitely need to mark them as error.

**Comment by shuo-wu** [comment] 2020-05-07 05:39
Do you mean that we don't need to mark the replica as ERROR immediately if the replica is not closed in issue #995? As long as the replica cannot be used as backend during the attachment/reattachment, the engine should mark it as ERROR, right?

And I plan to refactor [this part](https://github.com/longhorn/longhorn-engine/blob/4bf6f2b65fc8b64898ff76b788fe1dfb30d54003/pkg/controller/control.go#L472) for these 2 issues:
1. If the engine cannot use the replica as backend or cannot get the info, the engine will directly add the replica with mode ERROR later.
2. If the size is different among all replicas, the controller will pick up the largest one then mark all mismatching replicas as ERROR. Or we can directly error out for this case...

**Comment by yasker** [comment] 2020-05-07 05:50
Thinking about it, once #1304 implemented, the `open` replica will not be a problem even we mark them as error replicas. They will be rebuilt quickly later. So it will be fine.

Regarding the size, we can error out directly then. Better if we figure out a way to stop auto-reattach from working in this case.

**Comment by shuo-wu** [comment] 2020-05-07 06:08
The most naive/simplest way to stop continuous auto-reattach is by introducing the backoff (with max retry) mechanism. Otherwise, the engine process needs to somehow tell the instance manager/longhorn manager the error reason before exit.

**Comment by yasker** [comment] 2020-05-07 06:10
Back-off is fine if we are dealing with unknown conditions. But if it's known to be bad and there is no point to retry if possible.

**Comment by shuo-wu** [comment] 2020-05-07 06:17
For the possible size inconsistency issue we discussed above (although I don't know how to trigger it now), can we directly mark all replicas as ERROR so that there will be no auto attachment? 
Or since we haven't encountered that issue, it's actually a kind of unknown condition and auto reattachment is fine for the case.

**Comment by yasker** [comment] 2020-05-07 06:54
I think we should stop the auto attach for size mismatch for sizes. It's weird that sizes become different, since expansion success will not result in this situation, and the expansion failure should stop the auto attach from happening.

**Comment by shuo-wu** [comment] 2020-05-07 07:08
That's why I say "`I don't know how to trigger it now`".  Anyway, I will mark all replicas as ERROR for the case so that the volume will become `Faulted`.

**Comment by yasker** [comment] 2020-05-07 19:49
### Remember to validate https://github.com/longhorn/longhorn/issues/995 as well when this is fixed.

**Comment by shuo-wu** [comment] 2020-05-11 06:41
Right now the key point is that when we need to disable the auto reattachment. Hence we should check all possible causes of engine corruption first.

After this engine PR gets merged, theoretically the engine starting corruption may be caused by one of the following cases:
1. There are invalid parameters. This shouldn't happen since all parameters are set by the longhorn manager rather than the users. And the re-start check should detect the errors before sending the creation call to the instance manager.
2. All backends/replicas are unavailable. # 1253 and # 995 can be attributed to this situation. And I don't think auto reattachment makes sense for this and it's fine to disable the reattachment for this case.
3. Frontend starting failure. # 1240 is related to this situation. This failure may be caused by the leftover of the old engine frontend and the reattachment may work for this case.
4. Unknown gRPC server crash. I don't know if this will happen and what we can do for this case. I think I don't need to consider this before we observe this kind of issue.

It seems that we can focus on backend failure and frontend failure. But Longhorn cannot distinguish which one leads to the engine starting corruption before implementing [this feature](https://github.com/longhorn/longhorn/issues/677). Hence for safety purposes, I prefer to directly disable the auto reattachment for the engine crashed in the starting phase (by setting all replicas' `Spec.FailedAt`).

**Comment by yasker** [comment] 2020-05-11 21:03
@shuo-wu How will we tell if the engine is in the starting phase or not? Now I think #995 is beyond the scope for the current release now. We can move it to the next stable release.

Also, in the cases above, we can disable auto-attachment for case 3 as well.

**Comment by shuo-wu** [comment] 2020-05-12 10:13
Test 1:
Test if the volume still works fine when there is an invalid replica/backend in the engine starting phase.
1. Create a pod using Longhorn volume.
2. Write some data to the volume then get the md5sum.
3. Create a snapshot.
4. Repeat step2 and step3 for 3 times. Then there should be 3 snapshots.
5. Randomly pick up a replica and manually messing up the snapshot metafile.
6. Delete the workload and wait for volume detached.
7. Recreate the workload and wait for the volume attached.
8. Check if the volume is Degraded and the chosen replica is ERR once the volume attached.
9. Wait for volume rebuild and volume becoming Healthy.
10. Check volume data.
11. Check if the volume still works fine by r/w data and creating/removing snapshots.

Test 2:
Test if the volume won't be auto reattached when there is no valid replica/backend in the engine starting phase and the auto-salvage is disabled.
1. Disable the auto-salvage setting.
2. Create and attach a volume.
3. Create 3 snapshots for the volume.
4. Manually messing up the snapshot metafile for all replicas.
5. Detach the volume and wait for volume detached.
6. Reattach the volume.
7. Check if the volume is Faulted and if all replicas are failed.
8. Check if the volume is not auto reattached.

**Comment by yasker** [comment] 2020-05-12 22:33
@shuo-wu Can you file another issue to track all replica went bad during starting problem?

**Comment by yasker** [comment] 2020-05-12 22:43
Pre-merged Checklist
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] [area/ui] Has the UI issue filed or ready to be merged?
* [ ] [require-automation-e2e] Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] [require-automation-engine] Has the engine integration test been merged?
* [ ] [require-doc] Has the necessary document PR submitted or merged?

**Comment by shuo-wu** [comment] 2020-05-13 04:08
For the case that there is no valid replica/backend in the engine starting phase and the volume gets stuck in the detach-reattach loop. It is a different issue and it's complicated. We will track it in #1330

**Closed** 2020-05-28 21:58 UTC
Labels: area/engine, bug, priority/2, require/automation-e2e, require/automation-engine
