### ISSUE TITLE
[BUG] Worker node cordoned does not change the state of nodes in Longhorn

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1287] opened 2020-05-02 20:24 UTC
**Describe the bug**
Worker node cordoned does not change the state of nodes in Longhorn

**To Reproduce**

- Deploy longhorn in a cluster
- Cordon a worker node
- The node is still seen in "Schedulable" state.

**Expected behavior**
The node should be marked with a state to reflect that it has been cordoned.

**Environment:**
 - Longhorn version: master - 05/01/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: rke DO linux

**Comment by yasker** [comment] 2020-05-04 06:19
Related to #1278

**Comment by yasker** [comment] 2020-05-04 06:47
We can automatically disable the Longhorn node schedule when Kubernetes cordon the node. Since the user don't want any workload to be run on the node, it's highly likely they don't want any new replica to be created on the node as well. But just in case, we need to add a setting in the `Scheduling` section: `disable-scheduling-when-cordoned`. The default value would be `true`.

We can add a new node condition type `Cordoned`. And when the node is cordoned, update the condition regardless of the setting `disable-scheduling-when-cordoned`. If the setting was set to true, and node is cordoned, we will skip the node in the scheduler.

UI needs to respond to the condition as well by showing the node as unschedulable.

See https://github.com/longhorn/longhorn/issues/1278#issuecomment-623278449 for some information about cordon.

**Comment by boknowswiki** [comment] 2020-05-10 22:47
@smallteeths  could you help to clarify two questions?
1. Since we need to provide a setting for customer to decide if they would like to cordon the node or not if k8s disable schedule the node. What API do you expect, could you show me an example?

2. On UI node section, the status shows "Schedulable" in green box, and when you put the mount on the green box "Schedulable", it shows "node xxx is ready", could you help to clarify how does UI get this information? Like from which API?

Thanks,
Bo

**Comment by yasker** [comment] 2020-05-11 03:21
@boknowswiki For the setting part, you can refer to https://github.com/longhorn/longhorn-manager/blob/master/types/setting.go . The frontend will detect this automatically.

**Comment by boknowswiki** [comment] 2020-05-11 16:36
@yasker ,  do you know from UI side, what's the API call to get the node status? I would like to use that do verify longhorn-manager replying the right status.

**Comment by boknowswiki** [comment] 2020-05-11 23:27
Test case for this issue, the steps are below:

Case 1 with "Setting/general/disable-schedule-cordoned-node" set to True.

1. Create 3 nodes (e.g. node1/node2/node3) cluster and deploy longhorn in this cluster. 
2. Create a longhorn-volume(e.g. volum1), longhorn-manager should create replicas on all three nodes(node1/node2/node3). 
3. Set cordon on one node(e.g. node1), and the status for this node should become "Unschedulabe or Cordoned".
4. Create another new longhorn volume(e.g. volume2), and longhorn-manager should only schedule replicas on the other two nodes (e.g. node2 and node3). Verified volume1 has three replicas on node1/node2/node3, volume2 has three replicas on node2/node3. Remove volume1 and volume2.
5. Unset the cordoned node(e.g. node1), and the status for this node should become "Schedulable".
6. Create another new longhorn volume(volume3), and longhorn-manager should schedule replicas on all three nodes(node1/node2/node3). After verifiying volume3 has three replicas on node1/node2/node3, remove volume3.

Case 2 with "Setting/general/disable-schedule-cordoned-node" set to False.

1. Create 3 nodes (e.g. node1/node2/node3) cluster and deploy longhorn in this cluster. 
2. Create a longhorn-volume(e.g. volum1), longhorn-manager should create replicas on all three nodes(node1/node2/node3). 
3. Set cordon on one node(e.g. node1), and the status for this node should still be "Schedulabe ".
4. Create another new longhorn volume(e.g. volume2), and longhorn-manager should schedule replicas on all three nodes (e.g. node1/node2/node3). Need to verify volume1 and volume2 each has three replicas on node1/node2/node3.
5. Unset the cordoned node(e.g. node1), and the status for this node should still be "Schedulable".
6. Create another new longhorn volume(volume3), and longhorn-manager should schedule replicas on all three nodes(node1/node2/node3). Verify volume3 has three replicas on all three nodes(node1/node2/node3).

@yasker , @meldafrawi , please let me know what do you think?

Thanks,
Bo

**Comment by boknowswiki** [comment] 2020-05-12 20:50
After discussed with @yasker , below is the order we check the "Schedulable":

1. Node needs to be in ready condition.
2. From the nodes which are ready, we check if the schedulable has been enabled or not on each node.
3. Check the node schedulable and settings related to schedule.
Note: for the third one, currently we are checking the k8s node status(cordon) and the setting we have "Disable Scheduling On Cordoned Node" for now.

@smallteeths the response for the "get node" API call is the same as we discussed last night, backend will return the final longhorn node status to UI.
Response cases:
1. K8s node cordoned and the "Disable Scheduling On Cordoned Node" is set, we return "True".
2. K8s node uncordoned and "Disable Scheduling On Cordoned Node" is set, we return "False".
3. K8s node cordoned and "Disable Scheduling On Cordoned Node" is not set, we return "False".
4. K8s node uncordoned and "Disable Scheduling On Cordoned Node" is not set, we return "False".

@yasker , @smallteeths : Please let me know if there is any misunderstanding or unclarity.

**Comment by yasker** [comment] 2020-05-12 23:11
@boknowswiki LGTM.

**Comment by boknowswiki** [comment] 2020-05-14 21:37
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [ ] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~

**Comment by sowmyav27** [comment] 2020-05-18 19:22
**Verified on latest master - 05/18/2020 - ui tag: `wangsiye/longhorn-ui:941d022`**

When a node is cordoned in Rancher, the node shows up as `Unschedulable` in Longhorn.

**Comment by boknowswiki** [comment] 2020-05-18 21:06
@meldafrawi , I will start to work on this test case today. Just make sure we don't duplicate our work. Please let me know if you have worked on this issue already.

**Comment by meldafrawi** [comment] 2020-05-21 02:15
Validation: **PASSED**
Longhorn Version: **v1.0.0-rc1**

**Closed** 2020-05-28 22:04 UTC
Labels: area/kubernetes, area/manager, enhancement, highlight, priority/2, require/automation-e2e
