### ISSUE TITLE
[BUG] Detached Volume Stuck in Attached State During Node Eviction

### ISSUE THREAD

**Issue by WebberHuang1118** [longhorn/longhorn#9781] opened 2024-11-11 10:34 UTC
## Describe the bug

A detached volume is stuck in the attached state during node eviction, and the volume can't go back to the detached state

## To Reproduce
- Creating a three-node cluster
- Creating a volume `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90` with three replicas
- Attaching the volume to one of the nodes and detaching it
- Choosing one node (for example node2), disabling its `Node Scheduling` and enabling `Eviction Requested`
- The volume will be kept attached with a stopped replica which resides on the evicted node
  - Replica `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90-r-f763ee06` running on node-0
  - Replica `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90-r-6de8993b` running on node-1
  - Replica `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90-r-21988b84` running on node-2
  - Replica `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90-r-44369fec` stopped on node-2

## Expected behavior
Volume `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90` should be back to detached state

## Support bundle for troubleshooting
[supportbundle_d1e587b6-6921-420c-8e0d-a068c6cf110a_2024-11-11T08-57-30Z.zip](https://github.com/user-attachments/files/17700843/supportbundle_d1e587b6-6921-420c-8e0d-a068c6cf110a_2024-11-11T08-57-30Z.zip)

## Environment
 - Longhorn version: v1.4.3
 - Harvester: v1.2.1
 - Impacted volume (PV): `pvc-d743c883-692e-46d0-a3a5-9cb485c0eb90`

## Workaround and Mitigation
-  Reducing volume's replica count to 2 before node eviction

**Comment by derekbit** [comment] 2024-11-11 10:38
@chriscchien Could you check if the issue is reproducible in v1.6.3 and v1.7.3? Thank you.

**Comment by chriscchien** [comment] 2024-11-11 12:26
I can reproduce this issue in v1.7.2 and v1.6.3 by below steps
1. Dynamic provision a volume, wait volume healthy.
2. Scale down workload to `0` to detach the volume.
3. From UI, choose one replica node and disabling the Node Scheduling and enabling Eviction Requested **immediately** after step 2.
4. Volume kept attached.
      -  in v1.6.3, 1 stopped replica and 3 running replicas observed like this ticket mentioned.
      -  in v1.7.2, 3 replicas kept in running state, no extra stopped observed.


v1.7.2 - all replica running (evict ip-172-31-32-129)
```bash
> kl get nodes.longhorn.io
NAME               READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
ip-172-31-37-57    True    true              True          3m53s
ip-172-31-40-145   True    true              True          3m53s
ip-172-31-32-129   True    false             True          3m52s
>
> kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE              AGE
pvc-94b6d534-ae8b-408b-8b9b-94f6b0e83b4d   v1            attached   healthy                  2147483648   ip-172-31-37-57   2m55s
>
> kl get replicas
NAME                                                  DATA ENGINE   STATE     NODE               DISK                                   INSTANCEMANAGER                                     IMAGE                               AGE
pvc-94b6d534-ae8b-408b-8b9b-94f6b0e83b4d-r-b087166e   v1            running   ip-172-31-40-145   1d488181-b38c-402c-8944-b75c2226319c   instance-manager-682be07898be605a482901d3854583f9   longhornio/longhorn-engine:v1.7.2   3m1s
pvc-94b6d534-ae8b-408b-8b9b-94f6b0e83b4d-r-80b9b644   v1            running   ip-172-31-37-57    edff8df0-e5f7-4799-b093-6eb24331b4ff   instance-manager-f7ab0aa2aa492fb64d6aa19031c57c1f   longhornio/longhorn-engine:v1.7.2   3m1s
pvc-94b6d534-ae8b-408b-8b9b-94f6b0e83b4d-r-b30a5343   v1            running   ip-172-31-32-129   f8a523fa-195c-41ff-bae6-83865f278af0   instance-manager-0e8c361d05c1cf0fa4a6373f22853e8c   longhornio/longhorn-engine:v1.7.2   84s

```

v1.6.3 - 3 replics running and 1 stopped replica (evict ip-172-31-37-57 )
```bash
> kl get nodes.longhorn.io
NAME               READY   ALLOWSCHEDULING   SCHEDULABLE   AGE
ip-172-31-37-57    True    false             True          3m35s
ip-172-31-32-129   True    true              True          3m32s
ip-172-31-40-145   True    true              True          3m34s
>
> kl get volume
NAME                                       DATA ENGINE   STATE      ROBUSTNESS   SCHEDULED   SIZE         NODE               AGE
pvc-a4c3e035-653e-4652-89e9-dd06c25baf62   v1            attached   healthy                  2147483648   ip-172-31-40-145   2m29s
>
> kl get replicas
NAME                                                  DATA ENGINE   STATE     NODE               DISK                                   INSTANCEMANAGER                                     IMAGE                               AGE
pvc-a4c3e035-653e-4652-89e9-dd06c25baf62-r-a9410bb4   v1            running   ip-172-31-40-145   1d488181-b38c-402c-8944-b75c2226319c   instance-manager-8c0e16cf9c459267bd4d71b9daa248e1   longhornio/longhorn-engine:v1.6.3   2m47s
pvc-a4c3e035-653e-4652-89e9-dd06c25baf62-r-fd413e43   v1            running   ip-172-31-32-129   f8a523fa-195c-41ff-bae6-83865f278af0   instance-manager-ffb1c3aff0267f3fb796535d793464f7   longhornio/longhorn-engine:v1.6.3   2m47s
pvc-a4c3e035-653e-4652-89e9-dd06c25baf62-r-dae675b5   v1            running   ip-172-31-37-57    edff8df0-e5f7-4799-b093-6eb24331b4ff   instance-manager-cb6bb2ff2d85ed7981d4a7f9aed44aa7   longhornio/longhorn-engine:v1.6.3   2m46s
pvc-a4c3e035-653e-4652-89e9-dd06c25baf62-r-2d2bb614   v1            stopped                                                                                                                                                     2m4s
```

**Comment by c3y1huang** [comment] 2024-11-14 07:47
Reproduced on the current active Longhorn versions; did not check v1.4.3.

Cause:

The volume eviction controller updated the attachment ticket after the volume attachment controller had already detached the volume.

```
2024-11-14T07:08:22.467291107Z time="2024-11-14T07:08:22Z" level=info msg="Volume e2e-test-volume-123 is selected to detach from node ip-10-0-2-13" func="controller.(*VolumeAttachmentController).handleVolumeDetachment" file="volume_attachment_controller.go:555" controller=longhorn-volume-attachment longhornVolumeAttachment=e2e-test-volume-123 node=ip-10-0-2-13

2024-11-14T07:08:31.147398370Z time="2024-11-14T07:08:31Z" level=info msg="Volume e2e-test-volume-123 is selected to attach to node ip-10-0-2-13, ticket +&{volume-eviction-controller-e2e-test-volume-123 volume-eviction-controller ip-10-0-2-13 map[disableFrontend:any] 0}" func="controller.(*VolumeAttachmentController).handleVolumeAttachment" file="volume_attachment_controller.go:676" controller=longhorn-volume-attachment longhornVolumeAttachment=e2e-test-volume-123 node=ip-10-0-2-13
```

**Comment by c3y1huang** [comment] 2024-11-14 08:51
**Workaround for v1.4.3:** Enable the `Replica Node Level Soft Anti-Affinity` setting, and Longhorn will automatically detach the volume.

**Comment by WebberHuang1118** [comment] 2024-11-14 09:32
> **Workaround for v1.4.3:** Enable the `Replica Node Level Soft Anti-Affinity` setting, and Longhorn will automatically detach the volume. /cc @WebberHuang1118

Hi @c3y1huang
Does one node require multiple disks to make this workaround work?  What if the three nodes only have one disk? Thanks.

**Comment by c3y1huang** [comment] 2024-11-27 02:29
Move this back to implementation as this has introduced a regression failure.
https://github.com/longhorn/longhorn/issues/9857

**Comment by c3y1huang** [comment] 2024-11-27 05:36
> Move this back to `Analysis and Design` as this has introduced a regression failure. #9857

**Proposed fix:**

Precheck there are valid replica candidates before attaching the volume; otherwise, avoid volume attachment.

**Comment by derekbit** [comment] 2024-12-04 03:20
@c3y1huang The PR is merged. We can move it forward. Thank you.

**Comment by chriscchien** [comment] 2024-12-05 06:48
Verified **pass** on longhorn master(https://github.com/longhorn/longhorn-manager/commit/bb0a41dba42cf7fe1bebdd3f2e15efec8eb896ff)

Following test [steps](https://github.com/longhorn/longhorn/issues/9781#issuecomment-2468059440), volume detached successfully.

**Closed by chriscchien** 2024-12-05 06:48 UTC
Labels: kind/bug, priority/0, require/auto-e2e-test, area/volume-replica-rebuild, require/qa-review-coverage, require/backport, backport/1.6.4, backport/1.7.3
