### ISSUE TITLE
[BUG] Replicas get moved, when node goes for maintenance

### ISSUE THREAD

**Issue by wzrdtales** [longhorn/longhorn#5495] opened 2023-03-06 18:53 UTC
Related to https://github.com/longhorn/longhorn/issues/1958

When i.e. kured prepares a machine for a short maintenance restart, it will properly use the drain feature. However, this will cause longhorn **ALWAYS** to rebuild replicas, even so this is completely unnecessary.

The handling for this is just not well implemented, is there any way to instruct longhorn to **REUSE** the existing replica? Longhorn must be able to handle such normal and easy operations, unless you as the creators have a secret plan to destroy the lifetime of all the SSDs out there, in this case yes this makes totally sense!

**Comment by innobead** [comment] 2023-03-07 05:00
I assume the live replica on the drained node should become error state and failed, so the volume controller will request to create a new replica based on https://longhorn.io/docs/1.4.0/references/settings/#replica-replenishment-wait-interval, and see if there is a failed replica able to reuse. 

This is a quite general process w/o considering an intended failed replica caused by the drain. Probably we should have a gradual case for intended draining for better space efficiency. 

@shuo-wu @derekbit @PhanLe1010 any thoughts?

**Comment by shuo-wu** [comment] 2023-03-08 03:18
> This is a quite general process w/o considering an intended failed replica caused by the drain.

That's why we launch setting `replica-replenishment-wait-interval`. Does not it work? If users directly do drain without eviction (via Longhorn GUI), Longhorn does not start rebuilding immediately.

**Comment by camrossi** [comment] 2024-11-28 09:42
I think I am also seeing the same...
I upgrade my node OS following this process:

1. Cordon the node
2. Drain The node
3. Upgrade 
4. Uncordon 


The whole process took probably less than 5min. After the node came back online all the replicas where marked as failed. That is expected but they where ALL moved away and re-built on another node.

I am not really sure if this is expected or not in the end. 
I am running 1.7.2
Thanks !

**Comment by innobead** [comment] 2024-12-30 10:35
> whole process took probably less than 5min. After the node came back online all the replicas where marked as failed. That is expected but they where ALL moved away and re-built on another node.

https://longhorn.io/docs/1.7.2/maintenance/maintenance/#updating-the-node-os-or-container-runtime Longhorn will just do replica rebuilding if it can't reuse failed replicas from the maintenance node. 

>Uncordon the node. Longhorn will automatically re-enable the node scheduling. If there are existing replicas on the node, Longhorn might use those replicas to speed up the rebuilding process. You can set the [Replica Replenishment Wait Interval](https://longhorn.io/docs/1.7.2/references/settings#replica-replenishment-wait-interval) setting to customize how long Longhorn should wait for potentially reusable replica to be available.

**Closed as completed** 2024-12-30 10:35 UTC
Labels: kind/bug, component/longhorn-manager, area/volume-replica-scheduling, area/space-efficiency
