### ISSUE TITLE
[Question] Dose longhorn plays nice with my ssd disks?

### ISSUE THREAD

**Issue by liyimeng** [longhorn/longhorn#2303] opened 2021-03-06 19:10 UTC
**Question**
Hi longhorn experts! 

I am wondering if longhorn plays nice with ssd disks. I mean every SSD has write limits. whenever I see longhorn rebuild replica, it seems to write a lot more than necessary, this likely hurt my ssd and short its life span a lot.  What is actually happening when rebuild occurs in these scenarios:
- A replica fails because of node reboot,  will longhorn rebuild replica on the same node or on anther node?
   - If rebuild on the same node, will longhorn re-use the data, only write the diff to catch up the healthy one, or it re-write everything from scratch?
  - If rebuild on the another node, when/how longhorn clean up the old data? 
- Same questions abov when there is temporary network disconnection  
- When replica rebuild, longhorn copy the head version of data, or copy the who snapshot chain?  I see there is an option to cleanup snapshot after rebuild. I think it is more disk friendly that only copy the head version, and cleanup snapshots on other replicas afterward, right?

**Comment by shuo-wu** [comment] 2021-03-09 03:53
1. To make Longhorn have a chance to reuse the existing data of the failed replica, you can set an appropriate value for setting `Replica Replenishment Wait Interval`. This setting will wait for an interval before creating a new replica. If the node or the network gets recovered during this interval, Longhorn can automatically try to reuse the failed replicas.
2. For replica rebuilding, Longhorn will copy all data including snapshots for the new replicas. Since the data among all replica should be exactly the same, no exception. For the backup or restore, Longhorn only handle the current/active data without any snapshot.

**Comment by liyimeng** [comment] 2021-03-09 07:03
> * To make Longhorn have a chance to reuse the existing data of the failed replica, you can set an appropriate value for setting `Replica Replenishment Wait Interval`. This setting will wait for an interval before creating a new replica. If the node or the network gets recovered during this interval, Longhorn can automatically try to reuse the failed replicas.

What happen with "reuse the failed replicas"? Do replica rebuilding as below? 
 
> * For replica rebuilding, Longhorn will copy all data including snapshots for the new replicas. Since the data among all replica should be exactly the same, no exception. For the backup or restore, Longhorn only handle the current/active data without any snapshot.

**Comment by shuo-wu** [comment] 2021-03-09 08:49
> > * To make Longhorn have a chance to reuse the existing data of the failed replica, you can set an appropriate value for setting `Replica Replenishment Wait Interval`. This setting will wait for an interval before creating a new replica. If the node or the network gets recovered during this interval, Longhorn can automatically try to reuse the failed replicas.
> 
> What happen with "reuse the failed replicas"? Do replica rebuilding as below?
> 
> > * For replica rebuilding, Longhorn will copy all data including snapshots for the new replicas. Since the data among all replica should be exactly the same, no exception. For the backup or restore, Longhorn only handle the current/active data without any snapshot.

It will find the data directory of the failed replica and compare it with the data of a healthy replica. If there is a mismatching, Longhorn will copy that part of the data chunk only. 
As for new replica rebuilding, Longhorn will directly copy all data from a healthy replica.

**Comment by liyimeng** [comment] 2021-03-09 12:10
@shuo-wu Thanks a lot! Some more question how efficient is the diff operation? So the best way to upgrade a node is to shutdown  all live traffic on it, right? And snapshots should be prune periodically?

**Comment by shuo-wu** [comment] 2021-03-10 03:03
1. Longhorn will calculate the checksums then compare them before actually copying data.
2. You may need to cordon and evict all workloads as well as all Longhorn components for this node before upgrading or maintaining it. For Longhorn components eviction, it's better to do it on Longhorn UI - Node page. Others can be done by `kubectl`
3. Snapshot will take extra space. If you don't need so many snapshots to store historical data, you can set up a recurring job to make sure that there is a certain amount of snapshots at most in the volume.

**Comment by ElisaMeng** [comment] 2021-03-10 12:38
> * Longhorn will calculate the checksums then compare them before actually copying data.
> * You may need to cordon and evict all workloads as well as all Longhorn components for this node before upgrading or maintaining it. For Longhorn components eviction, it's better to do it on Longhorn UI - Node page. Others can be done by `kubectl`

will evict cause replica rebuild? Or just make them as temporary unavailable, then get them caught up with replica on other nodes later?

> * Snapshot will take extra space. If you don't need so many snapshots to store historical data, you can set up a recurring job to make sure that there is a certain amount of snapshots at most in the volume.

**Comment by shuo-wu** [comment] 2021-03-11 02:35
The node/disk eviction via Longhorn UI will lead to new replica rebuilding first, then delete the replicas on the evicting node/disk. This won't hurt the HA or most of the volume functionalities. But if there is no other node available for the replica rebuilding, the eviction may get stuck, IIRC.

**Comment by liyimeng** [comment] 2021-03-11 14:41
This sounds worrying for me. If there are TB of data on the node (it is actually so common nowadays), longhorn either need to rewrite most of them  on the same node or rebuild all of them on another node. It cost so much to reboot a node! There  should be room to improve here, e.g. take a maintenance snapshot on active volumes when user decide to maintain the node, catch up to by copying diff between head and maintenance snapshot, doable?

**Comment by shuo-wu** [comment] 2021-03-12 08:58
Maintaining a node without rebuildings implicitly means degrading the HA for running volumes. To avoid HA downgrade as well as rebuilding, directly detaching the volumes contain replicas on this node may be a choice. If you can't stop volumes and really don't want the rebuilding, you can set an appropriate value for setting `Replica Replenishment Wait Interval` and make sure the maintenance time is smaller than this interval. Then you can directly shut down or reboot the node. This will make the replicas on this node temporarily become `failed` but no rebuilding. When the node is back, it will automatically reuse the failed replicas by comparing the data and fix the mismatching data chunks only.

**Comment by ElisaMeng** [comment] 2021-03-12 14:11
@shuo-wu I got the idea of reuse existing data. But I read somewhere in your report, saying reuse existing data is actually not efficient as expected, @yasker said it was caused by the size of chunk, which then result in rewrite most of user data. I therefore take this into concern.

**Comment by liyimeng** [comment] 2021-03-14 01:19
> @shuo-wu I got the idea of reuse existing data. But I read somewhere in your report, saying reuse existing data is actually not efficient as expected, @yasker said it was caused by the size of chunk, which then result in rewrite most of user data. I therefore take this into concern.

I mean https://github.com/longhorn/longhorn/issues/1948

**Comment by shuo-wu** [comment] 2021-03-15 03:17
All right. Consider #1948, in the worst case, there is only one big chunk in the block device. Reusing a replica won't be faster or save more bandwidth. But most of the time there is a filesystem on top of Longhorn volume then replica reuse could help. Longhorn will limit the size when comparing or transfer the files for 2 replicas, which is a goal of #1948

**Comment by liyimeng** [comment] 2021-03-15 19:03
@shuo-wu  not sure if I get you. Are you saying as long as there is a file system in the volume, longhorn will only write the diff? I did a quick test, it dose take a longtime to rebuild on the same node. Not sure if it is read and compare takes time, or it was rewriting.

**Comment by shuo-wu** [comment] 2021-03-16 03:50
I mean, when you format and use a filesystem in a Longhorn volume, the filesystem will arrange data locations rather than directly store the data in a single chunk. Then there won't be only one data chunk in the volume, and you don't need to worry about [this issue](https://github.com/longhorn/longhorn/issues/1948#issuecomment-791641308). 

Longhorn may take some time to check the existing data of a failed replica when reusing it, but his would save some bandwidth. And the rebuilding will speed up in most of the cases after #1948.

**Comment by ElisaMeng** [comment] 2021-03-17 15:00
@shuo-wu Thanks for the  explantation! I am happy now :)  please close this question.

**Closed** 2021-03-18 02:51 UTC
Labels: kind/question
