### ISSUE TITLE
[BUG] Backport lvol flush implementation fron `spdk:v24.01` to `spdk:v24.09` and fix memory leak

### ISSUE THREAD

**Issue by DamiaSan** [longhorn/longhorn#8730] opened 2024-06-10 07:41 UTC
## What's the task? Please describe

With the introducing of lvol flush implementation, the set_parent and set_parent_bdev functionality have a memory leak when the previous parent of the lvol is an external snapshot

## Additional context

The problem is that the backing device of the previous parent is not freed because there is an additional reference to it.
Possible candidates are:

- bdev.c _event_notify
- blob_bdev.c bdev_blob_destroy
- blobstore.c blob_close_cpl

**Comment by innobead** [comment] 2024-07-26 06:29
Added to milestone 1.8.0.

**Comment by derekbit** [comment] 2024-07-28 15:09
@DamiaSan 
How did you find the issue?  Is the issue still valid in spdk longhorn-24.05?

**Comment by DamiaSan** [comment] 2024-08-19 13:37
I found it executing the tests of set parent functionality with address sanitizer enabled.

**Comment by DamiaSan** [comment] 2024-09-11 11:40
Found the problem but don't know how to solve it. I have put a patch on SPDK Gerrit to Request For Comments : https://review.spdk.io/gerrit/c/spdk/spdk/+/24882. Maybe core maintainers can help me to find the right solution.

**Comment by derekbit** [comment] 2024-12-07 02:00
@DamiaSan Can you elaborate more on how to check the quantity of the memory leak before and after the fix? Then, QA can validate the fix by your steps. Thank you.

**Comment by DamiaSan** [comment] 2024-12-09 09:28
The lvol flush implementation was present in `longhorn-v24.01` SPDK branch but was removed from `longhorn-v24.05`, because the introduction of the reparent functionalities caused the memory leak.
The leak comes out when we have a lvol that is a clone of an external snapshot and we change the parent of the lvol. This operation is done during the online replica rebuild, which has been introduced with longhorn 1.7.0 release. But this release uses the `longgorn-v24.05` branch, which doesn't contain the lvol flush implementation as mentioned above.
So the test you are describing is impossible.

**Comment by innobead** [comment] 2024-12-09 09:56
If this is an invalid issue, then let's just close and add an invalid label.

**Comment by DamiaSan** [comment] 2024-12-09 09:59
> If this is an invalid issue, then let's just close and add an invalid label.

What do you mean by invalid? 
The memory leak was not so little and very difficult to find, I worked over it for a lot of time.

**Comment by innobead** [comment] 2024-12-09 10:07
Doesn't mean the issue is not valid anymore? @DamiaSan 

> But this release uses the longgorn-v24.05 branch, which doesn't contain the lvol flush implementation as mentioned above.
So the test you are describing is impossible.

**Comment by derekbit** [comment] 2024-12-09 10:17
> because the introduction of the reparent functionalities caused the memory leak.
> The leak comes out when we have a lvol that is a clone of an external snapshot and we change the parent of the lvol. This operation is done during the online replica rebuild, which has been introduced with longhorn 1.7.0 release. But this release uses the `longgorn-v24.05` branch, which

@DamiaSan 
Do you mean you resolve the memory leak in https://github.com/longhorn/spdk/pull/39 or somewhere?

**Comment by DamiaSan** [comment] 2024-12-09 10:22
> > because the introduction of the reparent functionalities caused the memory leak.
> > The leak comes out when we have a lvol that is a clone of an external snapshot and we change the parent of the lvol. This operation is done during the online replica rebuild, which has been introduced with longhorn 1.7.0 release. But this release uses the `longgorn-v24.05` branch, which
> 
> @DamiaSan Do you mean you resolve the memory leak in [longhorn/spdk#39](https://github.com/longhorn/spdk/pull/39) or somewhere?

Exactly, I have put the lvol flush implementation in the new branch because now the leak is solved.

**Comment by derekbit** [comment] 2024-12-09 10:25
@DamiaSan Thanks for the clarification
@innobead Do we need to backport the fix to `spdk:longhorn-v24.01`

**Comment by innobead** [comment] 2024-12-09 10:30
> @DamiaSan Thanks for the clarification. @innobead Do we need to backport the fix to `spdk:longhorn-v24.01`?

No. As V2 is still an alpha feature, let's just move forward in 1.8. As I mentioned and no need to backport anything, if no memory leak issues in the latest SPDK code base, this bug is not a valid issue anymore. Right? @derekbit @DamiaSan

**Comment by derekbit** [comment] 2024-12-09 10:32
Let's close the ticket, because the leak issue is fixed in https://github.com/longhorn/longhorn/issues/8730 (https://github.com/longhorn/spdk/pull/39).

**Comment by yangchiu** [comment] 2024-12-12 03:37
Verification passed on master-head (longhorn-instance-manager c9fe3a5) following [the test plan](https://github.com/longhorn/spdk/pull/39#issuecomment-2528501818).

#### Validation steps for the lvol flush implementation:

1. create a very high IO load over a volume with multiple replicas
```
# while true; do dd if=/dev/urandom of=/data/test-2 bs=1M count=512 status=none; done
```
2. suspend IO over the volume
```
# cksum test-2
2237860189 235929600 test-2
```
3. perform a snapshot of the volume
4. check that replicas contain the same data
```
# cksum test-2
2237860189 235929600 test-2
```

#### Validation steps for lvol flush memory leak:

1. check `spdk_tgt` memory usage that hosts a replica

```
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2684  1280 ?        Ss   02:21   0:00 /tini -- instance-manager --spdk-log all --spdk-cpumask 0x1 --enab
root           7  2.2  0.3 1938668 52816 ?       Sl   02:21   0:56 longhorn-instance-manager --debug daemon --spdk-enabled --listen 0
root          14 99.6  0.1 67163880 24704 ?      RLl  02:21  40:36 spdk_tgt -L all -m 0x1
root        1330  0.0  0.0   5068  4352 pts/0    Ss   02:27   0:00 /bin/sh
root        9426  0.0  0.0   7328  3072 pts/0    R+   03:02   0:00 ps aux

# top -p 14
top - 02:29:07 up 15 min,  0 users,  load average: 2.18, 2.43, 1.64
Tasks:   1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie
%Cpu(s): 33.6 us, 11.9 sy,  0.0 ni, 53.1 id,  0.6 wa,  0.0 hi,  0.1 si,  0.7 st
MiB Mem : 15990.21+total, 8174.621 free, 3168.656 used, 4988.508 buff/cache
MiB Swap:    0.000 total,    0.000 free,    0.000 used. 12821.55+avail Mem 

PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                       
 14 root      20   0 64.052g  23680  12032 R 100.0 0.145   7:29.95 reactor_0   
```

2. trigger replica rebuilding more than 10 times
3. check `spdk_tgt` memory usage that hosts the replica again. No increase in memory usage has been observed.
```
top - 03:02:00 up 47 min,  0 users,  load average: 2.01, 2.01, 2.08
Tasks:   1 total,   1 running,   0 sleeping,   0 stopped,   0 zombie
%Cpu(s): 34.3 us, 12.5 sy,  0.0 ni, 52.6 id,  0.1 wa,  0.0 hi,  0.0 si,  0.4 st
MiB Mem : 15990.21+total, 8100.398 free, 3231.539 used, 4999.848 buff/cache
MiB Swap:    0.000 total,    0.000 free,    0.000 used. 12758.67+avail Mem 

PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND                                                       
 14 root      20   0 64.052g  24704  12032 R 100.3 0.151  40:17.69 reactor_0  
```

**Closed by yangchiu** 2024-12-12 03:37 UTC
Labels: kind/bug, priority/0, area/v2-data-engine, area/spdk
