### ISSUE TITLE
[BUG] Upgrade Longhorn Rancher catalog app - Wait helm template failed. panic: interface conversion:

### ISSUE THREAD

**Issue by pulberg** [longhorn/longhorn#2121] opened 2020-12-18 21:04 UTC
**Describe the bug**
Errors upgrading Longhorn catalog app from 1.0.2 to 1.1.0

**To Reproduce**
1. Go to cluster, go to project, go to apps, see indicator that Longhorn upgrade is available
2. Click on `upgrade available`
3. ensure all values are correct (we are air-gapped, so i used the provided save-images/load-images scripts)

**Expected behavior**
Longhorn is upgraded to v1.1.0

**Error**

```Wait helm template failed. panic: interface conversion: interface {} is string, not map[string]interface {} goroutine 1 [running]: k8s.io/helm/pkg/strvals.(*parser).key(0xc000544f20, 0xc000579a70, 0xc00067d438, 0x8) /go/src/k8s.io/helm/pkg/strvals/parser.go:211 +0xfde k8s.io/helm/pkg/strvals.(*parser).key(0xc000544f20, 0xc000579860, 0xc00067d650, 0x5) /go/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad k8s.io/helm/pkg/strvals.(*parser).key(0xc000544f20, 0xc0005797d0, 0x0, 0x0) /go/src/k8s.io/helm/pkg/strvals/parser.go:215 +0x1ad k8s.io/helm/pkg/strvals.(*parser).parse(0xc000544f20, 0xc0005797d0, 0xe00) /go/src/k8s.io/helm/pkg/strvals/parser.go:133 +0x38 k8s.io/helm/pkg/strvals.ParseInto(0x7fffdc2900f2, 0xee9, 0xc0005797d0, 0xc000000180, 0x200000003) /go/src/k8s.io/helm/pkg/strvals/parser.go:85 +0xbf main.vals(0x0, 0x0, 0x0, 0xc000328bb0, 0x1, 0x1, 0x2e176f8, 0x0, 0x0, 0x2e176f8, ...) /go/src/k8s.io/helm/cmd/helm/install.go:420 +0x29d main.(*templateCmd).run(0xc0000ac360, 0xc00031af00, 0xc0000f7110, 0x1, 0x7, 0x0, 0x0) /go/src/k8s.io/helm/cmd/helm/template.go:139 +0x1dc k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).execute(0xc00031af00, 0xc0000f70a0, 0x7, 0x7, 0xc00031af00, 0xc0000f70a0) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:826 +0x465 k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).ExecuteC(0xc0000bc500, 0x8, 0x8, 0xc0000bc500) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:914 +0x2fc k8s.io/helm/vendor/github.com/spf13/cobra.(*Command).Execute(...) /go/src/k8s.io/helm/vendor/github.com/spf13/cobra/command.go:864 main.main() /go/src/k8s.io/helm/cmd/helm/helm.go:270 +0x7a : exit status 2```

**Environment:**
 - Longhorn version: v1.0.2
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: RKE v1.2.3
 - Node config
   - OS type and version: Ubuntu 18.04.5 LTS
   - CPU per node: 4
   - Memory per node: 8
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth and latency between the nodes: 1Gb
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMware ESXi 6.7

**Additional context**

gz#14149

**Comment by joshimoo** [comment] 2020-12-18 21:21
@pulberg just to verify did you run the load/save images against the updated images.txt file for the longhorn 1.1 release?
Since we added a new share-manager image.

Interestingly the above looks like a helm template failure.

**Comment by pulberg** [comment] 2020-12-18 21:24
Yes, here is the list of images - 

```
bat longhorn-images.txt
───────┬──────────────────────────────────────────────────
       │ File: longhorn-images.txt
───────┼──────────────────────────────────────────────────
   1   │ longhornio/longhorn-engine:v1.1.0
   2   │ longhornio/longhorn-instance-manager:v1_20201216
   3   │ longhornio/longhorn-share-manager:v1_20201204
   4   │ longhornio/longhorn-manager:v1.1.0
   5   │ longhornio/longhorn-ui:v1.1.0
   6   │ longhornio/csi-attacher:v2.2.1-lh1
   7   │ longhornio/csi-provisioner:v1.6.0-lh1
   8   │ longhornio/csi-resizer:v0.5.1-lh1
   9   │ longhornio/csi-snapshotter:v2.1.1-lh1
  10   │ longhornio/csi-node-driver-registrar:v1.2.0-lh1
```

**Comment by shuo-wu** [comment] 2020-12-21 03:38
The Longhorn images LGTM. 
I just google the error you provide. It seems that something is wrong with the config value of the Longhorn Helm options. Can you click `Edit as YAML` on the Longhorn upgrade page then paste the contents (remember to delete the sensitive data) here?

BTW, what's your Rancher version?

**Comment by pulberg** [comment] 2020-12-28 21:31
Rancher version v2.5.3

```
---
  image: 
    defaultImage: false
    longhorn: 
      manager: 
        repository: "longhornio/longhorn-manager"
        tag: "v1.1.0"
      engine: 
        repository: "longhornio/longhorn-engine"
        tag: "v1.1.0"
      ui: 
        repository: "longhornio/longhorn-ui"
        tag: "v1.1.0"
      instanceManager: 
        repository: "longhornio/longhorn-instance-manager"
        tag: "v1_20201216"
      shareManager: 
        repository: "longhornio/longhorn-share-manager"
        tag: "v1_20201204"
    csi: 
      attacher: 
        repository: "longhornio/csi-attacher"
        tag: "v2.2.1-lh1"
      provisioner: 
        repository: "longhornio/csi-provisioner"
        tag: "v1.6.0-lh1"
      nodeDriverRegistrar: 
        repository: "longhornio/csi-node-driver-registrar"
        tag: "v1.2.0-lh1"
      resizer: 
        repository: "longhornio/csi-resizer"
        tag: "v0.5.1-lh1"
      snapshotter: 
        repository: "longhornio/csi-snapshotter"
        tag: "v2.1.1-lh1"
  privateRegistry: 
    registryUrl: "my.customregistry.com/blah"
    registryUser: ""
    registryPasswd: ""
    registrySecret: "supersecretsecret"
  longhorn: 
    default_setting: true
  csi: 
    kubeletRootDir: ""
    attacherReplicaCount: ""
    provisionerReplicaCount: ""
    resizerReplicaCount: "3"
    snapshotterReplicaCount: "3"
  defaultSettings: 
    backupTarget: ""
    backupTargetCredentialSecret: ""
    allowRecurringJobWhileVolumeDetached: false
    createDefaultDiskLabeledNodes: true
    defaultDataPath: "/mnt/dockerdata/"
    defaultDataLocality: "disabled"
    replicaSoftAntiAffinity: false
    storageOverProvisioningPercentage: "200"
    storageMinimalAvailablePercentage: "25"
    upgradeChecker: true
    defaultReplicaCount: "3"
    guaranteedEngineCPU: "0.25"
    defaultLonghornStaticStorageClass: "longhorn"
    backupstorePollInterval: "300"
    taintToleration: "dedicated=true:NoSchedule; longhorn=true:NoSchedule"
    priorityClass: ""
    autoSalvage: true
    autoDeletePodWhenVolumeDetachedUnexpectedly: true
    disableSchedulingOnCordonedNode: true
    replicaZoneSoftAntiAffinity: true
    volumeAttachmentRecoveryPolicy: "wait"
    nodeDownPodDeletionPolicy: "do-nothing"
    allowNodeDrainWithLastHealthyReplica: false
    mkfsExt4Parameters: ""
    disableReplicaRebuild: false
    replicaReplenishmentWaitInterval: "600"
    disableRevisionCounter: false
    systemManagedPodsImagePullPolicy: "if-not-present"
    allowVolumeCreationWithDegradedAvailability: true
    autoCleanupSystemGeneratedSnapshot: true
  persistence: 
    defaultClass: true
    reclaimPolicy: "Delete"
    defaultClassReplicaCount: "3"
    recurringJobs: 
      enable: false
      jobList: ""
  ingress: 
    enabled: false
    host: "xip.io"
  service: 
    ui: 
      type: "Rancher-Proxy"
      nodePort: ""
  enablePSP: true
```

**Comment by pulberg** [comment] 2020-12-31 16:16
I need to make some progress on this so i will be entering a support ticket.

**Comment by pulberg** [comment] 2020-12-31 17:53
Wait helm template failed. 2020/12/31 17:51:03 Warning: Merging destination map for chart 'longhorn'. Overwriting table item 'ui', with non table value: longhornio/longhorn-ui 2020/12/31 17:51:03 Warning: Merging destination map for chart 'longhorn'. Overwriting table item 'engine', with non table value: longhornio/longhorn-engine 2020/12/31 17:51:03 Warning: Merging destination map for chart 'longhorn'. Overwriting table item 'instanceManager', with non table value: longhornio/longhorn-instance-manager 2020/12/31 17:51:03 Warning: Merging destination map for chart 'longhorn'. Overwriting table item 'manager', with non table value: longhornio/longhorn-manager Error: render error in "longhorn/templates/uninstall-job.yaml": template: longhorn/templates/uninstall-job.yaml:20:56: executing "longhorn/templates/uninstall-job.yaml" at <.Values.image.longhorn.manager.repository>: can't evaluate field repository in type interface {} : exit status 1

**Comment by shuo-wu** [comment] 2021-01-03 04:42
It seems that something is wrong with your Helm rendering. More accurately, according to the error message, the value types seem to be messed up. e.g.The error `at <.Values.image.longhorn.manager.repository>: can't evaluate field repository in type interface {} : exit status 1` is weird. According to the YAML you provide, the value should be `"longhornio/longhorn-manager"`  rather than an invalid type `interface {}`. 

I cannot reproduce this error with the config you provide (except for the air-gapped setting). Have you applied other operations before the upgrade?

**Comment by pulberg** [comment] 2021-01-04 16:03
Nothing else was/has been done, I'm simply trying to upgrade the current v1.0.2 install.

The only things I modify on the upgrade page are - 

1. Pick v1.1.0 from the "template version" dropdown.
2. Enter my private registry secret name.
3. Update the "static storageclass name" to what mine is called.
4. Click upgrade.
5. View multiple errors.

**Comment by shuo-wu** [comment] 2021-01-05 09:45
All right. Can you try the following to see if it's a **Rancher + Helm** issue?
1. Download this chart directory: https://github.com/longhorn/longhorn/tree/master/chart
2. Update the value files, or directly use `--set` when running the command in step3
3. Run the helm command to see if the rendering works fine. e.g.
```
cd <The Chart Directory>
helm template --dry-run --debug longhorn ./ --namespace longhorn-system
```

If it works fine, then there may be something wrong with **Rancher + Helm**. If NO, there may be something wrong with the values or Helm itself.

**Comment by shuo-wu** [comment] 2021-01-08 06:51
OK. I can reproduce this issue now. Here is the Reproducing step:
1. Deploy Longhorn via Rancher UI - Cluster Manager
  - Set version to `1.0.2`
  - Select `Default Image: False`
  - Select `Customize Default Settings: True` and Change`Default Longhorn Static StorageClass Name: longhorn`
2. Wait for deployment success then upgrade to v1.1.0. The error reported above will be shown.
  - Set version to `1.1.0` then not change any other existing parameters.

**Comment by c3y1huang** [comment] 2021-01-27 01:14
This seems to be more towards a rancher UI issue.

Observed that the payload passed from rancher UI include both old and new `answers` key values. This confused helm in rancher and caused panic.
![Screenshot-2021-01-26-18:49:54](https://user-images.githubusercontent.com/22583541/105927776-a1681c80-607f-11eb-87ad-6384c57f6c62.png)

A quick workaround could be to pass the changes as the YAML file this would pass in the changes as `valuesYaml` instead of `answers`.
![Screenshot-2021-01-27-09:11:51](https://user-images.githubusercontent.com/22583541/105927832-bba1fa80-607f-11eb-8b90-a2db94219159.png)
1. Select `1.1.0` in Template Version.
2. Click `Edit as YAML` on the Longhorn upgrade page
3. Click `Upgrade`.

**Comment by yasker** [comment] 2021-01-27 02:07
Thanks @c3y1huang . I saw you already filed a Rancher issue. Let's wait for the response to the issue before proceeding.

Move the issue to Icebox.

**Comment by innobead** [comment] 2021-08-25 10:05
This can be fixed at Longhorn side, closing.

**Closed** 2021-08-25 10:04 UTC
Labels: kind/bug, wontfix, area/deployment, priority/2

**Comment by pulberg** [comment] 2021-08-25 13:02
@innobead Please explain how to fix this on the Longhorn side as you stated.
