### ISSUE TITLE
[BUG] Filesystem corruption in Longhorn

### ISSUE THREAD

**Issue by diamonwiggins** [longhorn/longhorn#4070] opened 2022-06-02 20:27 UTC
## Describe the bug

We're working with a user who suffered filesystem corruption and data loss as a result when using Longhorn persistent volumes in their K8s cluster. At times the filesystem is mounted read only and requires a `fsck` for it be remounted. At other times there is data loss and a restore of the app's data needs to be done.

Whenever the issue occurs we see the following in the kernel log on the host:
```
May 23 08:22:24 rbcdevesh593 kernel: sd 4:0:0:1: [sde] FAILED Result: hostbyte=DID_OK driverbyte=DRIVER_SENSE cmd_age=8s
May 23 08:22:24 rbcdevesh593 kernel: sd 4:0:0:1: [sde] Sense Key : Medium Error [current] 
May 23 08:22:24 rbcdevesh593 kernel: sd 4:0:0:1: [sde] Add. Sense: Unrecovered read error
May 23 08:22:24 rbcdevesh593 kernel: sd 4:0:0:1: [sde] CDB: Write(10) 2a 00 00 c0 02 50 00 00 08 00
May 23 08:22:24 rbcdevesh593 kernel: blk_update_request: critical medium error, dev sde, sector 12583504
May 23 08:22:24 rbcdevesh593 kernel: Buffer I/O error on dev sde, logical block 1572938, lost async page write
```

In the Engine Manager we see a number of:
```
2022-05-23T17:36:20.394183717Z time="2022-05-23T17:36:20Z" level=error msg="Setting replica tcp://10.32.10.15:10015 to ERR due to: r/w timeout"
2022-05-23T17:36:20.394188199Z time="2022-05-23T17:36:20Z" level=info msg="Ignore set replica tcp://10.32.10.15:10015 to mode ERR due to it's ERR"
2022-05-23T17:36:20.394192727Z time="2022-05-23T17:36:20Z" level=error msg="Ignoring error because tcp://10.32.12.7:10000 is mode RW: tcp://10.32.10.15:10015: r/w timeout"
```

It's worth pointing out that in at least one instance we're able to correlate a spike in disk latency along with the volume becoming inoperable. Right now we think that the customer is suffering from these issues as a result of low disk performance. A benchmark we use for disk performance put p99 latency at around 13ms over a 2 minute period. No meaningful spikes in CPU/Mem have been observed. The customer is running Hadoop/HDFS in this cluster. We noticed in both outages that the node with the issue is where the `hdfs` pod was running, so that could be relevant here as well.

If disk performance is agreed upon to be at the root cause, we'd love to know if there are any more detailed requirements beyond what is listed here - https://longhorn.io/docs/1.2.4/best-practices/#minimum-recommended-hardware. It would also be helpful to know if there's a better way to remediate and/or mitigate this. For Longhorn volumes with multiple replicas, should a single replica having a corruption issue impact the workload from resuming elsewhere? If no, how can we better configure our deployments to ensure this is the case?

We'd love to get a second opinion as well as any help you can provide to determine RCA. A Longhorn support bundle is attached.

## To Reproduce

Have not been able to reproduce yet

## Expected behavior

For volumes configured with multiple replicas, we'd expect that the workload would automatically detach and restart on a node with a healthy replica

## Log or Support bundle
[longhorn-support-bundle_c9abc40c-f534-41d1-b4c8-9b946beea73c_2022-06-01T12-35-09Z.zip](https://github.com/longhorn/longhorn/files/8827594/longhorn-support-bundle_c9abc40c-f534-41d1-b4c8-9b946beea73c_2022-06-01T12-35-09Z.zip)

## Environment

 - Longhorn version: 1.2.2
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): kubectl(kURL addon - https://kurl.sh/docs/add-ons/longhorn)
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: https://kurl.sh/docs/install-with-kurl/
   - Number of management node in the cluster: 1
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: Red Hat Enterprise Linux Server 7.9
   - CPU per node: 8
   - Memory per node: 32GB
   - Disk type(e.g. SSD/NVMe): User said they are in a class of "Performance", but we're still getting this information
   - Network bandwidth between the nodes: TBD
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 10

**Comment by PhanLe1010** [comment] 2022-06-09 22:22
@diamonwiggins 

Thanks for reporting. 
Longhorn volume consists of 1 engine + multiple replicas.  A crash of 1 replica shouldn't corrupt the filesystem and this should be the behavior out of the box. I am investigating this topic. As the first step, we would want to find a way to reproduce the filesystem corrupting issue. Can you provide us:

* Could you provide the name of the volume that had the filesystem corruption? 
* The YAML manifest of the deployment (we want to deploy the exact same setup in our lab)

> Disk type(e.g. SSD/NVMe): User said they are in a class of "Performance", but we're still getting this information
Network bandwidth between the nodes: TBD

Do you have this information yet ?

**Comment by diamonwiggins** [comment] 2022-06-10 15:55
@PhanLe1010 Thanks so much for getting back to me!

>Could you provide the name of the volume that had the filesystem corruption
`data-stackstate-hbase-hdfs-dn-0`/`pvc-70fc2e9b-e75d-415c-b85f-3efe67439717`

> The YAML manifest of the deployment (we want to deploy the exact same setup in our lab)
This is the helm chart which has the relevant component - https://github.com/StackVista/helm-charts/tree/master/stable/hbase. The entire application exactly as the user deploys it may be a little difficult to provide, but I'll see what I can do. 

The storage for Longhorn is backed by a HP 3PAR SAN. The user said it was "All Flash". The user also mentioned that some sort of replication for the SAN is enabled which may result in increased disk latency, but didn't allude to it being a issue here.

**Comment by voarsh2** [comment] 2022-06-12 03:03
Probably an unhelpful comment but I have experienced some corrupted volumes recently, if I see it again I'll be sure to add information here as well.

**Comment by PhanLe1010** [comment] 2022-06-16 23:54
I am trying to reproduce the filesystem crash problem but have no luck so far. If you have a lab env that I can borrow, that would be great help @diamonwiggins @voarsh2 . More details about the steps I have tried https://github.com/longhorn/longhorn/issues/4000#issuecomment-1158289321

**Comment by wzrdtales** [comment] 2022-08-19 10:02
we also noticed longhorn is far from being something usable for production. Filesystem crashes are very well possible. Also issues like getting stuck in a read only volume for no reason.

The filesystem crashes are probably coming from a combination of issues:

1) The longhorn processes run on the same nodes with the same resources that run other processes. This is generally a bad idea and can lead to unwanted OOM kills.
2) For some reason when a node is being restarted longhorn very quickly decides to make a snapshot, which hopefully is not used for a sync process, since I can repeat it not often enough, snapshots are not a backup. They can be very likely in a corrupted state. 
3) Replacing an active replica (temporarily offline) too fast with a new one.


We had to decide to broadly drop longhorn and communicate a low level of reliability and to use it only with a very careful setup (i.e. splitting explicitly storage from load).

**Comment by voarsh2** [comment] 2022-08-19 11:39
Yep.
I've had countless headaches with Longhorn in my 4 month trial.
I've dumped it now for Ceph, zero problems, smooth sailing.

**Comment by PhanLe1010** [comment] 2022-09-29 21:50
We recently identified a bug in Longhorn that may corrupt the filesystem. More details are at https://github.com/longhorn/longhorn/issues/4354

@diamonwiggins @voarsh2 To verify, could you provide us the filesystem info of your problematic volumes if possible?
1. SSH into the node that has Longhorn volume currently attached to
2. If it is ext4, `tune2fs -l /dev/longhorn/<longhorn-volume-name>`
3. If it is xfs, `xfs_info /dev/longhorn/<longhorn-volume-name>`

**Comment by innobead** [comment] 2022-10-27 14:48
https://github.com/longhorn/longhorn/releases/tag/v1.3.2 has been introduced, so the related issues have been fixed. Closing first, but feel free to reopen if your case is different. 

ref: https://github.com/longhorn/longhorn/issues/4354 and https://github.com/longhorn/longhorn/issues/4594

**Closed by innobead** 2022-10-27 14:48 UTC
Labels: kind/bug, area/engine, priority/0, investigation-needed, area/stability, area/data-integrity
