### ISSUE TITLE
[BUG] Multiple backups created at the same time by a recurring backup job when backupstore is configured in google cloud bug

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1424] opened 2020-05-28 22:50 UTC
**Describe the bug**
Multiple backups created at the same time by a recurring backup job when backupstore is configured in google cloud bug

**To Reproduce**

- Backupstore - configured in google cloud
- Enable recurring backups for a volume, retention count=2, backups to be generated every 1 minute.
- Because of this [issue](https://github.com/longhorn/longhorn/issues/1404) - backups will not get deleted
- In about 20 -23 minutes, the recurring backup job generated about 52 backups. Multiple backups seen being generated at the same time.
- Even with the deletion of backups issue, this count seems off. 

**Expected behavior**
Multiple backups should not be generated at the same time

**Log**
[longhorn-support-bundle_3c7f1296-f91f-4192-86c5-cfaa89798880_2020-05-28T21-41-49Z.zip](https://github.com/longhorn/longhorn/files/4698648/longhorn-support-bundle_3c7f1296-f91f-4192-86c5-cfaa89798880_2020-05-28T21-41-49Z.zip)

**Environment:**
 - Longhorn version: master - 05/27/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: Linux 18.04

**Comment by yasker** [comment] 2020-06-02 21:33
The reason for this is the failure of backup deletion is counted as the whole recurring backup failure, so the recurring job will retry.

We should be count the backup deletion as best effort in the recurring job, and make it possible for the next recurring job to retry the deletion. 

The Google Cloud deletion failure should be addressed by #1404 soon.

**Comment by ttpcodes** [comment] 2020-06-05 17:22
## Pre-merged Checklist
* [X] Does the PR include the explanation for the fix or the feature?

* [X] Is the backend code merged?
The PR is at longhorn/longhorn-manager#599.

* [ ] Is the reproduce steps/test steps documented?

* [ ] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~

* [ ] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~

* [ ] ~~**if labeled: require/doc** Has the necessary document PR submitted or merged?~~

* [ ] ~~**If labeled: require/automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~

* [ ] ~~**if labeled: require/automation-engine** Has the engine integration test been merged?
The engine automation PR is at~~

* [ ] **if labeled: require/manual-test-plan** Has the manual test plan been documented?
The updated manual test plan is at

**Comment by ttpcodes** [comment] 2020-06-08 21:59
Since #1404 has been resolved, this issue can be reproduced by using the following Quay.io `Engine Images` that I've built:
- `quay.io/ttpcodes/longhorn-engine:no-cleanup` - `Snapshot` and `Backup` deletion are both set to return an error. If the `Snapshot` part of a `Backup` fails, that will error out first and `Backup` deletion will not be reached.
- `quay.io/ttpcodes/longhorn-engine:no-cleanup-backup` - Only `Backup` deletion is set to return an error. The `Snapshot` part of a `Backup` should succeed, and the `Backup` deletion will fail.

Follow these steps to reproduce this error:
1. Set up a `BackupStore` anywhere (since the cleanup fails at the `Engine` level, any `BackupStore` can be used.
2. Add both of the `Engine Images` above via the UI.

The next steps need to be repeated for each image (this is to test the code for `Snapshot` and `Backup` separately).
3. Create a `Volume` and run an `Engine Upgrade` to use one of the above images.
4. Attach the `Volume` and create a `Recurring Job` for testing. You can use a configuration that runs once every 3 minutes and only retains one `Backup`.
5. You should see multiple `Snapshots` or `Backups` get created per `Job` invocation. The logs for the `Pod` executing the `Job` should indicate that `Snapshot` or `Backup` deletion caused an error in the `Pod`.

With the fix, which has been merged, you should instead only see one `Snapshot` or `Backup` created per invocation. The logs for the `Pod` will say something similar to the following:
```
time="2020-06-08T20:05:10Z" level=warning msg="created snapshot successfully but errored on cleanup for test: error deleting snapshot 'c-c3athc-fd3adb1e': Failed to execute: /var/lib/longhorn/engine-binaries/quay.io-ttpcodes-longhorn-engine-no-cleanup/longhorn [--url 10.42.0.188:10000 snapshot rm c-c3athc-fd3adb1e], output , stderr, time=\"2020-06-08T20:05:10Z\" level=fatal msg=\"stubbed snapshot deletion for testing\"\n, error exit status 1"
```

The `Job` should nonetheless run successfully according to `Kubernetes`.

**Comment by khushboo-rancher** [comment] 2020-06-09 23:33
Verified on master - 06-09-2020

Verification - **Failed**

Steps:
1. Set up a Google cloud backup store.
2. Enable recurring backup with 1 min interval and retain count 2.
3. After sometime, Disabled the recurring backup.
4. Backup page shows 3 backups. It seems there is always one extra backup present than retain count.

**Comment by joshimoo** [comment] 2020-06-10 00:03
@khushboo-rancher did you verify that the extra backup is actually present on s3?
I remember you having some caching issues when testing #1404

**Comment by khushboo-rancher** [comment] 2020-06-10 00:08
It doesn't look like cache issue here, Even if I check backup page after 1 hour, there is one extra backup appearing. 
Attaching the logs
[longhorn-support-bundle_6d37239e-54b2-4db0-817a-b238375b6f18_2020-06-09T23-23-50Z.zip](https://github.com/longhorn/longhorn/files/4755463/longhorn-support-bundle_6d37239e-54b2-4db0-817a-b238375b6f18_2020-06-09T23-23-50Z.zip)

**Comment by ttpcodes** [comment] 2020-06-17 22:38
@khushboo-rancher When was the `Recurring Job` disabled? If the interval is set to one minute and the `Job` was up for three minutes, then it's expected that there will be three backups.

In the `Engine Images` that I created for testing, I intentionally stubbed out the `Snapshot` and `Backup` deletion methods such that they would fail and result in an error (similar to the behavior being witnessed in #1404). But while the `Backups`/`Snapshots` (what fails to be deleted is determined by whichever `Engine Image` you use) will not be deleted, you should see that, accounting for the non-deleted `Backups`/`Snapshots`, the `Job` does not run extra times and does not attempt to create extra `Backups`/`Snapshots` at the same time since the `Job` now is supposed to exit successfully.

I'll clarify the test steps in order to make note of this.

**Comment by khushboo-rancher** [comment] 2020-06-18 19:28
@ttpcodes I didn't understand why one extra backups are expected in backup store. 
Let me explain another scenario:
1. Enable recurring job for every 10 minutes with retain count 2.
2. It ran for 15 mins.
3. Disable the recurring job after 2 minutes of last backup completion.
4. Check the backup store, it has 3 backups.

In the above scenario when backups count has reached retain count, I would expect as soon as new backup gets created the oldest backup deletion should be triggered.

I disabled the recurring job after 2 min when the new backup creation was completed. The oldest backup should have deleted, the job was up for 2 mins after that.

I think there is a delay in deletion of backup because which this problem would arise if my recurring backup interval is less.

**Comment by khushboo-rancher** [comment] 2020-06-22 18:24
After discussion with @ttpcodes we found that we are seeing one extra backup after disabling the recurring job is because of #1471 
Added the scenario in #1471, this is good to close as reported problem is resolved now.

**Closed by khushboo-rancher** 2020-06-22 18:24 UTC
Labels: area/manager, bug, priority/1, reproduce/always, require/manual-test-plan
