### ISSUE TITLE
[BUG] longhorn-frontend can't be used with kubectl proxy

### ISSUE THREAD

**Issue by mgcrea** [longhorn/longhorn#1643] opened 2020-07-29 11:16 UTC
**Describe the bug**

When using `kubectl proxy` and trying to reach the `longhorn-frontend` service using the proxied url: http://localhost:8001/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:http/proxy/, the page does load but there is several asset loading errors and the longhorn frontend does not work.

Longhorn frontend should be able to handle not being exposed at the root (`/`) of the url.

Since using the proxy is the recommended way to access the kubernetes-dashboard, I think longhorn should support it as well (safer than an exposed basic-auth). 

**To Reproduce**

1. `kubectl proxy`
2. `open http://localhost:8001/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:http/proxy/`

**Expected behavior**

Working frontend UI

**Log**

> index.js:123 WebSocket connection to 'ws://localhost:8001/v1/ws/1s/settings' failed: Error during WebSocket handshake: Unexpected response code: 404

**Environment:**
 - Longhorn version: 1.0.1

**Comment by smallteeths** [comment] 2020-07-30 10:04
The kubectl proxy:
-client to proxy uses HTTP
-proxy to apiserver uses HTTPS

The reason I found the problem is that kubectl proxy uses http to proxy to apiserver. When apiserver requests longhorn frontend, because apiserver uses https, it will change the static resource address path of longhron frontend to https, which is caused static resource loading failure.The solution is to switch the path of static resources. @yasker 

Thank you very much for your issues, otherwise I will always ignore the path problem @mgcrea

**Comment by longlnk** [comment] 2020-08-03 10:01
I have the same problem
![image](https://user-images.githubusercontent.com/15074179/89171127-e61c6a80-d5aa-11ea-8ab1-888d1192dbb9.png)
Please help me.

**Comment by khushboo-rancher** [comment] 2020-08-04 00:23
Validated on ```longhorn-ui-5d4f878cdf``` 

Validation - **Passed**

The longhorn-frontend ```http://localhost:8001/api/v1/namespaces/longhorn-system/services/http:longhorn-frontend:http/proxy/``` is working fine with ```kubectl proxy```.

Verified longhorn-ui with rancher proxy and by creating ingress controller as well.

@longlnk How are you accessing the longhorn frontend, can you please share the steps? This issue talks about accessing longhorn ui locally with  ```kubectl proxy``` which is fixed now and will be available with release v1.1.0.

Closing this issue for now, @longlnk I can revalidate this based on your steps to reproduce this.

**Closed by khushboo-rancher** 2020-08-04 00:23 UTC
Labels: area/ui
