### ISSUE TITLE
[FEATURE] Longhorn SPDK Support

### ISSUE THREAD

**Issue by keithalucas** [longhorn/longhorn#3202] opened 2021-11-01 23:10 UTC
Using the information gained by the SPDK proofs of concept, begin working a version of the longhorn engine that uses SPDK.  This will work on a network on systems running the same customized SPDK software.

**Describe the items of the task (DoD, definition of done) you'd like.**
- [x] Create SPDK JSON RPC command to add a volume, with 0 or more replicas.  This will make the volume available over NVMEoF.
- [x] Create a SPDK JSON RPC command to create a replica.  This will make a new replica and make it available over NVMEoF.
- [ ] Create a SPDK JSON RPC command to add a replica to a volume.  This will rebuild the replica to ensure the replica is consistent with the other replicas in the volume.
- [x] Create a SPDK JSON RPC command to remove a replica from a volume.
- [ ] Remove a replica automatically by timeout.  The longhorn bdev will basically proxy reads and writes to NVMe bdevs. 
- [ ] Create a SPDK JSON-RPC command to retrieve the state of a longhorn volume.
- [ ] Create a SPDK JSON-RPC command to retrieve the state of each replica in a longhorn bdev.  This will include the IP address.

We can add commands and a gRPC interface to eventually integration with longhorn-manager.

**Comment by innobead** [comment] 2021-12-06 12:34
@keithalucas moving this to the `analysis` pipeline, and also please help frequently update the status in the thread. Thanks.

**Comment by keithalucas** [comment] 2022-01-19 00:59
I have the commands to create a replica and to create a volume from a list of replicas.  I'm working on implementing the consistent snapshot for adding new replica to an existing volume.

**Comment by liyimeng** [comment] 2022-01-22 15:24
Is it possible to borrow some implementation from mayastor to speed up the progress?

**Comment by keithalucas** [comment] 2022-02-10 15:45
> Is it possible to borrow some implementation from mayastor to speed up the progress?

mayastor uses a Rust binding for SPDK's C API.  Our intention is to use C for the SPDK support.  Conceptually they do similar things in Rust to what we're doing in C.

**Comment by keithalucas** [comment] 2022-03-25 17:12
I ran the kbench to compare a volume created with SPDK to a volume created with the existing longhorn engine, both with three replicas.  Using the default kbench settings, SPDK was this:

```=========================
FIO Benchmark Summary
For: longhorn-spdk-10g
CPU Idleness Profiling:
Size: 10g
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:         132,460 / 36,112
    Sequential:         127,961 / 70,484

Bandwidth in KiB/sec (Read/Write)
        Random:      1,163,133 / 351,267
    Sequential:      1,329,411 / 297,980


Latency in ns (Read/Write)
        Random:        197,335 / 155,719
    Sequential:        195,769 / 155,325
```

And the existing longhorn-engine was this:

```
=========================
FIO Benchmark Summary
For: longhorn-legacy-10g
CPU Idleness Profiling:
Size: 10g
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:          45,178 / 16,775
    Sequential:          65,422 / 29,360

Bandwidth in KiB/sec (Read/Write)
        Random:        816,055 / 326,926
    Sequential:      1,050,622 / 341,601


Latency in ns (Read/Write)
        Random:        328,214 / 316,525
    Sequential:        324,732 / 315,977
```

However, I reran the test with a size of 100g. 

SPDK:
```
=========================
FIO Benchmark Summary
For: longhorn-spdk
CPU Idleness Profiling: 
Size: 100g
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:         135,052 / 31,597
    Sequential:         124,419 / 70,430

Bandwidth in KiB/sec (Read/Write)
        Random:      1,133,688 / 370,263
    Sequential:      1,116,099 / 339,418
                                        

Latency in ns (Read/Write)
        Random:        197,643 / 154,698
    Sequential:        194,259 / 154,323
```

Longhorn-engine:
```=========================
FIO Benchmark Summary
For: longhorn-legacy
CPU Idleness Profiling: 
Size: 100g
Quick Mode: disabled
=========================
IOPS (Read/Write)
        Random:          54,756 / 11,468
    Sequential:          65,500 / 29,495

Bandwidth in KiB/sec (Read/Write)
        Random:      1,748,036 / 314,339
    Sequential:      1,762,729 / 339,428
                                        

Latency in ns (Read/Write)
        Random:        242,818 / 357,016
    Sequential:        320,200 / 317,861
```

The bandwidth results for longhorn-engine don't necessarily make since because they are more three times the bandwidth of the drive being used.  https://semiconductor.samsung.com/ssd/datacenter-ssd/pm883/mz7lh480hahq/   3*550 MB/S would be 1650 which is less that the random and sequential read.

If Linux's disk caching is causing this performance improve for the existing longhorn-engine, why doesn't it improve the SPDK version as well or as much?

**Comment by LarsBingBong** [comment] 2022-03-26 12:01
Very interesting and promising results Mr. @keithalucas - is it possible to try out this SPDK longhorn volume already? I'm very eager as I'm seeing some less than desired perf. results currently on Longhorn v1.2.4 - see > https://github.com/longhorn/longhorn/issues/3037

Thanks

**Comment by liyimeng** [comment] 2022-03-27 20:17
@keithalucas caching is done in kernel, spdk work in user space, could it be the cause?

**Comment by fzyzcjy** [comment] 2022-04-26 11:56
Hi, is there any updates?

**Comment by innobead** [comment] 2023-01-05 15:44
Closing, we will reorganize issues for SPDK.

**Closed by innobead** 2023-01-05 15:44 UTC
Labels: kind/enhancement, area/engine, highlight, priority/0, require/lep, area/spdk, experimental
