### ISSUE TITLE
[BUG] Longhorn Instance Manager Memory leak 

### ISSUE THREAD

**Issue by PhanLe1010** [longhorn/longhorn#6481] opened 2023-08-08 23:04 UTC
## Describe the bug (🐛 if you encounter this issue)

A bad backup target might cause memory leak inside Longhorn instance-manager pods

## To Reproduce

1. Create a volume `testvol1` of 20Gb. Attach the volume. Write some data.
1. Setup an nfs backup target that points to a non-exist directory. For example, `nfs://longhorn-test-nfs-svc.default:/opt/backupstore-nonexist`
1. Create snapshot name `snapshot-xyz`
1. Deploy about 100 backups of the same snapshot `snapshot-xyz`  like:
      ```
      apiVersion: longhorn.io/v1beta2
      kind: Backup
      metadata:
        labels:
          backup-volume: testvol1
        name: ''backup1"
        namespace: longhorn-system
      spec:
        labels:
          longhorn.io/volume-access-mode: rwo
        snapshotName: snapshot-xyz
      ```
      Technically, I think 1 backup should work too. Having 100 backups just to speed up the memory leak issue
1. Observer that Longhorn manager asks one of the replicas of the volume to retry the backup repeatedly. The backup retry failed repeatedly with the mount error `No such file or directory`:
      ```
      [instance-manager-87e672f2892911a9e3c1049af5825e55] time="2023-08-08T05:17:04Z" level=error msg="Failed to create delta block backup" destURL="nfs://longhorn-test-nfs-svc.default:/opt/backupstore1" error="cannot mount nfs longhorn-test-nfs-svc.default:/opt/backupstore1: vers=4.0: mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t nfs4 -o nfsvers=4.0,actimeo=1,soft,timeo=300,retry=2 longhorn-test-nfs-svc.default:/opt/backupstore1 /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore1\nOutput: mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore1 failed, reason given by server: No such file or directory\n: vers=4.1: mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t nfs4 -o nfsvers=4.1,actimeo=1,soft,timeo=300,retry=2 longhorn-test-nfs-svc.default:/opt/backupstore1 /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore1\nOutput: mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore1 failed, reason given by server: No such file or directory\n: vers=4.2: mount failed: exit status 32\nMounting command: mount\nMounting arguments: -t nfs4 -o nfsvers=4.2,actimeo=1,soft,timeo=300,retry=2 longhorn-test-nfs-svc.default:/opt/backupstore1 /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_default/opt/backupstore1\nOutput: mount.nfs4: mounting longhorn-test-nfs-svc.default:/opt/backupstore1 failed, reason given by server: No such file or directory\n: cannot mount using NFSv4" snapshot="&{6b91c5f3-74b1-4454-b001-a99b36669545 2023-08-08T05:17:03Z}" volume="&{testvol1 21474836480 map[VolumeRecurringJobInfo:{} longhorn.io/volume-access-mode:rwo] 2023-08-08T05:17:03Z   0   lz4 }"
      ```
1. Wait for a few hours. Observe that the memory usage of the instance-manager which prints out the above logs keep climbing up (in my test it is the `instance-manager-87e672f2892911a9e3c1049af5825e55`)
      ````
      # Initial
      instance-manager-63d5a33c5fe16bacb5a707c25a11c4d2   2m           44Mi            
      instance-manager-87e672f2892911a9e3c1049af5825e55   93m          61Mi            
      instance-manager-ca3fd80e3efef0746afbd5a56c4a43d1   32m          98Mi             
      longhorn-manager-mqhgg                              12m          112Mi           
      longhorn-manager-prjft                              8m           114Mi           
      longhorn-manager-x8x5k                              14m          119Mi  
      # After 5 hours
      instance-manager-63d5a33c5fe16bacb5a707c25a11c4d2   10m          88Mi            
      instance-manager-87e672f2892911a9e3c1049af5825e55   25m          246Mi      
      instance-manager-ca3fd80e3efef0746afbd5a56c4a43d1   51m          165Mi               
      longhorn-manager-mqhgg                              7m           128Mi           
      longhorn-manager-prjft                              15m          130Mi           
      longhorn-manager-x8x5k                              9m           137Mi  
      ````
1. Check the RSS of the processes inside the instance-manager `instance-manager-87e672f2892911a9e3c1049af5825e55`, we can see that the RSS of the sync agent service keep climbing up:
      ```
      # Before
      instance-manager-87e672f2892911a9e3c1049af5825e55:/ # ps aux
      USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
      root           1  0.0  0.0   2508   700 ?        Ss   Aug07   0:00 /tini -- instance-manager --debug daemon --listen 0.0.0.0:8500
      root          19  0.5  0.8 1903776 33548 ?       Sl   Aug07   1:00 /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.5.1/longhorn replica /host/var/lib/longhorn/replicas/t
      root          25  1.2  1.4 1389496 57796 ?       Sl   Aug07   2:03 /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.5.1/longhorn sync-agent --listen 0.0.0.0:10002 --repli
      # After
      instance-manager-87e672f2892911a9e3c1049af5825e55:/ # ps aux
      USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
      root           1  0.0  0.0   2508   700 ?        Ss   Aug07   0:01 /tini -- instance-manager --debug daemon --listen 0.0.0.0:8500
      root           8  0.7  0.6 1469444 27828 ?       Sl   Aug07   3:43 longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500
      root          19  0.5  0.8 1903776 34124 ?       Sl   Aug07   2:34 /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.5.1/longhorn replica /host/var/lib/longhorn/replicas/testvol1-c7901ccd --siz
      root          25  1.1  2.8 1390200 116224 ?      Sl   Aug07   5:10 /host/var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-v1.5.1/longhorn sync-agent --listen 0.0.0.0:10002 --replica 0.0.0.0:10000 --lis
      ```
1. The number of open fd, TCP connection, WebSockets are normal. So there is no issue here

## Code base analysis
1. From the above information,we can see that there is some leaking memory inside the `sync-agent` service when the backup creation is retried repeatedly.  
1. Tracing through the backup creation flow, I found one leak:
      1. When sync-agent receives a backupcreate call, it calls [BackupCreate()](https://github.com/longhorn/longhorn-engine/blob/4d54af9e4ccf6be07cb6825e4213e2a01dd0da73/pkg/sync/rpc/server.go#L683)
      1. This function call [s.BackupList.BackupAdd](https://github.com/longhorn/longhorn-engine/blob/4d54af9e4ccf6be07cb6825e4213e2a01dd0da73/pkg/sync/rpc/server.go#L717) which add a in-memory `BackupInfo` struct to the sync-agent server struct. 
      1. The problem here is the BackupInfo struct is never removed. We only remove the BackupInfo when the backup is completed [link](https://github.com/longhorn/longhorn-engine/blob/4d54af9e4ccf6be07cb6825e4213e2a01dd0da73/pkg/sync/rpc/list.go#L94)
      1. As a consequence the sync-agent server struct keeps getting bigger and bigger

## pprof analysis
@ejweber, @james-munson, and I performed a pprof analysis 
1. Adding pprof to the sync-agent and export the heap memory graph of the problematic sync-agent we have
    ![profile004](https://github.com/longhorn/longhorn/assets/22139961/b66df7d0-cf8e-4f89-9cd5-3a3157947849)
1. We can see that most of the heap space is allocated by the errors.(*withMessage).Error() function. It is this line of code [link](https://github.com/longhorn/longhorn-engine/blob/4d54af9e4ccf6be07cb6825e4213e2a01dd0da73/vendor/github.com/longhorn/backupstore/deltablock.go#L130-L131)
1. That line of code serialize the error and store it into the BackupStatus struct. This make the size of  BackupStatus becomes bigger
1. The BackupStatus struct previously appended into [s.BackupList](https://github.com/longhorn/longhorn-engine/blob/4d54af9e4ccf6be07cb6825e4213e2a01dd0da73/pkg/sync/rpc/server.go#L717-L718) of the sync-agent server struct
1. The final result is we are keep adding big BackupStatus struct to sync-agent server BackupList. This cause the memory leak

## What changes led to this problem:
1. From @derekbit: The NFS change from soft mode to hard mode. This makes it possible the sync-agent to retry backup when it failed to mount. In hard mode, sync-agent server is just stuck there forever.
1. From @ejweber: We serialize the error and store it into the BackupStatus struct now but we didn't do it before like 
[link](https://github.com/longhorn/longhorn-engine/pull/882/files#diff-47235adbea5004f5cf0f94f0f11ac45ecec7cfa95eb5140f50887ef4717fed1dR121-R126). This makes the BackStatus struct size bigger. Combine with the fact that the sync-agent server BackuoList is growing in the sync-agent server struct. This eats a lot of heap memory

## Proposing solution:
1. From @james-munson So the fix would not be to not add the info, but perhaps to check for whether it is new/different before doing so?
1. From me: Agree. We should NOT retain BackupStatus the s.BackupList forever or at least we should collapse the backupstatus with the same ID by using a map instead of using a slice [s.BackupList](https://github.com/longhorn/longhorn-engine/blob/4d54af9e4ccf6be07cb6825e4213e2a01dd0da73/pkg/sync/rpc/list.go#L16-L19) currently

## Environment

 - Longhorn version: v1.5.1
 
Additional context

This ticket was originally discussed at https://github.com/longhorn/longhorn/issues/6315

**Comment by WebberHuang1118** [comment] 2023-08-11 04:07
Harvester could reproduce the same situation by intentionally misconfiguring NFS server

**Environment:**
- Harvester v1.2.0
- Longhorn v1.4.3

**Reproduce Steps:**
1. Creating a VM with one volume 
2. Configure NFS server with valid exports (e.q. /home/data/valid)
3. Setting Harvester backup-target (Settings->backup-target)
4. Misconfigure NFS server with invalid exports (e.q. /home/data/invalid)
5. Creating 100 VM backups (Virtual Machines -> Take Backup)
6. `instance-manager-r-xxxx` pod's memory usage climbs from 144MB for 1400MB in 15 hours

**Some Source Code Observation:**
1. For a newly created backup, it goes through the process of [backup controller reconcile](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L369-L406) -> [checkMonitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L525-L555) -> [enableBackupMonitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L620-L640) -> [NewBackupMonitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/engineapi/backup_monitor.go#L78-L114) to start backup operation
2. If the backup failed [other than DeadlineExceeded](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/engineapi/backup_monitor.go#L93-L97), the error bubbles up to [enableBackupMonitor without setting the monitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L634-L637) (since it's null).
3. And backup error bubbles up all the way to [backup controller reconcile without status update](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L341-L360)
4. For the next backup controller reconcile, it will treat the backup as newly created. Since [LastSyncedAt is null](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L369) and the backup [has no matched monitor](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L531-L533).  The above steps repeat over again and again.
5. This leads the `BackupInfo` structure keeps allocated in `instance-manager-r-xxxx` pods, as described [here](https://github.com/longhorn/longhorn/issues/6481#issue-1842216484).

**Comment by ejweber** [comment] 2023-08-11 13:22
> And backup error bubbles up all the way to [backup controller reconcile without status update](https://github.com/longhorn/longhorn-manager/blob/432b6d40f02a6fdffd8389df9d779016775f1d3a/controller/backup_controller.go#L341-L360)

This behavior was fixed by https://github.com/longhorn/longhorn-manager/pull/2086. I think this should make the leak @WebberHuang1118  is describing much slower on master (and eventually in v1.4.4). However, we will still leak memory with each legitimately new backup, so a fix is still needed.

**Comment by james-munson** [comment] 2023-08-17 20:25
With the fix, leaving 91 failing backups running overnight, the top pods look like:
```
$ kl top pod
NAME                                                CPU(cores)   MEMORY(bytes)   
instance-manager-524d96f7e531a3cf659b52ba31e6cfa4   225m         295Mi           
instance-manager-7694d1d58572b971e5b0176cc5855c17   111m         57Mi            
instance-manager-a81265cabd52ad39fb2c212b1611c313   177m         67Mi            
```
That's troubling.  The process list inside that pod is
```
# ps aux
USER         PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root           1  0.0  0.0   2516   716 ?        Ss   Aug15   0:07 /tini -- instance-manager --debug daemon --listen 0.0.0.0:8500
root           8  2.0  0.8 1543184 33212 ?       Sl   Aug15  53:40 longhorn-instance-manager --debug daemon --listen 0.0.0.0:8500
root          10  0.0  0.0   3008   872 ?        S    Aug15   0:17 tgtd -f
root          11  0.0  0.0   2532   712 ?        S    Aug15   0:00 tee /var/log/tgtd.log
root      102321  0.0  0.1   8984  4216 pts/0    Ss+  Aug16   0:00 bash
root      394458  1.2  0.6 1544964 25992 ?       Sl   03:29  10:11 /host/var/lib/longhorn/engine-binaries/jmunson4suse-longhorn-engine-6481-pprof/longhorn replica /host/var/lib/longhorn/replicas/testvol1
root      394464  5.5  1.1 2520672 **45764** ?       Sl   03:29  45:48 /host/var/lib/longhorn/engine-binaries/jmunson4suse-longhorn-engine-6481-pprof/longhorn sync-agent --listen 0.0.0.0:10002 --replica 0.0.

root     1107132  0.0  0.0   8104  1176 ?        S    12:31   0:00 mount -t nfs4 -o nfsvers=4.2,actimeo=1,soft,timeo=300,retry=2 longhorn-test-nfs-svc.default:/opt/backupstore-nonexist /var/lib/longhorn-
root     1107133  0.0  0.1  29956  5088 ?        D    12:31   0:00 /sbin/mount.nfs4 longhorn-test-nfs-svc.default:/opt/backupstore-nonexist /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_defa
root     1107134  0.0  0.0   8104  1260 ?        S    12:31   0:00 mount -t nfs4 -o nfsvers=4.1,actimeo=1,soft,timeo=300,retry=2 longhorn-test-nfs-svc.default:/opt/backupstore-nonexist /var/lib/longhorn-
root     1107136  0.0  0.1  29956  5088 ?        D    12:31   0:00 /sbin/mount.nfs4 longhorn-test-nfs-svc.default:/opt/backupstore-nonexist /var/lib/longhorn-backupstore-mounts/longhorn-test-nfs-svc_defa
... (89 more instances of mount ...)
```
That is, the RSS size of the sync-agent process is reasonable, although the VSZ is large.  That's because there are 91 goroutines hanging around waiting for the NFS mounts to be successful, in a blocking syscall.  Apparently each backup is attempting to mount the bogus NFS path, and is hung.

Thanks to @ejweber, this ps output shows
```
instance-manager-524d96f7e531a3cf659b52ba31e6cfa4:/ # ps -eo ppid,pid,user,stat,pcpu,comm,wchan:32
   PPID     PID USER     STAT %CPU COMMAND         WCHAN
      0       1 root     Ss    0.0 tini            do_sigtimedwait
      1       8 root     Sl    2.3 longhorn-instan ep_poll
      8      10 root     S     0.0 tgtd            ep_poll
      8      11 root     S     0.0 tee             pipe_read
      0  102321 root     Ss+   0.0 bash            do_select
      8  394458 root     Sl    1.1 longhorn        futex_wait_queue_me
 394458  394464 root     Sl    6.3 longhorn        do_wait
 394464 1107132 root     S     0.0 mount           do_wait
1107132 1107133 root     D     0.0 mount.nfs4      nfs_wait_client_init_complete
...

**Comment by james-munson** [comment] 2023-08-17 21:01
I regard this as showing the leak problem is fixed, but there are more issues behind it when attempting to use an invalid target.
This testing was done against release 1.5.1 code, so it would not have the fix for https://github.com/longhorn/longhorn/issues/1249, which will be in 1.5.2.

**Comment by chriscchien** [comment] 2023-09-05 07:59
Verified **pass** on longhorn master(longhorn-manager `421da0`) with test [steps](https://github.com/longhorn/longhorn/issues/6481#issue-1842216484)

Setup a nfs backup target points to a non-exist directory, create 101 backups and wait for 5 hours, did not encounter instance manager leak issue

backup-target
```
root@ip-172-31-39-247:/home/ubuntu#  k get backuptarget -A
NAMESPACE         NAME      URL                                                             CREDENTIAL   LASTBACKUPAT   AVAILABLE   LASTSYNCEDAT
longhorn-system   default   nfs://longhorn-test-nfs-svc.default:/opt/backupstore-nonexist                5m0s           false       2023-09-05T07:52:41Z
```

backup number
```
root@ip-172-31-39-247:/home/ubuntu# k get backup -n longhorn-system | wc -l
101
```

instance manager resource usage between 5 hours
```
root@ip-172-31-39-247:/home/ubuntu# date
Tue Sep  5 02:58:41 UTC 2023
root@ip-172-31-39-247:/home/ubuntu# k top pod -n longhorn-system | grep manager
instance-manager-130000bcff14db1d979608689971bb35   2m           36Mi            
instance-manager-46c62644a08222f713b8a53765a8fb9a   2m           32Mi            
instance-manager-b4dd06b937e48ec75376bfabf2f03a3b   9m           50Mi            
longhorn-manager-bdsjx                              5m           75Mi            
longhorn-manager-r88n2                              7m           69Mi            
longhorn-manager-t5p8t                              3m           72Mi            
root@ip-172-31-39-247:/home/ubuntu# date
Tue Sep  5 07:48:12 UTC 2023
root@ip-172-31-39-247:/home/ubuntu# k top pod -n longhorn-system | grep manager
instance-manager-130000bcff14db1d979608689971bb35   6m           37Mi            
instance-manager-46c62644a08222f713b8a53765a8fb9a   2m           32Mi            
instance-manager-b4dd06b937e48ec75376bfabf2f03a3b   10m          50Mi            
longhorn-manager-bdsjx                              7m           76Mi            
longhorn-manager-r88n2                              6m           71Mi            
longhorn-manager-t5p8t                              4m           72Mi            
```

**Closed by chriscchien** 2023-09-05 07:59 UTC
Labels: kind/bug, priority/0, require/qa-review-coverage, backport/1.4.4, backport/1.5.2
