### ISSUE TITLE
[BUG] Fix misleading error messages when creating a mount point for a backup store

### ISSUE THREAD

**Issue by derekbit** [longhorn/longhorn#5630] opened 2023-03-22 06:36 UTC
## Describe the bug (🐛 if you encounter this issue)

If the mount point doesn't exist, the check for syscall.ENOENT.Error() ([code](https://github.com/longhorn/backupstore/blob/master/util/util.go#L293)) will fail because the error message returned by mount.IsNotMountPoint is different. Although this won't introduce bugs and the mount point can be created in the end,
the error message might be misleading for users.

## To Reproduce

1. Create a Longhorn cluster using master branch
2. Set NFS backup store
3. Create a volume
4. Execute backup. If the mount point is not existing inside the longhorn-manager-r pod, the error will show "...was identified as corrupted by ReadDir...". The backup should succeed.

## Log or Support bundle

If applicable, add the Longhorn managers' log or support bundle when the issue happens. 
You can generate a Support Bundle using the link at the footer of the Longhorn UI.

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl):
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version:
   - Number of management node in the cluster:
   - Number of worker node in the cluster:
 - Node config
   - OS type and version:
   - CPU per node:
   - Memory per node:
   - Disk type(e.g. SSD/NVMe):
   - Network bandwidth between the nodes:
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal):
 - Number of Longhorn volumes in the cluster:

**Comment by derekbit** [comment] 2023-03-22 06:41
@innobead 
No need to backport to v1.3.3 and v1.4.2. This is caused by my refactoring.

**Comment by innobead** [comment] 2023-04-13 13:48
Closing w/o QA testing, since longhorn-manager, instance-manager, and engine are all updated and this is about log update. Let's follow up with the daily regression. 

cc @longhorn/qa

**Closed by innobead** 2023-04-13 13:48 UTC
Labels: kind/bug, area/manager, area/backup-store
