### ISSUE TITLE
[BUG] longhorn-driver-deployer fails to delete longhorn-csi-plugin DaemonSet due to Pods stuck in Terminating state on down nodes

### ISSUE THREAD

**Issue by ikaruswill** [longhorn/longhorn#2171] opened 2021-01-11 18:24 UTC
**Describe the bug**
I had nodes that are permanently down (Powered off but not deleted) in my k8s cluster, with `longhorn-csi-plugin` DaemonSet pods in `Running`' state. Let's call this set of nodes as `permanently offline but not deleted`. Other than those nodes, there are another set of nodes that are actively running workloads and among them are the longhorn storage nodes, let's call these nodes as the `active nodes`

When the `active nodes` are power-cycled one-by-one for hardware upgrade, volumes will be shown as `Healthy` in the UI but fail to 'detach' from nodes. All pods depending on such volumes will attempt to restart as the power-cycled `active nodes` slowly come back online, but will be stuck in `Pending` with an error of `timed out waiting for volumes to detach`. 

`longhorn-driver-deployer` Pod will fail showing `timed out waiting for DaemonSet deletion` as the csi-plugin pods on the `permanently offline but not deleted` nodes are stuck `Terminating` and the DaemonSet never successfully deletes. 

Disclaimer: Apologies my log message quotes may not be the exact wording as I was in a hurry to get the cluster services back online. I'm only typing this from my memory of the observed events and log messages.

**To Reproduce**
1. Power down some nodes in your cluster, do not delete them.
2. Introduce a cluster outage, power down all storage nodes either one-by-one or altogether
3. Wait for the cluster to recover and reschedule pods
4. Pods are stuck `Pending` and `longhorn-driver-deployer` fails on attempting to delete `longhorn-csi-plugin` DaemonSet

**Expected behavior**
Pods reschedule successfully and volumes reattach uneventfully

**Log**
Manager just shows a bunch of generic errors of not being able to retrieve logs, I'd say they are irrelevant.
Unfortunately, I've lost the logs for `longhorn-driver-deployer` when I deleted it in a hasty attempt to restart it ASAP.

**Environment:**
 - Longhorn version: 1.10.0
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: v1.19.5+k3s2
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 2
 - Node config
   - OS type and version: Armbian 20.11.1 Buster with Linux 5.9.11-rockchip64
   - CPU per node: 6
   - Memory per node: 4GB
   - Disk type(e.g. SSD/NVMe): NVMe
   - Network bandwidth between the nodes: 1Gbps
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): Baremetal

**Additional context**
Suggest force deleting the `longhorn-csi-plugin` DaemonSet for downed nodes to prioritize restoration of storage service in cluster in event of outage.

**Comment by PhanLe1010** [comment] 2021-01-13 05:22
@ikaruswill 

There are 2 problems you mentioned in this issue.
> When the active nodes are power-cycled one-by-one for hardware upgrade, volumes will be shown as Healthy in the UI but fail to 'detach' from nodes. All pods depending on such volumes will attempt to restart as the power-cycled active nodes slowly come back online, but will be stuck in Pending with an error of timed out waiting for volumes to detach.

There is current a [bug](https://github.com/longhorn/longhorn/issues/2062) in Kubernetes v1.19+ versions that breaks Longhorn's `Pod Deletion Policy When Node is Down` feature. We are hoping K8s team to fix it soon. Btw, did you deploy workload using a deployment or statefulset? Did you turn on the feature `Pod Deletion Policy When Node is Down` in Longhorn UI? 

> longhorn-driver-deployer fails on attempting to delete longhorn-csi-plugin DaemonSet

Longhorn shouldn't delete `longhorn-csi-plugin` DaemonSet unless you are upgrading Longhorn to a new version or using newer images. Is it the case?

**Comment by ikaruswill** [comment] 2021-01-13 09:52
Weird. I wasn't upgrading the cluster. There was just merely some downtime on storage nodes, not all at once but consecutively with a few minutes in between storage node outages. Would reapplying the longhorn yamls cause this? As the cluster is running fluxcd/flux which applies all manifests every few minutes. It has worked uneventfully for nearly a month so I doubt that's the cause. 

About the former. I have it set at `delete-both-statefulset-and-deployment-pod`. My workloads are majority deployments (20+) and 2 statefulsets. Seems like you're right in that there's an issue there. But the issue I face seems to be that even if I manually delete the Deployments the volumes do not detach, and stay on the original node.

**Comment by PhanLe1010** [comment] 2021-01-15 01:00
@ikaruswill 

I have followed the steps you mentioned:
> 1. Power down some nodes in your cluster, do not delete them.
> 1. Introduce a cluster outage, power down all storage nodes either one-by-one or altogether
> 1. Wait for the cluster to recover and reschedule pods
> 1. Pods are stuck Pending and longhorn-driver-deployer fails on attempting to delete longhorn-csi-plugin DaemonSet

With a similar setup Longhorn 1.1.0 and Kubernetes v1.19.4

I couldn't reproduce the same problem you encountered. I observered:
1. `longhorn-csi-plugin` DaemonSet is not deleted by `longhorn-driver-deployer`
2. Before of the bug in K8s, K8s doesn't set deletion timestamp on workload pods so Longhorn doesn't delete workload pod even when `delete-both-statefulset-and-deployment-pod` setting  is set. However, when I manually delete the workload pod, K8s set deletion timestamp on workload pods and after a `graceperiodseconds` 30s, Longhorn delete the workload pod, detach the volume, K8s spined up replacement pod and Longhorn attach the volume.

Go back to the problem you hit. It might be that the `longhorn-csi-plugin` DaemonSet was deleted so Longhorn cannot detach/attach at the time. Now, we need to find out why the  `longhorn-csi-plugin` DaemonSet was deleted while it is not supposed to be. I am not familiar with ` fluxed/flux` but constantly reapplying yaml might have some issue with current Longhorn v1.1.0. Can you provide us the support bundle to `longhorn-support-bundle@rancher.com`?

**Comment by ikaruswill** [comment] 2021-01-20 07:52
Thanks for trying to reproduce the issue @PhanLe1010 perhaps constantly reapplying the yaml is not ideal. I'll exclude longhorn manifests from `fluxcd` in hopes that it'll mitigate future issues like this. I'll send the support bundle over.

**Comment by joshimoo** [comment] 2021-01-27 18:57
Similar to the terraform issue, linking for reference: https://github.com/longhorn/longhorn/issues/2120

**Comment by PhanLe1010** [comment] 2021-01-28 09:18
@ikaruswill 
I read the support bundle but have't found anything abnormal yet.

One question, when you say `the active nodes are power-cycled one-by-one for hardware upgrade`, did you upgrade Kubernetes version?

**Comment by ikaruswill** [comment] 2021-01-28 11:10
Hmm I did not upgrade kubernetes version. I only upgraded the power supplies, which should be inconsequential to the cluster. Weird.

**Comment by yasker** [comment] 2021-01-29 01:55
We will try to reproduce the issue with fluxcd first.

**Comment by ikaruswill** [comment] 2021-01-29 03:18
@yasker @PhanLe1010 Thanks for the attention on this issue so far. 

Since fluxcd is now moving to fluxv2, this issue might not be relevant in the near future. 

I'm thinking if we're not able to reproduce this on your side, we can close this issue and reopen if this happens again on either fluxv2, or in a future power outage on my cluster.

**Comment by silhouette** [comment] 2021-03-26 15:08
I'm experiencing a similar issue. I have several volumes stuck in "Deleting" or "Attaching" status and no option to finish the process. Support-Bundle is attached. We had a power outage recently, too, but I'm not sure if it really caused this problem.

[longhorn-support-bundle_3cfdb494-dce5-451c-aa66-83cc180506c8_2021-03-26T15-03-56Z.zip](https://github.com/longhorn/longhorn/files/6212660/longhorn-support-bundle_3cfdb494-dce5-451c-aa66-83cc180506c8_2021-03-26T15-03-56Z.zip)

**Comment by innobead** [comment] 2021-04-29 18:23
> @yasker @PhanLe1010 Thanks for the attention on this issue so far.
> 
> Since fluxcd is now moving to fluxv2, this issue might not be relevant in the near future.
> 
> I'm thinking if we're not able to reproduce this on your side, we can close this issue and reopen if this happens again on either fluxv2, or in a future power outage on my cluster. What do you think?

@ikaruswill could you try the latest release v1.1.1 including the fix https://github.com/longhorn/longhorn/issues/2120? I think the issue is probably relevant like @joshimoo mentioned.

**Comment by innobead** [comment] 2021-04-29 18:25
> I'm experiencing a similar issue. I have several volumes stuck in "Deleting" or "Attaching" status and no option to finish the process. Support-Bundle is attached. We had a power outage recently, too, but I'm not sure if it really caused this problem.
> 
> [longhorn-support-bundle_3cfdb494-dce5-451c-aa66-83cc180506c8_2021-03-26T15-03-56Z.zip](https://github.com/longhorn/longhorn/files/6212660/longhorn-support-bundle_3cfdb494-dce5-451c-aa66-83cc180506c8_2021-03-26T15-03-56Z.zip)

@silhouette I would suggest creating another issue to describe your case w/ reproduce steps and info provided. That will be easy to identify your case. Thanks.

**Comment by ikaruswill** [comment] 2021-04-29 19:16
Yep. I upgraded on the day v1.1.1 released. So far I haven't had issues. 

But then again to be honest I'm not too keen on trying to reproduce it as in the worst case it results in the loss of all volumes, requiring a restore. 

My cluster topology has since evolved quite a bit as well so I'm afraid I am also unable to revert exactly to the circumstances that produced this issue.

Let's perhaps close this issue for the time being, and reopen should there be further observations, shall we?

**Comment by jenting** [comment] 2021-05-04 03:18
I'd prefer to close it now, feel free to reopen it once the issue is able to reproduce.

**Closed by jenting** 2021-05-04 03:18 UTC
Labels: area/deployment
