### ISSUE TITLE
[BUG] State transitions for a failure in backup restore

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1260] opened 2020-04-27 21:54 UTC
**Describe the bug**
State transitions for a failure in backup restore can be made better

**To Reproduce**

- Create a volume and a backup
- Invalidate the target URL in Settings page.
- Restore from backup into a volume - v1
- The volume v1 is seen. in Healthy. state
- The. replicas are seen in "Running" state

**Expected behavior**
If a backup restore fails, it should be seen. on the volume. The volume should NOT be in "Healthy" state and the replicas should not be in "Running" state.

**Environment:**
 - Longhorn version: master - 04/27/2020
 - Kubernetes version: 1.17.5
 - Node OS type and version: DO RKE cluster Linux

**Comment by yasker** [comment] 2020-05-04 01:57
We need a state or something to indicate that the volume is in the restoring process and cannot be used immediately. DR will need a similar state too.

**Comment by shuo-wu** [comment] 2020-05-05 09:22
And we need integration tests for the restoration failure cases, including incremental restoration failure.

**Comment by shuo-wu** [comment] 2020-05-05 11:17
I just double-checked the reproducing step and I found that was weird... 

@sowmyav27 Can you provide more detailed info/instruction for these 2 steps:
```
Invalidate the target URL in Settings page.
Restore from backup into a volume - v1
```
If the target URL is invalid, there shouldn't be backup volume in the UI page. Then how can you restore a volume?

**Comment by yasker** [comment] 2020-05-06 01:28
@shuo-wu I think @sowmyav27 has another tab open for the backup list page while modifying the setting page.

**Comment by shuo-wu** [comment] 2020-05-06 01:41
> @shuo-wu I think @sowmyav27 has another tab open for the backup list page while modifying the setting page.

Can you provide the URL? There are lots of issues related to the backup. I can't find the tab you mentioned.

**Comment by yasker** [comment] 2020-05-06 01:54
I meant, a browser tab pointed to the backup page.

**Comment by shuo-wu** [comment] 2020-05-06 02:06
Oh, OK...

**Comment by shuo-wu** [comment] 2020-05-06 11:51
More details about reproducing step2 and step3:
- Pick up a backup volume then click `Restore Latest Backup`. There should be a pop-up that allows users to config the restore volume.
- Invalidate the backup target URL. e.g., Add some extra characters
- Create the restore volume via the pop-up.

The error logs:
```
[longhorn-manager-wj8r6] E0506 11:19:31.571704       1 engine_controller.go:664] fail to update status for engine v1-e-57994569: error getting backup volume: Failed to execute: /var/lib/longhorn/engine-binaries/longhornio-longhorn-engine-master/longhorn [backup ls --volume pvc-28e6518e-fc16-4ed6-ba03-a8ae165ee6b2 --volume-only s3://backupbucket111@us-east-1/backupstore111], output failed to list objects with param: {
[longhorn-manager-wj8r6]   Bucket: "backupbucket111",
[longhorn-manager-wj8r6]   Delimiter: "/",
[longhorn-manager-wj8r6]   Prefix: "backupstore111/"
[longhorn-manager-wj8r6] } response: {
[longhorn-manager-wj8r6]
[longhorn-manager-wj8r6] } error: AWS Error:  NoSuchBucket The specified bucket does not exist <nil>
[longhorn-manager-wj8r6] 404 160C6C6A1D39746D
[longhorn-manager-wj8r6]
[longhorn-manager-wj8r6] , stderr, time="2020-05-06T11:19:31Z" level=error msg="Fail to list s3: failed to list objects with param: {\n  Bucket: \"backupbucket111\",\n  Delimiter: \"/\",\n  Prefix: \"backupstore111/\"\n} response: {\n\n} error: AWS Error:  NoSuchBucket The specified bucket does not exist <nil>\n404 160C6C6A1D39746D\n" pkg=s3
[longhorn-manager-wj8r6] time="2020-05-06T11:19:31Z" level=error msg="failed to list objects with param: {\n  Bucket: \"backupbucket111\",\n  Delimiter: \"/\",\n  Prefix: \"backupstore111/\"\n} response: {\n\n} error: AWS Error:  NoSuchBucket The specified bucket does not exist <nil>\n404 160C6C6A1D39746D\n"
[longhorn-manager-wj8r6] , error exit status 1
```
The error is returned [here](https://github.com/longhorn/longhorn-manager/blob/master/controller/engine_controller.go#L897).

This issue is a corner case of the restore failure: the restore fails in the beginning and there is no restore status info/error.

**Comment by shuo-wu** [comment] 2020-05-08 10:33
Test plan/skeleton 1:
Test if the invalid backup target will lead to the restore volume becoming Faulted, and if the auto salvage feature is disabled for the faulted restore volume.
1. Enable auto-salvage.
2. Set the backupstore. (No not use NFS server for this case before fixing #1295)
3. Create a volume and a backup.
4. Invalidate the target URL. (e.g., `s3://backupbucket-invalid@us-east-1/backupstore-invalid`)
5. Restore a volume from the backup. (The `fromBackup` fields of the volume create API should consist of the invalid target URL and the valid backup volume info)
6. Wait for the restore volume `Faulted`. 
    --> Check if `volume.conditions[restore].status == False && volume.conditions[restore].reason == "RestoreFailure"`.
    --> Check if the auto-salvage is disabled even if the setting is enabled.

Test plan/skeleton 1:
Test if all replica restore failure will lead to the restore volume becoming Faulted, and if the auto salvage feature is disabled for the faulted restore volume.
1. Enable auto-salvage.
2. Set the backupstore. (No not use NFS server for this case before fixing #1295)
3. Create a volume and a backup (with some data).
4. Delete some data blocks of the backup, which will lead to all replica restore failures later. (It's better to clean up the backups in the backupstore before this step. Then you can delete a random block and trigger the restore failure)
5. Restore a volume from the backup.
6. Wait for the restore volume `Faulted`. 
    --> Check if `volume.conditions[restore].status == False && volume.conditions[restore].reason == "RestoreFailure"`.
    --> Check if the auto-salvage is disabled even if the setting is enabled.

Notice that the field `volume.controllers[0].restoreStatus` will be cleaned up when the volume becomes Faulted. It's better not to check/wait for the error in the restore status.

**Comment by shuo-wu** [comment] 2020-05-08 10:58
This [PR](https://github.com/longhorn/longhorn-manager/pull/558) is not enough for issue #1188 since some incremental restore errors may not be recorded in the sync agent server restore status, then longhorn manager can't catch the errors and handle the failure.

**Comment by yasker** [comment] 2020-05-08 22:35
PR is mostly good. Need to finish the following items before merge:

- [ ] Communicate API change and the expected behavior to UI @smallteeths 
- [ ] Make a PR to the `longhorn/longhorn-test` about the above test cases. Make sure to include @sowmyav27 and @meldafrawi in the PR review.

**Comment by shuo-wu** [comment] 2020-05-11 11:36
UI part:
1. Add a new field `Available for workloads usage` in the volume detail page. The responding backend field is `v.ready`.
2. Add a hover if it's not ready: "The volume may be under maintenance."

@yasker Do we need to add something in the volume list page if a volume is not ready. 

Manually tests when the UI part is done:
Test 1: Create a DR volume and see if the volume is already not ready as long as it is not activated.
Test 2: Create a regular restore volume and see if the volume keeps not-ready before the restore complete.
Test 3: Expand a volume and see if the volume is not ready during the expansion.

**Comment by yasker** [comment] 2020-05-11 23:03
@shuo-wu I think we can just add `Ready for workload` in the volume detail page. `Yes` as green, `No` as red. Reason can be `The volume may be under maintenance or in the restore process`.

If the volume is not ready, we want to show it in the volume list as well. How about if the volume is not ready, we show a green icon next to the volume state to indicate that? Hover it will say `Not ready for workload`.

**Comment by shuo-wu** [comment] 2020-05-12 03:14
In general, it sounds good. I think a yellow icon for the volume is better if it's not ready.

**Comment by yasker** [comment] 2020-05-13 01:27
Pre-merged Checklist
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?

**Comment by sowmyav27** [comment] 2020-05-15 22:46
**Verified on master - 05/15/2020**

Validation: **`PASSED`**

- Create a volume and a backup
- Invalidate the target URL in Settings page.
- Restore from backup into a volume - v1
- The volume v1 is seen. in Healthy. state for a second ( approx)
- The volume is then in "Faulted" state in Volume detail page.
- Backup restore - fails in this case - which is expected

**Comment by meldafrawi** [comment] 2020-05-28 22:30
test_single_replica_restore_failure failed at **longhorn-upgrade-tests/114**

**Comment by meldafrawi** [comment] 2020-05-29 22:04
test_single_replica_restore_failure passed

**Comment by meldafrawi** [comment] 2020-05-29 22:29
Opened separate issue #1432 to track integration test failure

**Closed** 2020-07-09 16:33 UTC
Labels: area/manager, area/ui, bug, enhancement, priority/1, require/automation-e2e
