### ISSUE TITLE
Replicas are on the same node

### ISSUE THREAD

**Issue by vistalba** [longhorn/longhorn#570] opened 2019-05-20 17:16 UTC
Longhorn version: 0.5.0

I run a 3 node longhorn cluster. Replica Count is 3.
Tonight one node failed and longhorn rebuild the 3. replica on one of the two remaining nodes.

After the 3 node was back online, longhorn doensn't redistribute the replica. It stays in the state whith two replicas on the same node.

Is there a solution for this so that longhorn does automaticly redistribute one of the both replicas on the same node?

**Comment by yasker** [comment] 2019-05-23 08:04
For now you can follow the steps below to redistribute:
1. Increase the volume replicas by 1. The new replica should be rebuilt on the new node.
2. Decrease the volume replicas to original (3).
3. Remove one of the replicas on the existing node.

We can have something like that automatically. Though we need to think more about it since it also related to how can we minimalize the data transferred through the network.

**Comment by vistalba** [comment] 2019-05-23 08:59
Yes, I know how to solve this manually. 

But there is no alert/notification about this. I can just see this in the WebGUI.
I think this is a must that it can do this automaticly. (or that I can check it in the settings if I wish to do this automaticly).

Maybe there should be a limit how much volumes on the same time. A limit how oft a rebuild will be started in a timeperiod? How to send a notification about such stuff to someone?

**Comment by tidalf** [comment] 2019-05-23 19:11
I think I'd like two (and not more) on the same host only if one host is available (otherwise never)

**Comment by yasker** [comment] 2019-05-25 10:53
Seems there are many issues we want to discuss here. Let me try to list them down:
1. More than expected replicas are scheduled to the same node when there are no other nodes available. Two replicas on the same node sound OK, but no for three or more. Is that universal? I don't think so. We at least need an option for this.
2. The implication of 1 is if the volume has a number of replicas scheduled successful (e.g. 2), do we allow the volume to be attached even not all of the replicas of volume has been schedulable? Or is item 1 only applies to the rebuilding process?
3. Replicas scheduled on the same node are not automatically redistributed to another node if any other node is suitable for redistribution. We can call it `auto-balancing`. This can trigger far more traffic in the network currently, so it's better to wait for item 5, 6 and 7 to be implemented first.
4. No notification for the event that sysadmin should pay attention to ( #542 asked for notification as well). No doubt we need a new feature `notification` here.
5. Potentially, to minimize the data transfer, we may validate and use the existing replica for the rebuilding process. The reason we haven't done this is it complicates the logic. But we will need to do this eventually.
6. Minimize the data transfer during the rebuild, or even pause the rebuild if it's only a temporary shutdown of the node. Sounds like we need to think a bit more. We can have a limitation that how many replicas can be rebuilt in a delayed fashion (with specified interval), how many we have to rebuild immediately (e.g. if only 2 replicas and we lost one, we definitely want to start to rebuild immediately). If we support delayed rebuilding, we need to implement the item 5 first.
7. A limitation on how many volumes should be in rebuilding state at the same time, across the cluster. Or a limitation on what's the maximum bandwidth rebuilding should take.

Let me know if I missed something.

Btw, none of those features are trivial, it's likely to take quite some time for us to get all those done. But I want to start the discussion as early as possible, especially we're having a re-architect coming in v0.6.0. I want to at least make sure we've considered how to accommodate all the important features when we working on the v0.6.0.

**Comment by vistalba** [comment] 2019-05-25 11:35
> 1. More than expected replicas are scheduled to the same node when there are no other nodes available. Two replicas on the same node sound OK, but no for three or more. Is that universal? I don't think so. We at least need an option for this.

I don't think so too. What is the benefit, if two of three replica are on the same node?

> 2. The implication of 1 is if the volume has a number of replicas scheduled successful (e.g. 2), do we allow the volume to be attached even not all of the replicas of volume has been schedulable? Or is item 1 only applies to the rebuilding process?

From my point of view it should be possible. 
For Example:
If I have 3 replicas and one node goes offline. Two replicas are still running so the volume is "degarded". In this case it doesn't make sense to rebuild the 3 replica on one of the two remaining nodes... but why you should prevent the usage of the volume?

> 3. Replicas scheduled on the same node are not automatically redistributed to another node if any other node is suitable for redistribution. We can call it auto-balancing. This can trigger far more traffic in the network currently, so it's better to wait for item 5, 6 and 7 to be implemented first.

This is the main future I like to get. "Self-healing"/auto-balancing or whatever. I think it is more relevant than 1 and 2.
Why? 4. isn't in place. So as admin I don't know if something goes wrong. I've to check it manually and take some actions if I discover a degraded voulme (or helathy but with replicas on same node).
If this feature is implemented it would auto-balance when it is possible.

Networktraffic: Sure, it would be better to reduce traffic as much as possible but better more traffic and a healthy state than reduce traffic. (maybe a option to disable auto-balanse make sense for some people).

There should also be a limit for "auto-balance" operations. (at the same time but also if the operation fails x times in a row... etc?)

> 5. Potentially, to minimize the data transfer, we may validate and use the existing replica for the rebuilding process. The reason we haven't done this is it complicates the logic. But we will need to do this eventually.

Absolutly yes, but I think this will be very complicated. It will be easier to just get "auto-balance" than "just update a failed replica" to a healthy state.

> 6.  Minimize the data transfer during the rebuild, or even pause the rebuild if it's only a temporary shutdown of the node. Sounds like we need to think a bit more. We can have a limitation that how many replicas can be rebuilt in a delayed fashion (with specified interval), how many we have to rebuild immediately (e.g. if only 2 replicas and we lost one, we definitely want to start to rebuild immediately). If we support delayed rebuilding, we need to implement the item 5 first.

Should be possible to pause the rebuild in generally if there is planned maitenance for example.

There should be a option how many replicas can be in rebuild state at the same time. (May for big clusters there should be a more complex setting like... how many rebuild process per node?).

There should also be a priority order:
- First rebuild failed volumes (volumes that are not attachable/usable)
- Rebuild volumes with the lowest replica count first (1 of 3 before 2 of 3)
- Rebalance if replicas are on same node

> 7. A limitation on how many volumes should be in rebuilding state at the same time, across the cluster. Or a limitation on what's the maximum bandwidth rebuilding should take.

Absolutly, this may also be useful. I think this is easier than 5. & 6.

**Comment by paalkr** [comment] 2019-05-29 18:41
@vistalba , I absolutely agree with you on all the comments you made in the last post.

Regarding 1, I would like the option to configure (system wide or pr storage class?) a limit for how many replicas for the same volume that are allowed to land on the same node. In my case I would probably set the limit to 0, and run with a degraded volume until a new node is added to the storage cluster and Longhorns adds a replica on the newly added node, to bring the volume back to healthy state.

**Comment by vistalba** [comment] 2019-06-02 18:43
Happens again today. Don't know why but all volumes are "Healthy" again but with replicas on the same node. No rebalance and also no notification.

We should get a fast workaround solution here... :-/
Maybe something like a settings we can activate to avoid replicas build on same node or that he automaticly rebanalce if all nodes are back up. Any other suggestions?

**Comment by yasker** [comment] 2019-06-03 22:32
@vistalba 

> > 1. More than expected replicas are scheduled to the same node when there are no other nodes available. Two replicas on the same node sound OK, but no for three or more. Is that universal? I don't think so. We at least need an option for this.
> 
> I don't think so too. What is the benefit, if two of three replica are on the same node?

One extra replica can help with bit rot, though it's not common and will help only if you have just one working node left. I would prefer a simple option to enable hard anti-affinity rule here.

Filed https://github.com/rancher/longhorn/issues/586 for this.

> 
> > 1. The implication of 1 is if the volume has a number of replicas scheduled successful (e.g. 2), do we allow the volume to be attached even not all of the replicas of volume has been schedulable? Or is item 1 only applies to the rebuilding process?
> 
> From my point of view it should be possible.
> For Example:
> If I have 3 replicas and one node goes offline. Two replicas are still running so the volume is "degarded". In this case it doesn't make sense to rebuild the 3 replica on one of the two remaining nodes... but why you should prevent the usage of the volume?

It's not related to the existing volume. But if you want to create a volume with 3 replicas, but only one of them can be scheduled, do you still want to start that volume (and running the risk of no high availability) or you want the operation to be denied since it doesn't meet some minimal availability? I think mostly you wouldn't want the volume to be started. But if you do think the ideal availability (e.g. 3) is different than the minimal available you can accept temporarily (e.g. 2), then you may want to allow the volume to start. I don't think this usage is common though.

> 
> > 1. Replicas scheduled on the same node are not automatically redistributed to another node if any other node is suitable for redistribution. We can call it auto-balancing. This can trigger far more traffic in the network currently, so it's better to wait for item 5, 6 and 7 to be implemented first.
> 
> This is the main future I like to get. "Self-healing"/auto-balancing or whatever. I think it is more relevant than 1 and 2.
> Why? 4. isn't in place. So as admin I don't know if something goes wrong. I've to check it manually and take some actions if I discover a degraded voulme (or helathy but with replicas on same node).
> If this feature is implemented it would auto-balance when it is possible.
> 
> Networktraffic: Sure, it would be better to reduce traffic as much as possible but better more traffic and a healthy state than reduce traffic. (maybe a option to disable auto-balanse make sense for some people).
> 
> There should also be a limit for "auto-balance" operations. (at the same time but also if the operation fails x times in a row... etc?)

Filed https://github.com/rancher/longhorn/issues/587 for this.
> 
> > 1. Potentially, to minimize the data transfer, we may validate and use the existing replica for the rebuilding process. The reason we haven't done this is it complicates the logic. But we will need to do this eventually.
> 
> Absolutly yes, but I think this will be very complicated. It will be easier to just get "auto-balance" than "just update a failed replica" to a healthy state.

Yeah, we can revisit this later.
> 
> > 1. Minimize the data transfer during the rebuild, or even pause the rebuild if it's only a temporary shutdown of the node. Sounds like we need to think a bit more. We can have a limitation that how many replicas can be rebuilt in a delayed fashion (with specified interval), how many we have to rebuild immediately (e.g. if only 2 replicas and we lost one, we definitely want to start to rebuild immediately). If we support delayed rebuilding, we need to implement the item 5 first.
> 
> Should be possible to pause the rebuild in generally if there is planned maitenance for example.
> 
> There should be a option how many replicas can be in rebuild state at the same time. (May for big clusters there should be a more complex setting like... how many rebuild process per node?).
> 
> There should also be a priority order:
> 
> * First rebuild failed volumes (volumes that are not attachable/usable)
> * Rebuild volumes with the lowest replica count first (1 of 3 before 2 of 3)
> * Rebalance if replicas are on same node

Since normally the requests for rebuilding won't happen at the same time, the priority may not be applied. As a first step, it will be based on a first-come-first-serve basis.

> 
> > 1. A limitation on how many volumes should be in rebuilding state at the same time, across the cluster. Or a limitation on what's the maximum bandwidth rebuilding should take.
> 
> Absolutly, this may also be useful. I think this is easier than 5. & 6.

Filed https://github.com/rancher/longhorn/issues/588 for this.

**Comment by yasker** [comment] 2019-06-03 22:36
@vistalba 

In your latest case, it sounds like you'd lost the connection to one node, which triggered the rebuild process. At least you should be able to see the `limited redundancy` icon in the UI for the volumes.

I've added #586 to the next Longhorn release, but it's not the root cause of your issue. Can you check what's the reason of losing connectivity to a node in your environment? We also want to know what's the common failure reasons and make plans for it.

**Comment by vistalba** [comment] 2019-06-04 05:43
@yasker 
I know it isn't the root cause. It was a issue with host connectivity at my hosting provider.

I know that I can see this in the UI. But there is no notification about that... so the only thing to detect it is when I go to the UI periodically or if I can see the outage in the monitoring.

**Comment by innobead** [comment] 2021-05-21 03:43
This is duplicated of https://github.com/longhorn/longhorn/issues/587. Please follow up on the update from there.

**Closed by innobead** 2021-05-21 03:43 UTC
Labels: area/manager, kind/enhancement
