### ISSUE TITLE
[BUG]Fail to detach the volume when a node is down

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1214] opened 2020-04-17 10:48 UTC
**Describe the bug**
When a node is down, one replica in the volume becomes state `error` with the field `replica.Status.instanceManagerName` wrongly cleaned up. Then Longhorn cannot find out the replica manager and clean up the related instance for this error replica, which results in the volume getting stuck in `detaching` state.

Since there is no related log in the support bundle, we don't know why `replica.Status.instanceManagerName` is wrongly cleaned up here.

**To Reproduce**
Haven't found a way to reproduce it.

**Expected behavior**
1. The field `replica.Status.instanceManagerName` should not be cleared as long as the replica is not `stopped`
2. The volume on the down node can be detached.

**Log**
longhorn-manager-log:
```
2020-04-17T00:28:58.790892498Z time="2020-04-17T00:28:58Z" level=debug msg="Prepare to delete instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c"
2020-04-17T00:28:58.790925742Z time="2020-04-17T00:28:58Z" level=warning msg="Instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c is state error, error message: Instance Manager error"
2020-04-17T00:28:58.790978474Z time="2020-04-17T00:28:58Z" level=warning msg="Instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c crashed on Instance Manager instance-manager-r-b5776f64 at ip-10-100-104-246, try to get log"
2020-04-17T00:28:58.791039122Z time="2020-04-17T00:28:58Z" level=warning msg="cannot get crash log for instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c on Instance Manager instance-manager-r-b5776f64 at ip-10-100-104-246, error invalid Instance Manager instance-manager-r-b5776f64, state: unknown, IP: "
2020-04-17T00:28:58.791140776Z time="2020-04-17T00:28:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c\", UID:\"97544887-0c7d-44c2-b089-ae57fd51e407\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3485845\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c"
2020-04-17T00:28:58.841217911Z time="2020-04-17T00:28:58Z" level=debug msg="Prepare to delete instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c"
2020-04-17T00:28:58.841273727Z time="2020-04-17T00:28:58Z" level=warning msg="Instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c is state error, error message: Instance Manager error"
2020-04-17T00:28:58.841334394Z time="2020-04-17T00:28:58Z" level=warning msg="Instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c crashed on Instance Manager instance-manager-r-b5776f64 at ip-10-100-104-246, try to get log"
2020-04-17T00:28:58.841376258Z time="2020-04-17T00:28:58Z" level=warning msg="cannot get crash log for instance pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c on Instance Manager instance-manager-r-b5776f64 at ip-10-100-104-246, error invalid Instance Manager instance-manager-r-b5776f64, state: unknown, IP: "
2020-04-17T00:28:58.841723401Z time="2020-04-17T00:28:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c\", UID:\"97544887-0c7d-44c2-b089-ae57fd51e407\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3485845\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c"
2020-04-17T00:28:58.849292003Z time="2020-04-17T00:28:58Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-37278709-8841-459d-ac45-9e23165ad15e\", UID:\"b73f9073-adcf-4d92-83f3-52012740a4bd\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3486017\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' Cleanup Volume Attachment on 'NotReady' Node: csi-25d66fad08068f1e21a39d3d036195a700816f9b162d7c04d40359987aad4e3f"
2020-04-17T00:29:23.223235016Z time="2020-04-17T00:29:23Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"pvc-37278709-8841-459d-ac45-9e23165ad15e\", UID:\"b73f9073-adcf-4d92-83f3-52012740a4bd\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"3486017\", FieldPath:\"\"}): type: 'Normal' reason: 'Delete' Cleanup Volume Attachment on 'NotReady' Node: csi-25d66fad08068f1e21a39d3d036195a700816f9b162d7c04d40359987aad4e3f"

......
```
The replica info:
```
- typemeta:
    kind: Replica
    apiversion: longhorn.io/v1beta1
  objectmeta:
    name: pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c
    generatename: ""
    namespace: longhorn-system
    selflink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/replicas/pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c
    uid: 97544887-0c7d-44c2-b089-ae57fd51e407
    resourceversion: "3485845"
    generation: 5
    creationtimestamp: "2020-04-09T04:41:27Z"
    deletiontimestamp: null
    deletiongraceperiodseconds: null
    labels:
      longhornnode: ip-10-100-104-246
      longhornvolume: pvc-37278709-8841-459d-ac45-9e23165ad15e
    annotations: {}
    ownerreferences:
    - apiversion: longhorn.io/v1beta1
      kind: Volume
      name: pvc-37278709-8841-459d-ac45-9e23165ad15e
      uid: b73f9073-adcf-4d92-83f3-52012740a4bd
      controller: null
      blockownerdeletion: null
    initializers: null
    finalizers:
    - longhorn.io
    clustername: ""
    managedfields: []
  spec:
    instancespec:
      volumename: pvc-37278709-8841-459d-ac45-9e23165ad15e
      volumesize: 32212254720
      nodeid: ip-10-100-104-246
      engineimage: longhornio/longhorn-engine:v0.8.0
      desirestate: stopped
      logrequested: false
    enginename: pvc-37278709-8841-459d-ac45-9e23165ad15e-e-2a4d4869
    healthyat: "2020-04-09T04:41:40Z"
    failedat: ""
    diskid: 235508dad94866c6
    datapath: /var/lib/rancher/longhorn/replicas/pvc-37278709-8841-459d-ac45-9e23165ad15e-962945e3
    baseimage: ""
    active: true
  status:
    instancestatus:
      ownerid: ip-10-100-105-72
      instancemanagername: ""
      currentstate: error
      currentimage: ""
      ip: ""
      port: 0
      started: false
      logfetched: false
```

The corresponding instance manager info:
```
- typemeta:
    kind: InstanceManager
    apiversion: longhorn.io/v1beta1
  objectmeta:
    name: instance-manager-r-b5776f64
    generatename: ""
    namespace: longhorn-system
    selflink: /apis/longhorn.io/v1beta1/namespaces/longhorn-system/instancemanagers/instance-manager-r-b5776f64
    uid: 95301e97-fc07-44f2-a1f7-544390b5912f
    resourceversion: "3485835"
    generation: 1
    creationtimestamp: "2020-04-09T04:40:19Z"
    deletiontimestamp: null
    deletiongraceperiodseconds: null
    labels:
      longhorn.io/component: instance-manager
      longhorn.io/instance-manager-image: longhornio-longhorn-instance-manager-v1_20200301
      longhorn.io/instance-manager-type: replica
      longhorn.io/node: ip-10-100-104-246
    annotations: {}
    ownerreferences:
    - apiversion: longhorn.io/v1beta1
      kind: Node
      name: ip-10-100-104-246
      uid: 82d5641a-58d4-4cd1-9153-9da54821eb95
      controller: null
      blockownerdeletion: true
    initializers: null
    finalizers:
    - longhorn.io
    clustername: ""
    managedfields: []
  spec:
    image: longhornio/longhorn-instance-manager:v1_20200301
    nodeid: ip-10-100-104-246
    type: replica
    engineimage: ""
  status:
    ownerid: ip-10-100-105-72
    currentstate: unknown
    instances:
      pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c:
        spec:
          name: pvc-37278709-8841-459d-ac45-9e23165ad15e-r-ec0d4e6c
        status:
          endpoint: ""
          errormsg: Instance Manager error
          listen: ""
          portend: 10029
          portstart: 10015
          state: error
          type: ""
          resourceversion: 0
    ip: ""
    apiminversion: 0
    apiversion: 0
```

**Environment:**
 - Longhorn version: v0.8.0
 - Kubernetes version:
 - Node OS type and version:

**Comment by yasker** [comment] 2020-05-08 18:56
We don't have a reliable way to reproduce this issue at the moment.

**Comment by yasker** [comment] 2020-05-18 16:22
@dnoland1 Do you know if there is a way we can reproduce this? We've committed a fix for an obvious issue but unable to reproduce the issue before the fix.

**Comment by dnoland1** [comment] 2020-05-19 05:31
@yasker I was able to reproduce this issue once after two tries. Used a two node k3s cluster with volumes of a replica of 2. I drained and remove 1st node. Terminated the VM and added a replacement VM. Once the new node's replicas were synced, I drained and removed the second k3s node, terminated the VM, added a replacement. In longhorn I could not remove the down node in the UI and volume was stuck in "Detaching..." state:

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/468462/82288285-0303b300-9957-11ea-9b66-e3225b8af989.png">

**Comment by shuo-wu** [comment] 2020-05-21 13:23
The test plan:
1. Deploy a cluster with 1 master node and 2 worker nodes (**w1, w2**). Deploy Longhorn **v0.8.1**.
2. Create a volume then attach it to **node w2**.
3. Use `kubectl drain` and `kubectl delete node` to remove **node w1 first**. Then power off the corresponding VM.
4. Add a new worker node w3 to the cluster.
5. Wait for the volume replica rebuild.
6. Remove the volume attached node w2. (Should we add a new worker node immediately here?)
7. The volume may get stuck in Detaching.

@dnoland1 Is the above test plan correct? And which Longhorn version were you using for the reproduce?

**Comment by yasker** [comment] 2020-05-21 13:28
@dnoland1 can you help to reproduce it on v1.0.0-rc1 ? It's on branch v1.0.0 of longhorn/longhorn. You can use deploy/longhorn.yaml to deploy.

**Comment by dnoland1** [comment] 2020-05-21 16:54
@shuo-wu I think that test plan should work. I used a 2 node k3s server setup with replica count of 2. For step 6, not sure if you need to immediately add a new worker, can wait a while, or if that's even needed. In my use case, replacement node was added within about 5 minutes. This was originally reproduced on longhorn 0.8.1.

@yasker I tried this on longhorn 1.0.0-rc1. I tried multiple times by cycling through 6 nodes total and could *not* reproduce the problem. As expected, the volume detached/attached fine and did not get stuck as it did with 0.8.1. The replica for the volume went into a failed state and the volume was degraded. Once the new node came online, it rebuilt a new replica and volume went back to healthy. These volumes were being used for cluster monitoring (prometheus/grafana) and during the swapping out of nodes, the volumes were not lost and I could view the full monitoring history.

**Comment by yasker** [comment] 2020-05-21 19:56
@dnoland1 That's great news! We will see if we can write a test case to reproduce it. But that, we will need to add this test to our manual test plan https://github.com/longhorn/longhorn-tests/wiki/Manual-Test-Plan .

**Comment by yasker** [comment] 2020-05-22 23:20
Pre-merged Checklist
* [ ] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [ ] Is the reproduce steps/test steps documented?
* [ ] **If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?
* [ ] **If labeled: area/ui** Has the UI issue filed or ready to be merged?
* [ ] **if labeled: require-doc** Has the necessary document PR submitted or merged?
* [ ] **If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?
* [ ] **if labeled: require-automation-engine** Has the engine integration test been merged?
* [ ] **if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?

**Comment by sowmyav27** [comment] 2020-05-22 23:55
**Reproduced the issue using longhorn `0.8.1`**

- Deploy a 3 node k3s cluster - all nodes have control+worker nodes N1, N2, N3.
- Deploy longhorn 0.8.1
- Create a volume in longhorn, create a pv/pvc
- Create a workload and use the volume created ^^^
- The workload is attached to node N1
- Force drain N1.
- The volume is seen ind `detaching` state

**Instance manager logs:**
```
time="2020-05-22T23:51:51Z" level=warning msg="Instance test-r-5cbb037e is state error, error message: Instance Manager error"
time="2020-05-22T23:51:51Z" level=warning msg="Instance test-r-5cbb037e crashed on Instance Manager instance-manager-r-4c651163 at <ip>, try to get log"
time="2020-05-22T23:51:51Z" level=warning msg="cannot get crash log for instance test-r-5cbb037e on Instance Manager instance-manager-r-4c651163 at <ip>, error invalid Instance Manager instance-manager-r-4c651163, state: unknown, IP: 10.42.1.18"
time="2020-05-22T23:51:51Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"test-r-5cbb037e\", UID:\"45b80505-8f40-4d39-bcd0-246226b03d69\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6805\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-r-5cbb037e"
time="2020-05-22T23:52:21Z" level=debug msg="Prepare to delete instance test-r-5cbb037e"
time="2020-05-22T23:52:21Z" level=warning msg="Instance test-r-5cbb037e is state error, error message: Instance Manager error"
time="2020-05-22T23:52:21Z" level=warning msg="Instance test-r-5cbb037e crashed on Instance Manager instance-manager-r-4c651163 at <ip>, try to get log"
time="2020-05-22T23:52:21Z" level=warning msg="cannot get crash log for instance test-r-5cbb037e on Instance Manager instance-manager-r-4c651163 at <ip>, error invalid Instance Manager instance-manager-r-4c651163, state: unknown, IP: 10.42.1.18"
time="2020-05-22T23:52:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"test-r-5cbb037e\", UID:\"45b80505-8f40-4d39-bcd0-246226b03d69\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6805\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-r-5cbb037e"
time="2020-05-22T23:52:21Z" level=debug msg="Prepare to delete instance test-r-5cbb037e"
time="2020-05-22T23:52:21Z" level=warning msg="Instance test-r-5cbb037e is state error, error message: Instance Manager error"
time="2020-05-22T23:52:21Z" level=warning msg="Instance test-r-5cbb037e crashed on Instance Manager instance-manager-r-4c651163 at <ip>, try to get log"
time="2020-05-22T23:52:21Z" level=warning msg="cannot get crash log for instance test-r-5cbb037e on Instance Manager instance-manager-r-4c651163 at <ip>, error invalid Instance Manager instance-manager-r-4c651163, state: unknown, IP: 10.42.1.18"
time="2020-05-22T23:52:21Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"test-r-5cbb037e\", UID:\"45b80505-8f40-4d39-bcd0-246226b03d69\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6805\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-r-5cbb037e"
time="2020-05-22T23:52:51Z" level=debug msg="Prepare to delete instance test-r-5cbb037e"
time="2020-05-22T23:52:51Z" level=warning msg="Instance test-r-5cbb037e is state error, error message: Instance Manager error"
time="2020-05-22T23:52:51Z" level=warning msg="Instance test-r-5cbb037e crashed on Instance Manager instance-manager-r-4c651163 at <ip>, try to get log"
time="2020-05-22T23:52:51Z" level=warning msg="cannot get crash log for instance test-r-5cbb037e on Instance Manager instance-manager-r-4c651163 at <ip>, error invalid Instance Manager instance-manager-r-4c651163, state: unknown, IP: 10.42.1.18"
time="2020-05-22T23:52:51Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"test-r-5cbb037e\", UID:\"45b80505-8f40-4d39-bcd0-246226b03d69\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"6805\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-r-5cbb037e"
```

**Comment by sowmyav27** [comment] 2020-05-23 00:20
**Validated on longhorn `1.0.0-rc1`**

**Steps:**

- Deploy a 3 node k3s cluster - all nodes have control+worker nodes N1, N2, N3.
- Deploy longhorn 0.8.1
- Create a volume in longhorn, create a pv/pvc
- Create a workload and use the volume created ^^^
- The workload is attached to node N1
- Force drain N1.
- Remove node from cluster
- The volume is seen in detaching state
- But the volume recovered. And is in healthy state
- Volume is accessible

**Longhorn-manager logs:**
```
time="2020-05-23T00:15:17Z" level=warning msg="Instance test-e-5898de8d crashed on Instance Manager instance-manager-e-17bf11cd at <ip>, try to get log"
time="2020-05-23T00:15:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"test-e-5898de8d\", UID:\"cb7f68e0-c3a6-4cf1-bf25-7ded34edf5e9\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5344\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-e-5898de8d"
time="2020-05-23T00:15:17Z" level=error msg="failed to receive log for instance test-r-13d229d7: rpc error: code = NotFound desc = cannot find process test-r-13d229d7"
time="2020-05-23T00:15:17Z" level=warning msg="cannot get crash log for instance test-r-13d229d7 on Instance Manager instance-manager-r-b35fc103 at <ip>, error rpc error: code = NotFound desc = cannot find process test-r-13d229d7"
time="2020-05-23T00:15:17Z" level=error msg="failed to receive log for instance test-e-5898de8d: rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:17Z" level=warning msg="cannot get crash log for instance test-e-5898de8d on Instance Manager instance-manager-e-17bf11cd at <ip>, error rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:17Z" level=debug msg="Prepare to delete instance test-e-5898de8d"
time="2020-05-23T00:15:17Z" level=warning msg="Instance test-e-5898de8d is state error, error message: Instance Manager error"
time="2020-05-23T00:15:17Z" level=warning msg="Instance test-e-5898de8d crashed on Instance Manager instance-manager-e-17bf11cd at <ip>, try to get log"
time="2020-05-23T00:15:17Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"test-e-5898de8d\", UID:\"cb7f68e0-c3a6-4cf1-bf25-7ded34edf5e9\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5344\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-e-5898de8d"
time="2020-05-23T00:15:17Z" level=error msg="failed to receive log for instance test-e-5898de8d: rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:17Z" level=warning msg="cannot get crash log for instance test-e-5898de8d on Instance Manager instance-manager-e-17bf11cd at <ip>, error rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=debug msg="Prepare to delete instance test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-r-13d229d7 is state error, error message: Instance Manager error"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-r-13d229d7 crashed on Instance Manager instance-manager-r-b35fc103 at <ip>, try to get log"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-e-5898de8d is state error, error message: Instance Manager error"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-e-5898de8d crashed on Instance Manager instance-manager-e-17bf11cd at <ip>, try to get log"
time="2020-05-23T00:15:47Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"test-e-5898de8d\", UID:\"cb7f68e0-c3a6-4cf1-bf25-7ded34edf5e9\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5344\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=error msg="failed to receive log for instance test-r-13d229d7: rpc error: code = NotFound desc = cannot find process test-r-13d229d7"
time="2020-05-23T00:15:47Z" level=warning msg="cannot get crash log for instance test-r-13d229d7 on Instance Manager instance-manager-r-b35fc103 at <ip>, error rpc error: code = NotFound desc = cannot find process test-r-13d229d7"
time="2020-05-23T00:15:47Z" level=error msg="failed to receive log for instance test-e-5898de8d: rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=warning msg="cannot get crash log for instance test-e-5898de8d on Instance Manager instance-manager-e-17bf11cd at <ip>, error rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-r-13d229d7 is state error, error message: Instance Manager error"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-r-13d229d7 crashed on Instance Manager instance-manager-r-b35fc103 at <ip>, try to get log"
time="2020-05-23T00:15:47Z" level=error msg="failed to receive log for instance test-r-13d229d7: rpc error: code = NotFound desc = cannot find process test-r-13d229d7"
time="2020-05-23T00:15:47Z" level=warning msg="cannot get crash log for instance test-r-13d229d7 on Instance Manager instance-manager-r-b35fc103 at <ip>, error rpc error: code = NotFound desc = cannot find process test-r-13d229d7"
time="2020-05-23T00:15:47Z" level=debug msg="Prepare to delete instance test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-e-5898de8d is state error, error message: Instance Manager error"
time="2020-05-23T00:15:47Z" level=warning msg="Instance test-e-5898de8d crashed on Instance Manager instance-manager-e-17bf11cd at <ip>, try to get log"
time="2020-05-23T00:15:47Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"test-e-5898de8d\", UID:\"cb7f68e0-c3a6-4cf1-bf25-7ded34edf5e9\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5344\", FieldPath:\"\"}): type: 'Normal' reason: 'Stop' Stops test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=error msg="failed to receive log for instance test-e-5898de8d: rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:47Z" level=warning msg="cannot get crash log for instance test-e-5898de8d on Instance Manager instance-manager-e-17bf11cd at <ip>, error rpc error: code = NotFound desc = cannot find process test-e-5898de8d"
time="2020-05-23T00:15:52Z" level=warning msg="Cannot find the instance status in instance manager instance-manager-r-b35fc103 for the running instance test-r-13d229d7, will mark the instance as state ERROR"
time="2020-05-23T00:15:53Z" level=debug msg="Instance handler updated instance test-e-5898de8d state, old state error, new state stopped"
time="2020-05-23T00:15:53Z" level=debug msg="Instance handler updated instance test-r-13d229d7 state, old state error, new state stopped"
time="2020-05-23T00:15:54Z" level=info msg="Event(v1.ObjectReference{Kind:\"Volume\", Namespace:\"longhorn-system\", Name:\"test\", UID:\"02452570-35b0-48f8-9dc0-9fc5ae1d25df\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5129\", FieldPath:\"\"}): type: 'Normal' reason: 'Detached' volume test has been detached"
time="2020-05-23T00:16:05Z" level=debug msg="Prepare to create instance test-r-13d229d7"
time="2020-05-23T00:16:05Z" level=info msg="Event(v1.ObjectReference{Kind:\"Replica\", Namespace:\"longhorn-system\", Name:\"test-r-13d229d7\", UID:\"20df406b-fd76-4afe-9f7b-1aab2e21c1c0\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5715\", FieldPath:\"\"}): type: 'Normal' reason: 'Start' Starts test-r-13d229d7"
time="2020-05-23T00:16:06Z" level=debug msg="Instance test-r-13d229d7 starts running, IP 10.42.2.18"
time="2020-05-23T00:16:06Z" level=debug msg="Instance test-r-13d229d7 starts running, Port 10000"
time="2020-05-23T00:16:06Z" level=debug msg="Instance handler updated instance test-r-13d229d7 state, old state stopped, new state running"
time="2020-05-23T00:16:07Z" level=debug msg="Prepare to create instance test-e-5898de8d"
time="2020-05-23T00:16:07Z" level=info msg="Event(v1.ObjectReference{Kind:\"Engine\", Namespace:\"longhorn-system\", Name:\"test-e-5898de8d\", UID:\"cb7f68e0-c3a6-4cf1-bf25-7ded34edf5e9\", APIVersion:\"longhorn.io/v1beta1\", ResourceVersion:\"5747\", FieldPath:\"\"}): type: 'Normal' reason: 'Start' Starts test-e-5898de8d"
time="2020-05-23T00:16:07Z" level=debug msg="Instance process test-e-5898de8d had been created, need to wait for instance manager update"
```

**Comment by sowmyav27** [comment] 2020-05-24 01:33
**Was able to reproduce this issue on 0.8.1 using these steps also**


1. Deploy a 3 node k3s cluster - all nodes have control+worker nodes N1, N2, N3.
2. Deploy longhorn 0.8.1
3. Create a 3-replica volume in longhorn, create a pv/pvc/pod. The volume is attached to N1.
4. Write some data to the volume and get the md5sum.
5. Force drain and remove N2, which contains one replica only.
6. Wait for the volume Degraded.
7. Force drain and remove N1, which is the node volume attached to.
8. Wait for the volume detaching then being recovered to healthy state.
9. Validate the volume content. (edited) 

**Validated successfully on 1.0.0-rc1**

Validation: **`PASSED`**

Deploy a 3 node k3s cluster - all nodes have control+worker nodes N1, N2, N3.
2. Deploy longhorn 1.0.0-rc1
3. Create a 3-replica volume in longhorn, create a pv/pvc/pod. The volume is attached to N1.
4. Write some data to the volume and get the md5sum.
5. Force drain and remove N2, which contains one replica only.
6. Wait for the volume Degraded.
7. Force drain and remove N1, which is the node volume attached to.
8. Wait for the volume detaching then being recovered to healthy state.
9. Validate the volume content. (edited)

**Comment by yasker** [comment] 2020-05-26 19:11
Now we can reproduce the issue, so we should be able to understand it better. E.g. what exactly went wrong, and what would triggered the issue. After we understand those, we can see if we need to automate the test case for it.

**Comment by shuo-wu** [comment] 2020-05-27 13:00
The cause of the reported case:
1. The attached node is drained then the engine/replica manager pod gets evicted. 
2. The engine/replica becomes `error`. Then the field `Status.InstanceManagerName` will be unset immediately. 
3. Longhorn receives the `detach` call from the CSI plugin and starts to detach the volume.
4. The node is removed and the instance map in the instance manager won't be updated automatically.
5. Since the field `Status.InstanceManagerName` is empty, the engine/replica controller cannot clean up the entry from the instance map. --> The engine/replica cannot become `stopped`.

One extra corner case:
1. The attached node is drained and the engine manager pod gets evicted. 
2. The engine becomes state `error` then the auto reattachment logic is triggered.
3. The volume gets detached within a very short interval then starts reattaching. (It seems that the longhorn workloads haven't been cleaned up at this moment hence the detach would succeed?) 
4. The node is removed and the attachment cannot succeed.
5. Longhorn receives the `detach` call from the CSI plugin and `v.Spec.NodeID` is unset. 
   But `v.Status.CurrentNodeID` is retained there. Hence the volume will get stuck in `attaching` state.
   (One possible bug: If a volume somehow gets stuck in attaching state, will users be able to detach it manually? Need to double check it later)

**Comment by yasker** [comment] 2020-05-28 14:11
Thanks @shuo-wu . For this issue, we are dealing with the original reported case only. The other corner case found by @shuo-wu will be dealt with in #1363.

**Closed** 2020-05-28 19:38 UTC
Labels: area/manager, bug, priority/2, reproduce/often, require/manual-test-plan
