### ISSUE TITLE
[BUG] When a backup is in progress for 2 different volumes the "volume.cfg" in backupstore is deleted for one of the volumes and backup is stuck 

### ISSUE THREAD

**Issue by sowmyav27** [longhorn/longhorn#1326] opened 2020-05-12 20:21 UTC
**Describe the bug**
When a backup is in progress for a volume the "volume.cfg" in backupstore is deleted

**To Reproduce**

-  Create a backup from a volume
- The backup is stuck in 95% progress with an error: 

<img width="1652" alt="Screen Shot 2020-05-12 at 11 48 37 AM" src="https://user-images.githubusercontent.com/26032343/81741353-4a6bda00-9453-11ea-9776-369b6ba32ca9.png">

**Expected behavior**
Backup should finish successfully. `volume.cfg` in the backup store should not get deleted during a backup process.

**Log**
[longhorn-support-bundle_e53ddce0-01a3-4346-9d15-2759db9c968b_2020-05-12T20-09-25Z.zip](https://github.com/longhorn/longhorn/files/4618260/longhorn-support-bundle_e53ddce0-01a3-4346-9d15-2759db9c968b_2020-05-12T20-09-25Z.zip)

**Note:**
- Backupstore - S3
- Two backups on TWO DIFFERENT volumes were in progress at the same time. One succeeded. Other one failed as mentioned ^^^

**Environment:**
 - Longhorn version: master - 05/12/2020
 - Kubernetes version: 1.17.5  
 - Node OS type and version: - RKE DO Linux nodes

**Comment by yasker** [comment] 2020-05-12 23:09
@sowmyav27 The reproduce steps here are weird... I thought it was due to there were two backups happening at the same time? But it's not mentioned here.

**Comment by sowmyav27** [comment] 2020-05-13 16:19
@yasker Yes. Actually that was the only thing standing out in this use case, when it failed.
Two backups were in progress at the same time. One succeeded. Other one failed as mentioned in the issue https://github.com/longhorn/longhorn/issues/1326#issue-616934363

**Comment by yasker** [comment] 2020-05-13 19:36
@sowmyav27 Can you update that information in the original description? Since it would be crucial to reproduce this problem.

**Comment by joshimoo** [comment] 2020-05-16 01:51
@sowmyav27 To help with the repro case. the logs show that there was a backup delete request executed potentially while the prior backup create request was still not complete.

`
2020-05-12T18:45:41.194758991Z 24.130.226.140 - - [12/May/2020:18:45:40 +0000] "POST /v1/volumes/vol-2?action=snapshotCreate
 
2020-05-12T18:45:41.294533387Z 24.130.226.140 - - [12/May/2020:18:45:41 +0000] "POST /v1/volumes/vol-2?action=snapshotBackup 

2020-05-12T18:45:44.441078747Z 24.130.226.140 - - [12/May/2020:18:45:43 +0000] "GET /v1/backupvolumes?field=volumeName&keyword=vol-2&state=true HTTP/1.1" 200 1260 "https://161.35.135.190/backup/vol-2?field=volumeName&keyword=vol-2&state=true" 

2020-05-12T18:45:47.68290187Z time="2020-05-12T18:45:47Z" level=debug msg="Removed backup backup-b600d77c1f1a4e8c of volume vol-2"

2020-05-12T18:45:47.683127511Z 24.130.226.140 - - [12/May/2020:18:45:47 +0000] "POST /v1/backupvolumes/vol-2?action=backupDelete HTTP/1.1" 200 0 "https://161.35.135.190/backup/vol-2?field=volumeName&keyword=vol-2&state=true" 

2020-05-12T18:45:47.683299088Z time="2020-05-12T18:45:47Z" level=info msg="Start Deleting backup s3://longhorn-sowmya-2@us-east-2/?backup=backup-b600d77c1f1a4e8c&volume=vol-2"

2020-05-12T18:45:48.792861305Z 24.130.226.140 - - [12/May/2020:18:45:48 +0000] "POST /v1/backupvolumes/vol-2?action=backupList HTTP/1.1" 200 121 "https://161.35.135.190/backup/vol-2?field=volumeName&keyword=vol-2&state=true" 

2020-05-12T18:45:49.45840627Z time="2020-05-12T18:45:49Z" level=info msg="Complete deleting backup s3://longhorn-sowmya-2@us-east-2/?backup=backup-b600d77c1f1a4e8c&volume=vol-2"

2020-05-12T18:45:49.72345846Z time="2020-05-12T18:45:49Z" level=error msg="message from backupVolume[vol-2], type[error], content[cannot find backupstore/volumes/68/88/vol-2/volume.cfg in backupstore]"
`

**Comment by joshimoo** [comment] 2020-05-22 04:42
@khushboo-rancher  can you test this issues with the below custom images.
This issue is related to #1341 

Here are the test images, only the engine should be necessary but I like to have them in sync for testing.
Also by having the manager with the default engine deployed, it allows me to run the manager integration tests.
engine: `joshimoo/longhorn-engine:1341-test`
manager: `joshimoo/longhorn-manager:1341-test`

**Comment by joshimoo** [comment] 2020-05-22 22:13
Pre-merged Checklist
* [x] Does the PR include the explanation for the fix or the feature?
* [ ] Is the backend code merged?
* [x] Is the reproduce steps/test steps documented?
* [x] ~~**If the fix introduces the code for backward compatibility** Has an separate issue been filed with the label `release/obsolete-compatibility`?~~
* [x] ~~**If labeled: area/ui** Has the UI issue filed or ready to be merged?~~
* [x] ~~**if labeled: require-doc** Has the necessary document PR submitted or merged?~~
* [x] ~~**If labeled: require-automation-e2e** Has the end-to-end test plan been merged? Have QAs agreed on the automation test case?~~
* [x] ~~**if labeled: require-automation-engine** Has the engine integration test been merged?~~
* [x] ~~**if labeled: require-manual-test-plan-doc** Has the manual test plan been documented?~~

**Comment by joshimoo** [comment] 2020-05-23 01:57
Added section for Backup & Restore Test Scenarios to the [manual test plan](https://github.com/longhorn/longhorn-tests/wiki/Test-Scenarios-for-Backups-&-Restore).

**Comment by sowmyav27** [comment] 2020-05-24 20:30
**Verified on master latest 05/24/2020 - ui tag: `ebd09f9`**

**Steps:**

- create vol `vol-1` and Use it in a workload
- Write data into the volume
- wait for a bunch of data to be written (1GB)
- take a backup(1)
- wait for a bunch of data to be written (1GB)
- take a backup(2)
- immediately request deletion of backup(1)
- verify that backup(2) completes successfully
- verify that backup(1) has been deleted
- Restore from backup(2).
- Verified the checksum of the data is same as the original data

**Closed** 2020-05-24 20:35 UTC
Labels: area/engine, bug, priority/2
