### ISSUE TITLE
[BUG] Sometimes the pods running raw block volumes are stuck in `terminating` to be released due to `Resource busy`

### ISSUE THREAD

**Issue by yasker** [longhorn/longhorn#2474] opened 2021-04-12 20:41 UTC
**Describe the bug**
Sometimes the pods running raw block volumes are stuck in `terminating`. 

This issue only happens at a certain setup.

**To Reproduce**
1. Go to this setup.
2. Deploy https://github.com/longhorn/longhorn/blob/master/examples/block_volume.yaml
3. Once the pod starts running, delete pod `block-volume-test`
4. The pod will get stuck in the `terminating` state.

**Expected behavior**
Pod should be terminated correctly.

**Log**
When the issue happens, the following log can be observed from `/var/log/k3s-server.log`:

```
I0412 20:29:12.714689   44008 reconciler.go:196] operationExecutor.UnmountVolume started for volume "disk-0" (UniqueName: "kubernetes.io/csi/driver.longhorn.io^pvc-de31acda-1874-49b1-b476-1f9fef8285f0") pod "a246feca-31fd-4aa4-8b10-c6aa7686e56b" (UID: "a246feca-31fd-4aa4-8b10-c6aa7686e56b")
W0412 20:29:12.997720   44008 volume_path_handler_linux.go:61] couldn't find loopback device which takes file descriptor lock. Skip detaching device. device path: "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/dev/a246feca-31fd-4aa4-8b10-c6aa7686e56b"
W0412 20:29:12.997796   44008 volume_path_handler.go:219] Warning: Unmap skipped because symlink does not exist on the path: /var/lib/kubelet/pods/a246feca-31fd-4aa4-8b10-c6aa7686e56b/volumeDevices/kubernetes.io~csi/pvc-de31acda-1874-49b1-b476-1f9fef8285f0
E0412 20:29:13.000808   44008 nestedpendingoperations.go:301] Operation for "{volumeName:kubernetes.io/csi/driver.longhorn.io^pvc-de31acda-1874-49b1-b476-1f9fef8285f0 podName:a246feca-31fd-4aa4-8b10-c6aa7686e56b nodeName:}" failed. No retries permitted until 2021-04-12 20:31:14.999961636 +0000 UTC m=+304912.791073109 (durationBeforeRetry 2m2s). Error: "UnmapVo
lume.UnmapBlockVolume failed for volume \"disk-0\" (UniqueName: \"kubernetes.io/csi/driver.longhorn.io^pvc-de31acda-1874-49b1-b476-1f9fef8285f0\") pod \"a246feca-31fd-4aa4-8b10-c6aa7686e56b\" (UID: \"a246feca-31fd-4aa4-8b10-c6aa7686e56b\") : blkUtil.DetachFileDevice failed. globalUnmapPath:/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-de31acda-1
874-49b1-b476-1f9fef8285f0/dev, podUID: a246feca-31fd-4aa4-8b10-c6aa7686e56b, bindMount: true: failed to unmount linkPath /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/dev/a246feca-31fd-4aa4-8b10-c6aa7686e56b: unmount failed: exit status 1\nUnmounting arguments: /var/lib/kubelet/plugins/kubernetes.io/csi/volu
meDevices/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/dev/a246feca-31fd-4aa4-8b10-c6aa7686e56b\nOutput: umount: can't unmount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/dev/a246feca-31fd-4aa4-8b10-c6aa7686e56b: Resource busy\n"
```

**Environment:**
 - Longhorn version: v1.1.1-rc1 (with Harvester v0.2.0-rc1)
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Shipped with Harvester
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: k3s v1.20.4+k3s1
   - Number of management node in the cluster: 3
   - Number of worker node in the cluster: 3
 - Node config
   - OS type and version: k3os v0.19.5-rc1 (HARVESTER) (`cat /etc/issue`)
   - CPU per node: 32
   - Memory per node: 128G
   - Disk type(e.g. SSD/NVMe): SSD
   - Network bandwidth between the nodes: ?
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): bare metal
 - Number of Longhorn volumes in the cluster: 21, only 8 of them are attached.

**Additional context**
### Observed

Longhorn volumes have been correctly detached.

Also `crictl` no longer shows the container that is stuck in the `Terminating` state.

Trying to umount the `/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/a246feca-31fd-4aa4-8b10-c6aa7686e56b` will get:
```
$ umount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-ea706863-e670-43df-a38e-d1749fcb4a16/dev/38fa2acf-6353-458c-9e58-5177f6bfff95
umount: /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-ea706863-e670-43df-a38e-d1749fcb4a16/dev/38fa2acf-6353-458c-9e58-5177f6bfff95: target is busy.
```

Some related command's result 
* Those `fuser` and `lsof` are not the built-in version. Those results are generated using the latest `lsof` and `fuser` that use `apk add` installed inside alpine container then copied over.
```
$ ./fuser -v /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/dev/a246feca-31fd-4aa4-8b10-c6aa7686e56b
                     USER        PID ACCESS COMMAND
/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/dev/a246feca-31fd-4aa4-8b10-c6aa7686e56b:
                     root     kernel mount /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/a246feca-31fd-4aa4-8b10-c6aa7686e56b

$ ./lsof | grep "/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-ea706863-e670-43df-a38e-d1749fcb4a16/dev/38fa2acf-6353-458c-9e58-5177f6bfff95"
lsof: no pwd entry for UID 107
..... [tons of repeated messages, no actual output]
```

There is no device with the same major/minor number in `/dev/longhorn/` directory, or `/dev` directory.

```
$ ls -l /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/a246feca-31fd-4aa4-8b10-c6aa7686e56b
brw-rw---- 0 root root 8, 144 Apr  9 11:01 /var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/publish/pvc-de31acda-1874-49b1-b476-1f9fef8285f0/a246feca-31fd-4aa4-8b10-c6aa7686e56b

$ ls -l /dev/ | grep 144
$ [no result]
$ ls -l /dev/longhorn | grep 144
$ [no result]
```

### Source code of the error message
There is a typo in the error message. The function that throws the error is not `blkUtil.DetachFileDevice` as the error message mentioned, but `blkUtil.UnmapDevice`. See [here](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/volume/util/util.go#L569) for the source code of the caller. See [here](https://github.com/kubernetes/kubernetes/blob/ea0764452222146c47ec826977f49d7001b0ea8c/pkg/volume/util/volumepathhandler/volume_path_handler.go#L201) for the source code of callee.

The code is straightforward. It just tried to unmount the previous bind-mounted block device (was created by using `mount --bind <longhorn_dev> <this_dev>`) but failed to do so due to `Resource busy`.

Ref: https://github.com/rancher/harvester/issues/665

**Comment by yasker** [comment] 2021-04-12 21:42
The next step we can try is to reproduce the issue without Longhorn, e.g. use a loopback device for block volume to see if we can reproduce the issue.

**Comment by shuo-wu** [comment] 2021-04-15 12:46
Set up the local static provisioner in the problematic cluster:
1. Deploy the local static provisioner with fsType `Block`
2. create a loop device:
```
# dd if=/dev/zero of=/mnt/backfile1 bs=1M count=1024
# losetup /dev/loop70 /mnt/backfile1
# ls -alh /dev/loop70
brw-rw---- 1 root disk 7, 70 Apr 15 10:17 /dev/loop70
```
3. Create a StorageClass
4. Create a block device file based on the loop device in the local static provisioner host directory. Then the provisioner will automatically create a PV with mode `BlockVolume` based on the block device file.
```
# mknod /mnt/fast-disks/lp70 b 7 70
# chmod 777 /mnt/fast-disks/lp70
```
```
k get pv
local-pv-9cb306d5                          1Gi        RWO            Delete           Available                   fast-disks                      55m
```

Creating and deleting the test pod & PVC work fine. In other words, we cannot reproduce this issue with the local static provisioner.


I found 2 weird things:
1. There are lots of (around 70) loop devices on the node. 
2. It seems that the deletions for the longhorn test pod, PVC, and PV get stuck. There is no related unmount error in the k3s logs.

**Comment by gitlawr** [comment] 2021-04-19 09:58
@shuo-wu Good catch on the loop devices

Now we have a consistent way to reproduce. This happens when the node has over 8 block device volumes:
1. Deploy a single node Harvester.
2. Deploy a VM with 8 volumes, or deploy the [test yaml](https://github.com/longhorn/longhorn/files/6334881/alotblocks.txt)
3. Remove the pod, then it is stuck in terminating status.



Although loop-control is present, the output of `losetup -a` is limited to 8 entries(and kubelet depends on [losetup output](https://github.com/kubernetes/kubernetes/blob/425e33bd5007905475f31246fb48644e8d038332/pkg/volume/util/volumepathhandler/volume_path_handler_linux.go#L58))
```
$ losetup -V
losetup from util-linux 2.35.2
$ losetup -a
/dev/loop/1: [2049]:652808 (/k3os/system/k3os/v0.19.5-rc.1/k3os), offset 11231241
/dev/loop/6: [0006]:358 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-7d0d7675-5d91-4aa0-ada0-816b65d1f2ae/dev/6b328132-99cb-4a84-ada1-7ffba61d256a)
/dev/loop/4: [0006]:329 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-17d9a09d-9faa-47c3-85fe-21325ced7b38/dev/6b328132-99cb-4a84-ada1-7ffba61d256a)
/dev/loop/2: [2049]:652818 (/k3os/system/kernel/5.4.0-54-generic/kernel.squashfs)
/dev/loop/0: [0006]:271 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3ab21b37-b2b5-4631-8362-376475305fc1/dev/6b328132-99cb-4a84-ada1-7ffba61d256a)
/dev/loop/7: [0006]:315 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-5a0994a6-c53e-4f87-99a6-936e15d7e879/dev/6b328132-99cb-4a84-ada1-7ffba61d256a)
/dev/loop/5: [0006]:253 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-be045ef5-8d27-497c-a50a-e5886d566440/dev/6b328132-99cb-4a84-ada1-7ffba61d256a)
/dev/loop/3: [0006]:301 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-75c29b81-7b12-4e75-84bf-2d110100de1a/dev/6b328132-99cb-4a84-ada1-7ffba61d256a)
$ ls -l /dev/loop*
crw-rw---- 1 root disk 10, 237 Apr 19 08:12 /dev/loop-control
brw------- 1 root root  7,   0 Apr 19 09:40 /dev/loop0
brw------- 1 root root  7,   1 Apr 19 08:10 /dev/loop1
brw-rw---- 1 root disk  7,  10 Apr 19 08:24 /dev/loop10
brw-rw---- 1 root disk  7,  11 Apr 19 08:26 /dev/loop11
brw-rw---- 1 root disk  7,  12 Apr 19 09:29 /dev/loop12
brw-rw---- 1 root disk  7,  13 Apr 19 09:29 /dev/loop13
brw-rw---- 1 root disk  7,  14 Apr 19 09:40 /dev/loop14
brw-rw---- 1 root disk  7,  15 Apr 19 09:40 /dev/loop15
brw------- 1 root root  7,   2 Apr 19 08:10 /dev/loop2
brw------- 1 root root  7,   3 Apr 19 09:40 /dev/loop3
brw------- 1 root root  7,   4 Apr 19 09:40 /dev/loop4
brw------- 1 root root  7,   5 Apr 19 09:40 /dev/loop5
brw------- 1 root root  7,   6 Apr 19 09:40 /dev/loop6
brw------- 1 root root  7,   7 Apr 19 09:40 /dev/loop7
brw-rw---- 1 root disk  7,   8 Apr 19 08:24 /dev/loop8
brw-rw---- 1 root disk  7,   9 Apr 19 08:24 /dev/loop9
```

**Comment by gitlawr** [comment] 2021-04-19 10:04
Comparing to a working envionrment(a single ubuntu node cluster provisioned by rancher AWS node driver)
```
$ losetup -V
losetup from util-linux 2.27.1
losetup -a
/dev/loop0: []: (/var/lib/snapd/snaps/core_6673.snap)
/dev/loop1: []: (/var/lib/snapd/snaps/amazon-ssm-agent_1068.snap)
/dev/loop2: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-897ab2d3-666d-42f7-b75c-d89d47812bfd/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop3: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-b7b9699c-032a-4a98-9c25-80d422d38805/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop4: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-71ce9d2b-cbd7-4bd9-83f9-2f82e43ab7d1/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop5: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-1fff63e9-b15e-48ec-bc91-2f391ddfa565/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop6: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-8d863196-bfde-4e60-8cda-a63c2ebff348/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop7: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-488e1ae0-bcb1-402f-9540-d5c815c2a465/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop8: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-f630d325-759a-4f9a-8ed1-5f1daaaf86be/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
/dev/loop9: []: (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-0e681afd-54c0-4542-8db5-ea90d97e1dbc/dev/ed4d3d2c-921f-46cc-b567-8f1ebc3cb352)
```

**Comment by yasker** [comment] 2021-04-19 21:40
Can it due to k3s's `losetup` is a trimmed-down version? cc @brandond @dweomer

**Comment by brandond** [comment] 2021-04-19 22:49
This seems to be due to k3os including a /dev/loop/ with only 7 devices in it. losetup will prefer the contents of that directory (/dev/loop/N) if it exists, ignoring the devices in /dev/loopN:

```
k3os-22944 [~]# ls -la /dev/loop*
crw-rw---- 1 root disk 10, 237 Apr 19 22:22 /dev/loop-control
brw-rw---- 1 root disk  7,   0 Apr 19 22:22 /dev/loop0
brw-rw---- 1 root disk  7,   1 Apr 19 22:22 /dev/loop1
brw-rw---- 1 root disk  7,  10 Apr 19 22:30 /dev/loop10
brw-rw---- 1 root disk  7,  11 Apr 19 22:30 /dev/loop11
brw-rw---- 1 root disk  7,  12 Apr 19 22:30 /dev/loop12
brw-rw---- 1 root disk  7,  13 Apr 19 22:30 /dev/loop13
brw-rw---- 1 root disk  7,  14 Apr 19 22:30 /dev/loop14
brw-rw---- 1 root disk  7,  15 Apr 19 22:30 /dev/loop15
brw-rw---- 1 root disk  7,  16 Apr 19 22:30 /dev/loop16
brw-rw---- 1 root disk  7,   2 Apr 19 22:30 /dev/loop2
brw-rw---- 1 root disk  7,   3 Apr 19 22:30 /dev/loop3
brw-rw---- 1 root disk  7,   4 Apr 19 22:30 /dev/loop4
brw-rw---- 1 root disk  7,   5 Apr 19 22:30 /dev/loop5
brw-rw---- 1 root disk  7,   6 Apr 19 22:30 /dev/loop6
brw-rw---- 1 root disk  7,   7 Apr 19 22:30 /dev/loop7
brw-rw---- 1 root disk  7,   8 Apr 19 22:30 /dev/loop8
brw-rw---- 1 root disk  7,   9 Apr 19 22:30 /dev/loop9
/dev/loop:
total 0
drwxr-xr-x  2 root root  200 Apr 19 22:22 .
drwxr-xr-x 19 root root 4000 Apr 19 22:30 ..
brw-rw----  1 root disk 7, 0 Apr 19 22:22 0
brw-rw----  1 root disk 7, 1 Apr 19 22:22 1
brw-rw----  1 root disk 7, 2 Apr 19 22:22 2
brw-rw----  1 root disk 7, 3 Apr 19 22:22 3
brw-rw----  1 root disk 7, 4 Apr 19 22:22 4
brw-rw----  1 root disk 7, 5 Apr 19 22:22 5
brw-rw----  1 root disk 7, 6 Apr 19 22:22 6
brw-rw----  1 root disk 7, 7 Apr 19 22:22 7
k3os-22944 [~]# grep loop /proc/mounts
/dev/loop0 /usr squashfs ro,relatime 0 0
/dev/loop1 /usr/lib/modules squashfs ro,relatime 0 0
/dev/loop1 /usr/lib/firmware squashfs ro,relatime 0 0
/dev/loop1 /usr/src squashfs ro,relatime 0 0
/dev/loop2 /mnt/disk2 ext4 rw,relatime 0 0
/dev/loop3 /mnt/disk3 ext4 rw,relatime 0 0
/dev/loop4 /mnt/disk4 ext4 rw,relatime 0 0
/dev/loop5 /mnt/disk5 ext4 rw,relatime 0 0
/dev/loop6 /mnt/disk6 ext4 rw,relatime 0 0
/dev/loop7 /mnt/disk7 ext4 rw,relatime 0 0
/dev/loop8 /mnt/disk8 ext4 rw,relatime 0 0
/dev/loop9 /mnt/disk9 ext4 rw,relatime 0 0
/dev/loop10 /mnt/disk10 ext4 rw,relatime 0 0
/dev/loop11 /mnt/disk11 ext4 rw,relatime 0 0
/dev/loop12 /mnt/disk12 ext4 rw,relatime 0 0
/dev/loop13 /mnt/disk13 ext4 rw,relatime 0 0
/dev/loop14 /mnt/disk14 ext4 rw,relatime 0 0
/dev/loop15 /mnt/disk15 ext4 rw,relatime 0 0
/dev/loop16 /mnt/disk16 ext4 rw,relatime 0 0
k3os-22944 [~]# losetup -a
/dev/loop/1: [2816]:4489 (/k3os/system/kernel/5.4.0-54-generic/kernel.squashfs)
/dev/loop/6: [0024]:2360 (/root/disk6.img)
/dev/loop/4: [0024]:2356 (/root/disk4.img)
/dev/loop/2: [0024]:2351 (/root/disk2.img)
/dev/loop/0: [0024]:368 (/k3os/system/k3os/v0.19.5-rc.1-amd64/k3os), offset 9064457
/dev/loop/7: [0024]:2362 (/root/disk7.img)
/dev/loop/5: [0024]:2358 (/root/disk5.img)
/dev/loop/3: [0024]:2354 (/root/disk3.img)
```

The workaround for this appears to be just deleting /dev/loop, which can be done from a k3os `run_cmd` entry in config.yaml, until it is fixed in a release of k3os. 

```
k3os-11654 [~]# rm -rf /dev/loop
k3os-11654 [~]# losetup -a
/dev/loop1: [2816]:4489 (/k3os/system/kernel/5.4.0-54-generic/kernel.squashfs)
/dev/loop0: [0024]:368 (/k3os/system/k3os/v0.19.5-rc.1-amd64/k3os), offset 9064457
k3os-11654 [~]# for N in {0..15}; do truncate disk$N.img --size 4M; mkfs.ext4 disk$N.img; mkdir -p /mnt/disk$N; mount -o loop disk$N.img /mnt/disk$N; done
...
k3os-11654 [~]# losetup -a
/dev/loop1: [2816]:4489 (/k3os/system/kernel/5.4.0-54-generic/kernel.squashfs)
/dev/loop17: [0024]:2382 (/root/disk15.img)
/dev/loop8: [0024]:2364 (/root/disk6.img)
/dev/loop15: [0024]:2378 (/root/disk13.img)
/dev/loop6: [0024]:2360 (/root/disk4.img)
/dev/loop13: [0024]:2374 (/root/disk11.img)
/dev/loop4: [0024]:2356 (/root/disk2.img)
/dev/loop11: [0024]:2370 (/root/disk9.img)
/dev/loop2: [0024]:2351 (/root/disk0.img)
/dev/loop0: [0024]:368 (/k3os/system/k3os/v0.19.5-rc.1-amd64/k3os), offset 9064457
/dev/loop9: [0024]:2366 (/root/disk7.img)
/dev/loop16: [0024]:2380 (/root/disk14.img)
/dev/loop7: [0024]:2362 (/root/disk5.img)
/dev/loop14: [0024]:2376 (/root/disk12.img)
/dev/loop5: [0024]:2358 (/root/disk3.img)
/dev/loop12: [0024]:2372 (/root/disk10.img)
/dev/loop3: [0024]:2354 (/root/disk1.img)
/dev/loop10: [0024]:2368 (/root/disk8.img)
```

**Comment by guangbochen** [comment] 2021-04-20 01:42
verified after rm the `/dev/loop/N` path the user is able to delete the mounted volumes successfully.

**Comment by brandond** [comment] 2021-04-20 05:38
You should be able to just `rm -rf /dev/loop` in the config.yaml to clean this up on boot.

**Comment by innobead** [comment] 2021-04-20 06:58
Closing, because nothing can be done at the longhorn side. The workaround for k3os has been identified by @brandond . ref: https://github.com/longhorn/longhorn/issues/2474#issuecomment-822839310

**Closed by innobead** 2021-04-20 06:58 UTC
Labels: investigation-needed, kind/bug, kind/environment-issues

**Comment by derekbit** [comment] 2023-10-26 03:34
Workaound

- For the pod stuck in `Terminating ` state
   ```
   kubectl delete pod <name>> --force
   ```

- Detach the problematic block device
   - Find the problematic block device
      ```
      # losetup -a
      /dev/loop1: [1048679]:7340510 (/var/nfs-data/data.img)
      /dev/loop2: [0006]:426 (/var/lib/kubelet/plugins/kubernetes.io/csi/volumeDevices/pvc-3d454e11-5fce-4b0a-86fb-4d2698b84445/dev/f3d02095-1d37-4704-842f-a6bc63d9efb4 (deleted))
      /dev/loop0: [64515]:6816043 (/home/vagrant/blockfile)
      ```
  - Detach the device
     ```
     losetup --detach /dev/loop2
     ```
