### ISSUE TITLE
[FEATURE] Support v2 volume delta replica rebuilding based on snapshot checksum: SPDK part

### ISSUE THREAD

**Issue by innobead** [longhorn/longhorn#5573] opened 2023-03-16 07:47 UTC
## Is your feature request related to a problem? Please describe (👍 if you like this request)

For replica rebuilding, need to support `fresh/full replica building` and `failed differential replica rebuilding`. https://github.com/longhorn/longhorn/issues/5217 will support the fresh rebuilding, but for a failed replica, need to have a more efficient way to reuse healthy data from a failed replica if possible to reduce unnecessary data copy over the wire and    reduce the period of the degraded state.

## Describe the solution you'd like

A clear and concise description of what you want to happen

## Additional context

cc @longhorn/dev-data-plane

**Comment by DamiaSan** [comment] 2023-03-16 08:03
How do we understand which are faulty and which are healthy data? Moreover, what do we mean for faulty data, an entire lvol (snapshot or clone) or even a part of it?

**Comment by innobead** [comment] 2023-03-16 08:08
> How do we understand which are faulty and which are healthy data? Moreover, what do we mean for faulty data, an entire lvol (snapshot or clone) or even a part of it?

Currently, it's COW via lvol, so the unit for us is snapshot. This is what @derekbit asked, how SPDK ensure the data integrity of reach snapshot, if somehow a snapshot of a downstream replica/lvol, can we just rebuild it only instead of copying the whole stack of snapshots.

**Comment by DamiaSan** [comment] 2023-03-16 08:20
With shallow copy we are able to rebuild a single lvol over a different node: what we miss, in addition to the capability of checking data integrity, is a way to change the parent of a snapshot. In this waythe newly created lvol can be put in the middle of the snapshot stack of a logical volume. There is already a comment about this in the rebuild epic #5216

**Comment by innobead** [comment] 2023-03-16 08:24
Exactly there use this issue for both items we would like to clarify and achieve.

**Comment by DamiaSan** [comment] 2023-10-26 08:30
Write an example of how actually SPDK behaves:

- node1 exports lvol1 via nvme-of
- node0 imports lvol1 via nvme attach, creating the bdev nvme1n1
- nvme1n1 is a base bdev of raid0
- raid0 is exported via nvme-of
- a block device /dev/nvme1n1 on the host is connected to raid0

Suppose now that node 1 goes down:

- node0 try to reconnect to node1 for a configured number of times waiting a configured time betweene each attempt and the following
- during this reconnecting time, the write operations over /dev/nvme1n1 are stuck
- if during this reconnecting time node1 doesn't come back online, the bdev nvme1n1 is destroyed and the event is notified to raid0
- raid0 remove nvme1n1 from the list of base devices
- write operations over /dev/nvme1n1 restart without the dead node

**Comment by DamiaSan** [comment] 2023-11-14 06:37
Proposal:  https://github.com/longhorn/longhorn/pull/7031

**Comment by DamiaSan** [comment] 2023-11-30 06:56
Follow disussion https://github.com/longhorn/longhorn/issues/5422#issuecomment-1823820553

**Comment by DamiaSan** [comment] 2024-06-24 08:28
First PR for SPDK, actually without unit test end e2e test, but the development is ready: https://github.com/longhorn/spdk/pull/33

**Comment by derekbit** [comment] 2024-07-12 17:28
The PR developed by @DamiaSan is already reviewed and fixed.
Because of @shuo-wu's limited bandwidth, the delta rebuilding feature will be scheduled to v1.8.0 instead.

cc @shuo-wu @DamiaSan @DamiaSan

**Comment by DamiaSan** [comment] 2024-07-19 06:08
PR for snapshot checksum: https://github.com/longhorn/spdk/pull/35

**Comment by DamiaSan** [comment] 2024-07-22 16:36
PR for delta bitmap test https://github.com/longhorn/spdk/pull/36

**Comment by DamiaSan** [comment] 2024-11-15 15:13
The PR for delta bitmap test https://github.com/longhorn/spdk/pull/36 has been closed because the commits it included has been put directly into the new `longhorn-v24.09` branch, merged with the PR https://github.com/longhorn/spdk/pull/37

**Comment by derekbit** [comment] 2024-12-17 00:26
* [x] Have the backend code been merged (Manager, Engine, Instance Manager, BackupStore etc) (including `backport-needed/*`)?
The PR is at https://github.com/longhorn/spdk/pull/38

* [x] Which areas/issues this PR might have potential impacts on?
Area: snapshot spdk v2-data-engine

* [x] **If labeled: require/LEP** Has the Longhorn Enhancement Proposal PR submitted?
The LEP PR is at https://github.com/longhorn/longhorn/pull/7031

**Comment by derekbit** [comment] 2024-12-18 01:04
@DamiaSan The spdk and go-spdk-helper PRs are merged. Please update the validation steps in the checklist and move it to Ready-For-Testing. Thank you.

**Comment by derekbit** [comment] 2024-12-19 03:25
@DamiaSan Please add validation steps in https://github.com/longhorn/longhorn/issues/5573#issuecomment-2547233650 so that QAs can understand how to validate the ticket.

**Comment by DamiaSan** [comment] 2024-12-19 06:27
> @DamiaSan Please add validation steps in [#5573 (comment)](https://github.com/longhorn/longhorn/issues/5573#issuecomment-2547233650) so that QAs can understand how to validate the ticket.

I have already added it:

_Inside SPDK I have created a test here: https://github.com/longhorn/spdk/blob/002cd0679259c4e4b782d9540441a46e1228d484/test/lvol/snapshot_clone.sh#L927.
What we can do in go-spdk-helper is to reproduce the test above with go-spdk-helper binary's commands instead of rpc.py (wrapped by $rpc_cmd)_

**Comment by derekbit** [comment] 2024-12-19 06:30
> > @DamiaSan Please add validation steps in [#5573 (comment)](https://github.com/longhorn/longhorn/issues/5573#issuecomment-2547233650) so that QAs can understand how to validate the ticket.
> 
> I have already added it:
> 
> _Inside SPDK I have created a test here: [longhorn/spdk@`002cd06`/test/lvol/snapshot_clone.sh#L927](https://github.com/longhorn/spdk/blob/002cd0679259c4e4b782d9540441a46e1228d484/test/lvol/snapshot_clone.sh#L927). What we can do in go-spdk-helper is to reproduce the test above with go-spdk-helper binary's commands instead of rpc.py (wrapped by $rpc_cmd)_

I mean can you provide the go-spdk-helper commands. Then, QA doesn't need to read the script and translate to go-spdk-helper commands.

**Comment by DamiaSan** [comment] 2024-12-19 10:01
> > > @DamiaSan Please add validation steps in [#5573 (comment)](https://github.com/longhorn/longhorn/issues/5573#issuecomment-2547233650) so that QAs can understand how to validate the ticket.
> > 
> > 
> > I have already added it:
> > _Inside SPDK I have created a test here: [longhorn/spdk@`002cd06`/test/lvol/snapshot_clone.sh#L927](https://github.com/longhorn/spdk/blob/002cd0679259c4e4b782d9540441a46e1228d484/test/lvol/snapshot_clone.sh#L927). What we can do in go-spdk-helper is to reproduce the test above with go-spdk-helper binary's commands instead of rpc.py (wrapped by $rpc_cmd)_
> 
> I mean can you provide the go-spdk-helper commands and comprehensive comments. Then, QA doesn't need to read the script and translate to go-spdk-helper commands.

Done.

**Comment by roger-ryao** [comment] 2024-12-20 05:23
Hi @DamiaSan 
     I just followed up on the test steps and executed the script in the `instance-manager` pod on `v1.8.0-rc1` and `master-head`. I got the output below, but I'm not sure if this is the behavior you expected. Could you please take a look?
```bash
instance-manager-2541bef35b1a0a2122b5f7b69ac92299:/ # ./snapshot_checksum.sh 
{
        "bdev_name": "aio_disk"
}
"645d0eb2-d20a-401c-aa06-8df627b4f95a"
{
        "alias": "lvs_test/lvol_test",
        "uuid": "507ea55f-70ae-424d-a345-3ad18cec75fd"
}
"6405f5a4-f3bb-4f82-ac95-a1c7a8402e1f"
No help topic for 'register-snapshot-checksum'
No help topic for 'get-snapshot-checksum'
checksum error
true
true

```

**Comment by derekbit** [comment] 2024-12-20 07:34
> `longhorn-instance-manager/package/Dockerfile` still refers to a commit of SPDK that doesn't contain last developments like lvol flush implementation and snapshot checksum. @derekbit Do I update it?

Sure. Remember to update the deps if there is any update. Thanks.

**Comment by DamiaSan** [comment] 2024-12-20 07:48
> > `longhorn-instance-manager/package/Dockerfile` still refers to a commit of SPDK that doesn't contain last developments like lvol flush implementation and snapshot checksum. @derekbit Do I update it?
> 
> Sure. Remember to update the deps if there is any update. Thanks.

Ok, I will start with `longhorn-spdk-engine`, then `longhorn-instance-manager`.

**Comment by DamiaSan** [comment] 2024-12-20 09:08
@roger-ryao 
Deps updated in master branch and backported in v1.8.x, you can try again.
Thanks

**Comment by roger-ryao** [comment] 2024-12-23 02:59
> @roger-ryao Deps updated in master branch and backported in v1.8.x, you can try again. Thanks

Hi @DamiaSan 
    I tested it on `master-head` and `v1.8.x-head`, but still got the same output.
```bash
{
        "bdev_name": "aio_disk"
}
"09c29a09-bb2b-4c6b-850c-9ca04888ecf1"
{
        "alias": "lvs_test/lvol_test",
        "uuid": "8ef0dfde-8ad2-446f-8a67-7b10b1a50ba8"
}
"a0a911be-3260-4fbc-a3f1-2ba08ae6c574"
No help topic for 'register-snapshot-checksum'
No help topic for 'get-snapshot-checksum'
checksum error
true
true
```
I would like to confirm something: when the test passes successfully, we should not see these error messages:
```bash
No help topic for 'register-snapshot-checksum
No help topic for 'get-snapshot-checksum
```
Is that correct?

**Comment by shuo-wu** [comment] 2024-12-24 03:20
To make sure the test script work fine, the binary `go-spdk-helper` made in the dapper file should be updated as well:
https://github.com/longhorn/longhorn-instance-manager/pull/793

@roger-ryao @DamiaSan

**Comment by roger-ryao** [comment] 2024-12-25 10:27
> To make sure the test script work fine, the binary `go-spdk-helper` made in the dapper file should be updated as well: [longhorn/longhorn-instance-manager#793](https://github.com/longhorn/longhorn-instance-manager/pull/793)
> 
> @roger-ryao @DamiaSan

cc @derekbit

**Comment by derekbit** [comment] 2024-12-27 07:13
@roger-ryao @shuo-wu's PR is merged. Can you revalidate it?

**Comment by roger-ryao** [comment] 2024-12-30 08:02
**Verified on master-head 20241230**

- longhorn `master-head` https://github.com/longhorn/longhorn/commit/7da75642805760929883ff2100ee42c58f117d4c

**Verified on v1.8.0-rc2 20241230**

- longhorn `v1.8.0-rc2` https://github.com/longhorn/longhorn/commit/45d4e8029f686a0a5ffc8a1a68c42361b528dcae


**The test steps**
https://github.com/longhorn/longhorn/issues/5573#issuecomment-2547233650

**Result Passed**

The `snapshot_checksum.sh` script was executed successfully, and the checksum validation passed in both instances. 
Below are the detailed outputs.


`master-head`
```bash
instance-manager-898cc1a5ee4d88112947ec76fee03a75:/ # ./snapshot_checksum.sh 
{
        "bdev_name": "aio_disk"
}
"3a9f5876-3a51-44ca-85dd-7a7eb1c1b42a"
{
        "alias": "lvs_test/lvol_test",
        "uuid": "023b4094-b768-4482-9d73-0399c9994220"
}
"b0239fe3-4a53-4bf5-ac93-7f6d6745bbe8"
true
checksum ok
true
true
```


`v1.8.0-rc2`
```bash
{
        "bdev_name": "aio_disk"
}
"66fe6b10-3c89-49a4-9a63-75de63aa869a"
{
        "alias": "lvs_test/lvol_test",
        "uuid": "956e301b-af5a-4198-9da8-a5b6e27dbf78"
}
"c1579ed5-f730-4853-9e5a-7159b13c52a1"
true
checksum ok
true
true
```

**Closed by roger-ryao** 2024-12-30 08:02 UTC
Labels: kind/feature, highlight, priority/0, require/auto-e2e-test, require/lep, area/performance, area/v2-data-engine, area/replica, area/volume-data-integrity, area/volume-replica-rebuild
