### ISSUE TITLE
[BUG] Removing old instance records after the new IM pod is launched will take 1 minute

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#1363] opened 2020-05-19 05:36 UTC
**Describe the bug**
If an instance manager pod crashes unexpectedly, all related instances will be marked as `ERROR` and the records will be retained for 1 minute even if the new pod is launched.

The issue is found during test #1336

**To Reproduce**
1. Clean up all volumes
2. Create a new volume and attach it to a node
3. Delete the related engine manager pod for the volume
4. The volume will wait for 1 minute to become `detached` then starts reattachment

**Expected behavior**
The volume should be `detached` once the new engine manager pod is `running`.

**Log**
N/A

**Environment:**
 - Longhorn version: v0.8.1
 - Kubernetes version:
 - Node OS type and version:

**Additional context**
The 1-minute wait: https://github.com/longhorn/longhorn-manager/blob/2c8ad8ca03a645cafd0cc645c148dbe6f46da601/controller/instance_manager_controller.go#L818

**Comment by shuo-wu** [comment] 2020-05-22 11:57
This would lead to a bug: The running volume cannot be deleted if the engine manager of the attached volume cannot be launched.

The reproducing steps:
1. Create and attach a volume.
2. Set a large number for the setting `Guaranteed Engine CPU`. e.g., 10
3. Verify all engine/replica manager pods loop in deleting then restarting.
4. Delete the volume. --> The volume will get stuck in `Deleting`.

**Comment by shuo-wu** [comment] 2020-05-28 08:47
Need to retest [the case](https://github.com/longhorn/longhorn/issues/1214#issuecomment-633163795) found in #1214 after fixing this issue. 

Here is the cause:
1. The attached node is drained and the engine manager pod gets evicted.
2. The engine becomes state `error` then the auto reattachment logic is triggered.
3. The volume becomes `detached` within a very short interval then starts reattaching. (It seems that the longhorn workloads haven't been cleaned up at this moment hence the detach would succeed)
4. The node is removed and the attachment cannot succeed.
5. Longhorn receives the detach call from the CSI plugin and `v.Spec.NodeID` is unset.
But `v.Status.CurrentNodeID` is retained there. Hence the volume will get stuck in attaching state.

**Comment by mantissahz** [comment] 2022-11-21 09:36
@shuo-wu Could you reproduce this at master-head?
I could not reproduce it in my local environment.

**Comment by innobead** [comment] 2022-11-21 10:24
> @shuo-wu Could you reproduce this at master-head? I could not reproduce it in my local environment.

Probably this was due to this issue reported in 0.8, quite a long ago and postponed a few times.

**Comment by shuo-wu** [comment] 2022-11-21 12:19
YES, this is a pretty old issue. And there are several big changes after v0.8.1 including the instance manager lifecycle. Not sure if we can directly close this.

**Comment by innobead** [comment] 2022-11-21 12:22
Let's close this first and reopen this when this happens again. 

cc @longhorn/qa

**Closed** 2022-11-21 12:21 UTC
Labels: kind/bug, area/manager, reproduce/always, priority/0, require/automation-e2e
