### ISSUE TITLE
[BUG] Longhorn can't handle restore command error in DR volume incremental restore

### ISSUE THREAD

**Issue by cchien816** [longhorn/longhorn#4049] opened 2022-05-31 04:26 UTC
## Describe the bug
From [e2e](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/139/testReport/junit/tests/test_ha/test_dr_volume_with_restore_command_error_s3_/)

Incremental restore will fail in DR volume when set restore command error

Tested on master-head 20220531
Not happen on V1.2.4

## To Reproduce

1. Set a random backupstore.
2. Create a volume, then create the corresponding PV, PVC and Pod.
3. Write data to the pod volume and get the md5sum
4. Create the 1st backup.
5. Create a DR volume from the backup.
6. Wait for the DR volume restore complete.
7. Create a non-empty directory `volume-delta-<last backup name>.img`
       in one replica directory of the DR volume. This will fail the
       restore command call later.
8. Write data to the original volume then create the 2nd backup.
9. Wait for incremental restore.

In step 9, the incremental restore won'y start or complete immediately without failed replica in DR volume

## Expected behavior

Longhorn can capture and handle the restore command error

- Incremental restore complete.
- DR volume is Degraded
- One failed replica.

## Log or Support bundle

N/A

## Environment

 - Longhorn version:
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: K3s
   - Number of management node in the cluster: 1 
   - Number of worker node in the cluster: 3
 - Node config
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): VMWare
 - Number of Longhorn volumes in the cluster: 1

## Additional context

N/A

**Comment by innobead** [comment] 2022-05-31 05:05
cc @c3y1huang

**Comment by derekbit** [comment] 2022-06-01 02:58
```
time="2022-06-01T02:49:45Z" level=info msg="Prepare to restore backup, backup target: s3://backupbucket@us-east-1/backupstore, backup volume: longhorn-testvol-vigot8-std, requested restored backup name: backup-befb04effb564042" controller=longhorn-engine engine=longhorn-testvol-vigot8-dr-e-5b080655 node=rancher60-worker3
time="2022-06-01T02:49:45Z" level=warning msg="failed to restore backup backup-befb04effb564042 in engine monitor, will retry the restore later: proxyServer=10.42.4.8:8501 destination=10.42.4.8:10000: failed to restore backup s3://backupbucket@us-east-1/backupstore?backup=backup-befb04effb564042&volume=longhorn-testvol-vigot8-std to volume longhorn-testvol-vigot8-std: tcp://10.42.2.9:10015: failed to restore backup data s3://backupbucket@us-east-1/backupstore?backup=backup-befb04effb564042&volume=longhorn-testvol-vigot8-std to snapshot file volume-snap-4f5bab93-14b5-4fa9-9d22-c74c4027649f.img: rpc error: code = Unknown desc = error starting backup restore: error initiating incremental backup restore: failed to clean up the existing file volume-delta-backup-528472e88fe144a6.img before incremental restore: remove volume-delta-backup-528472e88fe144a6.img: directory not empty" controller=longhorn-engine engine=longhorn-testvol-vigot8-dr-e-5b080655 node=rancher60-worker3
E0601 02:49:45.193353       1 engine_controller.go:719] failed to update status for engine longhorn-testvol-vigot8-dr-e-5b080655: failed to restore backup backup-befb04effb564042 in engine monitor, will retry the restore later: proxyServer=10.42.4.8:8501 destination=10.42.4.8:10000: failed to restore backup s3://backupbucket@us-east-1/backupstore?backup=backup-befb04effb564042&volume=longhorn-testvol-vigot8-std to volume longhorn-testvol-vigot8-std: tcp://10.42.2.9:10015: failed to restore backup data s3://backupbucket@us-east-1/backupstore?backup=backup-befb04effb564042&volume=longhorn-testvol-vigot8-std to snapshot file volume-snap-4f5bab93-14b5-4fa9-9d22-c74c4027649f.img: rpc error: code = Unknown desc = error starting backup restore: error initiating incremental backup restore: failed to clean up the existing file volume-delta-backup-528472e88fe144a6.img before incremental restore: remove volume-delta-backup-528472e88fe144a6.img: directory not empty
```

**Comment by cchien816** [comment] 2022-06-06 06:50
Waiting for e2e master build [146](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/146/) result

**Comment by cchien816** [comment] 2022-06-07 02:50
Hello @derekbit 
In build 146 [result](https://ci.longhorn.io/job/public/job/master/job/sles/job/amd64/job/longhorn-tests-sles-amd64/146/testReport/junit/tests/test_ha/test_dr_volume_with_restore_command_error_s3_/) there still have problems with this issue and looks like the fix code merged days ago, could you help to clarify on it? thank you

**Comment by derekbit** [comment] 2022-06-07 03:36
@cchien816 
Not sure why, but it works as expected in my local env and https://ci.longhorn.io/job/private/job/longhorn-tests-regression/1479/console.

**Comment by derekbit** [comment] 2022-06-07 03:55
From the support bundle, the failure is not caused by assertion failure fixed in this PR, but it's not easy to identify the root cause currently.

**Comment by cchien816** [comment] 2022-06-07 06:17
Tested on local environment with s3 and NFS, the result were all passed on local.
On pipeline all failure were due to `wait_for_volume_restoration_start` maybe it's timing issue make case flaky.
I will keep track pipeline result and try reproduce

**Closed** 2022-06-09 01:53 UTC
Labels: kind/bug, area/manager, severity/1, priority/1, kind/regression
