### ISSUE TITLE
[BUG] [v1.5.5-rc1] rwx volume fails to mount on pod

### ISSUE THREAD

**Issue by roger-ryao** [longhorn/longhorn#8344] opened 2024-04-11 04:48 UTC
## Describe the bug

When creating a cluster on AWS using the `ubuntu-jammy-22.04-amd64-server-20240301` image, the kernel version is `6.5.0-1014-aws`.

1.  Testing with Longhorn versions `v1.5.5 and v1.5.4` on this kernel resulted in failure.
2.  However, when installing to Longhorn `v1.6.1` without updating the kernel, the issue was resolved, and RWX volumes could be successfully mounted on pods.
3.  Updated kernel version to `6.5.0-1017-aws` + Longhorn versions `v1.5.5` and `v1.5.4` passed successfully.

After discussing with @derekbit , for this issue, I believe we need to discuss whether to backport the `v1.6.x` NFS-Ganesha version to `v1.5.x` or continue recommending users to upgrade the worker node kernel version.

cc @james-munson @derekbit @innobead 
```
Events:
  Type     Reason                  Age               From                     Message
  ----     ------                  ----              ----                     -------
  Normal   Scheduled               62s               default-scheduler        Successfully assigned default/ubuntu-mountvol0 to ryao-155-w3-86892745-sxf82
  Normal   SuccessfulAttachVolume  25s               attachdetach-controller  AttachVolume.Attach succeeded for volume "vol-0"
  Warning  FailedMount             3s (x6 over 25s)  kubelet                  MountVolume.MountDevice failed for volume "vol-0" : rpc error: code = Internal desc = mount failed: exit status 32
Mounting command: /usr/local/sbin/nsmounter
Mounting arguments: mount -t nfs -o vers=4.1,noresvport,timeo=600,retrans=5,softerr 10.43.19.218:/vol-0 /var/lib/kubelet/plugins/kubernetes.io/csi/driver.longhorn.io/0507c11c5cae88bed1ea382c2b36f2faa90ff78759812a6c34599ece4336fb48/globalmount
Output: mount.nfs: Protocol not supported
```

## To Reproduce

1. create a rwx volume vol-0
2. Create pod mount vol-0

```yaml
kind: Pod
apiVersion: v1
metadata:
  name: ubuntu-mountvol0
  namespace: default
spec:
#  nodeSelector:
#    kubernetes.io/hostname: ryao-160-w2-d001851e-gl4nt # worker node
  containers:
    - name: ubuntu
      image: ubuntu
      command: ["/bin/sleep", "3650d"]
      volumeMounts:
      - mountPath: "/data/"
        name: vol-0
  volumes:
    - name: vol-0
      persistentVolumeClaim:
        claimName: vol-0

```
## Expected behavior

The volume should get mounted normally and the pod start

## Support bundle for troubleshooting
[supportbundle_866bb13a-2fb6-40db-9dce-d70cb7c60c1d_2024-04-11T04-30-11Z.zip](https://github.com/longhorn/longhorn/files/14941435/supportbundle_866bb13a-2fb6-40db-9dce-d70cb7c60c1d_2024-04-11T04-30-11Z.zip)

## Environment

 - Longhorn version: v1.5.5-rc1
 - Impacted volume (PV): 
 - Installation method (e.g. Rancher Catalog App/Helm/Kubectl): Kubectl
 - Kubernetes distro (e.g. RKE/K3s/EKS/OpenShift) and version: `v1.26.15+k3s1`
   - Number of control plane nodes in the cluster: `1`
   - Number of worker nodes in the cluster: `3`
 - Node config
   - OS type and version: `Ubuntu 22.04`
   - Kernel version: `6.5.0-1014-aws`
 - Underlying Infrastructure (e.g. on AWS/GCE, EKS/GKE, VMWare/KVM, Baremetal): `AWS`
 - Number of Longhorn volumes in the cluster: 2

## Additional context

https://github.com/longhorn/longhorn/issues/6857
https://github.com/longhorn/longhorn/issues/6887

**Comment by innobead** [comment] 2024-04-11 05:05
cc @PhanLe1010 @james-munson

**Comment by derekbit** [comment] 2024-04-11 05:41
The issue is caused by the regression in the NFS client of linux kernel`6.5.0-1014-aws` and fixed in `6.5.0-1014-aws`.

I'm fine with either upgrading nfs-ganesha in v1.5.x or recommending users to upgrade the kernel (we don't need to do anything).
Before proceeding, I'd like to check @PhanLe1010 and @james-munson's opinion.

**Comment by derekbit** [comment] 2024-04-11 05:48
BTW, @innobead what's your suggestion for the issue?

**Comment by innobead** [comment] 2024-04-11 05:55
@derekbit what's the regression issue?

**Comment by innobead** [comment] 2024-04-11 05:58
Why does 1.6 work without the kernel fix?

**Comment by derekbit** [comment] 2024-04-11 06:45
> @derekbit what's the regression issue? Is that specific to Ubuntu distro?

We don't know which commit causes the regression because we cannot find the source codes of `6.5.0-1014-aws` for now.

> What's the default kernel of 22.04

`6.5.0-1014-aws` for the AWS Ubuntu 22.04.

> Why does 1.6 work without the kernel fix?

Well, I still have no idea about it.
Not sure if nfs-ganesha v5 is more resilient to the client error

```
[ 1128.246737] nfs4_destroy_session Destroy backchannel for xprt 000000005d180e7b
[ 1128.246741] RPC:        destroy backchannel transport
[ 1128.246742] RPC:        req=00000000667cb67b
[ 1128.246744] RPC:        free allocations for req= 00000000667cb67b
[ 1128.246746] RPC:        backchannel list empty= true
[ 1128.246762] RPC:       xs_tcp_send_request(116) = 0
[ 1128.255951] NFS: destroy per-net callback data; net=f0000000
[ 1128.255990] svc: svc_destroy(NFSv4 callback)
[ 1128.255998] nfs_callback_down: service destroyed
[ 1128.256055] RPC:        destroy backchannel transport
[ 1128.256056] RPC:        backchannel list empty= true
[ 1128.256058] RPC:       xs_destroy xprt 000000005d180e7b
[ 1128.256060] RPC:       xs_close xprt 000000005d180e7b
[ 1128.256090] RPC:       xs_tcp_state_change client 000000005d180e7b...
[ 1128.256092] RPC:       state 4 conn 1 dead 0 zapped 1 sk_shutdown 3
[ 1128.257086] NFS4: Couldn't follow remote path
[ 1128.257088] <-- nfs4_try_get_tree() = -93 [error]
```

**Comment by innobead** [comment] 2024-04-11 06:59
I see. I would recommend users just update the kernel if they encounter this issue using that distro on AWS. Updating nfs ganesha major/minor version in a patch seems risky and not our dependency update policy. @derekbit WDYT?

**Comment by derekbit** [comment] 2024-04-11 07:02
> I see. I would recommend users just update the kernel if they encounter this issue using that distro on AWS. Updating nfs ganesha major/minor version in a patch seems risky and not our dependency update policy. @derekbit WDYT?
> 
> However, we can have a KB if appropriate in this case.

Same here. I recommend updating the kernel as well.

**Comment by innobead** [comment] 2024-04-11 07:10
Sounds good 👍

**Comment by chriscchien** [comment] 2024-04-12 06:36
Close this ticket as we made [documents](https://longhorn.io/kb/troubleshooting-rwx-volume-fails-to-attached-caused-by-protocol-not-supported/) for user to update kernel when encounter RWX mount failure on `Ubuntu 22.04` `6.5.0-1014-aws`

**Closed by chriscchien** 2024-04-12 06:36 UTC
Labels: kind/bug, wontfix, require/knowledge-base, area/volume-rwx, area/upstream, severity/2, require/qa-review-coverage, require/backport
