### ISSUE TITLE
[BUG] A stopped replica on a removed node should not be counted as a healthy replica for the drain setting

### ISSUE THREAD

**Issue by shuo-wu** [longhorn/longhorn#2237] opened 2021-02-05 05:14 UTC
**Describe the bug**
See the `Additional context` in issue https://github.com/longhorn/longhorn/issues/2235
If a detached volume has 2 stopped replicas and a replica is on the deleted node, both replicas will be counted as healthy. Then when the user drains the node containing the left replica of the volume, the setting `allow-node-drain-with-last-healthy-replica=false` won't block the drain and protect the volume data.

**To Reproduce**
1. Create a volume and write some data into it.
2. Detached the volume.
3. Power off/Delete a node containing 1 replica.
4. Drain the node containing another replica. --> The node will be drained, the instance manager pods will be evicted, and the volume will become unavailable

**Expected behavior**
The node draining should be blocked.

**Log**
N/A

**Environment:**
 - Longhorn version: v1.1.0

**Comment by innobead** [comment] 2021-03-20 14:33
remove stale due to the incorrect exempt label

**Comment by weizhe0422** [comment] 2022-12-13 08:10
I try to reproduce with v1.3.2, and I think this issue was fixed since instance-manager PDB protection mechanism. 

It will protect replica instance manager POD if there is no PDB protected healthy POD on another schedulable node.(https://github.com/longhorn/longhorn-manager/blob/900183b785b72edae601bbf53aef8b55a51b3365/controller/instance_manager_controller.go#L700-L759).

Environment
 - K8S cluster: master * 1 + worker *3 (AWS EC2)
 - Longhorn v1.3.2

Reproduce steps
 1. Create a 5G volume with 2 replicas, and detach the volume
   ![image](https://user-images.githubusercontent.com/17548901/207248147-71ef6e8a-c962-4c74-9661-a8dbe656059e.png)
 2. Stop the node containing one of the replicas
   ![image](https://user-images.githubusercontent.com/17548901/207248957-33f9bc55-227f-4073-984f-18795f3ddb76.png)
   ![image](https://user-images.githubusercontent.com/17548901/207249117-57f24f06-1b73-487e-9158-dd937f19cfdb.png)
 3. Attempts to drain the node containing remaining replica

Results
 - All pods on the drained node are evicted except the replica instance manager pod. And the message like below keeps appearing.
    ```shell
    evicting pod longhorn-system/instance-manager-r-b616908e
    error when evicting pods/"instance-manager-r-b616908e" -n "longhorn-system" (will retry after 5s): Cannot evict pod as it would violate the pod's disruption budget.
    ```
  - The node become cordoned. 
    ![image](https://user-images.githubusercontent.com/17548901/207254934-6d886a30-4b50-4f6e-956a-7155b8c991ec.png)
  - The volume is available 
```yaml
apiVersion: longhorn.io/v1beta2
kind: Volume
metadata:
  creationTimestamp: "2022-12-13T07:21:25Z"
  finalizers:
  - longhorn.io
  generation: 4
  labels:
    longhornvolume: pvc-1e66e2b4-03e7-42fc-9ad5-c952972a4343
    recurring-job-group.longhorn.io/default: enabled
    setting.longhorn.io/remove-snapshots-during-filesystem-trim: ignored
    setting.longhorn.io/replica-auto-balance: ignored
    setting.longhorn.io/snapshot-data-integrity: ignored
  name: pvc-1e66e2b4-03e7-42fc-9ad5-c952972a4343
  namespace: longhorn-system
  resourceVersion: "142236"
  uid: 31e76146-e00d-4aba-8dd3-89a0e9b851b8
spec:
  Standby: false
  accessMode: rwo
  backingImage: ""
  baseImage: ""
  dataLocality: disabled
  dataSource: ""
  disableFrontend: false
  diskSelector: []
  encrypted: false
  engineImage: longhornio/longhorn-engine:master-head
  fromBackup: ""
  frontend: blockdev
  lastAttachedBy: ""
  migratable: false
  migrationNodeID: ""
  nodeID: ""
  nodeSelector: []
  numberOfReplicas: 2
  recurringJobs: []
  replicaAutoBalance: ignored
  restoreVolumeRecurringJob: ignored
  revisionCounterDisabled: false
  size: "53687091200"
  snapshotDataIntegrity: ignored
  staleReplicaTimeout: 30
  unmapMarkSnapChainRemoved: ignored
status:
  actualSize: 413777920
  cloneStatus:
    snapshot: ""
    sourceVolume: ""
    state: ""
  conditions:
  - lastProbeTime: ""
    lastTransitionTime: "2022-12-13T07:21:25Z"
    message: ""
    reason: ""
    status: "False"
    type: toomanysnapshots
  - lastProbeTime: ""
    lastTransitionTime: "2022-12-13T07:21:56Z"
    message: ""
    reason: ""
    status: "True"
    type: scheduled
  - lastProbeTime: ""
    lastTransitionTime: "2022-12-13T07:21:25Z"
    message: ""
    reason: ""
    status: "False"
    type: restore
  currentImage: longhornio/longhorn-engine:master-head
  currentNodeID: ""
  expansionRequired: false
  frontendDisabled: false
  isStandby: false
  kubernetesStatus:
    lastPVCRefAt: ""
    lastPodRefAt: ""
    namespace: default
    pvName: pvc-1e66e2b4-03e7-42fc-9ad5-c952972a4343
    pvStatus: Bound
    pvcName: longhorn-volv-pvc-2
    workloadsStatus:
    - podName: volume-test-2
      podStatus: Running
      workloadName: ""
      workloadType: ""
  lastBackup: ""
  lastBackupAt: ""
  lastDegradedAt: ""
  ownerID: rc-k8s-1-rc-w1-489d6c2c-2sj87
  pendingNodeID: ""
  remountRequestedAt: ""
  restoreInitiated: false
  restoreRequired: false
  robustness: unknown
  shareEndpoint: ""
  shareState: ""
  state: detached
```

**Comment by weizhe0422** [comment] 2022-12-13 11:30
According to previous comments, this issue has been fixed by a previous PR [#1299](https://github.com/longhorn/longhorn-manager/pull/1299). Hence closing this issue.

**Comment by innobead** [comment] 2022-12-13 14:15
@weizhe0422 Do we have e2e test case?

**Comment by weizhe0422** [comment] 2022-12-13 15:36
I missed the e2e test case, reopen this issue and continue to follow it.

**Comment by innobead** [comment] 2023-02-16 01:52
The test has been merged.

**Closed by innobead** 2023-02-16 01:52 UTC
Labels: kind/bug, wontfix, area/manager, priority/1, require/automation-e2e, area/volume-data-protection
